### PR TITLE
[18.01] Trackster fixes.

### PR DESCRIPTION
**Pull request by dannon**
This makes the Trackster work again.

The gist here is a reasonably large viz overhaul with the goals of 1) making it work again, and 2) converting the whole thing to classes and modern javascript inheritance.

Implementing ES6 multiple inheritance w/ backbone objects/etc. turned out to be more of a pain than I expected, so I pulled those changes into another branch to keep working on in order to get the core fixes into 18.01.

### CODE REVIEW

**Comment by martenson** [comment]
We have branched the 18.01, if this wants to make it there, it needs to re-target to that branch.

**Comment by dannon** [comment]
It's a bunch of bugfixes; definitely needs to be 18.01; retargeting.

**Comment by dannon** [comment]
Basic local testing passes for me now; I can display and browse, change modes, etc.

**Comment by jmchilton** [comment]
Thanks @dannon!

**Pull request merged**
