### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by galaxybot**
Run `make update-dependencies`.

### CODE REVIEW

**Comment by nsoranzo** [comment]
The new 1.0.0 version of [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/) moves towards a Docker-based approach for smoke and production-like testing while the previous version was just a shim for [`celery.contrib.pytest`](https://docs.celeryq.dev/en/latest/userguide/testing.html), which is based on mocking for unit and integration testing.
The new version also brings in a number of extra dependencies (debugpy, decorator, docker, py, pytest-docker-tools, pywin32, retry), which we don't currently need.
Is there interest in the new functionalities of pytest-celery, or should we just replace it with `celery[pytest]` ?

**Comment by nsoranzo** [comment]
Ready to review/merge.

**Comment by mvdbeek** [comment]
Thank you!

**Comment by davelopez** [comment]
@nsoranzo after this change, when VSCode tries to discover the tests I'm getting:
```
ValueError: Plugin already registered under a different name: celery.contrib.pytest=<module 'celery.contrib.pytest' from '/home/dlopez/dev/galaxy/.venv/lib/python3.11/site-packages/celery/contrib/pytest.py'>
```

Before this change you could run: `pytest --collect-only lib/galaxy_test` and it will succeed but now it fails and makes debugging tests in VSCode not possible :disappointed: 

Any idea how to fix that? :pray:

**Comment by mvdbeek** [comment]
Did you install the dev dependencies ? `pip install -r lib/galaxy/dependencies/dev-requirements.txt` or use the run_test.sh or run.sh wrapper to get them automatically.

**Comment by davelopez** [comment]
I installed them with `pip install -r lib/galaxy/dependencies/dev-requirements.txt`

**Comment by nsoranzo** [comment]
> Is it working for you if you run: `pytest --collect-only lib/galaxy_test`?

Yes, works fine for me. Maybe try to recreate the `.venv`?

**Comment by mvdbeek** [comment]
Might also be worth checking that pytest is coming from the venv ... my zsh occasionally needs a `rehash`.

**Comment by davelopez** [comment]
> Yes, works fine for me. Maybe try to recreate the .venv?

That did the trick! Thank you both!

**Comment by nsoranzo** [comment]
Replicated in another venv, just `pip uninstall pytest-celery` and it works.

**Pull request merged**
