### PR TITLE
Reports tool trends

### PR DESCRIPTION
**Pull request by OldWorldBoa**
Added JQuery sparklines to the galaxy reports webapp.

### CODE REVIEW

**Comment by martenson** [comment]
this is a continuation of https://github.com/galaxyproject/galaxy/pull/353

**Comment by martenson** [comment]
visiting `Errors per tool` or `Jobs per tool` produces the following error: https://gist.github.com/martenson/adea8caabc1d02c23bc4

visiting `Jobs per user` produces https://gist.github.com/martenson/4eeba754db39ab208d27

**Comment by OldWorldBoa** [comment]
I was unable to reproduce your errors. This is the second time that has happened. Do you think it has something to do with my using mysql as opposed to postgres? Perhaps pointing my instance of galaxy to your database would let me find these errors in advance.

**Comment by OldWorldBoa** [comment]
I've found a postgres database to test on now and I'm getting the same errors, heads up.

**Comment by martenson** [comment]
Sorry I did not report I am using Postgres. I would consider it standard for any instance that utilizes reports though.

**Comment by OldWorldBoa** [comment]
No worries. I'll make sure to test on both database types from now on.

**Comment by OldWorldBoa** [comment]
I've accidentally added files here that shouldn't be. I'll open this up once I'm done fixing it.

**Pull request closed without merging**
