### PR TITLE
make the upload 'Start' button green when enabled

### PR DESCRIPTION
**Pull request by martenson**
I have seen numerous times how people struggle to find the correct
button when uploading. This should help them.
Also added some missing braces.
ping @guerler 
screenshot 2015-08-07 15 03 11

### CODE REVIEW

**Comment by hexylena** [comment]
+1!

I wrote a "how to use galaxy 001" the other day, the button was not clear
without a large red circle.

fre. 7. aug. 2015, 20.05 skrev Martin Cech notifications@github.com:

**Comment by dannon** [comment]
I like this a lot, thanks @martenson!  Can we make one tweak and define it in the .less and use it as a standard style/class instead of inline?

**Comment by martenson** [comment]
screenshot 2015-08-07 15 18 42

**Comment by jxtx** [comment]
Thar we go, +1

**Comment by nturaga** [comment]
+1

**Pull request merged**
