### PR TITLE
Remove redirect mako from tool runner controller

### PR DESCRIPTION
**Pull request by guerler**
This PR removes the `redirect.mako` used in the `tool_runner` controller. Instead of redirecting through the client the backend controller now directly performs the redirect. This controller function should probably be entirely removed in the near future since it is/should not be used anywhere.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
> This controller function should probably be entirely removed in the near future since it is/should not be used anywhere.

It's already unused, I'd get rid of it as part of this PR.

**Comment by guerler** [comment]
Awesome, thanks for chiming in @nsoranzo, I was not entirely sure.

**Comment by jmchilton** [comment]
In tools/actions/__init__.py.

```
        if "REDIRECT_URL" in incoming:
            # Get the dataset - there should only be 1
            for name in inp_data.keys():
                dataset = inp_data[name]
            redirect_url = tool.parse_redirect_url(dataset, incoming)
            # GALAXY_URL should be include in the tool params to enable the external application
            # to send back to the current Galaxy instance
            GALAXY_URL = incoming.get("GALAXY_URL", None)
            assert GALAXY_URL is not None, "GALAXY_URL parameter missing in tool config."
            redirect_url += f"&GALAXY_URL={GALAXY_URL}"
            # Job should not be queued, so set state to ok
            job.set_state(app.model.Job.states.OK)
            job.info = f"Redirected to: {redirect_url}"
            trans.sa_session.add(job)
            trans.sa_session.flush()
            trans.response.send_redirect(
                url_for(controller="tool_runner", action="redirect", redirect_url=redirect_url)
            )
```

I preferred the conservative approach would have been to stick with just removing the makos. But I will be honest I don't know a ton about how various data source and external integrations are working.

xref https://github.com/galaxyproject/galaxy/commit/b4890c1bbb009b93dd548bfa138c13353d0b3c1f

**Comment by guerler** [comment]
@jmchilton thank you for catching that. I replaced the call by directly redirecting to the url instead of going through the action. Do you think that's ok?

**Comment by jmchilton** [comment]
I have no great insight  - my gut says probably. The advantage of going through the controller is that the data sources / external tools might do URL path manipulation to get access to other tool_runner endpoints - but it doesn't look like you can run a tool through that controller anymore... so I assume what you've done is very likely okay. The advantage of trying to do something very likely to be close to right is that people will report bugs if something breaks instead of assuming we've just dropped the functionality - so I do appreciate you trying to maintain this behavior. Thanks so much!

**Review by jmchilton — APPROVED** [review]

**Comment by bgruening** [comment]
> Update: I am not sure url_for even works in the FastAPI context laughing - you may have fixed a bug we introduced last year with this approach heart.

@davelopez might be interested in this :)

**Comment by davelopez** [comment]
Yep, plain `url_for` does not work on FastAPI context it will just return a deprecation message :laughing: but as far as I know, it should still work in legacy routes thanks to https://github.com/galaxyproject/galaxy/pull/14066

**Pull request merged**
