### PR TITLE
[PROCEDURES] Re-license under MIT all work from 2021-04-07 onwards

### PR DESCRIPTION
**Pull request by nsoranzo**
This is allowed because since 2021-04-06 (when PR https://github.com/galaxyproject/galaxy/pull/11777 was merged) our pull request template contains a checkbox asking the contributor to allow the Galaxy committers to license all their contributions to the core galaxy codebase under the MIT license.

Explicit approval to this change will be sought from the few persons who:
- opened a PR before 2021-04-07 which was merged after this date, and
- haven't already agreed to the re-licensing in a later PR.

This is an interim step to a full re-licensing under MIT. A future PR will change `LICENSE.txt` again to add MIT to the older code, asking for approval from as many contributors as possible.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by dannon — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Comment by nsoranzo** [comment]
Ping @VJalili @anuprulez , can you please approve if you agree to re-license your contributions to this repository under the [MIT license](https://opensource.org/licenses/MIT)?

**Review by blankenberg — APPROVED** [review]

**Review by VJalili — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Review by davelopez — APPROVED** [review]

**Review by nuwang — APPROVED** [review]

**Review by natefoo — APPROVED** [review]

**Comment by anuprulez** [comment]
> Ping @VJalili @anuprulez , can you please approve if you agree to re-license your contributions to this repository under the [MIT license](https://opensource.org/licenses/MIT)?

I think I am not listed as a reviewer. Is there a way to approve the PR without being one of the reviewers? Thanks!

**Review by anuprulez — APPROVED** [review]

**Comment by nsoranzo** [comment]
Thanks @anuprulez !

**Comment by fubar2** [comment]
No idea if any lines of code of mine remain in the codebase, but wondering how us former contributors can most efficiently give consent to a change in the licence? I could make a dummy PR if necessary. 

Just in case this works, I **_hereby approve of any and all of my code contributions to the Galaxy source code being relicenced under the MIT licence._**

**Pull request merged**
