### PR TITLE
Update gsummary.py to be modern conda compatible

### PR DESCRIPTION
**Pull request by Petraea**
Hi there,
It looks like the Summary_Statistics1 tool no longer properly executes in the 17.09 branch of galaxy, as the conda rpy2 module defaultly uses python3.6. As such, this code needs to be able to execute in python3, and all file writes need a bytes object rather than a str.

Update:
It ought to be possible to require a python2.7 build in the conda module, however rpy2 version 2.9.0 appears to have no python2 builds, and so some kind of compatibility is going to be required at some point.

### CODE REVIEW

**Comment by bgruening** [comment]
@Petraea indeed. I just checked our server and we have this included:
```
    <requirement type="package" version="2.7">python</requirement>
    <requirement type="package" version="2.7.8">rpy2</requirement>
```
I think your fix is better.

**Comment by bgruening** [comment]
@nsoranzo do you think this is ok?

**Comment by nsoranzo** [comment]
What about opening the temp file in text mode at line 62 instead:

```python
tmp_file = tempfile.NamedTemporaryFile('w+t')
```

**Comment by Petraea** [comment]
@nsoranzo Oh, that's much more elegant. Let me just test that...

**Comment by Petraea** [comment]
Looks good, and is backwards compatible - just checked in 2.7.12.

**Comment by nsoranzo** [comment]
@Petraea Actually this was already fixed in the `release_18.01` and `dev` branch with PR https://github.com/galaxyproject/galaxy/pull/5043 (`w+` is equivalent to `w+t`), we can backport it to 17.09 if you need this.

**Comment by Petraea** [comment]
Ah - hence the merge.

If possible, I'd like to request that backporting.

**Comment by Petraea** [comment]
Backported in #5639  to 17.09

**Pull request closed without merging**
