### PR TITLE
Fuctional test case for testing column names as meta-data

### PR DESCRIPTION
**Pull request by yhoogstrate**
https://github.com/galaxyproject/galaxy/issues/2941

### CODE REVIEW

**Comment by nsoranzo** [comment]
@yhoogstrate I think you should also add `metadata_column_names.xml` to `test/functional/tools/samples_tool_conf.xml`

**Comment by nsoranzo** [comment]
The test failed, but I think you expected that.

**Comment by yhoogstrate** [comment]
`[metadata_column_names] failed, expected [First,2.tabular] but found [[u'First', u'2.tabular']]` - Yep, but it's a good starting point for a solution.

**Comment by nsoranzo** [comment]
@yhoogstrate It's basically the same error @peterjc got. You may want to look at method `_verify_metadata()` in `test/base/interactor.py` .

**Comment by jmchilton** [comment]
Cool - I'll try to fix this.

**Comment by nsoranzo** [comment]
Thanks @yhoogstrate  and @jmchilton!

**Comment by peterjc** [comment]
Thanks - I look forward to using this for https://github.com/peterjc/galaxy_blast/issues/84

**Pull request merged**
