### PR TITLE
Keep select field open for multi select

### PR DESCRIPTION
**Pull request by guerler**
This PR keeps the drop down of multi-select fields open and makes it easier to rapidly select a subset of options. It is a potential remedy for the issue described in: https://trello.com/c/TSB0sIvD/2787-ui-optional-revert-to-ctrl-shift-multiselect-widget-for-hundreds-of-options-in-huge-data-column-parameters.

### CODE REVIEW

**Comment by guerler** [comment]
Did you try the full patch including: https://github.com/guerler/galaxy/commit/f57d91794917ac7ee057585addc1891e81c40fdf?

**Comment by fubar2** [comment]
Thanks @guerler - yes, just added the second part and yes, that seems to scale much better.
AFAIK it doesn't obviously break anything although it is a slight change in UI behaviour. 
What's the "right" way to procede with UI changes?
@bgruening do you have time to test this?

**Comment by guerler** [comment]
@fubar2 Thanks for testing it.

**Comment by martenson** [comment]
This is related, right? https://github.com/galaxyproject/galaxy/pull/1025

**Comment by guerler** [comment]
@martenson Yes, somewhat.

**Comment by carlfeberhard** [comment]
A suggestion: instead of altering the select2 library directly, you should be able to set `Select2.class.multi.prototype.onSelect` from a separate file after the library is loaded. This would allow us to update the library without having to re-apply these changes each time.

**Comment by guerler** [comment]
This patch will not work for Select2 +4.0, so we will have to re-apply it either way. However, the patch fixes a known issue and there might be an official fix for it at one point: https://github.com/select2/select2/issues/2629.

**Pull request merged**
