### PR TITLE
Add history navigation options for dataset frames to scratch book

### PR DESCRIPTION
**Pull request by guerler**
This PR enhances the scratch book viewer such that frames may now contain optional header icons which can be customized with regard to the frame content. This functionality is demonstrated by adding basic history navigation icons for dataset display frames. This may serve as basis for future refinements of the navigation behavior, mime type detection, data type filtering, and possibly history caching. ping @bgruening

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
I love this! So good for imaging!

**Comment by martenson** [comment]
If you provide a screenshot with the PR, you might get some more feedback on UX @guerler .

**Comment by guerler** [comment]
Makes sense. Here is a screenshot of the revised scratch book frame for the display of datasets:
framenavigation

**Comment by martenson** [comment]
good idea & execution! 👍

**Comment by guerler** [comment]
It was @bgruening's idea, and I agree I like it too (:

**Comment by bgruening** [comment]
Thanks @guerler! :)

**Pull request merged**
