### PR TITLE
Add id to the upload button.

### PR DESCRIPTION
**Pull request by bgruening**
This will help to create interactive tours.

### CODE REVIEW

**Comment by guerler** [comment]
Does selecting with '#upload-button > a' work for you?

**Comment by martenson** [comment]
@guerler should be `'.upload-button > a'` I think

**Comment by bgruening** [comment]
Yes, this is what I do now. But this is not easy to do for a newcomer and I guess we want to make this work as easy as possible. Let me know if there are any disadvantages and I will close this PR.

**Comment by martenson** [comment]
If we expect the newcomer to not now the css selectors I do not see the addition of id helping much. We would need to provide the mapping of `selector <--> human readable description of area` anyways.

**Comment by jmchilton** [comment]
I'm :+1: on this for sure, we need to do that mapping - but the goal of that mapping should be to make it pretty simple - just falling back to ids whenever possible.

**Comment by bgruening** [comment]
@martenson is there any disadvantage of using ID's? I'm not going to fight for this, just want to know if there is anything wrong with a unique ID for such important UI elements.

**Comment by martenson** [comment]
It is difficult for me to understand adding markup without seeing the use of it. The div itself has class `upload-button` which is probably the element/area you want to target if you are showing people the place where to click. If you want to programatically expand the modal I think you should trigger the proper event on the view. I am unsure about this addition (mostly because of future on-demand-markup additions, not this single instance obviously)

**Comment by martenson** [comment]
ping @carlfeberhard

**Comment by dannon** [comment]
+1 to just using upload-button class itself, and not adding a redundant identifier to the link.

**Comment by carlfeberhard** [comment]
@martenson AFAIK it's considered a best practice to avoid id use as much as possible. I think that's mainly about the CSS rule confusion and specificity wars that happen when they're used, though.

That said, if the user never has to see it and if another selector would work, I'm not sure why it's needed here. I think it may be a mistake to add markup to lower the barrier of entry to creating a tour.

Up to you guys.

**Comment by bgruening** [comment]
Ok, I will stick to the long version then.

**Pull request closed without merging**
