### PR TITLE
Randomlines

### PR DESCRIPTION
**Pull request by pravs3683**
Modified Random Lines tool to add new features (see new feature points below), along with keeping the original functionality.

Optional features:
1) Can take an additional subset file with the list of entries that user wants to ignore.
2) Provide a number for how many random lines to be picked. OR
3) Can take the number equal to the number of lines in the subset file.

### CODE REVIEW

**Comment by pravs3683** [comment]
I am not sure why some of the tests are failing. I tried planemo lint on my local system and it passed. Can anyone please suggest?

**Comment by martenson** [comment]
@pravs3683 if you click on the detail of the check, you will see why it fails: https://travis-ci.org/galaxyproject/galaxy/jobs/489626152

**Comment by martenson** [comment]
@galaxybot test this

**Comment by pravs3683** [comment]
Hello Martin,

We did the planemo test on our computers and it passes successfully. Can
you please suggest what else should we check?

Thanks,
Praveen

**Comment by martenson** [comment]
your code is failing python lint:

```
./tools/filters/random_lines_two_pass.py:94:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:104:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:118:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:127:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:147:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:159:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:162:1: W293 blank line contains whitespace
./tools/filters/random_lines_two_pass.py:165:1: W293 blank line contains whitespace
```

**Comment by pravs3683** [comment]
Thank you, Martin!

**Pull request closed without merging**
