### PR TITLE
added config_diff.py to detect new configuration options in .ini files.

### PR DESCRIPTION
**Pull request by scholtalbers**
This script generates a tabular diff between two given ini files. The original purpose being to find new options in the ``galaxy.ini.sample`` file that are not yet in the users ``galaxy.ini`` file.

### CODE REVIEW

**Comment by bgruening** [comment]
@scholtalbers Just as small tip, have a look at `meld` to see the differences.

**Comment by scholtalbers** [comment]
thx @bgruening, meld seems indeed the better tool. This script was created with 'my horse blinkers on', if that translates to english...

**Comment by bgruening** [comment]
I at least  got it ;)

**Comment by jmchilton** [comment]
Can we close this because meld is probably the better tool then? I appreciate the contribution - but if we don't need to maintain this file and steer people away from meld - that would be better I guess.

**Pull request closed without merging**
