### PR TITLE
Style.move

### PR DESCRIPTION
**Pull request by carlfeberhard**
Moving less files from `static/style/src` to `client/galaxy/style`.

Less is now recompiled to css using:
`grunt style` (from the `<galaxy>/client` directory)

The entire `source_material` directory was removed as were the supporting files for the style build system in `static/style`. I did not see them being used, but let me know if those were needed.

### CODE REVIEW

**Comment by jxtx** [comment]
source_material contains scripts and stuff used to create images -- icons,
the spinner, and the workflow node inputs/outputs. These are not archived
anywhere else so we should probably keep them somewhere. I think all of
them are still used.

On Monday, May 4, 2015, carlfeberhard notifications@github.com wrote:

> carlfeberhard wants to merge 4 commits into galaxyproject:dev from
> carlfeberhard:style.move:
> 
> Less is now recompiled to css using:
> grunt style (from the <galaxy>/client directory)
> 
> The entire source_material directory was removed as were the supporting
> files for the style build system in static/style. I did not see them
> 
> ## being used, but let me know if those were needed.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/galaxyproject/galaxy/pull/208
> Commit Summary
> - Client build: move static/style/src to client/galaxy/style and merge
>   node/grunt build scripts (you should now use 'grunt style' to re-build css)
> - Client build, styles: remove source_material directory
> - Client build: break up grunt tasks into separate files for clarity
> - Client build, styles: remove style build system from static/style
> 
> File Changes
> - _M_ client/GruntFile.js
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-0 (189)
> - _M_ client/README.md
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-1 (11)
> - _R_ client/galaxy/style/blue_colors.ini
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-2 (0)
> - _R_ client/galaxy/style/less/autocomplete_tagging.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-3 (0)
> - _R_ client/galaxy/style/less/base.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-4 (0)
> - _R_ client/galaxy/style/less/bootstrap.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-5 (0)
> - _R_ client/galaxy/style/less/bootstrap/alerts.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-6 (0)
> - _R_ client/galaxy/style/less/bootstrap/badges.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-7 (0)
> - _R_ client/galaxy/style/less/bootstrap/bootstrap.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-8 (0)
> - _R_ client/galaxy/style/less/bootstrap/breadcrumbs.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-9 (0)
> - _R_ client/galaxy/style/less/bootstrap/button-groups.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-10 (0)
> - _R_ client/galaxy/style/less/bootstrap/buttons.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-11 (0)
> - _R_ client/galaxy/style/less/bootstrap/carousel.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-12 (0)
> - _R_ client/galaxy/style/less/bootstrap/close.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-13 (0)
> - _R_ client/galaxy/style/less/bootstrap/code.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-14 (0)
> - _R_ client/galaxy/style/less/bootstrap/component-animations.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-15 (0)
> - _R_ client/galaxy/style/less/bootstrap/dropdowns.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-16 (0)
> - _R_ client/galaxy/style/less/bootstrap/forms.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-17 (0)
> - _R_ client/galaxy/style/less/bootstrap/glyphicons.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-18 (0)
> - _R_ client/galaxy/style/less/bootstrap/grid.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-19 (0)
> - _R_ client/galaxy/style/less/bootstrap/input-groups.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-20 (0)
> - _R_ client/galaxy/style/less/bootstrap/jumbotron.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-21 (0)
> - _R_ client/galaxy/style/less/bootstrap/labels.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-22 (0)
> - _R_ client/galaxy/style/less/bootstrap/list-group.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-23 (0)
> - _R_ client/galaxy/style/less/bootstrap/media.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-24 (0)
> - _R_ client/galaxy/style/less/bootstrap/mixins.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-25 (0)
> - _R_ client/galaxy/style/less/bootstrap/modals.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-26 (0)
> - _R_ client/galaxy/style/less/bootstrap/navbar.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-27 (0)
> - _R_ client/galaxy/style/less/bootstrap/navs.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-28 (0)
> - _R_ client/galaxy/style/less/bootstrap/normalize.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-29 (0)
> - _R_ client/galaxy/style/less/bootstrap/pager.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-30 (0)
> - _R_ client/galaxy/style/less/bootstrap/pagination.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-31 (0)
> - _R_ client/galaxy/style/less/bootstrap/panels.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-32 (0)
> - _R_ client/galaxy/style/less/bootstrap/popovers.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-33 (0)
> - _R_ client/galaxy/style/less/bootstrap/print.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-34 (0)
> - _R_ client/galaxy/style/less/bootstrap/progress-bars.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-35 (0)
> - _R_ client/galaxy/style/less/bootstrap/responsive-utilities.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-36 (0)
> - _R_ client/galaxy/style/less/bootstrap/scaffolding.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-37 (0)
> - _R_ client/galaxy/style/less/bootstrap/tables.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-38 (0)
> - _R_ client/galaxy/style/less/bootstrap/theme.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-39 (0)
> - _R_ client/galaxy/style/less/bootstrap/thumbnails.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-40 (0)
> - _R_ client/galaxy/style/less/bootstrap/tooltip.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-41 (0)
> - _R_ client/galaxy/style/less/bootstrap/type.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-42 (0)
> - _R_ client/galaxy/style/less/bootstrap/utilities.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-43 (0)
> - _R_ client/galaxy/style/less/bootstrap/variables.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-44 (0)
> - _R_ client/galaxy/style/less/bootstrap/wells.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-45 (0)
> - _R_ client/galaxy/style/less/circster.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-46 (0)
> - _R_ client/galaxy/style/less/collections.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-47 (0)
> - _R_ client/galaxy/style/less/embed_item.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-48 (0)
> - _R_ client/galaxy/style/less/fontawesome/bordered-pulled.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-49 (0)
> - _R_ client/galaxy/style/less/fontawesome/core.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-50 (0)
> - _R_ client/galaxy/style/less/fontawesome/fixed-width.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-51 (0)
> - _R_ client/galaxy/style/less/fontawesome/font-awesome.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-52 (0)
> - _R_ client/galaxy/style/less/fontawesome/icons.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-53 (0)
> - _R_ client/galaxy/style/less/fontawesome/larger.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-54 (0)
> - _R_ client/galaxy/style/less/fontawesome/list.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-55 (0)
> - _R_ client/galaxy/style/less/fontawesome/mixins.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-56 (0)
> - _R_ client/galaxy/style/less/fontawesome/path.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-57 (0)
> - _R_ client/galaxy/style/less/fontawesome/rotated-flipped.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-58 (0)
> - _R_ client/galaxy/style/less/fontawesome/spinning.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-59 (0)
> - _R_ client/galaxy/style/less/fontawesome/stacked.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-60 (0)
> - _R_ client/galaxy/style/less/fontawesome/variables.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-61 (0)
> - _R_ client/galaxy/style/less/frame.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-62 (0)
> - _R_ client/galaxy/style/less/galaxy_bootstrap.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-63 (0)
> - _R_ client/galaxy/style/less/galaxy_bootstrap/overrides.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-64 (0)
> - _R_ client/galaxy/style/less/galaxy_bootstrap/variables.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-65 (0)
> - _R_ client/galaxy/style/less/galaxy_variables.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-66 (0)
> - _R_ client/galaxy/style/less/history.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-67 (4)
> - _R_ client/galaxy/style/less/iconic_stroke.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-68 (0)
> - _R_ client/galaxy/style/less/iphone.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-69 (0)
> - _R_ client/galaxy/style/less/job.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-70 (0)
> - _R_ client/galaxy/style/less/jstree.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-71 (0)
> - _R_ client/galaxy/style/less/library.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-72 (0)
> - _R_ client/galaxy/style/less/list-item.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-73 (0)
> - _R_ client/galaxy/style/less/masthead.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-74 (0)
> - _R_ client/galaxy/style/less/select2.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-75 (0)
> - _R_ client/galaxy/style/less/theme/blue.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-76 (0)
> - _R_ client/galaxy/style/less/toastr.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-77 (0)
> - _R_ client/galaxy/style/less/trackster.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-78 (0)
> - _R_ client/galaxy/style/less/ui.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-79 (0)
> - _R_ client/galaxy/style/less/ui/dataset-choice.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-80 (0)
> - _R_ client/galaxy/style/less/ui/icon-btn.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-81 (0)
> - _R_ client/galaxy/style/less/ui/pagination.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-82 (0)
> - _R_ client/galaxy/style/less/ui/paired-collection-creator.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-83 (0)
> - _R_ client/galaxy/style/less/ui/peek-column-selector.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-84 (0)
> - _R_ client/galaxy/style/less/ui/search-input.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-85 (0)
> - _R_ client/galaxy/style/less/upload.less
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-86 (0)
> - _A_ client/grunt-tasks/install-libs.js
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-87 (92)
> - _A_ client/grunt-tasks/scripts.js
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-88 (106)
> - _A_ client/grunt-tasks/style.js
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-89 (79)
> - _M_ client/package.json
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-90 (3)
> - _D_ static/style/Gruntfile.js
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-91 (87)
> - _D_ static/style/Makefile
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-92 (2)
> - _D_ static/style/README
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-93 (26)
> - _M_ static/style/blue/base.css
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-94 (76)
> - _D_ static/style/package.json
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-95 (10)
> - _D_ static/style/src/source_material/circle.py
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-96 (55)
> - _D_ static/style/src/source_material/galaxy_icons.svg
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-97 (345)
> - _D_ static/style/src/source_material/galaxy_spinner.fla
>   https://github.com/galaxyproject/galaxy/pull/208/files#diff-98 (0)
> 
> Patch Links:
> - https://github.com/galaxyproject/galaxy/pull/208.patch
> - https://github.com/galaxyproject/galaxy/pull/208.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/galaxyproject/galaxy/pull/208.

## 

jt (mobile)

**Comment by martenson** [comment]
@jxtx do you mean that the images created from the `source_materials` are being used but the build process itself is not part of the repo?

**Comment by jxtx** [comment]
There was no automated build process other than me manually cropping and
exporting things. They are in source control in case we ever want to modify
and export again. (Which admittedly we have not in almost 10 years, but why
not preserve the sources?)

On Monday, May 4, 2015, Martin Cech notifications@github.com wrote:

> @jxtx https://github.com/jxtx do you mean that the images created from
> the source_materials are being used but the build process itself is not
> part of the repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/galaxyproject/galaxy/pull/208#issuecomment-98765440.

## 

jt (mobile)

**Comment by carlfeberhard** [comment]
Ok. Back in. I used `git checkout <rev> <file>` so, unfortunately lost the changes/attributions for those files. That work?

**Comment by jxtx** [comment]
+1

On Monday, May 4, 2015, carlfeberhard notifications@github.com wrote:

> Ok. Back in. I used git checkout <rev> <file> so, unfortunately lost the
> changes/attributions for those files. That work?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/galaxyproject/galaxy/pull/208#issuecomment-98766541.

## 

jt (mobile)

**Comment by martenson** [comment]
works fine for me; would it make sense to attach the `grunt style` to `grunt watch`?

**Comment by carlfeberhard** [comment]
@martenson that's the plan. Go for it.

**Pull request merged**
