### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by galaxybot**
Run `make update-dependencies`.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@kxk302 It seems that updating `python-irodsclient` to 1.1.2 will break several integration tests: do you maybe know if the Galaxy code needs to be updated, or if there's a bug in this new release?

**Comment by kxk302** [comment]
> @kxk302 It seems that updating `python-irodsclient` to 1.1.2 will break several integration tests: do you maybe know if the Galaxy code needs to be updated, or if there's a bug in this new release?

@nsoranzo, let me check. I worked with my own branch before, which only had my changes. v1.1.2 has my changes plus other changes.

**Comment by kxk302** [comment]
@nsoranzo I downloaded the log archive and see this error in python-irodsclient code:

```
     host, port = sock.getpeername()
 ValueError: too many values to unpack (expected 2)
```

To troubleshoot, I created a socket object and ran getpeername() on it. It returns a tuple of size 2. I have python 3.9 on my laptop. Noticed that the build is using Python 3.7. Created a python 3.7 environment using Conda and and again got two values. The error shows up when we have more than 2 values returned. I can add a *other after port to capture any remaining returned values, but not sure this is the right thing to do.

Reading the Python socket documentation, I see this for getpeername(): "On some systems this function is not supported". Maybe I have to remove this call? Need to look into this further.

**Comment by nsoranzo** [comment]
Thanks @kxk302 , that seems indeed the cause of the test failures. I see you have already opened https://github.com/irods/python-irodsclient/pull/357 to fix this, thanks a lot!

**Comment by nsoranzo** [comment]
I've disallowed python-irodsclient 1.1.2 and re-done `make update-dependencies` . Now it's green and ready for merge if anyone would like to click the button :)

**Pull request merged**
