### PR TITLE
[17.09] Re-merge master into release_17.09.

### PR DESCRIPTION
**Pull request by jmchilton**
I went to update master against release_17.09 and I think this should have been a ``--ff-only`` merge - but there are some merge commits in master that aren't in release_17.09. That shouldn't have happened right? These don't look like they will hurt anything though.

### CODE REVIEW

**Comment by dannon** [comment]
We've usually done this the other way 'round; merging to master as a terminal merge,  never merging master into anything else, so it's merges forward all the way 17.05 -> 17.09 -> {dev, master}.

Did a little digging and these look to be no-op merges, right?  I'd probably just leave it, instead of merging master back into 17.09, which we'll then merge back into master.

**Comment by jmchilton** [comment]
We usually do go in that direction and I definitely want to and if we always did that it should be a ``--ff-only`` merge to the latest release into ``master``. This way ``master`` doesn't have any commits that aren't in the latest release (they should be the same thing). It doesn't merge cleanly though without this - because we didn't go in that direction at least once at some point it seems. After this fix - I will definitely do the release_17.09 -> master though - the correct direction.

**Comment by dannon** [comment]
Ahh, so the historical errant merges here are preventing the clean merges, I see.  Ok, sounds fine to me as long as we merge it back and `master` is terminal again (and always).  I see the three commits above, but was there a single PR/merge that caused these?  If not, we probably need to ping anyone merging like this and make sure they know the scheme moving forward.

**Comment by dannon** [comment]
@jmchilton I just noticed this was from jmchilton:master, and not galaxyproject:master.  You checked to make sure there wasn't anything hinky just going on in your repo, right?  Probably best-practice here to use the in-repo branches for merges like this.

(that said, there were zero actual changes, so I'm not *worried* about it, but github has been misleading before)

**Comment by jmchilton** [comment]
Thanks for the merge. It isn't clear to me if one of those merges was off or if maybe 17.05 was merged into master after 17.09 had been branched but before it was the new master and so it became off in that window.

I wouldn't open a PR from our master because people might delete it after the merge 😅 - and Github does that terrible thing of changing the branch if it is resolved in browser. I never open PRs from galaxyproject/galaxy for that reason I don't think. Even the branching instructions in the Makefile create these branches from downstream repos I think.

Update: In case I am right about that window between releases - maybe we should update the instructions for the release process to re-merge master back into the new release branch right before it becomes the release branch for that reason.

**Comment by dannon** [comment]
Surely our branch protection prevents the delete branch button from working, but that's a good point, and I probably shouldn't assume GitHub will just do the right thing...

**Comment by martenson** [comment]
@jmchilton master is protected, so it can't be deleted like that, however that second points stays and is a good reason to avoid such PRs

**Comment by jmchilton** [comment]
Good points - thanks guys. I've now updated master and it worked cleanly.

**Pull request merged**
