### PR TITLE
Charts revision, part 2

### PR DESCRIPTION
**Pull request by guerler**
This is the continuation of #2531. Chart definitions are now regular form definitions just like tool forms. The coding styles have been aligned and descriptions were added for 3rd party visualization libraries. Instead of filtering visualizations by the number of data points, visualizations are now filtered by selecting a 3rd party library or the curated default list. The filtering settings have been moved to the plugin configurations. With these modifications it should be easier to add new libraries like e.g. charts.js and others. It also improves the visibility of 3rd party library sources and gives proper credit. When selecting a new chart type, chart settings are now preserved. Previously only data group selections were preserved. The selected chart type is displayed with a description at the top of the form when using the settings or the data selection tabs.  Behind the scenes charts has been decoupled from its dependency on tabular datasets. There is no overhead when using other datatypes. Also charts is now able to execute any installed tool not just the R-based charts tool.

Chart types are filtered by visualization libraries:
chart_start

The settings/customize form is now equivalent to other forms e.g. Tool forms:
chart_custom

Additional screenshot of the data group selection view:
chart_data

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
:+1: - I do think the switch to putting the library front and center in those tabs has the potential to be a bit confusing. I would assume most biologists have no clue what the different JS plotting libraries are so I don't think I would arrange the plots this way. I do understand the desire to put similar ones together and to give proper credit though - it is a balancing act for sure.

**Comment by guerler** [comment]
Yeah thats a reasonable point. Maybe we can come up with a more user friendly chart categorization strategy once we have increased the number of installed plugins and see what works. One option could be a text search field and/or something like the biojs registry i.e. a list of installed plugins instead of tabs. Let me know if you have concrete ideas, I'd work on it in a follow up.

**Comment by jmchilton** [comment]
Awesome - glad it is on your radar.

**Pull request merged**
