### PR TITLE
Refactor workflow loading.

### PR DESCRIPTION
**Pull request by jmchilton**
Remove even more duplication between updating and creating workflows. A few new test cases to verify errors under certain conditions.

### CODE REVIEW

**Comment by jmchilton** [comment]
Added another small refactoring here to eliminate a parameter and simplify things for handling multiple workflows "source" types in downstream work.

**Comment by jmchilton** [comment]
Failing tool shed tests are known to be transiently failing tool shed tests unrelated to this PR.

**Comment by mvdbeek** [comment]
I went through the code, this is much nicer now, and no problems loading workflows :+1:
Can I speak to galaxybot?
@galaxybot test this

**Comment by mvdbeek** [comment]
thanks @jmchilton

**Comment by jmchilton** [comment]
Awesome - thanks for the merge @mvdbeek

**Pull request merged**
