### PR TITLE
Onload webhook toggles.

### LINKED ISSUE #5112: Tool Shed is trying to load webhooks - console errors
This is on production. On every page.

`VM835:1 GET https://testtoolshed.g2.bx.psu.edu/api/webhooks/onload/all 404 (Not Found)`

xref: https://github.com/galaxyproject/galaxy/issues/4969

### PR DESCRIPTION
**Pull request by dannon**
Fixes #5112 and #4969.  Ended up refactoring a bit of onload.js, which necessitated a tour.js refactor as well.

### CODE REVIEW

**Comment by jmchilton** [comment]
Selenium test failures related to tool describing tours look legit, let me know if you want me to dig into this:

https://jenkins.galaxyproject.org/job/docker-selenium/421/artifact/421-test-errors/test_generate_tour_with_data2017120121461512164763/browser.log.json

**Comment by dannon** [comment]
Yeah, was a last minute startTourWithData -> giveTourWithData that only had `client` added to the commit, I got it.

**Comment by dannon** [comment]
Since they're not just `/static`, resolving conflicts with a rebase.

**Comment by martenson** [comment]
Thanks @dannon

**Pull request merged**
