### PR TITLE
[WIP] New JS admin interface

### PR DESCRIPTION
**Pull request by martenson**
_warning: this branch will be force pushed in the future - if you build on top of it open PR so I know you have a wip_

This PR is a WIP and RFC on the new makoless admin API and UI

It illustrates a minimal approach of how to replace makos ( ping @nturaga @remimarenco ) for 'manage installed tools' admin menu option.

@carlfeberhard  could you please have a look? (specifically on how the manager and controllers are written and if we can provide a better security for these and of course review of everything else is welcomed) 

initial commit of 'manage installed tools' new UI and API
alters tool_shed_installation model;
creates new admin API endpoints and module;
creates new Admin_beta menu option for testing;
creates simple backbone representation of listing different installed repos

screenshot 2016-04-25 15 27 10

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@martenson nice work +1

**Comment by martenson** [comment]
mockup for the 'manage installed tools' interface ping @erasche @cganote @lparsons
installed_repos

**Comment by cganote** [comment]
I like it. I think the left top and left bottom panels are fine, and I agree that details should go on a separate page. I like the select all/none box in the top left. I don't understand what "Include the newest version" means. In the right-hand box, is the idea that the admin has installed 4 different fastqcs? Are they all available to the user? Why do two of those version allow updates, but not all 4? Why do the 'update to..' links point to two different dates/repos? If the user has the 9/11/2015 version installed, why would they need to update the other old versions?
I'm having some trouble interpreting it =)

-Carrie

**Comment by martenson** [comment]
@cganote the modal in the right depicts one of the more complicated situations Galaxy admins face. You have multiple versions (iow installable revisions) of fastqc repository in your Galaxy. Some of them have minor updates (not changing the version of the fastqc tool) and there are also new versions available (select at the bottom). Previously these versions would be listed as separate rows in the list, but I want to collapse these so I have to offer the functionality in some other form (modal here).

'include the newest version' is my try to differentiate between 'updating' and 'upgrading' of repositories (again the difference in between new revision and new installable revision). If you want only non-version-changing updates for your selected repositories you don't check it; if you also want to install the newest versions you check it.

**Comment by nsoranzo** [comment]
On the top menu to select the repository type ("With tools, "Packages", "Suites", "Data managers", "Datatypes") I'd add also "All". I think that would be useful to rapidly check for broken/updateable repositories.

**Comment by martenson** [comment]
update
screenshot 2016-05-03 13 29 46
screenshot 2016-05-03 13 30 09

**Comment by davebx** [comment]
Definitely liking the way this is starting to look.

**Comment by bgruening** [comment]
@martenson great work and so much needed!

**Comment by martenson** [comment]
working on filtering based on section that the repo has tools in
screenshot 2016-05-09 16 09 26

**Comment by martenson** [comment]
update:
screenshot 2016-05-23 17 32 33

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
screenshot 2016-09-15 12 47 05

**Comment by mvdbeek** [comment]
Do you think we still need the repair functionality, given that it's an additional path through the code and that most of the time you'll have to do an uninstall/install cycle anyway if you need a repair?

**Comment by martenson** [comment]
@mvdbeek I am on board to happily drop it.

**Comment by martenson** [comment]
continues in https://github.com/galaxyproject/galaxy/pull/2930

**Pull request closed without merging**
