### PR TITLE
Move some unit test helper modules into galaxy-app

### PR DESCRIPTION
**Pull request by jmchilton**
In the last two commits here, I moved galaxy_mock.py and tools_support.py respectively into a module where they will be packaged with galaxy-app. A precondition to #12549 it seems and another step along the path toward #8364 (along with #12552, #12551, #12550, etc..). 

Builds on #12546.

For the other packages I created a unittest_utils in ``galaxy.<package>`` - but I'm guessing we shouldn't create a ``galaxy.app`` folder I guess since there is a ``lib/galaxy/app.py`` file so I just placed these test helpers in ``app_unittest_utils`` instead - spiritually follows the convention if not literally.

## How to test the changes?
(Select all options that apply)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Can you fix the conflict please?

> For the other packages I created a unittest_utils in ``galaxy.<package>`` - but I'm guessing we shouldn't create a ``galaxy.app`` folder I guess since there is a ``lib/galaxy/app.py`` file so I just placed these test helpers in ``app_unittest_utils`` instead - spiritually follows the convention if not literally.

Mmmh, what about moving ``lib/galaxy/app.py`` to ``lib/galaxy/app/__init__.py`` instead?

**Comment by jmchilton** [comment]
> Mmmh, what about moving lib/galaxy/app.py to lib/galaxy/app/__init__.py instead?

I've got a bad history with doing those kind of refactorings - I'm worried about the pyc files conflicting as you switch between 21.09 and 22.01. Are those kind of issues any better with Python 3? I don't think getting the right name is worth the potential deployment issues. Also we do all sort so of gross things with galaxy.app (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/buildapp.py#L61) right near the top of the app. Am I being too risk adverse and Python ignorant though?

**Comment by nsoranzo** [comment]
I did a quick test with a module in BioBlend (back and forth) and it worked fine, but I wouldn't swear to it. Maybe we could try and see if at least the tests pass?

**Comment by jmchilton** [comment]
I've opened a PR for the tests you recommended #12583.

I'm still nervous - we've got other stuff that is imported from root by galaxy-app (di.py, queue_worker.py, config_watchers.py, etc..) - what do you think about just renaming ``galaxy.app_unittest_utils`` to ``galaxy.unittest_utils`` and call it matching the convention rather than #12583.

**Pull request closed without merging**
