### PR TITLE
[17.09] Changed GenomeSpace token handling to use manual OpenID association only

### PR DESCRIPTION
**Pull request by martenson**
I cherry picked @nuwang's work to 17.09, resolved few conflicts, please review.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@martenson Missing a `make client`? This is 17.09.

**Comment by martenson** [comment]
Yeah it is missing client, I will add when it is ok'd, is that ok?

**Comment by nsoranzo** [comment]
Tool changes looks good, can't say about changes in `client/`

**Comment by nuwang** [comment]
@martenson Thanks for backporting this. Other than the make client as @nsoranzo suggested, it looks ok to me too.

**Comment by martenson** [comment]
client is built now

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
@martenson Can you merge this forward, please?

**Pull request merged**
