### PR TITLE
[15.07] [Pulsar] Resubmit AMQP acknowledgement messages to the correct queue

### PR DESCRIPTION
**Pull request by natefoo**
...when consuming more than one. If an AMQP endpoint was consuming more than one queue (e.g. Galaxy), acknowledgement retries could be sent on the wrong queue. Also, only start one acknowledgement manager thread rather than one per consumer.
- xref [pulsar #86](https://github.com/galaxyproject/pulsar/pull/86)

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by natefoo** [comment]
Requesting a review - I'd like to at least get this in dev today. Anyone? Bueller?

**Comment by blankenberg** [comment]
+1

**Comment by natefoo** [comment]
Thanks @jmchilton @blankenberg !

**Pull request merged**
