### PR TITLE
Importing math.inf no longer needs try/except

### PR DESCRIPTION
**Pull request by jdavcs**
Just stumbled upon this. No need to support Python 2.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Not sure if its worth adding another import (could not find any info about the future for `float("inf")`), but there are more cases:  `grep inf lib -r | grep float` 

```
lib/galaxy/config/config_manage.py:        key_val_str = yaml.dump({key: value}, width=float("inf")).lstrip("{").rstrip("\n}")
lib/galaxy/config/sample/environment_modules_mapping.yml.sample:# YAML is a typed language, and types are inferred. Thus, the unquoted version 1.10 (for example) will be read by the YAML parser as the floating
lib/galaxy/queue_worker.py:    # python 2 doesn't have math.inf, but can use float('inf')
lib/galaxy/queue_worker.py:    inf = float('inf')
lib/galaxy/datatypes/sequence.py:        forward_strand_start = float('inf')
lib/galaxy/tool_util/parser/cwl.py:        exit_code_lower.range_start = float("-inf")
lib/galaxy/tool_util/parser/cwl.py:        exit_code_high.range_end = float("inf")
lib/galaxy/tool_util/parser/xml.py:                        exit_code.range_start = float("-inf")
lib/galaxy/tool_util/parser/xml.py:                        exit_code.range_end = float("inf")
lib/galaxy/tool_util/parser/stdio.py:        self.range_start = as_dict.get("range_start", float("-inf"))
lib/galaxy/tool_util/parser/stdio.py:        self.range_end = as_dict.get("range_end", float("inf"))
lib/galaxy/tool_util/parser/stdio.py:    exit_code_lower.range_start = float("-inf")
lib/galaxy/tool_util/parser/stdio.py:    exit_code_high.range_end = float("inf")
lib/galaxy/tools/__init__.py:                # Use float instead of int so that 'inf' can be used for no max
lib/galaxy/tools/__init__.py:                group_r.max = float(input_source.get("max", "inf"))
lib/galaxy/util/json.py:        elif val == float("inf"):
lib/galaxy/util/json.py:        elif val == float("-inf"):
lib/galaxy/jobs/dynamic_tool_destination.py:                    lower_bound = float('inf')
```

**Comment by ic4f** [comment]
> Not sure if its worth adding another import (could not find any info about the future for `float("inf")`), but there are more cases: 

Good point! I'm sure `float('inf')` isn't going anywhere. I've looked up the discussion on adding the constant in 3.5: [ref](https://bugs.python.org/issue23185); also here's the [motivation](https://mail.python.org/pipermail/python-ideas/2015-January/030775.html). 

I'm OK with either one. I have a very slight preference for `math.inf` (less verbose, etc.), but I `float('inf`)` is absolutely fine too. As long as we use one or the other consistently. If you prefer the latter, I'll change this file, otherwise I'll change the other instances.

**Comment by bernt-matthias** [comment]
No preference either, so lets go for `math.inf`

**Comment by ic4f** [comment]
Now to the *really* important dilemma! `math.inf` with `import math`, or `inf` with `from math import inf`?  To me, `math.inf` is intuitive, whereas `inf` would require a search for where it's defined or imported. But that's entirely based on habit. What do you think?

**Comment by bernt-matthias** [comment]
I guess the easiest is to repeat myself: 

> No preference either, so lets go for math.inf

:)

**Review by nsoranzo — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
