### PR TITLE
Improved state tracking of HDCA in history panel.

### PR DESCRIPTION
**Pull request by jmchilton**
For tools which dynamically discover datasets for an output collection, keep the collection yellow until the structure of the HDCA has been fully defined. HDCAs still have the problem that they will always be green even if datasets contained within are in error, running, or queued states - but at least the structure (if not contents) is now reflected in the color.

### CODE REVIEW

**Comment by jmchilton** [comment]
Removed WIP language and tag, this is fully functional thanks for the fix from @carlfeberhard (https://github.com/jmchilton/galaxy/pull/11).

There was a question about testing, if you load test/functional/tools/collection_split_on_column.xml into the tool panel this tool can be used to test this behavior.

**Comment by carlfeberhard** [comment]
Not sure why this is stalled or if I can even merge this since I'm an author on it, but:
@jmchilton I've never done it before - can you explain how to "load test/functional/tools/collection_split_on_column.xml into the tool panel"

**Comment by dannon** [comment]
@carlfeberhard I would say that you could test and merge.  My rationale would be that @jmchilton is implicitly approving of the work you did by merging your PR into his, and that you can approve his in the normal way.

Regarding testing, I think @jmchilton was just saying manually add that test tool to your tool panel (add it to config/tool_conf.xml), and use it.

**Comment by jmchilton** [comment]
@carlfeberhard See the end of this file https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/README.txt for instructions on interactive testing of these tools. Also I agree with @dannon, the merger of the PR just needs to be different then the opener of the PR - I routinely merge PRs that contain individual commits I implemented and I don't feel bad about, I feel good - it means I spent the time to really work on the PR and think about it.

**Comment by carlfeberhard** [comment]
Got it. Thanks to both of ya.

**Comment by carlfeberhard** [comment]
+1

**Pull request merged**
