### PR TITLE
Fix optional parameters

### PR DESCRIPTION
**Pull request by guerler**
Fix for #1341, related to #1249, #1319 and #1333.

### CODE REVIEW

**Comment by martenson** [comment]
There is one more occurence of this at L365 https://github.com/guerler/galaxy/blob/fix_validation_000/lib/galaxy/tools/parameters/basic.py#L365

**Comment by martenson** [comment]
Seems like a good solution to me. Will wait tests and merge.

**Comment by guerler** [comment]
Its only a timeout right?

**Comment by nsoranzo** [comment]
I'm pretty sure the bug was already fixed by #1319, but this doesn't hurt.

**Pull request merged**
