### PR TITLE
Trackster, chromosome interaction: fix display of chrint files in tra…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…ckster, do not apply config default_value if explicitly set to undefined, clean line endings

(Adding to dev since this contains changes to config model and may affect other tracks/painters)

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@jgoecks Double check, if you would?

**Comment by jgoecks** [comment]
@carlfeberhard Can you share a test dataset please?

**Comment by carlfeberhard** [comment]
https://usegalaxy.org/u/carleberhard/h/chrint - you'll hafta change the datatype manually.

**Comment by jgoecks** [comment]
@carlfeberhard :+1:

**Pull request merged**
