### PR TITLE
Use Gravity to run Galaxy

### PR DESCRIPTION
**Pull request by natefoo**
We have revived [galaxyproject/gravity](https://galaxyproject.org/galaxyproject/gravity) as a process manager now that we have added the Celery processes and as such want to be able to run multiple processes for a functioning Galaxy server, even in dev mode.

Gunicorn is also moved from dev to regular requirements, and uvloop (which only supports Python 3.7+) is added.

This replaces the circusd configs that @dannon added in #11720. This was a nice setup but had some drawbacks, like not being able to dynamically configure additional processes like job handlers. We stuck with supervisord over circusd mainly because circusd's killer feature - socket forwarding - doesn't work with [unicornherder](https://github.com/alphagov/unicornherder), which is what production servers will use for zero-downtime restarts. Supervisor also appears to be more actively developed these days. We can leave them in though, if people like the ability to run that way.

Possibly controversial feature: `run.sh` (or more accurately, `common_startup.sh`) will write to the venv's `activate` script, but only if it creates the venv. Note that nodeenv does this already so we're not the only ones doing this.

This is done to set `$GRAVITY_STATE_DIR`, which defaults to `~/.config/galaxy-gravity`. In the context of `run.sh` and a cloned Galaxy, we want an instance-specific Gravity state dir. This could be set in `run.sh`, but setting it in `activate` allows you to invoke the Gravity commands from anywhere, without any additional wrapper scripts. Run `run.sh` once and you are all set up. then activate the venv and:

- Run `galaxy` with no arguments to run gunicorn/celery/celery-beat and any job handlers, follow their log files, terminate on `CTRL+C`
- Run `galaxyctl <subcommand>` for start/stop/daemon, see `galaxyctl --help`

The [Gravity README](https://github.com/galaxyproject/gravity/blob/main/README.rst) contains details on how to configure stuff like job handlers, the log file directory, path to Galaxy if not running from source, unicornherder, and more.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by natefoo** [comment]
I went ahead and uploaded gravity 0.9.0 to wheels.galaxyproject.org for testing, I'll delete it after we publish to PyPI.

**Comment by nsoranzo** [comment]
Maybe there are good reasons not to, but wouldn't it be simpler to merge gravity into this repo?

**Comment by natefoo** [comment]
Nothing else in galaxy itself actually installs (into the venv) currently so that would be an extra step of setup. I'm not sure that there is a strong up or downside, but gravity was made to manage multiple instances and be a bit more decoupled from galaxy, which is why it was separate in the first place.

**Comment by natefoo** [comment]
> I went ahead and uploaded gravity 0.9.0 to wheels.galaxyproject.org for testing, I'll delete it after we publish to PyPI.

And now I deleted it as @mvdbeek reminded me you can just put dev/git URLS into the requirements. If folks are happy with this setup, then I will go ahead and publish the package to PyPI and mark this ready for review.

**Comment by natefoo** [comment]
Are we cool with this in 22.01, or push to 22.05? You can still run with uwsgi by setting `$APP_WEBSERVER` or running with uWSGI directly.

**Comment by mvdbeek** [comment]
Yes, let's get this into 22.01. I think this is the right order, get the run.sh setups to use fastAPI, give production setups a grace period where they can but don't have to switch, and then remove uwsgi in 22.05.

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
I don't think that requires any action @nsoranzo, which was the idea with the config/breaking label. It's a big one though.

**Pull request merged**
