### PR TITLE
Remove deprecated objectstore options from sample; the new way is to …

### PR DESCRIPTION
**Pull request by dannon**
…set object_store_conf and use it.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by nsoranzo** [comment]
`object_store_cache_path` and `object_store_cache_size` are not documented in `config/object_store_conf.xml.sample` (and I'm not sure they belong there).

**Comment by dannon** [comment]
I dunno if this is an 'enhancement', really.  Those two things are documented in sample underneath the two caching object stores.  (https://github.com/galaxyproject/galaxy/blob/dev/config/object_store_conf.xml.sample#L28)

**Comment by nsoranzo** [comment]
Ops, right, sorry!

**Pull request merged**
