### PR TITLE
[19.09] Release notes for 19.09.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by martenson** [comment]
I think the notes are in a really good shape, thanks @jmchilton!

**Comment by martenson** [comment]
@natefoo  I've pushed notes regarding the tool configuration changes, please review. I am thinking about shortening it, maybe extracting the full notes into separate document and including only summary?

**Comment by hexylena** [comment]
Will get the user notes wrapped up today.

**Comment by hexylena** [comment]
Added some gifs/etc. If someone could review the user-facing ones, that would be amazing. (I'm running really low on time today and am out for next 3 days.)

**Pull request merged**
