### PR TITLE
UI, Citations: fix citation-model's import of bibtex to use *either* …

### LINKED ISSUE #1317: Attempting to save workflows containing certain tools never completes.
Dev is affected. 

Error in console:
`Uncaught TypeError: a is not a function         http://xyz/static/scripts/mvc/citation/citation-model.js`
- Create new workflow
- Add Kraken `toolshed.g2.bx.psu.edu/repos/devteam/kraken/kraken/1.1.0` tool --> Error is logged in console.
- Save workflow --> 'Saving' spins forever

Current work around is to create workflow on working server, export, import in broken.

### PR DESCRIPTION
**Pull request by carlfeberhard**
…commonjs or global

We require via webpack (where bibtex loads via module.exports) in the homepage and via requirejs (where bibtex loads as a global var) in the workflow.

We fixed the former in #1261 and the latter here.

Attempts to fix: #1317

### CODE REVIEW

**Comment by carlfeberhard** [comment]
Got this error trying to install kraken on mac os x 10.10.5:

```
In file included from krakendb.cpp:20:
./kraken_headers.hpp:36:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [krakendb.o] Error 1
/bin/sh: /bin/true: No such file or directory
```

Probably user error, but putting it up so that someone will test this and forgive if it doesn't work.

**Comment by martenson** [comment]
This fixes it for me. I am quite puzzled about what happened though because I have tried the syntax used in this PR with the only difference in name for the import `parseBibtex` vs `BibtexParser`.

**Comment by martenson** [comment]
@carlfeberhard would you mind creating the issue for kraken here? https://github.com/galaxyproject/tools-devteam/issues

I think it is unrelated.

**Comment by carlfeberhard** [comment]
@martenson bibtex.js uses a universal module definition. In this case, a version that allows either global definition (attaching BibtexParser to the window object) or a commonjs definition (see the section in the file near the end that checks for module.exports).

When webpack makes a dependency tree by tracing the requirejs definitions, it then compiles it all using commonjs (module.exports), so when bibtex loads in the large libs.bundled.file loaded on the homepage, 'module.exports' is there and the function argument 'parseBibtex' will have the function. 

When the workflow/toolform (or really any other page that requires citation-model) outside the homepage, requirejs will load the bibtex.js library, but there will be no module.exports and bibtex will attach itself to the global namespace.

We use both forms, so we need that small hack that checks for either.

**Comment by martenson** [comment]
@carlfeberhard thank you very much for the explanation!

**Pull request merged**
