### PR TITLE
Don't fail a TravisCI build if first_startup fails.

### PR DESCRIPTION
**Pull request by jmchilton**
It seems to fail an awful lot.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Yesterday's failings were due to the MTS 16.01->16.07 update and were fixed when it was updated to include #2950, so they were legitimate.

**Comment by jmchilton** [comment]
Perhaps we can make first startup skip a dependency on the tool shed - skip tool migrations and tool shed update checks?

**Comment by mvdbeek** [comment]
Are you sure this isn't just the OS X build? This does take quite a while to start on Travis, and then its installing python and co via homebrew. I think the linux one shouldn't fail frequently.

**Comment by jmchilton** [comment]
Okay... I've rebased to try to just disable the OSX one.

**Comment by nsoranzo** [comment]
I can't see the difference (apart from the commit title).

**Comment by jmchilton** [comment]
@nsoranzo Look closer :wink: I'm sure it is in there somewhere.

**Comment by martenson** [comment]
I think Travis was failing because of the reasons @nsoranzo described (example here: https://travis-ci.org/galaxyproject/galaxy/builds/161924335). 

I understand removing the dependency on MTS unless we lose something we really want to test. Nevertheless 'first startup' probably shouldn't be the place to fail and this PR does not solve much imo. If anything I would disable failing all tests for the osx platform, however they don't fail more often than linux, they just take super long because Travis does not have enough OSX VMs I think.

I am not sure which problem we are trying to solve here.

**Pull request closed without merging**
