### PR TITLE
Add tox to dev requirements

### PR DESCRIPTION
**Pull request by nsoranzo**
Used (e.g. in CI) to run all sort of backend tests.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
What's the reasoning here ? I suppose tox isn't usually run from within Galaxy's virtualenv ?

**Comment by nsoranzo** [comment]
> What's the reasoning here ? 

Provide a ready-to-go developer environment.

> I suppose tox isn't usually run from within Galaxy's virtualenv ?

Depends on how you install it, the one provided by Linux distributions is usually out of date, so I normally install it inside Galaxy virtualenv. Then `tox` creates its own test virtualenvs inside `.tox`, but that's a different story.

**Comment by mvdbeek** [comment]
Can you tell me what the user story here is ? you `pip install -r dev-requirements.txt` to get all the things just so you can have tox, and then you're not using it at all because tox manages this ? I don't think that's convincing.

The downside is that we need to install more stuff to run tests that don't need tox, and that is a pretty significant downside IMO.

**Comment by nsoranzo** [comment]
> Can you tell me what the user story here is ?

```shell
. .venv/bin/activate
pip install -r dev-requirements.txt
tox -e py37-unit
```

works instead of getting `tox: command not found`.

> you `pip install -r dev-requirements.txt` to get all the things just so you can have tox, and then you're not using it at all because tox manages this ? I don't think that's convincing.

I don't get how you're not using it, what do you mean?

**Comment by mvdbeek** [comment]
> ```shell
> . .venv/bin/activate
> pip install -r dev-requirements.txt
> tox -e py37-unit
> ```

really ? anyone gonna wait half an hour to get tox ??



> I don't get how you're not using it, what do you mean?

None of the dev-depencies, except for tox are going to be used in that scenario, right ?

**Comment by nsoranzo** [comment]
I guess most developers would like to run some of the tests locally before opening a PR, so they would need tox at some point since `./run_tests.sh` doesn't cover everything (and it shouldn't).
So my main reasons to have tox in the Galaxy virtualenv are:
- tox from Linux distro repo is often at an old version
- if possible, I prefer to have the development tools in the same virtualenv, so I can run tox, pytest, ipython, flake8, mypy...

But since there's no consensus that's helpful, I'm closing this.

**Comment by mvdbeek** [comment]
Maybe we can revisit this if/when dev-requirements.txt doesn't contain all of Galaxy's dependencies as well ?

**Pull request closed without merging**
