### PR TITLE
Avoid passing headers argument twice in datatypes display

### LINKED ISSUE #14759: Can't execute or download Jupyter Notebook
I've created a jupyter notebook on Galaxy some time ago.
However, when I wanted to download or execute it again it does not work.
For the download it shows:
`{"err_msg":"Could not get display data for dataset: _serve_raw() got multiple values for argument 'headers'","err_code":500001}`
For the execution it shows:
`cp: cannot stat '/data/dnb06/galaxy_db/files/f/9/7/dataset_f971fa2d-2753-4ae6-8925-928b8effed63.dat': No such file or directory`

Seems like the whole file is gone.
Any help would be appreciated.

### LINKED ISSUE #15737: Datasets of type ipynb cannot be viewed or downloaded
**Describe the bug**
When trying to view or download .ipynb notebook files the server response is `{"err_msg":"Could not get display data for dataset: _serve_raw() got multiple values for argument 'headers'","err_code":500001}`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Upload any file of datatype ipynb
2. Click on the eye or download icons of the dataset

### PR DESCRIPTION
**Pull request by wm75**
Fixes #15737
Fixes #14759
Fixes https://github.com/usegalaxy-eu/issues/issues/340 
## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
I guess the obvious comment is that the headers shouldn't be passed way down into the datatypes, but I have some vague hope we'll get rid of this when display functionality is moved to the client. Thanks for the fix @wm75

**Comment by wm75** [comment]
Well, it's actually possible that the whole business around handling passed in headers is historic cruft. The only part touched by this PR that's causing an *actual* error is the `display_data_trusted` branch of the Ipynb datatype (thanks @hexylena for your remark about this being an .eu-only issue). This is failing because it will pass a duplicated `headers` argument even if no headers key was in the **kwd dict.
The other changes I made are only lurking bugs that *would* cause duplications with `headers` in **kwd, but maybe that's never the case, and all of this could be simplified a lot more?

**Comment by dannon** [comment]
@wm75 Did you want to target 23.0 with this?

**Comment by wm75** [comment]
@dannon if it's ok from your side, then that would, of course, be preferable to have things fixed on .eu earlier.

**Comment by wm75** [comment]
Ok, @dannon I'm a bit lost. Why are type annotations in these files not the same between `dev` and `release_23.0`, and what's the best option to target both eventually?
Should I first target dev after all, then backport manually to release_23.0, or something else?

**Comment by dannon** [comment]
@wm75 That's interesting; I haven't followed the history there.  In general for this kind of fix I'd say target 23.0 first and we'd just merge forward resolving whatever issues we had to along the way.

**Comment by wm75** [comment]
Ok! Sorry for the mess here - reopened as #15766.

**Pull request closed without merging**
