### PR TITLE
[PROCEDURES] Remove jxtx from committers list.

### PR DESCRIPTION
**Pull request by dannon**
:(

Years later now and this is no easier, but I'm pretty sure James would have wanted this done a while ago.  I think he'd also be thrilled with the state of the community and project today.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
:cry:

**Review by nsoranzo — APPROVED** [review]
Agreed :cry: , thanks for taking the step.

**Review by bgruening — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]

**Review by afgane — APPROVED** [review]
Should we add a section on Past Committers?

**Review by davelopez — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Review by nuwang — APPROVED** [review]

**Comment by assuntad23** [comment]
> Should we add a section on Past Committers?

How would the transition to that section work? There is one other committer who is no longer part of the project. Do they get put in the past committers list too?

**Comment by dannon** [comment]
@assuntad23 Yeah, we'd keep a list of past committers.  I like the idea, and I'll open a separate PR following up on that.

**Pull request merged**
