### PR TITLE
Add rgb option for color picker

### PR DESCRIPTION
**Pull request by guerler**
ping @bgruening

### CODE REVIEW

**Comment by jmchilton** [comment]
This is added in the wrong place I think - this isn't an intrinsic property of the value being represented. It is a way to view the data. I think you should add a wrapper function to generate this. So `$param` would still be the same - but `$param.as_rgb()` would do this.

Update: `galaxy.tools.wrappers:InputWrapper.as_rgb()`?

Update 2: The complexity of dealing with multiple representations of the parameter is worse at the param value level - since it affects tool state being persisted to the database, extracted from histories into workflows, etc.... At the wrapper level - this is a very light-weight addition.

Update 3: I guess to_param_dict_string isn't what gets persisted huh? If that is the case - I guess this is fine.

**Comment by guerler** [comment]
Yes, these are good points. I assume that `to_param_dict_string` only transforms the representation for the tool template itself and does not effect how the actual value is stored too. The value which is stored is what `value_to_basic` i.e. `to_json` returns. I also would like to keep the abstraction layer out of the wrapper. I would like to avoid a pattern in which we end up with two classes for customized tool parameters i.e. one in basic.py and one in the input wrappers. Thanks a lot for looking into it.

**Comment by bgruening** [comment]
@guerler I have PR some changes to the XSD file to your branch. Thanks!

**Comment by jmchilton** [comment]
> I also would like to keep the abstraction layer out of the wrapper. I would like to avoid a pattern in which we end up with two classes for customized tool parameters i.e. one in basic.py and one in the input wrappers. Thanks a lot for looking into it.

I'm going to merge this, but I disagree with this logic in the abstract. The parameters are complex and to whatever degree we can separate logic for representation (JSON/DB/etc..), processing (request handling), and 'viewing' the data (using them within tool command blocks) that is good thing in my opinion.

**Comment by guerler** [comment]
Ok, we should talk about it and figure out what pattern we want to continue to use in the future. In general I agree with you but the degree of separation and abstraction seems to be the question. This PR demonstrates it. My current preference is to keep it together in basic.py and use designated functions instead of multiple files and classes. I also removed redundant wrappers in the past. Thanks a lot for reviewing this. I appreciate it a lot.

**Pull request merged**
