### PR TITLE
Add EDAM operations to tools and expose in API

### PR DESCRIPTION
**Pull request by mvdbeek**
This our (@nsoranzo, @odoppelt) contribution from the TWW Hackathon.

@dannon @jmchilton any comments?

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome!

**Comment by nsoranzo** [comment]
Ready for review.

**Comment by jmchilton** [comment]
:+1: Looks perfect to me - what percentage of tools should have an EDAM operation?
- All tools
- Most bioinformatics tools
- Some bioinformatics tools
- Some tools

If it is all tools we should add a planemo lint for this also. If it is just most or all bioinformatics tools - maybe we should add a planemo linter for that keyed on like a `--bioinformatics` flag for instance. If useful there are other things we can do with `--bioinformatics` such as check that the datatypes are in Galaxy core.

**Comment by nsoranzo** [comment]
EDAM provides ontologies for bioinformatics, so I'd say "most bioinformatics tools". Regarding planemo lint, it could at least verify that it is structured correctly if it is present.

**Comment by hmenager** [comment]
@mvdbeek @nsoranzo @odoppelt @jmchilton quick question: could/should we add a way to also specify EDAM topics in this? Something like an <edam_topic> element?

**Comment by nsoranzo** [comment]
@hmenager Sure, EDAM topic is also a mandatory attribute for bio.tools registration: https://github.com/bio-tools/biotoolsxsd

**Pull request merged**
