### PR TITLE
Revise tool url building

### PR DESCRIPTION
**Pull request by guerler**
Avoids the second ampersand at the end of the url.

### CODE REVIEW

**Comment by hexylena** [comment]
This is for https://github.com/galaxyproject/galaxy/issues/937#issuecomment-149321996 correct?

**Comment by guerler** [comment]
Yeah.

**Comment by hexylena** [comment]
Okay, I'll test this later tonight. Thanks for the quick turnaround on this. I'm happy to make PRs for the parent issue of that comment, but I don't know where to look.

**Comment by guerler** [comment]
Thank you for catching this. The url is initialized at the location touched by this PR and then finalized at https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/utils/utils.js#L104. What do you mean with 'parent issue'?

**Comment by hexylena** [comment]
LGTM.

**Comment by martenson** [comment]
This is the only change in dev since https://github.com/galaxyproject/galaxy/commit/278c2aa399c45aec0eac6e8fa66e47d83e3bace2 so it might be the cause of why the jenkins framework tests started to fail ever since 
trace here: https://jenkins.galaxyproject.org/job/docker-framework/586/console

ping @guerler @erasche 

it can also be docker image related though :/

**Comment by hexylena** [comment]
T_T will investigate soon. Hope I didn't cause this

**Comment by martenson** [comment]
well it dies on 

```
Attempting to serve app on randomly chosen port: 9905
Error - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'STOP_RENDERING'
```

so probably not this PR unless I am missing something

**Comment by hexylena** [comment]
Huuuh. Weird

**Comment by martenson** [comment]
api tests run fine, I am puzzled

**Comment by hexylena** [comment]
@martenson did that crash/fail? Jenkins says you cancelled that build. https://jenkins.galaxyproject.org/job/docker-framework/586/ Would make sense to see a weird/unexpected error if it was halted midway through

**Comment by martenson** [comment]
@erasche that is the terminal state, it will be stuck there forever

**Comment by hexylena** [comment]
@martenson not sure I understand... do you mean it was just looping in that state? Or ... ? you killed it and disabled the job, of course it will be stuck there forever.

**Comment by martenson** [comment]
@erasche It was looping there so I cancelled it, tried it on dev and it got stuck in a loop again, so I disabled the job to prevent polluting the PRs.

**Comment by hexylena** [comment]
@martenson thanks, that makes sense. Makes no sense for those tests to be failing on this, I'll try and reproduce locally.

**Comment by martenson** [comment]
My next suspect is https://github.com/galaxyproject/galaxy/pull/942 because it might have changed the docker environment and we might not be cleaning it up properly.
It has not been merged but the test has ran for the PR so e.g. the `test/docker/base/run_test_wrapper.sh` has been executed.

**Comment by hexylena** [comment]
Hmmm. Yeah, I think we start looking there, agreed, because my tests work on a clean copy of everything

**Comment by martenson** [comment]
the Jenkins bug was unrelated to this PR; it tried to use templates compiled by latest mako but we only had 0.4 (the latest were there from the wheel PR, now we cleanup compiled templates)

**Comment by hexylena** [comment]
Aha. I thought it might've been mako's fault. Good to know.

**Comment by erasche** [comment]
the Jenkins bug was unrelated to this PR; it tried to use templates compiled by latest mako but we only had 0.4 (the latest were there from the wheel PR, now we cleanup compiled templates)

**Pull request merged**
