### PR TITLE
Refactor cloud "Upload" > "Get"

### PR DESCRIPTION
**Pull request by VJalili**
This follows the refactoring of cloud "Download" > "Send" @https://github.com/galaxyproject/galaxy/pull/6583.

ping @dannon

### CODE REVIEW

**Comment by martenson** [comment]
This should go to 18.09 so we don't release an API with signature that we instantly change in the next release.

edit: we can just backport after merge, we just need to remember :)

**Comment by martenson** [comment]
@dannon are you fine with the wording now?

**Comment by dannon** [comment]
Yep.  To be clear, my main concern with the confusing naming upload/download to cloud was never the source code, but the options presented to the user, but this is all fine with me.

@VJalili Sorry I missed that initial ping!

**Comment by VJalili** [comment]
Thanks @martenson & @dannon

**Pull request merged**
