### PR TITLE
[20.05] Backport linkifying library description

### PR DESCRIPTION
**Pull request by OlegZharkov**
Backporting commits from  https://github.com/galaxyproject/galaxy/pull/9746 and https://github.com/galaxyproject/galaxy/pull/9790 to 20.05

### CODE REVIEW

**Comment by dannon** [comment]
While I'm pretty sure it's 'safe' to backport; I'm not sure we should, since it's not a bugfix and it's primarily cosmetic?

**Comment by OlegZharkov** [comment]
@dannon it's also a bug fix here https://github.com/galaxyproject/galaxy/pull/9791/files#diff-b83467811fbbeac22dcb8303e80384fbR134

before 
bug

now:
fix


It's not a major issue, but it looks a quite weird, when it blinks

**Comment by mvdbeek** [comment]
I guess there's no harm getting this in. Thanks @OlegZharkov!

**Comment by OlegZharkov** [comment]
Thank you  @dannon and @mvdbeek !

**Pull request merged**
