### PR TITLE
This should fix bug #1892 in toolshed

### PR DESCRIPTION
**Pull request by nturaga**
screen shot 2016-04-12 at 5 30 43 pm

### CODE REVIEW

**Comment by dannon** [comment]
(working w/ @nturaga directly, this is getting swapped over to a class+style def to be more reusable)

**Comment by martenson** [comment]
xref #1892

**Comment by nturaga** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@nturaga please label PRs properly
see https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/issues.rst for details

**Comment by martenson** [comment]
thanks for fixing this @nturaga

**Comment by remimarenco** [comment]
Is it on purpose we don't use the Less nesting feature? http://lesscss.org/features/#features-overview-feature-nested-rules

Could we do that instead?

``` LESS
@borderGrey: solid #DDDDDD 1px; 

.grid {
    tbody {
        td {
            line-height: @line-height-base;
            border-top: @borderGrey;
            border-bottom: @borderGrey;
            padding: 5px;
        }

        td:empty {
            padding: 0;
        }
    }

    thead {
        tr {
            height: 2em;
        }

        th {
            line-height: @line-height-base;
            background: @table-heading-bg;
            color: contrast(@table-heading-bg);
            border-top: solid @table-border-color 1px;
            border-bottom: solid @table-border-color 1px;
            padding: 5px;
            text-align: left;
            white-space: nowrap;
        }
    }

    tfoot td {
        background-color: #F8F8F8;
        border-top: @borderGrey;
        border-bottom: @borderGrey;
        padding: 5px;
    }

    .current {
        background-color: #EEEEFF;
    }
}
```

**Comment by dannon** [comment]
@remimarenco I'm not aware of any particular reasons we don't use that style other than, perhaps, general familiarity with cascading and non-nested css style when we first implemented this.

It might be worth looking at refactoring the .less at some point to see if the nested style works well and is more readable.  On the face of it, it looks like it might be, to me, though I don't know how high I'd put it on the priority list ;)

**Comment by martenson** [comment]
@remimarenco It is not on purpose. Most of the .less files are ready for some refactoring using more of the less features. Mainly separating files for each JS app and providing better namespacing. We do not enforce any style though.

**Comment by remimarenco** [comment]
Thanks for the answers! Added in my personal backlog then :p

**Pull request merged**
