### PR TITLE
Implement undelete user function with api tests

### PR DESCRIPTION
**Pull request by juleengraham**

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@juleengraham I think the API test failures are legitimate failures. You might want to merge in or rebase against the current dev branch (https://github.com/galaxyproject/galaxy/pull/8324 might have fixed part of this) and see if they still fail.

**Comment by martenson** [comment]
I cherry picked the relevant commits to https://github.com/galaxyproject/galaxy/pull/8309 and finished it. This PR is now part of the other one so I am closing it. Thanks for helping with this @juleengraham !

**Pull request closed without merging**
