### PR TITLE
Workflow editor undo/redo

### LINKED ISSUE #644: Workflow editor needs an undo button
Use case:
- Editing a workflow
- Haven't saved in a couple steps
- Accidentally delete a step and lose all of that progress
- Tears

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
closes #644 

Adds a undo-redo system to the workflow editor.

The system works with a store managing an undo- and a redo stack of action class instances, which encapsulate bi-directional state changes. 

All workflow editor user actions were moved to these action classes, allowing every modification of the workflow to be undone, and redone in granular steps. Continuous state-changes (like moving a node around, or typing text) are stored every second, or when another change occurs.

To learn more about how the actions and the store functions, see the README.md in the undoRedoStore module.

https://github.com/galaxyproject/galaxy/assets/44241786/f8404687-d9ac-465c-8afc-ab8abe63a6d8

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
exciting feature! 🎊

> Currently undo/redo is bound to the keyboard keys ctrl-z, and ctrl-y.

this is `Cmd+z` and `Cmd+Shift+z` on macos

**Comment by ElectronicBlueberry** [comment]
This will have major merge conflicts with #17615
I'd prefer to merge the undo/redo PR first

**Comment by davelopez** [comment]
I suggest putting the other one temporary into `draft` just in case :sweat_smile:

**Review by mvdbeek — COMMENTED** [review]
Sorry for the late review, but here's a couple of things I've noticed.
- [x] At first I didn't find the undo-redo buttons, since my test workflow had a long name:

Screenshot 2024-04-08 at 10 52 31

- [ ] The success messages don't appear consistently on undo/redo:
  - [ ] change a parameter value: no message
  - [ ] toggle a workflow output: no message
  - [ ] change a step label: message
  - [ ] move a step there's: no message (that might be fine ...)
  - [ ] connect or disconnect: no message (would be nice as that can be hard to track visually)
  - [ ] insert or remove step: no message (would also be nice)

I think the message inconsistency isn't necessarily a deal-breaker if that's hard to fix. Another thing that would be really cool is if we could introspect the stack of changes, and maybe even send that as a patch request to the backend, which would align very well with a long-term goal of diff-based workflow updates (https://github.com/galaxyproject/galaxy/issues/9166)

**Comment by mvdbeek** [comment]
Really cool work overall, I like this a lot!

**Comment by ElectronicBlueberry** [comment]
> The success messages don't appear consistently on undo/redo

The messages should currently appear in the sane scenarios where a message would appear on manual change.

This could be changed to always display a message, but I think this might clog the interface quickly, when many things are undone/redone.

**Comment by ElectronicBlueberry** [comment]
Reading your post again, I think the ones you marked as 'would be nice' make a lot of sense.

**Comment by mvdbeek** [comment]
> The messages should currently appear in the sane scenarios where a message would appear on manual change.

Ah, makes sense, though the context is a little different. As an example, if I change a parameter value from 1 to 2, I probably am aware that I am doing that right now. If I click undo, there's an arbitrary amount of time in between that change (and possibly multiple other changes if undoing multiple things). Again, I don't think this needs fixing for an initial implementation and we have the version selector which doesn't implement anything like this, so this is fine for now.

**Review by mvdbeek — APPROVED** [review]
This is very cool, thanks a lot for continuing to improve the editor @ElectronicBlueberry!

**Comment by ElectronicBlueberry** [comment]
> > Another thing that would be really cool is if we could introspect the stack of changes
> 
> +1 I'll add this to this PR

On second thought, this may be better in a follow-up

**Pull request merged**
