### PR TITLE
Webhooks: add tests

### PR DESCRIPTION
**Pull request by anatskiy**
Once Webhooks have been introduced, tests were missing. Now I fixed it. Also, `WebhooksRegistry` doesn't consider junk files (like .DS_Store) and the `demo` folder as a webhook directory anymore.

### CODE REVIEW

**Comment by bgruening** [comment]
Don't worry about the failing tests, that will be fixed in an other PR.
Thanks @anatskiy

**Comment by martenson** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Thanks for the contribution - I'm going to open a PR to fix this up a bit. It is close but you...
- Shouldn't need to modify Galaxy to treat your test data specially (this is a smell indicating a test problem). 
- API tests shouldn't modify ``app`` IMHO - they should treat Galaxy as somewhat immutable so they can run on remote Galaxy instances. Really no test should modify app in this way because it violates Galaxy's abstractions. If you need Galaxy with a specific configuration - you should write an integration test that configures Galaxy this way from the get go - this way you are not violating Galaxy's abstractions and you also have the benefit of testing Galaxy's configuration parsing code.

These should be really easy to fix but there isn't a lot of test documentation so I'm going to open a PR against your repository - I hope that is okay.

**Comment by anatskiy** [comment]
@jmchilton yeah, sure, no problem.

I spent I lot of time trying to figure out how to change the `webhooks_directory` path but couldn't find anything. That's why I had to re-use the `WebhooksRegistry` in such a manner.

**Comment by jmchilton** [comment]
I pushed a merge against dev to resolve conflicts in the PR. This is really nice - thanks for the tests!

**Comment by jmchilton** [comment]
@bgruening In response to some out of band comments on this pull request I get that these are potentially useful plugins on there own - and I'm willing to move them outside of ``$GALAXY_ROOT/test`` for sure. I just don't think ``config/plugins/webhooks/demo`` is appropriate because I feel like each directory in ``config/plugins/webhooks/`` should be a plugin. Also I guess tests shouldn't depend on things in ``config/plugins/`` if it can be avoided since things may be removed from there by deployers and the tests should still pass.

If you want to put the useful plugins in ``contrib/plugins/webhooks`` or something - I would be fine with that - but I think they are fine in test for now as well. Let me know if you'd like to keep discussing this.

**Comment by bgruening** [comment]
I think it's ok. You have added a nice comment into the galaxy.ini and people can also add the path to the test dir to galaxy.ini. It ok as it is. We loose a little bit of visibility but I guess as soon as people are confident with this plugin infrastructure we should advertise it more and enable PhD comics on main :stuck_out_tongue:

**Pull request merged**
