### PR TITLE
Fix issue #745 sort bam-to-sam output

### PR DESCRIPTION
**Pull request by mvdbeek**
... and potentially the the sam-bam conversion failure of issue #744

### CODE REVIEW

**Comment by jmchilton** [comment]
Isn't the correct thing to sort the test data files in repository? Galaxy's current bam datatype requires the bams to be sorted, but other bam datatypes might not right so I am not sure the framework should do this.

**Comment by nsoranzo** [comment]
Ping @blankenberg

**Comment by mvdbeek** [comment]
@jmchilton the test-data files are coordinate sorted (the example being devteam's bowtie2), so the sorting of the test-data in the PR can be skipped.  I agree that if galaxy's datatype enforces sorted bam file, sorting shouldn't be necessary. The question then is, why do we get unsorted bam files into the comparison in the first place? Especially considering that the tool wrapper explicitly converts to sorted bam ...

**Comment by mvdbeek** [comment]
OK, I get it now, there appears to be a problem in generating the index file and/or sorting the bamfile within the bam datatype (see @martenson framework output https://jenkins.galaxyproject.org/job/G-framework/9/testReport/functional.test_toolbox/TestForTool_metadata_bam/test_tool_000000/).
This PR would just work around that issue instead of fixing it, at the expense of sorting multiple times.

**Pull request closed without merging**
