### PR TITLE
[PROCEDURES] Remove Oleg from committers list

### PR DESCRIPTION
**Pull request by mvdbeek**
Oleg has done so much awesome stuff for us, but he's moved on to
Industry. Thanks for all your brilliant work @OlegZharkov, and hope to
see you around.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Comment by OlegZharkov** [comment]
Thanks everyone for a great time in Galaxy!

**Review by dannon — APPROVED** [review]

**Review by blankenberg — APPROVED** [review]

**Comment by davelopez** [comment]
See you around Oleg! and enjoy your new adventures! :smile:

**Review by davelopez — APPROVED** [review]

**Review by martenson — APPROVED** [review]
Thanks for all the contributions @OlegZharkov!

**Review by natefoo — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]
Real loss for the project :_(, so many amazing contributions in such a short period of time. Very nice work Oleg, thanks for everything and good luck on what's next.

**Pull request merged**
