### PR TITLE
[16.01] Workaround for #1739 - fixing up subworkflow input connections.

### LINKED ISSUE #1739: not able to connect to workflow in workflow inputs
Hi, I was checking out the new workflow in workflow tool from 16.01 and found that I can only connect "basic" workflow inputs to inputs of this tool. It does not connect if the datatype is changed, e.g. to tabular by the cut tool.

Steps to reproduce:
- check out fresh 16.01
- create a workflow consisting of one input and one concatenate "single_input_cat"

wf_single_input_cat
- create new workflow with single input and try to connect to "single_input_cat"
  - first row: _can't_ connect via cut
  - second row: **can** connect directly from input
  - third row: **can** connect via cat
  - fourth row: **can** connect cut and cat

test_wf_in_wf

### PR DESCRIPTION
**Pull request by jmchilton**
Do the same relaxed thing we do for inputs of type 'input' as we do for outputs of this type. Someday we should have better tracking, but such a change is probably not wise for a release branch.

Fixes #1739

### CODE REVIEW

**Comment by mvdbeek** [comment]
It works partially for us on 16.01:
The previsouly unconnectable workflow connects, but a save fails with:

```
sh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
Error - <type 'exceptions.KeyError'>: 1
URL: https://lbcd41.snv.jussieu.fr/workflow/save_workflow
File 'lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File 'lib/galaxy/web/framework/base.py', line 184 in handle_request
  body = method( trans, **kwargs )
File 'lib/galaxy/web/framework/decorators.py', line 48 in call_and_format
  return dumps( func( self, trans, *args, **kwargs ), **json_kwargs )
File 'lib/galaxy/webapps/galaxy/controllers/workflow.py', line 710 in save_workflow
  from_editor=True,
File 'lib/galaxy/managers/workflows.py', line 310 in update_workflow_from_dict
  self.__connect_workflow_steps( steps, steps_by_external_id )
File 'lib/galaxy/managers/workflows.py', line 868 in __connect_workflow_steps
  conn.output_step = steps_by_external_id[ conn_dict['id'] ]
KeyError: 1

```

**Comment by jmchilton** [comment]
@mvdbeek - Simple tests I have done do exhibit this save error, but it has been reported before https://github.com/galaxyproject/galaxy/issues/1673.

So I think the save error is a separate and unrelated issue. I want to solve it also and a minimum example would be very helpful (I've never seen it) - but I don't think it should prevent merging this PR.

**Comment by mvdbeek** [comment]
> So I think the save error is a separate and unrelated issue. I want to solve it also and a minimum example would be very helpful (I've never seen it) - but I don't think it should prevent merging this PR.

entirely reasonable, and definitely an advance to be able to connect the workflows. it's a user workflow, I'm not exactly sure how to reproduce this cleanly :/.

:+1:

**Comment by jmchilton** [comment]
Erg... :rage: users break all my nice toys - why are we letting them use Galaxy.

**Pull request merged**
