### PR TITLE
Fix tool downloads in tool form

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by jmchilton** [comment]
Why is this a WIP, the fix seems fine to me.

**Comment by davebx** [comment]
That's interesting, this should not have worked before, but I know it did. Was to_archive() moved into Tool from another class?

**Comment by jmchilton** [comment]
It was moved by me from toolbox - I thought I tested it though :disappointed:.

**Comment by nsoranzo** [comment]
@galaxybot test this.

**Comment by nsoranzo** [comment]
Maybe we need a (unit?) test for this.

**Comment by jmchilton** [comment]
I promise I will write a test next time I touch it :wink:.

**Pull request merged**
