### PR TITLE
Revert "[WIP] Mega flake8 linting"

### PR DESCRIPTION
**Pull request by dannon**
Reverts galaxyproject/galaxy#433

### CODE REVIEW

**Comment by hexylena** [comment]
@dannon is procedure that someone (e.g. I) should go ahead and merge this to do the revert? 

I'm +1 on reverting, as I'm in agreement #433 didn't follow procedure:
- No +1s
- WIP
- (though I don't see a -1 from you when ctrl-fing)

**Comment by jmchilton** [comment]
-0 on reverting I guess. I agree with @martenson - we should be bold, lean in and fix the problems (this will stale quickly). Ran a workflow, ran some tools, checked login and registration and things seemed fine to me.

**Comment by hexylena** [comment]
There's an argument for being bold, I don't disagree with that at all. I do disagree with:
- WIP tag
- WIP in title
- no +1s 

as of merge time.

From CONTRIBUTING.md:

> Any other pull request requires at least 1 +1 binding vote from someone other than the author of the pull request.

which was not met.

**Comment by hexylena** [comment]
(Sorry to be a stickler for the rules @jmchilton)

**Comment by jmchilton** [comment]
Though not stated formally, we agreed internally that a merge constitutes an implicit :+1: - there are plenty example PRs of this I believe. @bgruening, @martenson, and I believe merging this was the right thing to do.

**Comment by bgruening** [comment]
Hi Dannon,

sorry we didn't saw a minus one and tested it in here in Dublin ... late night hacking :)
We tested a lot of thins, like installing from the TS install, Pages and so on ...

If you still feel uncomfortable, please revert it.

**Comment by hexylena** [comment]
Copied comments from IRC:

> [jxtx] erasche: I think the revert is mandated by procedure, but it is probably safe to give time for others to weigh in.

@jmchilton ok, I'm fine with implicit +1 from merge

**Comment by hexylena** [comment]
Dannon, I'm +1 on this, merge/not as you feel fit.

**Comment by jmchilton** [comment]
Merged revert based on internal agreements about procedures not formally stated - @martenson, @bgruening , and I are still :+1: for merging the original PR as is.

I think we need to move fast on this - it is a big change that will improve a lot.

**Comment by bgruening** [comment]
Yes moving this in fast seems reasonable, before everyone get back and adding new features. I'm not sure when the next release is schedules, but merging this and @natefoo wheel work as soon as possible and get some serious testing seems good for me.

**Comment by martenson** [comment]
@bgruening according to http://galaxy.readthedocs.org/en/latest/releases/15.07_announce.html the planned freeze is Monday July 13 (tomorrow). I am not sure if it is still the plan though. I guess we can postpone it if we want to, as we did before. Another question is whether we want to merge it post-freeze (i.e. mega linting will be part of 15.09/10) or to include it in 15.07.

**Comment by nsoranzo** [comment]
@martenson The consensus at GCC2015 was to merge the original PR as soon as possible since this will stale quickly, so postponing to the next release seems a bad idea to me.

**Comment by dannon** [comment]
I actually disagreed with that consensus.  Just because something is huge (line-count-wise) and we'd like to get it into a #stable release doesn't mean we should just merge it and figure out what broke later.  In my opinion, if you make a PR that's large enough that it's onerous to keep up to date with potential changes, you've earned that extra work.

It's probably important to note that this changes nothing _functionally_ for the stable release other than potentially (even likely?) adding more bugs.  Were it a new feature, I could be swayed.

**Comment by martenson** [comment]
@nsoranzo given we freeze soon we can imo merge soon and the linting will stay on `dev` for next few months so we should be able to find more bugs. Given the scope of the megalint PR the 'testing' basically consist of using Galaxy in any way.
This will result in us having clean release, but also won't end up with obsolete huge PR nobody wants to touch.
Agree with @dannon than there is no pressure to push this PR into 15.07

**Comment by nsoranzo** [comment]
@martenson But backporting fixes from dev to release_15.07 branch or viceversa will be more difficult.

**Comment by dannon** [comment]
@nsoranzo Not sure I'd really worry about the backporting issue.  The scope of changes for anything fixed on #stable should be as surgical as possible fixing _only_ the bug without any excessive refactoring/etc.

Now that you bring it up, though -- this will probably conflict with a significant portion of the 25 open PRs.  How do we want to handle that?

**Comment by nsoranzo** [comment]
@dannon: In the previous cycles we had a lot of changes after release:

```
$ git diff --shortstat v15.01 release_15.01 --
 65 files changed, 396 insertions(+), 188 deletions(-)
$ git diff --shortstat v15.03 release_15.03 --
 88 files changed, 287 insertions(+), 632 deletions(-)
$ git diff --shortstat v15.05 release_15.05 --
 51 files changed, 419 insertions(+), 140 deletions(-)
```

Regarding the open PRs, I don't know how many will have conflicts, I guess we can manually merge them.

**Comment by dannon** [comment]
@nsoranzo Looking at the changes https://github.com/galaxyproject/galaxy/compare/v15.05...release_15.05?diff=split&name=release_15.05, I really don't agree that it's much extra work we'd have to deal with to get stable fixes in based on that release's history.  The shortstat includes javascript, tool changes, test cases, and sample file tweaks.

I looked through open PRs and I actually don't think it'll be as big an issue as I expected.  Much of the work in them is isolated or would be unaffected.

I still think that I would _really_ rather this be the very first thing applied to dev _after_ the freeze.

**Pull request merged**
