### PR TITLE
[17.01] Properly label hidden datasets in dataset selectors

### LINKED ISSUE #3487: Hidden datasets are annotated as unavailable to tools on tool forms at http://usegalaxy.org
Example

Input with status "hidden". **Clarification**: the job will still run with the hidden input (for tools tested)
hidden_dataset_unavailable

After unhiding
hidden_changed_unhidden

May be related to: https://github.com/galaxyproject/galaxy/issues/3481

ping @dannon @galaxyproject/guac

### PR DESCRIPTION
**Pull request by guerler**
This PR improves the label annotation for selected datasets in the tool form. Fixes #3487.

### CODE REVIEW

**Comment by guerler** [comment]
@jmchilton I was trying to add test cases for deleted datasets but when I run the test protocol with `hda1.deleted=True` the dataset gets matched as regular dataset and I wonder why. Does the dataset matcher match deleted datasets too?

**Comment by bgruening** [comment]
@guerler is this still WIP?

**Comment by guerler** [comment]
Only because of the test cases I would like to add. I tested this with deleted datasets on my Galaxy instance and it works fine for me but I could not add an automated test for it yet.

**Comment by guerler** [comment]
Ok, adding the test required a minor adjustment to the active hda identification method in the mock environment.

**Comment by jmchilton** [comment]
Thanks for the fix @guerler!

**Comment by guerler** [comment]
Thank you.

**Pull request merged**
