### PR TITLE
[STABLE] Fix: datasets.purge_async/_purge to allow purging hdas within non-curren...

### PR DESCRIPTION
**Pull request by carlfeberhard**
...t histories

datasets._purge did not allow purging hdas outside the current history.

Also pass exception for easier debugging.
https://sentry.galaxyproject.org/galaxy/galaxy-main/group/4526/
https://biostar.galaxyproject.org/p/11549/

### CODE REVIEW

**Comment by martenson** [comment]
:+1:

**Comment by dannon** [comment]
Fix looks good to me, but I'd prefer it without the exception message surfaced to the user.  Besides this being a stable PR that should keep changes as minimal as necessary to fix the bug, I'm not sure we want that information in a user message.

**Comment by carlfeberhard** [comment]
Where does it surface to the user again?

**Comment by dannon** [comment]
message != msg, even though my brain _fixed_ it for me, you're right.

**Comment by dannon** [comment]
I would still prefer stable PRs only touch the bare minimum necessary to fix the bug, with any extra additions, formatting changes, etc added to #dev post-merge, but this is pretty minor on that front and I think mergeable.

**Pull request merged**
