### PR TITLE
[15.05] fix the data source tools for modendcode with proper URLs

### PR DESCRIPTION
**Pull request by martenson**
ping @blankenberg

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
please do not merge yet, @blankenberg requested a look

**Comment by blankenberg** [comment]
Probably should verify that the default dbkeys being set are still the currently valid ones for the data/builds being sent over.

**Comment by nsoranzo** [comment]
Any fix for wormbase_test (i.e. http://dev.wormbase.org/db/seq/gbrowse/c_elegans/ )?

**Comment by martenson** [comment]
@nsoranzo test data source tools are quite low on priority

**Comment by blankenberg** [comment]
dbkeys have been updated and the external display application links updated as well

**Comment by martenson** [comment]
thanks @blankenberg

**Comment by natefoo** [comment]
:+1:

**Pull request merged**
