### PR TITLE
Resolve Conda Dependencies All at Once

### PR DESCRIPTION
**Pull request by jmchilton**
No real progress yet but I wanted to continue the conversation and ideas that are being discussed in #3299.

### CODE REVIEW

**Comment by jmchilton** [comment]
I've made some significant progress on this this afternoon. I've added a test tool that likely wouldn't work before according to the bug report in #3299 and it seems to work now.

I think what is left is to redo the docs and re-implement the tool shed interaction stuff.

If anyone knows of some potentially problematic tools and wants to help with testing - that would be great.

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Great work John. I created a Docker image tracking this branch so we can start testing:

`docker run -i -t -p 8080:80 quay.io/bgruening/galaxy:jmc_conda`

I will also try some flavors based on this branch. If planemo targets your galaxy branch, it will use this new way to resolve dependencies, correct? I would like to test a few IUC packages if I get some computer resources.

We own you a few :beer:!

**Comment by bgruening** [comment]
@jmchilton this seems to be a valid error: https://travis-ci.org/galaxyproject/tools-iuc/jobs/189690301#L2617

**Comment by mvdbeek** [comment]
> If planemo targets your galaxy branch, it will use this new way to resolve dependencies, correct?

My guess is that if you use `--conda_auto_install` it will. `planemo conda_install` followed by `planemo test` will probably get the fallback "one by one" behavior.

**Comment by bgruening** [comment]
@mvdbeek it acutally works for testing on tools-iuc. Have a look at this branch: https://github.com/galaxyproject/tools-iuc/compare/jmc_conda?expand=1

**Comment by mvdbeek** [comment]
As far as I can tell from https://travis-ci.org/galaxyproject/tools-iuc/jobs/189690515, you're testing deseq2, which only has a single requirement, so this doesn't apply.

**Comment by jmchilton** [comment]
I had a fix for the NPE I believe last night but forgot to push - it would happen when there are unmet dependencies. If I find some time at my laptop today I'll push that out. Thanks for everything you guys!

**Comment by jmchilton** [comment]
Tool shed tests were failing - because fixing the NPE broke something else (added a logic error - my own fault). I've rebase and fixed things up again.

**Comment by bgruening** [comment]
Triggered a new build https://quay.io/repository/bgruening/galaxy
And some new testing here: https://github.com/galaxyproject/tools-iuc/compare/jmc_conda?expand=1

**Comment by mvdbeek** [comment]
Alright, with auto_install enabled it does what it's supposed to do:
```
galaxy.tools.deps.conda_util DEBUG 2017-01-08 16:47:43,308 Executing command: /home/mvandenb/miniconda3/bin/conda create -y --name mulled-v1-d95627189237fac550a9b53956b040c455a7f3682aea67e941022bbc115bc78a bowtie2=2.3.0 samtools=1.3.1
Fetching package metadata ...............
127.0.0.1 - - [08/janv./2017:16:47:46 +0200] "GET /api/histories/f597429621d6eb2b/contents?details=33b43b4e7093c91f%2Ca799d38679e985db&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2017-01-08T15%3A47%3A42.000Z&qv=False&qv=False HTTP/1.1" 200 - "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [08/janv./2017:16:47:46 +0200] "POST /api/tools/toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.3.0/build HTTP/1.1" 200 - "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
Solving package specifications: ..........

Package plan for installation in environment /home/mvandenb/miniconda3/envs/mulled-v1-d95627189237fac550a9b53956b040c455a7f3682aea67e941022bbc115bc78a:

The following NEW packages will be INSTALLED:

    bowtie2:       2.3.0-py35_0    bioconda   
    curl:          7.49.0-1                   
    libgcc:        5.2.0-0                    
    openssl:       1.0.2j-0                   
    perl-threaded: 5.22.0-10       bioconda   
    pip:           9.0.1-py35_1               
    python:        3.5.2-0                    
    readline:      6.2-2                      
    samtools:      1.3.1-5         bioconda   
    setuptools:    27.2.0-py35_0              
    sqlite:        3.13.0-0                   
    tbb:           2017_20161128-0 conda-forge
    tk:            8.5.18-0                   
    wheel:         0.29.0-py35_0              
    xz:            5.2.2-1                    
    zlib:          1.2.8-3                    

Linking packages ...
[      COMPLETE      ]|##########################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate mulled-v1-d95627189237fac550a9b53956b040c455a7f3682aea67e941022bbc115bc78a
#
# To deactivate this environment, use:
# > source deactivate mulled-v1-d95627189237fac550a9b53956b040c455a7f3682aea67e941022bbc115bc78a
#
```
Nice job! We're halfway there to eliminate the cached dependencies :).
Some things that are not yet working is the display of the resolved status 
installed_repo_details
And I guess we also need to call the install_all method at tool install time.

**Comment by bgruening** [comment]
IUC testing looks good so far: https://github.com/galaxyproject/tools-iuc/compare/jmc_conda?expand=1
Galaxy Docker is also happy.

One of the more complicated flavors is also happy with auto_init=True and others (https://github.com/bgruening/galaxy-rna-workbench/blob/master/Dockerfile#L8): https://travis-ci.org/bgruening/galaxy-rna-workbench/builds/189689669#L536

**Comment by mvdbeek** [comment]
@jmchilton 
I have added some code for the install_time creation of the merged environments here:
https://github.com/jmchilton/galaxy/pull/52

**Comment by mvdbeek** [comment]
@jmchilton I have an alternative version of my last PR here https://github.com/jmchilton/galaxy/pull/53/files
I think that one is more correct. I promise I'm done with coding for tonight :)

**Comment by jmchilton** [comment]
@mvdbeek I already modified the previous PR - I'll force push backward and merge your second PR tomorrow morning or tonight if I get some time. At any rate thanks for dealing the tool shed part - that is awesome!

**Comment by mvdbeek** [comment]
Alright, no problem. Very happy about getting the conda resolver into top shape!

**Comment by jmchilton** [comment]
@mvdbeek I pulled out of my cleanup commit and merged your latest PR - thanks again! Is there anything else in your assessment that needs to be done to the code before merging?

We should probably re-write the docs to mention this and the caching stuff together. I'll update #3248 to include this and be sure to cover both before the next release.

**Comment by mvdbeek** [comment]
We should address the regression in the requirement status display soon, but that can be done in another PR if you want to merge now. 👍

**Comment by jmchilton** [comment]
@mvdbeek Ahhh... like the GUI would show the individual requirements don't resolve because they all need to be resolved together to see this new resolution? 

Edit: Ahh - like you have a screenshot of just above this question. Sorry.

**Comment by mvdbeek** [comment]
Yep, I think that's the problem.

**Comment by jmchilton** [comment]
Well that stinks - in neither place in the code is it really broken out in a per-tool fashion. These are done on a per-repository basis.

- We could significantly rewrite these blocks of code to break things out on a per-tool basis.
- We could install the requirements individually also when installing them together. This seems silly in some ways but it might be "more correct" given how requirements have traditionally worked. And I imagine Conda will probably cache things to make it quicker than fresh installs.

**Comment by mvdbeek** [comment]
> We could install the requirements individually also when installing them together. This seems silly in some ways but it might be "more correct" given how requirements have traditionally worked. And I imagine Conda will probably cache things to make it quicker than fresh installs.

What would speak against this:
 - At least on large shared file systems it takes just as long, so it would be good if we can avoid that (and if you have to use --copy it also takes a significant amount of storage).
-  what do you do with numpy for python2 and numpy for python3? ...

Why don't we resolve as in this PR, but make sure that the to_dict representation of MergedCondaDependency contains the individual packages that it is composed of?

The downside is that it would be confusing if a tool that uses bowtie2 and samtools works, but that you'd need to "install" samtools again for a tool that only requires samtools.


> We could significantly rewrite these blocks of code to break things out on a per-tool basis.

In a sense we do resolve on a per tool basis ... I'm just not sure how to arrange this information in an obvious and easily digestible way to users/admins

**Comment by jmchilton** [comment]
@mvdbeek You are the second person in 24 hours to ask me to merge a broken PR. I'm fine with it as long as we are confident it can be tackled before "the next release".

I'm going to work on the Qiime hackathon today and I'll dig into this more tomorrow.

> In a sense we do resolve on a per tool basis ... I'm just not sure how to arrange this information in an obvious and easily digestible way to users/admins

It didn't seem like it at first glace to me, but as far as I got to tracking down this code was these lines:

```
lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py
```

```
        requirements = suc.get_unique_requirements_from_repository(repository)
        requirements_status = view.get_requirements_status(requirements, repository.installed_tool_dependencies)
```

```
        tool_requirements = suc.get_tool_shed_repo_requirements(app=trans.app,
                                                                tool_shed_url=tool_shed_url,
                                                                repo_info_dicts=repo_info_dicts)

        view = views.DependencyResolversView(self.app)
        requirements_status = view.get_requirements_status(tool_requirements)
```

I guess digging into ``get_unique_requirements_from_repository`` and ``get_tool_shed_repo_requirements`` it is clear they have the information on a per-tool basis. I think we just need to pass up the dict in the form ``{"tool_id": <requirements_dict>, **}`` instead of just the ``requirements_dict``. And then when we display things we show the table with like sections for each tool

| Dependency | version | status|
| **tool_id_0** | | | 
| samtools | 0.18 | Installed |
| numpy | 1.0 | Installed |
| **tool_id_1** | | | 
| samtools | 0.18 | Installed |
| six | 1.0 | Installed |

That could be the first step - a second step might be to collapse the dependencies and require you to click on the tool to see them? So an even more tool-centric view of things - which is probably what admins will want to see anyway.

**Comment by bgruening** [comment]
Given the positive feedback from @jmchilton and the :+1: from @mvdbeek let's merge this, it is a big step forward.

**Pull request merged**
