### PR TITLE
Remove microseconds when parsing datetimes for MySQL.

### LINKED ISSUE #2037: Warning: Incorrect datetime value in Galaxy 16.01
Hello

When I try to upload a file, I can see this error in the log file :

`/softs/bioinfo/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:450: Warning: Incorrect datetime value: '2016-03-29 07:25:29.220Z' for column 'update_time' at row 32`

On the interface, the upload job seems to be stuck. The history will never be refreshed.
Otherwise, if I manually click on the “refresh history” icon, it works. The error is not shown again and my file appears in the history.

I run a git pull (see git.txt)
[git.txt](https://github.com/galaxyproject/galaxy/files/195007/git.txt)

```
 * branch            HEAD       -> FETCH_HEAD
Updating 909a549..d15b103
```

Here is the log when I try to upload a file (in galaxylogFirst.txt file).
[galaxylogFirst.txt](https://github.com/galaxyproject/galaxy/files/195009/galaxylogFirst.txt)

The history will never refresh automatically.
Otherwise, if I manually click on the “refresh history” icon, it works. The error is not shown again and my file appears in the history.

Here is the log after I click the “refresh history” icon.
[galaxylogSecond.txt](https://github.com/galaxyproject/galaxy/files/195008/galaxylogSecond.txt)

Here is the result of uname -a

```
uname -a
Linux  2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

We run under PBS Pro but upload is run locally (config/job_conf.xml).
`<tool id="upload1" destination="local"/>`

Does anybody see this ? I hope it will be easy to debug because this is annoying.

Thank you.

Fred

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix #2037.

Also add database/jobs_directory to `.gitignore` .

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@nsoranzo It'd be a shame to lose the milliseconds filter. Are you sure it's not the trailing Z used in the iso8601 format? I can successfully insert dates in the form "2012-06-15T18:33:00.34", but not "2012-06-15T18:33:00Z".

**Comment by nsoranzo** [comment]
@carlfeberhard Similar problems with milliseconds in MySQL have already been reported and fixed, see #1761. Not sure about the trailing Z.

**Comment by dannon** [comment]
@nsoranzo So, following up on what @carlfeberhard said, it looks like mysql (at least recent versions) should support milliseconds just fine.  Are we sure the fix in #1761 is correct, or perhaps it's the Z that was causing errors and and we actually need to fix (correctly) the place in #1761 as well?

**Comment by carlfeberhard** [comment]
I'm now set up but I can't reproduce the error from #2037. Both upload and tool running works fine.

I'm using MySQL 5.6 (Homebrew) with Galaxy at dev and sql_mode is default at "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" (ref: http://stackoverflow.com/questions/11053941/mysql-insert-to-datetime-is-it-safe-to-use-iso8601-format)

**Comment by dannon** [comment]
Did a bit more digging here, and reproduced the error.  This PR does not fix it for me, and stripping the Z does.

Here's a patch to test, I can PR if it fixes it:  https://gist.github.com/51b32f59c29f7fb0bbc70e9c764c5fcb

**Comment by nsoranzo** [comment]
@dannon Thanks for testing and the patch, I will rework this PR in a bit to integrate it.

**Comment by carlfeberhard** [comment]
Hey, guys. I really appreciate the work you've done on this. Remember that since this is my recent work in the development branch you can go ahead and ping me on the trouble or point me at a bug report you see that looks like the same areas I've been working on.

I'm going to go ahead and do a separate pull request on this since it needs other work done as well.

**Comment by carlfeberhard** [comment]
+1 Again, thanks for the work @nsoranzo 
Top section for epoch time will work as is I believe. Gonna fix the rest in post it seems.

**Comment by carlfeberhard** [comment]
And @dannon!

**Pull request merged**
