### PR TITLE
[15.10] Fix citation-model to fail silently/gracefully

### LINKED ISSUE #1877: Workflow containing the meme tool cannot be saved
Any workflow that includes the meme tool from here https://toolshed.g2.bx.psu.edu/view/iuc/meme_meme/798018a73e3f cannot be save.  After clicking the save button, the workflow editor hangs forever.  This issue exists in dev and goes back to at least release 15.10.  Could the fix please be ported back to release 15.10?  Thanks!

no_save

### PR DESCRIPTION
**Pull request by carlfeberhard**
… when a non-parsable bibtex entry is tried

May fix #1877 

Can someone who has or can install meme_meme try this out. imagemagick and libxml error on MacOSX/clang for me.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Yep, that fixes #1877 for me by showing an empty citation. Thanks @carlfeberhard!
:+1:

**Comment by nsoranzo** [comment]
@carlfeberhard Don't worry about the lint failures, they are expected on 15.10.

**Comment by gregvonkuster** [comment]
Thanks @carlfeberhard !!

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Purely javascript changes, test failures are unrelated.  LGTM

**Pull request merged**
