### PR TITLE
Selenium test for Tool-Describing-Tours

### PR DESCRIPTION
**Pull request by anatskiy**
This PR adds a simple test for Tool-Describing-Tours, which checks whether a tour can be generated.

The webhooks path must be overridden before running the test:

```
export GALAXY_CONFIG_OVERRIDE_WEBHOOKS_DIR=$GALAXY_DIRECTORY/config/plugins/webhooks/demo
```

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot selenium test this

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@anatskiy Thanks for this - awesome stuff! I pushed a bunch stuff into your branch that hope maximize the utility of this great work. In short:

- I merged with ``dev`` - where it turns out we totally broke TDTs this development cycle (this test case would have caught that - so awesome!). cecef90
- I pushed a fix for TDTs - the other webhooks may need to be likewise updated - but I don't know. fb91302
- I replaced the test using Cut1 with two tests each using framework test tools loaded with Selenium tests by default - this makes it easier to run these as part of our CI Jenkins setup.
- I created a symbolic link so that tour generator is configured with default test webhooks. Together with the above change - this means these tests will now run for every PR after merged.
- I established and used components and navigates_galaxy.py abstractions for tour generation and navigation based on the work you had.
- In one of the tool tests actually walk the tour (previously we only verified the initial tour popover).
- I used the infrastructure from #4971 to capture some screenshots of tours as they run - so hopefully we will be able to visually inspect the tour running after after Jenkins is done.

**Comment by jmchilton** [comment]
And it works... the tests were included in the Jenkins Selenium tests that are green here and the following screenshots of a test tour were generated:

**Comment by anatskiy** [comment]
@jmchilton oh, wow, thanks a lot for these cool improvements!

**Comment by anatskiy** [comment]
> I pushed a fix for TDTs - the other webhooks may need to be likewise updated

@jmchilton nope,  no other webhook uses the `Tours` module.

**Comment by dannon** [comment]
Nice, looks good!

(and, it's not the `Tours` module specifically, it's how the es6 module exports changed when used from `require()`;  I definitely got everything in `client` and `templates`, but am checking through `config` now.  Followup: Looks like the only other ones were IES, which I already fixed as a part of the main branch, only TDTs got forgotten)

**Comment by bgruening** [comment]
Cool thanks a lot all!

**Pull request merged**
