### PR TITLE
Add script for propagating hashtags in a Galaxy history

### PR DESCRIPTION
**Pull request by anuprulez**
## Background:

To process data using Galaxy, an raw dataset (HDA) is uploaded and few hashtags are added to make it better searchable and identifiable. Then, using different tools/workflows, this raw/input dataset is transformed into multiple new datasets. What if, after running dozens of tools, generating hundreds or thousands of datasets, you realise that you’ve forgotten to tag your input datasets? In this case, the new hashtags will not be propagated to the generated datasets automatically. We require an easy and automatic solution to assign correct hashtags to all of the downstream datasets generated from our inputs, whenever new hashtags are added to any of the datasets in our history. Before going into the further explanation, let’s assign the following labels to the types/names of datasets we would use:

- Input datasets as parent datasets
- Derived/generated datasets as child datasets

This script will solve the situations mentioned above, adding any new hashtags to all derived datasets. The script is written considering a Galaxy history as a tree (data structure) with input datasets as its roots and all the generated ones either as nodes or leaves of this tree. An example history ‘tree’ is shown in the figure below.
<p align="center">
  
</p>                                                                
In the above figure, we can see one input dataset with multiple datasets created from this input, using different tools (Galaxy tools). There can be any number of levels (tree hierarchy) in the ‘history’ tree from the top to bottom.

## How to use the script:
In order to use the script to propagate hashtags from parents to children, a user should remember the hierarchy of their datasets. Wherever hashtags are added to datasets, they will be propagated to all the children of that dataset.  These new hashtags will be appended to the already existing hashtags for each child dataset. To use this script:

1. Acquire your API key from your Galaxy.
2. (Optionally) Get the ID of the history to apply hashtags to. If this id is not supplied, the script will use the most recently updated history.
3. Install [BioBlend](https://bioblend.readthedocs.io/en/latest/#installation) on your machine.
4. Execute: 
`python apply_tags.py <galaxy_url> <galaxy_api_key> <history_id optional>`

Here, <galaxy_url> is the URL of your Galaxy instance. <galaxy_api_key> is the Galaxy API key you obtained from your user preferences. <history_id> is the encoded id of a Galaxy history. It is an optional parameter.

## Example commands: 
Propagate hashtags in a specific history
`python apply_tags.py "https://usegalaxy.org" "*******************" "f2db41e1fa331b3e"`

Propagate hashtags in your most recently updated history
`python apply_tags.py "https://usegalaxy.org" "*******************"`

## A visual example:
1. Upload a raw dataset using an upload tool and add a couple of hashtags (figure below the next point). Each arrow denotes the use of a Galaxy tool to transform one dataset into another.

2. Run a few tools (say ToolA and ToolB) using the input dataset and create new (child) datasets (figure below).
<p align="center">
  
</p>

3. Now, add new hashtags to the input dataset. The figure below shows new hashtags (#new_root_tag1, #new_root_tag2) getting added to the input dataset.
<p align="center">
  
</p>

4. To propagate the new hashtags from parent to child datasets, execute the script using the example commands (here one should use the id of the history created above containing 3 datasets). We can see the child datasets now contain the new hashtags from their parent (figure below).
<p align="center">
  
</p>

## More complex example:
In the previous example, we saw a tree with one level of hierarchy. In the following visual, we would see a more complex example of inheriting hashtags from parents involving multiple levels in the history tree.(figure below).
<p align="center">
  
</p>

## Propagate hashtags in Galaxy:
<p align="center">
  
</p>   
                                                                     
1.fasta &rarr; 3:Replace Text on data 1 &rarr; 4: Text transformation on data 3

In the above figure, “1.fasta” is the root (input dataset). “3:Replace Text on data 1” is the child/derived dataset from the root. “4: Text transformation on data 3” is the child of the second dataset. The hashtags that we see are after executing the script on this history.

Thanks @torhou, @erasche and @bgruening 

**Note**: We are currently working to integrate this idea tightly into Galaxy as a UI feature.

### CODE REVIEW

**Comment by hexylena** [comment]
When I said PR @anuprulez I meant a PR to https://github.com/usegalaxy-eu/website/ with a "post", telling our users about this script existing. Sorry for this confusion!

If galaxy accepts this, great, it will be nice to distribute it with the codebase until we can get some API integration or whatever the long term plans are.

**Comment by anuprulez** [comment]
@erasche Thanks for the clarification. I added a blog post for this and opened a PR.

**Comment by VJalili** [comment]
What would be your strategy for preventing a history item from being polluted by many hashtags when the hierarchy of operations gets deeper? In your solution, a hierarchy with height _h_ can create **at least** _h_ tags in leaf nodes. A hierarchy with _h=3_ in your example, created 5 tags in the leaf node. If tags do not get aggregated, this approach will quickly pollute history items with many tags, which is quite opposite to the base motivation of tags.

**Comment by hexylena** [comment]
This script just allows tagged histories to behave exactly how they would have if they have been tagged properly from the start / along the way, so I do not see it as making the situation any worse or requiring any special solution for aggregating tags. (The example intentionally had many tags to demonstrate the functionality, I imagine real world usage looks different?)

If the user adds many tags, I see it as their intention / decision to help them manage their data, and how they are finding tags useful (whether or not this was the base motivation for the feature.) This is mostly to support the case where they've forgotten to tag the input datasets, or only know the proper tag at the end of their analysis, and want to re-tag everything with a meaningful tag, or want to go back and tag histories that were created before this feature was implemented.

**Comment by anuprulez** [comment]
@VJalili Thanks for your comment. The number of hashtags a child (or derived) dataset can have is limited by the number unique hashtags contained by all its parent datasets (until the root/raw dataset) and its own hashtags. Yes, it is true that as we go down the tree propagating hashtags, datasets will inherit more hashtags but only those added by the user to its parent datasets, nothing more.

**Comment by jmchilton** [comment]
Great - thanks for the neat script @anuprulez! I'm intrigued by the possibility to adding this to the UI - keep up the awesome work.

**Comment by anuprulez** [comment]
@jmchilton thank you for merging :)

**Pull request merged**
