### PR TITLE
Unified webpack4

### PR DESCRIPTION
**Pull request by dannon**
WIP, still, but this swaps us to webpack 4, which is an important step towards more intelligent client shipping.  This swaps webpack to build our styles, and bundle assets, as well.  Will document more about the changes, but I'm working on getting tests working first -- still have a few loose ends to fix, hopefully today, but I want to get the real tests running on jenkins now.

- [x] 4 workflow tests are currently expected to fail, and that's what I'm working to address first
- [x] image mapping/staging for old endpoints like trackster, etc., which do interesting asset management.
- [x] jquery rating styles

Notes:  With the dropped grunt/gulp tasks and other upgrades, this will allow us to unpin from node 9 (10 works, in my hands).  I still want to upgrade karma and qunit, but I did the minimum to get it working for this pass.  Qunit of the version we'll need does *not* work under node 9, though, so we'll want to do that carefully and re-pin against 10, maybe.

### CODE REVIEW

**Comment by dannon** [comment]
I actually cannot believe the tests all passed on jenkins.  There's still a little work for me to do, but that sure is encouraging!

**Comment by Nerdinacan** [comment]
Yay!

**Comment by Nerdinacan** [comment]
Smells like victory.

**Comment by dannon** [comment]
Not quite, but it's getting there.  Lots of dark corners to check and fix.

**Comment by dannon** [comment]
I've just re-merged this with dev to fix things.  It'd be great to get it merged in quickly, as the style links/reconfiguration will quickly conflict again.

All tests will pass, though I'd bet we'll find more dark corners that have mis-mapped assets.  Those will be easy to fix, though.

**Comment by martenson** [comment]
What do I need to do to make this work? Fresh checkout gives me this on startup:

screenshot 2018-10-30 13 17 30

**Comment by dannon** [comment]
@martenson You should just have to make the client -- do you have SKIP_CLIENT_BUILD in your environment, or did it fail to build?

And, if neither of those are the cause, can you look for those files (*.chunk) in /static, and see if/where they are?

**Comment by guerler** [comment]
I noticed that the tag-plus button in grids is not displayed properly.

image

**Comment by martenson** [comment]
I think the problem was I checked for `SKIP_CLIENT_BUILD` instead of  `GALAXY_SKIP_CLIENT_BUILD`. My bad.

**Comment by dannon** [comment]
@guerler Where did you see the fugue reference (what URL/feature)?  The map, we may have to look at down the road, it isn't behaving how I want it to exactly, yet.

**Comment by guerler** [comment]
@dannon e.g. the workflow list at 127.0.0.1:8080/workflows/list.

I also noticed a minor style glitch related to buttons e.g. at 127.0.0.1:8080/admin/repositories:

image

Thank you so much for working on this!

**Comment by martenson** [comment]
I see the same as @guerler. Also the admin interface seems a tad broken due to missing images. 

screenshot 2018-10-30 16 39 34

**Comment by dannon** [comment]
Ok, give me a sec to fix those mappings, definitely a missing image/images in the admin list.

**Comment by martenson** [comment]
it is the same for the fugue thing, that is the tag plus icon 
screenshot 2018-10-30 16 51 22

**Comment by dannon** [comment]
@martenson Yep, thanks.  I have a fix for that, looking for more right now.

**Comment by martenson** [comment]
`ok_small.png` `delete_tag_icon_gray.png`

**Comment by dannon** [comment]
(the above problems were mainly uwsgi's static mapping not allowing the symlink following -- I was testing against paste)

**Pull request merged**
