### PR TITLE
Fix issue #667 Tool installation failure due to dependency history

### PR DESCRIPTION
**Pull request by mvdbeek**
Hopefully fixes issue #667, see my comments there.
I would really appreciate feedback.

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek please remove the WIP if we can start testing.

If anyone wants to test, this PR is now in: `docker run -it -p 8080:80 bgruening/galaxy-stable:experimental`

**Comment by mvdbeek** [comment]
@bgruening removed WIP tag, thanks for the image!

**Comment by bgruening** [comment]
I installed a lot of packages, new and old revisions ... everything looks good.
:+1: 
@martenson feel free to merge if you are happy.

**Comment by mvdbeek** [comment]
OK, so I discovered a few additional problems, leading me to think that this approach is not the right one.
For example: 
Uninstall dependent package "A" and package "B" that depends on package A.
Then installing package A will not install package B again.

Sorry for the fuss, I'll not be able to occupy myself with this during the next week, so if anyone wants/can continue, please do so!

**Pull request closed without merging**
