### PR TITLE
Partial fix of missing page titles

### PR DESCRIPTION
**Pull request by anuprulez**
This PR partially fixes the issue [4416](https://github.com/galaxyproject/galaxy/issues/4416). For workflow list, the title of the Galaxy is displayed as "Workflow home" instead of empty. 

I think the script `galaxy/scripts/apps/analysis.js` which serves as the starting point for loading the resources of a route can be a good place to update the HTML titles for the files being transformed from mako to javascript.

### CODE REVIEW

**Comment by martenson** [comment]
I am unsure about using the analysis app for page title management. imo ideally we would use the title much more (folder names in datalibs, dataset name in details) and in a dynamic way (number of jobs running/waiting) which I think would make the global management of this convoluted.

Opinions on this @guerler ?

**Comment by dannon** [comment]
@anuprulez After talking to @guerler about this, I think the approach in #4578 may be a little more flexible for us in the long run.  Does that look good to you, too?

**Comment by anuprulez** [comment]
@dannon Thanks. #4578 is better. :+1:

**Comment by anuprulez** [comment]
I am closing this PR as #4578 suggests a better approach

**Pull request closed without merging**
