### PR TITLE
[17.09] Add message (error and info) display to workflows display list.

### LINKED ISSUE #4712: Importing workflow (that is not a workflow) does not display error
Importing a "workflow" by e.g. URL, that isn't a valid format or isn't accessible, no longer displays the error -- just looks like a page refresh to the user. The error message is still encoded in the page's URL query parameters, however. release_17.09

### PR DESCRIPTION
**Pull request by dannon**
This fixes #4712.

Not a huge fan of the toastr display, but it's the only mechanism this page uses to display messages; reused it for consistency.

I also came across and fixed another two bugs while I was at it.  One undefined variable that'd be hit in particular situations, and another error generating the context menu for workflows shared to you.

### CODE REVIEW

**Comment by dannon** [comment]
@nsoranzo Thanks for the tags, etc., but not quite for review yet.

**Comment by dannon** [comment]
Ok, now it's ready!  (fixed a few more bugs while I was at it)

**Comment by dannon** [comment]
Since it's reasonably closely related, @guerler suggested combining https://github.com/galaxyproject/galaxy/pull/4717 here, so that changeset has been cherry-picked into this branch for easier review/merging.

**Comment by guerler** [comment]
👍

**Comment by mvdbeek** [comment]
Thanks @dannon!

**Comment by blankenberg** [comment]
thanks!

**Pull request merged**
