### PR TITLE
Ethercalc Interactive Environment

### PR DESCRIPTION
**Pull request by shiltemann**
Hi All,

I've made an interactive environment for the [Ethercalc](https://ethercalc.org/) spreadsheet application.

The corresponding docker definition can be found here: https://github.com/shiltemann/ethercalc-galaxy-ie

This will run on any tabular or csv file, load this dataset into Ethercalc, and upon save will give the option of saving in either of those two formats, and will automatically save an audit trail to the history as well,  recording all the edits made.

Let me know what you think, and any comments/suggestions :)

ping @bgruening @erasche 

image

image

image

### CODE REVIEW

**Comment by hexylena** [comment]
Woah, an audit trail. That's really really awesome!

**Comment by blankenberg** [comment]
awesome :)

**Comment by martenson** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
Overall:

- This is awesome! I've wanted an ethercalc IE forever. No more need to (download, change a single cell, re-upload), it is so much easier to edit "in place" so to speak. I am getting to the point of "why leave galaxy for the desktop ever". 
- I really love the audit trail functionality, that makes the inner functional programmer in me quite happy.

Architectural:

- The container redirects to galaxy once the dataset is saved, is it possible to disable this behavior? While this neatly solves the "unrefreshed history" problem, it's a suboptimal UX to be forced to leave their work just because they want to save/checkpoint their work. If this can be fixed (or we know there is no way to fix it), this has my :+1: 
  - Edit: I didn't get around to testing without (hit some other issue), but I'm guessing it is this line. https://github.com/shiltemann/ethercalc-galaxy-ie/blob/master/Docker/main.js#L216 maybe some other way to disable the save thingy, as you mentioned.

Nitpicks:

- The save button is hard to find, but this is an upstream problem. Nothing you can reasonably do there.

**Comment by shiltemann** [comment]
thanks for testing :) 

huh, it doesn't redirect to galaxy upon save for me, will have to look into that..

Edit: seems to happen when serving from subdirectory

**Comment by mvdbeek** [comment]
That does look awesome!

**Comment by bgruening** [comment]
I remember that ethercalc was one of our first ideas after Jupyter and RStudio, so this is great! Big :+1: !

As usual I'm a little bit worried about reproducibility here, but everyone Admin is able to decide this on their own.

Thanks Saskia, see you soon!

**Comment by shiltemann** [comment]
@bgruening it is actually possible to replay those audit trail commands via the API, so was thinking of trying to make a tool that takes a tabular/csv file and an audit trail and replays the actions on top of the input file, that way it could also be used in workflows, what do you think? (you can use docker images in tools right?)

**Comment by hexylena** [comment]
Ok, @shiltemann has fixed the nested/redirection issue in the container. All looks good now! :+1:

**Comment by bgruening** [comment]
Nice!!!

**Comment by nekrut** [comment]
@natefoo @martenson : can we enable this on test asap? this truly saves a lot of issues that are too difficult for people to do with Jupyter
@shiltemann - this is awesome

**Comment by CicoZhang** [comment]
Wow! Cool!

**Pull request merged**
