### PR TITLE
remove TS hg middleware

### PR DESCRIPTION
**Pull request by martenson**
This PR completely removes the hg middleware in TS thus removing the push functionality (which is long deprecated, retroactively disabled since 16.01 and unwanted).

As a side effect we will not track `times_downloaded` for hg clones but we can probably re-add this functionality in hg.py controller.

### CODE REVIEW

**Comment by martenson** [comment]
the TS tests should pass: https://jenkins.galaxyproject.org/view/Marten/job/martenson-docker-toolshed/12/console

**Comment by nsoranzo** [comment]
Anything to be done in lib/galaxy/webapps/tool_shed/controllers/hg.py ?

**Comment by martenson** [comment]
@nsoranzo now when you point at it I might be able to remove some code from there too, gimme a sec

**Comment by martenson** [comment]
@nsoranzo done, thanks

**Comment by dannon** [comment]
+1, good to start cleaning this out.

**Pull request merged**
