### PR TITLE
[19.05] Re-version 19.05 as 19.05 - introducing the new 19.05.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
dev got merged into 19.05 at some point, we don't really know when or how but we decided it would probably just be safest to call the thing on usegalaxy.org right now release_19.05.

**Review by dannon — APPROVED** [review]

**Comment by natefoo** [comment]
It'd be cool if we could at least figure out how/when. Interesting that git makes this so difficult.

**Comment by nsoranzo** [comment]
I think the issue is commit ee89a482bc99b36026b170e5680b5a88a860a4bb, which was pushed to the `release_19.05` branch (in addition to `dev`).

**Comment by natefoo** [comment]
@nsoranzo Ah, good catch! How'd you find it?

**Comment by dannon** [comment]
@natefoo I posted it on Gitter last night.  I still don't understand the PR reference on that commit, though.

(to elaborate, the way I found it was basically manually bisecting to check for the version string on all merge commits to release_19.05, since (as you found out as well) the automated bisect just finds the source commit)

**Comment by natefoo** [comment]
@dannon ah thanks!

~~For the record:~~

> ~~I generated it doing something like `git log --no-merges allgood..nobueno` to find the substantive commit differences.~~  
> ~~Where `allgood` and `nobueno` are branches checked out at af95770d600f9b34a48f93769757e11cd277d8b8 and ee89a482bc99b36026b170e5680b5a88a860a4bb respectively.~~

**Comment by martenson** [comment]
+0.1

I think we should backport https://github.com/galaxyproject/galaxy/pull/7935.

fwiw these are the PRs that got to release and shouldn't:

https://github.com/galaxyproject/galaxy/pull/7746
https://github.com/galaxyproject/galaxy/pull/7827
https://github.com/galaxyproject/galaxy/pull/7858
https://github.com/galaxyproject/galaxy/pull/7874
https://github.com/galaxyproject/galaxy/pull/7859
https://github.com/galaxyproject/galaxy/pull/7860
https://github.com/galaxyproject/galaxy/pull/7840

in addition to the [merge commit](https://github.com/galaxyproject/galaxy/commit/ee89a482bc99b36026b170e5680b5a88a860a4bb) being weird, [this one](https://github.com/galaxyproject/galaxy/commit/513fb016dcdb991b9a9aa5dbcbdb2cbef559b95a) is also weird

**Comment by nsoranzo** [comment]
> @nsoranzo Ah, good catch! How'd you find it?

I just grepped the output of `git log release_19.05` for the most recent `Merge ...release_19.05' into dev`.

The last "correct" commit @dannon mentions (af95770d600f9b34a48f93769757e11cd277d8b8) is simply the right parent of ee89a482bc99b36026b170e5680b5a88a860a4bb .

**Comment by dannon** [comment]
@natefoo That command was for generating https://gist.github.com/dannon/b4bb6dc5c470311957500d34eee01961, which was the extra changesets included.

**Comment by natefoo** [comment]
D'oh

**Comment by dannon** [comment]
I'll backport #7935.

**Comment by jmchilton** [comment]
Fixed up PR tags - re-tagging those listed by @martenson and went through a bunch of older 19.09 PRs not listed and made sure they weren't in release_19.05. Thanks all.

**Pull request merged**
