### PR TITLE
Git error reporting - bug fixes and better error handling

### PR DESCRIPTION
**Pull request by selten**
-  Deal with unavailable Tool Shed or connectivity issues
-  Improve stacktrace for debugging of the system

### CODE REVIEW

**Comment by jmchilton** [comment]
Can you rebase this into a single commit so we don't touch those data manager files in the git history? If you can do that in the next couple days, I'll merge this and get it into the next release which we are freezing soon.

**Comment by selten** [comment]
@jmchilton Was this what you intended for me to do?

**Comment by jmchilton** [comment]
Looks good, thanks! Will merge it once the first few tests come out green.

**Comment by mvdbeek** [comment]
Great, thanks @selten!

**Pull request merged**
