### PR TITLE
[master-toolshed] merge in release_16.07

### PR DESCRIPTION
**Pull request by martenson**
ping @natefoo

### CODE REVIEW

**Comment by natefoo** [comment]
Just a straight branch merge, what could possibli go wrong?

**Comment by martenson** [comment]
@natefoo dunno, that's why I merely opened it and you are the one merging it

**Comment by martenson** [comment]
thanks @jmchilton

**Comment by natefoo** [comment]
Thanks @jmchilton. I was waiting for tests.

**Comment by martenson** [comment]
@natefoo sorry, I motivated @jmchilton to review this, as I needed a quick turnaround to fix Jenkins and Travis builds (Travis is now fixed and jenkins TS tests will be once we have https://github.com/galaxyproject/galaxy/pull/2959/commits/5e7ee28e0d6937fa53f39b350e04357b554ce9ae in dev)

**Pull request merged**
