### PR TITLE
More work toward more Jenkins testing.

### PR DESCRIPTION
**Pull request by jmchilton**
Replace more CasperJS API tests with Python API tests and small improvements to run_tests.sh aimed improved Docker testing image and adding the integration tests to Jenkins.

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@jmchilton somehow you broke selenium with config changes on jenkins? I checked the diffs and both were reasonable... :/

**Comment by martenson** [comment]
hmm, now the test triggers, magic

**Comment by martenson** [comment]
however I do not think we have the `xunit-${BUILD_NUMBER}.xml` file with results available for selenium, do we?

**Comment by jmchilton** [comment]
I attempted to create that file - I'll figure out why it isn't there.

**Comment by jmchilton** [comment]
Decomposing this into smaller PRs with some updates also.

**Pull request closed without merging**
