### PR TITLE
Rework Jupyter IE for additional_ids handling.

### PR DESCRIPTION
**Pull request by jmchilton**
- Add a new option ``use_volumes`` to the Docker config.
- If using volumes, do nothing differently.
- If not using volumes, set ADDITIONAL_IDS in the environment for the IE itself to fetch (requires https://github.com/bgruening/docker-jupyter-notebook/pull/17).

### CODE REVIEW

**Comment by jmchilton** [comment]
xref #3974 - this will require updating main's GIE configuration and rebuilding a new container.

**Comment by hexylena** [comment]
@jmchilton any interest in adding these changes to rstudio.mako as well? I'm happy to test.

**Comment by jmchilton** [comment]
@erasche I saw you already started work on this from the container side of things - do you want me to just make the same changes to the mako entry points then?

**Comment by hexylena** [comment]
@jmchilton yes, that'd be perfect!

**Comment by hexylena** [comment]
yep, perfect! Thanks.

**Comment by hexylena** [comment]
Tested this PR in all the configurations that I use regularly, looks good! :+1: Should this new option be documented in the individual .ini.sample config files?

**Comment by jmchilton** [comment]
@erasche Good point - I've added a comment about this new option to the two most relevant GIEs.

**Comment by hexylena** [comment]
Looks good, thanks @jmchilton

**Comment by hexylena** [comment]
I'm happy to merge, but the test seems to be failing due to ConventionChecker missing? Is that safe to merge over?

**Comment by jmchilton** [comment]
@erasche Yeah - that is an unrelated CI problem. I have an open PR to fix that.

**Pull request merged**
