### PR TITLE
Upgrade sqlalchemy to 1.0.0 (hooray!)

### PR DESCRIPTION
**Pull request by dannon**
Tested under sqlite, mysql, and postgres and while there a few (mostly not even new) optimization warnings to follow up on, everything (including migrations, etc) appears to work perfectly.  Lots of new features, lots of performance improvements.

For anyone interested, migration document here:  http://docs.sqlalchemy.org/en/rel_1_0/changelog/migration_10.html

### CODE REVIEW

**Comment by martenson** [comment]
awesome!
:+1:

**Comment by carlfeberhard** [comment]
Integer! +1

**Comment by jmchilton** [comment]
:+1:

**Comment by davebx** [comment]
+:100: even after the fact.

**Pull request merged**
