### PR TITLE
Add a simple UI to manage tool dependencies

### PR DESCRIPTION
**Pull request by mvdbeek**
This page simply lists all loaded tools and their dependency status.
On the left are checkboxes to select multiple tools, and at the bottom
is a button to install the selected tool dependencies.

Ping @martenson

### CODE REVIEW

**Comment by mvdbeek** [comment]
screen shot 2017-01-24 at 10 48 19 pm

**Comment by mvdbeek** [comment]
I've added another view that focuses on dependency environments.
screen shot 2017-01-26 at 5 33 35 pm
I think that's quite useful to keep track of what is using the all-in-one resolution ~~and what would benefit from caching (which I will also add, now that I'm already on it ...)~~

**Review by martenson — APPROVED** [review]
I fixed a forgotten `</div>` that prevented it from rendering properly and tried to improve UX a bit. The functionality works for me and will be useful to admins I believe.

@mvdbeek could you please add a short summary to the top of the page that explains what the user sees and can do and why? I tried to come up with something but I am bad at explaining things I don't understand well. ;)

**Comment by mvdbeek** [comment]
@martenson is it sth like this that you had in mind?
screen shot 2017-03-08 at 12 09 35 pm

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@mvdbeek Yes, thanks!

Also what happens when you install non-TS dependency using Conda? Does it also follow the resolver conf?

**Comment by mvdbeek** [comment]
> Also what happens when you install non-TS dependency using Conda? Does it also follow the resolver conf?

Yes, the same rules apply. The critical part through the code is the same then the one that is being followed when you run a job.

**Pull request merged**
