### PR TITLE
[23.0] Don't build Docker image when pushing to release branches  

### LINKED ISSUE #16053: Docker images being pushed with the same tag
Merging code into `release_*` branches causes a new Docker images to be built and pushed with the release version number as the Docker tag. This can result in images with the same tag that are incompatible with each other and may contain breaking changes. Discussion about versioning policy aside, this can result in problems when users attempt to add a new node to a Kubernetes cluster and get a different Docker image even though they are pulling the same tag (e.g. galaxyproject/galaxy-min:22.05).

Until a solution for versioning the release Docker images is developed no more release images should be pushed using the 23.0 (or other release) version numbers.

- [x] Disable building release Docker images in the dev branch
- [x] Disable building release Docker images in release_* branches, at least release_23.0
- [x] Add a new GitHub action to build Docker images for release_* branches with a new revision number. That is 23.0.1, 23.0.2, etc.

### PR DESCRIPTION
**Pull request by ksuderman**
Disable building Docker images when code is pushed to `release_*` branches.  Closes #16053 

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by ksuderman** [comment]
I have updated this pull request so now the Docker image builds are triggered as follows:

1. pushes to the `dev` branch are built as they have been in the past. e.g `galaxyproject/galaxy-min:dev`
1. pushes to `release_*` branches have the string `-auto` appended to the release version, eg `galaxyproject/galaxy:23.0-auto`.  Maybe this should be `-latest`?
1. tagging a release on GitHub causes a "stable release" image to be built and pushed with just the release version number, eg `galaxyproject/galaxy:23.0`

**Review by mvdbeek — APPROVED** [review]
I think that's fine in principle, but you should also definitely try updating your clusters as soon as there is a new image. We only merge bug fixes to release branches, so ideally you would always update as soon as we push to the release branch.

**Review by nuwang — APPROVED** [review]
I think the idea of using tags to trigger a fixed, immutable build sounds good, as that ties to a specific revision.

You've referred to tagging a release on GitHub as a "stable release", but that seems more like an immutable release than a stable release? E.g. rancher's notion of stable is even more fluid, and is continuously updated. Rancher's stable can be contrasted with latest, in that it's not a bleeding edge dev environment, but is nevertheless, a pretty up-to-date, QA assured version.

By that definition, I think all Galaxy release branches are "stable", in that they've already gone through a QA process and only bug fixes go in.

So by those definitions, release branches could be named <release>-auto or <release>-stable, but probably not latest.

**Comment by ksuderman** [comment]
Yes, I have been using _stable  release_ to mean _immutable release_.  Rancher has a _stable_ release tag, but those always point to immutable versions.  Galaxy doesn't have immutable versions/releases, that is, there have been >30 changes merged into `release_23.0` since it was tagged, and it is still version 23.0 rather than 23.0.1, 23.0.2 etc.  
> By that definition, I think all Galaxy release branches are "stable", in that they've already gone through a QA process and only bug fixes go in.

I disagree.  The revision that gets tagged has gone through QA, but none of the bug fixes that get merged have. That is how two breaking changes* were deployed in 22.05.  For that reason I would be -1 on appending `-stable` to the tag name for any Docker image built from a `release_*` branch.  Also, if a PR does break something (I'm looking at you #14726) it is difficult to go back to a previous stable version as there is no "previous stable version", just a chain of mutations to the branch.

* the changes broke Kubernetes deployments, they didn't necessarily break Galaxy itself.

**Comment by mvdbeek** [comment]
> I disagree. The revision that gets tagged has gone through QA, but none of the bug fixes that get merged have.

Well, bug fixes fix bugs, so they definitely were found in QA-like activity (aka users reporting these bugs). I think there is a much smaller surface area in bug fixes than new features that would require full blown QA. I would also say that none of the fixes found during the pre-release QA actually get tested more extensively before the release. That's simple the job of the person fixing the bug.

**Comment by mvdbeek** [comment]
> (I'm looking at you #14726)

It's a little unfortunate that we hear about problems with PRs more than half a year later. If you still know what exactly was the issue it'd be great to hear what it was and how it was fixed, because I don't see anything linked up against that PR.

**Comment by ksuderman** [comment]
I am not sure why the cross ref in galaxyproject/galaxy-helm/pull/383 wasn't shown in that PR...

However, the issue was that the `create_db.sh` script was removed and replaced with `manage_db.sh init`.  I don't know if anyone would reasonably call that a _breaking change_ in Galaxy, but it broke Kubernetes deployments.  We didn't notice until our tool tests started failing because Galaxy wouldn't launch.

Even more insidious was the time an innocuous change (can' find the PR right now) triggered a Docker build and an unpinned requirement (TPV) upgraded from 1.4 to 2.0 resulting in a user that could not add a new node to their cluster since the `galaxy-min:22.05` image being pulled was incompatible with the `galaxy-min:22.05` images used by the other nodes in the cluster.  Why even have version numbers if the users can not reliably use them to distinguish between revisions?  And I am just talking about how the Docker images are versioned.  Users with production clusters need to **know** that the version they pull today is the same as the version they pulled yesterday.  We can't guarantee that at the moment.

> Well, bug fixes fix bugs,

But that does not mean they don't also introduce bugs 😉 And I am not suggesting they need to go though the whole release testing process, but the fact is that they don't get the same QA treatment.

**Comment by nuwang** [comment]
> Galaxy doesn't have immutable versions/releases, that is, there have been >30 changes merged into release_23.0 since it was tagged, and it is still version 23.0 rather than 23.0.1, 23.0.2 etc.

If many bug fixes were merged in, that's a good thing, and we want those bug fixes to get into the image as soon as possible. We don't have any tooling yet for automatically bumping the revision number. Nor do we have the time to manually tag versions or increment version numbers every time there's a change. Which means that, as a purely practical matter,  the chart must point to an automatically built version anyway, which does not solve the problem of "undetected change". This is not unprecedented. Even with rancher, the stable version changes and no one knows right? They do however, support precisely tagged versions, which this PR partly fixes.

To make this work in the sense that you are suggesting, we need several additional things:

a) Automatic tooling for tagging and building the image + tooling for updating the image in the helm chart and making a new chart release
b) Better test suites - both the migration and TPV examples are two examples of not having adequate integration test coverage. If that test coverage had been there, any failures would have been detected prior to an anvil deployment.

> And I am just talking about how the Docker images are versioned. Users with production clusters need to know that the version they pull today is the same as the version they pulled yesterday. We can't guarantee that at the moment.

Sans the above tooling, I don't see how we can provide that guarantee by default. Users will need to pick a specifically tagged image if they want such guarantees, but deal with bug fixes etc. manually. It looks like AnVIL is a good candidate for that.

**Comment by ksuderman** [comment]
@afgane Any chance you can review/approve this PR so we can get it merged?  I will work on integration tests when I am back.

**Comment by mvdbeek** [comment]
Actually this is fine then

**Pull request merged**
