### PR TITLE
UI, history: update using xhr date header

### LINKED ISSUE #2242: History not updating when client time ahead of server time
This is with release_16.04 and OSX / chrome as client.
To reproduce, set the clock a few minutes ahead of the server time and run a tool.
Notice that the history never refreshes (past the initial "grey state" ). I guess this is related to #1788
Setting the clock to the correct time fixes this, but unfortunately our university's firewall is blocking access to apple's time server, so this is a bit annoying.

Ping @carlfeberhard, do you have any idea how to make this more robust ?

### PR DESCRIPTION
**Pull request by carlfeberhard**
Makes the 'updated since' contents query based on any previous update's
ajax Date response header instead of the client time. This may offer
more protection against incorrect client time.

This works (and may work better than the previous method) because the
Date header is floored and not rounded and seems to mark a time before
the contents query is made.

Resolves #2242 (hopefully)

### CODE REVIEW

**Comment by nsoranzo** [comment]
@carlfeberhard I think this should target `release_16.04`, if possible.

**Comment by mvdbeek** [comment]
Definitely fixes #2242 for me, thanks for working this out @carlfeberhard !
And yes, 16.04 would be good.

**Comment by dannon** [comment]
@carlfeberhard This looks like a good fix to me, I like it.  Do you want this applied to 16.04 as well?  If so, would you rather retarget this PR or cherrypick the change back?

**Comment by carlfeberhard** [comment]
@nsoranzo @dannon No, it's meant for 16.07. This isn't a fix for a bug, it's a workaround/enhancement for the corner case where a client is misconfigured. 16.04 is frozen and things that are central like this need more time to shake out before they're in production IMO.

@mvdbeek Glad it's working.

**Comment by martenson** [comment]
thanks @carlfeberhard

**Comment by dannon** [comment]
Cool, just wanted to check what your intent was.

**Pull request merged**
