### PR TITLE
Managers, sharable: implement list_shared_with; API, histories: imple…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…ment api/histories/shared_with_me (with order, limit, offset, and filters as index)

Addresses #595

### CODE REVIEW

**Comment by martenson** [comment]
awesomeness in a form of code!
:+1: 
ping @Tarostar

**Comment by dannon** [comment]
Looks good, works.

**Comment by jmchilton** [comment]
Retroactive :+1:

**Comment by Tarostar** [comment]
Very happy with this and we got it working for Galaxy Portal, many thanks for adding it.

**Comment by martenson** [comment]
good job @Tarostar and @carlfeberhard  !

**Pull request merged**
