### PR TITLE
Add "Save as" as an option in the workflow editor

### PR DESCRIPTION
**Pull request by tmcgowan**
Enhancement to allow for "Save as" functionality in workflow editing. User can save an existing workflow under a new name. After saving, the user is moved back to the workflow index page.

save_as_menu
save_as_name

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Hacktoberfest contribution is coming! Thanks @tmcgowan for fixing https://github.com/galaxyproject/galaxy/issues/3000!

**Comment by dannon** [comment]
This is a great start @tmcgowan, thanks for taking a look at this.  I tried it out locally and it does create a copy of the workflow, but there are a few issues.  

The most prominent of these (and what I think might be a common case for this functionality) is that it actually saves _both_ the existing workflow and the copy.
- Have a workflow with 2 steps.
- Add a step or two (without saving)
- Click 'Save as', enter a new name.
- Wait a second and you'll be redirected to the workflows list.  

At this point, note that both the copy _and_ the old workflow will have the new steps you've added.  This needs to be changed to make sure that original workflow isn't unintentionally saved.

The redirect seems problematic too, to me.  Part of the issue is that during that time it takes to save (which may not be insignificant on slow connections or with very large workflows), the user can continue to click, edit, make changes in the editor and will be interrupted by the redirect randomly once the $.ajax returns.  If we _do_ want a redirect, I'd suggest we need the overlay to stay and prevent interaction while waiting for that save/redirect.  I'd probably go a step further though and just say we should remove the redirect.  With "Save As", I think users have likely made changes to a workflow, think "Hrmm, these changes are more experimental than I thought and I don't want to lose my previous revision, let's save this as a new name and keep going".

Again, nice start, thanks for tackling this!  Let me know if you want any help digging into the issues above.

**Review by dannon — CHANGES_REQUESTED** [review]
(see previous comment -- really the first issue is the only one that _must_ be fixed before merge)

**Comment by tmcgowan** [comment]
@dannon, no problem. The save behavior and redirect was intentional. I wavered on how to handle that. Makes sense to stay in place and only have the new version reflect changes. I'll make the changes needed.

**Comment by dannon** [comment]
@tmcgowan Thanks!

**Comment by martenson** [comment]
I renamed the PR and moved to WIP

**Comment by tmcgowan** [comment]
Now the save as functionality reflects the @dannon change requests.
1. Source workflow is unaffected by the Save as
2. Once the 'save as' workflow is saved, it is loaded into the edit view
3.  Overlay is in place until all operations are complete

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@dannon would you please re-visit your review?

**Comment by dannon** [comment]
@tmcgowan Thanks for the tweaks, looks great now!  Merged locally to resolve the conflicts.

**Comment by dannon** [comment]
Sure, thanks for the ping, I'll check it out

**Pull request merged**
