### PR TITLE
[17.05] Check name type in legacy export section

### LINKED ISSUE #4202: Workflow export bug
Hi all, I am experiencing a strange bug regarding downloading of a workflow .ga file.

when my workflow involves the mothur [`count.seqs`](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/count.seqs.xml) tool, I get the following error message when attempting to export the .ga file: 

```
Module galaxy.web.framework.middleware.error:154 in __call__
>>  app_iter = self.application(environ, sr_checker)
Module paste.recursive:85 in __call__
>>  return self.application(environ, start_response)
Module paste.httpexceptions:640 in __call__
>>  return self.application(environ, start_response)
Module galaxy.web.framework.base:135 in __call__
>>  return self.handle_request( environ, start_response )
Module galaxy.web.framework.base:214 in handle_request
>>  body = method( trans, **kwargs )
Module galaxy.webapps.galaxy.controllers.workflow:261 in display_by_username_and_slug
>>  return self.export_to_file( trans, encoded_id )
Module galaxy.web.framework.decorators:55 in call_and_format
>>  return _format_return_as_json( rval, jsonp_callback, pretty=( pretty or trans.debug ) )
Module galaxy.web.framework.decorators:316 in _format_return_as_json
>>  json = safe_dumps( rval, **dumps_kwargs )
Module galaxy.util.json:79 in safe_dumps
>>  dumped = json.dumps( *args, allow_nan=False, **kwargs )
Module json:250 in dumps
>>  sort_keys=sort_keys, **kw).encode(obj)
Module json.encoder:209 in encode
>>  chunks = list(chunks)
Module json.encoder:434 in _iterencode
>>  for chunk in _iterencode_dict(o, _current_indent_level):
Module json.encoder:408 in _iterencode_dict
>>  for chunk in chunks:
Module json.encoder:408 in _iterencode_dict
>>  for chunk in chunks:
Module json.encoder:408 in _iterencode_dict
>>  for chunk in chunks:
Module json.encoder:332 in _iterencode_list
>>  for chunk in chunks:
Module json.encoder:408 in _iterencode_dict
>>  for chunk in chunks:
Module json.encoder:442 in _iterencode
>>  o = _default(o)
Module json.encoder:184 in default
>>  raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.tools.parameters.basic.RuntimeValue object at 0x7f76cc02a990> is not JSON serializable
```

This can be reproduced on Main by making a workflow containing nothing but this tool.

ping @guerler any ideas?

### PR DESCRIPTION
**Pull request by guerler**
Fixes #4202.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@guerler Wrong target branch.

**Comment by guerler** [comment]
Thanks @nsoranzo for catching that.

**Comment by nsoranzo** [comment]
If I understand correctly, the problem was triggered by the input dataset named `name` in the [count.seqs](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/count.seqs.xml) tool:
```
<param name="name" type="data" format="mothur.names" label="name - Sequences Name reference"/>
```
Right?

**Comment by guerler** [comment]
Correct.

**Review by nsoranzo — APPROVED** [review]

**Comment by guerler** [comment]
Thanks guys.

**Pull request merged**
