### PR TITLE
Update Mercurial to Py3-compatible v5.2, and all other deps

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by mvdbeek** [comment]
That looks relevant:
```
tool_shed.repository_registry: ERROR: Handled error adding entry to repository registry
Traceback (most recent call last):
  File "/galaxy/lib/tool_shed/repository_registry.py", line 59, in add_entry
    certified_level_one_tuple = self.get_certified_level_one_tuple(repository)
  File "/galaxy/lib/tool_shed/repository_registry.py", line 164, in get_certified_level_one_tuple
    latest_installable_changeset_revision = metadata_util.get_latest_downloadable_changeset_revision(self.app, repository)
  File "/galaxy/lib/tool_shed/util/metadata_util.py", line 93, in get_latest_downloadable_changeset_revision
    repository_tip = repository.tip(app)
  File "/galaxy/lib/tool_shed/webapp/model/__init__.py", line 297, in tip
    return str(repo.changectx(repo.changelog.tip()))
  File "/galaxy_venv/local/lib/python2.7/site-packages/mercurial/repoview.py", line 314, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'derivedrepo:/tmp/tmpKAZonR/tmpMdlsUW/database/file' object has no attribute 'changectx'
```

**Comment by nsoranzo** [comment]
And we need wheels for mercurial 5.2: https://github.com/galaxyproject/starforge-recipes/pull/57

**Comment by nsoranzo** [comment]
> That looks relevant:
> 
> ```
> tool_shed.repository_registry: ERROR: Handled error adding entry to repository registry
> Traceback (most recent call last):
>   File "/galaxy/lib/tool_shed/repository_registry.py", line 59, in add_entry
>     certified_level_one_tuple = self.get_certified_level_one_tuple(repository)
>   File "/galaxy/lib/tool_shed/repository_registry.py", line 164, in get_certified_level_one_tuple
>     latest_installable_changeset_revision = metadata_util.get_latest_downloadable_changeset_revision(self.app, repository)
>   File "/galaxy/lib/tool_shed/util/metadata_util.py", line 93, in get_latest_downloadable_changeset_revision
>     repository_tip = repository.tip(app)
>   File "/galaxy/lib/tool_shed/webapp/model/__init__.py", line 297, in tip
>     return str(repo.changectx(repo.changelog.tip()))
>   File "/galaxy_venv/local/lib/python2.7/site-packages/mercurial/repoview.py", line 314, in __getattr__
>     return getattr(self._unfilteredrepo, attr)
> AttributeError: 'derivedrepo:/tmp/tmpKAZonR/tmpMdlsUW/database/file' object has no attribute 'changectx'
> ```

This broke in mercurial 4.6: https://www.mercurial-scm.org/wiki/Release4.6

**Review by mvdbeek — APPROVED** [review]

**Comment by drosofff** [comment]
Hi @nsoranzo 
I am not sure about the details yet, but I think this PR has in some way broken the ansible-galaxy-extras tasks for watchdog install and drmaa install. This is apparently related to a change in https://wheels.galaxyproject.org/

Does it make sense to you ?

Meantime I have found a turnaround by directly installing these dependencies with pip and pinned versions
I have a training session "Run Galaxy" with students Monday afternoon and not sure that I will have time to elaborate a more instructing bug report before this time... Sorry.

**Comment by nsoranzo** [comment]
@drosofff I doubt there is any connection with this PR, since it applies only to the dev branch of galaxy and I suppose the ansible roles use some release branch.
Your issue is probably due to the network issues we have seen for wheels.galaxyproject.org in the last 2 weeks, @natefoo has been working to replace it, so it should be better.
Anyway, given it's intermittent, re-running usually solve the problem.

**Comment by drosofff** [comment]
Thanks @nsoranzo yes it makes better sense.  Although when I checked manually I did not notice problem with accessibility to the wheels site. Anyway, I'll keep an eye on it and in the meantime I have disconnected the playbook from the site.

**Pull request merged**
