### PR TITLE
Revise toolshed config dependency check error message in repository install manager

### LINKED ISSUE #8715: Galaxy fails to install tools with dependencies
On dev when I do not set `tool_dependency_dir` in galaxy.yml it should default to `database/dependencies` but instead installation fails.

cc @ic4f @guerler @natefoo 

```
  # Various dependency resolver configuration parameters will have
  # defaults set relative to this path, such as the default conda
  # prefix, default Galaxy packages path, legacy tool shed dependencies
  # path, and the dependency cache directory.  Set the string to None to
  # explicitly disable tool dependency handling. If this option is set
  # to none or an invalid path, installing tools with dependencies from
  # the Tool Shed or in Conda will fail.
  #tool_dependency_dir: database/dependencies
```

`err_msg: "Tool dependencies can be automatically installed only if you set the value of your 'tool_dependency_dir' setting in your Galaxy configuration file (galaxy.ini) and restart your Galaxy server.  "`

### PR DESCRIPTION
**Pull request by guerler**
Follow-up to #8660. Fixes #8715.

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]
It feels like the check should be modernized and fixed but eliminated entirely. I'm fine with this though - we don't have any testing to verify the check works clearly so if we decide to do this better later we can add that with tests.

**Review by jdavcs — APPROVED** [review]
`app.tool_dependency_dir` *can* be None. I'm afraid I can't estimate whether this check is needed here (I don't know this part of the codebase well enough), so I'll rely on @jmchilton 's opinion.

**Comment by nsoranzo** [comment]
I cannot reproduce #8715, is this still needed after #8696 was merged? If yes, how to reproduce?

**Comment by nsoranzo** [comment]
`app.config.tool_dependency_dir` can be `None`, while I don't think `app.tool_dependency_dir` should be `None` just because `tool_dependency_dir` is not set in `galaxy.yml` .

See https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py#L1102 and https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/deps/__init__.py#L83

**Comment by guerler** [comment]
This underlying issue seems to be fixed now by a recent change in dev. Thank you @nsoranzo! Should we still remove the check here or at least revise the message?

**Comment by nsoranzo** [comment]
> Should we still remove the check here or at least revise the message?

I think we can revise the message to something like "Tool dependencies installation is disabled in your configuration files."

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
