### PR TITLE
[16.07] separate styles of new and old libraries fixing various ui bugs

### PR DESCRIPTION
**Pull request by martenson**
initially reported by @dpryan79 @bgruening
the bugs would be on the admin interface side as it was improperly tested after the recent wrapping of all CSS in `.library_style_container` specific selector

part of this is additional cleanup and some LESSification

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @martenson!

**Comment by carlfeberhard** [comment]
Looks good +1
(except for losing the spaces before the first brace? Is that just a new style your using?)

**Comment by martenson** [comment]
@carlfeberhard the file was a mess using 3 styles so I chose one - I do not have a preference (in hindsight I should have followed base.less)

**Comment by martenson** [comment]
base.less also has multiple styles :/

```
#content_table td{
```

```
.toolMenuAndView .toolForm
{
```

```
.icon-button.tag {
```

**Comment by carlfeberhard** [comment]
@martenson no worries! not a crit - just curious. less can be somewhat strange with it's parsing. Use any style you prefer.

edit: re-read my comment - sorry if that wasn't clear

**Pull request merged**
