### PR TITLE
Revise style of radio button groups to improve visibility

### LINKED ISSUE #10477: Make choice on Yes/No toggle more apparent
The default Yes/No toggle button (used e.g. for `<param type="boolean">` tool inputs) does not radiate with clarity in which option is selected. Is _Yes_ or _No_ selected here?
image

At the very minimum, I feel making the selected text bold would help. Better yet, replacing the component with a slider (or a more visually discerning element) would help.

### PR DESCRIPTION
**Pull request by guerler**
A: Current change:

image

B: Alternative with radio button:

image

C: Alternative with gray button:

image

Resolves #10477

### CODE REVIEW

**Comment by afgane** [comment]
How about also making the text for the selected option bold?

**Comment by hexylena** [comment]
Agreed with @afgane I would've thought Yes was selected due to colouring.

**Review by OlegZharkov — APPROVED** [review]
thanks a lot, works perfectly :+1: 
The current blue style is way better than green IMHO

**Comment by hexylena** [comment]
The green definitely removes the feeling of disabled I had from the blue/grey! I like it.

**Comment by guerler** [comment]
I personally like the `blue` one too but than again. `Blue` is my favorite color. Will ask a few more ppl about the color. Thank you for reviewing this.

**Comment by guerler** [comment]
How about:

image

**Comment by OlegZharkov** [comment]
> How about:
> 
> image

better than green, but I think blue is still better

**Comment by guerler** [comment]
@hexylena @enis @OlegZharkov, sorry for the back and forth and thank you guys for your patience. I made another suggestions above replacing the buttons with regular radio buttons for boolean fields. The benefit is that we would not have to introduce field specific coloring into the tool form.

**Comment by dannon** [comment]
I really prefer this version, without the inclusion of additional colors on the tool form.

**Comment by nsoranzo** [comment]
I like the "compact" Yes/No button of B) and C), we could make the button use the light grey of the other 2 buttons in A) to not introduce additional colours.

**Comment by guerler** [comment]
> I like the "compact" Yes/No button of B) and C), we could make the button use the light grey of the other 2 buttons in A) to not introduce additional colours.

I added it as option B. Above and removed the colored options since our consensus seems to be to preserve the default coloring of buttons.

**Comment by hexylena** [comment]
Love the clarity of the radio buttons! There is zero ambiguity there, amazing. 

Is there any way to combine the compactness of inline with the clarity of the checked/unchecked circles?  Say the circles/checks inside an inline button group?

> sorry for the back and forth and thank you guys for your patience

sorry for the bikeshedding UI changes and thanks for *your* patience :)

**Comment by bgruening** [comment]
What about those switches: https://mdbootstrap.com/docs/jquery/forms/switch/

GNOME also is using now those switches.

grafik

This is how it looks in Windows:

grafik

**Comment by davelopez** [comment]
My 2 cents: https://medium.com/uxtoast/toggle-switches-e395b505c44d :)

**Comment by guerler** [comment]
> Love the clarity of the radio buttons! There is zero ambiguity there, amazing.
> 
> Is there any way to combine the compactness of inline with the clarity of the checked/unchecked circles? Say the circles/checks inside an inline button group?
> 
> > sorry for the back and forth and thank you guys for your patience
> 
> sorry for the bikeshedding UI changes and thanks for _your_ patience :)

image

**Comment by guerler** [comment]
> What about those switches: https://mdbootstrap.com/docs/jquery/forms/switch/
> 
> GNOME also is using now those switches.
> 
> grafik
> 
> This is how it looks in Windows:
> 
> grafik

I build it by adding a new input element, however I personally still prefer the regular radio buttons next to each other. I think the overall styling fits better into the existing tool form. Nevertheless, this is how it would look like:

image

**Comment by bgruening** [comment]
Thanks @guerler! How would a non-selected boolean look like?

My feeling is that this problem was discussed and solved elsewhere and the major OS are currently using those switches so Galaxy should do this as well, as long as we don't have any UX expert at hand. The link of @davelopez is also nice.

**Comment by dannon** [comment]
Switches are more of a replacement for checkboxes, not radio buttons which might have 3-4 options in some cases.

**Comment by guerler** [comment]
> Switches are more of a replacement for checkboxes, not radio buttons which might have 3-4 options in some cases.
> 
> Bootstrap does come with 'switch' components, though: https://getbootstrap.com/docs/4.2/components/forms/#switches
> 
> Also:
> 
> > My feeling is that this problem was discussed and solved elsewhere and the major OS are currently using
> 
> This is precisely why we use bootstrap/bs-vue component libraries instead of rolling our own.

The above example uses bootstrap switches tho not the vue component, since the tool form is currently based on backbone.

**Comment by guerler** [comment]
@bgruening I wrapped and added a switch field for the tool form. Its shown above as `A: Current change` and seems to work fine.

**Comment by bgruening** [comment]
> @bgruening I wrapped and added a switch field for the tool form. Its shown above as A: Current change and seems to work fine.

I like that the most. My reasoning is that this is what most other systems use for a "checkbox" or a boolean. B) is mixing to much with the concept of a radio button, whih this is not. So my preference would be __A > C > B__

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
Failed selenium test is unrelated, passes locally.

**Comment by jmchilton** [comment]
Are we sure the Selenium test is unrelated? I think it might be? It has been failing for a while and those radio buttons are used in the toolbox filter preference page.

**Comment by dannon** [comment]
@jmchilton I'll check yet again locally, but unless I goofed something (entirely possible), it passed selenium when I ran it on my box before.

**Comment by jmchilton** [comment]
Opps. I kept looking at it and I made it green. Sorry for not updating the issue.

**Comment by jmchilton** [comment]
I got the very ugly:

```diff
diff --git a/test/integration_selenium/test_toolbox_filters.py b/test/integration_selenium/test_toolbox_filters.py
index 212da73f7e..f7db9cd7ea 100644
--- a/test/integration_selenium/test_toolbox_filters.py
+++ b/test/integration_selenium/test_toolbox_filters.py
@@ -31,11 +31,15 @@ class ToolboxFiltersSeleniumIntegrationTestCase(SeleniumIntegrationTestCase):
         self.navigate_to_user_preferences()
         self.components.preferences.toolbox_filters.wait_for_and_click()
         self.sleep_for(self.wait_types.UX_RENDER)
+        self.screenshot("toolbox_filters_landing")
         sibling_text = 'This tool filter will disable the Test Section section.'
         # This is the least terrible way I've found to get the right element.
-        filter_upload = self.driver.find_element_by_xpath("//span[contains(. ,'%s')]/../div//label" % sibling_text)
+        xpath = "//span[contains(. ,'%s')]/../div/div[@class=\"custom-control\"]" % sibling_text
+        filter_upload = self.driver.find_element_by_xpath(xpath)
+        self.sleep_for(self.wait_types.UX_RENDER)
         self.action_chains().move_to_element(filter_upload).click().perform()
         self.sleep_for(self.wait_types.UX_RENDER)
+        self.screenshot("toolbox_filters_swapped")
         self.components.toolbox_filters.submit.wait_for_and_click()
         self.sleep_for(self.wait_types.UX_RENDER)
         self.home()
```

Happy to PR.

**Comment by dannon** [comment]
@jmchilton Go for it, no worries!

**Pull request merged**
