### PR TITLE
Fix selenium selector for collections

### PR DESCRIPTION
**Pull request by davelopez**
Fixes

```
FAILED lib/galaxy_test/selenium/test_workflow_invocation_details.py::TestWorkflowInvocationDetails::test_job_details - selenium.common.exceptions.TimeoutException: Message: Timeout waiting on XPATH selector [//span[@class="content-title name"][text()="forward"]] to become clickable.
```

Many thanks to @ElectronicBlueberry for figuring out the issue!!

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by dannon — APPROVED** [review]

**Comment by ElectronicBlueberry** [comment]
Looking at the screenshot from the test failure it seems like the test navigates away from the multi-history view.

**Comment by davelopez** [comment]
Hmm... I thought that it didn't even go inside the sub-collection, but could it actually be that it went inside and then out again? And why does it pass locally? Could the selector be the cause here too? Too many questions... :face_exhaling:

**Comment by davelopez** [comment]
> lib/galaxy_test/selenium/test_history_multi_view.py::TestHistoryMultiView::test_list_list_display PASSED [100%]

This is starting to look more and more like a Heisenbug :upside_down_face:

**Comment by davelopez** [comment]
Alright... after some more debugging, I still can't understand what is going on with `lib/galaxy_test/selenium/test_history_multi_view.py::TestHistoryMultiView::test_list_list_display`.

This is the information I gathered so far:
- If you run this test **locally** it passes :white_check_mark:  (including prefix, headless or no, no matter what)
- If you run this test in CI **disabling any other CI tests** it passes :white_check_mark: 
- if you run the **entire test suite** in CI the test always fails :boom: 
- If you run **all selenium tests** in CI disabling all other CI tests it fails :boom: 
- if you run **some selenium tests** in CI disabling all other CI tests it passes :white_check_mark: 

When it fails, [for the look of the debugging screenshots](https://github.com/galaxyproject/galaxy/actions/runs/6349750769?pr=16754), it seems after clicking on the sub-collection `test0` it doesn't drill down into that sub-collection.

0-multi_history_list_list_before_click_hid_1-screenshot

I double-checked the selector but everything seems fine, it is in the DOM and obviously, it drills down fine locally or when you disable other most of the other selenium tests... I don't know how other selenium tests can really affect this... :disappointed:

**Comment by mvdbeek** [comment]
I can get it to fail locally with:

```
./run_tests.sh --skip-common-startup -selenium lib/galaxy_test/selenium -- --num-shards=3 --shard-id=0
```
Given this, I would assume there's an id conflict somewhere ... that's a tough one unless you can spot the mixup from the component itself.

**Comment by mvdbeek** [comment]
OK, so for posterity: you can run the test locally against a configured database with `GALAXY_TEST_DBURI='postgresql://postgres:postgres@localhost:5555/galaxy123?client_encoding=utf8`. Abort once you see the test failure, find the failing job from the test log, find the test user through the job in the database. Configure your normal instance to use that database, register an admin account, impersonate the user that was active during the failing job. Then open the multi-history view, and indeed you can't navigate into the nested collection in question.

**Comment by davelopez** [comment]
Thank you @mvdbeek! I will try out this technique and see if I can get to the bottom of this :+1:

**Comment by davelopez** [comment]
Ok, I tried to use the same DB for running the selenium test and then connect to the same DB in my local instance but for some reason, the user that is supposed to have that history doesn't have that history... :exploding_head: 
I'm sure I'm doing something wrong... but it is basically using the same DB connection URI for both the selenium run and the local instance if I understood it correctly...


https://github.com/galaxyproject/galaxy/assets/46503462/0548b578-05ba-4606-b566-4a6b7464d040

**Comment by davelopez** [comment]
Now everything is starting to make sense, but still I have a piece of the puzzle missing in my head...

The "collection loop issue" is caused by [this change](https://github.com/galaxyproject/galaxy/pull/16725/files#diff-ea906c23912b8a52d7712fdf98df49f8316c948286bbcca6859575ce452cd776R62-R65) I made in #16725

https://github.com/galaxyproject/galaxy/blob/2ed0ab042d40d6c684dac74f25b07ba40729b4ee/client/src/components/History/CurrentCollection/CollectionPanel.vue#L63

I was wrongly assuming the ID of the `DCObject` (DatasetCollection) was the same ID used to query `api/dataset_collections/{id}` so I fetched the "collection" from the store to drill down.

These are the values of the variables in the case of the test failure:

<details><summary>itemObject: DCObject</summary>

```json
{
    "id": "df7a1f0c02a5b08e", <-- This is a DatasetCollection ID
    "model_class": "DatasetCollection",
    "collection_type": "list",
    "populated": null,
    "element_count": null,
    "contents_url": "/api/dataset_collections/df7a1f0c02a5b08e/contents/df7a1f0c02a5b08e",
    "elements": []
}
```

</details> 

<details><summary>collection: HDCA</summary>

```json
{
    "id": "df7a1f0c02a5b08e", <- HDCA ID
    "name": "list:list",
    "history_id": "ee3742ed6d8b4a0c",
    "hid": 5,
    "deleted": false,
    "visible": true,
    "type_id": null,
    "type": "collection",
    "create_time": "2023-10-02T13:25:26.649540",
    "update_time": "2023-10-02T13:25:26.649545",
    "url": "/api/histories/ee3742ed6d8b4a0c/contents/dataset_collections/df7a1f0c02a5b08e",
    "tags": [],
    "history_content_type": "dataset_collection",
    "model_class": "HistoryDatasetCollectionAssociation",
    "collection_type": "list:list",
    "populated_state": "ok",
    "populated_state_message": null,
    "element_count": 1,
    "job_source_id": null,
    "job_source_type": null,
    "job_state_summary": {
        "all_jobs": 0,
        "new": 0,
        "waiting": 0,
        "running": 0,
        "error": 0,
        "paused": 0,
        "skipped": 0,
        "deleted_new": 0,
        "resubmitted": 0,
        "queued": 0,
        "ok": 0,
        "failed": 0,
        "deleted": 0,
        "upload": 0
    },
    "contents_url": "/api/dataset_collections/df7a1f0c02a5b08e/contents/0a248a1f62a0cc04",
    "collection_id": "0a248a1f62a0cc04",
    "populated": true,
    "elements": [
        {
            "id": "1e8ab44153008be8",
            "model_class": "DatasetCollectionElement",
            "element_index": 0,
            "element_identifier": "test0",
            "element_type": "dataset_collection",
            "object": {
                "id": "df7a1f0c02a5b08e", <- Coincidence...
                "model_class": "DatasetCollection",
                "collection_type": "list",
                "populated": true,
                "element_count": 3,
                "contents_url": null,
                "elements": [
                    {
                        "id": "c9468fdb6dc5c5f1",
                        "model_class": "DatasetCollectionElement",
                        "element_index": 0,
                        "element_identifier": "data0",
                        "element_type": "hda",
                        "object": {
                            "id": "2d9035b3fc152403",
                            "model_class": "HistoryDatasetAssociation",
                            "state": "ok",
                            "hda_ldda": "hda",
                            "history_id": "ee3742ed6d8b4a0c",
                            "tags": [],
                            "create_time": "2023-10-02T13:25:26.537999",
                            "validated_state": "unknown",
                            "peek": "<table cellspacing=\"0\" cellpadding=\"3\"><tr><td>TestData123</td></tr></table>",
                            "metadata_dbkey": "?",
                            "deleted": false,
                            "name": "data0",
                            "file_size": 12,
                            "visible": false,
                            "purged": false,
                            "uuid": "80a8fa98-5f94-43d1-b77e-deaddc8042c5",
                            "misc_blurb": "1 line",
                            "misc_info": null,
                            "hid": 2,
                            "metadata_data_lines": 1,
                            "file_ext": "txt",
                            "update_time": "2023-10-02T13:25:26.538003",
                            "history_content_type": "dataset",
                            "data_type": "galaxy.datatypes.data.Text",
                            "validated_state_message": null,
                            "genome_build": "?"
                        }
                    },
                    {
                        "id": "2a56795cad3c7db3",
                        "model_class": "DatasetCollectionElement",
                        "element_index": 1,
                        "element_identifier": "data1",
                        "element_type": "hda",
                        "object": {
                            "id": "5a1cff6882ddb5b2",
                            "model_class": "HistoryDatasetAssociation",
                            "state": "ok",
                            "hda_ldda": "hda",
                            "history_id": "ee3742ed6d8b4a0c",
                            "tags": [],
                            "create_time": "2023-10-02T13:25:26.538006",
                            "validated_state": "unknown",
                            "peek": "<table cellspacing=\"0\" cellpadding=\"3\"><tr><td>TestData123</td></tr></table>",
                            "metadata_dbkey": "?",
                            "deleted": false,
                            "name": "data1",
                            "file_size": 12,
                            "visible": false,
                            "purged": false,
                            "uuid": "bc2e2adb-5153-4140-9011-cc94ee7a9763",
                            "misc_blurb": "1 line",
                            "misc_info": null,
                            "hid": 3,
                            "metadata_data_lines": 1,
                            "file_ext": "txt",
                            "update_time": "2023-10-02T13:25:26.538008",
                            "history_content_type": "dataset",
                            "data_type": "galaxy.datatypes.data.Text",
                            "validated_state_message": null,
                            "genome_build": "?"
                        }
                    },
                    {
                        "id": "4b187121143038ff",
                        "model_class": "DatasetCollectionElement",
                        "element_index": 2,
                        "element_identifier": "data2",
                        "element_type": "hda",
                        "object": {
                            "id": "d413a19dec13d11e",
                            "model_class": "HistoryDatasetAssociation",
                            "state": "ok",
                            "hda_ldda": "hda",
                            "history_id": "ee3742ed6d8b4a0c",
                            "tags": [],
                            "create_time": "2023-10-02T13:25:26.538011",
                            "validated_state": "unknown",
                            "peek": "<table cellspacing=\"0\" cellpadding=\"3\"><tr><td>TestData123</td></tr></table>",
                            "metadata_dbkey": "?",
                            "deleted": false,
                            "name": "data2",
                            "file_size": 12,
                            "visible": false,
                            "purged": false,
                            "uuid": "93f3361e-c18c-42d9-8575-f4e03176d688",
                            "misc_blurb": "1 line",
                            "misc_info": null,
                            "hid": 4,
                            "metadata_data_lines": 1,
                            "file_ext": "txt",
                            "update_time": "2023-10-02T13:25:26.538013",
                            "history_content_type": "dataset",
                            "data_type": "galaxy.datatypes.data.Text",
                            "validated_state_message": null,
                            "genome_build": "?"
                        }
                    }
                ]
            }
        }
    ],
    "elements_datatypes": [
        "txt"
    ]
}
```

</details> 

The mixed ID `df7a1f0c02a5b08e` was causing the drill down collection stack to push always the same HDCA, creating the loop. That could explain why it failed only when more selenium tests were run vs just running `TestHistoryMultiView::test_list_list_display` in isolation. There was a higher change of hitting this mixed ID issue.

The missing part of the puzzle is the actual solution :sweat_smile: I need to wrap my head around the different concepts related to collections, HDCA, DCE, DC... but maybe someone more versed in collection internals can help... The previous solution was relying in using the `contents_url` for drilling down, but I wanted to use the fetcher to get all the typing benefits.

**Comment by davelopez** [comment]
I've updated this PR description to fix only one of the tests (that these changes address). The other one will be tracked in its own issue (https://github.com/galaxyproject/galaxy/issues/16785), as it is not a selenium problem but an actual bug. So taking this out of draft.

**Pull request merged**
