### PR TITLE
Code cleanups from ruff and pyupgrade

### PR DESCRIPTION
**Pull request by nsoranzo**
- Enable [flake8-comprehensions ruff rules](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4), but allow `dict()` calls that make use of keyword arguments (e.g., `dict(a=1, b=2)`).
- Move out from the `galaxy-util` package a file that requires `galaxy.files`
- Code cleanups from pyupgrade

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
Thats for the galaxy.files fix. That looks right to me!

**Review by jmchilton — APPROVED** [review]

**Comment by jdavcs** [comment]
Would you mind waiting for #17180 to be merged first? I'm afraid this might cause conflicts and some painful rebasing.

**Comment by nsoranzo** [comment]
> Would you mind waiting for #17180 to be merged first? I'm afraid this might cause conflicts and some painful rebasing.

@jdavcs I've compared the 2 PRs side-by-side and I think the only conflict would be in `lib/galaxy_test/selenium/framework.py` (pretty easy to solve).

**Comment by jdavcs** [comment]
thanks for checking, @nsoranzo, then it'll be fine.

**Comment by nsoranzo** [comment]
> ...and I merged too soon! This: `return [wid for wid in sa_session.scalars(stmt)]` does not translate into this: `list(sa_session.scalars(stmt))`: the latter will raise an error.
> 
> I'll go through this line by line and will submit a fix shortly.

Is this a SqlAlchemy 2.0 change or are these lines not tested?
The scalars results are iterable, so the syntax should be equivalent, but I am not at the computer so cannot test right now.

**Comment by jdavcs** [comment]
It's not a SQLAlchemy thing, it applies to sqlite3 as well. I've tested it - they are not directly iterable, here's one example:
```
-> for i, row in enumerate(results):
(Pdb) row
<sqlite3.Row object at 0x7ff558d996c0>
(Pdb) list(row)
*** Error in argument: '(row)'
(Pdb) [x for x in row]
[1, 'john', 'davis', 'sagd']
```
Same for SQLAlchemy's Result object. Why exactly these are not iterable when passed to `list`, I don't know.

**Comment by nsoranzo** [comment]
`list` is a command in Pdb, as you may guess from the error. Try `print(list(row))`

**Comment by jdavcs** [comment]
Now, this is truly embarrassing :laughing: After getting tripped by `args` in pdb in the past, I didn't expect to step on the same rake twice. Closing this. Thank you! :)

**Comment by nsoranzo** [comment]
No worries, I was able to notice this because I have been confused by these Pdb weirdnesses too many times!

**Pull request merged**
