### PR TITLE
Reports: Applied paging to all pages

### PR DESCRIPTION
**Pull request by OldWorldBoa**

### CODE REVIEW

**Comment by OldWorldBoa** [comment]
I'm doing some timing of the "optimized" queries. It doesn't seem like putting a limit and offset make any difference to the amount of time it takes to run the query. I've run both queries with and without a limit and offset, the of the query being the same. The results are incredibly similar, ie: 14.231235, 14.5686913, 15.234563, 14.56831253, etc. I believe that this variance in time has nothing to do with the limit and offset since there are examples of the query running shorter without limit and offset. Does anyone have a different experience with this?

**Comment by OldWorldBoa** [comment]
Here is the quick and dirty code I used to time queries. I manually removed and added the offset and limit  to said queries (jobs per user page)

**Comment by martenson** [comment]
Works fine for me, I will test the load speed on Test Reports once they are up (were giving us trouble lately).

Thank you very much for the contribution Daniel @Airistotal  !

**Comment by OldWorldBoa** [comment]
You're welcome @martenson. Just so you know, the timing code that's in my last commit really shouldn't be there in the production version. I just put that in there for you guys to look at in case you wanted to use/see it.

**Comment by martenson** [comment]
@Airistotal I will delete it after testing on Test, thanks for the reminder!

**Comment by OldWorldBoa** [comment]
No problem. I just didn't want someone to look at that page and think "Why the heck are there small numbers at the top for no reason???"

**Pull request merged**
