### PR TITLE
Updates and fixes for dockerized Galaxy testing.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by hexylena** [comment]
If this makes testing easier, great. I still find it a bit odd to have a container with all postgres/mysql rolled in which is why I was working (in parallel) to work out the configuration axis for testing against docker database images in jenkins. Otherwise, definitely a good thing for testing :)

**Comment by jmchilton** [comment]
What are the chances we were both working on this today. Anyway, I don't like all the configuration that has gone into the jenkins host. The advantage of `~/run_tests.sh --dockerize -db [postgres|mysql|sqlite]` is that the whole test environment is defined in container. So people can run the exact testing commands on the remote server and not just run the same database container with some docker magic. `galaxy/testing-base` additionally pre-migrates the databases so the tests run faster (especially important for local testing).

**Comment by hexylena** [comment]
I definitely sympathise with the dislike of amount of config in jenkins. It's definitely an issue. In the past I've solved this by simply backing up the jenkins home (where all the job configs live), but that's isn't quite as clean as the ansible stuff for deployment.

The major issue I see to the current dockerized testing is the hardcoded environments, i.e. we've picked a base image and we've picked a version of a database and those are _it_. With the jenkins test, we can pick 5 different versions of python and another 5 versions of postgres that we intend to support, and test across all of those axes.

In a perfect world, I imagine that we'd have a couple of different base images (centos, debian) with a couple variants (py2.6, 2.7, ...) without the database installed, and we'd test with multiple `docker-compose.yml`s. Would that be amenable to you?

**Comment by hexylena** [comment]
That said, in retrospect, it loses the pre-migrated databases. Not sure what to do there :(

**Comment by jmchilton** [comment]
We can have lots of containers, it doesn't have to be all packed into one. I think the key though is that the jenkins jobs really should be dead simple - calls to run_tests.sh - and even then as they get longer we should write scripts that parameterized down to just our configuration axis and stuck into `.ci/scripts`. We can have the transparency of Travis but advantages of complete local reproduciblity and not depending on closed source services if we follow this pattern.

**Comment by hexylena** [comment]
Yeah, adding stuff to `.ci/scripts` would be OK with me. That makes sense. I'll move some of the jenkins job scripts in there sometime tomorrow :)

**Comment by martenson** [comment]
my thinking was to first hack it into jenkins config and once its stable
and reliable make it part of galaxy repo and simplify the jenkins
'configuration'

in other words +1

**Comment by hexylena** [comment]
@martenson yep, that seems to be what we're doing in practice. So everyone is/will be happy :D

**Pull request merged**
