### PR TITLE
[PROCEDURES] Create a project code of conduct

### PR DESCRIPTION
**Pull request by natefoo**
Because the original PR #608 contained a typo, it has been closed and this PR supersedes it.

This PR creates a code of conduct which will apply to anyone participating in the Galaxy community. Although I'm submitting the request, this is the work of a number of other team and community members, who I thank for their roles in moving this forward. It's my belief that Galaxy has always been a welcoming and inclusive community, and my hope is that it will continue to be so in the future. Making an affirmation of these values sends a strong statement to the community that supporting diversity is important to the project, and that anyone is free to raise a concern which will be taken seriously.

As noted, this was derived from the [Open Code of Conduct from the TODOGroup](http://todogroup.org/opencodeofconduct/). Please feel free to comment on anything you feel should be added to or removed from this policy as written.

| Requirement | Value |
| --- | --- |
| 192 hour window start | 2015-08-25 18:09:20+00:00 |
| 192 hour window end | 2015-09-02 18:09:20+00:00 |
| 25% quorum | ceil(19 \* .25) = 5, +1 votes |

### CODE REVIEW

**Comment by hexylena** [comment]
:+1:

**Comment by nsoranzo** [comment]
:+1:

**Comment by jmchilton** [comment]
:+1:

**Comment by davebx** [comment]
:+1:

**Comment by bgruening** [comment]
:+1:

**Comment by natefoo** [comment]
:+1:

**Comment by dannon** [comment]
I'll re-apply my -0.  We've talked about this a lot offline and I'm not going to rehash all the arguments here, but in general I don't think it's specific enough to be useful and, moreover, simply isn't necessary.

I disagree that it "sends a strong statement to the community" -- our actions thus far in building a community have done that, our positive day-to-day interactions with people will continue to do that, and this document is meaningless.

That said, the argument stands that I can't see how it'd actively hurt anything, so, -0.

**Comment by tnabtaf** [comment]
:+1:

I'm quite happy to serve as the default point of contact for this.

**Comment by jxtx** [comment]
+1, with reservations

I withheld my vote for as long as possible to see how this developed. I think this is too important to be left to a 25% quorum and I hope people will take the chance to comment, even if it is to state complete indifference. 

Overall, I think this falls under "explicit is better than implicit". I agree with @dannon that (hopefully) we have already sent a strong message through our actions. However, I don't see how it can hurt to also make an affirmative statement of our commitment to inclusiveness. The most important thing here is establishing a process and a point of contact should there be a problem in the future, _which hopefully will never need to be used_.

I continue to have concerns about the specific language. Full disclosure, I suggested this specific wording in the first place, but I'm still not sure it is exactly right. However, maybe it is good enough for now. There are real problems with diversity and inclusiveness in the open-source community at large, and if this makes even one person feel more comfortable participating in the project, then it is worthwhile.

**Comment by guerler** [comment]
I vote with -0 although I think that this document can send a positive signal to the community as a whole. On the other hand it is so unspecific that it might damage the interaction between members. I suggest that members who feel offended or observe unacceptable behaviour should be encouraged to instantly raise their concern to that particular person instead of keeping silent, reporting the incident and/or being upset. This should be particularly true for those members with commit rights.

Here is an incomplete/unsorted list of questions which might arise:
1. How often was this code of conduct already violated?
2. How is "Be friendly and patient." different from "Be respectful"?
3. Would voting for Trump violate this code of conduct?
4. "Be careful in the words that we choose" sounds very unspecific. Is this not a general life advise?
5. "Be kind to others." Does this include members outside of the Galaxy Community or does this say its ok to use "racist terms" outside of the community? How do we decide if a term is actually inappropriate? Will a vote be taken? Will we provide a list? Would that violate laws?
6. How do we specify "Personal insults"?
7. "Being unable to understand why someone holds a viewpoint doesn’t mean that they’re wrong" is a good advise but I am not sure why its in this code of conduct? Is this supposed to be a general how to be good/smart guide?

**Comment by natefoo** [comment]
@jxtx I really like the way you expressed this, this really gets at the reason that I and the other early supporters of a code of conduct wanted to see this happen. Galaxy has indeed been a great community and I really hope it stays that way. There were a couple of specific incidents outside of our community that lit the fire under this issue for me and made it clear that no matter how uncontroversial a person may be, they can still become a target of harassment for no reason other than their gender, race, etc.

@guerler thanks for joining the discussion, l can do my best to respond to those from my perspective if you want, but it wasn't clear whether you were asking those questions or just asking "what will we do when these come up?"

**Comment by guerler** [comment]
Thanks @natefoo. No need to answer those. I made the list to illustrate why I perceive the document as unspecific.

**Pull request merged**
