### PR TITLE
Search Overlay plugin bug fix

### PR DESCRIPTION
**Pull request by anuprulez**
This PR fixes the bug: https://github.com/galaxyproject/galaxy/issues/4247

Changes:

- The window object `Galaxy.toolPanel` is replaced by `Galaxy.config.toolbox_in_panel`

- Indentation fixes

Thanks @martenson!

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Review by martenson — APPROVED** [review]

**Comment by martenson** [comment]
Thank you @anuprulez !

**Comment by anuprulez** [comment]
@martenson thanks for merging :)

**Pull request merged**
