### PR TITLE
Remove NetworkException catch clauses, so if irods server is down, NetworkException percolates up, preventing a silent failure and alerting us

### PR DESCRIPTION
**Pull request by kxk302**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by natefoo — COMMENTED** [review]
I think this might allow us to notice problems sooner if the Galaxy server is idle, but I think we would still have the case we currently have where datasets continue to be created and used from the cache but will never be pushed back to the iRODS server, even once that server is up again, right?

**Comment by kxk302** [comment]
> I think this might allow us to notice problems sooner if the Galaxy server is idle, but I think we would still have the case we currently have where datasets continue to be created and used from the cache but will never be pushed back to the iRODS server, even once that server is up again, right?

The healthcheck is called when the server is being used (Its creating/getting/deleting files). So, it won't help when the server is idling. We may need an alternate way of checking irods server for an idle Galaxy server.

On your second point, you are correct. If irods is down, files get created in cache, but are not pushed to irods (even if irods server is back later). But the file upload also fails. So, the user knows to retry.

**Comment by kxk302** [comment]
The healthcheck is not needed anymore. I suspect after this change is deployed to Test, we'd see Test fail due to irods server being down.

**Comment by kxk302** [comment]
@natefoo so it seems removing the NetworkException catch clauses caused the exception to percolate up and fail the upload on Test. Could you please review the current state of the PR? Thx

**Comment by kxk302** [comment]
I suppose this PR can wait till irods on Test is back, so the checks can be run.

**Pull request merged**
