### PR TITLE
Allow JSONP to be returned from API endpoints

### PR DESCRIPTION
**Pull request by carlfeberhard**
https://en.wikipedia.org/wiki/JSONP
Simplifies use of API for users on servers where CORS is not enabled.

Adds the `callback` parameter to all existing JSON endpoints. For example, calling:
    api/histories/:history_id?callback=process_data
 would return:

```
process_data({
    id: "1234abcd",
    ...
});
```

wrapping the API return data in the javascript call requested by `callback`.

### CODE REVIEW

**Comment by martenson** [comment]
I implemented this slightly differently for TS search using both the `jsonp` param  _and_ the `callback` param but this seems alright.
(my implementation: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/tool_shed/api/tools.py#L34)

Is it worth unifying the approach?

**Comment by carlfeberhard** [comment]
Unified is always better and I can throw the `jsonp` arg in there, too, if you'd like. 

Doesn't the presence of the callback argument imply `jsonp=True`, though?

**Comment by martenson** [comment]
@carlfeberhard it does - I think I was trying be more readable as solo `callback` API argument seemed a bit cryptic at the time.

I can change the implementation but this needs to go through deprecation on the TS side. I will deprecate in 16.10 and replace in 17.01. Sounds good?

**Comment by carlfeberhard** [comment]
Sure - easy enough from my side! I'll add an alternate decorator to turn this off for the tools endpoint for now. Good catch and thanks for working with it.

**Comment by martenson** [comment]
Note: we also need to alter-decorate the TS repositories search which works the same as tools.

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/tool_shed/api/repositories.py#L355

**Comment by carlfeberhard** [comment]
I saw that. I think the new commits will account for both endpoints (all `_future_expose_api_raw_anonymous_and_sessionless` endpoints for now). Does that work for the existing jsonp endpoints?

**Comment by martenson** [comment]
@carlfeberhard perfect, thanks a bunch!

**Comment by martenson** [comment]
@carlfeberhard ~~let me know if you want to merge this, as it is marked WIP~~
sorry, page did not update

**Comment by martenson** [comment]
I assume that failing API test is random

**Comment by carlfeberhard** [comment]
Yeah - I'm not sure myself - hopefully we'll find out. Thanks for the merge.

**Pull request merged**
