### PR TITLE
Sync doc/source/lib with current lib/

### PR DESCRIPTION
**Pull request by nsoranzo**
This PR will also fix many doc pages that were failing build with a Traceback, plus move the extra API doc from the automatically generated docs.

### CODE REVIEW

**Comment by jmchilton** [comment]
So I had a branch that did something similar with sphinx-apidoc because what was there was just hopelessly out of date - but I abandoned it because the long module names don't really work right? 
api_screenshot.

For whatever reason this is not a problem with planemo because the API docs do not show up in the left hand bar:

http://planemo.readthedocs.org/en/latest/planemo.shed.html#module-planemo.shed.interface

Thoughts? Can we do this but remove it from the sidebar maybe?

**Comment by nsoranzo** [comment]
@jmchilton I've changed the theme to `sphinx_rtd_theme` and now seems to display quite nicely:

http://nsoranzo-galaxy.readthedocs.org/en/dev/

**Comment by jmchilton** [comment]
@nsoranzo - Beautiful! This is fantastic now - I doubt any PR has ever fixed some many individual bugs :).

**Comment by dannon** [comment]
Looks great to me too.  +1

**Pull request merged**
