### PR TITLE
Enable admin resend activation email

### PR DESCRIPTION
**Pull request by jdavcs**
Re #6981
@erasche I misread the issue and implemented a button for the admin UI instead of an API endpoint. Which was careless of me.. But since it's done, will this solve the issue, and is it useful at all? Or is an API endpoint preferable? (I'll implement the endpoint if need be) 
@dannon I used same approach.

### CODE REVIEW

**Comment by martenson** [comment]
With your previous PR you closed https://github.com/galaxyproject/galaxy/issues/3208

**Comment by jdavcs** [comment]
> With your previous PR you closed #3208

But that's a different issue? It's mentioned in 3208's discussion.

**Comment by dannon** [comment]
I'm guessing having the admin be able to manually activate a user is sufficient here, and that this might not be necessary?

**Comment by jdavcs** [comment]
Close it then? I don't mind - was minimal effort anyway.

**Comment by hexylena** [comment]
> is it useful at all

yes!!!! This is great! APIs are great for some admins, but in general admins should be able to do everything they need without resorting to the API.

**Comment by hexylena** [comment]
> I'm guessing having the admin be able to manually activate

In EU's case, sometimes emails didn't get sent for one reason or another. We occasionally had to manually send the activation link to the users.

I don't want to activate users for them, because their accessing of the activation link confers consent to the ToS/our privacy policy.

**Comment by jdavcs** [comment]
@erasche thanks for the comment - this certainly clarifies the use case for this!

**Comment by dannon** [comment]
Cool, happy to defer to @erasche's admin experiences here -- I hadn't considered the ToS agreement angle, makes sense to me.

**Comment by jdavcs** [comment]
@galaxybot test this

**Review by bgruening — APPROVED** [review]
@ic4f cool beans!

**Pull request merged**
