### PR TITLE
Consolidates data dialog components

### PR DESCRIPTION
**Pull request by guerler**
This PR consolidates data dialog components and converts them to composition api and type script. This is a preparation for upcoming changes to the data dialog functionality. Additionally this PR decomposes some of the nested abstraction layers. Moving forward it should be easier for us to make additions or customize the data dialog for use in different contexts. 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
I'd really like the ability to extend the Markdown editor components with the ability to customize the form for each directive you insert with added option (e.g. add an optional footer, select a size from a dropdown, etc..). Mostly these are all just these selection dialogs currently. I hope you can keep this use case in mind as you refactor these!

**Comment by guerler** [comment]
@jmchilton absolutely, the goal of this refactoring is to simplify the overall structure while at the same allowing for more flexibility. As we go along we can easily add additional slots to extend or replace the footer or other components as necessary. I'd be happy to help with that.

**Review by jmchilton — APPROVED** [review]
My gut says I don't think that slots is the right approach - the Markdown pickers are not data pickers with extra options they are a set of options that include data as one. Conceptually not a huge difference but I think it guides one to a different approach. The right approach would be to extract the stuff inside the modal as a component that could be included in other modals not making the existing modal more complex and having to deal with the complexity of the existing modal. I think that sort of leads us down the road of Forms and Grids - where you think there should be a big hyper-parameterizable mega widget and I think we should have smaller composable ones even if that means a lot more duplication. You're a brilliant developer though and I understand your vision and I know you always find a way to make it work and work well. I'm happy to try it your way - especially if you were willing to do the work on a few of the markdown components to outline what it should look like.

**Comment by guerler** [comment]
@jmchilton I will definitely put the work in to adjust this as needed as we go along. I really appreciate it. Thank you!

**Pull request merged**
