### PR TITLE
[WIP] introduce intro.js introductions

### PR DESCRIPTION
**Pull request by martenson**
This is WIP of adjusted @bgruening's implementation of intro.js into Galaxy.

_looking for feedback_
## Concept

Each step in the introduction yml config looks similar to this:

```
  element: "textarea#text-content"
  intro: "Insert data into Galaxy."
  position: "top"
  textinsert: 'https://raw.githubusercontent.com/arq5x/bedtools/master/test/merge/a.full.bed'
  postclick: "textarea#text-content"
```
## Testing

To test you have to add the following line to the config
`introduction_tutorials_config_dir = config/plugins/interactive_tutorials`

After start you will have a new menu item under 'Shared data' the `Interactive tutorials`.

From the list of available tutorials the best one for testing is `galaxy_ui.yml`
## Modifications of intro.js

added functions to allow intro config specify the following:
`textinsert` insert given text to the `element` of the introjs step
`preclick` triggers given selector before showing step
`postclick` triggers given selector after showing step
## Known issues

There are problems with z-index - especially when trying to highlight something in the modal. Discussed at https://github.com/usablica/intro.js/issues/109 and many other places. I tried few hacks but did not find a plausible solution yet. 
You can replicate it by running the `galaxy_ui.yml` intro. It will upload fetch a url using the upload modal but the modal itself will be invisible because of Z-index.

This is not yet production ready (e.g. hardpasting modified intro.js instead of bowering fork, css is separated, needs rebase etc.)

### CODE REVIEW

**Comment by martenson** [comment]
I would appreciate if you guys had a look at this: @carlfeberhard @guerler @dannon 
The z-index issue is also described here with a workaround: https://github.com/heelhook/chardin.js/issues/26. I tried to use it but did not succeed yet.

**Comment by dannon** [comment]
Closing this for now due to conflicts and other issues talked about in IRC and hangouts (using a different library which won't require customizations, etc).  I have a different implementation that I've talked about with Bjoern at length that I'm polishing up and will open a PR for when I'm back in town.

**Comment by martenson** [comment]
Closing this is setting us back where we were at SAB last Fall. Please make your different implementation public so we can test and cooperate or do not close this. Unless you present your work this is the place where we should record the discussion and decisions.

**Comment by dannon** [comment]
@martenson Like I said, that's the plan, and I will.  

I was told the point of this PR was simply because @nekrut wanted to see it, which I assume has been done at this point.  This was talked about at length on Hangouts, etc., and I didn't want anyone to sink more time into this particular fork, hence the closing.

**Comment by dannon** [comment]
In any event, -1 to this implementation using intro.js

**Comment by natefoo** [comment]
@dannon Does this preclude you from doing any of the work you wanted to do? I am not sure I see a downside with using this until yours is ready.

What I'd hate to see happen is if this is closed and we have nothing until you have time to work on your implementation, which could be pretty far down the line.

**Comment by blankenberg** [comment]
Any reason not to open a PR with the mentioned other implementation, marked as WIP? No harm in having something that is not polished being available for review, consideration, and collaboration, even if it is not yet finished.

**Comment by dannon** [comment]
@blankenberg Because I want to have more done before pushing it.  It isn't quite what I want to have 'reviewed' or 'contributed to' yet.

I don't show up and demand everyone else push things they're working on before they'd like to do so, and I'd appreciate folks not do it to me.

**Comment by dannon** [comment]
Talked to @natefoo a bit on IRC about whether or not it precludes other work, but, in short -- yes, it's worth getting the format of tours we want to use correct and nailed down before people start building a ton of them and we have to make a bunch of adapters that we maintain forever going forward.  This is one of the things I'm still working on, and experimenting with.

Since this is not a feature we _must have in dev this week_, and which I've said I'm close to wanting to show off a different version of (and which I've already talked about with the actual _author_ of this particular code, @bgruening ) I'd really appreciate folks just giving it a rest (which is why I tried to close this particular PR, to avoid sinking more time into this fork for right now) until I can get back from vacation.

**Comment by jmchilton** [comment]
> "I'd appreciate folks just giving it a rest."

I think people would have been happy to give you time to work on this @dannon but it has been over a year. If your -1, given without technical justification, is because you are working on a superior implementation can you at least provide a timeline for when you would like us to stop "giving it a rest". I hope you don't expect the team to wait indefinitely for you while an existing implementation exists and people are generally pretty impressed with.

I hope you can appreciate that from the outside it seems unlikely (though admittedly not impossible) that a different choice of underlying library is worth the implementation:
- Delaying a very important feature for a year
- Making a highly proficient community member wait in limbo for a year
- Being developed behind closed doors instead of out in the open

**Comment by dannon** [comment]
@jmchilton I clearly said "giving it a rest ... until I get back from
vacation" and can get it out.  So the timeline is vacation calendar + a few
days at most.

The rest of what you've said is fairly disingenuous, and I'm having a hard
time figuring out why the entire PSU team feels the need to pile on here.

I haven't 'delayed a very important feature for a year', or 'made a highly
proficient community member wait in libmo for a year' or anything like
that.  Like _everything_ we do there are features we want to create and
other things that need to get done that take priority.  This has clearly
_become_ a priority in the past couple weeks, somehow, so I talked to
@bgruening (who actually hacked out this implmentation -- I have no idea
how all of you are so invested all of a sudden) about this during his JHU
visit and we agreed that I'd get the other implementation working and we'd
go from there.

**Comment by jmchilton** [comment]
@dannon thanks for the timeline.

**Comment by hexylena** [comment]
> This has clearly _become_ a priority in the past couple weeks

(Not to add fuel to the fire, I just want to apologise for poor communication on **my** end)
I did a poor job of conveying my personal priority level for this in in Galaxy, and I'm sorry about that. I should've been more vocal in my need for this over the past 9 months. It has always been a high priority item for me as a Galaxy Admin and the primary person who trains users in my department; ever since the first PR I've been excited for this. 

Per your comments at the time of the original PR, we've use Bjoern's implementation internally, pending it getting into Galaxy proper. Not that I think anyone needs convincing of the utility of this feature, but training is a _massive_ time sink for me (as a tool dev and a person who has many other responsibilities); these sort of things take an incredible load off of my back just to say "Go run through this and _then_ ask questions" rather than having to onboard individual users. Those of us who train users regularly are looking for every place we can improve the process, this would/will be a majorly important feature for us.

Again, my apologies for not communicating the importance of this feature (this implementation or another) to some (n=1) Admins and trainers.

**Comment by nekrut** [comment]
@erasche thanks. The N is much higher than 1

**Comment by martenson** [comment]
A superior implementation is being worked on at https://github.com/galaxyproject/galaxy/pull/1422

**Pull request closed without merging**
