### PR TITLE
Fix library zip download

### PR DESCRIPTION
**Pull request by dannon**
This zipfile creation code all needs refactoring, WIP

This fixes zip archive downloads in the library @OlegZharkov

### CODE REVIEW

**Comment by bgruening** [comment]
@dannon we should either get this under testing or maybe drop a few of the archive options. Our users usually do not know the difference between all of them and maybe we should make a decision and only offer one? maybe two options with more recent compression formats that we also test.

**Comment by dannon** [comment]
@bgruening Yep, I agree; right now it's handled differently in a couple places and could use centralization and testing in a refactoring pass.

**Comment by OlegZharkov** [comment]
Thanks a lot @dannon! that was extremely fast response.

I probably should write a selenium test for this, so it doesn't suddenly break again.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@OlegZharkov I take your word for some tests :)

**Pull request merged**
