### PR TITLE
HiC Multi-resolution heatmap datatype, dataprovider, and visualization plugin

### PR DESCRIPTION
**Pull request by msauria**
HiC data is of increasing importance in understanding genome architecture. The tool 'hifive', currently present in the toolshed, allows analysis of these data on galaxy. However, because this data is 2-dimensional it can not be visually explored in the same way as other genome annotation data.

Hifive creates a compact binary filetype called a 'multi-resolution heatmap' or 'MRH', which provides an efficient way to explore HiC data across a range of resolutions. This format, as well as a visualization plugin, has been adapted into Galaxy for real-time navigation of HiC data in an interactive 2D genome browser.

The data provider has a unit test and test data allowing easy verification of function, while the test data can be used to see the functionality of the visualization plugin, albeit with very low resolution.

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @msauria this looks great! Thanks very much!
Can you please fix failing the tests at first and rebase your branch against dev if possible?

**Comment by msauria** [comment]
Working on that now.

**Comment by dannon** [comment]
When you rebase, you don't need to collapse all commits, it might just be nice to get rid of the merges I guess (that said, I'm totally fine with no rebase at all).  Many of these look like they're useful as atomic commits.

**Comment by guerler** [comment]
This looks very interesting. Can you link some example data?

**Comment by bgruening** [comment]
@guerler: https://github.com/galaxyproject/galaxy/pull/658/files#diff-1c66ef79fce1fe220b620d8b6e9dd829

**Comment by guerler** [comment]
Thx @bgruening

**Comment by msauria** [comment]
All lint and unit test issues have been resolved.

**Comment by martenson** [comment]
This should continue in #672

**Pull request closed without merging**
