### PR TITLE
Set 'deleted' to True when purging a history dataset association

### LINKED ISSUE #3548: [15.03-dev] API: purging history dataset association does not set 'deleted' to True
Bug introduced in commit 58f677ad4f4473d0549dd417f187cc1f7a3a9a4e.

On my Galaxy instance:
```
SELECT COUNT(id) FROM history_dataset_association WHERE purged IS TRUE AND deleted IS FALSE;
 count 
-------
  4282
(1 row)
```

This can be trigged by an API call like:
```
DELETE /api/histories/03501d7626bd192f/contents/f597429621d6eb2
```
with payload `{'purge': True}`. The same happens when permanently deleting a history which has non-deleted datasets.

This can be a serious problem for API/BioBlend scripts filtering history datasets on the `deleted` field.

A possible fix would be to modify [PurgableManagerMixin.purge()](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/deletable.py#L75) in `lib/galaxy/managers/deletable.py` to call:
```
self.delete(item, flush=False)
```

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix https://github.com/galaxyproject/galaxy/issues/3548 , bug introduced in commit 58f677ad4f4473d0549dd417f187cc1f7a3a9a4e.

Add API and unit test cases.
Add migration to fix misaligned databases.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
I've added a second commit which adds test cases also for histories (not affected by the issue) and avoids deleting them twice when purging.

**Comment by jmchilton** [comment]
I don't know what the deal is with this hung test - I've seen it occasionally for other tests also but there doesn't seem to be a Jenkins record of it. At any rate I am confident the tests wouldn't fail as a result of this PR.

@natefoo @blankenberg do either of you have a good reason why some purged datasets aren't deleted - I feel like I may have heard a reason at one point from one of you why but my memory is faulty and it is really counter intuitive now why this would be an allowed state.

**Comment by dannon** [comment]
+1, thanks @nsoranzo.

**Comment by natefoo** [comment]
Yes, the reason was that if you look at a purged history, you still want to see the history in the "state" it was in when purged. If you `delete` the `purge`d HDAs, you lose the record of which datasets were deleted and which were active at the time you deleted and/or purged the history.

**Comment by natefoo** [comment]
To add to that, I don't know if the UI allows for extracting a workflow from purged histories, but it could/should, and you would definitely want the correct HDA `delete`d state in that case.

**Comment by jmchilton** [comment]
So @natefoo do you think we should back out of this PR then?

**Comment by dannon** [comment]
Hrmm.  Are we sure there's actually value in seeing deleted vs purged for purged histories?  I see that we've lost information here, for sure, in aligning the flags.  I just am skeptical it's info worth keeping.

**Comment by natefoo** [comment]
It's my opinion that it should be backed out, yes.

**Comment by dannon** [comment]
Guess we should treat this like a -1, then.  I've opened a PR to revert it.  We'll want to follow up on the original bug(s) mentioned by @nsoranzo in the previous issue and see if there's something else going on.

**Comment by nsoranzo** [comment]
@natefoo That was not the case pre-release_15.03, I doubt that was changed on purpose to allow this scenario.

**Comment by martenson** [comment]
-1 and +1 are explicit - I wouldn't 'treat' things like something that is explicitly specified

**Comment by natefoo** [comment]
Agreed, I'd prefer more discussion before throwing an explicit -1 on this.

**Comment by natefoo** [comment]
@nsoranzo It was when I added `hda.purged` - I am not sure when it broke, however.

**Comment by dannon** [comment]
I'm not stopping anyone talking about things at all, @natefoo or @martenson, I merely opened a PR to revert it reflecting the dissent expressed here, since I'm the one that merged this.  Keep on talking.

**Comment by nsoranzo** [comment]
For what I see, it is not possible in 17.01 (so before this PR) to extract a workflow from a purged history (in the UI at least) because you cannot set it as current history.

**Comment by jmchilton** [comment]
I'm -.5 on backing out - I prefer the new behavior.  I understand information was lost but that wasn't t an intuitive way to capture it and it isn't worth the confusion and it has broken for sometime anyway.

**Comment by natefoo** [comment]
@nsoranzo Ah okay, I misunderstood what you were referring to when you said it was previously possible.

I really think it's less useful to view a purged history and see nothing - and have no idea what you did - than it is to see it look the way it was when you deleted it. If you (via bioblend) are treating undeleted-but-purged HDAs in a purged history as anything but purged that seems to be a usage error?

**Comment by nsoranzo** [comment]
@natefoo When I said:
> That was not the case pre-release_15.03, I doubt that was changed on purpose to allow this scenario.

I meant that in release_15.01, when you purged a dataset through the API, it was also deleted: https://github.com/galaxyproject/galaxy/blob/release_15.01/lib/galaxy/webapps/galaxy/api/history_contents.py#L490

**Comment by natefoo** [comment]
Ah, ok. That behavior would have been different from the UI behavior at the time, however.

**Comment by natefoo** [comment]
A bit of clarification, in the UI, there is no way to purge an undeleted HDA other than purging the history, or via the cleanup scripts. So if you purged an individual HDA, it would've been already explicitly deleted.

**Comment by nsoranzo** [comment]
> in the UI, there is no way to purge an undeleted HDA other than purging the history

That's correct, in fact my original bug report https://github.com/galaxyproject/galaxy/issues/3548 was that purging a dataset through the API did not mark it as deleted.

**Comment by natefoo** [comment]
Sorry for the run around on this @nsoranzo. So in that case, it makes sense to mark deleted when purging an individual HDA via the API assuming current methods for purging histories presumably do not individually purge HDAs via the API. It's the DB update marking all purged HDAs as deleted that's a problem in my opinion.

**Comment by nsoranzo** [comment]
> A bit of clarification, in the UI, there is no way to purge an undeleted HDA other than purging the history, or via the cleanup scripts.

I've checked the cleanup scripts and I cannot find a place where something non-deleted-yet is purged. Also the `purge_histories()` method deletes all history datasets.

**Comment by natefoo** [comment]
Interesting. [pgcleanup.py](https://github.com/galaxyproject/galaxy/blob/dev/scripts/cleanup_datasets/pgcleanup.py) does as I've described, but apparently the older cleanup script was never updated to do this. That's a bit concerning. The scripts should be updated to both do the same thing.

If nobody thinks it's useful to preserve the deleted state of HDAs in a deleted history then we can reinstate the change, but it seems kinda silly to make a conscious decision to permanently "lose" those details when the schema allows us not to.

**Comment by martenson** [comment]
@natefoo just to be clear, the change is still in since the #3613 has not been merged yet

**Comment by jmchilton** [comment]
@natefoo I'm not saying it isn't useful - it is. But there was clearly some cognitive costs or technical debt involved here since many people looked this over and no one saw a reason to keep it. I'm not -1 on the other PR - feel free to merge it - I just don't think it is a good idea.

**Comment by dannon** [comment]
Just to chime in as well, since this is still floating -- even though I opened the other reversion PR (to have a discussion about it there) I *do* like the changes in this PR and don't think reverting it is a great idea.  As I stated before, I'm skeptical there's value in keeping the additional complexity around.

**Comment by natefoo** [comment]
Since I seem to be the only person advocating for keeping `deleted` I say we keep this change and close #3613. However, pgcleanup.py also needs to be modified to set `deleted` accordingly.

**Comment by blankenberg** [comment]
FWIIW, I think preserving the state is worthwhile.

**Pull request merged**
