### PR TITLE
[20.05] More structured errors for tool validation problems.

### PR DESCRIPTION
**Pull request by jmchilton**
The goal is improved error handling during tool testing - trying to see if we can get to a point where we can skip tests if the target server simply doesn't have the needed .loc files. Alternative to https://github.com/galaxyproject/galaxy/issues/7998.

### CODE REVIEW

**Comment by mvdbeek** [comment]
> can skip tests if the target server simply doesn't have the needed .loc files.

Mechanism-wise this should just flat-out never attempt it. The loc files may be there, but are most likely containing the full-sized reference dataset instead of a small subset. What do you think about baking some logic into the Tool class for filtering tests that reference incompatible parameter types ?

**Comment by jmchilton** [comment]
> The loc files may be there, but are most likely containing the full-sized reference dataset instead of a small subset.

Ohhhh... that is gross. I thought they had modified dbkeys for the subsets. I've removed the skip option from the CLI since it sounds like you don't think it will be effective but I've retained the more structured error handling - I think that stuff is all good plumbing changes.

**Comment by jmchilton** [comment]
The CLI changes are in a commit at the head of this branch https://github.com/jmchilton/galaxy/tree/structured_errors_1 if the need arises for them.

**Comment by jmchilton** [comment]
I'll reopen this against dev.

**Pull request closed without merging**
