### PR TITLE
include approx. dates for 15.07 release

### PR DESCRIPTION
**Pull request by martenson**
to allow community better sync

### CODE REVIEW

**Comment by hexylena** [comment]
Thanks @martenson, much appreciated. Gives @bgruening and me a timeline for IPython/RStudio updates!

**Comment by jmchilton** [comment]
Thanks for opening up this conversation @martenson!

Now that it is public I feel it is more worthwhile to debate it unfortunately :). I don't really like this timeline - the most important part of the release process - debugging what use to be called "next-stable" - is happening while everyone is at the conference. I feel like this doesn't really help anything - why the rush when there is not a new shiny release for the conference and why have usegalaxy.org buggy during the conference. I would suggest that either aim for a 15.06 release (and freeze within the next couple weeks) so that we have plenty of time to have a really solid release for the conference that still has some new goodies such as RStudio **or** that we delay the release until the end of July or beginning of August (a 15.08 release) - so that usegalaxy.org can be updated after we get back and we can give the RC process the time it deserves.

**Comment by martenson** [comment]
@jmchilton I think the decision served two purposes: get the newest stuff on Main for GCC and test it well (thus prolonged freeze) but leave the release hassle post-conference.
So in your words the 'new shiny release' would be running on Main throughout the conference but others would get it later.
I am fine either way though (pre || post).

**Comment by jmchilton** [comment]
You have not sold me that this isn't a crazy idea - but I am used to being alone in my pessimism. If we are going to do the release during this window then I am strong :+1: for merging this - I really like the idea of having a public plan.

Image of Eeyore

**Pull request merged**
