### PR TITLE
[23.0] Fix for Numeric form field to allow Null min/max values in validation methods

### PR DESCRIPTION
**Pull request by hujambo-dunia**
Addresses: #16335 and #18161 

demo_v1_Fix_Allows_Null

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by hujambo-dunia** [comment]
[gmx_trjQAFixNumericValidation.XML.txt](https://github.com/user-attachments/files/16377894/gmx_trjQAFixNumericValidation.XML.txt)

@bernt-matthias Could you confirm the demo video above is as expected? (Demo XML file for video attached.)

@davelopez I removed the `!isNaN()` method since it outputs `True` when input was `Null` which is partly what caused the error. I believe the FormNumber.vue is expecting `Null` to _not_ be a number in order that the slider visualization does not appear when there is no maximum range listed. This was the only use of `isNan()` I could find in our `*.vue` files which is good.

@mvdbeek Unsure why 1 check is failing ("Selenium tests / Test (3.8, 0) (pull_request)"), if this is an issue related to my code that needs to be resolved prior to merge, please let me know.

**Review by bernt-matthias — APPROVED** [review]
Video looks good to me. Can't say much about the code changes.

**Review by davelopez — COMMENTED** [review]
Thank you @hujambo-dunia
You may need to target an older branch (probably 23.0), as this is a bug fix.

**Review by davelopez — APPROVED** [review]
Thank you!

Test failures are unrelated.

At some point, when this component gets refactored to composition API + Typescript it will be easier to catch and handle all these type mismatches :+1:

**Pull request merged**
