### PR TITLE
update pinned-requirements.txt

### PR DESCRIPTION
**Pull request by matthdsm**
Updated Bioblend version 0.6.1 > 0.7.0

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
The version needs to be updates in Starforge's wheels.yml and new wheels need to be built before this can be done. See http://starforge.readthedocs.org/en/latest/readme.html#pull-request-wheel-builder

Unfortunately our Starforge build server is down, I'll head over to the machine room hopefully today to figure out what's up.

**Comment by natefoo** [comment]
More complete documentation: https://github.com/galaxyproject/galaxy/blob/release_16.01/doc/source/admin/framework_dependencies.rst#adding-additional-wheels-as-galaxy-dependencies

The Starforge build server is back up, so you can go ahead and PR it there.

**Comment by matthdsm** [comment]
Hi Nate,

I made the same change in the starforge repo and submitted a pull request!

M

Op 28 jan. 2016, om 19:29 heeft Nate Coraor <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

More complete documentation: https://github.com/galaxyproject/galaxy/blob/release_16.01/doc/source/admin/framework_dependencies.rst#adding-additional-wheels-as-galaxy-dependencies

The Starforge build server is back up, so you can go ahead and PR it there.

**Comment by natefoo** [comment]
Thanks! These wheels are now on wheels.galaxyproject.org. Could you also update pinned-hashed-requirements.txt using the checksums in https://depot.galaxyproject.org/starforge/wheels/build-39/checksums.txt please?

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by matthdsm** [comment]
Will do! Do I add the hash for the wheel of the tar.gz file? or both?

M

**Comment by natefoo** [comment]
It should be both the source and wheel hashes.

**Comment by matthdsm** [comment]
Hi Nate,

I modified the hashed in pull request #1646.
ps, sorry for the barrage of pull requests, I’m making the modifications directly from the github interface.

M

**Comment by natefoo** [comment]
Thank you @matthdsm!

**Pull request merged**
