### PR TITLE
Masthead/Scratchbook revision and test cases

### PR DESCRIPTION
**Pull request by guerler**
masthead
This revision unites masthead tabs and icons into a single view, transitions its options into a model and applies coding styles to masthead and scratch book code. It also adds test cases for the masthead and unifies/modifies its appearance:
- Tabs and Icons are highlighted properly and are shown closer to each other
- They now both support notes and secondary icons
- The Scratchbook-enable icon has a secondary check icon which is shown upon toggle
- The 'User Tab' is now displayed as 'User Icon'

### CODE REVIEW

**Comment by jmchilton** [comment]
Very nice, looks great to me. New and more prominent masthead icons are great! :+1:

**Comment by bgruening** [comment]
Awesome!

**Comment by guerler** [comment]
Thanks guys! Happy new year.

**Comment by bgruening** [comment]
To you too Aysam!

**Comment by martenson** [comment]
All over it is very nice, thanks @guerler . Scratchbook would also greatly profit from some hints and tutorial how to use it.

**Comment by guerler** [comment]
Yeah, I agree. I'll look into it this week.

**Pull request merged**
