### PR TITLE
Reinsert update state function to fix workflow execution which still relies on it.

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by martenson** [comment]
8 more API tests pass: https://jenkins.galaxyproject.org/job/docker-api/321/testReport/

**Comment by jmchilton** [comment]
One of the failing tests is for legacy API behavior that pretty much only existed for the tool form - it was never really documented so I would be happy to drop that variant of batching parameters from the API and deleting the test if there are not objections.

**Comment by martenson** [comment]
@jmchilton the second one?
 api.test_tools.ToolsTestCase.test_library_data_param
 api.test_tools.ToolsTestCase.test_map_over_two_collections_legacy

**Comment by jmchilton** [comment]
Yeah - the second one. I'm not sure what exactly the problem is but it is called `_legacy` for a reason and I did see some of the meta parameter code removed from the original PR that handled the "legacy" behavior.

**Comment by martenson** [comment]
so for the test_library_data_param we have

```
assert output_content == "TestData", output_content
'TestData\n\n
```

is the one extra `\n` a problem?

**Comment by jmchilton** [comment]
Probably it is a huge problem, that behavior really shouldn't have changed right?

**Comment by martenson** [comment]
we do not know if this is still connected to #829

**Comment by jmchilton** [comment]
True, nothing in #786 jumps out at me as looking like the culprit. I don't know.

**Pull request merged**
