### PR TITLE
Selenium Overhaul

### PR DESCRIPTION
**Pull request by jmchilton**
- This includes #4704 which fixes a bug that hits Selenium maybe?
- This includes #4694 which overhauls how Selenium works with time and sleeps as well as adding a test for Juypter and others tests.
- This also includes a new commit on top of those that uses a new more structured, more object oriented approach to reading "navigation data" and component descriptions from a YAML file.

The previous YAML file "navigation-data.yml" was pretty unstructured - labels, selectors, text all over the place. Sometimes selectors outside of other components, etc... The new YAML file "navigation.yml" has a pretty clear grammar at the top and is parsed in a structured way. The idea is to break everything into components and sub-components. Any component can be associated with "selectors" (which can be XPATH, CSS, etc...), labels, and text bits. These are parsed into objects which have a more object oriented and more uniform interface. The commit is large and changes a lot - but just take for instance the following diff:

```diff
-            self.click_xpath(self.navigation_data["selectors"]["registrationPage"]["submit_xpath"])
+            self.wait_for_and_click(self.navigation.registration.selectors.submit)
```

As the consume of the selector - you don't need to know it is XPATH for instance. Before we had different wait methods for CSS, XPATH, Labels, IDs, etc.... Now for all selectors coming out of the navigation component data you can just use a single method. Also note that it goes from component to selector to selector name for all selectors and the more concise object oriented accession then the previous raw dictionary based approach.

Here is a Jenkins build that passes with this branch https://jenkins.galaxyproject.org/view/All/job/jmchilton-selenium/42/. Hopefully that will help make merging easier?

### CODE REVIEW

**Comment by jmchilton** [comment]
dev's performance today:

screen shot 2017-10-02 at 3 03 01 pm

this branch's performance today (since I last rebased it):

screen shot 2017-10-02 at 3 03 18 pm

**Comment by bgruening** [comment]
This is insane wonderful! I would merge it right now but there are a few client changes in it. @dannon can you look at this please. 

Thanks a ton @jmchilton!

**Comment by dannon** [comment]
Just finished running the suite locally and checking through it.  This looks really nice to me, definitely a usability improvement for the tests.  The included #4704 also looks reasonable as a stab at that elusive bug.

**Comment by jmchilton** [comment]
Thanks for the merge @dannon!

**Pull request merged**
