### PR TITLE
Implement #8183 for further GitLab integration. 

### PR DESCRIPTION
**Pull request by selten**
Allow toggling of the proxy functionality, add automatic assignment to the last person that commited to the repository.

### CODE REVIEW

**Review by hexylena — COMMENTED** [review]
looks good! haven't tested personally, but I guess you're the primary user of this reporter, the code all looks valid

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
Thanks @selten!

**Comment by hexylena** [comment]
Oh, I guess my 'review' comments never were recorded/submitted, only thing was "why make proxy optional if it can be autodetected/configured by presence of those env vars" but this is a small detail.

**Comment by selten** [comment]
@erasche Because the no_proxy variable isn't being respected seemingly. So therefore there are use cases where turning this off completely is preferential.

**Pull request merged**
