### PR TITLE
xsd: reorder choices for permissive boolean

### PR DESCRIPTION
**Pull request by bernt-matthias**
in order of preference. language server seems to take the suggested values from this list using this ordering.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — APPROVED** [review]

**Comment by mvdbeek** [comment]
I guess that's moot now that it's a union (starting from 23.2), where the actual boolean comes first ? No problem either way

**Comment by bernt-matthias** [comment]
> I guess that's moot now ...

So you mean that starting from 23.2 the order has no meaning anymore and the preference might need to be implemented directly in the language server?

**Comment by mvdbeek** [comment]
It's a union, I don't know what the language server does, but if it follows the schema and uses the first valid option it'll be fine.

**Comment by davelopez** [comment]
The language server uses a custom parser for the XSD (it was a toy project to learn Python :man_shrugging:), but I don't remember from the top of my head, I guess if the first valid option is the one we want to present to the user it will work. For enums like this, it will present the options as they appear in the declaration not sure for unions though.

**Pull request merged**
