### PR TITLE
Remove static/scripts/* from the dev branch, add to .gitignore.  

### PR DESCRIPTION
**Pull request by dannon**
Per conversations with several folks, it'll make it easier to manage dev without having to wrangle these, request rebases to remove cruft, etc.  The plan will still be to include these in all release branches along with any other artifacts for distribution.  This slight release-time burden (one command, `git add -f static/scripts/*` as a part of release finishing to easily add it all) is outweighed by making dev easier to work with.  Additionally, it's probably just the right way to handle this in `dev` anyway, since we don't want to ship likely outdated and potentially incompatible static scripts.

Ping @guerler

### CODE REVIEW

**Comment by martenson** [comment]
I am 👍  on this. We should think hard of the places where we could have problems with on-the-fly client building before merging this (tests, docker-galaxy, cloud?). Maybe there are none.

**Comment by nsoranzo** [comment]
What about `static/style/blue/base.css` ? I see it modified when I do `git status` on `dev`.

**Comment by dannon** [comment]
@nsoranzo That file shouldn't usually change unless there are actual style changes; I'm wondering if it got left out of a recent commit?  I was hoping to handle just scripts here, and we can work on other build artifacts separately.  (sprite handling, etc).

**Comment by dannon** [comment]
@martenson I can't think of any, but maybe it'd be good to have those things fail fast (i.e. -- delete this stuff now, early in the dev cycle) rather than potentially use an outdated client for a while.

edit: Thinking about it more, too, if the on-the-fly client build fails then the galaxy service won't start anyway and we'd hopefully already be seeing some of those problems since the merge of that PR.

**Comment by guerler** [comment]
I am in favor of this. 👍

**Comment by guerler** [comment]
@martenson can we move forward with this?

**Comment by martenson** [comment]
@guerler For sure.

**Comment by guerler** [comment]
Awesome. Thx.

**Pull request merged**
