### PR TITLE
Fix no dataset found

### LINKED ISSUE #5828: when using API to get a dataset not existing, an error is raised instead of a "not found"
Which Galaxy: latest dev and previous

When using bioblend (or api) to get a dataset:

    ds = gi.datasets.show_dataset('XXXX')

if dataset does not exists, galaxy does not return a not found error but a 500 error with "None has no attribute dataset"

Code expects to have an exception on query but (may depends on librairies/databases) query just return a None if dataset_id is not found.

API should return correct HTTP code with message "dataset_id does not exists"

### PR DESCRIPTION
**Pull request by osallou**
This PR closes #5828 and returns a HTTPRequestRangeNotSatisfiable if dataset is not found instead of a 500 failure with python error.

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
I took the liberty and switched to a more fitting http response, thanks for the contribution @osallou !

**Comment by dannon** [comment]
LGTM, thanks @osallou!

**Comment by osallou** [comment]
@martenson, indeed http error code was not the best, i simply used what was
already done before, to limit scope of PR.

But why not using a 404 not found?

**Comment by martenson** [comment]
@osallou My thinking was that this endpoint is now marginally more difficult to use for ID guessing.

**Pull request merged**
