### PR TITLE
[19.05] Fix shed_tool_conf isolated tool (not in section) removal

### PR DESCRIPTION
**Pull request by dannon**
Should fix https://github.com/galaxyproject/galaxy/issues/8471

Looks like an oops in https://github.com/galaxyproject/galaxy/pull/7300/files#diff-b90bd48b86c144bb69d7201cb65bda65R412

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]
Damn copy/paste, thanks for the fix!

**Comment by nsoranzo** [comment]
Need to backport to 19.05.

**Comment by dannon** [comment]
@nsoranzo I'll just rebase/retarget this one in a sec.

**Comment by mvdbeek** [comment]
Thanks @dannon!

**Pull request merged**
