### PR TITLE
Remove /mobile and associated templates

### PR DESCRIPTION
**Pull request by dannon**
I stumbled across this when updating/locking/removing libraries (specifically jQtouch, which is dead) for #4435.  This endpoint has been effectively deactivated for almost three years now, and if we're approaching mobile again it won't be with custom templates for each endpoint, etc.

If folks really want, I'll add a route/redirect, but I really don't think we need to at this point.

(I left the mobile *styles* thinking that's actually something we might want to work with moving forward, but none of this would be useful)

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by dannon** [comment]
After looking more, the styles require resources that aren't even there, and we'd do that differently in the future as well.  One more change coming, then I'll flag this for review.

**Comment by dannon** [comment]
Ok, I went ahead and pulled jQtouch out as well to make this a comprehensive PR removing all of the related materials here.  Ready for a second look and a merge, thanks @nsoranzo and @guerler!

**Comment by jxtx** [comment]
Definitely kill all of this.

**Comment by martenson** [comment]
This kills urls, but after ~3 years of deprecation I think that is fine. Thanks @dannon !

**Pull request merged**
