### PR TITLE
Update the schema image in architecture slides to be correct and recent (and use git-lfs for doc pngs)

### PR DESCRIPTION
**Pull request by dannon**
I think the one that was being used is the one I generated many years ago, which is pretty out-of-date.

### CODE REVIEW

**Comment by dannon** [comment]
(testing git lfs tracking of this file, one sec)

**Comment by martenson** [comment]
this seems to be adding many more pictures than the schema image

**Comment by dannon** [comment]
@martenson Yes, I swapped `doc/**/*.png` to use git-lfs.

(https://git-lfs.github.com/ for more information)

**Comment by martenson** [comment]
I would suggest to try introduce git lfs in a separate and clear PR. Since devs need to install this extension. Also we should probably discuss pros and cons of storing our files outside of repo. Doesn't it add an extra step to cloning?

**Comment by dannon** [comment]
Hrmm.  If you think it's going to be contentious, I can open it separately, though I did not expect it'd be a concern.

We could potentially use this for other large files, but I limited it to `doc/**/*.png` intentionally at first, so we could try it out slowly.

**Comment by martenson** [comment]
@dannon this adds some complications, right? Like if you want to build the slides you need to somehow fetch the lfs-stored files. So you have to be online?

**Comment by dannon** [comment]
(force-pushed to truncate at the first commit, reopening the LFS stuff separately)

**Comment by martenson** [comment]
This increased the size of the schema image sixfold to almost 3MB. Can we get it back to half a meg? I tried simple compression but that does not seem to help.

**Pull request merged**
