### PR TITLE
Add accepted extensions to form data input

### LINKED ISSUE #9218: List accepted formats of data inputs in help.
I would like to suggest to add the list of data types that are accepted by a data input parameter automatically to the help of the parameter. Similar to what happens for the `argument` attribute.

Otherwise users do not know (except if the tool developer provided the info manually) what kind of data is expected by a tool. 

Currently only if the history does not contain a suitable data set the selector lists the file types `No ... data sets available`. As soon as a single data set is available this is not the case but the first suitable is selected and the user does not see the alternatives anymore

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
closes [#9218](https://github.com/galaxyproject/galaxy/issues/9218)

image

image

image

image

This PR adds the following features:

* a drop-down listing all accepted data extensions, if they are specified.
* tool-tip previewing accepted extensions in a list
* new error message which names the accepted extension, if there are less than 5

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
> a drop-down listing all accepted data extensions, if they are specified

I don't think that is right - things can be auto-converted or subclasses and they don't seem listed based on the screenshots. I don't know if "target formats" is better terminology than "accepted formats" for this reason? Maybe I being pedantic though.

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
Leaning into the pedantic... maybe even listing this just because the option list is empty is wrong also. There might be things of the right datatypes that are filtered for other reasons. This is a tough problem and this PR might be a good step forward, I don't know.

**Comment by martenson** [comment]
This is an improvement and given the complexity of the situation inherently imperfect. We should watch for any confusion or problems that people have with this and adjust if needed.

**Comment by martenson** [comment]
Thank you @ElectronicBlueberry

**Pull request merged**
