### PR TITLE
Added title on anchor tag on keyboard Focus for W3C Accessibility Compliance

### LINKED ISSUE #15383: Import Info Tooltip not Accessible
The import info addressed in #14857 is not accessible.
`aria-describedby` is being added on hover, but there is no way to access this information  without a mouse. I suggest adding a sr-only text

**To Reproduce**
1. Import a workflow
2. Try seeing which workflows are imported relying on text and keyboard only

**Expected behavior**
It is in some way communicated which workflows are imported, without needing to rely on mouse or icons.

**Additional context**
A solution might be to duplicate the label on the focusable workflow name

### PR DESCRIPTION
**Pull request by hujambo-dunia**
_(Turn on audio for "voice over" Accessibility audio)_
https://user-images.githubusercontent.com/3672779/217060458-0845ab8f-8d2d-4c3b-a48e-feeb557ae7cc.mp4

closes #15383 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by ElectronicBlueberry — APPROVED** [review]

**Comment by davelopez** [comment]
Thank you!

**Comment by davelopez** [comment]
Does this one need to be backported to 23.0?

**Comment by mvdbeek** [comment]
Yes, I think so.

**Comment by davelopez** [comment]
@hujambo-dunia do you want to backport it to 23.0? or should I do it?

**Comment by hujambo-dunia** [comment]
Hi @davelopez yes, please go ahead and backport this PR. Thank you.

**Pull request merged**
