### PR TITLE
Implement min/max for multiple data input parameters.

### LINKED ISSUE #749: multiple="True" should allow min/max params
Needed for https://github.com/galaxyproject/tools-iuc/issues/239
I'm replacing `<repeat>` blocks with `multiple="True"` and some need to be able to specify `min="1"`.

### PR DESCRIPTION
**Pull request by jmchilton**
Closes #749.

### CODE REVIEW

**Comment by hexylena** [comment]
This is one of those cases where I look forward to jenkins tests of PRs. (I'm not going to merge just yet as I haven't actually tested any of the code, but I'm just commenting to commit to testing this and merging this in case no one else does)

**Comment by nsoranzo** [comment]
@erasche @martenson It seems to me we are not far from the point in which Jenkins tests of PRs can be enabled, right?

**Comment by nsoranzo** [comment]
:+1: 

```
./run_tests.sh -framework
./run_tests.sh -api
./run_tests.sh -with_framework_test_tools -api
```

All passed for me.

**Comment by hexylena** [comment]
@nsoranzo no, not far at all. We just need to get all tests passing first, before they're really meaningful or helpful.

**Comment by nsoranzo** [comment]
@erasche We can proceed incrementally, starting with the ones that are passing (e.g. API tests).

**Comment by martenson** [comment]
@nsoranzo `-api` used to pass but then @erasche started to dockerize it I think and I do not know where we are now. `-framework` is passing though. I would like the tests to be more steady and improved before we put in work all the PR plugins and email notifications and stuff. It needs to be reliable so people won't discard  and ignore it.
ping @jmchilton

**Comment by hexylena** [comment]
@nsoranzo, perhaps. It feels weird to me (I think of the case where people see the "passes" test and don't realise that it's failing other tests, but perhaps that's a minor concern), but yes, we could add one suite of tests at a time. 

@martenson ouch :P It should be passing, did I screw things up?

**Comment by hexylena** [comment]
@martenson I just paused the tests because the jenkins user couldn't run the docker command, is that fixed?

**Comment by martenson** [comment]
@erasche dunno, I did not run it since you cancelled the build, thought you are still working on it :)

**Comment by hexylena** [comment]
Ah, sorry, I didn't convey that clearly. Is jenkins able to execute 'docker'? If so,  the test should be ready to go

**Comment by hexylena** [comment]
https://jenkins.galaxyproject.org/job/G-API/DATABASE_IMAGE=postgres%3A9.4,TOXENV=py26/33/console this was the test leading me to believe jenkins couldn't docker. I'll re-enable the test now...maybe this is fixed.

**Comment by hexylena** [comment]
Yep, triggered another build and same problem.

```
[py27] $ /bin/bash /tmp/hudson9158665370566809414.sh
time="2015-09-22T11:47:03-04:00" level=fatal msg="Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
docker: "inspect" requires a minimum of 1 argument. See 'docker inspect --help'.
```

(docker inspect is giving that error because it's run like `docker inspect $CONTAINER_ID

**Comment by martenson** [comment]
@erasche could be ok now, keep an eye here: https://jenkins.galaxyproject.org/job/G-API/35/console

**Comment by hexylena** [comment]
@martenson nope :( it doesn't show up in the parent jobs, only the child jobs. https://jenkins.galaxyproject.org/job/G-API/DATABASE_IMAGE=postgres%3Alatest,TOXENV=py26/35/consoleFull

**Comment by hexylena** [comment]
Jenkins/Docker is working now. Whu!

We need to dockerize the galaxy portion (ah if only @bgruening's images were already split up), so that we can parallelize these builds. Currently they're running sequentially because they all use the same `files/database` folder on disk, as they all share the same workspace, I foresee that causing hard-to-detect havoc.

**Comment by jmchilton** [comment]
Guys - I appreciate the do-acractic approach but  `run_tests.sh --dockerize --db $DB_TYPE` is the future I think, that is what we should be using. It works for `--framework` tests today, probably it would work for API tests as well.

**Comment by hexylena** [comment]
@jmchilton see previous comments about dislike of pinning us to a database version and host OS. See your comment that it's [okay to have multiple containers](https://github.com/galaxyproject/galaxy/pull/759#issuecomment-141713234). My understanding is that --dockerize expects a database inside, and that's just not friendly. What's wrong with .ci/scripts which test with properly separated containers? People want that [for deployment](https://github.com/bgruening/docker-galaxy-stable/issues/43) anyway.

**Comment by jmchilton** [comment]
`--dockerize` is already done, what do you mean it is not friendly? It works today for all three types of databases we support.

It is much easier to just use the very simple command-line options and have everything just magically work than having to setup the container separately, etc... for a end developer.

**Comment by hexylena** [comment]
@jmchilton I was wrong to say unfriendly, sorry, that's not a technical reason to dislike it. I dislike it because it hides things that may be important away and sticks everything in a single container which makes me uncomfortable. 

Again, all of the discussion in that thread, I'd be more comfortable with the ability to test against specific versions of databases rather than relying on whatever version the ubuntu image has provided us with. 

People want split containers for deployment, this is a parallel goal to that. We would be testing in something used for production deployments:

> So people can run the exact testing commands on the remote server and not just run the same database container with some docker magic

(sorry if ^ is a tiny bit out of context, just wanted to note that we have identical goals, dev/prod/test parity)

**Comment by hexylena** [comment]
`--dockerize` may be done, but I don't think it's the long term answer, there's a clear "where to go from here" that involves `docker-compose.yml` for deploys and testing

**Comment by jmchilton** [comment]
I mean I guess I am fine that there is an option to use multiple containers for running tests, I'm not sure there is a reason to prohibit just using the one container though. So if that is the case, I still feel like there are two parallel tasks:
- Get jenkins to setup and use `--dockerize` for all testing.
- Modify `--dockerize` to optionally use `docker-compose.yml` style deployments.

I think the paramount thing is that we make it dead simple to run tests tests for the end developer, I feel like baking this stuff into `--dockerize` is the way to do that.

**Comment by bgruening** [comment]
@erasche  see also this issue: https://github.com/bgruening/docker-galaxy-stable/issues/43
We are not there yet. From my feeling Docker compose is still to complicated and error prone. It might be the way forward but not yet. Let's start small with what we have currently and extend it later.

**Comment by jmchilton** [comment]
The other advantage of `test/docker/base` over docker-galaxy-stable currently is that it does not have this issue https://github.com/bgruening/docker-galaxy-stable/issues/31.

**Comment by hexylena** [comment]
@jmchilton okay, I see where you're coming from now, streamlining the developer experience. That's excellent, my goal was broad spectrum testing rather than the quick and dirty tests a dev might want to do to check that things don't break.

Is there any reason to bake the `docker-compose.yml` type tests into `--dockerize`? I get that you want to have a single place for testing with docker to go through, but it seems overly complex compared to just running the test command in a `docker-compose` environment that was set up for running a production instance.

@bgruening I linked that above, yes :)

**Comment by hexylena** [comment]
@jmchilton I'll have to follow up with bgruening/docker-galaxy-stable#31 I'm not sure I'm 100% understanding the issues involved there but that's orthogonal to this discussion.

**Comment by jmchilton** [comment]
I mean I would need to see the details, but just adding the `--dockerize` flag to `run_tests.sh` means that all the same options work regardless. The developer doesn't need to worry about learning anything new. I feel like it is the simplest possible developer experience and does not require the developer learn anything new. You could convince me otherwise I suspect, but large jenkins command scripts are doing the opposite :(.

**Comment by hexylena** [comment]
--dockerize is better for developers, agreed. 

However, I think that the _complete_ test suite across multiple platforms/configurations isn't something a developer is going to be running, and is more analogous to a proper galaxy deployment and should reflect the architectures and software versions that Galaxy expects to run on.

**Pull request merged**
