### PR TITLE
[18.01] Install latest conda and don't use shell=True

### PR DESCRIPTION
**Pull request by nsoranzo**
See commits for details.

### CODE REVIEW

**Comment by jmchilton** [comment]
Awesome - good idea to catch up early after the branch!

**Comment by mvdbeek** [comment]
Should we backport b8873c65ad8c2b14bf00de2330586e606c232787 to 17.05 ?

**Comment by nsoranzo** [comment]
Maybe 17.09? Conda installation is performed only at startup.

**Comment by mvdbeek** [comment]
Sounds good, though I'd probably encourage anyone with conda issues to update the channel order and install 4.3.33, so in that spirit I was thinking to apply this to the last supported release.

**Pull request merged**
