### PR TITLE
Allow InteractiveTools to use path-based proxying when requires_domain=False

### PR DESCRIPTION
**Pull request by blankenberg**
Only a subset of InteractiveTools Entry Points can currently make use of path-based proxying. It is possible that potential coverage can be increased through enhanced path rewriting, etc, rules.

### CODE REVIEW

**Comment by martenson** [comment]
I am sorry but I have no idea what this does. I'd like to review it but it looks like days of diving into uwsgi routing without at least a basic documentation or examples are working now, that did not work before.

**Comment by mvdbeek** [comment]
@blankenberg can you add an example and/or some documentation for how to use this ?

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
@blankenberg can you rebase this please ?

**Comment by mvdbeek** [comment]
@blankenberg if you can rebase this before Friday I'm happy to get this in to 20.09, but I've pushed the milestone to 21.01 for now.

**Comment by mvdbeek** [comment]
Well, that took a while, but we finally got there. Thanks @blankenberg !

**Pull request merged**
