### PR TITLE
HTML Escape Workflow import Exception

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by dannon** [comment]
I'd actually prefer just removing the exception echo completely.  We shouldn't be showing exceptions to users in messages.  It should be log.exception'ed, with a user-friendly message presented.

**Comment by dannon** [comment]
(other than that, this is clearly an improvement, so +1 if folks think we should keep the exception in there)

**Comment by blankenberg** [comment]
I find the exception in the case to be helpful, as it is often e.g., 'node not found' or 'connection refused', 'unknown protocol', which can help with fixing the problem.

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Hrmm, ok.  We can potentially revisit whether or not to surface raw Exception messages in the future, merging this for now.

**Pull request merged**
