### PR TITLE
Add support to PDBQT molecule datatype

### PR DESCRIPTION
**Pull request by leobiscassi**
Hi @bgruening , here the PR according with discussing in Autodock Vina PR on ChemicalToolBoX. Please, can you check?

### CODE REVIEW

**Comment by bgruening** [comment]
@leobiscassi two pep8 errors :)

```
./lib/galaxy/datatypes/molecules.py:495:1: E302 expected 2 blank lines, found 1
./lib/galaxy/datatypes/molecules.py:547:1: E302 expected 2 blank lines, found 1
```

**Comment by leobiscassi** [comment]
@bgruening problems are solved, thanks for you help!

**Comment by martenson** [comment]
👍

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@nsoranzo I believe the doctests were executed in travis? is that not the case?

edit: `Doctest: galaxy.datatypes.molecules.PDBQT.sniff ... ok`

**Comment by nsoranzo** [comment]
Yeah, I guess.

**Pull request merged**
