### PR TITLE
Client build: do not drop console when compressing, when not compress…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…ing do not mangle variable names

### CODE REVIEW

**Comment by dannon** [comment]
So I just recently removed the console logs in #601, intentionally.  Is this something we ever actually ever want to ship?  I can't think of any other websites that do.

**Comment by carlfeberhard** [comment]
Yeah - I understand. Apologies for not catching that then.

It's very useful for live debugging of deployed systems. Plenty of sites do and there's no harm in including them.

Many of our included libraries output to console as well, console.error is used throughout galaxy for additional error info, and the (admittedly) unused client metric system uses console for local logging which would also help with debugging.

**Comment by dannon** [comment]
Out of curiosity, how often has it actually been useful to have console output from real deployments in debugging things?  I briefly searched the mailing list and biostar and didn't find anything worth warranting the inclusion.  I'm not a -1, more like -0, but it just feels a little off to me -- like shipping a binary compiled with debugging output left on.

**Comment by carlfeberhard** [comment]
Aside from taking my word for it - I'm sorry - I don't have a paper trail for you. It's proved useful for me to debug the test server a number of times and main at least once.

Comparing it to debugging output from a binary isn't quite right. I'd suggest thinking of it as our logging/log system on the backend. The user does not see this without opening the console.

**Comment by guerler** [comment]
Yes, I agree with Carl. It can be very useful to have outputs in production instances.

**Comment by dannon** [comment]
I'm still -0, but that's fine.  Merging manually to resolve conflicts.

**Comment by martenson** [comment]
:+1:

**Pull request merged**
