### PR TITLE
Fix blockquote>p sizing

### PR DESCRIPTION
**Pull request by hexylena**
Noticed this styling, it was quite unattractive. I've made a change that removed it, and I'm not seeing anywhere else that uses a blockquote containing a p, other than tool help.

utvalg_015

### CODE REVIEW

**Comment by jmchilton** [comment]
I feel like modifying bootstrap's stock less files (https://github.com/twbs/bootstrap/blob/v2.3.2/less/type.less#L196) is likely not the correct way to handle this. It seems like this will make updating against upstream bootstrap changes more difficult.  Can you restrict this change to a style sheet that just affects the tool form and simply undoes the change you find visually unappealing?

**Comment by hexylena** [comment]
yeah, TIL galaxy_boostrap.less exists. I'll move my changes there.

**Comment by jmchilton** [comment]
Fantastic - thanks @erasche!

**Comment by jxtx** [comment]
We could probably remove the stock bootstrap files and pull them in with
bower as part of the client build process to avoid this confusion.

(Things that didn't exist when these files were checked in ;)

**Comment by hexylena** [comment]
should be fixed now (though not entirely sure why the JS files ended up being recompiled. Urgh)

**Comment by martenson** [comment]
@erasche 
> TIL galaxy_boostrap.less exists. I'll move my changes there.

[really](https://gcc2017.sched.com/event/9muI/advanced-customisation-of-a-galaxy-instance)? :D

**Pull request merged**
