### PR TITLE
Add a password strength evaluation bar

### PR DESCRIPTION
**Pull request by benfulton**
Modify the register and change_password pages to show a bar
evaluating the strength of the password. Bar displays in red
for passwords < 6 chars or below a certain minimum complexity;
green otherwise. Adds a dependency on Complexify, a password
evaluator written by Dan Palmer. Let me know if you'd like any changes!

### CODE REVIEW

**Comment by martenson** [comment]
thank you @benfulton for the contribution
I will test this tomorrow but one thing that needs to be done is to run `make client` and add the created artifacts to the PR (e.g. the modified`base.css` file has to be here)

**Comment by carlfeberhard** [comment]
Initial read through looks fine. You'll need to recompile and include it, though, since our build artifacts are still in the repo:

```
make client
```

...should be enough in this case. Then add the uncompressed, compressed, and source map for complexify.

Edit: martenson was too fast

**Comment by benfulton** [comment]
Thanks, I'll work on this.

**Comment by jmchilton** [comment]
@benfulton I'm going to label this a WIP for now, ping us when you have added this files or if you need help. Thanks a bunch for the contribution.

**Pull request closed without merging**
