### PR TITLE
irods methods now create/destroy irods connections.

### PR DESCRIPTION
**Pull request by kxk302**
Reading irods forum, it seems the best practice is for apps to not maintain a connection to irods, but rather create/destroy them as needed. 

We are seeing some irods Sentry errors. One theory is that irods server drops stale connections (without client knowing). After this, the first call would times out and a new connections is created and all is good until the same issue repeats. 

Creating/dropping connections, should solve this problem.  

@mvdbeek I think this PR should be reviewed before https://github.com/galaxyproject/galaxy/pull/9928

### CODE REVIEW

**Comment by mvdbeek** [comment]
This looks odd. You probably don't want to run shutdown on every method and instead make the connection a property if this is really the right thing to do, but this seems to run counter to the existence of the session pool in the python-irodsclient. Are these irods forums publically available ? Shouldn't python-irodsclient handle such dropped connections ? Did you manage to get a handle on this on the irods server side ? I don't think the Galaxy object store layer is the right place to manage this.

**Comment by kxk302** [comment]
> This looks odd. You probably don't want to run shutdown on every method and instead make the connection a property if this is really the right thing to do, but this seems to run counter to the existence of the session pool in the python-irodsclient. Are these irods forums publically available ? Shouldn't python-irodsclient handle such dropped connections ? Did you manage to get a handle on this on the irods server side ? I don't think the Galaxy object store layer is the right place to manage this.

I agree that this looks odd. The irods forum is public, I believe. See if you can access it (https://groups.google.com/g/irod-chat). There is an old thread that discusses this connection issue. I asked for an update on this topic. 

I need to dig into irods-client code further.

Anyways, the Sentry errors are still around, and when Nate and I looked into it, it seems the un-used connections are dropped. Creating/dropping a connection for every irods call should circumvent this issue.

**Comment by mvdbeek** [comment]
Might be worth checking with the python-irodsclient folks, I suppose this must be a common problem then. Did you manage to reproduce this locally ?

**Comment by kxk302** [comment]
Created a new PR for this (https://github.com/galaxyproject/galaxy/pull/9941)

**Pull request closed without merging**
