### PR TITLE
Enhance task monitor composable

### PR DESCRIPTION
**Pull request by davelopez**
- Improve the API endpoint return type annotation
- Migrate composable and tests to Typescript

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by davelopez** [comment]
I think the [Selenium Integration test failure for export progress tracking](https://github.com/galaxyproject/galaxy/actions/runs/6246095704/job/16956519759?pr=16695#step:11:5004) might be related... It is known to be flaky, but it seems to be failing more consistently now. I'll investigate and hopefully get rid of the flakiness for good

**Comment by davelopez** [comment]
Hmm... I couldn't find the reason why the test is flaky... I doubt my last commit makes any difference and the last screenshot in the error report seems fine,

last


I don't know why the Tab component cannot change to the `to remote file` tab even if the following line:

https://github.com/galaxyproject/galaxy/blob/0daa4aa2e42bc38ec5f57d7b4dc0f40c8406b346/test/integration_selenium/test_history_import_export_ftp.py#L118

should have made sure that the tab was clicked... but for some reason that scapes me it doesn't sometimes.

**Comment by davelopez** [comment]
Well let's see how it behaves from now on, I will convert the HistoryExport component to Typescript and refactor it a bit anyway in a follow-up.

**Review by mvdbeek — APPROVED** [review]
Very cool, love those refactorings

**Pull request merged**
