### PR TITLE
[18.05] Allow non-ascii chars in pbkdf2 passwords

### LINKED ISSUE #6173: Registration failure (exception) when using a password containing extended set characters.
An example failing password would be `Müßiggänger`.

Ideally we support the full character set for passwords.  At minimum, it shouldn't just blow up like this.

### PR DESCRIPTION
**Pull request by dannon**
This should fix #6173

### CODE REVIEW

**Comment by nsoranzo** [comment]
@dannon I looked into this file for the Python3 support some time ago, and also @mvdbeek in https://github.com/mvdbeek/galaxy/commit/92251b47b297c74a91502a9ca72a0b0898559598 (but I think there was some issues in that commit). I'm quite busy this week, but I should be able to check again before the end of the week, if that's OK.

**Comment by dannon** [comment]
@nsoranzo It'd be good to get this into the release, which is this week, though I understand if you can't get to it in time.  I'll remove the specific review request, and whoever gets to it first is welcome to test/merge.

In my testing, swapping `bytes` for `smart_str` seems to work well in both py2 and py3, and yields the correct digests.  Maybe I should follow up and simplify the bits in https://github.com/mvdbeek/galaxy/commit/92251b47b297c74a91502a9ca72a0b0898559598?

**Comment by nsoranzo** [comment]
>  I'll remove the specific review request, and whoever gets to it first is welcome to test/merge.

Sure, do you know if that's a regression or an old issue?

>  Maybe I should follow up and simplify the bits in mvdbeek/galaxy@92251b4?

Maybe we can drop that commit if/when this get merged, not sure till I get back to my stashed changes.

**Review by jmchilton — APPROVED** [review]
Wrote a set of tests for these methods and verified both the problem and the fix, thanks Dannon. Thinking I should merge this as is and follow up in dev with the test case and Python 3 fixes .

**Comment by martenson** [comment]
@jmchilton sounds good to me

**Pull request merged**
