### PR TITLE
[15.10] UI, Collections: allow expansion to fetch details for DatasetDCEs (as…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…suming they're HDAs); move rerunnable and creating_job fetch to HDAs.

The upshot of this is:
- this fixes the api url issues currently with datasets in collections (at least HDAs)
- this allows editing, annotating, and tagging datasets from within collection panels
- this allows visualization and launching display applications (IGV, Gbrowse) from the collection datasets

@blankenberg @bgruening I could use a review to make sure the display apps work, please.
@jmchilton please review

### CODE REVIEW

**Comment by martenson** [comment]
Editing, annotating and tagging within collection works fine for me. The only surprise is that after I edit a dataset within collection, the history refreshes and closes the collection and highlights the original dataset in the history. Chances are that I want to edit another dataset in the collection so I have to find it again and click on it to get back.
Visualizations seem to launch without problem.

Thanks @carlfeberhard

**Comment by martenson** [comment]
:+1:

**Comment by carlfeberhard** [comment]
Yeah - that frustrates me, too. The history panel can't currently save whether a collection panel is open over it - so it will lose the user's place when the history refreshes. Editing the attributes and saving them will refresh the panel to show the changes at this point. I'd rather it simply fetched/shared only the dataset info that's changed instead of a full refresh, but that will require a bit more work in the long run.

IOW, on the list.

**Comment by jmchilton** [comment]
:+1: Thanks a bunch @carlfeberhard.

**Comment by bgruening** [comment]
Awesome @carlfeberhard! The basic things just work great. In Addition to @martenson concerns I found deleting a dataset is not consistent. 
1. Delete a dataset in a collection
2. You will see it at the top of the history that there are deleted datasets
3. undelete them in the main history view, they are still deleted in the collection

Or vice versa.

If anyone else want to test:
`docker run -p 8080:80 bgruening/galaxy-stable:experimental`

**Comment by carlfeberhard** [comment]
@bgruening That looks like an issue with caching of the collection data. It should display correctly after a refresh/page-reload. I'll see what I can do about fixing before the final 15.10 release that by just re-fetching the collection every time it's opened.

**Comment by bgruening** [comment]
@carlfeberhard thanks a lot. This really makes collections for us now usable. Before we weren't able to display them for example.
Given this PR just improves the current situation and that we have 2 x :+1: I will merge this!

Thanks again!
Bjoern

**Pull request merged**
