### PR TITLE
Allow multiple collections to be supplied to a multiple data parameter.

### LINKED ISSUE #750: multiple="True" should allow selecting multiple collections

### PR DESCRIPTION
**Pull request by jmchilton**
Allow multiple collections to be fed to a multi data parameter in one reduction step. Fixes #750 and will really simplify certain classes of tools.

Rebased original with fixes for rerun of such reductions.

Manually tested workflow execution and everything seems fine. The workflow editor already thought this was possible, so that is another bug corrected by this enhancement.

To run the associated API test, execute the following command:

```
./run_tests.sh -with_framework_test_tools -api test/api/test_tools.py:ToolsTestCase.test_reduce_multiple_lists_on_multi_data
```

### CODE REVIEW

**Comment by nsoranzo** [comment]
Should fix #750.

**Comment by jmchilton** [comment]
Dropped WIP tag, this is ready to be reviewed and merged.

**Comment by martenson** [comment]
test this please

**Comment by martenson** [comment]
@jmchilton jenkins found 10 failing framework tests for this

**Comment by jmchilton** [comment]
I think we can all agree this jenkins experiment is a bust, lets stop this testing.

**Comment by erasche** [comment]
stop this testing ... *for the time being*, right? Once the tests stabilise we'll turn the bot commenting/status API back on?

**Comment by jmchilton** [comment]
Marking this as WIP until the author fixes failing tests.

**Comment by jmchilton** [comment]
Taking backout of WIP, thanks for the catch @galaxybot and @martenson!

**Comment by hexylena** [comment]
@galaxybot test this (again, I want it.)

**Comment by jmchilton** [comment]
Rebased with fix for last failing API test.

**Comment by martenson** [comment]
functional.test_toolbox.TestForTool_output_format_collection.test_tool_000000

```
Error Message
Dataset metadata verification for [file_ext] failed, expected [txt] but found [data].
Dataset metadata verification for [file_ext] failed, expected [txt] but found [data].
```

I saw this before, cannot remember where.

**Comment by jmchilton** [comment]
Should be fixed by b036adcaa166153e544935c12123877c69a7450f.

**Comment by hexylena** [comment]
@jmchilton, awesome! Looking forward to it.

**Comment by nsoranzo** [comment]
framework tests pass for me locally.

:+1:

**Comment by jmchilton** [comment]
Rebased due to #1144.

**Comment by gregvonkuster** [comment]
@jmchilton Thanks for this feature!  

I'm running the latest from the dev branch, so i believe I have the feature.  I'm wondering how I need to change my tool to use it.  I've checked the code, but haven't quite figured it out.  I currently have this tool parameter...
    &lt;inputs&gt;
        &lt;param  name="input" type="data" format="gff" multiple="True" min="2" label="Match paired peaks on" /&gt;
...which provides a multi-select list for which I can choose the dataset collection option:

multi-select

However, the select list still does not allow me to upload more than a single dataset collection.  Do I need to make the parameter type "dataset_collection"?  If so, then the tool inputs would not allow for individual datasets which may be too restrictive.  Thanks in advance for the help on this!

**Pull request merged**
