### PR TITLE
History Introduction tour fixes for structural changes

### PR DESCRIPTION
**Pull request by dannon**
WIP, addressing https://github.com/galaxyproject/galaxy/issues/3182

### CODE REVIEW

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@bgruening Is the suite of tests now running testing tours too?

**Comment by bgruening** [comment]
Not yet, afaik, but @jmchilton was working on it. But all tests were red, so I thought retrigger before merging is a good idea.

**Comment by jmchilton** [comment]
There are tests for the other two tours - they work for me locally and on rare occasions on Jenkins. 

https://github.com/galaxyproject/galaxy/blob/dev/test/selenium_tests/test_stock_tours.py

**Comment by bgruening** [comment]
Always faster then I can follow. Thanks @jmchilton!

**Comment by dannon** [comment]
Yep, that's exactly what I wanted to check on, whether or not the 'tour testing' was live and functional, thanks guys!

**Comment by jmchilton** [comment]
@dannon I can no longer PR your repository - I assume it is because there are too many forks and it doesn't load them all in the drop down to select a target. However - if you'd be willing to merge https://github.com/jmchilton/galaxy/tree/tour_history_fixes into your branch that would be awesome. It fixes the tour and adds a test case for it.

**Comment by dannon** [comment]
@jmchilton Weird, sure, I'll check out merging that in.

**Comment by bgruening** [comment]
Got today a mail about this, can we get this fixed, anything blocking.

**Comment by dannon** [comment]
@bgruening Nothing blocking, just time.  Let me do this now.

**Comment by bgruening** [comment]
Urgs, sorry. But thanks for doing it now!

**Comment by dannon** [comment]
@bgruening Give it a shot now.

**Comment by dannon** [comment]
(I haven't had a chance to tinker with it again, but I did pull @jmchilton's additional changes to this branch, and took this out of WIP.  If this is a good start, we can merge it and move on from there.)

**Pull request merged**
