### PR TITLE
Replace registration mako with vue component

### PR DESCRIPTION
**Pull request by guerler**
This PR is a follow up to replace the registration mako with a vue component.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: on the Selenium fixes, they look good.

@guerler what is the plan, do you want to delay the release on this or can we push it to 19.05? If you want it in 19.01, anything I can do to help get it in?

**Comment by guerler** [comment]
Thanks @jmchilton. This PR relies on the deprecation of OpenID which we decided to be deprecated with 19.01. So it looks as if this PR will be part of 19.05.

**Comment by dannon** [comment]
@guerler Thanks for the fixes and the re-merge.  I'll check it out now.

**Comment by dannon** [comment]
One more fix coming to update the selenium tests again, then I'll get this in.

**Comment by dannon** [comment]
The one failing API test is unrelated and (I think) known to be dodgy.

**Pull request merged**
