### PR TITLE
Ckpt

### PR DESCRIPTION
**Pull request by astrovsky01**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
This might benefit from adding a sniffer for the magic bits.

**Comment by astrovsky01** [comment]
@bernt-matthias I'm intentionally not adding a sniffer for now to discourage uploading of these types of files. They're used in a tool for now, so are necessary, but would rather they be used purely from ones made in galaxy

**Comment by bernt-matthias** [comment]
Then it's fine. You still want `display_in_upload="true"`?

**Comment by astrovsky01** [comment]
Yes, for the case where someone pulls their data out of Galaxy and wants to put it back in. This pairs with the tool: https://github.com/galaxyproject/tools-iuc/pull/2427

**Review by mvdbeek — APPROVED** [review]
Is this ready to be merged ?

**Comment by astrovsky01** [comment]
@mvdbeek should be

**Comment by mvdbeek** [comment]
Thanks @astrovsky01!

**Comment by astrovsky01** [comment]
@mvdbeek awesome, thanks! Now we just need to figure out the scvis tool issues

**Pull request merged**
