### PR TITLE
[23.0] Find correct collection type if collection_type_source points at input of "any" collection type

### PR DESCRIPTION
**Pull request by mvdbeek**
And also adds a hover hint on the output terminal that mentions what type of output this is:

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nekrut** [comment]
Hmmm ... what is the difference between list and list:list?

**Comment by mvdbeek** [comment]
One is a list, the other is a list of lists, i.e when you click on the collection the elements are another collection.

**Comment by mvdbeek** [comment]
@nekrut is that any clearer ?
Screenshot 2023-03-19 at 14 11 43

**Comment by jmchilton** [comment]
Failing selenium test related? Worth a rebase?

**Comment by mvdbeek** [comment]
It's related, I'll figure it out

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/15823/commits/2180c38a35d61d4ef366bdf765dcb2ef78fb248c should fix the failing tests, but for some reason it looks like tests aren't being triggered.

**Review by dannon — APPROVED** [review]

**Pull request merged**
