### PR TITLE
Note on updating tool testing

### PR DESCRIPTION
**Pull request by hexylena**
Noticed https://github.com/galaxyproject/tools-iuc/pull/764 and https://github.com/galaxyproject/galaxy/pull/2378 and thought this should be on the TODO as well.

### CODE REVIEW

**Comment by jmchilton** [comment]
Perfect!

@nsoranzo - do you want to pile on and maybe enable bioblend testing for the branch as soon as  it is made earlier in the process?

**Comment by martenson** [comment]
we should do the same with  the devteam tools at 
https://github.com/galaxyproject/tools-devteam/blob/master/.travis.yml#L6

**Comment by martenson** [comment]
thanks @erasche !

**Comment by nsoranzo** [comment]
@jmchilton Sure! I just did that in commit https://github.com/galaxyproject/bioblend/commit/b74b1c302a1b8fed86786b40d7ecc3520cbadcd3 , are you going to add the task to `scripts/bootstrap_history.py` ?

**Pull request merged**
