### PR TITLE
Update browserslist and exclusions, linting.

### PR DESCRIPTION
**Pull request by dannon**
Prompted by a question about what's technically supported in UI/UX I updated and then checked through this; we can drop most of the old excludes as they are now not a part of 'default'.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by dannon** [comment]
Looks like eslint is still relying on older defaults, flagging the `compat` issues?

**Comment by hexylena** [comment]
Could we publish this in a human readable format somewhere, maybe?

**Comment by dannon** [comment]
Right now the list resolves to:
```
and_chr 104
and_ff 101
and_qq 10.4
and_uc 12.12
android 104
chrome 104
chrome 103
chrome 102
edge 104
edge 103
firefox 103
firefox 102
firefox 91
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 12.2-12.5
kaios 2.5
op_mob 64
opera 89
opera 88
safari 15.6
safari 15.5
samsung 17.0
samsung 16.0
```
which is a bit of a mouthful, and I think it's always a bit in flux. The setting maps to >.5% usage share, last two versions of the browsers, and not officially EOL'd.  If we want, the formal position could just be last two versions of "FF, Chrome, Safari, Opera" or something similar?

**Comment by hexylena** [comment]
Ah it's something that complicated then. Yeah, doesn't have to be a hard/permanent commitment but having that statement somewhere I think is useful from a user perspective.

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
