### PR TITLE
Mark sniffer for fastqillumina as not implemented

### PR DESCRIPTION
**Pull request by bernt-matthias**
Not sure if this was forgotten .. or is intended.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
We should probably remove the sniffing code instead.

**Comment by bernt-matthias** [comment]
> We should probably remove the sniffing code instead.

We could also add `NotImplementedError` to FastqSolexa

**Comment by mvdbeek** [comment]
Oh, wow, I think that has uncovered an interesting bug that we should probably fix like this:
```
diff --git a/lib/galaxy/datatypes/sniff.py b/lib/galaxy/datatypes/sniff.py
index 40341e0bc6..8d0f6192c1 100644
--- a/lib/galaxy/datatypes/sniff.py
+++ b/lib/galaxy/datatypes/sniff.py
@@ -664,7 +664,10 @@ def build_sniff_from_prefix(klass):
         if hasattr(self, "compressed_format"):
             if self.compressed_format != file_prefix.compressed_format:
                 return False
-        return self.sniff_prefix(file_prefix)
+        try:
+            return self.sniff_prefix(file_prefix)
+        except Exception:
+            return False
 
     klass.sniff = auto_sniff
     return klass

```

**Comment by bernt-matthias** [comment]
Maybe, but to me its odd that the the sniffer runs at all also for datatypes that are not listed in the datatypes config in the sniffers section.

**Comment by bernt-matthias** [comment]
Should we be more explicit with the exception, i.e. catch only `NotImplementedError`?

**Comment by mvdbeek** [comment]
My intuition is to use the same rules that we use for normal `sniff` functions, which is everything that is an exception is a False.

> are not listed in the datatypes config in the sniffers section.
IIRC think that section is only needed if you want to move the priority of sniffers up/down

**Comment by nsoranzo** [comment]
I think that:
```diff
diff --git a/lib/galaxy/datatypes/upload_util.py b/lib/galaxy/datatypes/upload_util.py
index 963e2bfb96..c4772c3533 100644
--- a/lib/galaxy/datatypes/upload_util.py
+++ b/lib/galaxy/datatypes/upload_util.py
@@ -80,9 +80,13 @@ def handle_upload(
     if requested_ext != 'auto':
         datatype = registry.get_datatype_by_extension(requested_ext)
         # Enable sniffer "validate mode" (prevents certain sniffers from disabling themselves)
-        if check_content and hasattr(datatype, 'sniff') and not datatype.sniff(path):
-            stdout = ("Warning: The file 'Type' was set to '{ext}' but the file does not appear to be of that"
-                      " type".format(ext=requested_ext))
+        if check_content and hasattr(datatype, 'sniff'):
+            try:
+                is_of_datatype = datatype.sniff(path)
+            except Exception:
+                is_of_datatype = False
+            if not is_of_datatype:
+                stdout = f"Warning: The file 'Type' was set to '{requested_ext}' but the file does not appear to be of that type"
 
     # Handle unsniffable binaries
     if is_binary and ext == 'binary':
```

is a better fix than 304e1cd because many datatypes don't have a `sniff_prefix()` method but have a `sniff()` method that can raise exceptions.

**Comment by mvdbeek** [comment]
> is a better fix than [304e1cd](https://github.com/galaxyproject/galaxy/commit/304e1cdc385109fc0e894e8d63d7ffa282309eea) because many datatypes don't have a `sniff_prefix()` method but have a `sniff()` method that can raise exceptions.

hmm, how is the try/except implemented for dataypes.sniff today ? Because exceptions are already caught for regular `sniff` functions

**Comment by mvdbeek** [comment]
Okay, so if the datatype is set to auto that would be https://github.com/mvdbeek/galaxy/blob/a61a6848dd9afe6c4408f24a15089e1e78647e80/lib/galaxy/datatypes/sniff.py#L602, but that's not the stack in question, which is
```
E           Exception: Job in error state.. tool_id: upload1, exit_code: 1, stderr: Traceback (most recent call last):
E             File "/home/runner/work/galaxy/galaxy/galaxy root/test/functional/tools/upload.py", line 342, in <module>
E               __main__()
E             File "/home/runner/work/galaxy/galaxy/galaxy root/test/functional/tools/upload.py", line 335, in __main__
E               metadata.append(add_file(dataset, registry, output_path))
E             File "/home/runner/work/galaxy/galaxy/galaxy root/test/functional/tools/upload.py", line 145, in add_file
E               convert_spaces_to_tabs=dataset.space_to_tab,
E             File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/datatypes/upload_util.py", line 83, in handle_upload
E               if check_content and hasattr(datatype, 'sniff') and not datatype.sniff(path):
E             File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/datatypes/sniff.py", line 667, in auto_sniff
E               return self.sniff_prefix(file_prefix)
E             File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/datatypes/sequence.py", line 866, in sniff_prefix
E               raise NotImplementedError
E           NotImplementedError
E           .
```
So whenever you'd set the datatype to a sniffer that isn't actually the right sniffer and that doesn't catch the exception the upload would fail ... anyway, yeah, I agree that s the better fix.

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
