### PR TITLE
Interactive Tours installable via tool sheds

### PR DESCRIPTION
**Pull request by yhoogstrate**
Dear Galaxy maintainers,

In this PR I propose support for Interactive Tours installation via a tool shed.

The code in this PR: 
 - Adds a new subtype of Galaxy TS repository (Interactive Tours)
 - Directly loads them after installation
 - Directly unloads them afer removal/de-installation
 - Is able to deal with multiple tours with the same basename
 - Is compatible with `repository_dependencies.xml` - thanks for the help @nsoranzo and @bgruening 
   - This allows to install a tour that automatically also downloads additional Galaxy tools, useful for explaining entire pipelines

During installation valid YAML/YML files are picked up and scanned for the presence of `steps` and `description`, and stored into the metadata of the repository. When Galaxy used to start up, it looks in its configured tool directory (`./config/plugins/tours') and will now also iterate over all tool shed repositories to check whether there are interactive tours in the metadata, and load them.

I have some additional ideas that may or may not be seen as improvements, and I would like to receive feedback on them before I start to work on them:
 - For now there are no restrictions to other files in *Interactive Tours*-type of repositories. Hence, it is possible to add XML tool wrappers. Is it desired to add limitations to this?
 - Include Interactive Tours in the tool menu?
 - Insert by default catagories into the tool shed database schema: *Tool Dependencies* and *Interactive Tours*

I hope you like the changes. All best,

Youri

### CODE REVIEW

**Comment by bgruening** [comment]
We need more of these European Galaxy Developer Workshops! Absolutely amazing @yhoogstrate!

**Comment by dannon** [comment]
@yhoogstrate Awesome, I'll check it out ASAP!

**Comment by jmchilton** [comment]
@yhoogstrate thanks for the contribution and I understand the desire to get these things incorporated in a standardized way into Galaxy quickly. This is not a -1 on my part, this is simply my dissenting opinion. I think this is a mistake for the same reason I think it is a mistake to add visualizations to the tool shed at this stage.

There is no stable interface provided by Galaxy to tours - Galaxy updates can easily break them and we have no way to determine whether a given tour is compatible with Galaxy and we can provide no guarantee that they won't break even if they do work once as Galaxy is upgraded. In the other direction, we have no concept of versioning tours as things update either right - I don't quickly see it in the added code anyway?

> For now there are no restrictions to other files in Interactive Tours-type of repositories. Hence, it is possible to add XML tool wrappers. Is it desired to add limitations to this?

I would definitely restrict the files allowed - maybe one YAML file and a repositories file for now. We wish tools were one tool per repository - we should not allow tours to have all the same problems from the get go.

> This allows to install a tour that automatically also downloads additional Galaxy tools, useful for explaining entire pipelines

The tour should annotate these things internally and not need to depend on being installed from the tool shed to be able to leverage this functionality. If I have a tour file annotated with tools workflows I should be able to install these things without requiring the tour be installed through the tool shed. This is the direction we are trying to head with tool dependencies and workflows and I think it should be how this is handled for tours from the beginning.

**Comment by bgruening** [comment]
> The tour should annotate these things internally and not need to depend on being installed from the tool shed to be able to leverage this functionality. If I have a tour file annotated with tools workflows I should be able to install these things without requiring the tour be installed through the tool shed. This is the direction we are trying to head with tool dependencies and workflows and I think it should be how this is handled for tours from the beginning.

Interesting, we discussed this briefly. To make this really neat, we would need to have a HTML ID that corresponds to the tool-id, so that a tour is opening a tool, it needs to specify the tool-id. This ID can then be used to install tools. Are `/` even allowed in HTML IDs?

**Comment by yhoogstrate** [comment]
@jmchilton Any suggestions on how I can carry this forward in a way that is compatible with how you see this in the future?

**Comment by dannon** [comment]
Sorry for the delay, I let this thread fall through the cracks a while back and only just saw the bump to it this morning.

I need to think a lot more about what an implementation would look like (security is a concern, etc), but I'd really like for tours to be accessible to users without requiring an admin (where possible, of course new tools would need admin rights to install).  Right now you *can* do things with tours that'd be unsafe, but I think that's a solvable problem, and constraining the language tours can use is probably a good thing.

Regarding particular tool and workflow dependencies, yes, this is something we need to handle with tours.  Instead of repository_dependencies.xml, I think it'd be cleaner to have a simple toplevel requirements annotation in the tour.yml itself, basically the yml version of the xml tags.

I agree with John that this is probably premature, and the point that it's going to have the same fundamental issues we have with visualizations is very appropriate.  I think I'd prefer to defer this for now.

**Pull request closed without merging**
