### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by nsoranzo**
In particular for NoseHTML 0.4.5, which will enable unit testing under Python 3.

xref. #1715

### CODE REVIEW

**Comment by nsoranzo** [comment]
I can't reproduce the unit test failures on my workstation, ideas welcome!

**Comment by mvdbeek** [comment]
Looks like pysam issues: `[E::bgzf_uncompress] Call to inflateInit2 failed: invalid parameter/compression level, or inconsistent stream state`. ~~Maybe the official pysam wheels for python3 are not compatible with what's available on travis ? https://github.com/pysam-developers/pysam/blob/master/buildwheels.sh looks like it should be portable though :/~~
Nevermind, it's the py27-unit tests ... d'oh.

**Comment by mvdbeek** [comment]
Re-ran this one and https://travis-ci.org/galaxyproject/galaxy/jobs/397055540 for the last dev commit to make sure this isn't some new travis change. Very strange.

**Comment by nsoranzo** [comment]
I've fixed it by changing lxml back to version 4.2.1 . I think this is due to https://github.com/lxml/lxml/pull/265 , the wheel for lxml 4.2.2 ships a `libz-a147dcb0.so.1.2.3` which seems to interfere with the one from pysam.

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Cool, thanks for working this all out!

**Pull request merged**
