### PR TITLE
Fix importing library datasets via the api

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by martenson** [comment]
@gregvonkuster could you please explain what is the intention of this PR? The added require `payload` param breaks the API and also this endpoint works in my testing so I do not understand what is this fixing.

**Comment by gregvonkuster** [comment]
@martenson I couldn't actually get it to work in its original form.

My post to /api/libraries/datasets with a valid payload dict returns the following:
in post
    return json.loads(urllib2.urlopen(req).read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by martenson** [comment]
@gregvonkuster  I am not sure what is a `payload` dict for you, but this endpoint is for POST request and I tested it with `form-data`, 'x-www-form-urlencoded' and  raw json - all worked for me.

How are you making the request?

**Comment by gregvonkuster** [comment]
Here's my url:
http://localhost:8763/api/libraries/datasets?key=my api key

Here's my payload:
{'file_type': 'fastqsanger', 'source': 'admin_path', 'encoded_folder_id': 'F7b162ce545dceed9', 'path': '/Users/gvk/work/library_prep_dir/60645_R1.fq'}

Here's my post function:
def post(api_key, url, data):
    """
    Do the actual POST.
    """
    url = make_url(api_key, url)
    req = urllib2.Request(url, headers={'Content-Type': 'application/json'}, data=json.dumps(data))
    return json.loads(urllib2.urlopen(req).read())

**Comment by martenson** [comment]
@gregvonkuster I can replicate that and made a fix for it at #1634
thanks!

**Comment by gregvonkuster** [comment]
Thanks @martenson !!  ;)

**Pull request closed without merging**
