### PR TITLE
Bump sqlite3 version

### PR DESCRIPTION
**Pull request by matthdsm**
Update sqlite to version 3.1.3

### CODE REVIEW

**Comment by davebx** [comment]
Suspended +1 pending test results, but I don't predict many problems from bumping the sqlite version.

**Comment by martenson** [comment]
just so it is clear: this is sqlite dependecy for the reverse proxy

**Comment by martenson** [comment]
@galaxybot test this

**Comment by matthdsm** [comment]
Yeah, we know. I bumped it up to the latest version since we had some issues with the previous version when we migrated our environment from virtualenv to a conda env.

M

Op 4 mei 2016 om 18:35 heeft Martin Cech <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

just so it is clear: this is sqlite dependecy for the reverse proxy

##

**Comment by martenson** [comment]
thanks @matthdsm

**Pull request merged**
