### PR TITLE
Updated TES Runner

### LINKED ISSUE #12074: feat : Implementing a new TES runner
I am currently working on implementing a TES runner for Galaxy. For the TES Runner, the `baseJob` runner would be inherited. There are mainly five methods that need to be implemented, which are primarily used by the galaxy to execute the tasks. They are

`__init__(app, nworkers, **kwargs)` - This method would contain the required specs and params of the TES server like host address, TES HTTP client, etc., which are defined in the job_conf.xml. Also, the other functions needed would be called, which would help monitor the status of the currently submitted job and execute the next available jobs and listen for new jobs to queue them up. 

`queue_job(job_wrapper)` - This method will create the desired job script to execute the Job in the TES. The created job script will be sent to TES with the request, which will respond with the job id, and the job can be added for monitoring.

`check_watched_item(job_state)` - This method will check the status of the job by making a request to TES with desired parameters and will update the status of the job and modify the monitoring queue accordingly.

`stop_job(job)` - This method will send a request to the TES with the job id for canceling the job. Also, it will update the status locally and remove it from further monitoring.

`recover(job, job_wrapper)` - This method will put the Job in the monitor queue.

There will be other supporting methods that need to be implemented. Some of them would be private, and some could be made public depending upon the requirements, such as creating a config file for the job and breaking the above methods into smaller fragments.

The current compatible runners can be found [here](https://github.com/galaxyproject/galaxy/tree/4f9ee14dfd28e67a93115825ed43c744b6c24f5b/lib/galaxy/jobs/runners), and also, there are two reference implementations available which can be found [here](https://github.com/snakemake/snakemake/pull/634/files) and [here](https://github.com/ohsu-comp-bio/galaxy/blob/tes-runner/lib/galaxy/jobs/runners/tes.py) which will be used as a reference for implementing the TES runner. 

Any Feedback and Suggestion would be highly appreciated.

### PR DESCRIPTION
**Pull request by vipulchhabra99**
Fixes #12074. PR for adding TES Runner with required files for execution of tasks. It's the updated version of #12102

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Setup a TES Instance (Funnel, TESK, etc.).
  2. Follow the instructions in the video to set up the TES Runner - https://iiitaphyd-my.sharepoint.com/personal/vipul_chhabra_research_iiit_ac_in/_layouts/15/stream.aspx?id=%2Fpersonal%2Fvipul%5Fchhabra%5Fresearch%5Fiiit%5Fac%5Fin%2FDocuments%2Fdemo%2D2021%2D08%2D23%5F21%2E53%2E26%2Emkv&ga=1
  3. After adding required specifications in the `job_conf.xml` file, run the Galaxy Instance
  4. Try executing the tools and workflows in the Galaxy  

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
This is thoroughly phenomenal work - and I was assuming I was reading work from a full time engineer working on some related project not a GSoC project. I'm not ready to merge it as is but it will definitely make it into Galaxy in some form and I'm working through that. This is a template for how to do that and I think it goes above and beyond - you've pieced together disparate and complex systems very well and made it very clear what abstractions we need to make this flow a bit nicer.

**Comment by vipulchhabra99** [comment]
> This is thoroughly phenomenal work - and I was assuming I was reading work from a full time engineer working on some related project not a GSoC project. I'm not ready to merge it as is but it will definitely make it into Galaxy in some form and I'm working through that. This is a template for how to do that and I think it goes above and beyond - you've pieced together disparate and complex systems very well and made it very clear what abstractions we need to make this flow a bit nicer.

Thank you for reviewing it @jmchilton, I understand that there are things like linting and integration tests pending, out of which I have already worked on some things but haven't pushed. Apart from it, if you still feel there are changes required or I can contribute in any way, I would be happy to do that :)

**Comment by uniqueg** [comment]
Thanks a lot @jmchilton! I was involved with mentoring @vipulchhabra99 during GSoC last year and I can only agree with you, @vipulchhabra99 did an amazing job. From ELIXIR, we would also be hugely interested in Galaxy having a TES backend, so that we could use Galaxy's workflow engine with a range of different compute backends using that setup. (Similarly, we would love to implement TES server-side in Pulsar, and WES server-side in Galaxy, but those are different stories).

Please let us know if there is anything we can help you to get this merged any sooner.
Also tagging @kellrott here.

**Comment by kellrott** [comment]
I also wanted to emphasize that @vipulchhabra99's original GSoC project was for 2021, he's kept on this project and refactored the code to fit requests long after his original work was completed.

**Comment by mvdbeek** [comment]
Thanks a lot for your work @vipulchhabra99, with https://github.com/galaxyproject/galaxy/pull/14777 and https://github.com/galaxyproject/pulsar/pull/302 merged I think we can close this.

**Pull request closed without merging**
