### PR TITLE
[15.10] Fix workflow extraction from history

### PR DESCRIPTION
**Pull request by guerler**
See: #928

### CODE REVIEW

**Comment by martenson** [comment]
I feel this usecase would benefit a lot from a testcase.
+1

**Comment by guerler** [comment]
./run_tests.sh -api test/api/test_jobs.py:JobsApiTestCase.test_search does run this failed test locally, right?

**Comment by martenson** [comment]
I do not understand the question. 

As I see it this was broken and the `-api` tests on jenkins were routinely passing (https://jenkins.galaxyproject.org/job/docker-api/) so it is probably not covered by the tests.

The test that failed for this PR (`test_search`) is sometimes failing because of timeout - which I believe is also this case.

**Comment by guerler** [comment]
I was wondering if I ran the test properly because it passed locally.

**Comment by martenson** [comment]
the `test_search` is an unreliable test and I wouldn't worry about it not passing

**Comment by guerler** [comment]
Ok, Thx.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
:+1:

**Pull request merged**
