### PR TITLE
replace the png logo with svg version

### LINKED ISSUE #15241: Galaxy masthead logo became significantly smaller and distorted
the right part of the yellow stripe is also cut off

Galaxy___martenson_and_Galaxy

left usegalaxy.org right dev

### PR DESCRIPTION
**Pull request by martenson**
Goes down from 16kb to 9kb and preserves all details. Thanks to @guerler for teaching me with inkscape 🫣

closes https://github.com/galaxyproject/galaxy/issues/15241

BEFORE 

Galaxy___martenson_and_Galaxy

~~AFTER~~

Galaxy___martenson

AFTER AFTER
Galaxy___martenson_and_Signal__1_

Maybe it is a tad too big? Try it out before you judge, it grew on me when I saw it with the whole site.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
It also feel a bit too big for my taste.

**Comment by guerler** [comment]
Thanks for adding the padding, looks great to me!

**Review by guerler — APPROVED** [review]
Looks good to me. Thank you for having pointed this out. The logo looks much better, is sharper and the logo file is smaller too.

**Comment by martenson** [comment]
just rebased to clean up commits

**Comment by martenson** [comment]
thanks @guerler !!

**Comment by guerler** [comment]
Thank you!

**Pull request merged**
