### PR TITLE
Fixes #2230

### LINKED ISSUE #2230: Poorly escaped input value in run workflow form shows html snippet.
utvalg_726

So...that's neat. On d7353d381987df3c1b2364fd74ded5134d1415fc. Not tested on dev yet, sorry.

So that happens because of this HTML snippet:

``` html
<input type="hidden" name="13442|tool_state" value="{"input": "{\"__class__\": \"RuntimeValue\"}", "__rerun_remap_job_id__": null, "header_lines": "\"0\"", "cond": "\"100 * c4 / c23 > 50\"", "__page__": 0}">
```

It's the filter tool and the filter I used was `100 * c4 / c23 > 50`. The escaping job on `value` is somewhat suboptimal.

### PR DESCRIPTION
**Pull request by hexylena**
This sanitizes some instances where tool parameters were included directly into the DOM.

`workflow/run.mako` displayed the parameter as a value in a hidden input. This was base64 encoded as there was no better solution apparent at the time. I'm not sure where this parameter is POSTed to but we should figure that out and b64decode it, or remove the hidden parameter. I logged every use of "tool_state" I could find in lib/ that looked plausible but I couldn't see any uses of it during normal workflow calling.

`client/...` added the parameter value into the DOM. This was easily sanitized using a standard method.

`workflow/display.mako` included the parameter value directly into the HTML. This was cgi.esacped

This needs to be backported I believe, I have not tested it yet. Thanks @guerler for being online :)

CC @natefoo @dannon

### CODE REVIEW

**Comment by guerler** [comment]
Thanks @erasche

**Comment by hexylena** [comment]
@natefoo did we ever end up backporting this? You mentioned you were working on it in IRC

**Comment by martenson** [comment]
@erasche this is not in 16.04 yet; @natefoo has more pressing agenda now (jetstream), is there anything difficult here or can I just backport it?

**Comment by hexylena** [comment]
TIL Jetstream > XSS. @martenson this is a stored XSS which applies to **every** version of Galaxy. It should be easy enough to backport, please do so!

**Pull request merged**
