### PR TITLE
Added Illumina methylation datatype (IDAT) to binary.py

### PR DESCRIPTION
**Pull request by nturaga**
Tools to support this datatype will come in soon. Can be a WIP till then if needed.

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton - I could not find a EDAM number for it, what is the official procedure to propose one? A simple github issue to https://github.com/edamontology/edamontology?

**Comment by jmchilton** [comment]
:+1: as is. @bgruening - I believe @fmareuil and @odoppelt are maintaining a list of these datatypes (so I am pinging them) and they will decide which ones to try to get added to EDAM. For now - this datatype will inherit the generic code for binary data from its superclass.

**Comment by bgruening** [comment]
Ok, I'm :+1: as well!

**Comment by nturaga** [comment]
@bgruening I wasn't aware of edamontology till I saw your comment. Does every datatype need to have a an EDAM ontology number?

**Comment by bgruening** [comment]
@nitesh1989 if there is one yes. This is our aim at least :)

**Comment by odoppelt** [comment]
It is also our aim ;)

## We'll add that datatype to the Edam new format' spreadsheet. 

Olivia Doppelt-Azeroual, PhD 
CIB - C3BI - Institut Pasteur, Paris

**Comment by bgruening** [comment]
@odoppelt do you have a preferred way to "submit" missing data types?

**Comment by nturaga** [comment]
Thanks @odoppelt and @bgruening

**Comment by odoppelt** [comment]
I need to discuss this with the Edam people and let you know what they prefer. 

## 

Olivia Doppelt-Azeroual, PhD

**Pull request merged**
