### PR TITLE
Allow users to create new activity bar items

### PR DESCRIPTION
**Pull request by guerler**
Requires: #16184. Provides a framework to allow users to drag items from the UI into the activity bar component. Demonstrated here for datasets and workflows. The context menu has been augmented, now allowing to search activities.

https://github.com/galaxyproject/galaxy/assets/2105447/2c7be541-aa1a-4c02-ba70-cbf554ddb309

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
I've got 2 Workflow activities now, Workflow and Workflows:

Screenshot 2023-06-09 at 17 46 31

**Review by mvdbeek — APPROVED** [review]
This is amazing ... it's so good I'm a little sad we're not making that the default yet 😆

**Comment by bgruening** [comment]
Hüstle... Let's make it default ;-)

**Comment by guerler** [comment]
Thanks for all the comments and help. I really appreciate it! I think we should refine the list of activities first and then discuss switching this feature on by default.

**Pull request merged**
