### PR TITLE
[18.01] Webhooks improvements

### PR DESCRIPTION
**Pull request by dannon**
This deconflicts and catches #5164 up to be mergeable with dev.  I checked with @anatskiy who OK'd the rebase.

See #5164 for more details, also copied below.

-----

This PR improves and simplifies the overall Webhooks' structure.

1. All the webhook's files now are located in one folder (no more `config`, `helper` and `static` subfolders).
2. Function `Webhooks.load()` is unified even more for all endpoints (e.g., `onload`, `masthead`, `tool`, etc.). 
3. Webhooks have a weight now (like it was explained [here](https://github.com/galaxyproject/galaxy/pull/5047#issuecomment-346066590)).
4. Some of the logic has been moved to the client (like it was suggested [here](https://github.com/galaxyproject/galaxy/pull/5047#issuecomment-345807872)).

If you agree to the changes, I'll update the documentation accordingly.

P.S. Every single webhook is broken now. I've updated all the demo webhooks in this PR, but others won't work.

### CODE REVIEW

**Comment by dannon** [comment]
Fixing linting issues now that the tests are running.  Also looks like potentially legit qunit failures; will check them out in the morning

**Comment by dannon** [comment]
After the last few commits, QUnit tests pass for me locally now.  Letting test suites run and then I'll revisit the TDT tests.

(edit the last: Good to go now)

**Comment by martenson** [comment]
>P.S. Every single webhook is broken now. 

@anatskiy I am willing to merge this so it makes it to 18.01 but I would like to see documentation for the new and also for the transition from the old, so people can update their webhooks more easily.

With any feature that is a bit more mature I would argument for at least one deprecation release -
 webhooks are on the borderline for me.

**Comment by martenson** [comment]
We have branched the 18.01, if this wants to make it there, it needs to re-target to that branch (and be merged soon).

**Comment by dannon** [comment]
@martenson I had it targeted and milestoned; per the rules it probably should have been bumped or merged prior to the branch.  Not a big deal though, retargeted.

**Comment by martenson** [comment]
I think we delayed Evgeny's PR enough so I am willing to break the rule here. It would be cool to have webhooks mature for the GCC18 and this PR goes in this direction but if the branching rules are above both of these for you, please raise your voice @dannon

**Comment by dannon** [comment]
@martenson I think you misinterpreted my words, but no worries.  As I said above, I retargeted this (to the 18.01 branch) and would definitely like for someone to merge it.  Preferably not me, since half of these commits are mine at this point.

**Comment by anatskiy** [comment]
@dannon thanks a lot for the revision! Everything webhooks-related seems to work well. The search plugin is broken, though. I'll fix it soon.

@martenson hm, what do you mean by _mature_ here?

I'll update the documentation regarding the simplified plugin structure.

**Comment by dannon** [comment]
@anatskiy Sure, anytime!

**Comment by martenson** [comment]
@anatskiy I mostly mean 'stable'/'not getting breaking changes in future'.

**Comment by anatskiy** [comment]
@martenson oh, I see. Right, it won't change that much anymore.

**Comment by anatskiy** [comment]
@dannon I pushed a fix https://github.com/dannon/galaxy/pull/25

**Comment by martenson** [comment]
Thanks @anatskiy ! Could you please write a paragraph or so of docs for folks that have custom webhooks in old format what they need to go through? We will include it in the release notes. Thanks.

**Comment by anatskiy** [comment]
@martenson oh, I totally forgot about it. I'll do it!

**Comment by martenson** [comment]
@anatskiy awesome, once you have it please xref it to https://github.com/galaxyproject/galaxy/issues/4920

**Comment by anatskiy** [comment]
@martenson here are a few words on the migration to the new Webhooks format. 

---

To make old Webhooks work with the recent changes, you need to do the following:
- rename the main config file: `<name>.yml` -> `config.yml`
- in the config file, rename the name attribute: `name` -> `id`
- put all files into the plugin's root folder, which should contain only four files: `config.yml` (mandatory), `__init__.py` (optional), `script.js` (optional), `styles.css` (optional)

xref #4920

**Pull request merged**
