### PR TITLE
Improve Embed Performance

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Improves the start-up time of embeds, and reduces the load on the server by skipping additional initializations when in embed mode.

Most notably the current history update interval, and notification update interval are not started.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Nice, thank you!

**Comment by mvdbeek** [comment]
Should we apply that to 23.2 ?

**Comment by ElectronicBlueberry** [comment]
> Should we apply that to 23.2 ?

Probably yes. I'll open a back-port PR

**Comment by bgruening** [comment]
I think this one can be closed now. The changes are in 23.2 (https://github.com/galaxyproject/galaxy/pull/17326) and will be merged forward.

**Pull request closed without merging**
