### PR TITLE
Fixes for errors reported by mypy 1.11.0

### PR DESCRIPTION
**Pull request by nsoranzo**
## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
@jmchilton How would you like the errors in `lib/galaxy/objectstore/__init__.py` to be fixed? See https://github.com/galaxyproject/galaxy/actions/runs/10133978191/job/28019706741

**Comment by jmchilton** [comment]
I would say we should just replace the very generic signatures with the specific ones and pray nothing breaks. Might hit some bugs in the mean time but long term that sounds better. I need to finish the dataset uuid stuff but if this is still red tomorrow - I could try to work through it.

**Comment by nsoranzo** [comment]
Thanks @jmchilton , I followed your suggestion but please double check!
Any help appreciated, there are still more than 70 mypy errors to fix.

**Comment by nsoranzo** [comment]
@jmchilton Only 17 mypy issues left, and all other tests (except the unrelated integration test failures) are green.
Do you have time to fix the remaining ones? I need to finish other stuff before my holidays start, and these look a bit tricky for me.

**Comment by jmchilton** [comment]
I think the fixes are higher priority than the mypy upgrade itself. Can I recommend we strip out the mypy upgrade and just PR the fixes so they don't stale. I'd be willing to take that task on while you're away - I am not ready to commit to finishing the upgrade though.

**Comment by nsoranzo** [comment]
> Can I recommend we strip out the mypy upgrade and just PR the fixes so they don't stale.

Sounds good, this part should be ready for review/merge.

**Comment by jmchilton** [comment]
Wow - that is a lot of scary changes. I think we have really good test coverage for the object store stuff and that is what I'm most worried about. We also have good test coverage of the toolbox and manager things I think. I'm most worried about the data provider stuff but I walked through closely and I think it should be all fine and I'm not certain any of it is used at this point anyway.

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
Integration test failures unrelated.

**Pull request merged**
