### PR TITLE
[16.10] Swap the client's ui-misc.Message to escape by default.

### PR DESCRIPTION
**Pull request by dannon**
More commits in https://github.com/dannon/galaxy/tree/client_ui_message_escaping that'll be opened against -dev.

### CODE REVIEW

**Comment by dannon** [comment]
Argh, the cherrypick/rebuild didn't work as I expected it to, one sec.  (scratch that, it did work, was just mistargeted -- all good now)

**Comment by martenson** [comment]
👍

**Review by martenson — APPROVED** [review]

**Comment by jmchilton** [comment]
This seems to break that functionality we talked about earlier of showing tool requirements.

**Comment by dannon** [comment]
@jmchilton I'll check it out; I can pull in the rest of the commits from that other branch and allow that behavior via UnescapedMessage if need be.

**Comment by dannon** [comment]
Hrmm, yeah.  I asked before doing it this way, but sure enough there are other implications here.  Let me pull the rest of the changes over to this branch and migrate the various consumers.

**Pull request merged**
