### PR TITLE
Minor workflow editor fixes

### PR DESCRIPTION
**Pull request by mvdbeek**
- Fix (random-ish) position for new step inserts to be close to the center of the screen
- Display a message in connections menu when no valid connection can be made
- Drop (hopefully?) unused jQuery scroll-panel plugin
- Fix handling of node and connector coordinates if background is scrolled (e.g by using the tab key to jump to elements that were not visible)
- Selenium tests and usability fixes for connections menu
- Fix inserting workflow steps from existing workflow and selenium test for that
- Destroy select2 instance on unmounting form parameter

TODO: 
- [ ] state stays in browser after unloading the editor, after which it'd ask you on some future navigation if you wanted to save your changes 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by guerler** [comment]
Can we make an addition to reduce the frequency of the loading spinner in the steps, currently it appears frequently e.g. when changing any form value etc?

**Comment by mvdbeek** [comment]
> step box instead of the header

That's what I had before, the jump is very jarring ... but it is also quite silly that the form emits on created even if no parameter has changed, I think that's the real thing to change.

**Comment by mvdbeek** [comment]
> * state stays in browser after unloading the editor, after which it'd ask you on some future navigation if you wanted to save your changes

I had seen this before too, but I can't reproduce it now, if anyone runs into it again and knows the sequence to trigger it that'd be great.

**Comment by guerler** [comment]
That's a good point, it's probably because the form itself gets actually `created`. We probably do not keep the forms in cache to save space. Maybe we can try to only replace the step icon with the `spinner` when refreshing, without the loading label to avoid flickering.

**Comment by mvdbeek** [comment]
I don't know that we even need to cache anything. If the config_form is present on create (it is created fresh when you load the workflow in the editor), don't fire on create, only refresh when the user changes a value.

**Comment by dannon** [comment]
This looks great, and can follow up on the loading indicator refinements down the road, thanks @mvdbeek and @guerler

**Pull request merged**
