### PR TITLE
removed extract genomic DNA

### PR DESCRIPTION
**Pull request by bernt-matthias**
Since the tool seems not work with reference data created by the twobit data_manager anyway I suggest to remove it in favor of https://github.com/galaxyproject/tools-iuc/tree/master/tools/extract_genomic_dna. 

See also https://github.com/galaxyproject/galaxy/issues/4320 and https://github.com/galaxyproject/galaxy/issues/636. 

Sorry for the mess with git.

### CODE REVIEW

**Comment by nsoranzo** [comment]
If we want a proper tool migration, this would need corresponding files in `scripts/migrate_tools/` and `lib/tool_shed/galaxy_install/migrate/versions/` and a ToolShed repository with the current 2.2.3 version (probably under devteam, since the iuc one started at 3.0.0).
Or is the tool so broken that we don't need to ensure reproducibility?

**Comment by bernt-matthias** [comment]
seemed broken to me. the tool was not able to use reference data created by the twobit data manager

**Comment by jennaj** [comment]
@bernt-matthias yes, the tool has a problem with DM created indexes. Needs a fix: https://github.com/galaxyproject/galaxy/issues/5493

I tried to link all of these together so we can get the fix done, then all the updates to the appropriate places (MTS, public servers, galaxy release).

ping @davebx any status or other comments? @blankenberg thought this tool needed more changes.

**Comment by bgruening** [comment]
@bernt-matthias @jennaj this tool is filtering the reference list according to the DB key. So please add a DB key to your input file and it will work, it does so on our instance last time I checked.

**Comment by jennaj** [comment]
@bgruening sorry for cross-posting this all over the place! but assigning a dbkey does not help. The incorrect data table is being accessed (or was in the prior version). I just reran it in the same test history again. Details: https://github.com/galaxyproject/galaxy/issues/5493

I can test at https://galaxy.uni-freiburg.de and see if can reproduce. This is tricky since the data is not configured at Main the same as it is other places (not all data is DM, some is from earlier). But let's see what happens. Feedback soon.

**Comment by jennaj** [comment]
@bgruening Ok, tested and version 3.0.3 works and the earlier version there 3.0.2 does not (gives same error as 2.2.3.

Looks like an update to 3.0.3 (everywhere) might resolve the problem for main, but that is difficult to test given how indexes at different servers are set up. On main, danRer10 fails, at freiburg mm10 does (earlies tool versions). Both work with 3.0.3

Test history: https://galaxy.uni-freiburg.de/u/jenj/h/test-history-extract-genomic-dna

**Comment by jennaj** [comment]
Just reran the mm10 test using the older tool version and it went through. The paired tests are data 6 and 7 - identical except for the timing. In the history I shared for freiburg. Maybe a transient problem or something changed.

So now just need main updated and we might be good!

**Comment by bgruening** [comment]
@jennaj we will soon use all the same reference datasets on all usegalaxy.* servers. One problem less to worry.

**Comment by bernt-matthias** [comment]
as far as I remember the tool checked for reference data only in the ones refered in the files in tool-data/. Seemed hard coded to me (GALAXY_DATA_INDEX_DIR)? So if there are multiple loc files it won't work. And in particular it seemed not to work with data manager created loc files because they are at a different location.

**Comment by jennaj** [comment]
@bernt-matthias Correct, the twobit loc content needs to be linked in and the tool modified to use the final merged data table. That is what the ticket @blankenberg and I created is about. :) Should solve the root problem.

@bgruening Agree, a common built-in data source will simplify so many testing/troubleshooting issues!

**Comment by jmchilton** [comment]
How about this - can we just remove this tool from the sample conf? People who have it and want to keep it can wait for the migration - new Galaxy admins won't be confused by a tool that no longer works with how contemporary data management occurs in Galaxy. If they want the tool they can find a shiny new version in the tool shed.

**Comment by jmchilton** [comment]
Closing in lieu of https://github.com/galaxyproject/galaxy/pull/5618 since @bernt-matthias gave my comment a 👍. Feel free to re-open if I am misinterpreting that.

**Comment by bernt-matthias** [comment]
I guess you meant https://github.com/galaxyproject/galaxy/pull/5741 .. but completely fine from my side. Thanks

**Comment by jennaj** [comment]
Linking to the ticket for Main to be updated (&& remove old non-functional version): https://github.com/galaxyproject/galaxy/issues/5493

**Pull request closed without merging**
