### PR TITLE
[20.05] Various small fixes for galaxy packages. 

### PR DESCRIPTION
**Pull request by jmchilton**
See individual commits for details.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Wouldn't it be simpler to move `test/unit/test_containers.py` to `test/unit/containers/test_containers.py` ? With the symlink these tests are run twice by pytest.

**Comment by jmchilton** [comment]
Opps - looks like I duplicated the test. I meant to create a directory called containers and just symlink that so we don't have to manage individual files. Ideally each package could correspond to one or a couple unit test directories (i.e. https://github.com/galaxyproject/galaxy/blob/dev/packages/data/tests/datatypes) and the unit tests wouldn't have to be managed file by file. I clearly messed up this commit though.

**Comment by jmchilton** [comment]
Sorry about that confusion - does this look any better?

**Review by nsoranzo — APPROVED** [review]

**Comment by bgruening** [comment]
How do we trigger uploads to pypi? https://pypi.org/project/galaxy-objectstore

**Comment by nsoranzo** [comment]
It's still a manual process AFAIK.

**Pull request merged**
