### PR TITLE
flake8 fixes for the tabular datatypes

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by martenson** [comment]
@bgruening I think this is not the right time to correct whitespace as there is PR in progress that will change this file considerably: https://github.com/galaxyproject/galaxy/pull/191

**Comment by jmchilton** [comment]
I have merged conflicts that has been introduced with https://github.com/bgruening/galaxy/pull/1.

**Comment by bgruening** [comment]
Thanks John. Totally forgot about this PR. I was planning to work on improving the VCF datatype, related to the VCF iobio visualisation and started with the cleanup.

**Comment by martenson** [comment]
:+1:

**Pull request merged**
