### PR TITLE
Infrastructure for dynamic compressed datatypes

### PR DESCRIPTION
**Pull request by jmchilton**
Just annotate ``auto_compressed_types="gz|bz2|gz,bz2"`` in datatypes_conf.xml and get for free:

- The compressed datatype with correct extension, no need to have a class definition.
- Converters from the compressed datatype to the uncompressed datatype.
- A sniffer in the correct order.

Additionally, the hacky way we were controlling whether types would be sniffed or not has been improved. This can now be set in the datatypes_conf.xml file or read from a global Galaxy configuration option for options that haven't been explicitly set on a per-datatype basis in the configuration (``sniff_compressed_dynamic_datatypes_default``). (Need to document this still.)

This should make PRs like #5553  and #5772 as simple as modifying one line of XML. It also introduces the possibility of just loading such datatypes dynamically as needed based on what the tools in the tool panel annotate for inputs and outputs. See a tool with an input of type "genbank.gz" should be enough to trigger this someday I hope.

Builds on memory bound sniffing introduced in #5793.

### CODE REVIEW

**Comment by mvdbeek** [comment]
That's awesome! Could we enable this for all non-binary datatypes, or would that be too ambitious ?

**Comment by jmchilton** [comment]
@mvdbeek I really don't know. The pros are sort of obvious - we don't need to make decisions about what is useful, if something turns out to be useful it will just be there - this gives both tool authors and end users more powerful options for data management in Galaxy.

The cons are a bit more subtle:
- Slower toolbox loading (meh - this is fine with me)
- More upload formats in the list can be confusing (we can add a flags to only show certain ones but load them all ``display_compressed_formats="gz"``, this might be a good compromise between giving tools a lot of freedom but simplifying the user interface for now until these issues are more cleanly solved)
- If we opt to change the representation later (e.g. a flag on the dataset instead of using the datatype extensions), limiting the uses of this technique makes things marginally easier.
- No need to update Galaxy just to get a new set of compressed files.

**Comment by natefoo** [comment]
> Slower toolbox loading (meh - this is fine with me)

pls no :sob:

**Comment by jmchilton** [comment]
> pls no 😭

That was a brain fart, I think I meant datatype registry reloading and it is all in memory. Reloading datatypes would still be much, much faster than the toolbox I believe.

**Comment by natefoo** [comment]
Phew.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Rebased with fix for failing integration test.

**Comment by martenson** [comment]
last commit eliminates the following startup errors:
```
galaxy.datatypes.registry ERROR 2018-04-19 14:15:47,341 [p:30375,w:0,m:0] [MainThread] Error calling method FastqSangerGz from class <module 'galaxy.datatypes.sequence' from 'lib/galaxy/datatypes/sequence.pyc'>
Traceback (most recent call last):
  File "lib/galaxy/datatypes/registry.py", line 478, in load_datatype_sniffers
    aclass = getattr(module, datatype_class_name)()
AttributeError: 'module' object has no attribute 'FastqSangerGz'
galaxy.datatypes.registry ERROR 2018-04-19 14:15:47,341 [p:30375,w:0,m:0] [MainThread] Error calling method FastqSangerBz2 from class <module 'galaxy.datatypes.sequence' from 'lib/galaxy/datatypes/sequence.pyc'>
Traceback (most recent call last):
  File "lib/galaxy/datatypes/registry.py", line 478, in load_datatype_sniffers
    aclass = getattr(module, datatype_class_name)()
AttributeError: 'module' object has no attribute 'FastqSangerBz2'
galaxy.datatypes.registry DEBUG 2018-04-19 14:15:47,342 [p:30375,w:0,m:0] [MainThread] Loaded sniffer for datatype 'galaxy.datatypes.sequence:Fastq'
galaxy.datatypes.registry ERROR 2018-04-19 14:15:47,342 [p:30375,w:0,m:0] [MainThread] Error calling method FastqGz from class <module 'galaxy.datatypes.sequence' from 'lib/galaxy/datatypes/sequence.pyc'>
Traceback (most recent call last):
  File "lib/galaxy/datatypes/registry.py", line 478, in load_datatype_sniffers
    aclass = getattr(module, datatype_class_name)()
AttributeError: 'module' object has no attribute 'FastqGz'
galaxy.datatypes.registry ERROR 2018-04-19 14:15:47,342 [p:30375,w:0,m:0] [MainThread] Error calling method FastqBz2 from class <module 'galaxy.datatypes.sequence' from 'lib/galaxy/datatypes/sequence.pyc'>
Traceback (most recent call last):
  File "lib/galaxy/datatypes/registry.py", line 478, in load_datatype_sniffers
    aclass = getattr(module, datatype_class_name)()
AttributeError: 'module' object has no attribute 'FastqBz2'
```

**Comment by jmchilton** [comment]
Thanks for the fix @martenson !

**Comment by martenson** [comment]
This looks pretty solid and I like the abstraction and possibilities it brings. I had some weird behaviors while testing but I think this PR is not the culprit (or making it worse). Thanks @jmchilton

**Pull request merged**
