### PR TITLE
Removes Sample request and External services makos/controllers

### PR DESCRIPTION
**Pull request by guerler**
This PR is branched from #4480 and contains sections from #4493. It removes the controller endpoints and associated makos for sample requests and external services. These are features being deprecated in 17.09. Additionally it reorganizes the left admin panel by reducing it to three categories: Server, User Management and Tools/Toolshed.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
Works fine / looks good to me. Only comment is with the newer, shorter menu I see a white section at the bottom.

auswahl_066

It looks like this can be fixed with 

```
diff --git a/client/galaxy/style/less/base.less b/client/galaxy/style/less/base.less
index fb998e414c..49768ad355 100644
--- a/client/galaxy/style/less/base.less
+++ b/client/galaxy/style/less/base.less
@@ -134,6 +134,7 @@ body  {
     width: 250px;
     z-index: 200;
     border-right: solid @layout-border-color 1px;
+    background: @panel-bg-color;
 }
 #left-border  {
     left: 250px;
```

**Comment by martenson** [comment]
@erasche that is unrelated to this PR I think, I saw it before.

**Comment by hexylena** [comment]
:+1: from me (but not merging due to requested review from @martenson)

**Comment by martenson** [comment]
We need to have another discussion about this I think. There were comments about how/if to proceed with the controllers removal or whether to just bind them to the tracking configuration.

**Comment by guerler** [comment]
ping @martenson. Can we discuss this? It would be nice if we could move forward. It could allow us to complete the mako-to-js transition within this year. Also no one responded to the email we sent out a couple weeks ago.

**Comment by martenson** [comment]
@guerler yep, let's talk monday

**Comment by martenson** [comment]
I disabled both samples.py and requests.py API controllers unless new config option is set to True (False by default)

`#enable_legacy_sample_tracking_api = False`

I think this is now ready for merging and I will do so later today, unless there are objections.

**Review by martenson — APPROVED** [review]

**Comment by guerler** [comment]
We got some new failing tests.

**Comment by martenson** [comment]
The api tests were already failing for https://jenkins.galaxyproject.org/job/docker-api/9020/ which is an unrelated PR 🤔

**Comment by martenson** [comment]
switching to WIP, found few things that need to be included

**Comment by martenson** [comment]
seems the problems were caused by bad merges, @guerler is on it

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by martenson** [comment]
Thanks for your work @guerler!

**Comment by guerler** [comment]
Thanks a lot for the help and review @martenson.

**Pull request merged**
