### PR TITLE
Resolve conflicting label CSS class for trackster.

### PR DESCRIPTION
**Pull request by jgoecks**

### CODE REVIEW

**Comment by guerler** [comment]
That was quick. (: We should also fix Sweepster and apply it to 15.10. See: #1089.

**Comment by martenson** [comment]
15.10 should not have the change from James, I agree with Sweepster though

**Comment by guerler** [comment]
Yeah you are right.

**Comment by guerler** [comment]
It seems that we have an issue packing styles i.e. running 'grunt style'. In dev it currently breaks 'green'.

**Pull request merged**
