### PR TITLE
Remove Trackster, Circster, Sweepster and Phyloviz Makos

### PR DESCRIPTION
**Pull request by guerler**
This PR removes the legacy mako, js-code of Trackster, Circster, Sweepster and Phyloviz built-in visualizations. This is a critical prerequisite for moving forward with the overall client modernization in regard to backbone-based code and legacy makos.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
I think Trackster, Circster, Sweepster have been discussed many times in various GCCs to be removed. Thanks @guerler for taking the lead here. :+1: 
I'm not sure about Phyloviz. Do we know if this is used? Do we have a replacement?

@nekrut I remember you have at least participated in those discussions and have been in favor of removing Trackster in favor of other Genome Browsers.

**Comment by mvdbeek** [comment]
I also like this a lot, but maybe the order should be addition of embedded IGV (or jbrowse) first before we remove trackster ?

**Comment by nekrut** [comment]
100% REMOVE!

**Comment by guerler** [comment]
Closed in favor of #17415

**Pull request closed without merging**
