### PR TITLE
[15.05] Change view_multiple histories to lazy load history size

### PR DESCRIPTION
**Pull request by ericenns**
As this is the most computationally expensive part

### CODE REVIEW

**Comment by Takadonet** [comment]
Without theses changes.... took 26 minutes and 8.5 G of ram to load up the history panel.... Yes I have lots of very large histories. (i.e over 800 datasets in over a few dozen)

**Comment by carlfeberhard** [comment]
This seems like a too-heavy approach changing the view entirely and I'd already planned to tackle this in a different way by reducing the number of histories loaded initially.

**Comment by ericenns** [comment]
I've updated it to now to longer change the summary view for histories. Instead I just request the additional key (user_id).

**Comment by ericenns** [comment]
Just to note, I only need user_id so that the buttons for tags and annotations appear.

**Comment by carlfeberhard** [comment]
No sorry - what I meant was that you're using an entirely different view for the json loaded into the histories:
https://github.com/galaxyproject/galaxy/pull/498/files#diff-885dec55cc50562fa45a4385ea874679R646

I'd really rather take this is in a different direction - EDIT: which will take some time. The multi-history view really should be considered a work-in-progress and why the 'Saved Histories' view is still around.

**Comment by ericenns** [comment]
'Saved Histories' is also affected by the same issue, i.e. wont load with @Takadonet histories.

**Comment by Takadonet** [comment]
Finally got 'Saved Histories' to load and took 34 minutes. No idea why since all larger histories are gone. My only assumption would be that delete permanently histories are still process on the server side but not shown unless prompted by the user. Thinking of making a new local user and abandon my old one.

**Comment by carlfeberhard** [comment]
Then the underlying issue is performance and scaling of the method used for calculating the history size and I'd rather address that.

**Comment by carlfeberhard** [comment]
@Takadonet what's your approximate history count, your overall approximate number of datasets, and the average number of datasets per history?

**Comment by Takadonet** [comment]
Cannot access my galaxy at the moment but will be in tomorrow. My estimate is that I have over 400 histories, with at least a few thousands datasets. The last 30 or so histories, have over 800 datasets in each.....

My current workaround is simply to make a new user. Since every time i hit the 'saved histories' link, it locks a web worker for 70 minutes with 8 G of ram.

**Comment by jmchilton** [comment]
I guess I will close this since there doesn't seem to be momentum, feel free to reopen and re-argue.

**Pull request closed without merging**
