### PR TITLE
[18.05] Fix toolshed nav for BS4

### LINKED ISSUE #5961: toolshed does not have menu
latest dev deployed on https://testtoolshed.g2.bx.psu.edu/
screenshot 2018-04-23 14 18 58

### PR DESCRIPTION
**Pull request by dannon**
This should fix #5961

### CODE REVIEW

**Comment by martenson** [comment]
Thank you for the fix and sorry that this needs to re-target 18.05.

**Comment by dannon** [comment]
@martenson No big deal on retargeting -- done; I wanted to keep this open for a bit as WIP and test a few more things, anyways.

**Comment by martenson** [comment]
@dannon the menu seems to show up fine with this PR, I have found other bugs though and documented them here: https://github.com/galaxyproject/galaxy/issues/5985

**Comment by dannon** [comment]
@martenson Thanks for taking a look.  Yeah, the menu misalignment you noted there is related, and is something I'm going to fix in this PR.

**Comment by martenson** [comment]
@dannon is this still wip? If so can we please merge it and continue elsewhere?

**Review by martenson — APPROVED** [review]

**Pull request merged**
