### PR TITLE
Viz plugin loading fixes

### LINKED ISSUE #5067: Charts Broken on dev
Charts seems broken on dev to me - I also can get the rebuild to work.

Web Console:

```
Uncaught TypeError: Utils.get is not a function
    at app.js:12
    at Object.execCb (require.js?v=1511537801:1)
    at b.check (require.js?v=1511537801:1)
    at b.<anonymous> (require.js?v=1511537801:1)
    at require.js?v=1511537801:1
    at require.js?v=1511537801:1
    at each (require.js?v=1511537801:1)
    at b.emit (require.js?v=1511537801:1)
    at b.check (require.js?v=1511537801:1)
```

Build:

```
yarn run build-charts
yarn run v1.1.0
$ webpack -p --config ../config/plugins/visualizations/charts/webpack.config.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/john/workspace/galaxy-clean/config/plugins/visualizations/charts/webpack.config.js:3:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

### PR DESCRIPTION
**Pull request by dannon**
Fixes charts and scatterplot.

Refactors imports and exports used by external-to-client consumers to allow direct access (without generally requiring Blah.default access).  Includes cleanup and minor fixes, removing some unused imports in various modules, etc.

Overhauls scatterplot to be a bundled plugin, using webpack instead of grunt/concat/etc.

@guerler It'd be worth perusing the bundling changes here with #4256 in mind.  We could simplify the Galaxy/Viz interface and continue to plug bundles in pretty easily, I think (without mako!)

Fixes #5067

### CODE REVIEW

**Comment by dannon** [comment]
Rebased and rebuilt.

**Comment by dannon** [comment]
Rebased and rebuilt again.

**Comment by dannon** [comment]
Rebased and rebuilt again.

**Comment by bgruening** [comment]
@dannon thanks! :)

**Pull request merged**
