### PR TITLE
Prettier javascript formatting.

### PR DESCRIPTION
**Pull request by dannon**
Prettier formatting, extracted from #4435 for separate PR per @jmchilton's request.

Merge after #4435.

### CODE REVIEW

**Comment by dannon** [comment]
There was conversation in #galaxyproject about whether or not we want to go with a 4-space or 2-space tab stop, with @martenson and @jxtx primarily.  I think it was agreed that we need to have a standard and enforce it, but it seems like there are arguments for both 2 and 4.  This PR currently enforces a 4-space tab standard, following the trend of much of our existing JS style, and our Python code style.  That's easily removed by stripping https://github.com/galaxyproject/galaxy/pull/4436/commits/0669e780e09f05c9eb6365dc662e7a661a8391b5, but I think that what is presented here is a good starting point.

The best news is that with Prettify it's trivial to swap, should we change our mind down the road.

**Comment by willdurand** [comment]
Let's go for 4 spaces. It is best to set the rule for the whole project so Python, CSS, JS should be all 4 spaces.

**Comment by martenson** [comment]
converting all JS to 4 spaces :+1:

**Comment by jmchilton** [comment]
What I was requesting was a clean PR that just modified the code formatting - maybe after the build pipeline was in place (?) - so maybe a PR to setup the new build system and then a second afterward that actually builds the artifacts and modifies the formatting of the files. This still seems to mix Makefile changes, babel configuration, gulpfile addition, etc... in with the formatting changes. Github won't even load the list of all changed files for me. Like I said before though - it isn't feasible that is fine - it'd just help me grok the changes.

**Comment by dannon** [comment]
@jmchilton This is branched off the other PR.  When that's merged, all you'll see are the prettier addition and formatting changes.  (and I'd like that merged first and this building on that, anyway)

**Comment by jmchilton** [comment]
@dannon Ahhh... I see what you are saying - thanks for the clarification.

**Comment by jmchilton** [comment]
@dannon Indeed I see it now over in the other PR - it is a lot cleaner now - much easier to understand what is going on. Thanks for doing this!

**Comment by dannon** [comment]
@jmchilton No problem, wasn't a big deal.

**Comment by dannon** [comment]
(rebased on top of #4435, cleaned up)

**Pull request merged**
