### PR TITLE
[16.10] Fix #3353

### LINKED ISSUE #3353: Samtools Filter on BAM or SAM fails at http://usegalaxy.org
Fails immediately. Was a problem last week, then worked, now fails again on some runs, but not all. Same exact inputs.

**Error**:

> Job environment and execution information is available at the job Info Page.
> Job ID	XXX
> Tool ID	toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.1.2
> Tool Version	1.1.2
> Job PID or DRM id	None
> Job Tool Version	None
> Job Execution and Failure Information

> Command Line
> 
> None
> stderr
> 
> 
> stdout
> 
> 
> Job Information
> 
> Can't instantiate abstract class SafeStringWrapper(galaxy.datatypes.tabular.TabularData:<class 'galaxy.tools.wrappers.ToolParameterValueWrapper'>,<class 'galaxy.util.object_wrapper.SafeStringWrapper'>,<class 'numbers.Number'>,<type 'NoneType'>,<type 'NotI
> Job Traceback
> 
> ```
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 909, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
>     raise e
> TypeError: Can't instantiate abstract class SafeStringWrapper(galaxy.datatypes.tabular.TabularData:<class 'galaxy.tools.wrappers.ToolParameterValueWrapper'>,<class 'galaxy.util.object_wrapper.SafeStringWrapper'>,<class 'numbers.Number'>,<type 'NoneType'>,<type 'NotImplementedType'>,<type 'bool'>,<type 'bytearray'>,<type 'ellipsis'>) with abstract methods set_meta
> ```
cc @galaxyproject/guac @natefoo

### PR DESCRIPTION
**Pull request by jmchilton**
Fix #3353 something the tool does causes instantiation of the abstract class.

Ping @nsoranzo - this doesn't feel great let me know if you want to dig a bit deeper and uncover the source of the instantiation.

### CODE REVIEW

**Comment by jennaj** [comment]
self ping @jennaj

**Comment by martenson** [comment]
@jmchilton this seems to target wrong branch according to the title

**Comment by nsoranzo** [comment]
Thanks @jmchilton for fixing this, I'd like to take a look at what's exactly happening here (samtools_filter2 has a few weirdnesses in its command, but not sure that's the cause) , but I'll be away from a proper computer for the next 2 weeks, so feel free to merge this and assign me a follow-up ticket.

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@nsoranzo your take.

**Comment by martenson** [comment]
👍 
let's merge this and create a follow-up ticket @nsoranzo asked for

**Comment by nsoranzo** [comment]
This simple patch for the affected tool fixes the problem for me:
```patch
diff --git a/tools/samtool_filter2/samtool_filter2.xml b/tools/samtool_filter2/samtool_filter2.xml
index a5d2b9a..8e1632a 100644
--- a/tools/samtool_filter2/samtool_filter2.xml
+++ b/tools/samtool_filter2/samtool_filter2.xml
@@ -9,11 +9,11 @@
   <command>
 <![CDATA[
 ##set up input files, regions requires input.bam and input.bai
-#if isinstance($input1.datatype, $__app__.datatypes_registry.get_datatype_by_extension('bam').__class__):
+#if $input1.is_of_type('bam')
   #set $input = 'input.bam'
   ln -s "$input1" $input &&
   ln -s "$input1.metadata.bam_index" input.bai &&
-#elif isinstance($input1.datatype, $__app__.datatypes_registry.get_datatype_by_extension('sam').__class__):
+#elif $input1.is_of_type('sam')
   #set $input = 'input.sam'
   ln -s "$input1" $input &&
 #end if
```
I have checked several tool repositories for other affected tools and I found 5:

- tools-devteam: `tool_collections/gops/flanking_features/flanking_features.xml` , `tool_collections/gops/intersect/intersect.xml` , `tool_collections/gops/subtract/subtract.xml` , `tool_collections/hgv/hgv_hilbertvis/hilbertvis.xml`
- tools-iuc: none
- bgruening/galaxytools: none
- TGAC/earlham-galaxytools: none
- peterjc/galaxy_blast: none
- crs4/orione-tools: none
- galaxyproteomics/tools-galaxyp: `tools/morpheus/morpheus.xml`

I'd say that these old tool just need to be fixed to use the appropriate syntax. Opinions?

**Comment by bgruening** [comment]
I fixed galaxyp in https://github.com/galaxyproteomics/tools-galaxyp/pull/113
But still if old tools and old versions are not working this is not good.

**Comment by jmchilton** [comment]
Clearly it is the better tool definition with the patch applied and clearly these tools shouldn't have been written that way - but reproducibility is very important. I don't think the trade off in this case of superior code design in the datatypes class is worth these older tools breaking. Galaxy allows older tools to be executed - that is important for re-running tools and workflows. I'm with @bgruening on this.

**Comment by martenson** [comment]
Can we please rename this to something more informative for the sake of release notes?

**Comment by nsoranzo** [comment]
I still need to check, but I suspect this PR may not fix the other broken tools.

**Comment by nsoranzo** [comment]
I think I have a better fix for this in #3429.

**Comment by jmchilton** [comment]
#3429 does seem a better fix - certainly more technically correct. Thanks a ton @nsoranzo.

**Pull request closed without merging**
