### PR TITLE
Allow installation of different repositories with the same name in a …

### PR DESCRIPTION
**Pull request by mvdbeek**
…single install transaction.

Addresses issue #1338

### CODE REVIEW

**Comment by mvdbeek** [comment]
Ping @gregvonkuster @bgruening

**Comment by gregvonkuster** [comment]
@mvdbeek Thanks for looking into this issue.  I think it would be better to not
restrict this enhancement to only repositories that contain tools.

Repositories in the tool shed are usually defined uniquely by a combination of repository name, owner and changeset revision.  If I remember correctly, each repo_info_dict in this case has this structure:

{&lt;repository name&gt; :
  (description, clone_url, changeset_revision, ctx_rev, owner, repositoy_dependencies, tool_dependencies)}

Have you found this to be correct?  If so, the following may be a better approach for your check (this has not been tested!!):

Note that I've also added a break in the for loop so that is does not continue
looking if the owner is found.

If the above structure is not correct, then we just need the owner (and possibly the changeset_revision as well) rather than a tool_id.  Will a combination of repository name and owner be sufficient to make this check?

owner = required_repo_infor_dict[required_repo_info_dict_key[4]
is_present = False
for repo_info_dict in all_repo_info_dicts:
    for k, v in repo_info_dict.items():
        if required_repo_info_dict_key == k:
            if owner == v[4]
                is_present = True
                break
...

**Comment by mvdbeek** [comment]
I don't think this is currently limited to tools, packages have a tool_id as well.
(Which indeed is a combination of name, owner, (version, if any is defined) and toolshed)
For example the [testcase suite_white_ghosts](https://testtoolshed.g2.bx.psu.edu/view/mvdbeek/suite_white_ghosts/f8aa371efc50) does not specify any tool.

You're right about break, that saves an additional loop though.

**Comment by gregvonkuster** [comment]
@mvdbeek Ok, sounds good!  ;)

**Comment by mvdbeek** [comment]
I'll add the break and do more testing, marking this WIP in the meantime.

**Comment by mvdbeek** [comment]
OK, i tested this now with the smaller white_ghost testsuite (which doesn't contain any tools) and also with the very large [metavisitor](https://toolshed.g2.bx.psu.edu/view/drosofff/suite_metavisitor_1_0/8a55ab5f0f81) suite that we will send out for peer-review soon.

**Comment by bgruening** [comment]
Works for me on with the test repo and does not break a few tools I tested.
@gregvonkuster what do you think?

**Comment by martenson** [comment]
This looks great, thanks a bunch @mvdbeek !
Still testing but probably gonna merge soon.

**Comment by martenson** [comment]
next beer is on me, @mvdbeek !

**Comment by gregvonkuster** [comment]
@bgruening I think this is fine.  ;)

**Comment by bgruening** [comment]
Awesome! Thanks a bunch @mvdbeek!

**Comment by mvdbeek** [comment]
Alright, thanks everyone!

**Pull request merged**
