### PR TITLE
add API endpoint to create TS repository

### PR DESCRIPTION
**Pull request by martenson**
This PR introduces new endpoint at the Tool Shed
you can **POST {toolshed_url}/api/repository**

``` json
{
"name": "new_repo_17",
"synopsis": "new_synopsis",
"description": "this is some repository",
"type": "unrestricted",
"remote_repository_url": "https://github.com/galaxyproject/tools-devteam",
"homepage_url": "https://github.com/galaxyproject/",
"category_ids[]": [ "adb5f5c93f827949", "529fd61ab1c6cc36" ]
}
```

and you will receive:

``` json
{
"deleted": false,
"deprecated": false,
"description": "new_synopsis",
"homepage_url": "https://github.com/galaxyproject/",
"id": "8cf91205f2f737f4",
"long_description": "this is some repository",
"model_class": "Repository",
"name": "new_repo_17",
"owner": "qqqqqq",
"private": false,
"remote_repository_url": "https://github.com/galaxyproject/tools-devteam",
"times_downloaded": 0,
"type": "unrestricted",
"user_id": "adb5f5c93f827949"
}
```

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/1QPzNb8w) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/2.patch) for testing.

**Comment by hexylena** [comment]
Thanks @martenson. @jmchilton I'm assuming code for this will need to be added to bioblend for it can be used in planemo?

**Comment by jmchilton** [comment]
Good plan! I don't know if I can get to it before the release (there are a lot of bugs left) - but ping after please if I forget - or PR's to bioblend welcome :).

**Comment by hexylena** [comment]
Ok, I'll have some time tomorrow for making those PRs, I'll see what I can get done. It's significantly of interest to me to automate that portion.

**Comment by bgruening** [comment]
How should we handle this in `shed.yml`? Simply adding 
- synopsis
- description
- type: one out of three? 
- remote_repository_url
- homepage_url
- category_ids []

Category list will fail silently if the category does not exists?

**Comment by hexylena** [comment]
I was going to use category titles rather than IDs and yes, print a warning
if the category doesn't exist.

Will need to add code to handle updating that information if it gets
changed over time

fre. 27. feb. 2015, 07.43 skrev Björn Grüning notifications@github.com:

**Comment by hexylena** [comment]
@martenson which parameters are required? name/synopsis/description?

**Comment by bgruening** [comment]
afaik, description is not required ...

**Comment by hexylena** [comment]
@martenson @bgruening never mind...it's documented in the docstring. Thanks @martenson!

**Pull request merged**
