### PR TITLE
Cytoscape as the Galaxy charts plugin

### PR DESCRIPTION
**Pull request by anuprulez**
# Introduction:

This PR integrates interactive graph visualizations adapted from the [Cytoscape](http://js.cytoscape.org/) as part of the Galaxy charts visualization. The Cytoscape is equipped with capabilities for the visualization and analysis of complex data based on Graph theory. The features like graph search algorithms, graph querying, set theory operations and compatibility with all modern browsers, jQuery, Node.js, Require.js and the R language (via RCyjs) make it a powerful library.

# First look:
look

Following from it, this PR includes:

- Graph search algorithms
- Graph traversal techniques
- Numerous layouts of graphs
- Multiple edge types
- Colors for animated edges and nodes and Zoom

Depth First Search

dfs

A* Search:

astar

Predecessors:

predecessors

# Usage tips:

- For animated Breadth First Search and Depth First Search one should click/ tap on a node (which become the root node). For Graph traversal techniques like Successors, Incomers etc. one node should be clicked.
- For animated A*, one should click on two nodes, one for the root and another for the destination.

# Data format:

The version of Cytoscape built for working with browsers supports input data as JSON which contains information about nodes and edges of the graph. So, data formats like Simple Interaction File (SIF) should be converted to JSON for the visualization to be included into the Galaxy. Hence, this PR includes a file format converter from SIF to JSON. The specification of a SIF file has been taken from [here](http://wiki.cytoscape.org/Cytoscape_User_Manual/Network_Formats). 
Right now, the plugin supports only SIF and JSON files. Moving forward, to extend the support for different kinds of files like GML and XGMML, converters to JSON can be written for these file formats too.

## Example of a SIF file:

nodeA _relationship_type_ nodeB
nodeC _relationship_type_ nodeA
nodeD _relationship_type_ nodeE nodeF nodeB
nodeG
...
nodeY _relationship_type_ nodeZ

Or

node1 _typeA_ node2
node2 _typeB_ node3 node4 node5
node0

# Citation:
Cytoscape.js: a graph theory library for visualization and analysis
Franz M, Lopes CT, Huck G, Dong Y, Sumer O, Bader GD
Bioinformatics (2016) 32 (2): 309-311 first published online September 28, 2015 doi:10.1093/bioinformatics/btv557

# Note: 

It overwrites and enhances the previously present basic Cytoscape viewer as charts plugin.

# Credits:

Thanks a lot to Björn Grüning (@bgruening) for his support and review.

All suggestions are welcome. Thanks a lot!

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @anuprulez! Nice work.
@nekrut this can be used for teaching as well!

**Comment by guerler** [comment]
This is really nice. I have minor suggestions. 1. Can we use the color selector instead of the RGB-sliders. 2. min-Zoom should probably be either 0, or stop zooming once all nodes are within the boundaries of the frame. Max-zoom should be set to a large number or such that at least one node is shown. Then we do not need those slider options in customization form either. 3. Finally, we should update the thumbnail/icon of this visualization type.

**Comment by nekrut** [comment]
incredible! once this is merged let cytoscape people know

**Comment by anuprulez** [comment]
@guerler Thanks for your review! I have updated the repository with the following changes:

1. Added color pickers for nodes, edges and highlighted edges and nodes (for search algorithms and traversals) and removed the RGB sliders.

2. Removed the zoom sliders too and fixed the values of minZoom as 0.1 (and not 0 because the graph becomes invisible) and maxZoom as 20 (one node and its label fits in the viewport).

3. Updated the icon of the plugin.

**Comment by martenson** [comment]
Well done, thanks for the flow of contributions @anuprulez ! 🎉

**Comment by anuprulez** [comment]
@martenson Thanks a lot!

**Comment by shenweiyan** [comment]
It is really a nice job. And if there are some SIF and JSON files for testing, it will be perfect.

**Comment by bgruening** [comment]
Maybe we should add some example data to the plugin, this could be used later for automatic testing.
@guerler opinions?

**Comment by guerler** [comment]
Sounds good, I think the goal should be to integrate this into our unified vis framework.

**Pull request merged**
