### PR TITLE
[21.05] Disable dockerhub pushes

### PR DESCRIPTION
**Pull request by mvdbeek**
We don't have the secrets and we're over the storage limits, so disable this for now.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Fixes https://github.com/galaxyproject/galaxy/actions/runs/1411499740

**Review by martenson — APPROVED** [review]

**Comment by almahmoud** [comment]
What storage limit are we over? I am still building and pushing from anvil fork fine to `galaxy` org on Dockerhub.
Also at least me, @nuwang, and @afgane could give you secrets for the `galaxy` Dockerhub org (and I offered to give secrets in the original PR if needed) if that's the issue.
Also the quay.io repo that was left also doesn't work. If you got credentials from Bjorn, you need to change the name of the quay repo from `galaxy-k8s` to `galaxy` assuming he owns that one.

**Comment by nuwang** [comment]
The quay.io repository is also galaxy-min now, and that has been configured to use a robot account.

**Comment by almahmoud** [comment]
I see `quay.io/galaxy-k8s/galaxy` still https://github.com/galaxyproject/galaxy/blob/dev/.github/workflows/build_container_image.yaml#L35 (and it's failing)

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/12837

**Pull request merged**
