### PR TITLE
hyphy-vision

### PR DESCRIPTION
**Pull request by rdvelazquez**
- Adds a visualization for results from [hyphy-tools](https://github.com/galaxyproject/tools-iuc/tree/master/tools/hyphy).
- Currently live at https://galaxy.hyphy.org
- I think the idea is to eventually add the hyphy-tools to usegalaxy.org; getting this viz in is an important step; there are also some minor revision still to be done to the tools themselves (that will be tracked at http://github.com/galaxyproject/tools-iuc) 

hyphyVision_galaxy

Thank you @stephenshank, @stevenweaver and @davebx

### CODE REVIEW

**Comment by rdvelazquez** [comment]
@nsoranzo or @bgruening This PR is holding up the CI for the HyPhy tools PR ( https://github.com/galaxyproject/tools-iuc/pull/2369) because the `hyphy_json_results` datatype is not yet in galaxy (here's the CI line: https://travis-ci.org/galaxyproject/tools-iuc/jobs/544760215#L1700). Is there a timeline for reviewing and merging this?

**Comment by nsoranzo** [comment]
@rdvelazquez That's outside of my comfort zone, unfortunately.

**Comment by mvdbeek** [comment]
If you'd like the datatype merged now we can do that if you split it out to a separate PR.

**Comment by rdvelazquez** [comment]
Actually, it looks like the CI is using release 19.05 (https://travis-ci.org/galaxyproject/tools-iuc/jobs/544760215#L465) so getting the datatype into the dev branch wouldn't address the issue anyway. No need to split out the datatype addition here; I'll keep this all together.

**Comment by mvdbeek** [comment]
We've discussed this internally, for just subclassing the datatype we're OK merging this into 19.05

**Comment by rdvelazquez** [comment]
Closing this now. To be reopened by @stevenweaver.

**Pull request closed without merging**
