### PR TITLE
add Saskia to contributors

### PR DESCRIPTION
**Pull request by martenson**
based on https://github.com/galaxyproject/galaxy/pull/2038 and other contributions (https://github.com/galaxyproject/galaxy/commits?author=shiltemann)

ping @galaxyproject/core 

@shiltemann

### CODE REVIEW

**Comment by hexylena** [comment]
:+1:

**Comment by mvdbeek** [comment]
👍

**Comment by bgruening** [comment]
+1

**Comment by tnabtaf** [comment]
Hi All,

What's the status of this nomination?

Thanks,

Dave C

On Wed, Apr 27, 2016 at 9:12 AM, Björn Grüning notifications@github.com
wrote:

> +1
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/galaxyproject/galaxy/pull/2256#issuecomment-215134616

## 

http://galaxyproject.org/
http://getgalaxy.org/
http://usegalaxy.org/
https://wiki.galaxyproject.org/

**Comment by martenson** [comment]
@tnabtaf it has been merged, but do not confuse this with the committers list, contributors do not have necessarily the responsibilities nor the rights of the committers

**Comment by dannon** [comment]
Yeah, this wasn't really a 'nomination' or anything.  Every person who contributes code to Galaxy should be in this list.  I added a bunch more in https://github.com/galaxyproject/galaxy/pull/2257

**Comment by tnabtaf** [comment]
Diky!
Thanks!

On Tue, May 10, 2016 at 8:43 AM, Dannon Baker notifications@github.com
wrote:

> Yeah, this wasn't really a 'nomination' or anything. Every person who
> contributes code to Galaxy should be in this list. I added a bunch more in
> #2257 https://github.com/galaxyproject/galaxy/pull/2257
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/galaxyproject/galaxy/pull/2256#issuecomment-218199884

## 

http://galaxyproject.org/
http://getgalaxy.org/
http://usegalaxy.org/
https://wiki.galaxyproject.org/

**Comment by dannon** [comment]
@tnabtaf If I get where you may have been going with this, however, it'd probably be really nice to highlight new contributors with every release/newsletter/whatever.

**Pull request merged**
