### PR TITLE
Cytoscape: bugfix for SIF files

### PR DESCRIPTION
**Pull request by anuprulez**
This PR includes a bug fix for SIF to JSON file conversion for Cytoscape charts plugin. 

- Nodes are now correctly arranged according to SIF file specification

For this SIF description:

```
nodeA xx nodeB
nodeB xx nodeC
nodeC xx nodeD
nodeD xx nodeA nodeB nodeC
nodeB xx nodeD
nodeZ
```
this is the resulting graph:

screenshot from 2017-04-06 16 49 50

### CODE REVIEW

**Comment by dannon** [comment]
I see the bundled libs were changed here -- do you know what caused that?  These plugins shouldn't probably be touching those.

**Comment by anuprulez** [comment]
This bundled lib map file showed up after pulling changes from dev

screenshot from 2017-04-06 17 05 17

It was also a part of the main [PR](https://github.com/galaxyproject/galaxy/pull/3817/files#diff-5384f0b1930a4765d3475830db040352)

**Comment by dannon** [comment]
Hrmm.  Wish I'd seen that then -- these should not be touching that main bundle.

If you check out dev and run 'make client', do you get changed bundles?

**Comment by anuprulez** [comment]
Yes, I did a fresh check out and made same changes as for this bug fix. Then I did "git status", bundle map file (static/scripts/bundled/libs.bundled.js.map) was not showing. Then I did "make client" and "git status", then this bundled file was added to the list of modified files.

**Comment by dannon** [comment]
@anuprulez Ok, let me test a few things and see what I find.  I'd really like to make sure the charts changes stay isolated and not interacting with our primary analysis bundles.

**Comment by dannon** [comment]
I'm not sure what I'm missing in your setup.  I just applied your changes to a fresh dev and I'm getting this:

https://github.com/galaxyproject/galaxy/compare/dev...dannon:charts_fix?expand=1

(sorry!  was just trying to comment, not close ;))

**Comment by nsoranzo** [comment]
Different `node/npm` version?

**Comment by dannon** [comment]
@nsoranzo Usually I'd say yes, but there seem to be a lot more side effects here than that would explain.

**Comment by dannon** [comment]
@nsoranzo This also has conflicts in the build artifacts.  Maybe that's a part of it.  Check out the updated diff in my comment before, it should be clean like that.

**Comment by dannon** [comment]
@anuprulez Not sure what's going on with the conflicts here, but I'm happy to cherrypick your changes and resolve the conflicts, merging manually, if you want.

**Comment by anuprulez** [comment]
@dannon Shall I try to merge again? fresh one after reverting/ rolling back changes?

**Comment by dannon** [comment]
@anuprulez Up to you.  I'm happy to do it on my end if you want.  (or, you can even open the PR from my link showing that diff above)

**Comment by anuprulez** [comment]
@dannon Can I delete this branch and work with a fresh one? I think I have messed this up because I am not able to commit or revert anything from here :(

**Comment by dannon** [comment]
@anuprulez Of course.

**Pull request closed without merging**
