### PR TITLE
Automatically remove the container when it exits. [WIP]

### PR DESCRIPTION
**Pull request by bgruening**
We should remove containers after using them. For more informations see: 
http://docs.docker.com/reference/run/#clean-up-rm

### CODE REVIEW

**Comment by hexylena** [comment]
This will likely be appropriate for all IEs, perhaps we should add this once in the IE code which uses `command_inject`?

**Comment by bgruening** [comment]
Thought about this to, but it's nice to get rid of this option easily to enable easier debugging. Moreover, I could imagine a setup without `--rm` + an automatic clean-up after 24h to enable some kind of data recovery.

**Comment by hexylena** [comment]
Yeah, ok, I understand the easier debugging, just wanted to prevent extra boilerplate. 

:+1: from me, maybe we'll revisit it later and improve it some way.

**Comment by bgruening** [comment]
Please don't merge ....

**Comment by jmchilton** [comment]
What is the WIP in progress on this?

My preference here would be that this detail is taken care of at the framework level - have ie_request add the remove container and perhaps disable it if a debug option is set in the ini file.

**Comment by hexylena** [comment]
Is there any conceivable reason to not have `--rm` set? If not, then I'm with @jmchilton, should be framework level.

**Comment by bgruening** [comment]
Yes there is `--rm` is not compatible with `-d`. We need to start the container as daemon in an other way. Closing this now ...

**Comment by hexylena** [comment]
Could with replace `-d` with a `&` at the end?

**Comment by bgruening** [comment]
Yes something like that, but this needs to be tested carefully. Actually subprocess has some magic for this as well ...

**Pull request closed without merging**
