### PR TITLE
Plugin directory staging

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by dannon** [comment]
@guerler Thanks for taking over on this one and getting it off my plate!

**Comment by guerler** [comment]
Sure np. Thanks for the gulp addition and for coming up with this solution.

**Comment by nsoranzo** [comment]
Is this going to affect out-of-tree visualisations?

**Comment by guerler** [comment]
I made some adjustments such that it will not effect existing visualizations. Thanks.

**Comment by nsoranzo** [comment]
@guerler Thanks!

**Comment by dannon** [comment]
I don't think those routes will work under uWGSI -- that's why we had to do all this in the first place, right?  I think it's probably best to just require staging in the plugins directory *or* if someone wants to host plugins outside /config/plugins, they can handle their own static routing?

**Comment by nsoranzo** [comment]
@guerler Thanks!

**Comment by nsoranzo** [comment]
@guerler Thanks!

**Comment by guerler** [comment]
@dannon I rerouted them to the staged static directory. I thought the problem with uswgi was that the config directory is not statically served, these routes on the other hand just provide aliases for the already served static directory, but maybe I am misunderstanding this.

**Comment by dannon** [comment]
@guerler Sorry, I think I should have explained the problem this work needed to address a bit better.  The static middleware doesn't even get applied under uWSGI -- https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/stack/__init__.py#L173

**Comment by guerler** [comment]
I see. Ok. I restored it to the previous commit which require accessing through 'static/' until we know how to move forward. Thanks @dannon.

**Pull request merged**
