### PR TITLE
Repack

### PR DESCRIPTION
**Pull request by dannon**
@martenson When I rebuilt the client I'm seeing dynatree as well as the two files you included in #850.  Any ideas?

### CODE REVIEW

**Comment by martenson** [comment]
I do not see any changes after running `grunt` on latest dev

**Comment by martenson** [comment]
ping @guerler @carlfeberhard

**Comment by blankenberg** [comment]
FWIIW, I also had no local changes after grunting latest dev.

**Comment by carlfeberhard** [comment]
Not seeing it either. Could be node version variation (0.12.4 here).

**Comment by martenson** [comment]
@dannon if it is the dynatree regex there is an interesting comment above the line (last line in file https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/libs/jquery/jquery.dynatree.js#L2033):
`// Eclipse syntax parser breaks on this expression, so we put it at the bottom.`

**Comment by dannon** [comment]
Yeah, I just saw that too.  The regex as it stands in the existing repo is correct, when comparing to the original source.

My node version is 4.1.1
grunt-cli is v0.1.13

**Comment by dannon** [comment]
(marked WIP just so this doesn't get merged, but we should sort out which version(s) of things are incompatible)

**Comment by martenson** [comment]
node --version: v0.10.32 (brew)
grunt-cli@0.1.13

**Comment by dannon** [comment]
The new dynatree doesn't have this same error and builds consistently regardless of nodejs platform, closing in favor of #856.

**Pull request closed without merging**
