### PR TITLE
Replace Workflow Editor Tool Panel with Vue component

### PR DESCRIPTION
**Pull request by guerler**
This PR replaces the mako-based workflow tool panel in `editor.mako` with the vue-components introduced by @inkuzmin in #8368.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Any chance you'll merge https://github.com/galaxyproject/galaxy/pull/9167? I'm happy to resolve the conflicts with that and merge this if you do.

**Comment by guerler** [comment]
I started reviewing #9167 and commented. I would prefer to merge this PR first since it can go stale quickly.

**Comment by jmchilton** [comment]
That doesn't seem fair given mine was out of WIP longer, opened first, and has more lines of diff meaning more likely to stale(?) 😆. I at least offered to clean up the conflict that will result and merge yours - any chance you would do the same for me if I merge this?

This doesn't end well for me does it? 😆

**Comment by guerler** [comment]
Definitely, I'd always help with resolving code conflicts due to a merge. And you are right, sorry for not having looked into #9167 earlier. It looks pretty good but I am wondering if we can vue-ify the backbone rows before we merge it. I am still looking into it. Eitherway I feel like these two PRs are independent except some minor code conflict which I'd definitely help to resolve quickly.

**Comment by guerler** [comment]
I assumed that this panel change touches a larger variety of code parts than vue-ifying the upload dialog but you are right, there is no empirical evidence for its 'staleness' yet. (:

**Comment by guerler** [comment]
Can you still review this PR? Do you have any suggestions?

**Pull request merged**
