### PR TITLE
Fix smart_str for Python 3. Add doctests

### PR DESCRIPTION
**Pull request by nsoranzo**
xref. #1715

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Jenkins test failure is random, toolshed tests passed on the previous run and framework failed, now the opposite, not sure what the cause is (disk space again, @martenson?)

**Comment by martenson** [comment]
@nsoranzo disk space is fine, but the error seems indeed random

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
