### PR TITLE
[16.01] Test case and fix for issue #1514

### PR DESCRIPTION
**Pull request by jmchilton**
Prior to PR #1302 workflows wouldn't validate call validate at all on inputs. 1302 was perhaps an over correction that causes validate to be called on datasets that aren't yet READY but require metadata. This rolls that back somewhat, other parameters will still validate - but validation asserting the existence of metadata won't get called in workflows. This is still not ideal but after 1302 and this - we are still in a better, more secure place than beforehand.

One might argue that since we need to introduce a new validation point (right before a job is scheduled and set to QUEUED) - that we would be better off rolling back #1302 entirely. I've considered that, but I still think it is better to fail fast on the other problems, also I would rather call the validation code too many times than not enough and it would be very late in the release cycle for such a change.

### CODE REVIEW

**Comment by Takadonet** [comment]
Patch fixes issue #1514  on our local test server. 
Thanks John.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
:+1:

**Comment by guerler** [comment]
:+1:

**Pull request merged**
