### PR TITLE
Suppress filenames in SAM merge using egrep

### PR DESCRIPTION
**Pull request by peterjc**
Based on fix suggested by Roberto Alonso (at CIPF) on the mailing list, see:
https://lists.galaxyproject.org/pipermail/galaxy-dev/2015-February/021589.html

### CODE REVIEW

**Comment by nsoranzo** [comment]
+1

Option "-h" is supported also on OS X: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/egrep.1.html

I was also suggesting to Roberto to open a PR, but including also the changes to lib/galaxy/datatypes/sequence.py .

**Comment by peterjc** [comment]
Fixing `lib/galaxy/datatypes/sequence.py` is on my TODO list if Roberto doesn't take this up.

**Comment by blankenberg** [comment]
If someone is going to be looking into this anyway, it might be nice to make sure that we are using a list of arguments instead of a string when calling the external command. And also probably not use os.system.

But this change looks good to me.

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/V4jAwtro) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/4.patch) for testing.

**Pull request merged**
