### PR TITLE
use dictobj as standard dependency

### PR DESCRIPTION
**Pull request by martenson**
ping @jmchilton @natefoo 
related to https://github.com/galaxyproject/starforge/pull/54

jstree.py has some customizations that we need to address before we do the same move :/

### CODE REVIEW

**Comment by nsoranzo** [comment]
Should we remove lib/galaxy/util/dictobj.py then?

**Comment by martenson** [comment]
@nsoranzo I knew I forgot something :D

**Comment by martenson** [comment]
is the `cmp` method handled to your liking @jmchilton ?

**Comment by martenson** [comment]
thank you for the merge @jmchilton

**Comment by jmchilton** [comment]
@martenson No - thank you for following through on this :smile:.

**Pull request merged**
