### PR TITLE
Kubernetes runner: authenticate through service account

### PR DESCRIPTION
**Pull request by pcm32**
The current PR allows the Kubernetes runner to authenticate to a Kubernetes master node when Galaxy is being run as a pod. This means, the runner can talk and send jobs to the same cluster where Galaxy is executing as a Kubernetes service (as a pod). Apologies for my PRs keep dragging the two commits for the logs part that I thought had been already merged.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@pcm32 Apparently #2528 never got merged, sorry about that. I'll merge it when tests finish.

**Comment by pcm32** [comment]
Thanks @nsoranzo, apparently test for commit c9b7d9b have been stalled for a day or more, keeping them with the yellow dot for long.

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
This looks great! Thanks.

**Pull request merged**
