### PR TITLE
[16.01] libraries: always fetch new permissions as we are reusing the view

### PR DESCRIPTION
**Pull request by martenson**
this caused other item's permissions to be shown on items in case you were accessing them in series without refreshing/reloading
ping @nsoranzo

### CODE REVIEW

**Comment by martenson** [comment]
test fail unrelated, please review

**Comment by martenson** [comment]
please review

**Comment by carlfeberhard** [comment]
+1 looks good to me

**Comment by hexylena** [comment]
:+1: looks harmless.

**Comment by nsoranzo** [comment]
Belated :+1:, thanks @martenson!

**Comment by martenson** [comment]
thanks for reporting it @nsoranzo !

**Pull request merged**
