### PR TITLE
[18.05] Added missing level fatal_oom to xsd

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/galaxyproject/galaxy/issues/6340

### CODE REVIEW

**Comment by nsoranzo** [comment]
Can you also add it to the `<exit_code>` (around line 4866) and `<regex>` documentation (around line 4934), please?

**Comment by bernt-matthias** [comment]
I hope I found all the places where docs were missing. Oddly some examples for using oom were already present. 

Will the PR find its way to dev and planemo?

**Comment by nsoranzo** [comment]
> Will the PR find its way to dev and planemo?

@bernt-matthias Yes, thanks for working on this!

**Comment by bernt-matthias** [comment]
Welcome. I use the oom+resubmission feature quite a lot. See also https://github.com/galaxyproject/galaxy/pull/6338 :)

**Review by nsoranzo — APPROVED** [review]

**Comment by jmchilton** [comment]
Thanks @bernt-matthias for the update, and thanks for the review @nsoranzo !

**Pull request merged**
