### PR TITLE
SQLAlchemy 2.0 upgrades (part 2)

### PR DESCRIPTION
**Pull request by jdavcs**
Follow-up to #16434. Covers ORM usage ([ref](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-orm-usage)). This PR is ready for review.

**For follow-up PRs:**
- [ ] lib/galaxy/datatypes
- [ ] lib/galaxy/jobs
- [ ] lib/galaxy/managers
- [ ] lib/galaxy/metadata
- [ ] lib/galaxy/tool_shed
- [ ] lib/galaxy/web
- [ ] lib/galaxy/webapps/galaxy/controllers
- [ ] lib/galaxy_test
- [ ] lib/tool_shed
- [ ] `build_initial_query` and friends (`web/framework/*`, `webapps/*`)
- [ ] #16761
- [ ] `model.DatasetCollection._get_nested_collection_attributes()`
- [ ] `model.DatasetCollection.populated_optimized`
- [ ] managers.users (tags: convert from Query, apply union correctly)

Ref: #12541

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
I wonder if we should just merge the new tool shed backend before you go making lots of changes to the code - that branch already refactors a bunch of stuff.

**Comment by jdavcs** [comment]
> I wonder if we should just merge the new tool shed backend before you go making lots of changes to the code - that branch already refactors a bunch of stuff.

I would be very much in favor of that; I wasn't sure how close that was to merging. Is it the full #15639 or a subset of it? (I'll then go through it and review (at least) the db/SA-related code).

**Comment by jmchilton** [comment]
Well we had decided to deploy it and test it first... that is seeming like a mistaken call given how we're not making progress on that. 

I already found and commented on one issue with the previous DB commit.

**Comment by jdavcs** [comment]
@jmchilton: rebased

**Comment by jdavcs** [comment]
Rebased again - just for the sake of starting a new branch on top of this. The pre-rebase version was all green (except for one unrelated selenium failure).

**Comment by jmchilton** [comment]
Very nice! Thanks for breaking these up into reviewable pieces.

**Pull request merged**
