### PR TITLE
[20.09] fix exporting datasets from library as collection

### PR DESCRIPTION
**Pull request by OlegZharkov**
## What did you do? 
FIxed collection creation from library datasets 

## Why did you make this change?
fixes https://github.com/galaxyproject/galaxy/issues/11610

## How to test the changes? 
- [x] Instructions for manual testing are as follows:
  1. create library
  2. upload 2+ datasets
  3. import as collection

thanks a lot @martenson for reporting!

### CODE REVIEW

**Comment by martenson** [comment]
@OlegZharkov  thanks for the quick fix. Btw the prefix of this PR does not correspond to the target branch.

**Comment by OlegZharkov** [comment]
> @OlegZharkov thanks for the quick fix. Btw the prefix of this PR does not correspond to the target branch.

Oh, you're right. Just a sec ...

**Comment by OlegZharkov** [comment]
thanks @dannon

**Comment by OlegZharkov** [comment]
thanks @dannon

**Pull request merged**
