### PR TITLE
Add datatype for Mash Sketch files.

### PR DESCRIPTION
**Pull request by dfornika**
https://mash.readthedocs.io/en/latest/sketches.html

I'm working on adding a `mash screen` tool to the tools-iuc repo:

https://github.com/galaxyproject/tools-iuc/pull/2205

This pull request adds a datatype for mash sketch files.

### CODE REVIEW

**Comment by bgruening** [comment]
@dfornika do you know if this file format as a magic-bit (https://en.wikipedia.org/wiki/List_of_file_signatures) set? Or can we `sniff` this format in any way?

**Comment by dfornika** [comment]
I took a look at the docs and couldn't find any mention of a magic-bit. We could try contacting the developer(s) to find out how to sniff `.msh` files.

**Comment by dfornika** [comment]
@ondovb is there any way to 'sniff' a mash sketch file for a specific magic bit or some other binary signature to detect the file type? I'd like to add a mash sketch datatype to Galaxy.

**Comment by jmchilton** [comment]
I'm going to merge as is and we can follow up if there is a sniffer we can add?

**Review by jmchilton — APPROVED** [review]

**Comment by dfornika** [comment]
Sounds good to me. Thanks @jmchilton

**Comment by ondovb** [comment]
> @ondovb is there any way to 'sniff' a mash sketch file for a specific magic bit or some other binary signature to detect the file type? I'd like to add a mash sketch datatype to Galaxy.

Not exactly, but they are [Cap'n Proto](capnproto.org) serializations, so there may be a way to check for that. Capnp schemas also have globally unique IDs, which for the Mash schema is `@0xc4c8b1ada05e7704`. I don't know how to actually query this, or if it is even stored in the serialized files, but hopefully this is a good place to start looking at least. For what it's worth, our tools just look for a `.msh` extension :).

**Pull request merged**
