### PR TITLE
[PROCEDURES] Update committers list to reflect latest

### PR DESCRIPTION
**Pull request by nturaga**

### CODE REVIEW

**Comment by martenson** [comment]
👍 goodluck 
😿

**Comment by hexylena** [comment]
:+1: thanks for all the fun (and the rstudio commits!)

**Comment by jmchilton** [comment]
:+1: you'll be missed!

**Comment by nturaga** [comment]
I'm always here in spirit :D Just not on the committers list.

**Comment by nsoranzo** [comment]
:+1: Sorry to see you go! Good luck with your new projects!

**Comment by bgruening** [comment]
Äh ... 😿  ... good luck with whatever comes next!

**Comment by blankenberg** [comment]
+1
hoping to still seeing you at conferences

**Comment by blankenberg** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
👍  thanks for all the good work Nitesh!

**Comment by natefoo** [comment]
👍 

Best of luck with your current and future endeavours Nitesh

**Comment by martenson** [comment]
farewell @nturaga

**Pull request merged**
