### PR TITLE
Install tools and workflow

### PR DESCRIPTION
**Pull request by manabuishii**
import_tools is option and default is False.
If import_tools is True, install tools in workflow.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hi @manabuishii, thanks for this contribution, I think this is something a lot of people want.
I think https://github.com/galaxyproject/galaxy/pull/2823 is trying to achieve a very similar goal. Perhaps you could test this out and provide some feedback on whether it does what you would like to achieve here?

**Comment by manabuishii** [comment]
Sorry long time no reply.

I need to check #2823 more detail and try with it.

Difference (a glimpse)
At least my PR is installed tool from toolshed when option is specified.
My PR is designed for Web API and using bioblend.

#2823 is not install tool from toolshed , it just return tool which is required install.
But I need to check more detail soon.

Future.
I want to import workflow and tool at once from web interface.
It'll be another PR.

**Comment by manabuishii** [comment]
Currently I test #2823 

```
/api/workflows?missing_tools=True
```

works fine.

It returns workflows with missing tools list.
After I install it disappear in return value.

**Comment by manabuishii** [comment]
Still test #2823

```
/api/tool_shed_repositories/shed_repository
```

works file.

I can access different toolshed repository.
toolshed and testtoolshed

**Comment by manabuishii** [comment]
I want to test GUI change of #2823 
But I don't know how to check #2823 change in GUI ( Web interface )
Please tell me how to test GUI change.

**Comment by manabuishii** [comment]
Main difference of my this PR and #2823 is that my PR is `install missing tools`.
#2823 is just display ( at least I my understand )

But my PR is just support `/api/workflows` not GUI (Web interface)

Option name is different from #2823

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
I abused my access to merge with dev and pushed to this PR.

I also made a modification that requires the API user to be an admin to run this - since only admins are allowed to install shed repositories. I added a test case for this.

I'm 👍 on this - looks great - thanks for the contribution @manabuishii! I'll merge when the tests are done and I'm sorry for the delay.

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
