### PR TITLE
Very basic tool error sentry reporting.

### PR DESCRIPTION
**Pull request by dannon**
Report field suggestions very welcome, this is just my first guess as to what might be useful.

Addresses #1750 

Ping @erasche

### CODE REVIEW

**Comment by hexylena** [comment]
Will test tomorrow AM. Thanks @dannon looks like a great start!!

**Comment by hexylena** [comment]
@dannon okay, got it running this morning.
1. Absolutely beautiful. This will save me many hours. I owe you a tasty beverage.
2. Could we include the tool version in the title, so multiple versions of a tool don't get conflated?
3. Is the path to the XML file available (xref #1127)

**Comment by dannon** [comment]
@erasche Thanks for checking it out, great ideas!  Both implemented in f46f1d5

**Comment by hexylena** [comment]
@dannon great, :+1:, I'll merge as soon as tests finish.

**Comment by dannon** [comment]
Cool, if this is viable enough as a first pass for ya I'll go ahead and take it out of WIP.

**Comment by hexylena** [comment]
@dannon it absolutely is. Was there something else you were planning on adding?

**Comment by dannon** [comment]
Nothing in particular, just wanted some feedback about what'd be useful to include -- which you gave.

**Comment by hexylena** [comment]
:)

**Comment by martenson** [comment]
looks great!

**Pull request merged**
