### PR TITLE
Upgrade FastAPI to v0.70.0

### PR DESCRIPTION
**Pull request by davelopez**
I will try to upgrade the FastAPI dependency to the latest version gradually as in the [v0.70.0 release notes](https://github.com/tiangolo/fastapi/releases/tag/0.70.0)
- [x] First to FastAPI 0.68.2, with no breaking changes, but upgrading all the sub-dependencies.
- [x] Next to FastAPI 0.69.0, which upgrades Starlette to 0.15.0, with AnyIO support, and a higher chance of having breaking changes.
- [x] Finally to FastAPI 0.70.0, just upgrading Starlette to the latest version 0.16.0 with additional bug fixes.

*Note*: I'm going to update the dependencies manually because I can't make poetry work in a reasonable amount of time, so I will appreciate expert eyes on this... :sweat_smile:  

## Reason
There are some bug fixes in both FastAPI and Starlette and we should try to keep in sync with the latest changes as much as we can at least until the new stack becomes the default.
Also, there is a fix for the previous breaking change in 0.65.2 that was forcing us to use JSON Content-type on all payloads, so after this, hopefully, there should be no need to explicitly set `json=True` in the API tests requests.

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by jdavcs — APPROVED** [review]
I've given up on poetry for now - last time I tried to add a dependency and record how long it takes for it to solve the dependency graph, it took 10 hours before it died. So I just added the dependency manually. We may need to find a better way to do this, eventually, but for now, in my opinion, it's fine. (At least the risk of something conflicting - which we will find and fix sooner rather than later - outweighs the potential derailment of any PR that seeks to update a dependency :smile:

**Comment by davelopez** [comment]
The failing tests seem unrelated:
- `lib/galaxy_test/api/test_libraries.py::LibrariesApiTestCase::test_nonadmin` has been flaky for a while.
- The converter tests are failing apparently because some tool is failing the lining:
  ```
  root/lib/galaxy/datatypes/converters/fasta_to_bowtie_base_index_converter.xml
  Failed linting
  Applying linter general... WARNING
  .. WARNING: Requirement bowtie defines no version
  ```

So I guess there are no breaking changes after the upgrade :tada:

**Comment by davelopez** [comment]
Ok, I've seen exceptions being logged in the [currently failing Converters tests](https://github.com/galaxyproject/galaxy/runs/4094784659?check_suite_focus=true#step:11:36578) in the new pull requests due to `anyio.BrokenResourceError`.
Apparently is related to https://github.com/tiangolo/fastapi/issues/4041 which is a Starlette issue that seems to be [addressed in Starlette v0.17.0](https://github.com/encode/starlette/issues/1284)

FastAPI v0.70.0 is pinned to Starlette v0.16.0, so I guess we cannot just update to Starlette v0.17.0 yet. Should we downgrade FastAPI to v0.69.0 then or wait for a new release?

**Comment by nsoranzo** [comment]
The failing converter test has just been fixed by https://github.com/galaxyproject/galaxy/pull/12851 (already merged forward), but we probably still want to avoid the `anyio.BrokenResourceError` .

**Pull request merged**
