### PR TITLE
Enhance the VTK datatypes to support cell data in addition to point

### PR DESCRIPTION
**Pull request by gregvonkuster**
data.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@gregvonkuster It seems that you force-pushed to the same branch of PR #1185, which is now "Closed".

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@gregvonkuster Very useful git/github way of managing multiple PRs/works in progress is to create a new branch(based on the future PR target branch) for each of them. then you can have multiple PRs open and you can update every single one independently.

**Comment by gregvonkuster** [comment]
@nsoranzo @martenson Should this PR be closed with a new one opened against dev?  I thought this one was going against dev, sorry!

**Comment by martenson** [comment]
@gregvonkuster this one is against dev and it is fine, but the other PR (#1185) now has 0 commits because you also used gregvonkuster:dev as source and probably force pushed to it (overriding commits) while working on this new PR.

You should be able to retrieve the overriden commits by using `git reflog` (please see http://sp2hari.com/git-reflog-and-git-force-push/)

**Comment by gregvonkuster** [comment]
@martenson Should I close https://github.com/galaxyproject/galaxy/pull/1185 and re-submit the changes as a new PR?

**Comment by martenson** [comment]
@gregvonkuster I think you have to, preferrably put your changes in a separate branch and then make a new PR from it. Thank you Greg!

**Comment by gregvonkuster** [comment]
@martenson Ok, I hope this is correct.

**Comment by nsoranzo** [comment]
Unfortunately no, you pushed again to the same `dev` branch instead of creating a new one, so now this PR is now mixing the code for the old #1185 with the code for VTK datatypes.

**Comment by gregvonkuster** [comment]
Ok, I give up.  Should I close this?

**Comment by nsoranzo** [comment]
I'm opening a new PR for release_15.10 for the TS fixes now.

**Comment by nsoranzo** [comment]
@gregvonkuster Do you have the original commit message for the TS fixes?

**Comment by gregvonkuster** [comment]
@nsoranzo I believe they are here: https://github.com/galaxyproject/galaxy/pull/1185

**Comment by gregvonkuster** [comment]
@martenson I'm wondering if this PR is still useful or if I should close it and reopen one with only this change: https://github.com/gregvonkuster/galaxy/commit/df35d1795e3bcdf7860bdcc097bbfa21957bf32a

**Comment by martenson** [comment]
@gregvonkuster closing this and opening a new PR from a clean feature-branch would be my choice

**Pull request closed without merging**
