### PR TITLE
[20.01] Use browser locale over global default

### PR DESCRIPTION
**Pull request by mvdbeek**
Not 100% sure this is correct, but it seems logical to me.
Should fix https://github.com/galaxyproject/galaxy/issues/9459.

### CODE REVIEW

**Comment by dannon** [comment]
@mvdbeek The change looks reasonable to me, but this code hasn't changed in a long time, and i18n is working fine for me.  When I change browser locale to `zh`, for example, it works fine.  Are you seeing it fail for you, too?

**Comment by mvdbeek** [comment]
Yes, if I set firefox to french and go in anonymous mode to usegalaxy.org I don't see french. Same with a local Galaxy instance.

**Comment by dannon** [comment]
@mvdbeek I'm perplexed.  
image


(doing a little more debugging to see what's up)

**Comment by mvdbeek** [comment]
Hmm, can you try this locally and check if you don't have anything in `user_locale`, which would take precedence ?

**Comment by dannon** [comment]
@mvdbeek I think there still *might* be a race condition, otherwise I wouldn't be seeing what I did in the screenshot above (anonymous user, incognito browser, langauge set to `fr`).  But this does adjust priorities correctly IMO, and it fixes the one bug related to the swap from `null` to `'auto'` as the default value.

**Pull request merged**
