### PR TITLE
Add the CSG Viewer visualization plugin

### PR DESCRIPTION
**Pull request by gregvonkuster**
based on conversations here:
https://github.com/galaxyproject/galaxy/issues/1191#issuecomment-162553926

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@martenson @nsoranzo @erasche @bgruening @blankenberg Can this be merged or is there something more I should do?

**Comment by martenson** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
I'm can not tell about the JS side, the vis side looks good!

**Comment by gregvonkuster** [comment]
@bgruening The JS side works.  I recently added a tool that allows you to use an image dataset (png or jpg format) to apply a texture to a shape.  Here's a sample using the viewer!  ;)

block

**Comment by martenson** [comment]
I am not an expert but this looks solid. Thanks @gregvonkuster !

**Comment by gregvonkuster** [comment]
@martenson @bgruening Thanks for the reviews and the merge - much appreciated!  ;)

**Pull request merged**
