### PR TITLE
ToolSourceDisplay dynamic import for shared libs bundle size improvement.

### PR DESCRIPTION
**Pull request by dannon**
Prism is our largest individual library at ~1.5Mb parsed, but it's only used in one place.  This shifts that component to a dynamic load for its own bundle, trimming the main shared library bundle significantly (~30%) and loading it on demand.

## How to test the changes?
(Select all options that apply)
- [x] Instructions for manual testing are as follows:
  1. View tool source, ensure that still works.
  2. Note the extra bundle fetch for ToolSourceDisplay.bundled.js and the accompanying library (something like `751.bundled.js`).
 

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Very cool! I can confirm those benchmarks :)

**Comment by bgruening** [comment]
@dannon is there something to test here to not add an unexpected large dependency tree to the client?

**Comment by dannon** [comment]
@bgruening That's a great idea; I'll look to see if there are any CI options for at least a way to highlight the (bundled) size of new dependencies.  Right now we have a couple more very large ones I want to adjust the loading for, and I'm going to be paying more attention manually going forward.

**Comment by bgruening** [comment]
I found this so far:

* https://github.com/bundlewatch/bundlewatch (needs API key)
* https://github.com/marketplace/actions/bundle-size-diff

**Pull request merged**
