### PR TITLE
Add support for compressed VCF files

### PR DESCRIPTION
**Pull request by gallardoalba**
This PR includes gzip compression option in VCF datasets.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:

Compress a VCF dataset.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, tests failure looks relevant :( - no idea why this is failing.

**Comment by mvdbeek** [comment]
```
>           assert file_ext == PARENT_SNIFFER_MAP.get(expected_file_ext, expected_file_ext)
E           AssertionError: assert 'vcf.gz' == 'vcf_bgzip'
E             - vcf_bgzip
E             + vcf.gz
```
I think that just doesn't work, is there any reason not to go with `vcf_bgzip`, which is the exisiting, correct compressed vcf datatype.

**Comment by gallardoalba** [comment]
> ```
> >           assert file_ext == PARENT_SNIFFER_MAP.get(expected_file_ext, expected_file_ext)
> E           AssertionError: assert 'vcf.gz' == 'vcf_bgzip'
> E             - vcf_bgzip
> E             + vcf.gz
> ```
> 
> I think that just doesn't work, is there any reason not to go with `vcf_bgzip`, which is the exisiting, correct and indexable compressed vcf datatype ?

Just because it was necessary for including this PR https://github.com/galaxyproject/tools-iuc/pull/4437

**Comment by mvdbeek** [comment]
I don't know if using the auto_compressed framework for this is a good idea. As the tests are telling you, the result of the conversion is actually vcf_bgzip (which makes sense, why would we do gz compression if we get "free" indexing capabilities with bgzip). Maybe @FredericBGA can clarify what the source of these non-bgzipped vcf files is (if they aren't already bgzipped, in which case they should just be vcf_bgzip).

**Comment by FredericBGA** [comment]
> I don't know if using the auto_compressed framework for this is a good idea. As the tests are telling you, the result of the conversion is actually vcf_bgzip (which makes sense, why would we do gz compression if we get "free" indexing capabilities with bgzip). Maybe @FredericBGA can clarify what the source of these non-bgzipped vcf files is (if they aren't already bgzipped, in which case they should just be vcf_bgzip).

Hello,
I've added 'vcf.gz' because this is the real extension of the files. And most of our compressed VCF files are used through a Galaxy data library. And this data library has been created using the real file name and extension.

**Comment by mvdbeek** [comment]
So they are bgzipped ? Then you only need to change the extension. The problem here is that non-bgzipped files can't be used in many applications, yet they are vcf.gz files. I also don't think this PR would help here.

**Comment by FredericBGA** [comment]
yes, my files are `vcf.gz` files. It is quite old now, I remember that I wanted to see 'vcf.gz' in the library, instead of 'vcf_bgzip'

**Comment by gallardoalba** [comment]
This PR can be closed I think. Thanks @mvdbeek

**Pull request closed without merging**
