### PR TITLE
Zoom reset feature

### LINKED ISSUE #8170: Add a reset-zoom button to workflow zoom
Kind of like how browsers let you reset to default, and usually the button showing the percentage of zoom will also reset to default on click

image

### PR DESCRIPTION
**Pull request by juleengraham**
- fix bug in the zoom feature (off-by-one error affecting zoom ranges)
- implement button to reset to default zoom percent (100%) and display current zoom percent
fixes #8170

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
It works well, I wonder if it would be beneficial to add a title/tooltip to the reset button to make it more obvious, @juleengraham ?

**Comment by juleengraham** [comment]
something like text when the user hovers over the button @martenson ?

**Comment by martenson** [comment]
@juleengraham sounds good, thanks!

**Comment by juleengraham** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@juleengraham I sent an invite to your account, from now on @galaxybot will listen to you.

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by juleengraham** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@juleengraham the failing test has been fixed upstream, it is not related to this PR
Thanks for your contribution!

**Pull request merged**
