### PR TITLE
Strip legacy history structure view

### PR DESCRIPTION
**Pull request by dannon**
This removes another (web, not API) controller endpoint and the associated mako.  It has been non-navigable from the UI for quite some time now.

Per discussions, we're going to start from scratch here.

### CODE REVIEW

**Comment by bgruening** [comment]
Are we going to replace this with something new in this release cycle? If not I would leave it in as long as we have a replacement.

**Comment by martenson** [comment]
@bgruening this cannot be reached from the UI and there are no plans to fix it atm

**Comment by dannon** [comment]
@bgruening Yep, @martenson Is correct on both points there.  We're going to develop something similar in this coming release cycle, but will start from scratch using the current client stack.

**Review by jmchilton — APPROVED** [review]

**Comment by mvdbeek** [comment]
Is it this structure ?

screen shot 2018-05-31 at 17 29 08

That one is quite useful to me and was working in 18.05 ? Do we have an issue to track progress for this ?

**Comment by dannon** [comment]
@mvdbeek No, it is not that structure view.  That said, I'll have the future work I mentioned written up this week.

**Comment by mvdbeek** [comment]
OK, cool, sorry for the noise

**Comment by dannon** [comment]
No worries at all.

**Pull request merged**
