### PR TITLE
use history_id fixture instead of instance variable with the same name

### LINKED ISSUE #15032: Type error: new history_id fixture conflicts with history_id instance variables
A recent change introduced a bug in our integration testing code. The new `history_id` pytest fixture ([see integration_utils.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy_test/driver/integration_util.py#L192)) conflicts with `history_id` instance variables [like this one](https://github.com/galaxyproject/galaxy/blob/dev/test/integration/test_upload_configuration_options.py#L57). This leads to multiple type errors  (~90) which can be triggered by running `mypy test lib` from a galaxy venv.

There have been two PRs that contain fixes to this bug: #14971 (currently a draft) and #15020 (closed). The former leaves the fixture intact and removes all references to `self.history_id`. The latter renames the fixture and updates all tests that use it. The former is a better approach; besides, it also solves the problem of assigning stuff to `self` in the body of a test (in pytest, each test gets its own instance of the class it belongs to ([ref](https://docs.pytest.org/en/7.1.x/getting-started.html#group-multiple-tests-in-a-class)), so assigning anything to `self` in a test is misleading at best).

I'm opening this issue to track the `history_id` bug (which is not the focus of #14971). Fixing this bug removes 91 mypy errors and, therefore, is a prerequisite for #15004.  (ping @nsoranzo, @mr-c)

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #15032 , pulled out from #14971 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jdavcs** [comment]
Test failures are relevant.

**Comment by mr-c** [comment]
@jdavcs @nsoranzo Any thoughts about these `test/integration/objectstore/test_objectstore_datatype_upload.py::test_upload_datatype_irods` errors?

https://github.com/galaxyproject/galaxy/actions/runs/3516010336/jobs/5892003490#step:15:589


> AssertionError: Failed to create new dataset with response: {"err_msg":"1 validation error for Request\nhistory_id\n  Invalid id length, must be multiple of 16 (type=value_error)","err_code":400008,"validation_errors":[{"loc":["history_id"],"msg":"Invalid id length, must be multiple of 16","type":"value_error"}]}

Same error at
https://github.com/galaxyproject/galaxy/actions/runs/3516010336/jobs/5892003675#step:15:592 (x4)

https://github.com/galaxyproject/galaxy/actions/runs/3516010336/jobs/5892003833#step:15:603

https://github.com/galaxyproject/galaxy/actions/runs/3516010336/jobs/5892003998#step:15:10448 (x5)

Presumably some problem with https://github.com/galaxyproject/galaxy/pull/15037/files#diff-a1ae38ab61c69ace06544e1e5d338fc55ea12fda9f21ac0291f29292e8699c51R207

**Review by jdavcs — APPROVED** [review]
Looks great! Thank you, @mr-c and @nsoranzo!

**Comment by nsoranzo** [comment]
@jdavcs Sorry, there were a few more instances of `self.history_id` in integration tests, which I have fixed in an additional commit.

**Pull request merged**
