### PR TITLE
[18.05] Specify standard HTTPTransport for Sentry

### PR DESCRIPTION
**Pull request by dannon**
This should play nicer with a wider array of uwsgi configurations.

### CODE REVIEW

**Comment by dannon** [comment]
@moskalenko I *think* this might fix your problem.

**Comment by moskalenko** [comment]
We'll see. Thanks.

**Comment by moskalenko** [comment]
I've modified the code and restarted Galaxy. I'll monitor for any job-related errors in sentry.

**Review by hexylena — APPROVED** [review]

**Comment by moskalenko** [comment]
Here's what I'm seeing in the logs after the change, not sure if relevant:

18:09:52 [DEBUG] sentry.api: New event received (d1a41fcd42094b6fb3fe5d1f85e181ae) (project=u'sentry/galaxy' protocol=u'6' tags={'project': u'sentry/galaxy', 'protocol': u'6', 'agent': 'raven-python/6.9.0'} agent=u'raven-python/6.9.0')
127.0.0.1 - - [28/Jun/2018:18:09:52 +0000] "POST /api/2/store/ HTTP/1.1" 200 366 "-" "raven-python/6.9.0"
18:10:00 [DEBUG] sentry.api: Ignored empty interface value: repos (project=u'sentry/galaxy' protocol=u'6' tags={'project': u'sentry/galaxy', 'protocol': u'6', 'agent': 'raven-python/6.9.0'} agent=u'raven-python/6.9.0')
18:10:00 [DEBUG] sentry.api: New event received (c8c38d69e30c4e80a3b1c42465cb65c5) (project=u'sentry/galaxy' protocol=u'6' tags={'project': u'sentry/galaxy', 'protocol': u'6', 'agent': 'raven-python/6.9.0'} agent=u'raven-python/6.9.0')
127.0.0.1 - - [28/Jun/2018:18:10:00 +0000] "POST /api/2/store/ HTTP/1.1" 200 366 "-" "raven-python/6.9.0"

**Comment by moskalenko** [comment]
Unfortunately centry doesn't pick up drmaa runner errors as those are considered external and not internal tracebacks even though they get printed to galaxy job runner logs.

**Pull request merged**
