### PR TITLE
[WIP] Do not update dataset states. Expect tests to fail.

### PR DESCRIPTION
**Pull request by jdavcs**
This is intended to fail.

### CODE REVIEW

**Comment by jdavcs** [comment]
Surprisingly, only 1 (~~relevant~~) test failed.

**Comment by jdavcs** [comment]
And it passed! And it wasn't supposed to.

**Comment by jmchilton** [comment]
That is terrifying 😰.

**Comment by jdavcs** [comment]
Closing; related development + discussion in #9515

**Pull request closed without merging**
