### PR TITLE
[22.05] Make Agp set_meta more lenient

### PR DESCRIPTION
**Pull request by astrovsky01**
Certain tools used in VGP workflows, specifically YAHS and Salsa2, set the linkage column in AGP files to yes and the `linkage_evidence` column to `na`. This converts the error raised by that problem into a warning

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by bernt-matthias — COMMENTED** [review]
Can you add a test case?

**Comment by mvdbeek** [comment]
And a `make format` will fix the linting error.

**Comment by bernt-matthias** [comment]
> Can you add a test case?

Maybe analogous to https://github.com/galaxyproject/galaxy/blob/dev/test/unit/data/datatypes/test_qiime2.py

**Comment by mvdbeek** [comment]
Thanks @astrovsky01!

**Pull request merged**
