### PR TITLE
[STABLE] UI, History: fix model setAsCurrent to use galaxy_config.root proxy pref...

### PR DESCRIPTION
**Pull request by carlfeberhard**
...ix

### CODE REVIEW

**Comment by carlfeberhard** [comment]
Hopefully this doesn't cause any issues since it's in dev already. I'm sure there's a way to cherry pick that commit over to this branch - I'll learn how to do that.

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/lc4dACuu) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/39.patch) for testing.

**Comment by martenson** [comment]
I don't think there should be merge issues.
:+1:

**Comment by jmchilton** [comment]
:+1: 

@carlfeberhard Should be `git cherry-pick <hash>` unless I am missing something.

**Pull request merged**
