### PR TITLE
[16.01] Backport #3122 #3124 - fix unescaped & in integrated_tool_panel.xml

### PR DESCRIPTION
**Pull request by mvdbeek**
ping @nsoranzo @bgruening

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by martenson** [comment]
This fails 2.6 unit tests, is it a problem?

```
  File "/home/travis/build/galaxyproject/galaxy/lib/galaxy/util/__init__.py", line 48, in <module>
    from xml.etree.ElementTree import ParseError
ImportError: cannot import name ParseError
```

**Comment by jmchilton** [comment]
I think it is a problem unfortunately. If this version of Galaxy supported Python 2.6 we probably need to make sure these changes support Python 2.6.

**Comment by mvdbeek** [comment]
I think the failing TS test is unrelated and has been failing on 16.01 for a while now (see other PRs targeting 16.01).

**Comment by bgruening** [comment]
Yeah, the TS tests seems to be a non-issue. Thanks Marius! :+1:

**Comment by nsoranzo** [comment]
Merged forward.

**Pull request merged**
