### PR TITLE
Paginate contents for large histories

### PR DESCRIPTION
**Pull request by carlfeberhard**
...and do some refactoring. 

Has histories that have more than 500 datasets/collections render the contents in pages with pagination controls above the contents display. The goals here are: 
- keep it relatively simple
- use a familiar control method (plain pagination) for large lists 
- make sure everything works with that, then start optimizing the caching and/or painful use cases

The PR also:
- improves the speed of queries for both contents and histories themselves
- stops loading deleted and hidden contents (until told to do so)
- loads views generated in mako templates using the api instead of template variables (as a step to removing those templates)
- restructures the dom of the panels and uses a fixed header
- shows search progress in history subtitle
- improves error handling and display

(Apologies for the large PR - this has taught me to, in the future, work with separate refactoring and prototyping PR's in parallel)

Related:
#2126 (part 1 & discussion on prototyping other pagination types)
#1374

### CODE REVIEW

**Comment by bgruening** [comment]
@carlfeberhard thanks for working on this!
We have tested it here with some users and here is the initial feedback:
- if we have 100.000 datasets, the motivation of this PR, the compo-box with "1st of 200" does not work I think
  - search, jump to a specific number would be great
  - jump to a specific page (I want to go to page 12)
- it should be configurable for a user how many elements he/she wants to see on one page (one user sad he wants to have 50 elements per page)
- a indication which datasets are shown in one page (page 1: 1-499)
- multi-history view: it is possible to drag-drop datasets into page X, I guess we should only allow dragging into page 1

**Comment by carlfeberhard** [comment]
@bgruening Thanks for the feedback - very valuable as always.

> if we have 100.000 datasets, the motivation of this PR, the compo-box with "1st of 200" does not work I think search, jump to a specific number would be great,  jump to a specific page (I want to go to page 12)

Understood. Like any select box, you can begin typing when it's in focus and the options will move to that text. For example, if you open the dropdown and begin typing '12' it will move to page 12 and you can press enter to move to that page. That's standard select box behavior and why the pages are numbered with the digits first (as opposed to 'page 12 of...' which would require typing 'page' first). 

I kind of consider the standard pagination '<< < 5 6 7 _8_ 9 10 11 > >>' to be an anti-pattern. I'm no expert and I have no research on it, but I've always found it frustrating not being able to move directly to a page. That's where the select box came from - a _native_ way to directly choose the page.

Whether there's enough of an affordance there that text can be used is probably a good question.

> it should be configurable for a user how many elements he/she wants to see on one page (one user sad he wants to have 50 elements per page)

That's fair and I would agree with him. I think there are a lot of thing in Galaxy that should be user configurable. I think adding a way to set this (a new preference UI) goes beyond the scope of this PR?
Not sure. 

> a indication which datasets are shown in one page (page 1: 1-499)

For the current page, this is easy to get. For all other pages, it would require fetching the page and getting the HID of the first and last dataset of each. Unlike the prototype with sections from the previous PR, the pages here aren't determined by an HID range, just limit and offset.

For the current page, we could show the hid range possibly. Would that be an improvement even if the other pages in the dropdown don't display the hid ranges?

> multi-history view: it is possible to drag-drop datasets into page X, I guess we should only allow dragging into page 1

This is a bug I had thought was fixed. I'll see what I can do about that.

@nsoranzo good catch. Will fix.

**Comment by bgruening** [comment]
> > if we have 100.000 datasets, the motivation of this PR, the compo-box with "1st of 200" does not work I think search, jump to a specific number would be great,  jump to a specific page (I want to go to page 12)
> 
> Understood. Like any select box, you can begin typing when it's in focus and the options will move to that text. For example, if you open the dropdown and begin typing '12' it will move to page 12 and you can press enter to move to that page. That's standard select box behavior and why the pages are numbered with the digits first (as opposed to 'page 12 of...' which would require typing 'page' first). 

Ah true. Ok this is nice, not so obvious but good enough!

> I kind of consider the standard pagination '<< < 5 6 7 _8_ 9 10 11 > >>' to be an anti-pattern. I'm no expert and I have no research on it, but I've always found it frustrating not being able to move directly to a page. That's where the select box came from - a _native_ way to directly choose the page.

Yeah, I actually like it, not sure if there is a nice way to make it more obvious.

> Whether there's enough of an affordance there that text can be used is probably a good question.
> 
> > it should be configurable for a user how many elements he/she wants to see on one page (one user sad he wants to have 50 elements per page)
> 
> That's fair and I would agree with him. I think there are a lot of thing in Galaxy that should be user configurable. I think adding a way to set this (a new preference UI) goes beyond the scope of this PR?
> Not sure. 

Not this PR! :)

> > a indication which datasets are shown in one page (page 1: 1-499)
> 
> For the current page, this is easy to get. For all other pages, it would require fetching the page and getting the HID of the first and last dataset of each. Unlike the prototype with sections from the previous PR, the pages here aren't determined by an HID range, just limit and offset.
> 
> For the current page, we could show the hid range possibly. Would that be an improvement even if the other pages in the dropdown don't display the hid ranges?

Yes this would be nice and is enough!

Thanks @carlfeberhard!

**Comment by carlfeberhard** [comment]
> Yeah, I actually like it, not sure if there is a nice way to make it more obvious.

I'll see what a tooltip can add.

> Not this PR! :)

True! How about 'goes beyond the scope of a better planned...oh dear god...I have to get this PR in before it's longer than the tax code.../drinks extensively.../dies'?

> Yes this would be nice and is enough!

Got it and I'll give it a try. Any suggestions on an unobtrusive spot for that are welcome.

**Comment by bgruening** [comment]
@carlfeberhard I think this is a great improvement and we should merge it if you feel ready! Looking forward to it!

This one needs a small rebase.

**Comment by carlfeberhard** [comment]
Hey, @bgruening I'm going to move this to 16.10 to get it more testing/time. I'd rather keep all the commits, so I won't rebase it but I will resolve conflicts.

**Comment by carlfeberhard** [comment]
@bgruening I tried a few ideas and there's no great place (currently) to put the hid range. I'll add it to the list for the next iteration, tho.

**Comment by bgruening** [comment]
Carl, as soon as this is in dev I will prepare some Docker images and get some user feedback. I think this is great work and we should collect as many feedback as we can!

Thanks a ton!

**Comment by dannon** [comment]
I like this, seems to work pretty well in a few huge histories I made for testing.  Merging locally to resolve conflicts.

**Comment by dannon** [comment]
@carlfeberhard Found one small bug after playing with it a bit more, here at #2707

**Comment by carlfeberhard** [comment]
@dannon Thanks for taking a look and the merge. I'll put 2707 on the list for the next iteration this cycle.

**Comment by dannon** [comment]
@carlfeberhard Anytime, no worries about 2707, pretty minor.

**Pull request merged**
