### PR TITLE
ES6 broad pass overhaul

### PR DESCRIPTION
**Pull request by dannon**
This 
- converts all of our javascript (both amd and commonjs) to es6 modules, and updates require()s left in .mako to use the default exports that were added during translation.  **we can replace the defaults with named exports as we go, that just wasn't reasonable to do in a single pass**
- replaces callbacks with arrow functions
- implements string literals
- minor formatting w/ variable declarations (multi-defines are gone, for readability/explicit handling)
- Adds a GXY_NOPACK env var you can use when building to beautify instead of uglify the code.  This is useful when you're trying to watch the console and variable names/etc are garbled.
- Adds (cherry-picked @jmchilton's commit from #4832) a `make client-format` makefile target.

As the *very last commit* on this branch, I'm going to swap `prettier` formatting to 120 chars as discussed in #4828 and #4875, to minimize conflict resolution required by anyone merging with this work (so, hopefully one merge instead of having to track through multiple).

The structure view (not show_structure, but structure) needs some help, but that's not exposed anywhere, is also broken in dev, so I'm going to shelve that for right now.

### CODE REVIEW

**Comment by jmchilton** [comment]
Any clue how to fix the failing qunit tests? Seeing the same thing after I cleanup imports a different way in my local branch.

**Comment by dannon** [comment]
@jmchilton Nothing solid, but I think I have an idea as to what it is, but it'll take some tinkering with babel/requirejs.

**Comment by dannon** [comment]
Closer.  Now both bundled and non-bundled es6 code should work in the browser, but there are definitely a few conversion bugs (particular imports vs *, etc).

**Comment by dannon** [comment]
Most of this is working nicely now with the exception of charts, which I need to fix.  Going to grep around for the same class of errors (default import issues when pulling in new stuff via require -- so, the old parts of the app) and see what else needs fixing, but it's close.

Barring complaint, I will pull #4875 in as well, to make it easier on people merging against this branch.

**Comment by dannon** [comment]
Pages are busted, working on a fix.

(fixed)

**Comment by jmchilton** [comment]
I've pointed this Jenkins Selenium job at this branch https://jenkins.galaxyproject.org/view/All/job/jmchilton-selenium/. It runs every two hours. dev had three failures in it earlier today but I think #4913 should have fixed those (it fixed at least one locally for me).

The imports are cleaner and the arrow stuff looks good to me, there are some places I think where the template literals took stuff that prettier had made bad and somehow made things a bit worse (some really long lines that mix a lot of strings and variables in such a way that the flat short lines were a bit easier to visually parse), overall though on average I think we are coming out ahead in terms of readability with that change as well.

**Comment by dannon** [comment]
Fixing IEs right now, then this should pass tests (unit, functional, all of it) completely.

**Comment by dannon** [comment]
Jupyter will hopefully work now.

**Comment by jmchilton** [comment]
Manually tested on your branch - Jupyter does indeed work for me.

**Comment by dannon** [comment]
@jmchilton Awesome, thank you.  I'm looking for any other weirdness, and plan to take this out of WIP tonight.

**Comment by dannon** [comment]
All IES updated.  They all do things in slightly different ways; it'd be good to define a single, consistent interface/entrypoint for the launching protocol and update them all. (down the road)

**Comment by dannon** [comment]
All tests passing, ready for review.   If anyone has outstanding javascript work they want to get in today, before this, please let me know and I'll check it out and handle merging it with this; don't want to cause a mess for everyone.

**Comment by jmchilton** [comment]
I got a +1 on this out of band from @guerler who isn't feeling well today but looked it over so I'm going to bite the bullet and merge.

**Comment by dannon** [comment]
Awesome, thanks!  If we do find bugs (I'm sure there's *something*), nothing at this point should be too terrible to fix up.

**Comment by bgruening** [comment]
Thanks a lot @dannon! I have so high hopes for the client!

**Comment by martenson** [comment]
Overall the 120 is huge improvement to me compared to previous prettier settings, readability has been hurt at places but that is just a fallout of 'one size fits all' formatting which is expected. 

Thanks for doing this @dannon and let's hope we won't need any more of these all-touching blocking PRs.

**Comment by dannon** [comment]
@martenson I was just starting one for ES2018, though...  `/s`

**Comment by martenson** [comment]
🤓

**Pull request merged**
