### PR TITLE
flake8 lib/galaxy/webapps/tool_shed/model/migrate/versions/ .

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix 227 linting errors (mainly star imports).

`./run_tests.sh -toolshed` passes for me.

### CODE REVIEW

**Comment by nsoranzo** [comment]
xref: #391

**Comment by martenson** [comment]
I think we need to test this on all supported DB types

**Comment by nsoranzo** [comment]
@martenson: You can if you want, but this PR does not change the SQL commands, mainly fixes the star imports.

**Comment by dannon** [comment]
Should definitely be tested against the various database types.  I'm not saying that this one is broken, but these sorts of flake8 changes yield unexpected behavior frequently enough that we must test.

**Comment by nsoranzo** [comment]
@martenson Can Jenkins test PRs already? I'm not willing to do more testing locally, for the reason stated above.

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
I ran sqlite migrations and then `-toolshed` tests: all passed; we still need MySQL

**Comment by nsoranzo** [comment]
@martenson: Did you test on your local machine or Jenkins?

It would really help if this can be automated since I'm working on cleaning the other migration scripts.

**Comment by dannon** [comment]
Tested with mysql, works.

**Comment by martenson** [comment]
thanks @dannon

**Comment by nsoranzo** [comment]
Thanks @dannon!

**Pull request merged**
