### PR TITLE
[15.07] With Pulsar, ensure AMQP consumers receive published messages

### PR DESCRIPTION
**Pull request by natefoo**
See galaxyproject/pulsar#77 for full details. Galaxy is losing Pulsar status updates and jobs are often stuck in a non-terminal state when they have in fact already finished on the Pulsar side.

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton this includes an update of the Pulsar client which seems to work fine but I haven't tested extensively. Let me know if this is a particularly bad idea.

**Comment by natefoo** [comment]
Pulsar side of the work is galaxyproject/pulsar#81

**Comment by jmchilton** [comment]
Ugh - didn't notice this was 15.07. :+1: - anyone want to add another :+1: or should I do a revert?

**Comment by natefoo** [comment]
:+1: =D

**Comment by jmchilton** [comment]
Excellent - clearly no policy violations here, nothing to see, keep moving...

**Pull request merged**
