### PR TITLE
Add Galaxy Architecture slides in .md

### PR DESCRIPTION
**Pull request by martenson**
this is a very squashed rebase of #2283 by @remimarenco and @jmchilton 
squashed to get rid of huge png images that were added 

---

\+ the plumbing for slides creation

### CODE REVIEW

**Comment by martenson** [comment]
thanks @remimarenco, @jmchilton, @natefoo and others involved!

**Comment by jmchilton** [comment]
I still feel bad about squashing all of @remimarenco's commits. @remimarenco if you wish to rebase the old PR with the large images stripped and open a PR with Galaxy that just merges in a commit history for these files I would merge that. I'm not sure if the end merge would apply cleanly because all the changes are already here or if it would be a nightmare though.

**Comment by martenson** [comment]
I talked to @remimarenco and he approved of the squash. Nothing to feel bad about @jmchilton .

**Comment by jmchilton** [comment]
There is always something to feel bad about... I'll come up with something new I guess.

**Comment by martenson** [comment]
@jmchilton you were defending Tool Shed yesterday

**Comment by jmchilton** [comment]
With actual @jmchilton quotes such as "It is terrible." and "No one hates the tool shed more than me." I'm not sure defending is the right word.

**Comment by martenson** [comment]
Those are just things you say all the time. It is like 'good morning' or 'the weather is nice' from you and does not bear a meaning anymore. 😛  
However "Tool Shed is much better", "Tool Shed is not a priority", "I am much happier with Tool Shed now" are the new quotes.

**Pull request merged**
