### PR TITLE
Fixes to make Sweepster work again: (a) update template syntax to mat…

### PR DESCRIPTION
**Pull request by jgoecks**
…ch changes made in underscore v1.7 and (b) update tool rerun to account for API changes.

### CODE REVIEW

**Comment by carlfeberhard** [comment]
+1

**Comment by jmchilton** [comment]
Does this need to be in 14.07 - seems like probably. Ping @carlfeberhard

**Comment by carlfeberhard** [comment]
15.07?

**Comment by jmchilton** [comment]
Yes - that one - sorry - right around November is when I usually finally get used to the fact the year has changed.

Modifying these release notes I have found a few things to backport, I can do that for this - I was just wondering if it is the right thing to do.

**Comment by carlfeberhard** [comment]
Ha - yeah, this should be in the 15.07 release.

**Comment by jmchilton** [comment]
Cool - I'll open a PR with a few backported things in a little bit. Thanks Carl.

**Pull request merged**
