### PR TITLE
Merge release_16.01 into dev.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
@nsoranzo Why did you remove the milestone from this? For the release notes I need to assign everything interesting a milestone - and the easiest way to do that is to filter by "has no milestone" in github - so giving everything a miletstone is useful.

**Comment by natefoo** [comment]
These are 16.01 commits though. They won't show up in 16.04's release notes?

**Comment by jmchilton** [comment]
It has been marked as "merge" - I'll filter out everything marked as "merge".

**Comment by nsoranzo** [comment]
@jmchilton It seemed to me that the outcome of the IRC discussion was that forward-merge PRs don't go to the release notes and a milestone does not really apply for them (see @natefoo comment), so we introduced the "merge" label to make galaxybot happy.

If you need to exclude PRs tagged with "merge" you can add `-label:merge` to your query, but if you prefer to add the milestone also to forward-merge PRs, that's fine with me.

**Pull request merged**
