### PR TITLE
Allow using the rule based collection builders right from libraries.

### PR DESCRIPTION
**Pull request by jmchilton**
Fuses recent additions allowing creation of collections from libraries (#5080) and creating arbitrary collections from the rule builder (#5365).

Requested by @mblue9 on https://github.com/galaxyproject/galaxy/issues/5381#issuecomment-378107183 who is providing awesome feedback on the new rule based collection builder. She lays out the potential for this to save dozens of clicks when importing collections from libraries.

### CODE REVIEW

**Comment by martenson** [comment]
because of how the library router works the 'fake' links `href="#"` in the rule builder will have effects on navigation within libraries (the application under the rule builder modal reacts and goes to the library index)

**Comment by martenson** [comment]
`{"traceback": "Traceback (most recent call last):\n  File \"lib/galaxy/web/framework/decorators.py\", line 281, in decorator\n    rval = func(self, trans, *args, **kwargs)\n  File \"lib/galaxy/webapps/galaxy/api/history_contents.py\", line 393, in create\n    return self.__create_dataset_collection(trans, history, payload, **kwd)\n  File \"lib/galaxy/webapps/galaxy/api/history_contents.py\", line 530, in __create_dataset_collection\n    **create_params\n  File \"lib/galaxy/managers/collections.py\", line 100, in create\n    validate_input_element_identifiers(element_identifiers)\n  File \"lib/galaxy/managers/collections_util.py\", line 52, in validate_input_element_identifiers\n    raise exceptions.RequestParameterInvalidException(message)\nRequestParameterInvalidException: Found duplicated element identifier name 1.bam.\n", "err_msg": "Found duplicated element identifier name 1.bam.", "err_code": 400008}`

libraries allow datasets with same name

**Comment by martenson** [comment]
When rendering the rows for the preview the rulebuilder-css affects the global cascade and all rows within libraries become very short in the y-axis even after closing the modal. Needs hard reload to get rid of.

screenshot 2018-04-23 14 51 05


after hard reload: 
screenshot 2018-04-23 14 53 19

**Comment by jmchilton** [comment]
> libraries allow datasets with same name

So does the uploader and and then history panel - they will all suffer from the same poor validation checking here I think.

**Comment by jmchilton** [comment]
CSS problem is handsontable - I'm looking into it also:

screen shot 2018-04-23 at 3 09 12 pm

**Comment by jmchilton** [comment]
Three commits with various fixes - one commit per comment above from @martenson (library router, CSS contamination, and better handling of duplicate identifier errors).

**Pull request merged**
