### PR TITLE
Integration of charts into the generic visualization framework

### PR DESCRIPTION
**Pull request by guerler**
This PR augments the visualization framework by adding features which were initially established for charts visualization plugins e.g. now visualization input parameters and data groups are described in the visualization XML instead of charts js-config files. The associated form builder has been moved to core and can be used by other visualizations too. The chart selection grid with logos has also been moved to core and is used for all visualizations as default interface of the unified visualization framework. Individual chart visualization types/plugins have been re-intregated into the augmented visualization framework. This PR will require follow-ups.

### CODE REVIEW

**Comment by dannon** [comment]
Failing tests are unrelated.

**Comment by dannon** [comment]
+1

**Comment by guerler** [comment]
Thanks @dannon.

**Comment by bgruening** [comment]
@guerler this is amazing thanks a lot - super cool! ❤️

**Pull request merged**
