### PR TITLE
Show sections in workflow run

### LINKED ISSUE #1780: Sections don't show up properly in run-workflow on >=16.01
Workflow editor

selection_571

Run workflow

selection_572

Tool used in #1779

### PR DESCRIPTION
**Pull request by guerler**
Fixes #1780

### CODE REVIEW

**Comment by hexylena** [comment]
As mentioned out of band, would be helpful to have indentation/section names.

utvalg_684

Compare with the view workflow form
utvalg_685

**Comment by hexylena** [comment]
Thanks @guerler, I appreciate it. This was one of the issues that forced us to be on an old release.

**Comment by martenson** [comment]
just a reminder this needs a port to 16.01

**Comment by hexylena** [comment]
@martenson also need to fix the indentation/section labeling. Opening a new, blocking issue on 16.04 :(

**Pull request merged**
