### PR TITLE
Disable tool shed test function that fails frequently on Jenkins.

### PR DESCRIPTION
**Pull request by jmchilton**
xref #1617

### CODE REVIEW

**Comment by nsoranzo** [comment]
Maybe that's solved now by #3814?

**Comment by mvdbeek** [comment]
I think there could be a chance that #3814 fixed this, maybe we can observe this for a little longer?

**Comment by jmchilton** [comment]
Cool beans - very nice - I'll close and just re-open if I see it on a new PR.

**Comment by mvdbeek** [comment]
we have another one here: https://github.com/galaxyproject/galaxy/pull/3836 / https://jenkins.galaxyproject.org/job/docker-toolshed/5607/testReport/junit/shed_functional.functional.test_1090_repository_dependency_handling/TestRepositoryDependencies/test_0045_uninstall_and_verify_tool_panel_sections/

**Comment by jmchilton** [comment]
Thanks for re-opening and following up on this @mvdbeek. I check the parent commit and it looks like her branched that work after your PR was merged - so it looks like the bug in the test case (or Galaxy) still exists.

**Comment by davebx** [comment]
I've spent quite a number of cycles on trying to track down the cause of that issue, I've so far only been able to determine that it seems to happen on every second run. Don't know if that is of any help, and at my decrepit old age, I'm not even sure my memory is accurate on that.

**Pull request merged**
