### PR TITLE
Workflow run display improvements - esp. for inputs.

### PR DESCRIPTION
**Pull request by jmchilton**
- If steps have labels, use them.
- Use workflow step type icon from workflow editor in the run step bar.
- Eliminate "Step Index" from display of workflow steps.

Given the following labelled workflow input:

workflow_icon_0

It would show up as follows in the run form:

workflow_icon_2

I think the fact the label is ignored is problematic. This PR fixes that. It also condenses the display of the input a bit - using the icon used in the workflow editor to describe the "type" of step represented instead of a potentially redundant textual description of the workflow step. 

I also don't really like the "Step Index" display in the title taking up so much real estate. It isn't something users really need to know about and it is confusing in my opinion to describe an input as a "step" of the workflow so I just removed that outright. The new more condense, informative input is as follows: 

workflow_icon_3

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
Fwiw, my org's documentation for "how to run this workflow" includes a couple of steps with variable parameters and users are instructed to change parameters in those steps.

utvalg_007

While in all of my documentation instances, the steps are relatively uniquely named (and the forms expanded by default during run), I could see the removal of step number being a negative. (E.g. we have three blast steps in a row with only small changes between them. If there were some parameter our documentation told them that they had to change, we couldn't easily instruct the user exactly which step was which.)

Might be nice to hear from others but some alternative solutions:

- Remove "Step ", leave the number
- de-emphasize step (remove boldness)
- Move step number to the right side if it is visually disruptive.

Otherwise, SUPER excited to see input dataset label being used. That is so much clearer! Also like the icons. They're subtle but appreciated.

**Comment by jmchilton** [comment]
@erasche I like removing the step but keeping the number - that might be a good compromise. Happy to hear from others and just to restore the previous prefix if it is desired also.

**Comment by hexylena** [comment]
Personally, I'm happy to see "step step step step" gone, it was definitely redundant!

**Comment by guerler** [comment]
I think its a good idea and improves the display, but the changes to form-input.js and form-section.js should not be necessary, right?

**Comment by jmchilton** [comment]
@guerler Are you saying there is a different way to do it or that there is no change needed? It would just show like ``null`` or ``false`` in text for me without these I thought. I was just sort of trying different things to get it to work though - maybe not all these changes are needed. Feel free to push that change directly or I can play around with it some more.

**Comment by jmchilton** [comment]
@guerler Opps - sorry, missed the PR. Yeah it seems to work - I must be crazy.

**Comment by nsoranzo** [comment]
Agreed with @erasche that step numbers are useful.

> I like removing the step but keeping the number - that might be a good compromise.

+1

**Comment by jmchilton** [comment]
Based on this conversation, I have updated this to add the prefix of the order index back on the step title display.

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Merged manually because of merged in JS bundles.

**Comment by bgruening** [comment]
Thanks all!

**Pull request merged**
