### PR TITLE
Database connection disposal fixes.

### PR DESCRIPTION
**Pull request by dannon**
My hope is that this resolves database issues observed recently on the test toolshed under uwsgi.  If this actually resolves the issue, it will be cherry-picked over to #stable.

### CODE REVIEW

**Comment by martenson** [comment]
I will apply this manually on TTS and see what it does.

**Comment by martenson** [comment]
seems working well on TTS, :+1:

**Comment by blankenberg** [comment]
:+1:

**Comment by dannon** [comment]
Thanks for testing it.  I opened a stable PR as well, since these should be applied there.

**Pull request merged**
