### PR TITLE
Filter download links, avoid warning dialog

### PR DESCRIPTION
**Pull request by guerler**
This PR adds the 'download' attribute to dataset and tool download links. The attribute usually silences the 'beforeunload' event but is not yet supported by Safari: http://caniuse.com/#feat=download. That is why a manual filter for download requests has been added. In order to test this PR, you may open a scratch book window, hide it and then 1) download a dataset from the history or a tool from the tool form and 2) attempt to navigate away from the analyze view.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this please

**Comment by guerler** [comment]
@galaxybot test this please

**Comment by guerler** [comment]
@galaxybot test this please.

**Comment by guerler** [comment]
@galaxybot test this please

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Tested in both Safari and IE, works!

**Pull request merged**
