### PR TITLE
[15.10] Fix for Section and conditional upgrade messages.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Should we also update the `prefix` before recursing?

**Comment by blankenberg** [comment]
@nsoranzo I'm not so sure, as the messages are themselves nested. I don't think that displaying the prefixes in the messages is helpful here. 
Additionally, we aren't currently using prefix for conditionals, where a section is sort of a conditional with only one non-alterable condition.

Although, I don't feel strongly about it at all.

**Comment by nsoranzo** [comment]
We are using `rep_prefix` for repeats, so some consistency it's indeed needed. I'd lean toward adding a prefix because there could be the same parameters in different sections/conditional branches.

**Comment by jmchilton** [comment]
I'm :+1: because I'm indifferent regarding the prefix issue, especially for a bug fix. But ping @blankenberg - you should respond to @nsoranzo.

**Comment by blankenberg** [comment]
IMHO, the prefixing stuff makes sense and is necessary when going to a flat representation (e.g. creating /parsing HTML parameter names within a `<form>`), but doesn't really apply here, where everything is scoped to the current (nested) level.

However, looking at the two halves of this method, they are handling the scoping differently, with the first half always scoping into a local dictionary, but the second half scoping the messages directly into the base message dict (for conditionals and repeats).

Definitely inconsistent here, with scoping into local dicts seeming to be more proper.

**Comment by martenson** [comment]
As I see it this is a good bugfix. Thanks @blankenberg

@nsoranzo please feel free to open an issue whether or not we should prefix these (and possibly more?)

**Pull request merged**
