### PR TITLE
encourage wittiness in release notes

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by hexylena** [comment]
:+1: for making release notes great again. (Memes count as a topical reference, right?)

**Comment by jmchilton** [comment]
I really was kidding when I suggested this. I don't think it is a good idea to add this to the checklist, but it has enough +1s for merging - so I'm going to do that.

**Comment by hexylena** [comment]
@jmchilton I'm pretty much in agreement, saw this as kidding, not sure this is good to add to the checklist in this form. Perhaps we should revise this to be a little less silly:

Maybe the following would be more palatable / appropriate:
- 3 witty comments → 1-3 visually attractive screenshots of new features in action.
- inject one whimsical story → inject 0-1 whimsical stories about a galaxy in the wild solving real problems for real people.
- inject one topical reference → ?

**Comment by martenson** [comment]
I think revising this is silly. We should just leave it there as an easter egg. :)

**Pull request merged**
