### PR TITLE
Add ``py35-first_startup`` macOS job to Travis

### PR DESCRIPTION
**Pull request by nsoranzo**
Use conda to install Python 3.5 .

### CODE REVIEW

**Comment by mvdbeek** [comment]
How about running the unit tests as well ? I think that'd be quite valuable.

**Comment by nsoranzo** [comment]
> How about running the unit tests as well ? I think that'd be quite valuable.

py27-unit ?

**Comment by mvdbeek** [comment]
I'd probably opt for both unless we think it's too much load for our travis resources ?

**Comment by nsoranzo** [comment]
macOS builds used to be an issue, but now the situation seems much better. Maybe we can start with the 2 startup and the `py27-unit` jobs, and add `py35-unit` if it works well.

**Comment by mvdbeek** [comment]
Sounds good to me.

**Comment by mvdbeek** [comment]
Also if it does become a resource issue we can also bundle the unit tests with the startup test, I assume what is slow is booting the machines.

**Comment by mvdbeek** [comment]
Hmm, I see this is still 2/3 pending for more than 30 minutes. Should we maybe try to run everything as a single job ?

**Comment by nsoranzo** [comment]
@mvdbeek Unit tests failed twice for both reload tests :cry:

**Comment by mvdbeek** [comment]
Hmm, the callback hasn't been triggered, so I assume the thread failed to start in time ?

**Comment by nsoranzo** [comment]
> Hmm, the callback hasn't been triggered, so I assume the thread failed to start in time ?

Maybe, not sure to be honest. I don't have a Mac, so I cannot debug locally. Should we leave `py27-unit` for a separate PR, or do you want to try to fix it as part of this PR?

**Comment by martenson** [comment]
I would stick to the startup tests for now - those are the most important for macos I think.

**Comment by mvdbeek** [comment]
Different issue, let's not start fixing things in this PR. I do think the unit tests are as important as the startup tests, but we can talk about that when someone has figured out what is going wrong there.

**Review by martenson — APPROVED** [review]

**Pull request merged**
