### PR TITLE
Recalculate user disk usage on logout.  

### PR DESCRIPTION
**Pull request by dannon**
Not as ideal as just having it be accurate all the time, but it 1) avoids adding yet another control people need to dig for when they need to recalculate, and 2) makes things right when following 'turn it off and on again'

### CODE REVIEW

**Comment by dannon** [comment]
Adding a hint on the quota meter tooltip that if it seems incorrect, log out and back in.

**Comment by martenson** [comment]
@dannon what about adding this on login too?

edit: good idea btw

**Comment by dannon** [comment]
I thought about that, on login, but it's not *super* fast so I figured it would bother people less on logout.  What do folks think?  We can try it, I just don't want it to slow down the login/getting-started feeling.

**Comment by dannon** [comment]
(it occurs to me that we could consider this a 'fix' for the 'bug' where user disk space gets out of whack all the time, so we could also backport it to get it live on main/elsewhere if people like it)

**Comment by martenson** [comment]
I wonder why this PR never ran the jenkins suite... we could have found the TS fails :(

**Comment by dannon** [comment]
Good question, we should probably figure that out!  :)  In any event,  I updated the other PR with an extra check for user, and we can merge forward, and test should work fine from that point.

**Comment by jennaj** [comment]
When this goes to Main, could we note that here so end-users know when it is active? Many are following this ticket. Thanks!

**Comment by martenson** [comment]
@jennaj I think it is on Main already.

**Comment by dannon** [comment]
@jennaj @martenson is right -- this code is on main.  Subsequent improvements and fixes to the functionality are not, yet.  Some of those are in #3669, and others are in #3734

**Pull request merged**
