### PR TITLE
[23.0] Upgrade minimum conda to be compatible with latest conda-build

### PR DESCRIPTION
**Pull request by bernt-matthias**
solution for the build problems in https://github.com/galaxyproject/planemo/pull/1388

I manually tested that this solves the problem...

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Still testing. @nsoranzo still has some doubts ..

**Review by nsoranzo — APPROVED** [review]
Needed due to new changes in conda-build, see https://github.com/conda/conda-build/issues/4984#issuecomment-1701660360

**Comment by nsoranzo** [comment]
Maybe target release_23.0, which has the same issue and is still supported?

**Review by nsoranzo — APPROVED** [review]
Thanks!

**Pull request merged**
