### PR TITLE
[PROCEDURES] Explicit language on reversions and WIP v3

### PR DESCRIPTION
**Pull request by hexylena**
This commit implements #382 in response to the lack of explicit language
on how reversions are to be handled. This is in response to the events
transpiring in #433 and #449.

Additionally this PR corrects the misspelling of the pluralization of
the word veto.

This is a direct follow up, per procedures with a single squashed commit, of #450.

Let's try this again y'all, sorry for the mistakes.

| Key | Value |
| --- | --- |
| 192 hour window start | `2015-08-05 14:43:22+00:00` |
| 192 hour window end | `2015-08-13 14:43:22+00:00` |
| 25% quorum | `ceil(19 * .25)` = `ceil(4.75)` = 5, +1 votes |

### CODE REVIEW

**Comment by jmchilton** [comment]
@erasche No need to apologize - the rules are such that this bound to happen.

:+1: and thanks for continuing with the process @erasche.

**Comment by martenson** [comment]
:+1: Thank you Eric.

**Comment by dannon** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

**Comment by natefoo** [comment]
+1

**Comment by jxtx** [comment]
+1

**Comment by hexylena** [comment]
Okay, that's 6 :+1:s, we've reached our quorum. Someone please merge :)

**Comment by martenson** [comment]
@erasche I think we have to wait 192 hours.

**Comment by nsoranzo** [comment]
@erasche @martenson Yes, we have to wait (unless every qualified committer has voted).

**Comment by bgruening** [comment]
:+1:

**Comment by carlfeberhard** [comment]
+1

**Comment by blankenberg** [comment]
+1

**Comment by jmchilton** [comment]
The process works! Thanks for opening @erasche and merging @nsoranzo.

**Pull request merged**
