### PR TITLE
Enable collapsing markdown elements

### PR DESCRIPTION
**Pull request by guerler**
Mentioned in: #15088. Allows to optionally collapse/expand all existing markdown elements by declaring shared element attributes. This feature can be used with any markdown element by adding the `collapse="[TITLE]"` attribute. Additionally this PR adds client tests, unfortunately the client test coverage of markdown elements is still limited.

https://user-images.githubusercontent.com/2105447/210628091-44199566-abfe-40b5-9028-1aa58e1acd3e.mov

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by dannon — APPROVED** [review]

**Comment by hexylena** [comment]
I am trying to use this now and cannot figure out how one should add an attribute. I looked through the test case, but there's no markdown I as a user can recognised there, and the video only shows the output. So I've tried the kramdown style attributes

```
*something*
{: collapse="title"}
```

but that doesn't seem to work. The `?` button on pages doesn't document it either (I think this is the only attribute that can be added?), but links to CommonMark tutorial which also doesn't document it. Looking through the [common mark spec](https://spec.commonmark.org/0.31.2/), they don't support that flavour of attributes. 

I've tried html, but that doesn't work either. Any tips here would be welcome! :)

**Comment by guerler** [comment]
Sorry for not having documented that well enough. The attribute is supposed to be added as shown here:

```galaxy
history_dataset_type(history_dataset_id=3108c91feeb505da, collapse="[TITLE]")
```

**Comment by hexylena** [comment]
thanks so much! I'll add it to a tutorial!

**Comment by hexylena** [comment]
I think i was just mislead by 

> This feature can be used with any markdown element by adding the collapse="[TITLE]"

which meant *galaxy* markdown, not the rest, but it makes sense now, also why there wasn't any markdown in the test cases either! i'm adding it as an FAQ to the workflow reports tutorial so it'll be easy for learners to discover :)

**Pull request merged**
