### PR TITLE
NORA's image viewer. A medical image viewer and annotation tool

### PR DESCRIPTION
**Pull request by bgruening**
grafik

We added a few datatypes and will add more for the next Galaxy release to support a medical usecase. This a super cool viewer developed as part of the Nora project. Thanks a lot to Marco Reisert! 

I marked it as WIP as we need to move more dependencies into NPM I guess, but this should work as it is already!

Thanks again to Marco!

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Awesome!!!

**Comment by dannon** [comment]
@bgruening Nifty!  I found https://www.nora-imaging.com/#, but is there a public code repository somewhere?  I can do the packaging and deploy the viz if you want.

**Comment by dannon** [comment]
@bgruening Look good to you?  (If so, I'll merge this so we can get it into the release and keep iterating)

**Comment by bgruening** [comment]
Go for it Dannon! And thanks!

**Pull request merged**
