### PR TITLE
Multiview missing histories fix

### LINKED ISSUE #4605: Histories created via the REST API don't appear in the Web UI Straight Away
This is a rather odd issue, but it would appear that if you create a new history via the REST API it doesn't appear in the multiple histories view of the web UI until you create another new history; either via the REST API or using the "Create New" button in the web UI. Steps to see this in action are....

1. Firstly go and look at the current list of histories; for example on a local install visit http://localhost:8080/history/view_multiple and take note of the existing histories.
2. Create a new history via the REST API; there are many ways you could do this but possibly the easiest is from a browser with the Poster extension (in firefox or Chrome) by posting `{"name":"Testing 1, 2, 3", "deleted":false}` to http://localhost:8080/api/histories
3. Now refresh the histories page http://localhost:8080/history/view_multiple and you'll see that the history you created isn't displayed.
4. Create another new history (with a different name for sanity purposes) either via the REST API or the "Create New" button in the web UI and then refresh the page. At this point the history you created in step 2 will now appear.

I honestly have no idea why the histories don't appear until another one is created, but it's really quite frustrating when trying to debug REST API usage if the history simply doesn't appear in the web UI.

### PR DESCRIPTION
**Pull request by dannon**
This fixes #4605 and *probably* #3519.

Fix in 4f93f88.  Minor cruft cleanup, and swapping of commented out log statements to Galaxy.debug included in 	1502e00.

### CODE REVIEW

**Comment by mvdbeek** [comment]
This doesn't fix #3519 unfortunately :(. I can reproduce this 100% of the time though, so if you want me to try something else that wouldn't be a problem.

**Comment by greenwoodma** [comment]
does fix #4605 though, thanks!

**Comment by mvdbeek** [comment]
```
--- a/client/galaxy/scripts/mvc/base/controlled-fetch-collection.js
+++ b/client/galaxy/scripts/mvc/base/controlled-fetch-collection.js
@@ -57,6 +57,10 @@ var ControlledFetchCollection = Backbone.Collection.extend({
         // options.data.filters --> options.data.q, options.data.qv
         var filters = this._buildFetchFilters( options );
         Galaxy.debug( 'filters:', filters );
+        console.log('filters:');
+        console.log(filters);
+        filters = {'purged': "", 'deleted': "", 'encoded_id-in': ""};
+        console.log(filters);
         if( !_.isEmpty( filters ) ){
             _.extend( options.data, this._fetchFiltersToAjaxData( filters ) );
         }
```

is a hacky way that solves #3519  for me. And it's always the newest history that is missing if you make the current history a history that is not the newest history.

**Comment by mvdbeek** [comment]
this also works, and is probably closer to the real issue (concerning #3519):
```
--- a/client/galaxy/scripts/mvc/history/history-model.js
+++ b/client/galaxy/scripts/mvc/history/history-model.js
@@ -443,12 +443,12 @@ var HistoryCollection = _collectionSuper.extend( BASE_MVC.LoggableMixin ).extend
             xhr = _collectionSuper.prototype.fetchFirst.call( self, {
                 silent: true,
                 limit : 1,
-                filters: {
-                    // without these a deleted current history will return [] here and block the other xhr
-                    'purged'        : '',
-                    'deleted'       : '',
-                    'encoded_id-in' : this.currentHistoryId,
-                }
+                // filters: {
+                //     // without these a deleted current history will return [] here and block the other xhr
+                //     'purged'        : '',
+                //     'deleted'       : '',
+                //     'encoded_id-in' : this.currentHistoryId,
+                // }
             });
         }
         return xhr.then( function(){
```

**Comment by mvdbeek** [comment]
And empirically testing `// without these a deleted current history will return [] here and block the other xhr` doesn't reveal a problem, neither in the "saved histories" view nor in the "view all histories" view.

**Comment by mvdbeek** [comment]
This filter was introduced in 2a38b11e87bf58872850c23af0185c98cab491e4, which first appeared in 16.10, which is consistent with https://github.com/galaxyproject/galaxy/issues/3519#issuecomment-280659270

**Comment by mvdbeek** [comment]
I've opened a PR to this branch [here](https://github.com/dannon/galaxy/pull/20)

**Comment by dannon** [comment]
@mvdbeek Thanks!  At first glance, that filter (at least with the current history id) seems like it'd be necessary; let me check out what's going on.

**Comment by mvdbeek** [comment]
That shouldn't hold up this PR in any way, every fix is a good fix. Just thought we could combine it.

**Comment by mvdbeek** [comment]
This actually also fixes #3519, I guess I must have done something stupid building the client during my tests.

**Comment by mvdbeek** [comment]
Thanks so much @dannon !

**Comment by nsoranzo** [comment]
Should https://github.com/galaxyproject/galaxy/pull/4610/commits/4f93f88f0a2df07c5a8c3fa7c62fd4bda40fb3c1 be backported to 16.10?

**Comment by dannon** [comment]
Sure, I can do that!

**Pull request merged**
