### PR TITLE
Bug fix in Reports

### PR DESCRIPTION
**Pull request by OldWorldBoa**
Max items per page was reset when changing the amount of time Sparkline graphs spanned for per user, per tool, error per tool pages

Changed reports to use d3 from galaxy, not d3 servers.

### CODE REVIEW

**Comment by OldWorldBoa** [comment]
I'm not sure how this all actually works, but won't calling h.js() in run_stats.mako also guarantee me the requirement?

**Comment by OldWorldBoa** [comment]
So, this does the changes you suggested @carlfeberhard, but there's an error: 
Uncaught Error: Mismatched anonymous define() module: [object Object]
Hopefully I'll be able to iron that out quickly.

**Comment by carlfeberhard** [comment]
You might want to try moving the '${h.js("libs/d3")}' line before the '${parent.javascripts()}' line. d3 will try to load via requirejs if it detects require in the global namespace. Apologies for not noticing that.

**Comment by OldWorldBoa** [comment]
That fixes it, thanks!

**Pull request merged**
