### PR TITLE
all commands in new isolated shell

### PR DESCRIPTION
**Pull request by bgruening**
Remove `enable_beta_tool_command_isolation` from galaxy.ini and activate it by default.

This is more and more essential for tools that are depending on their own python version.

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening I agree that this should be done, but I'm wondering what the plan is for handling tools that do not function correctly when this setting is used.  I have no idea of the full set of tools, but iirc bwa is one.

**Comment by bgruening** [comment]
@gregvonkuster do you have any error message? I'm not aware of any tool that is nor working with this setting.

**Comment by gregvonkuster** [comment]
This is the tool stack trace when I run BWA from here https://toolshed.g2.bx.psu.edu/view/devteam/bwa/7bee165c3a44 on OS X.  I haven't tried this on Linux.  This is due to having this configuration setting.  When it is set as False, the tool runs fine.

Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/jobs/runners/local.py", line 128, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/jobs/**init**.py", line 1198, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/datatypes/binary.py", line 309, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jmchilton** [comment]
Is this because samtools isn't on Galaxys PATH. I think we can fix that, but I want to make sure it is the only problem.

**Comment by bgruening** [comment]
@jmchilton this would be also my guess.
@gregvonkuster can you confirm that this happens with every BAM file tool. It should also happen during upload of BAM files.

**Comment by gregvonkuster** [comment]
@bgruening Yes, this happens when uploading a bam file (below).  However, this same exception is thrown no matter the setting of enable_beta_tool_command_isolation in the Galaxy config file - it can be true or false and this happens when uploading.  Not sure how that affects this...
Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/galaxy/tools/data_source/upload.py", line 431, in <module>
    **main**()
  File "/Users/gvk/work/git_workspace/galaxy/tools/data_source/upload.py", line 420, in **main**
    add_file( dataset, registry, json_file, output_path )
  File "/Users/gvk/work/git_workspace/galaxy/tools/data_source/upload.py", line 347, in add_file
    if link_data_only == 'copy_files' and datatype.dataset_content_needs_grooming( output_path ):
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/datatypes/binary.py", line 213, in dataset_content_needs_grooming
    version = self._get_samtools_version()
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/datatypes/binary.py", line 176, in _get_samtools_version
    output = subprocess.Popen( [ 'samtools' ], stderr=subprocess.PIPE, stdout=subprocess.PIPE ).communicate()[1]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bgruening** [comment]
Can you try to following and create a symlink in your samtools directory called 'default' that points to the directory where your samtools `env.sh` is?

**Comment by martenson** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Anyone know if the correct way is to modify the tests?

**Comment by jmchilton** [comment]
@bgruening Can you close this in favor of #1412. @gregvonkuster can you verify #1412 doesn't suffer from the same samtools resolution problems as this does.

**Comment by gregvonkuster** [comment]
@jmchilton I cloned a new dev branch and applied your patch as follows (I had previously downloaded it into my_patch).  Let me know if there's a better way to do this.
MacBook-Pro-2:galaxy gvk$ git apply --stat my_patch 
 config/galaxy.ini.sample               |    7 ++++--
 lib/galaxy/config.py                   |    2 +-
 test/unit/jobs/test_command_factory.py |   28 +++++++++++++++++++++++---
 lib/galaxy/jobs/**init**.py            |   35 ++++++++++++++++++++------------
 lib/galaxy/jobs/command_factory.py     |    9 +++++---
 lib/galaxy/jobs/command_factory.py     |    4 ++--
 lib/galaxy/jobs/command_factory.py     |    5 +++--
 7 files changed, 63 insertions(+), 27 deletions(-)

I set the following in galaxy.ini:
enable_beta_tool_command_isolation = True

I then ran the same bwa job I had run several months ago that uncovered this problem at that time and see the same exception:

Traceback (most recent call last):
  File "/Users/gvk/work/galaxy/lib/galaxy/jobs/runners/local.py", line 128, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/Users/gvk/work/galaxy/lib/galaxy/jobs/**init**.py", line 1206, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/Users/gvk/work/galaxy/lib/galaxy/datatypes/binary.py", line 309, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bgruening** [comment]
Closed in favour of #1412. 

@gregvonkuster please feel free to post here even if it's closed.

**Comment by bgruening** [comment]
@gregvonkuster this might help you: https://help.github.com/articles/checking-out-pull-requests-locally/

git is so powerful that you patch workflow seems to complicated.

**Comment by gregvonkuster** [comment]
@bgruening I saw that tip, but couldn't locate the "command line at the bottom of the PR"...

**Comment by bgruening** [comment]
This is only for people with commit access. This one is more interesting for us:
`git fetch origin pull/ID/head:BRANCHNAME`

**Comment by gregvonkuster** [comment]
Thanks Bjoern, I'll give this a try.

**Comment by jmchilton** [comment]
Double checked and this does seem to resolve samtools dependencies now for metadata.

Also pushed out a change so the stack trace reported by @gregvonkuster should be considerably cleaner (see screenshot below).

samtools_error

**Pull request closed without merging**
