### PR TITLE
[STABLE] Re-enable job metrics by default.

### PR DESCRIPTION
**Pull request by jmchilton**
This has been broken since 14.10.

### CODE REVIEW

**Comment by martenson** [comment]
How come we did not notice it? :(

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/QHb0Auat) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/42.patch) for testing.

**Comment by nsoranzo** [comment]
:+1:

**Comment by blankenberg** [comment]
:+1:

**Comment by martenson** [comment]
:+1:

**Pull request merged**
