### PR TITLE
[17.01] Fix incorrect logout while impersonating

### LINKED ISSUE #3581: REMOTE_USER User impersonation Logout => (null)@domain
We're on release_17.01,

1. Log in as an admin user
2. Impersonate a non-admin
3. "Log out"
4. Stuck as `(null)@domain`.

Not sure if this is reproducible yet or just us, will try at end of day on my local instance.

### PR DESCRIPTION
**Pull request by hexylena**
cc @bgruening (y'all's code) @martenson (you do JS things) @dannon (remote_user)

In #3581 I documented that as I tried to logout under `REMOTE_USER`, my user account would be set as `(null)@fqdn` and I would be stuck until I cleared my browser cookies.

This happens because of the new webhooks. When on the `/user/logout` route a request is made to `/api/webhooks/history-menu/all` and `/api/webhooks/masthead/all`. Normally this is fine, but on the logout page there is no user set.

The API responds with a cookie for the null user, which the browser dutifully accepts and uses. In order to prevent this we have a special case for the one page where we cannot make XHRs.

I feel like there is an API based solution but it is escaping me. Everything I try seems to set a cookie (i.e. switch `expose_api_anonymous_and_sessionless` to `expose_api` in the hopes of 404'ing when on /user/logout fails to behave as expected.

### CODE REVIEW

**Comment by bgruening** [comment]
@erasche sorry for the mess. Looks good to me, at least I do not have a better idea :(

**Comment by hexylena** [comment]
No, not your fault at all! Sorry, I did not mean to come across as blaming you. This was a hard to detect bug. I doubt anyone would have guessed this very strange corner case that could happen, much less plan or test for it.

**Comment by hexylena** [comment]
https://github.com/erasche/docker-jasig-cas-proxy now exists as well, to help with testing. Just stick this in front of your galaxy instance and experience life under CAS <s>hell</s>.

**Comment by dannon** [comment]
@erasche I'll try this out today; This might work for the short term, but I'm with you that there should probably be a different solution here.

**Comment by hexylena** [comment]
@dannon thanks!

**Comment by dannon** [comment]
@erasche I haven't been able to reproduce this locally yet, but can you take a look at https://github.com/dannon/galaxy/tree/fix_logout?

I have a hunch that that's what's actually causing your problem, and it may be a cleaner fix.

**Comment by martenson** [comment]
@dannon you mean this commit https://github.com/dannon/galaxy/commit/6c82cf3c22445e97621429591e72951a0941104e ? What was this hack fixed by if so?

**Comment by dannon** [comment]
@martenson Yes, that commit.  The hack should not be necessary at all.

**Comment by martenson** [comment]
@dannon Wanna PR the hack removal then?

**Comment by dannon** [comment]
@martenson That's the plan, just wanted @erasche's word on whether it fixes his problem as an alternative to this PR it before I pursue it more.  (otherwise, if the hack isn't hurting anything, I won't PR against 17.01)

**Comment by martenson** [comment]
We want to remove that hack anyways, right?

**Comment by dannon** [comment]
@martenson Yes, but if it's not a solution to erasche's problem I'm not going to PR against 17.01 for it.

**Comment by hexylena** [comment]
Closing this in favour of @dannon's changes which are a cleaner solution.

**Pull request closed without merging**
