### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by galaxybot**
by running `make update-dependencies`.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@davelopez Any idea about this error?

```
RuntimeError: Cannot update undefined schema for $ref=#/components/schemas/galaxy__schema__notifications__PersonalNotificationCategory-Input__1
```

Traceback in https://github.com/galaxyproject/galaxy/actions/runs/11983603557/job/33413355009?pr=19190 (and others).

**Comment by davelopez** [comment]
Hmmm I've never seen that one before, likely something changed in the new Pydantic version that our custom OpenAPI schema generation, FastAPI schema generation, or a combination of them broke it :thinking: 

https://github.com/galaxyproject/galaxy/blob/1d99e6ddff433c4f006de1483fb09bf8738f7b2f/lib/galaxy/webapps/openapi/utils.py#L69

I'll try to investigate... :mag_right:

**Comment by nsoranzo** [comment]
> Hmmm I've never seen that one before, likely something changed in the new Pydantic version that our custom OpenAPI schema generation, FastAPI schema generation, or a combination of them broke it 🤔
> 
> https://github.com/galaxyproject/galaxy/blob/1d99e6ddff433c4f006de1483fb09bf8738f7b2f/lib/galaxy/webapps/openapi/utils.py#L69
> 
> I'll try to investigate... 🔎

Thanks! :pray:

**Comment by nsoranzo** [comment]
Thanks for looking into this @davelopez !
Let's see if the pydantic issue gets fixed fast, otherwise we can pin it.
In the meantime I still have 280 UP031 errors to fix for the Python linting :laughing:

**Comment by davelopez** [comment]
The pydantic issue should be fixed in https://github.com/pydantic/pydantic/releases/tag/v2.10.3

**Comment by nsoranzo** [comment]
> The pydantic issue should be fixed in https://github.com/pydantic/pydantic/releases/tag/v2.10.3

Yes, I noticed yesterday and already re-run the update process. The previous issue is indeed solved, although we need to update the OpenAPI schemas and fix some type annotation issues due to the new pydantic.

Something else is now breaking the ToolShed tests though (and I am not yet finished fixing the new UP031 errors), so it may be worth to split out the pydantic update and related fixes in a separate PR.

**Review by jdavcs — APPROVED** [review]

**Pull request merged**
