### PR TITLE
[15.10] Log a warning for missing tool whitelist file only if explicitly defined.

### PR DESCRIPTION
**Pull request by nsoranzo**
Also fix the log message.

Otherwise the message will pop up even when executing e.g. `python scripts/cleanup_datasets/cleanup_datasets.py` .

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Don't merge yet, I think this needs an additional tweak.

**Comment by dannon** [comment]
Yeah, this breaks editing of the whitelist in multiprocess mode.  PR incoming.

**Comment by dannon** [comment]
Works now.  +1

**Pull request merged**
