### PR TITLE
Core, CORS: allow (non-preflighted) CORS requests by echoing back the…

### LINKED ISSUE #1029: Send CORS headers
http://caniuse.com/#feat=cors

Where appropriate (primarily API) and test preflight, etc.

Should be able to do this easily for simple GET requests like:
http://dev.list.galaxyproject.org/CORS-requests-to-public-Galaxy-server-td4668094.html

The OPTIONS preflight for (most) POST and PUT requests will take some extra work. OPTIONS throws a 404 for most of our API routes currently.

### PR DESCRIPTION
**Pull request by carlfeberhard**
… origin header if the requesting client is allowed

Fixes #1029

### CODE REVIEW

**Comment by hexylena** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
Looks like a failed TS test

```
Error - <type 'exceptions.AttributeError'>: 'Configuration' object has no attribute 'allowed_origin_hostnames'
URL: http://localhost:8397/
File '/galaxy/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/galaxy/lib/galaxy/web/framework/base.py', line 127 in __call__
  return self.handle_request( environ, start_response )
File '/galaxy/lib/galaxy/web/framework/base.py', line 157 in handle_request
  self.set_cors_headers( trans )
File '/galaxy/lib/galaxy/web/framework/base.py', line 219 in set_cors_headers
  if not trans.app.config.allowed_origin_hostnames:
AttributeError: 'Configuration' object has no attribute 'allowed_origin_hostnames'
```

**Comment by carlfeberhard** [comment]
Not sure what's going on with Travis here. Can't reproduce this locally with tox either. /shrug

**Comment by hexylena** [comment]
Yeah, dunno about travis either, but I'm a bit nervous to break the build for everyone else. 
You have my :+1:, but I'd like a second pair of eyes merging this.

**Comment by hexylena** [comment]
@martenson maybe? You're brave :)

**Comment by jmchilton** [comment]
I imagine the Travis problem is this line in Configuration.

```
        self.new_file_path = resolve_path( kwargs.get( "new_file_path", "database/tmp" ), self.root )
        tempfile.tempdir = self.new_file_path
```

Invoking a Configuration object changes global state of the Python interpreter for all the other unit tests run in. I'd suggest a flag to configuration to disable that for unit tests.

**Comment by carlfeberhard** [comment]
@jmchilton Interesting. Thanks for the info - I'll check it out

**Comment by carlfeberhard** [comment]
That was it. Thanks, @jmchilton

**Comment by jmchilton** [comment]
Awesome sauce, glad that worked out. Thanks @carlfeberhard!

**Pull request merged**
