### PR TITLE
Remove unused and deprecated parameters from k8s runner

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Because I just stumbled over it: could you check if this https://github.com/galaxyproject/galaxy/blob/470031e1564deaed7e67d041b8563f824a52fb3b/lib/galaxy/jobs/runners/kubernetes.py#L272 is still done?

**Comment by mvdbeek** [comment]
@nuwang do you want to get this into 20.05 ?

**Comment by nuwang** [comment]
@bernt-matthias Thanks for pointing that out, that's no longer used either. I'll update the PR.
@mvdbeek Somehow, I missed both the comments on this thread. Sorry about that. Will update the PR for the next release.

**Comment by mvdbeek** [comment]
@nuwang I've rebased this against dev, I'm gonna say let's merge this, unless you think this is not ready ?

**Comment by nuwang** [comment]
@mvdbeek Thanks for rebasing. I think it's good to go!

**Pull request merged**
