### PR TITLE
[23.0] Add script for creating (point) releases

### PR DESCRIPTION
**Pull request by mvdbeek**
Still working on it, but it's minimally useful already.

(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
This is what the dev branch would look like after running `python scripts/release.py --galaxy-root . --new-version 23.0.1 --last-commit v23.0 --no-confirm`  https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:galaxy:dev

https://github.com/galaxyproject/galaxy/commit/1127c24e5edd34bc34a22aee8481c9cf8c5e3395 is what would get tagged (and for which we build packages), https://github.com/galaxyproject/galaxy/commit/104993ca7b186d167fdd507d4302f54c163886bf is what remains on the release branch.

If that's what we want I would add a bunch of tests and start on the CI & automation.

**Review by jmchilton — APPROVED** [review]
I have mixed feelings on the auto-generated histories. I think on balance they are probably good - but it might be worth throwing a note about them being auto-generated and not maintained?

Could we converge with the release monitoring code and skip the same tags and do the same formatting (stripping the [23.0] in the prefix for instance). I know we don't curate the release notes as aggressively as we used to... but it would be nice to say have a map from PRs to Markdown/RST descriptions so we could do curation across release notes and the histories here. The map could also allow us to merge similar PRs, skip PRs, etc... across artifacts. I would love it - but I know some people prefer a less curated set of notes.

**Review by jmchilton — APPROVED** [review]
I have mixed feelings on the auto-generated histories. I think on balance they are probably good - but it might be worth throwing a note about them being auto-generated and not maintained?

Could we converge with the release monitoring code and skip the same tags and do the same formatting (stripping the [23.0] in the prefix for instance). I know we don't curate the release notes as aggressively as we used to... but it would be nice to say have a map from PRs to Markdown/RST descriptions so we could do curation across release notes and the histories here. The map could also allow us to merge similar PRs, skip PRs, etc... across artifacts. I would love it - but I know some people prefer a less curated set of notes.

**Review by jmchilton — APPROVED** [review]
I have mixed feelings on the auto-generated histories. I think on balance they are probably good - but it might be worth throwing a note about them being auto-generated and not maintained?

Could we converge with the release monitoring code and skip the same tags and do the same formatting (stripping the [23.0] in the prefix for instance). I know we don't curate the release notes as aggressively as we used to... but it would be nice to say have a map from PRs to Markdown/RST descriptions so we could do curation across release notes and the histories here. The map could also allow us to merge similar PRs, skip PRs, etc... across artifacts. I would love it - but I know some people prefer a less curated set of notes.

**Review by jmchilton — APPROVED** [review]
I have mixed feelings on the auto-generated histories. I think on balance they are probably good - but it might be worth throwing a note about them being auto-generated and not maintained?

Could we converge with the release monitoring code and skip the same tags and do the same formatting (stripping the [23.0] in the prefix for instance). I know we don't curate the release notes as aggressively as we used to... but it would be nice to say have a map from PRs to Markdown/RST descriptions so we could do curation across release notes and the histories here. The map could also allow us to merge similar PRs, skip PRs, etc... across artifacts. I would love it - but I know some people prefer a less curated set of notes.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:dev_release_bump?expand=1 is another attempt with the current version. This follows the classification that bootstrap_history.py does, with the difference that the categories are "Bug fixes", "Enhancements" and "Other Changes". https://github.com/galaxyproject/galaxy/commit/37d7941556629d7b567983c898e8ba9a1ea2955e is an example of how the changelog looks like.

**Comment by mvdbeek** [comment]
Alright, I think the script portion is done. What I’m envisioning is that either someone manually creates and curates a point release or uses a slash command to do the same (essentially running `python scripts/release.py create-release --galaxy-root . --new-version 23.0.1 --last-commit v23.0 --no-confirm`). The tags, branch (and branches that needed forward merging) get pushed (as part of the script or manually). If the tag and the branches looks good we create an actual release on github. That triggers a workflow that checks out the tag, builds the artifacts and publishes the artifacts associated with the tag (`python scripts/release.py build-and-upload`).

All of this is step-wise, so if anything goes wrong you can re-do things at any point prior to uploading the actual packages.

**Comment by mvdbeek** [comment]
I've added a publish artifacts workflow that uploads to https://test.pypi.org/ when creating a github prerelease and to https://pypi.org/ when creating a release. You can see this in action at https://github.com/mvdbeek/galaxy/actions/runs/5102745991/jobs/9172493938 (my account doesn't have permissions to upload to galaxyproject test packages on pypi). I think this is a good starting point. The package release process is the following now:

- Make sure merge forward is clean (script will abort of that's not the case)
- `GITHUB_AUTH=$GITHUB_PAT python scripts/release.py create-release --new-version 23.0.1 --last-commit v23.0`
  - That will
    -  find all PRs that went into a package since the tag "v23.0" had been created
    - write changelog entries
    - bump package and version.py versions
    - in interactive mode (without `--no-confirm`) the changes are shown.
      - review the changes, maybe abort and fix PR titles if necessary
      - you can curate the changelogs some more if you like, just stage the changes and they will be included
    - commit and tag changes
    - create a .dev0 version entry and merge it forward to newer branches
    - push to github (git utl is configurable with `--upstream`)
    - before each action a confirm dialog asks you if you really want to do it
- If you're happy with everything, go to the release tab on github, select the newly created tag and create a pre-release form it. That will build packages and upload them to test.pypi.org
- Augment that to a release and packages will be uploaded to https://pypi.org/

**Comment by jmchilton** [comment]
```
python scripts/release.py create-release --new-version 23.0.1 --last-commit v23.0
Making sure galaxy clone at '/Users/jxc755/workspace/galaxy' is clean
Current Galaxy version is 23.0.1.dev0, will create new version 23.0.1
Does this look correct? [y/N]: y
Making sure that merging forward will result in clean merges
Updating files: 100% (1089/1089), done.
Switched to branch 'dev'
Auto-merging test/functional/tools/sample_tool_conf.xml
Auto-merging templates/webapps/reports/base_panels.mako
CONFLICT (content): Merge conflict in templates/webapps/reports/base_panels.mako
Auto-merging templates/base/base_panels.mako
CONFLICT (content): Merge conflict in templates/base/base_panels.mako
Auto-merging pyproject.toml
Auto-merging lib/galaxy_test/selenium/test_tool_form.py
Auto-merging lib/galaxy_test/selenium/test_collection_edit.py
Auto-merging lib/galaxy_test/base/populators.py
CONFLICT (content): Merge conflict in lib/galaxy_test/base/populators.py
Auto-merging lib/galaxy_test/api/test_history_contents.py
Auto-merging lib/galaxy_test/api/test_histories.py
Auto-merging lib/galaxy_test/api/test_dataset_collections.py
Auto-merging lib/galaxy/webapps/galaxy/services/history_contents.py
Auto-merging lib/galaxy/webapps/galaxy/fast_app.py
Auto-merging lib/galaxy/webapps/galaxy/controllers/workflow.py
Auto-merging lib/galaxy/webapps/galaxy/controllers/visualization.py
Auto-merging lib/galaxy/webapps/galaxy/controllers/history.py
Auto-merging lib/galaxy/webapps/galaxy/controllers/dataset.py
Auto-merging lib/galaxy/webapps/galaxy/controllers/authnz.py
Auto-merging lib/galaxy/tools/__init__.py
Auto-merging lib/galaxy/tool_util/verify/asserts/__init__.py
Auto-merging lib/galaxy/tool_util/deps/mulled/util.py
CONFLICT (content): Merge conflict in lib/galaxy/tool_util/deps/mulled/util.py
Auto-merging lib/galaxy/tool_util/deps/mulled/mulled_build.py
Auto-merging lib/galaxy/tool_util/deps/conda_util.py
Auto-merging lib/galaxy/selenium/navigates_galaxy.py
Auto-merging lib/galaxy/schema/schema.py
Auto-merging lib/galaxy/model/security.py
Auto-merging lib/galaxy/model/migrations/util.py
CONFLICT (content): Merge conflict in lib/galaxy/model/migrations/util.py
Auto-merging lib/galaxy/model/__init__.py
Auto-merging lib/galaxy/managers/history_contents.py
Auto-merging lib/galaxy/managers/hdas.py
Auto-merging lib/galaxy/managers/base.py
Auto-merging lib/galaxy/jobs/handler.py
Auto-merging lib/galaxy/dependencies/pinned-requirements.txt
CONFLICT (content): Merge conflict in lib/galaxy/dependencies/pinned-requirements.txt
Auto-merging lib/galaxy/dependencies/dev-requirements.txt
Auto-merging lib/galaxy/dependencies/conditional-requirements.txt
Auto-merging lib/galaxy/dependencies/__init__.py
Auto-merging lib/galaxy/datatypes/interval.py
CONFLICT (content): Merge conflict in lib/galaxy/datatypes/interval.py
Auto-merging lib/galaxy/datatypes/genetics.py
CONFLICT (content): Merge conflict in lib/galaxy/datatypes/genetics.py
Auto-merging lib/galaxy/datatypes/data.py
CONFLICT (content): Merge conflict in lib/galaxy/datatypes/data.py
Auto-merging lib/galaxy/datatypes/binary.py
Auto-merging lib/galaxy/celery/tasks.py
Auto-merging client/tsconfig.webpack.json
CONFLICT (content): Merge conflict in client/tsconfig.webpack.json
CONFLICT (modify/delete): client/tests/qunit/tests/ui_tests.js deleted in HEAD and modified in release_23.0. Version release_23.0 of client/tests/qunit/tests/ui_tests.js left in tree.
Auto-merging client/src/utils/navigation/navigation.yml
Auto-merging client/src/stores/workflowStepStore.ts
Auto-merging client/src/stores/workflowEditorStateStore.ts
CONFLICT (content): Merge conflict in client/src/stores/workflowEditorStateStore.ts
Auto-merging client/src/schema/schema.ts
Auto-merging client/src/mvc/ui/ui-select-content.js
Auto-merging client/src/components/Workflow/WorkflowList.vue
Auto-merging client/src/components/Workflow/Editor/modules/terminals.ts
Removing client/src/components/Workflow/Editor/composables/useCoordinatePosition.ts
Auto-merging client/src/components/Workflow/Editor/WorkflowGraph.vue
CONFLICT (modify/delete): client/src/components/Workflow/Editor/TerminalConnector.vue deleted in release_23.0 and modified in HEAD. Version HEAD of client/src/components/Workflow/Editor/TerminalConnector.vue left in tree.
Auto-merging client/src/components/Workflow/Editor/NodeOutput.vue
CONFLICT (content): Merge conflict in client/src/components/Workflow/Editor/NodeOutput.vue
Auto-merging client/src/components/Workflow/Editor/NodeOutput.test.ts
Auto-merging client/src/components/Workflow/Editor/Node.vue
CONFLICT (content): Merge conflict in client/src/components/Workflow/Editor/Node.vue
Removing client/src/components/Workflow/Editor/Connector.vue
Auto-merging client/src/components/Visualizations/Tabular/TabularChunkedView.vue
Auto-merging client/src/components/Tool/ToolForm.vue
CONFLICT (content): Merge conflict in client/src/components/Tool/ToolForm.vue
Auto-merging client/src/components/Panels/utilities.test.js
CONFLICT (content): Merge conflict in client/src/components/Panels/utilities.test.js
Auto-merging client/src/components/Panels/utilities.js
Auto-merging client/src/components/Panels/ToolBoxWorkflow.vue
Auto-merging client/src/components/Panels/ToolBox.vue
Auto-merging client/src/components/History/HistoryPublishedList.vue
Auto-merging client/src/components/History/Export/HistoryExport.test.ts
Auto-merging client/src/components/History/CurrentHistory/HistoryOperations/SelectionOperations.vue
Auto-merging client/src/components/History/Content/GenericItem.vue
CONFLICT (content): Merge conflict in client/src/components/History/Content/GenericItem.vue
Auto-merging client/src/components/History/Content/Dataset/DatasetActions.vue
Auto-merging client/src/components/Form/FormElement.vue
Auto-merging client/src/components/Form/FormDisplay.vue
Auto-merging client/src/components/Collections/common/CollectionEditView.vue
Auto-merging .github/workflows/unit-postgres.yaml
Auto-merging .github/workflows/integration.yaml
Automatic merge failed; fix conflicts and then commit the result.
Merge conflicts occurred while attempting to merge branch release_23.0 into dev. You should resolve conflicts and try again.
Continue anyway ? [y/N]: n
```

Seems cool so far - I'll try to do a merge and try again.

**Comment by jmchilton** [comment]
@mvdbeek So this failed (I think) because my local dev branch was not updated against the remote - do you think that is something we should check for or is there a downside to that? It seems like this would be a lot safer if we did that but it adds some complexity. If there is some downside - I'll just update the exception message there to add that this should be checked for.

**Comment by mvdbeek** [comment]
> do you think that is something we should check for or is there a downside to that?

I think that would be fine for finer-grained error messages, though I guess the conclusion would be similar; make sure branches are clean, updated and ideally merged forward. If we can check against the upstream url I think that would be a good idea.

> dev though... updated in https://github.com/galaxyproject/galaxy/pull/15844.

Should we backport that ? I think a medium-term thing we should do eventually is maybe pushing the release scripts into their own package

**Pull request merged**
