### PR TITLE
Webhook plugin: tool_list

### PR DESCRIPTION
**Pull request by blankclemens**
Add a webhook plugin at masthead which creates a list of installed toolshed tools on this instance in YAML format. Users can then use it to create their own Galaxy instance or Galaxy Docker flavour based on the same tools.

### CODE REVIEW

**Comment by jmchilton** [comment]
I have no particular objection to merging this since it is optional - but if this is useful don't you think it should just be available in the admin menu somewhere?

**Comment by blankclemens** [comment]
While it can be useful for admins as well, the initial thought was to provide it to non admin users. But I agree, thematically I would rather put it in some kind of "server information" page or likewise, e.g. something inside the user preferences (admin interface would fit better, but that again is restricted to admins).

I'd be willing to look into that if there are suggestions on where to put it (and how to present it).

**Comment by mvdbeek** [comment]
> While it can be useful for admins as well, the initial thought was to provide it to non admin users.

I agree with you, and this information is already available to non-admin users with a GET to api/tools.
We could probably work a bit on the formatting and the output style of the API so that you would just need to GET to api/tools.

Given that the webhooks are nicely isolated I'm happy to merge this.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by martenson** [comment]
Thank you for the contribution @blankclemens !

**Comment by blankclemens** [comment]
Thanks @martenson , although it's the smallest possible start I guess.. but it's a start ;)

**Pull request merged**
