### PR TITLE
[15.10] propagate the of fix failing casperjs tests (original was in #952)

### PR DESCRIPTION
**Pull request by martenson**
xref #952

### CODE REVIEW

**Comment by martenson** [comment]
hmm so this seems to not fix the casperjs @carlfeberhard 
back to not nowing why it passes in dev and not in 15.10

**Comment by martenson** [comment]
this is the diff of that file in between dev and 15.10 (green)

``` diff
--- from_file
+++ /Users/marten/devel/git/galaxy/test/docker/base/run_test_wrapper.sh
@@ -6,46 +6,32 @@
 then
     su -c '/usr/lib/postgresql/9.3/bin/pg_ctl -o "-F" start -D /opt/galaxy/db' postgres
     sleep 3
-    GALAXY_TEST_INSTALL_DB_MERGED="true"
-    GALAXY_TEST_DBURI="postgres://root@localhost:5930/galaxy?client_encoding=utf8"
-    TOOL_SHED_TEST_DBURI="postgres://root@localhost:5930/toolshed"
+    GALAXY_TEST_DBURI="postgres://root@localhost:5930/galaxy"
 elif [ "$GALAXY_TEST_DATABASE_TYPE" = "mysql" ];
 then
     sh /opt/galaxy/start_mysql.sh
-    GALAXY_TEST_INSTALL_DB_MERGED="true"
     GALAXY_TEST_DBURI="mysql://galaxy:galaxy@localhost/galaxy?unix_socket=/var/run/mysqld/mysqld.sock"
-    TOOL_SHED_TEST_DBURI="mysql://galaxy:galaxy@localhost/toolshed?unix_socket=/var/run/mysqld/mysqld.sock"
 elif [ "$GALAXY_TEST_DATABASE_TYPE" = "sqlite" ];
 then
-    GALAXY_TEST_INSTALL_DB_MERGED="true"
     GALAXY_TEST_DBURI="sqlite:////opt/galaxy/galaxy.sqlite"
-    TOOL_SHED_TEST_DBURI="sqlite:////opt/galaxy/toolshed.sqlite"
 else
-  echo "Unknown database type"
-  exit 1
+ echo "Unknown database type"
+ exit 1
 fi
 export GALAXY_TEST_DBURI
-export TOOL_SHED_TEST_DBURI
-export GALAXY_TEST_INSTALL_DB_MERGED

 cd /galaxy
 GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION="$GALAXY_TEST_DBURI";
 export GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION

-./scripts/common_startup.sh || { echo "common_startup.sh failed"; exit 1; }
-
-dev_requirements=./lib/galaxy/dependencies/dev-requirements.txt
-[ -f $dev_requirements ] && ./.venv/bin/pip install -r $dev_requirements
-
 sh manage_db.sh upgrade

 if [ -z "$GALAXY_NO_TESTS" ];
 then
-    sh run_tests.sh --skip-common-startup $@
+    sh run_tests.sh $@
 else
     GALAXY_CONFIG_MASTER_API_KEY=${GALAXY_CONFIG_MASTER_API_KEY:-"testmasterapikey"}
     GALAXY_CONFIG_FILE=${GALAXY_CONFIG_FILE:-config/galaxy.ini.sample}
-    TOOL_SHED_CONFIG_FILE=${GALAXY_CONFIG_FILE:-config/tool_shed.ini.sample}
     GALAXY_CONFIG_CHECK_MIGRATE_TOOLS=false
     if [ -z "$GALAXY_MULTI_PROCESS" ];
     then
@@ -58,7 +44,6 @@

     export GALAXY_CONFIG_MASTER_API_KEY
     export GALAXY_CONFIG_FILE
-    export TOOL_SHED_CONFIG_FILE
     export GALAXY_CONFIG_CHECK_MIGRATE_TOOLS
     export GALAXY_CONFIG_JOB_CONFIG_FILE
     export GALAXY_CONFIG_FILE_PATH
```

**Comment by carlfeberhard** [comment]
I would say just drop the casper tests for 15.10?

**Comment by jmchilton** [comment]
@martenson Are you sure this didn't help, this would require a new Docker build and tag to take affect right?

That said, I'm not sure it is worth the effort as long as it is working now.

**Comment by martenson** [comment]
@jmchilton hmm, you are right, I did not realize this piece is in the docker image. It would be nice to know this fix is correct. If we dont track it we won't know what it was for future reference,

**Comment by martenson** [comment]
closing, I think this is the correct fix but the overhead of updating repo, rebuilding test image, and running tests - all this for 15.10 - is too much for the small gain

**Pull request closed without merging**
