### PR TITLE
[17.05] Improve resilience of tool url building

### PR DESCRIPTION
**Pull request by guerler**
Attempt to fix the issue described in #4211 by improving the resilience of the tool url building.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
That works for me. Did you manage to figure out why `Galaxy.params` is empty sometimes?

**Comment by guerler** [comment]
Not in a particular case but in principal it is possible that no url parameters are send when requesting an initial tool model. Changing the version in a consecutive request would build a new url without actually specifying the `tool_version`. Thanks a lot for identifying this issue and helping to resolve it.

**Comment by mvdbeek** [comment]
With a498390 you're also addressing https://github.com/galaxyproject/galaxy/issues/1729 right?
Absolutely awesome!!!

**Comment by mvdbeek** [comment]
Hmm, so in it's current state you can click on rerun for an existing dataset and it does change the version, but the initial parameters are not conserved ... which is fine as a bug fix, I think this is how it used to be.

**Comment by guerler** [comment]
Sorry, but yes, this is just a fix, restoring the previous behavior.

**Comment by martenson** [comment]
Thanks to both of you. This closes https://github.com/galaxyproject/galaxy/issues/4097 right?

**Pull request merged**
