### PR TITLE
Fix datalib search pagination

### LINKED ISSUE #2188: libraries search takes into account pagination
which is incorrect because it should take you to the first page of search results

### PR DESCRIPTION
**Pull request by martenson**
and remove some cruft code I saw

fixes #2188

### CODE REVIEW

**Comment by martenson** [comment]
rebased, the tests passed previously

**Comment by anuprulez** [comment]
We can remove these three library imports in file (`client/galaxy/scripts/mvc/library/library-librarylist-view.js`)
```
 mod_masthead,
 mod_baseMVC,
 mod_utils
```
although they are unrelated to your changes. I think they are not being used anymore.

**Comment by martenson** [comment]
@anuprulez I incorporated the request and rebased

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
