### PR TITLE
Remove page create/edit form mako

### PR DESCRIPTION
**Pull request by guerler**
Branched from and analogous to #4682. Removes page create/edit form mako and uses client-side form builder instead.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by dannon** [comment]
This was actually merged manually to resolve conflicts; it just isn't showing up right on github due to the extra merges here.

**Pull request closed without merging**
