### PR TITLE
Smart string handling on the wsgi response -- this fixes uwsgi blanki…

### PR DESCRIPTION
**Pull request by dannon**
…ng out when handling endpoints that return unicode.

This would prevent problems like seen with #2628

### CODE REVIEW

**Comment by dannon** [comment]
(might be pushing one more commit to handle iterables that need encoding post-flattening)

**Comment by nsoranzo** [comment]
If you add that commit, it may be better to include the call to `smart_str()` inside `flatten()`, since it is a generator and it is used only by the `make_body_iterable()` method.

**Comment by dannon** [comment]
@nsoranzo yep.  still waiting on tests to find locations :)

**Comment by dannon** [comment]
@nsoranzo Should work now.  Like I mentioned on IRC, I added a few dummy endpoints with iterable garbage to test that it packs and ships correctly, and it does, even though I never did run across a 'live' endpoint that uses this functionality.

In any event, strings coming from the webapp would need to be non-unicode, and this should prevent further errors like #2628 from happening.

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by blankenberg** [comment]
@galaxybot test this

**Comment by martenson** [comment]
The failed tests are probably Jenkins running out of memory. :/ I need to lower the number of workers.

edit: I have lowered the number of executors from 8 to 5. Hope it helps.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
api and framework tests pass locally, let's give Jenkins this last chance before merging.

**Pull request merged**
