### PR TITLE
[17.09] Backbone routing slashes fix

### PR DESCRIPTION
**Pull request by dannon**
This fixes https://github.com/galaxyproject/galaxy/issues/4490

The problem was that the backbone router strips trailing slashes from urls *always*.  This causes the relative image links from toolshed-installed tools (and potentially other stuff?) to fail to load correctly.  All URLs in galaxy handle the trailing slash just fine, so this patch removes the stripping from Backbone.

Warning, when moving this upstream, it'll take a little more legwork (separate PR, these changes will do nothing -- I'll follow up). 

That said, I'm working towards dropping backbone router entirely, anyway, so this just hacks the bug (at least for our usage) out of it on our side for this past release.  This fix is a bit of a hack, but I couldn't get backbone to cooperate with what I wanted it to do otherwise, and we're dropping it anyway.

### CODE REVIEW

**Comment by pjbriggs** [comment]
This issue is fixed for us when these changes are manually applied to our local Galaxy instances running the `release_17.09` branch and using `proxy-prefix` - thanks @dannon!

**Comment by martenson** [comment]
I have reservations against this approach but am unable to reproduce the problem to help fixing it, details: https://github.com/galaxyproject/galaxy/issues/4490#issuecomment-352836056

**Comment by dannon** [comment]
@martenson Sorry you're having trouble reproducing the problem.  I see in that issue you set
```
[filter:proxy-prefix]
prefix = /galaxy
```
But did you set the following:
```
filter-with = proxy-prefix
```
(and probably the `cookie_path` bit, too)

What's the exact URL shown in your browser when looking at the tool?

Edit: And, I guess I should ask, what exactly are your reservations?

**Comment by martenson** [comment]
@dannon yeah, that is the default

```
[app:main]
filter-with = proxy-prefix
```

the url:
`http://127.0.0.1:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fintersect%2Fgops_intersect_1%2F1.0.0&version=1.0.0&__identifer=yi3sfbsqunp`

My reservations are that given we control all parts of the problem we shouldn't be modifying our dependencies for a fix.

**Comment by dannon** [comment]
@martenson You're still hitting 8080, skipping nginx?

**Comment by martenson** [comment]
my nginx is on 8080, damn it might be some other Galaxy instance responding to me, will check later and report here

**Comment by dannon** [comment]
Weird, sounds like you have some debugging to do on your side, there.

Anyway, ideally backbone would be configurable in leaving the trailing slash on or not, but it is not.  It just does not work in a way that was compatible with the existing Galaxy infra in this sense -- we expect (and handle correctly) trailing slashes at routing endpoints, and we leverage that to serve relative images in toolshed-installed tool help (and potentially other places?).

IMO, we can jump through hoops to try to fix it in some other way (though I don't currently see a good way to do this), or we can patch Backbone as I have done here, until it's phased out.  Backbone's last release was ~~18~~ 20 (older than I remembered...) months ago, so this isn't something we're going to have to redo anytime soon.  It's dead.  To me, it seems like a waste of time to pursue a more invasive fix to Galaxy to work around a backbone bug, especially considering this is a (relatively low-impact) bug report that has been open for many months during which nobody else has tried to look at it.

**Comment by martenson** [comment]
This PR does not fix the issue for me with
```
[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
prefix = /galaxy

[app:main]
filter-with = proxy-prefix
```

and

```
    upstream galaxy_app {
        server localhost:8088;
    }
    server {
        listen       8080;
        server_name  localhost;
        location /galaxy {
            proxy_pass http://galaxy_app;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

screenshot 2017-12-20 12 21 32

**Comment by dannon** [comment]
It looks to me like you've manually put in a broken url instead of using navigation, which generates the correct links.  This PR fixes backbone routing, which you are intentionally (?) bypassing.  Edit: I've moved on to other work.  I maintain that the right fix is what is in this PR and am sad about the bandaid in the other one, but I'm moving on.

**Pull request closed without merging**
