### PR TITLE
[21.01] Add HHR datatype

### PR DESCRIPTION
**Pull request by bgruening**
## What did you do? 
- adding a new datatype called HRR as simply subclass of text

## Why did you make this change?

Needed by @guerler workflows.

## How to test the changes? 

Look at the upload tool if you can select an hrr datatype during upload.

### CODE REVIEW

**Comment by bgruening** [comment]
@guerler do you have any link or formal description of this datatype that we can add?

**Comment by guerler** [comment]
Should this be targeting dev?

**Review by guerler — APPROVED** [review]

**Comment by bgruening** [comment]
I think we have an exception for simply datatypes and you need this on 21.01, isn't it? We could also backport it. I can also target dev.

**Comment by nsoranzo** [comment]
21.01 is fine, I've amended the PR title.

**Comment by bgruening** [comment]
Thanks @nsoranzo! Ok to merge?

**Pull request merged**
