### PR TITLE
add slash command to trigger IUC CI

### PR DESCRIPTION
**Pull request by bernt-matthias**
in conjunction with https://github.com/galaxyproject/tools-iuc/pull/3298

### CODE REVIEW

**Comment by mvdbeek** [comment]
I think having just the tools-iuc repo listen is probably enough ? The permissions needed to do this are pretty wide unfortunately.

**Comment by bernt-matthias** [comment]
> I think having just the tools-iuc repo listen is probably enough ?

Guess so.

**Comment by bernt-matthias** [comment]
> I think having just the tools-iuc repo listen is probably enough ? The permissions needed to do this are pretty wide unfortunately.

https://github.com/peter-evans/slash-command-dispatch#token "f you will be dispatching commands to public repositories only then you can use the more limited public_repo scope." .. not sure yet what that means - but sounds helpful

**Comment by mvdbeek** [comment]
We can add this at any point, so I dropped the milestone here.

**Pull request closed without merging**
