### PR TITLE
Merge forward release_20.09

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix merge conflict due https://github.com/galaxyproject/galaxy/pull/10652

### CODE REVIEW

**Comment by nsoranzo** [comment]
Ping @OlegZharkov

**Review by mvdbeek — APPROVED** [review]

**Comment by OlegZharkov** [comment]
@nsoranzo ah, right, it's that `if` condition. Sorry, I forgot that I fixed it already in https://github.com/galaxyproject/galaxy/pull/10557/files#diff-421675cbac7b46f4d74385828695ff4695b8bd2fa27ccb82fa5d435123e9e46fR232

But it's not that big I guess. it's the same like 

```
if (this.metadata.full_path)
=============================
if (this.metadata.full_path)
```

**Comment by nsoranzo** [comment]
OlegZharkov No, the conflict was on slightly different implementation of `dataset_manipulation` and `logged_dataset_manipulation` .

**Comment by OlegZharkov** [comment]
> slightly different implementation

no way. So I just tried this:
```
git checkout dev
git merge release_20.09
```

I am getting 2 conflicts in ```.github/workflows/lint.yaml``` and `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue`

So the conflict in `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue` is just removing the comment:
```
<<<<<<< HEAD
=======
        // logic from legacy code
>>>>>>> release_20.09
```

Am I doing something wrong? maybe I am looking at the wrong place....

**Comment by nsoranzo** [comment]
> > slightly different implementation
> 
> no way. So I just tried this:
> 
> ```
> git checkout dev
> git merge release_20.09
> ```
> 
> I am getting 2 conflicts in `.github/workflows/lint.yaml` and `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue`
> 
> So the conflict in `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue` is just removing the comment:
> 
> ```
> <<<<<<< HEAD
> =======
>         // logic from legacy code
> >>>>>>> release_20.09
> ```
> 
> Am I doing something wrong? maybe I am looking at the wrong place....

That's correct, but if you look at the merged `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue` you will see there are 2 implementations of the methods I mentioned above.

**Comment by OlegZharkov** [comment]
> > > slightly different implementation
> > 
> > 
> > no way. So I just tried this:
> > ```
> > git checkout dev
> > git merge release_20.09
> > ```
> > 
> > 
> > I am getting 2 conflicts in `.github/workflows/lint.yaml` and `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue`
> > So the conflict in `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue` is just removing the comment:
> > ```
> > <<<<<<< HEAD
> > =======
> >         // logic from legacy code
> > >>>>>>> release_20.09
> > ```
> > 
> > 
> > Am I doing something wrong? maybe I am looking at the wrong place....
> 
> That's correct, but if you look at the merged `client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue` you will see there are 2 implementations of the methods I mentioned above.

you're right. I was actually looking at the wrong place. 
it looks like I did it with https://github.com/galaxyproject/galaxy/commit/dd4a11cde30263380075bff0e9f059364d2fbeb1 in https://github.com/galaxyproject/galaxy/pull/10204 and forgot about it.

Thanks a lot for noticing it!
Could you keep the original implementation, please? The one from dev, where `contains_file_or_folder` is a separate value in computed

**Comment by nsoranzo** [comment]
Sure, I'll switch them now.

**Review by OlegZharkov — APPROVED** [review]
well, we can consider it as backporting a few fixes from https://github.com/galaxyproject/galaxy/pull/10204
:)

**Pull request merged**
