### PR TITLE
[release_13.01] Ancient bug.

### PR DESCRIPTION
**Pull request by hexylena**
Please merge all the way to dev.

### CODE REVIEW

**Review by martenson — APPROVED** [review]

**Comment by blankenberg** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@blankenberg 13.01 won't pass anything I bet

**Comment by blankenberg** [comment]
output from tests:
```
/tmp/hudson6938148352160112651.sh: line 3: ./run_tests.sh: No such file or directory
Build step 'Execute shell' marked build as failure
```
test script didn't exist in 13.01

**Comment by blankenberg** [comment]
Was this tested manually: does `escape` exist? It is imported from `markupsafe` in later revs, but with all those `import *`s its hard to see.

**Comment by martenson** [comment]
@blankenberg good point, I did not test this on 13.01

**Comment by jmchilton** [comment]
13.01 has hundreds of known XSS vulnerabilities.

**Comment by martenson** [comment]
After an email discussion I think better target is 16.04, the new PR is linked above.

**Pull request closed without merging**
