### PR TITLE
[15.10] Update Kombu and AMQP eggs to fix problems with El Capitan's System Integrity Protection

### PR DESCRIPTION
**Pull request by natefoo**
As reported in [Biostar](https://biostar.usegalaxy.org/p/14492/) and by @gregvonkuster. New eggs are on https://eggs.galaxyproject.org/

This won't be mergeable to dev, I'll create a separate PR there updating the wheels.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
API tests for this seem stuck
https://jenkins.galaxyproject.org/job/docker-api/1559/console

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
@galaxybot test this

Just cleaned out ~60 stuck containers on the Jenkins server, so hopefully things won't time out this time.

**Comment by martenson** [comment]
thanks Obama

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Dunno what's up with the testing framework, but I verified the new eggs work fine locally on el cap for me.  +1 and merging.

**Comment by martenson** [comment]
@dannon the error we are solving does not hit every el capitan, only a subset (I suspect very new laptops). The testing framework in 15.10 does not include the timeout fixes so that is why some API tests were failing on timeout.

I would prefer to not have this issue closed 4 minutes after I restarted the tests too.

**Comment by dannon** [comment]
@martenson I talked to Wolfgang a while ago about this and already understand the intricacies of which versions it affects, but thanks.  The failing tests are completely unrelated and it doesn't make any sense to keep rerunning them and waiting.  I tested against the built-in el-cap python, which it affected.

**Comment by dannon** [comment]
@martenson Followup question -- the testing framework isn't even _running_ el cap or osx at all, anyway, is it?

Unless it is, why would the results from that even be relevant to this particular PR, other than verifying that the updated eggs didn't break arbitrary linux installs (which they did not, and which I also tested manually)?

**Comment by martenson** [comment]
I do not know who Wolfgang is but this issue seemed to be untouched since it was reported 8 weeks ago at https://biostar.usegalaxy.org/p/14492/ 

And yes, the tests were for general running of Galaxy on Jenkins' Linux with the new wheels.

**Comment by dannon** [comment]
Wolfgang is the guy from the thread you just linked who sorted out what the problem was and posted a temporary workaround, until new eggs could be rolled with the (now available, not when he first posted) new versions of amqp/etc.

In any event, didn't want to step on any toes.  IMO, especially with Jenkins false negatives being fairly pervasive, it's perfectly reasonable (and honestly, I prefer it, really) to test locally and merge based off that.

**Comment by natefoo** [comment]
Changing the versions of these two deps would affect Galaxy running on any platform, which is why I was hoping tests would pass (but granted, I don't expect anything to break since we don't use kombu/amqp heavily and use them in a pretty standard way).

**Pull request merged**
