### PR TITLE
Fix for ToolShed not having config.shed_tool_data_path

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by natefoo** [comment]
How far does this go back and what does it break?

**Comment by blankenberg** [comment]
Not sure if there are additional previous issues, but it fixes an issue seen with the tests on 15.03 and dev post #3

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/Og1WxqSA) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/6.patch) for testing.

**Comment by natefoo** [comment]
+1

**Pull request merged**
