### PR TITLE
[17.05] conditional postclick execution onNext

### PR DESCRIPTION
**Pull request by bagnacan**
backport of #4062

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
ping @dannon

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
@bgruening Missed the ping.  I approve, but we need one more.  I'm happy to merge/rebuild as necessary though, as soon as we get it.

**Comment by bgruening** [comment]
@dannon now you have the second one. Thanks.

**Comment by martenson** [comment]
Thank you @bagnacan !

**Pull request merged**
