### PR TITLE
(WIP) Add support for the ideaspre datatype

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Is there something I need to do regarding the broken selenium tests?

**Comment by martenson** [comment]
@gregvonkuster I don't think so.

**Comment by gregvonkuster** [comment]
@davebx @martenson @natefoo This IdeasPre datatype is needed for the IDEAS tools I'm building (currently located here https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/epigenetics)  for @yuzhang123.  @nekrut has agreed with @yuzhang123 to host these tools on both Galaxy test (during tool development) and ultimately Galaxy main.

I'm getting close to having the first pass of the tools finished, but @yuzhang123 has not been able to work with them since we cannot get them installed on Galaxy test for 2 reasons: 1) this PR needs to be merged and Galaxy test updated with it, and 2) the issues with updating tools on Galaxy test need to be resolved so that the latest versions of these tools can be installed there.  Please let me know if there is anything I can do to help with either of these issues.

When we are finished with the development phase for these tools, I'll likely move them to the tools-iuc repo so that they can be installed on Galaxy main.  My understanding is that in order for a tool to be allowed on Galaxy main, the tool must be housed in the tools-iuc repo.  Please let me know if this is not actually a requirement.

Thanks everyone!  ;)

**Comment by natefoo** [comment]
Tools are installable on Test now. This PR looks good to me but I am the last person who would know the standards for datatypes.

**Comment by gregvonkuster** [comment]
Thanks a bunch @natefoo ;)

**Comment by gregvonkuster** [comment]
Ping @martenson

**Comment by gregvonkuster** [comment]
Added WIP to label since I just discovered I need at least another function (generate_primary_file).  I'm working on a functional test for a tool that uses this datatype, so when I get that to pass, I'll add another commit here and change the label.

**Comment by gregvonkuster** [comment]
Unfortunately a functional test cannot be written to handle this datatype as input, so I'll close this PR.  This is unfortunate because the datatype works very well for the tools, but the Galaxy functional test framework uses the upload tool to upload the dataset for testing, and Html datasets that contain associated files in the extra_files_path cannot be uploaded.  I've spent some time changing the dataset to be a composite datatype (subclassed Rgenetics), but it turns out composite datatypes cannot have an unknown number of associated files in the extra_files_path.  The base names are not required to be known, but the number of files is, and my tool produces an unknown number of files.  :(

**Comment by martenson** [comment]
I think we should adapt Galaxy so this is possible.

also from gitter, @mvdbeek:

>shouldn't the downstream tool just accept any number of bed (or subclass of bed) files ? That would be testable.

**Comment by gregvonkuster** [comment]
I may be missing a new planemo feature, so please let me know if I am.  I think the issue here is planemo test requiring the use of the upload tool for testing a tool.  I've added an issue here: https://github.com/galaxyproject/planemo/issues/760.

**Pull request closed without merging**
