### PR TITLE
Migrate Libraries API (top level) to FastAPI

### PR DESCRIPTION
**Pull request by davelopez**
## What did you do? 
- Create pydantic models for all parameters and responses.
- Include legacy pydantic models for backward compatibility.
- Annotate types in the service class for parameters and return values.
- Add FastAPI router with all the relevant endpoints.
- Fixed a permission check that allowed unauthorized users to create folders in a library https://github.com/galaxyproject/galaxy/commit/80a8e4d0dd3f3c0cb1b2e8f42ed38c998f7fdabf.

## Why did you make this change?
This is part of the FastAPI migration process, see xref #10889

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Launch Galaxy using uvicorn: `uvicorn --app-dir lib --factory galaxy.webapps.galaxy.fast_factory:factory`
  2. Go to `http://localhost:8080/api/docs#/libraries`
  3. Use the interactive documentation to manually test the API calls

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

## For UI Components
image

### CODE REVIEW

**Comment by davelopez** [comment]
Although the Selenium tests look related they seem to pass locally... I wonder why 🤔 
Any chance someone can rerun them again just to be sure?

**Comment by bgruening** [comment]
rerun ...

**Comment by davelopez** [comment]
Well... at least now only fails one instead of 2 tests 🤣

**Comment by davelopez** [comment]
Thanks @mvdbeek!

**Pull request merged**
