### PR TITLE
Restore function necessary for splitting.

### PR DESCRIPTION
**Pull request by roalva1**
There was a function deleted in this merge 
https://bitbucket.org/galaxy/galaxy-central/commits/76277761807306ec2be3f1e4059dd7cde6fd2dc6#comment-820648
I restore it

### CODE REVIEW

**Comment by natefoo** [comment]
It looks like the `get_split_commands_with_toc` method should also be restored.

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/qdCos9Hq) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/5.patch) for testing.

**Comment by natefoo** [comment]
+1

**Comment by dannon** [comment]
+1

**Pull request merged**
