### PR TITLE
HiCBrowser as Galaxy IE

### PR DESCRIPTION
**Pull request by bgruening**
This is a new Galaxy IE for visualizing HiC data. It will be part of the upcoming HiC Galaxy flavor, based on [HiCExplorer](https://github.com/maxplanck-ie/HiCExplorer ) and [HiCBrowser](https://github.com/maxplanck-ie/HiCBrowser) by @fidelram and friends.

hicbrowser_galaxy_ie

The underlying Docker Image is available here: https://github.com/maxplanck-ie/docker-hicbrowser

I labeled it as WIP as it depends on https://github.com/galaxyproject/galaxy/pull/3328 and to be really useful I need to find time to improve the HiCExplorer wrappers.

### CODE REVIEW

**Comment by bgruening** [comment]
Ready for review!

**Comment by hexylena** [comment]
Note to self, example data https://github.com/maxplanck-ie/HiCBrowser/tree/master/example_browser

**Comment by hexylena** [comment]
@bgruening the HiC browser doesn't respect `PROXY_PREFIX`. Would need something like

```
sed -i "s|PROXY_PREFIX|${PROXY_PREFIX}|" /etc/nginx/conf.d/nginx.conf;
```

in startup.sh and then some specialized NGINX config. I'm afraid I don't know enough to help with that. I've only ever done HTTP proxying in nginx (e.g. https://github.com/erasche/docker-rstudio-notebook/blob/master/proxy.conf#L12).

**Comment by bgruening** [comment]
@erasche the container is under our control. So I can change this here: https://github.com/maxplanck-ie/docker-hicbrowser/blob/master/nginx.conf

**Comment by nekrut** [comment]
@jxtx @msauria - can you comment on this?

**Comment by jxtx** [comment]
@nekrut I believe it still needs fixes per the previous two comments.

**Review by hexylena — CHANGES_REQUESTED** [review]
Fix proxy prefix

**Comment by jmchilton** [comment]
Marking as WIP until the proxy prefix issue is resolved.

**Comment by bgruening** [comment]
I added PROXY_PREFIX support to the container and travis testing as well.

https://github.com/maxplanck-ie/docker-hicbrowser/blob/master/.travis.yml#L17

**Comment by hexylena** [comment]
bumped temporarily, hopefully I can get the necessary config changes in by end of tomorrow.

**Comment by bgruening** [comment]
@erasche the container does now support PROXY_PREFIX.

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Thanks @bgruening

**Pull request merged**
