### PR TITLE
If config_file is None, use cwd, not its parent

### PR DESCRIPTION
**Pull request by jdavcs**
Addresses this comment:
https://github.com/galaxyproject/galaxy/pull/921#discussion_r304351292

@natefoo , @nsoranzo - is this correct?

(the added empty lines improve readability, I hope)

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
I'm still not sure if overwriting `self.config_dir` at line 139 is correct, maybe we can refactor that too?

**Comment by jmchilton** [comment]
This needs to be back ported to 19.09 I think.

**Review by jmchilton — APPROVED** [review]

**Comment by jdavcs** [comment]
@nsoranzo about line 139: I don't know. As I understand, if the config file is not specified, cannot be found, etc., and galaxy is running from source tree, just use the `config/` dir in the source tree. Should it default to some other location?

**Comment by jdavcs** [comment]
backporting in a min..

**Comment by nsoranzo** [comment]
@ic4f One issue is that if a value is specified for `'config_dir'` in `config_kwargs`, it is overwritten by `os.path.join(self.root, 'config')` .

**Comment by jdavcs** [comment]
@nsoranzo you're right! (`config_file` looked too much like `config_dir` - so i didn't notice this!). I'll suggest a fix later today.

**Pull request merged**
