### PR TITLE
Reports tool trends

### PR DESCRIPTION
**Pull request by OldWorldBoa**
Added tool trends for four pages, jobs per month, jobs per month in error, and the specified ones of the same sort.

### CODE REVIEW

**Comment by martenson** [comment]
meta: If you install and setup flake8 (https://flake8.readthedocs.org/en/2.3.0/) the Galaxy way (https://github.com/galaxyproject/galaxy/blob/dev/.ci/flake8_wrapper.sh) you won't need to listen to Travis complaints :)

**Comment by martenson** [comment]
This looks great! I do not have full enough database to see it in full action locally but I will try to check it out on Test tomorrow.

I noticed this bug: if visiting `Jobs in error per day this month` I will get https://gist.github.com/martenson/6e2a421e65142625c408
Same with visiting `Jobs in error per month` and clicking on a month name

**Comment by martenson** [comment]
Also I do not think you want to include file `static/scripts/libs/.jquery.sparklin.js.swp` in this PR

**Comment by martenson** [comment]
also the `static/scripts/libs/jquery.sparklines.js` needs to go to `client/galaxy/scripts/libs/jquery.sparklines.js` and get minimized - I will show you how to do that tomorrow

**Comment by OldWorldBoa** [comment]
Sounds good. I'm done work for today anyways.

**Comment by martenson** [comment]
How to run the client build system is describedhere: https://github.com/galaxyproject/galaxy/tree/dev/client
Let me know if you have any questions.

**Comment by OldWorldBoa** [comment]
Okay, now all I need to do is minimize the file now.

**Pull request closed without merging**
