### PR TITLE
ScatterPlot No API connection for nested www_root

### PR DESCRIPTION
**Pull request by yhoogstrate**
ScatterPlot makes use of a hardcoded API url which is incorrect for certain server configurations (if www_root of galaxy is different from "/", e.g. "/galaxy/"). Currently these servers need to be manually configured to link to the correct API URL. This patch creates the correct URL from the parental variable parent.galaxy_config.root and returns "/" if this variable can not be found.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Can we agree on changing the file syntax to the one proposed in Best Practices?:

https://wiki.galaxyproject.org/Develop/BestPractices

This file is written as one single long line which makes it a bit complicated to modify and to track changes via GIT.

**Comment by dannon** [comment]
The reason it's one long line is that this is the static packed version of the file.  The one you'll want to edit with your changes is in ./config/plugins/visualizations/scatterplot/src/.  There's a Gruntfile in ./config/plugins/visualizations/scatterplot/ that handles actually _building_ that source into these packed versions for shipping.

What you're proposing as a fix sounds good -- can you apply it to the source files, run grunt, and push updates to this PR?  If you'd rather send a patch to me, I can apply it and issue a PR against your branch, so you can see what changes are necessary for next time.

**Comment by yhoogstrate** [comment]
Thanks, Dannon. I see the same thing indeed in src/scatterplot-display.js. I will try working and solving it with grunt.

**Comment by dannon** [comment]
Sure, let me know if I can help!

**Comment by yhoogstrate** [comment]
It should now work the way you proposed it. I saw that in the code of the charts module the variable _galaxy_config.root_ was chosen. When I tested that variable it didn't work, because the frame in which scatterplot runs does not get automatically access to the scope of the parent window. Therefore I have used the _parent._ prefix.

**Comment by dannon** [comment]
Thanks for the quick update, this looks good to me.  +1

**Comment by martenson** [comment]
for future reference our javascript build process: https://wiki.galaxyproject.org/Develop/JSA
:+1:

**Comment by martenson** [comment]
thanks @yhoogstrate for the fix

**Pull request merged**
