### PR TITLE
adding itp and mdp datatypes (for gromacs)

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
It seems that this PR was lost. it is not in the latest dev branch as it seems.

**Comment by jmchilton** [comment]
Bad merge in https://github.com/galaxyproject/galaxy/commit/adc62f6ba7d8f6ef462cc42c914743044ed9d2ee#diff-d5c80b3279bf41b0a8f1368025c840c7 it seems.

**Comment by bgruening** [comment]
Out of interest how can you figure this out?
See new one here: https://github.com/galaxyproject/galaxy/pull/7189

Thanks @simonbray and @jmchilton

**Comment by jmchilton** [comment]
I just clicked on the history for button in Github and went through changes to that file until I found the right one.

**Comment by bgruening** [comment]
> I just clicked on the history for button in Github and went through changes to that file until I found the right one.

:smile:

**Comment by nsoranzo** [comment]
Or `git log -p config/datatypes_conf.xml.sample` on the command line.

**Pull request merged**
