### PR TITLE
Log exception in set_metadata.py.

### PR DESCRIPTION
**Pull request by jmchilton**
We can finally do this as a result of #7095 I believe!

### CODE REVIEW

**Comment by jmchilton** [comment]
xref https://trello.com/c/Nrwodu9d 😆

**Comment by martenson** [comment]
> I would suggest writing the metadata exceptions to a file (rather than reusing the existing job streams). The framework could inject a logging stream into the datatypes to allow this.

? :)

**Comment by mvdbeek** [comment]
Cool! Should we test it as well ?

**Comment by martenson** [comment]
@mvdbeek As a separate PR maybe? We are testing sniffing already, not sure if another test here helps.
@jmchilton I'll leave you the honors to close the trello ticket.

**Pull request merged**
