### PR TITLE
Python3: port 215 files

### PR DESCRIPTION
**Pull request by nsoranzo**
This is a collective work done mainly during the GCC2016 Hackathon by @tshtatland, @xiaoqian1984, @alanryanwang, @ericenns and me. Thank you all for the tremendous effort!

xref: #1715

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: - thanks a ton all - awesome hackathon contributions.

**Comment by bgruening** [comment]
Half way through and this looks fantastic - thanks all!

**Comment by dannon** [comment]
+1

**Comment by bgruening** [comment]
:+1: from me as well! Fantastic work!

**Pull request merged**
