### PR TITLE
graph visualization added

### PR DESCRIPTION
**Pull request by eteriSokhoyan**
Graph visualization using Cytoscape.js

### CODE REVIEW

**Comment by guerler** [comment]
Please remove temporary files (*~) e.g. config/plugins/visualizations/graphViz/templates/graphviz.mako~, unless they are explicitly required.

**Comment by martenson** [comment]
@guerler Do we need to re-include jquery?
config/plugins/visualizations/graphViz/static/js/jquery-1.11.3.min.js

**Comment by martenson** [comment]
@eteriSokhoyan the commit af43097732c26409898c4866da58911319e8f414 added another copy of jquery
at this point please close this PR and open a new one, that will not contain commits with temp files and unneeded copies of multi-thousand line js library in order to keep this repo's size reasonable
thank you

**Comment by jmchilton** [comment]
Alternatively - this can just be squashed. `git rebase -i upstream/dev` (where upstream is the name of the github remote for galaxyproject/galaxy). This will give open an editor and if you opt to 'pick' the first commit and 'squash' or just 's' each subsequent commit they will all be squashed down to a single one. If you then force push the resulting branch back- the PR will be updated with a new history.

**Comment by carlfeberhard** [comment]
+1 Huge step over where we were (with graphview). Thanks very much for the work, Eteri. Sorry it's taken so long to get more feedback.

There are some additional improvements we can make after it's merged like:
- making a more specific datatype in the config, 
- using the existing node-edge provider, 
- and using something from `libs` for the tooltip, 
- etc.

Will you continue to work on this after the merge? How long can you stay on this visualization as a project?

**Comment by eteriSokhoyan** [comment]
@carlfeberhard 
Thanks for the feedback! 

In general I would like to continue to work on this project after the merge but i'm not  sure if it will be possible because of my time constraints(thesis, exams, work). 

Officially this visualization as a project is over for me, as it was my master project. 
But anyway i'll try to make the improvements you have mentioned as soon as possible. 

Thanks again.

**Comment by carlfeberhard** [comment]
If it's alright with everyone involved (especially @eteriSokhoyan), I'll go ahead and merge this next week and see what modifications still need to be done.

**Comment by eteriSokhoyan** [comment]
Hello, 
of course it's alright for me to merge it. 
I'm sorry, i didn't have a chance to make the improvements you have suggested, I was too busy with other projects lately.

**Comment by nsoranzo** [comment]
> making a more specific datatype in the config,

@eteriSokhoyan @carlfeberhard Can this be fixed? I don't know exactly what Galaxy datatype should be used, but today there was a bug report on IRC from @platyna about users confused by the fact that this visualization is now available for all kind of unrelated datasets: https://botbot.me/freenode/galaxyproject/2016-06-13/?msg=67803369&page=1

**Comment by bgruening** [comment]
I quick fix would be to only allow json. But this disallow the txt or rather tabular based input. I guess the proper fix would be to create an own datatype for both supported ones.

**Comment by platyna** [comment]
Would it be possible to create a "graph" data type?

**Comment by bgruening** [comment]
@platyna yes something along these lines, but there are a lot of different ones. This special json-based Graph datatype is the one from networkx. So maybe `networkx-graph`?

**Comment by platyna** [comment]
Looks fine for me.

**Pull request merged**
