### PR TITLE
Additions for tool form version updates in the workflow editor

### PR DESCRIPTION
**Pull request by guerler**
Addition to #4373. Currently only the tool version number is changed but the new tool is not loaded into the editor. If two versions of a tool have different inputs the changes are not shown.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Out of curiosity, how did you notice this ? I have been switching between tool versions that add and remove inputs and outputs, and that seems to have worked fine.

**Comment by mvdbeek** [comment]
On the contrary, this doesn't work now. It switches to a regular tool form, offering you to load files from the history inside the editor.

**Comment by guerler** [comment]
Interesting, so it works for you if have two tool versions and lets say one takes an integer field value and the other one does not?

**Comment by mvdbeek** [comment]
Ah, that I haven't tested, that is probably not going to work now that I think about it.
The inputs had different names, that's why this worked for me.

**Comment by mvdbeek** [comment]
It mostly works, i.e if I change a boolean to a text value the text value becomes what was the boolean, i.e false. And a text value to boolean shows the boolean selector. But I can see corner cases where this won't work, like for inputs whose accepted formats change.

**Comment by mvdbeek** [comment]
For reference, I'm using these tools to test https://github.com/mvdbeek/galaxy/commit/211e525a4ac4707066161d6c2effccd1ad737608

**Comment by guerler** [comment]
In general this assumes that two versions of a tool have the same input parameters and parameter names. Only the tool version string/number is switched.

**Comment by mvdbeek** [comment]
No, that is not correct, how did you get to that conclusion ?
We're building a whole new module for the new tool version, and with that new module we update the nodes field data and trigger a form refresh.

**Comment by mvdbeek** [comment]
~~What is a deficiency now though is that a connection between two two tools will not be broken even if after a version change the input/output formats are not compatible anymore. IMO a change like this is fairly unlikely, but we should still address that somehow.~~ That is adressed by #4431

**Comment by guerler** [comment]
Yes, that makes sense. Thanks.

**Comment by mvdbeek** [comment]
I think the changes in here still make sense to me, are you going to pick them out as a separate PR ?

**Comment by mvdbeek** [comment]
At least a078ee025f02732e108cf2d790e18cc826829ac5 looks good to me, apart from the change in client/galaxy/scripts/mvc/tool/tool-form-base.js

**Comment by guerler** [comment]
Yes, I am considering it.

**Comment by mvdbeek** [comment]
I have another fix for post job actions that get rendered multiple times after multiple version switching, I can include a078ee0 if your OK with that.

**Comment by guerler** [comment]
@mvdbeek I see. I prepared a PR to include the refactoring from this one here as enhancements. If you want to you can open a PR against that branch. Thanks a lot.

**Comment by mvdbeek** [comment]
Thanks @guerler, the PR is here https://github.com/guerler/galaxy/pull/22

**Pull request closed without merging**
