### PR TITLE
[17.01] Merge 16.10 into 17.01

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by martenson** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Thanks to all!

**Comment by nsoranzo** [comment]
@bgruening I've restored the `release_16.10` branch, that was the official 16.10 release branch!

**Comment by martenson** [comment]
@nsoranzo the branch is now protected from force pushing and deletion. We forgot to manually protect it so I opened #3562

**Comment by nsoranzo** [comment]
Thanks @martenson, I didn't remember that was possible, well done!

**Comment by bgruening** [comment]
Urgs, sorry.

**Pull request merged**
