### PR TITLE
[17.05] Change to only inheriting 'name' tags

### PR DESCRIPTION
**Pull request by dannon**
We may want to branch this out further in the future, but we'll start conservatively.

### CODE REVIEW

**Comment by dannon** [comment]
Fixes #4099, forgot to PR this at SAB.

**Comment by martenson** [comment]
I am confused here, I thought we are going to use `#` as the prefix for propagating (and dataset-shown) tags. Did this change back? This PR propagates only `name:whatever` tags.

**Comment by dannon** [comment]
`#` tags *are* `name:whatever` tags.

**Comment by nekrut** [comment]
`#` is a shortcut for `name:`

**Comment by martenson** [comment]
@dannon this is not clear to me, how is the hashtag supposed to work?

*BEFORE*
screenshot 2017-05-23 12 37 27

*AFTER*
screenshot 2017-05-23 12 38 23

**Comment by dannon** [comment]
Yeah, sorry, I wasn't clear.  #3979 implemented hashtags as clientside shorthand -- the underlying data representation never changed.

**Comment by martenson** [comment]
@dannon my point is that propagation of `#hashtag` does not work on this PR

**Comment by dannon** [comment]
If you're just checking out the branch and trying hashtags, it's because the change in this PR predates hashtags (I wrote it at SAB, we just never PR'd it).  So, this branch does not contain all the hashtag stuff (it's irrelevant here).

To test it with hashtags, you'd probably want to check out a testing branch, merge this in, and run that.

**Comment by martenson** [comment]
@dannon That explains my confusion.

After merging this with 17.05 the propagation works as expected. Minor issue is that it renames the `name:huhu` to `#huhu` in the output dataset tag - is that expected?

**Comment by dannon** [comment]
No worries.  It shouldn't actually be changing it, just rendering differently.  If you reload the whole page, *all* `name:huhu` should be `#huhu` -- can you test that?

**Comment by martenson** [comment]
@dannon that seems to work, given that we won't encourage people to actually use `name:` notation this shouldn't cause confusion.

**Pull request merged**
