### PR TITLE
[22.05] Bump tuswsgi middleware

### PR DESCRIPTION
**Pull request by mvdbeek**
The middleware (prior to 0.5.5) attempts to cleanup files on every upload, this can be a problem if there are many files in the upload directory, especially on NFS.

Should help with
```
uvicorn.access INFO 2023-02-27 14:44:26,392 [pN:main.1,p:23,tN:MainThread] 10.80.0.13:42166 - "POST /api/upload/resumable_upload/ HTTP/1.0" 500
[2023-02-27 14:44:26 +0000] [23] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/galaxy/server/lib/galaxy/webapps/base/api.py", line 163, in dispatch
    return await call_next(request)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/galaxy/server/lib/galaxy/webapps/galaxy/fast_app.py", line 99, in add_x_frame_options
    response = await call_next(request)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 140, in __call__
    return await responder(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 172, in __call__
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 222, in wsgi
    for chunk in self.app(environ, start_response):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/galaxy/server/lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "/galaxy/server/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 215, in __call__
    self.handle(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 254, in handle
    self.post(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 280, in post
    self.create_files(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 431, in create_files
    self.cleanup()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 602, in cleanup
    os.remove(fpath)
OSError: [Errno 16] Device or resource busy: '/galaxy/server/database/tmp/.nfs00000000001e38fa00000038'
```

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by nuwang — APPROVED** [review]

**Comment by mvdbeek** [comment]
Looks like the nodeenv install is on strike ...

**Comment by mvdbeek** [comment]
fwiw I ran the tests against s prerelease yesterday and it all passed, in case node can't be installed again
Screenshot 2023-03-15 at 12 35 14

**Comment by pcm32** [comment]
Cool! I was getting this exact error every now and then.

**Comment by pcm32** [comment]
@nuwang for this to work on the helm setup, do we need to change the version used of the tusd container? Or only the python component that Galaxy uses needs updating as done here? Thanks!

**Comment by pcm32** [comment]
...mmm... I suspect that we might be using the middleware anyway, I get every now and then this on our helm based setup:

```
[2023-04-17 19:06:59 +0000] [21] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/galaxy/server/lib/galaxy/webapps/base/api.py", line 163, in dispatch
    return await call_next(request)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/galaxy/server/lib/galaxy/webapps/galaxy/fast_app.py", line 99, in add_x_frame_options
    response = await call_next(request)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/galaxy/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/starlette/routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 140, in __call__
    return await responder(scope, receive, send)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 172, in __call__
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 222, in wsgi
    for chunk in self.app(environ, start_response):
  File "/galaxy/server/.venv/lib/python3.10/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/galaxy/server/lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "/galaxy/server/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 215, in __call__
    self.handle(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 254, in handle
    self.post(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 280, in post
    self.create_files(env)
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 431, in create_files
    self.cleanup()
  File "/galaxy/server/.venv/lib/python3.10/site-packages/tuswsgi.py", line 602, in cleanup
    os.remove(fpath)
OSError: [Errno 16] Device or resource busy: '/galaxy/server/database/tmp/.nfs00000000001c08c300003df0'
```

which seems to be the same stacktrace that Marius posted above.

**Comment by pcm32** [comment]
or maybe something needs to be deactivated in Galaxy so that this runs with the dedicated tus container that the helm chart installation has?

**Comment by nuwang** [comment]
Has the ingress entry for tus been correctly created? If the tus ingress intercepts the request, it will be routed to the tusd server, and Galaxy shouldn't receive a chance to process it: https://github.com/galaxyproject/galaxy-helm/blob/e71fa41c1be6638debfa782e48e03fe04d9f7854/galaxy/values.yaml#L646

**Comment by pcm32** [comment]
Thanks @nuwang, indeed my host wasn't set on the tusd ingress. Hopefully I won't see this one again.

**Pull request merged**
