### PR TITLE
[23.2] Separate `ConnectedValue` from `RuntimeValue`

### PR DESCRIPTION
**Pull request by mvdbeek**
Writing tests turned out to be trickier than expected since gxformat2 injects RuntimeValues into the state ...

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
A connected value is a value set at runtime... so this seems silly to me but I'm fine with it if you think it is more readable.

**Comment by mvdbeek** [comment]
I thought ConnectedValue is what we inject for values that are connected at definition time, as opposed to runtime values which are not and must be set by the user. Or are your and my definition compatible and I didn't understand something ?

**Comment by mvdbeek** [comment]
where this makes a difference is https://github.com/galaxyproject/iwc/pull/358/files#diff-200c2dbfd39d003b5d822b18523f30af6d4ccdd3dfd79ca42e9d1758b1099d88

**Comment by mvdbeek** [comment]
ok, I see your point, it's literally what you wrote, I was mixing up runtime with submission time.

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
