### PR TITLE
[19.01] User facing release notes

### PR DESCRIPTION
**Pull request by hexylena**
Fixes https://github.com/galaxyproject/galaxy/issues/7425 :)

I've made an attempt at updating `bootstrap_history.py` but I am ... quite unconfident in my changes. :(

I have not linked to the user announcements from anywhere, not sure where that would happen. I volunteer to write these for the foreseeable future.

### CODE REVIEW

**Comment by dannon** [comment]
I definitely like the presentation here, seems more useful for the majority of readers than the other format.

I initially thought we might want to come up with some other approach for images, but I don't know that it's (~200k a few times per year) worth worrying about to try to do anything other than include them in the repo as you've done here.

**Comment by hexylena** [comment]
yeah, just a different (and maybe larger) target audience, I still find utility in the full release notes, I skim them every time for interesting things that have been included. Hopefully something easily consumable/redistributable by admins and community managers.

I ran optipng on all of these, given the width of the documentation could potentially shave a few more bytes off but yeah maybe not worth it to either do that or to explore s3 type options.

**Comment by hexylena** [comment]
@dannon any more comments or are you OK with this? :)

**Comment by dannon** [comment]
@erasche Oh, yeah, sorry that wasn't clear -- I like them.  I have not tried to run your changes to the bootstrapper, but I can check that out later if you'd like.

**Comment by hexylena** [comment]
Sure, if you have time, that'd be great. If not, I can drop my changes to the bootstrap script? I'd like to be able to link people to the notes when we do manage to upgrade at least.

**Comment by jmchilton** [comment]
These are no doubt nice and I understand the appeal of targeting a different audience. Selfishly, I just don't love creating more work indefinitely. Is Freiburg willing to commit to writing these going forward or does this fall on the release manager? If this is merged, we can automate picking out the datatype changes and tool changes using tags and pre-populate some of that stuff.

**Comment by hexylena** [comment]
> Is Freiburg willing to commit to writing these going forward or does this fall on the release manager?

I am willing to commit to writing the highlights, if we can automate the rest that would be brilliant. Even for the this PR, it was nice to have a reason to explore the WF parameters, I might not have for another few months otherwise.

**Comment by jmchilton** [comment]
If you do that write up, I'll do the rest and automate what I can for 19.05. You can have my +1 I suppose, thanks!

**Review by jmchilton — APPROVED** [review]

**Comment by dannon** [comment]
@erasche Pushed one bug fix and one bit of cleanup, looks like it'll work now to me.  (But I guess @jmchilton will take care of it when 19.05 rolls around if not ;))

**Comment by hexylena** [comment]
Thanks for the fixes @dannon!

**Comment by martenson** [comment]
How is this going to be presented? A link from the general release notes?

**Comment by hexylena** [comment]
@martenson per comments in OP, no idea. We could link from general, I thought about something like "[Release notes]() to send to your users" but didn't have a good place to put that that wouldn't either be completely skipped over, or way too prominent.

**Comment by hexylena** [comment]
Maybe we leave it alone this release, and next release if I write some nice notes we can add it as a 4th highlighted feature? And then in future just a small link somewhere of "user facing release notes"

**Comment by martenson** [comment]
I wouldn't be afraid of giving it prominent spot - as a highlight or link above the highlights.

**Pull request merged**
