### PR TITLE
[15.07] Fix yield statements at the top level of macros.

### LINKED ISSUE #647: Nested, yielded macros don't expand properly
Test case

``` xml
<?xml version="1.0"?>
<tool id="embedded_macros" name="Embedded macros" version="1.1">
        <macros>
                <xml name="a">
                        <param name="a1" type="text" value="a1" label="a1"/>
                        <yield />
                </xml>
                <xml name="b">
                        <param name="b" type="text" value="b" label="b" />
                </xml>
        </macros>
        <command><![CDATA[
echo "HI"
]]></command>
        <inputs>
                <expand macro="a">
                        <expand macro="b" />
                </expand>
        </inputs>
        <outputs>
                <data format="txt" name="output"/>
        </outputs>
        <help><![CDATA[
Nested macros tests
]]></help>
</tool>
```

Rendered output

defcon1

Am I mis-using the yield keyworld? Or ... ?

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes #647.

### CODE REVIEW

**Comment by hexylena** [comment]
Absolutely beautiful! Thanks for the quick turnaround @jmchilton :)

**Comment by martenson** [comment]
@erasche this needs +2 before merging

**Comment by hexylena** [comment]
@martenson ... oh crap, it's 15.07, so sorry. I mistakenly thought it was dev. You're absolutely right. Back out for me not following procedure, or is there anyone else who would +1 this?

**Comment by hexylena** [comment]
Also what's the procedure for merging things from release branches into dev? It's nice to have in 15.07, but ...

**Comment by martenson** [comment]
:+1: 
@erasche once in release branch anybody can merge it to dev

**Comment by dannon** [comment]
I went ahead and merged it forward to master, but there's a conflict merging master-> dev that I haven't looked into yet.

**Comment by hexylena** [comment]
@martenson, okay! I'll bear that in mind.

**Pull request merged**
