### PR TITLE
Remove handlebars and rely solely on underscore templates

### LINKED ISSUE #1476: Remove handlebars templates, task, and compiler
Attempting to continue simplification of front end framework. We've never really used handlebars to it's full potential and the tool menu handlebars templates have essentially become cruft (IMO).
- [x] move tool menu handlebars templates into underscore 
- [x] remove requirement in tool modules and any mako templates
- [x] remove webpack loader, grunt task, and grunt dependency

That's my plan but I'm happy to reverse/stall if anyone objects.

Edit:
- [x] remove from scatterplot

### PR DESCRIPTION
**Pull request by carlfeberhard**
This is an effort to reduce complexity by removing handlebars templates from the tool panel, the old tool form, and scatterplot.

Difficult to test old tool form use in Trackster but seems to function the same as the handlebars version in Sweepster.

Resolves #1476 

Edit: (And replace spinner gif with font-awesome spinner when searching)

### CODE REVIEW

**Comment by guerler** [comment]
Looks great.

**Comment by davebx** [comment]
I am in favor of this change.

**Comment by martenson** [comment]
thank you @carlfeberhard !

**Comment by martenson** [comment]
Damn, I missed the WIP label, I am sorry :(

**Pull request merged**
