### PR TITLE
Remove legacy request controller from reports app

### PR DESCRIPTION
**Pull request by guerler**
This PR removes remaining makos and sequence tracking features from the reports app.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@guerler I thought about this when we were removing the requests from Galaxy (sorry for not bringing it up then). I am not sure we want to fo this, since the requests database stays intact, this could still be useful for looking into data there. What about hiding this behind config that is False by default?

**Comment by guerler** [comment]
I think at this point we should remove it since the data is not in the model mapping anymore it just exists in the database but we are not keeping track of it. In other words `model.Request` does not exists anymore within Galaxy: https://github.com/galaxyproject/galaxy/pull/5182/files#diff-31531c415fb7f30199dcc455872a51eaL68.

**Comment by jmchilton** [comment]
@martenson It should be possible to run an older version of the reports app with a newer version of Galaxy if you simply host them from different Git roots. If anyone finds this information useful - they can do that - but these people don't exist I don't think.

**Review by martenson — APPROVED** [review]

**Pull request merged**
