### PR TITLE
fixed stale link

### PR DESCRIPTION
**Pull request by bernt-matthias**

### CODE REVIEW

**Comment by nsoranzo** [comment]
@bernt-matthias I've rebased to get rid of the merge commits.

**Comment by bernt-matthias** [comment]
Thanks. Can you tell me how I could have done this myself. These merge commits always turn up in my PRs and I never understood why and what I can do against it.

**Comment by nsoranzo** [comment]
If you have already defined an `upstream` remote, it's just:
```
$ git pull --rebase upstream dev
```

If you don't have an `upstream` remote defined, you can add it with:
```
$ git remote add upstream https://github.com/galaxyproject/galaxy
```

**Comment by bernt-matthias** [comment]
Ah. OK. And I do this while being on the topic branch - right?

**Comment by nsoranzo** [comment]
Yes, see e.g. http://gitready.com/advanced/2009/02/11/pull-with-rebase.html for what `pull --rebase` does.

**Pull request merged**
