### PR TITLE
Add EDAM topics to tools and expose in API

### PR DESCRIPTION
**Pull request by nsoranzo**
Suggested by @hmenager in https://github.com/galaxyproject/galaxy/pull/2379#issuecomment-221002717.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Tests are failing because http://wheels.galaxyproject.org/ is down.

**Comment by mvdbeek** [comment]
Looks good, 👍  if the tests are passing.

**Comment by bgruening** [comment]
We have created a single-point of failure with depot.galaxyproject.org. All over the place tests are failing, even in the deeptools repository which contains Galaxy wrappers :sob:

**Comment by hmenager** [comment]
Thank you so much @nsoranzo. There probably is somewhere a documentation for tool definition authors that should be updated, to explain what are EDAM topics and how they should be chosen. I'm willing to contribute, but need a few pointers for this!

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Very nice - thanks so much!

**Comment by nsoranzo** [comment]
@hmenager The main tool XML documentation is at https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax

**Pull request merged**
