### PR TITLE
Fix all E731 "errors".

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by martenson** [comment]
beautiful

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Are the failing API tests known to be unrelated?

**Comment by nsoranzo** [comment]
@dannon: Related to my changes to `test/api/helpers.py` , will look into it. Suggestions appreciated!

**Comment by martenson** [comment]
@dannon afaik the only known failing tests look like this: `Timed out after 15.25 seconds waiting on state.`
so these are legit

**Comment by dannon** [comment]
@martenson Thought so as well, thanks for the confirmation.  @nsoranzo Taking a look now.

**Comment by nsoranzo** [comment]
I've modified the changes to `test/api/helpers.py` and rebased, the API tests pass now for me locally.

**Comment by dannon** [comment]
@nsoranzo What was the issue exactly with the function definitions?  Due to the rebase it's not obvious what you changed.

**Comment by jmchilton** [comment]
He switched a `map` statement to this line:

```
element_identifiers = [hda_to_identifier(i, hda) for (i, hda) in enumerate(hdas)]
```

The direct translation of the lambda statement would have been to declare the procedure with one argument instead of two - but bind i and hda in that one argument as follows:

```
def hda_to_identifier((i, hda)):
                return dict(name=contents[i][0], src="hda", id=hda["id"])
```

Which despite looking like Haskell or ML actually does work in Python:

```
>>> def foo((x,y)): return x + y
... 
>>> foo((1, 2))
3
```

Anyway - since no one realizes this works in Python - I think the more basic list comprehension is an entirely appropriate refactoring.

:+1:

**Comment by nsoranzo** [comment]
Yes, I also firstly fixed it as @jmchilton suggested above, but it looked quite obfuscated and so I preferred the clarity of using a list comprehension where the tuple (pair) generated by `enumerate()` is clearly split.

**Comment by dannon** [comment]
Got it, didn't see the list comprehension change in the diff there (grumble grumble rebase).  This looks good, and I prefer the list comprehension as well, much more readable.

**Pull request merged**
