### PR TITLE
[20.09] Close tempfile file descriptor

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes https://github.com/galaxyproject/ephemeris/issues/166

### CODE REVIEW

**Comment by mvdbeek** [comment]
I systematically looked at the code base and found a couple more instances where we don't close the fd returned by mkstemp in https://github.com/galaxyproject/galaxy/pull/10852/commits/13f597b0ff71372f8a3dc509656ad747156e954f

**Comment by bernt-matthias** [comment]
Wouldn't `with` blocks be even better?

**Comment by nsoranzo** [comment]
> Wouldn't `with` blocks be even better?

I also generally prefer to use `with tempfile.NamedTemporaryFile(..., delete=False) as`

**Review by jmchilton — APPROVED** [review]

**Comment by mvdbeek** [comment]
I'd prefer not to refactor on a released branch (there are more mkstemp to fix beyond the cases that are problematic).

**Pull request merged**
