### PR TITLE
Restore ToolsApi and create new api route for new panel structure

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
We changed the shape of `api/tools` in #16739 . However, as discussed in the backend team meeting (10/17/2023), it isn't ideal to change the shape of an API without a deprecation cycle.
Therefore, I have restored the `index` function for the `api/tools` route in the `ToolsController`, and added a `panel_view` function for a new `api/tool_panel` route.
In the case that people may have built stuff against the older API, they will still be able to access the older structure, while at the client side we use this new route, and eventually the older one is replaced.

Please let me know if this approach is correct and if the new route `api/tool_panel` is reasonable (Do we want `api/tools/panel` or something else?)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
>if the new route api/tool_panel is reasonable (Do we want api/tools/panel or something else?)

`api/tools?view=panel`?

**Comment by ahmedhamidawan** [comment]
> > if the new route api/tool_panel is reasonable (Do we want api/tools/panel or something else?)
> 
> `api/tools?view=panel`?

This was discussed in the meeting, and apparently, we want a temporary new route, keeping `api/tools?...` as is.
But still, that could work too, let's see what others say

The problem with `api/tools?view=panel` could be that we also have a `view` param through which we select panel views

**Comment by martenson** [comment]
It can be `?mode=panel` or something like that so we do not overload. However, if we are making this route internal only and will drop it immediately after the deprecation cycle for old `/api/tools` it does not matter.

**Comment by hexylena** [comment]
>  In the case that people may have built stuff against the older API

oh, gosh, I've built a *lot* against `/api/tools`, that will generate a lot of work for me if it's deprecated. Some of the GTN automation around supported servers uses that API to look at all tools on that instance, same in the video-library. The public server list grafana also used the same APIs as well.

Thanks for continuing to support it!

**Comment by dannon** [comment]
The plan discussed at the backend working group meeting was just to reconnect the original route without changes (so, back to the existing to_dict) and add the new to_panel_view functionality under a new route, as this PR does.

There was some conversation that it would have been nice to have a different original API at `/api/tools` that looked closer to what these newer responses look like, but even during the meeting there was recognition that any transition of this particular endpoint would be messy and that we might just want to leave it as-is.  In any event, no deprecation is happening here, yet, and maybe never.

**Pull request merged**
