### PR TITLE
Mixed Python3 fixes

### PR DESCRIPTION
**Pull request by nsoranzo**
Commits cherry-picked from https://github.com/mvdbeek/galaxy/commits/py3_fixes2

xref. #1715

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think this is ready for merge, before the PR becomes too big.

**Comment by dannon** [comment]
@nsoranzo Do we need a wheel for packaging first?

**Comment by nsoranzo** [comment]
@dannon There's already a wheel on https://pypi.python.org/pypi/packaging (which is used in the tests run on Travis), is that enough?

**Comment by dannon** [comment]
@nsoranzo I didn't think so, but maybe it is?  @natefoo for packages with wheels available on pypi, are we okay with not creating/archiving/shipping our own anymore?

**Comment by dannon** [comment]
(pypi wheels are okay, we just need to back them up for depot if we're not building our own)

**Pull request merged**
