### PR TITLE
Strip broken autocomplete feature, webbrowsers console error is an artifact

### LINKED ISSUE #3675: menu loading broken
Happens on everything under Shared Data except libraries, also happens on Visualization/Saved Visualizations

This is on `dev`. Menu does not load and JS console has:

from jquery-ui
```
Uncaught TypeError: Cannot set property 'selectFirst' of undefined
    at t.widget.extend (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:33:5822)
    at t.fn.init.t.fn.(anonymous function) [as autocomplete] (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:33:6011)
    at n.init_grid_controls (http://127.0.0.1:8080/static/scripts/mvc/grid/grid-view.js?v=1488213067:1:2225)
    at n.init_grid (http://127.0.0.1:8080/static/scripts/mvc/grid/grid-view.js?v=1488213067:1:1029)
    at n.initialize (http://127.0.0.1:8080/static/scripts/mvc/grid/grid-view.js?v=1488213067:1:295)
    at n.e.View (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:27:13017)
    at new n (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:27:20968)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8080/workflow/list_published:297:28)
    at l (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:24:22690)
    at Object.add [as done] (http://127.0.0.1:8080/static/scripts/bundled/libs.bundled.js?v=1488213059:24:22992)
```

ping @guerler @dannon

### PR DESCRIPTION
**Pull request by guerler**
Fixes #3675. The autocomplete feature has been disabled awhile ago, the outdated autocomplete front-end plugin causes an artifact console error. This PR strips the remaining autocomplete code parts. Autocomplete features for advanced grid search fields have to be revisited and re-implemented using the api.

### CODE REVIEW

**Comment by guerler** [comment]
No need to review yet.

**Comment by dannon** [comment]
@guerler What change was it when this stopped working?

**Comment by guerler** [comment]
At least since last year: https://github.com/galaxyproject/galaxy/blame/dev/templates/grid_base.mako#L105.
It is not a critical feature and I would prefer to revisit it in a consistent way at another time.

**Comment by dannon** [comment]
Sorry, I meant the menu itself, what changed that broke between 17.01 and dev?

**Comment by guerler** [comment]
I enabled access to the regular jquery autocomplete module in #3407. The former use pattern for grids started to throw an exception on initialization after making the current autocomplete plugin available. The exception hinders the execution of the menu module.

**Comment by martenson** [comment]
Seems like a decent solution to me. Thanks @guerler !

**Pull request merged**
