### PR TITLE
Optionally pass dataset lists as a single file within tool wrappers

### PR DESCRIPTION
**Pull request by ghost**
This change, when used with a 'multiple=True' tool wrapper XML input parameter passed in cheetah with the paths_in_file method called, passes the dataset list of files to the wrapped program as a single file containing a list of the dataset files.

This prevents show-stopper issues where the command line passed to a wrapped
tool is truncated or rejected due to the 'argument list too long' error.

### CODE REVIEW

**Comment by jmchilton** [comment]
Cool start @einon. I'm going to try to redirect your effort a bit though - making this an attribute on the input is not the approach I would take, this is an operation related to building the command line not something to do with the inherent nature inputs being collected. As such, I think it would work better as a method available on the existing wrappers. This simplifies the implementation and placing the method on `HasDatasets` allows collections and multi-data parameters to share this functionality.

I've sketched out some initial work on this approach in the following commit:

https://github.com/galaxyproject/galaxy/commit/04ed0abc3e8ed3015b47d4fc2698126a64f50efd

In addition to the above change it also uses tempfile to prevent naming collisions and allows other separators than '\n'.

Can you make these changes to your PR (my commit doesn't pass around job_working_directory the way it needs to for instance and the way yours does) and debug the sample tool that I have included as a test case to test and demonstrate this functionality?

The test case can be executed with:

```
./run_tests.sh -framework -id paths_as_file
```

**Comment by ghost** [comment]
@jmchilton Sure, will do. I was eventually going to remove the extra attribute and make it a property of all multiple inputs (because why not?). As long as the gist of my changes makes sense, that's good.

As for your test, I can see the fancy github HTML page, which has a commit ID, but I can't see any reference to that commit in my git tree. I'm not a big user of the github interface - how do I go about getting an old fashioned plain text patch of your changes, at least?

**Comment by nsoranzo** [comment]
@einon https://github.com/galaxyproject/galaxy/commit/04ed0abc3e8ed3015b47d4fc2698126a64f50efd.patch

**Comment by ghost** [comment]
@jmchilton One thought - what about existing tool wrappers that use 'multiple' params, and expect a list of files, if there are any - this change would break them. What is your policy for changes like this, do I have to change any tools to reflect this?

**Comment by jmchilton** [comment]
@einon My approach wouldn't break them - it adds a new method to the wrappers - if the cheetah doesn't call `$inputs.paths_as_file` there would be no change.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by ghost** [comment]
HI,
Thanks fro the test. Is it possible to remove the WIP tag for this now?

**Comment by martenson** [comment]
@einon you as the author are deciding when to remove that tag

**Comment by jmchilton** [comment]
Looks beautiful to me :smile:, many thanks @einon.

:+1:

**Comment by jmchilton** [comment]
@martenson I think only we can modify the labels - I suppose that is what @einon meant by tags.

**Comment by martenson** [comment]
got it, thanks @nsoranzo for doing so

**Comment by martenson** [comment]
thanks @einon !

**Comment by ghost** [comment]
Awesome, thank you very much!

**Pull request merged**
