### PR TITLE
Update 15.07 timeline to post-GCC

### PR DESCRIPTION
**Pull request by dannon**
Proposing two new dates following discussion from #385

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1:

**Comment by bgruening** [comment]
:+1:

**Comment by jmchilton** [comment]
:+1: as this is better than the current timeline - though my preference would actually be to stick with the 3 week release window and call this 15.08.

**Comment by martenson** [comment]
0 as I am not in favor of changing plans the day they should be carried out

**Comment by dannon** [comment]
@jmchilton I like that idea, July 13 is _right_ after BOSC and still during ISMB for some folks.  Anyone else care to chime in?  Happy to update the dates to whatever we'd like.

**Comment by dannon** [comment]
Merging as-is for now.  We can revisit 15.07 vs 15.08 as testing happens.

**Comment by martenson** [comment]
5/18 is pretty small voting attendance for something that affects everybody

**Comment by hexylena** [comment]
@martenson fair point. 20 hour window, day of, was probably too short for this sort of decision.

**Comment by erasche** [comment]
pinging @galaxyproject/core

**Comment by dannon** [comment]
Maybe I'm confused, but there was no option _but_ for this to be day-of, since it was the day of the freeze.  Clearly the freeze did not happen, so I updated this.

**Comment by hexylena** [comment]
(discussion moved to irc)

**Pull request merged**
