### PR TITLE
Close empty multi view, fix icon alignment

### PR DESCRIPTION
**Pull request by guerler**
Fixes regressions in the masthead and the multi-view/scratch book handling:
- The multi-view should disappear when all windows are closed
- The note icon counting the number of open windows has been shifted
- The active attribute was not used properly
- Highlighting of drop-down tabs was not working
- Legacy backbone view file has been removed
- Conflicting style sheet definitions have been removed

### CODE REVIEW

**Comment by mvdbeek** [comment]
The tick mark / number of scratchbook items seems a bit too far away from the scratchbook, can you have a look at that too ?
Screenshot 2020-11-26 at 10 19 02
Screenshot 2020-11-26 at 10 18 51

**Review by mvdbeek — APPROVED** [review]
Nice, looks good to me!

**Comment by guerler** [comment]
@mvdbeek thanks for catching this, I noticed a few more issues which regressed e.g. the highlighting of active tabs and possibly something else. Working on fixing these issues now.

**Comment by mvdbeek** [comment]
I noticed those too, but I thought that was a deliberate decision 😆

**Comment by guerler** [comment]
@mvdbeek Ok, I fixed a few more issues.

**Comment by guerler** [comment]
Fixes #10614

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
