### PR TITLE
Fix tool JSON wrapper fail to wrap paths

### PR DESCRIPTION
**Pull request by qiagu**
We now can wrap the file paths in the JSON temp file by having `data_style="paths"` in tool xml.

### CODE REVIEW

**Comment by qiagu** [comment]
I feel being able to wrap paths in the JSON config file is helpful.  What do you think? @jmchilton @martenson and others.

**Comment by qiagu** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Yeah - solid bug fix thanks @qiagu.

**Comment by qiagu** [comment]
Thanks @jmchilton

**Pull request merged**
