### PR TITLE
Implement UI to display list of lists dataset collections

### PR DESCRIPTION
**Pull request by carlfeberhard**

### CODE REVIEW

**Comment by jmchilton** [comment]
Wonderful - this is huge! Thanks a million @carlfeberhard.

**Comment by gregvonkuster** [comment]
Can this please be applied to 16.04?

**Comment by bgruening** [comment]
Oh this is awesome! Very much needed, thanks a lot Carl!
@gregvonkuster no new features to a stable branch, just bug-fixes.

**Comment by gregvonkuster** [comment]
@bgruening @jmchilton This is a bug fix, or at least should be labeled as one.  It came out of my issue here: https://github.com/galaxyproject/galaxy/issues/2581, which is the last hurdle to get the Galaxy ChIP-exo flavor completed.

**Pull request merged**
