### PR TITLE
Make tool search field stay at top of window when tool list scrolls, Issue 2375

### LINKED ISSUE #2375: Tool search bar should stay visible when scrolling through tools.
One of our wet-lab folks just came up with a nice feature request. It's sometimes the case that you search for a tool in Galaxy and get a LOT of results. You end scrolling down through the results to find the tool you want, only to realize after multiple screens of tools that you should just refine your search. In such cases, it'd be really convenient if the tool search bar stayed at the top of the results when one scrolls up/down.

It's minor usability tweak, but it'd be nice.

### PR DESCRIPTION
**Pull request by sszakony**
Changes to CSS to allow field to stay in place when long search results enable scrolling of the tool list. Fixes #2375.

### CODE REVIEW

**Comment by martenson** [comment]
thanks @sszakony !

**Comment by guerler** [comment]
Looks like this now i.e. needs some touch up:
fix_style

**Comment by dannon** [comment]
@guerler What is that "whats up?" from?

**Comment by dannon** [comment]
@sszakony There are problems with the workflow form tool search, however.  I'm looking at those now.

**Comment by sszakony** [comment]
Dannon, I see the differences in the CSS that are causing the issues, the question is if we adjust on this page what else what might we be breaking?

**Comment by martenson** [comment]
@dannon `Whats up?` is a info message banner, configurable in Galaxy (we use warning on Main sometimes)

**Comment by dannon** [comment]
@martenson Yeah, I got it, at first (before my coffee kicked in) I thought it was something @guerler was working on.

**Pull request merged**
