### PR TITLE
Raise exception if some Active Directory options are not defined

### PR DESCRIPTION
**Pull request by nsoranzo**
Bug fixed: when using authenticating against an AD provider which allows anonymous LDAP binds, if bind-user and bind-password are not configured in the <options> section of auth_conf.xml, the password is not checked and the user is always logged in.

Also:
- pylint fixes
- generalize use of ConfigurationError exception.

Ping @andrewjrobinson for review.

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/GmCljUwe) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/33.patch) for testing.

**Comment by andrewjrobinson** [comment]
Looks fine from my end.  All my tests still work.

**Comment by jmchilton** [comment]
Awesome, thanks for the fixes and keep them coming.

**Comment by nsoranzo** [comment]
Thanks Andrew and John!

**Pull request merged**
