### PR TITLE
[23.1] Load latest version only into panel views

### PR DESCRIPTION
**Pull request by mvdbeek**
Might be a quick and dirty fix for

image

seen at vgp.usegalaxy.org. Need to figure out how I can test this.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
```
% grep -r 'walk_loaded_tools' lib/
lib//galaxy/tool_util/toolbox/views/interface.py:def walk_loaded_tools(tool_panel: ToolPanelElements, toolbox_registry: ToolBoxRegistry):
Binary file lib//galaxy/tool_util/toolbox/views/__pycache__/edam.cpython-39.pyc matches
Binary file lib//galaxy/tool_util/toolbox/views/__pycache__/interface.cpython-39.pyc matches
lib//galaxy/tool_util/toolbox/views/edam.py:    walk_loaded_tools,
lib//galaxy/tool_util/toolbox/views/edam.py:        for tool_id, key, val, val_name in walk_loaded_tools(base_tool_panel, toolbox_registry):
```

I don't think this could fix this because that method is only used by EDAM? I think maybe definition_with_items_to_panel in static.py::StaticToolPanelView should instead not build sections with duplicated ids.

**Review by jmchilton — APPROVED** [review]
I appreciate the quick fix but I'd like to understand why ``add_tool_to_tool_panel_view`` isn't preventing this. It has code in there to try to it looks like. I'm happy to merge this and see if it works for now but I will try to follow up with a reversion of this today and a fix I'm more comfortable with. Is it possible to test this on test.galaxyproject.org - it seems to have the issue.

**Comment by jmchilton** [comment]
The core tool panel just treats tool shed tools and local tools with multiple versions so differently and that is reflected out when applying filters: 

```
in here with section.elems {'tool_toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.19.5+galaxy1': <galaxy.tools.Tool object at 0x12f4f4a60>, 'tool_toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.20.1+galaxy0': <galaxy.tools.Tool object at 0x12efb7e20>, 'tool_toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.23.2+galaxy0': <galaxy.tools.Tool object at 0x12ef87910>, 'tool_multiple_versions': <galaxy.tools.Tool object at 0x12f463c10>}
```

I tried your fix here and it didn't seem to work in my local testing with this fastp tool in the above debug message. I'm still getting multiple versions repeated.

**Comment by mvdbeek** [comment]
Let's do it right then

**Comment by mvdbeek** [comment]
(Seeing that too, but I don't think the lineage is at fault, the is_newer  / latest version is correct)

**Pull request closed without merging**
