### PR TITLE
implement selenium test User->Preferences->Manage information

### PR DESCRIPTION
**Pull request by OlegZharkov**
Expanding Selenium tests coverage according to https://github.com/galaxyproject/galaxy/issues/3241

Test capabilities under ```{http://{galaxy}/user/information```
- test changing user email
- test public name
- test user address (a tricky one, will appreciate a comment on it, see ```test_personal_information.py:get_address_input_field()``` )

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@OlegZharkov this needs a rebase :(

**Comment by OlegZharkov** [comment]
> @OlegZharkov this needs a rebase :(

@bgruening  Oh, thanks for an update! I see that GenoSpace was removed from user preferences and it led to this conflict. I will deal with it

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by davebx** [comment]
@OlegZharkov On the test_user_address() test, if we add the label to the div like so, in `client/galaxy/scripts/mvc/form/form-input.js:178-181`:

```
            this.$collapsible.hide();
        }
        this.$field.attr("data-label", this.model.get("label"));
    },
```
You could get away with eliminating the `get_address_input_field()` method entirely and doing
```
           input_field = get_address_form() \
                .find_element_by_xpath('.//div[@data-label="' + input_field_label + '"]') \
                .find_element_by_tag_name('input')
```

It doesn't feel like _exactly_ the right solution, but it would make it possible to at least get to the desired parent directly.

**Comment by OlegZharkov** [comment]
Thanks a lot, @davebx! I just tried your idea with ```"data-label"```. This is exactly what I was looking for. That would be way cleaner, than searching for a parent element.

**Comment by OlegZharkov** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by davebx** [comment]
I'm rerunning the API test on jenkins, looks like it failed due to unrelated reasons.

**Comment by OlegZharkov** [comment]
thanks @davebx, it looks like it. Why do we actually run selenium on jenkins? Why not regular github actions pipeline?

**Review by davebx — APPROVED** [review]

**Comment by davebx** [comment]
@OlegZharkov I truly can't remember, it's been so long. My first guess would be to have these tests running on an environment we control, but that is only a guess.

**Comment by OlegZharkov** [comment]
@davebx @mvdbeek thanks for reviewing!

**Pull request merged**
