### PR TITLE
Kubernetes runner: fixes result files from work directory not being recovered issue

### PR DESCRIPTION
**Pull request by pcm32**
Removes incorrect FALSE option for include_work_dir which makes certain jobs that discover files from working directories to fail recovering files when running through the Kubernetes runner. This is related to pull #2314 .

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Awesome - thanks for the fix!

**Pull request merged**
