### PR TITLE
[17.01] By default, do not allow workflow invocations to schedule indefinitely.

### PR DESCRIPTION
**Pull request by jmchilton**
Give up after a month but allow admins to reduce this amount as well.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is that a workaround for the problem manifested by log messages like:
```
Workflow step 1585 of invocation 554 delayed
```
?

**Comment by jmchilton** [comment]
Those lines don't necessarily indicate there is a problem but this would prevent the same workflow invocation from generating those lines for over a month I guess.

I plan to follow up tomorrow with another PR that will add an end to that sentence to indicate why the workflow is being delayed - it can help admins determine if there is a problem - because I suspect in many cases there is not.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Rebased a fix for the failing test and pulling this one out of WIP.

**Review by martenson — APPROVED** [review]
lgtm

**Pull request merged**
