### PR TITLE
[19.09] Revert hacking IPs in container monitor script.

### PR DESCRIPTION
**Pull request by jmchilton**
It breaks the Mac setup and seems just wrong, docker might not be on localhost. This needs to be made more specific in some way and should handle those socker commands not working on OS X.

### CODE REVIEW

**Comment by natefoo** [comment]
Yeah, I didn't take too good of a look at this, sorry about that.

**Comment by bgruening** [comment]
I understand this, but merging this revert will break our and Nates setup afaik. I'm afraid we are sacrificing real-world deployment for OSX users and hypothetical deployments when we merge the PR as it is :(

**Comment by nsoranzo** [comment]
There's a flake8 error to fix.

**Comment by jmchilton** [comment]
It is marked WIP - I'm not suggesting we merge as is, but someone should fix it. I don't have a slurm or condor setup so I'd hope someone else offer but if no one will I can give it a try. Can someone at least provide a dump of that ``ports`` variable on your respective setup so I can think more about this?

**Comment by natefoo** [comment]
Here's the raw output:

```console
[root@clone0n0 ~]# docker port d2b7340119564d63bcb0277141c67339
8888/tcp -> 0.0.0.0:32769
```

**Comment by jmchilton** [comment]
Does this feel like an okay compromise?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
