### PR TITLE
Prefer versioned Conda dependencies to unversioned Galaxy ones

### PR DESCRIPTION
**Pull request by natefoo**
We have been trying to get the updated dunovo tools working on Main and ran into both an install time and run time problem of the bowtie2 dependency, which was specified as 2.2.5, resolving via Galaxy packages as 2.1.0. This is due to us having a `default` symlink to 2.1.0 from Way Back In The Day before they were handled by TS dependencies. Ultimately we don't have any unversioned requirement tags that depend on it, so I removed the `default` symlink.

I can't imagine any situation in which you'd want an unversioned dependency over a versioned one, even in the explicit "I am making a decision as an admin to override the conda version" case - just use the versioned Galaxy dep in that case. If you really do want unversioned Galaxy deps to override versioned Conda deps then set up a dependency resolvers conf accordingly.

### CODE REVIEW

**Comment by natefoo** [comment]
That said, @jmchilton insists I argued for it to be the way it is now. I can't remember why I would have argued for it or whether I had a technical argument for it, though.

**Comment by jmchilton** [comment]
The docs are incorrect throughout now though.

**Comment by natefoo** [comment]
Ah, we should definitely fix that before merging this if we decide we want to make this change.

**Comment by nsoranzo** [comment]
I had the same issue with a bunch of dependencies, ended up removing many `default` symlinks. :+1:

**Comment by dannon** [comment]
+1, thanks for updating the docs.

**Pull request merged**
