### PR TITLE
Revert "Set 'deleted' to True when purging a history dataset association"

### PR DESCRIPTION
**Pull request by dannon**
Reverts galaxyproject/galaxy#3572

### CODE REVIEW

**Comment by martenson** [comment]
This will break instances that were already migrated since they cannot downgrade.

**Comment by natefoo** [comment]
This is a dev change so I don't think that is a problem we need to consider.

**Comment by dannon** [comment]
Right, in -dev, someone can just check out $REV-1, downgrade, then pull new changes.

**Comment by dannon** [comment]
(closed per discussion in #3572)

**Pull request closed without merging**
