### PR TITLE
Update Dynamic Tool Destinations With Configurable Priorities and Better Validation

### PR DESCRIPTION
**Pull request by TamsenSpelchak**
**Why should these changes be made?**
The current way priorities are handled by `dynamic_tool_destination.py` is rather limited -- there are three values (low, med, high), and they cannot be altered or renamed. This is especially problematic for large instances of Galaxy where there are many different use cases and/or users.

Also, `tool_destination.yml` validation does not validate as many things as it could. For example, it doesn't check if `verbose` is set to a boolean value, or if destinations exist.

**Implementation**
This branch alters the way `dynamic_tool_destination.py` works: rather than having 3 hardcoded priority values, it allows for an arbitrary number of config-specified priorities. Essentially, whatever priorities that are used in the global `default_destination` section of `tool_destination.yml` are put in a set of priorities considered 'valid' at runtime. 

`dynamic_tool_destination.py` also checks to see if destinations referenced in `tool_destination.yml` are valid, and does so in different ways depending how the program is run.
- If running the tool directly for config validation, it allows the user to pass in the `job_conf.xml` file to use, and looks for default ones if none are specified. It then parses the config and creates a set of valid destinations. If a destination is referenced that does not appear in the job config, a message is printed notifying the user, and if the invalid destination is a small edit distance away from a valid destination, the program recommends what the user might have been trying to type in the config.
- If the tool is invoked from a Galaxy instance, the tool checks referenced destinations against `job_config.get_destination()` to see if they are valid.

Typo checking has also been implemented for priority names.

Other miscellaneous fixes have been included, such as printing a message if `verbose` is not a boolean value in `tool_destination.yml`.

**Testing these changes**
The `dynamic_tool_destination` tests have been updated to test this new functionality. These tests can be run with
```./run_tests.sh -unit test/unit/jobs/dynamic_tool_destination/```

### CODE REVIEW

**Comment by TamsenSpelchak** [comment]
@ericenns, @Takadonet: you guys asked to be tagged on this, so here you go!

**Comment by TamsenSpelchak** [comment]
Anyone have any ideas why locally running `.ci/flake8_wrapper.sh` doesn't show the issues that Travis is showing? It's making it difficult to test if my code modifications will fix the Travis errors before committing.

**Comment by nsoranzo** [comment]
`tox -e py27-lint` is the way to do it.

**Comment by TamsenSpelchak** [comment]
Thanks @nsoranzo, I was trying that but getting some errors about the system being unable to create the virtual environment. I'll take another look!

**Comment by TamsenSpelchak** [comment]
I removed a bunch of files that were unrelated to this pull request that were accidentally included due to a pull from the `phac-nml` galaxy repo, and also merged in the latest changes from the `dev` branch.

Hopefully this pull request should be a lot easier to read now!

**Comment by jmchilton** [comment]
There are a lot of commits in here from #4830 but not all of it is covered. It is kind of hard to read and it is conflicted. Is there any chance I can get you to rebase on the current development branch now that #4830 has been merged. It will help me read this PR I think.

**Comment by TamsenSpelchak** [comment]
I merged in the latest dev branch, how does it look?

**Comment by TamsenSpelchak** [comment]
I think I goofed up, will fix it soon!

**Comment by TamsenSpelchak** [comment]
Alright, I think everything should be looking better now!

**Comment by jmchilton** [comment]
Looks good to me - thanks!

**Comment by TamsenSpelchak** [comment]
Wowee! I can pass my co-op term now @JeffreyThiessen @Takadonet

**Comment by TamsenSpelchak** [comment]
Thanks @jmchilton :)

**Pull request merged**
