### PR TITLE
linkify Data Libraries description and bugfix

### PR DESCRIPTION
**Pull request by OlegZharkov**
This PR will linkify elements in Library description. It will create an ```<a>``` element, that will open link a new tab on click
image

Additionally, don't run ```$('#center [data-toggle="tooltip"]').tooltip({trigger: "hover"}```, if title is there. I guess, we don't really need an additional title on hover. I assume it was the reason, that caused tooltip glitch.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @OlegZharkov

**Comment by dannon** [comment]
I'm always hesitant to strap anything else onto jquery; can we do this on render without the jquery linkage?

**Comment by OlegZharkov** [comment]
> I'm always hesitant to strap anything else onto jquery (especially given we want to remove it completely); can we do this on render without the jquery linkage?

Yeah, it's totally understandable. jQuery is definitely a legacy crap and you're right, probably adding a new plugin is not the best idea. I hope, it is better now. (I wanted to say that babel will take care, but to my surprise `querySelectorAll` is supported even by Internet Explorer 0_o wow)

**Comment by OlegZharkov** [comment]
@dannon thank you

**Comment by dannon** [comment]
@OlegZharkov Thank you!

**Pull request merged**
