### PR TITLE
adding GPU support to Galaxy

### PR DESCRIPTION
**Pull request by jashwantraj92**
We are adding automated GPU support tin Galaxy to run GPU-enabled tools. This effort is a part of Galaxy academic project at Penn State funded by NSF. We are open for feedback and kindly want this be pushed to the main upstream repository.

### CODE REVIEW

**Comment by bgruening** [comment]
@jashwantraj92 can you please rebase this against latest dev.

**Comment by jashwantraj92** [comment]
> @jashwantraj92 can you please rebase this against latest dev.

Sure let me do that

**Comment by martenson** [comment]
On the committers meeting we've guessed this is guided by @natefoo. Can you please confirm Nate?

**Comment by martenson** [comment]
This has been very likely superseded by https://github.com/galaxyproject/galaxy/pull/12775.

**Pull request closed without merging**
