### PR TITLE
[21.01] Fix mtx unbound error

### PR DESCRIPTION
**Pull request by mvdbeek**
Needed for the smorgasboard scanpy tutoial

### CODE REVIEW

**Comment by mvdbeek** [comment]
So now our linter is forcing bugs on us? 💢 
```
./lib/galaxy/datatypes/tabular.py:1280:17: E741 ambiguous variable name 'l'
./lib/galaxy/datatypes/tabular.py:1284:25: E741 ambiguous variable name 'l'
```

**Comment by nsoranzo** [comment]
Can't you just backport from dev?

**Comment by mvdbeek** [comment]
Sure, didn't know it was fixed on dev

**Comment by mvdbeek** [comment]
dev is still broken, fixing it would raise the linting error. But I see the data_lines calcualtion makes sense

**Review by nsoranzo — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thank you @nsoranzo!

**Pull request merged**
