### PR TITLE
Fix: rdata extension type

### PR DESCRIPTION
**Pull request by nturaga**
Typo.

### CODE REVIEW

**Comment by hexylena** [comment]
What exactly does this fix? Rdata has historically had that capitalisation in the extension, so I preserved it here.

**Comment by hexylena** [comment]
Ah, the second commit makes more sense.

**Comment by nturaga** [comment]
I think its just confusing, cause "rdata" is not a thing. I saw, and fixed it the wrong way :P

**Comment by hexylena** [comment]
:+1:

**Pull request merged**
