### PR TITLE
Readme changes

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Retroactive :+1: 

What do you guys think about moving the content of the `Issues` and `Galaxy Development` sections from `README.rst` to `CONTRIBUTING.md` and linking this document in the README? I feel that this information is already scattered between GitHub and the wiki.

That would be also a good time for splitting `Handling Pull Requests` from `CONTRIBUTING.md` to a new document (or to `doc/source/project/organization.rst`), as suggested by @jmchilton. In this way `CONTRIBUTING.md` would be no longer subject to the `Procedures` process.

**Comment by hexylena** [comment]
@nsoranzo yeah, I'd support all of that. :)

**Comment by martenson** [comment]
@nsoranzo Sounds reasonable. Open a PR :)

**Comment by nsoranzo** [comment]
@martenson: :stuck_out_tongue_winking_eye: 

Any opinion about `Handling Pull Requests` being either a separate document or integrated in `organization.rst`? @jmchilton?

**Comment by jmchilton** [comment]
@nsoranzo This sounds great to me!

**Comment by nsoranzo** [comment]
See PR #702.

**Pull request merged**
