### PR TITLE
Remove reset handler from ruler input element

### PR DESCRIPTION
**Pull request by guerler**
This PR attempts to revise the reset handling mechanism used in the ruler input element. The PR is not complete yet. ping @jmchilton

### CODE REVIEW

**Comment by jmchilton** [comment]
@guerler is this just marked as WIP because it is waiting on my input? I'll review and merge it if it works for me for 19.01 if you take it out of WIP.

**Comment by jmchilton** [comment]
Yeah - so I tested this and it doesn't work yet so I'm kicking this to 19.05. It is difficult to test since there is added validation in the rule builder modal that makes it harder to get it in an error state but I think this works:

- Open a list with the apply rules tool.
- Assign column A (generated from the list identifier) to be the target list identifier.
- Delete the rule that adds column A and save.
- Click "Execute" on the tool form.
- The rule element goes red.
- Now fix the rules by editing them and adding column A back using add column from metadata.
- Click save.
- In dev, this restores the rule element to its unerrored state. In this branch, the element is still in error.

Pushing my dev merge, but feel free to rebase it away.

**Review by jmchilton — CHANGES_REQUESTED** [review]
See comment in conversation.

**Comment by guerler** [comment]
Ah ok, thanks for the description on how to reproduce the mechanism. Thanks.

**Comment by guerler** [comment]
@jmchilton although the states remains red, is the tool executable after having fixed the rule configuration?

**Comment by jmchilton** [comment]
Re-ran the test I described and the same result. Yes, the tool can be executed - I feel like the dynamic check that it was good after returning to the tool form was good.

**Pull request merged**
