### PR TITLE
Remove tool form mako, reduce tool runner, fix job resubmission options

### PR DESCRIPTION
**Pull request by guerler**
This PR removes the tool form mako and reduces the tool_runner controller by redirecting the index and rerun actions to Galaxy root (see: https://github.com/galaxyproject/galaxy/pull/786/files#diff-99430eab480b0bc21518d808dff6ccdf). Now, the front-end handles tool_runner actions and renders all tool form routes without iframes (see: https://github.com/galaxyproject/galaxy/pull/786/files#diff-7079cdc7743e7207e726e8144a0b8142). The regular tool form is now consistently displayed with masthead, tools and history panels. Previously, this was not always the case e.g. https://test.galaxyproject.org/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fagordon%2Fdatamash_wrapper%2FDatamashReverse%2F1.0.6.
The PR revises the tool form error notifications e.g. a re-run attempt of an upload job does not leave the central panel empty (see: https://github.com/galaxyproject/galaxy/pull/786/files#diff-b2dc7e14d68766f211fa40a53c2eeb5dR122).
Finally the form customization is slightly revised. This fixes the resubmission options (see: https://github.com/galaxyproject/galaxy/pull/786/files#diff-637cc654035ea4e5fefc67e4d578be13).

See https://github.com/galaxyproject/galaxy/pull/768.

### CODE REVIEW

**Comment by dannon** [comment]
Most of this looks like it works fine, but upload is having a new problem.  This is the display after get data, paste in random text:

image

The upload tool form shouldn't be displayed there, and [object Object] looks like it might hint at another bug.

**Comment by guerler** [comment]
Thx, Dannon. I added a commit to hide the regular tool form for the upload tool. The "[Object]" content in the tool form looks right. The upload tool input parameter is not supported in the tool form and unavailable input parameters are matched to Text or Select fields (https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/form/form-parameters.js#L74).

**Comment by dannon** [comment]
@guerler Looks good, thanks for the fix!

**Comment by jmchilton** [comment]
So is every tool request going through the API now? Is it time to start gutting the tool class of cruft?

**Comment by nsoranzo** [comment]
This PR (the first commit in particular) breaks a Tool Shed test: `test_0020_verify_tool_image_link` in `test/tool_shed/functional/test_1140_tool_help_images.py`.

Reproduce with:

```
./run_tests.sh -toolshed test/tool_shed/functional/test_1140_tool_help_images.py
```

Output is:

```
======================================================================
FAIL: Load the tool page and verify the image link.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/tool_shed/functional/test_1140_tool_help_images.py", line 119, in test_0020_verify_tool_image_link
    self.load_page_for_installed_tool( tool_id, strings_displayed=[ image_path ] )
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/tool_shed/base/twilltestcase.py", line 998, in load_page_for_installed_tool
    self.check_for_strings( strings_displayed, strings_not_displayed )
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/base/twilltestcase.py", line 347, in check_for_strings
    self.check_page_for_string( string )
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/base/twilltestcase.py", line 458, in check_page_for_string
    raise AssertionError( errmsg )
AssertionError: no match to 'admin_toolshed/static/images/adb5f5c93f827949/count_modes.png'
page content written to '/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/tool_shed/tmp/tmpkEjnoO/twilltestcase-fPWPuc.html'

----------------------------------------------------------------------
```

**Comment by jmchilton** [comment]
I would generally be hesitant to just delete tests, but reworking this test for JavaScript would require rewriting it from scratch using the spaceghost stuff. I don't think that is worth anyone's time at this point.

**Comment by nsoranzo** [comment]
Fine for me, I will prepare a patch deleting `test_0015_install_htseq_count_repository` and `test_0020_verify_tool_image_link` from `test/tool_shed/functional/test_1140_tool_help_images.py` .

**Comment by guerler** [comment]
@nsoranzo Cool Thx.
@jmchilton Yes, we should do that. So data_source tools are still executed through the tool_runner controller and not the API but we can redirect these if necessary (https://github.com/guerler/galaxy/blob/e351107797f1d3bbccdd122dfcc5590f64c37a15/lib/galaxy/webapps/galaxy/controllers/tool_runner.py#L88). On the other hand "handle_input" is now only necessary to execute tools not to build forms. I followed up on this by removing more or less obvious parts from tools (https://github.com/galaxyproject/galaxy/compare/dev...guerler:tool_execution_000), maybe we can use this as a starting point.

**Pull request merged**
