### PR TITLE
Fix Galaxy.user to be available when not using 1 require

### PR DESCRIPTION
**Pull request by carlfeberhard**
Intermittent race condition here.

### CODE REVIEW

**Comment by guerler** [comment]
:+1:

**Comment by martenson** [comment]
I trust you on this one as I am not sure when the race condition happens.

**Comment by martenson** [comment]
ahh, @guerler is faster :)

**Comment by carlfeberhard** [comment]
@martenson That was a bit vague and cryptic - sorry.

I first noticed it in the multi-history panel. In this case, we've got two requires going at the same time: one via galaxy_client_mako in base_panels.mako and one in galaxy.masthead.mako loaded from galaxy/webapps/base_panels.mako. If the one from masthead.mako gets loaded first, it will generate the Galaxy.currUser but not the Galaxy.user which is now used in galaxy.menu.

Convoluted - but these issues should get more rare as the drive to simplify moves forward.

**Comment by martenson** [comment]
@carlfeberhard cool, thanks for explaining!

**Pull request merged**
