### PR TITLE
Add proxy, logo and example file for hivtrace

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by martenson** [comment]
can we trim down the 24k lines file?

**Comment by dannon** [comment]
Yeah, I used a much, much smaller example file they provided when I tested the original PR -- any of this sample test data we include in the repos should be minimal in size.

(edit: which is here, at https://raw.githubusercontent.com/veg/tools-iuc/master/tools/hivclustering/test-data/hivclustering-out1.json)

**Comment by guerler** [comment]
I removed the example file until we figure out where to place these larger test and demo files. The smaller test files are good for automated testing but often not helpful for user demos.

**Comment by bgruening** [comment]
Lets create a new repo called `test_data` and put it there. IUC needs something similar as well so we can share test data between tools easily.

**Comment by guerler** [comment]
It would have been nice if we could have kept the user demo files with the actual visualizations. The only reason they are part of the repo is that visualizations are still shipped with core. This is not optimal but it should not keep contributors from providing good examples. Eitherway, we can provide UI access to the example files to demo the visualizations.

**Comment by dannon** [comment]
I think just having a sample_data_url or something would work, right?  Easy enough for people to find and test, and we can have a bunch without worrying about bloat.  

And, can you please amend the first commit dropping that example?  (or rebase, whatever's easier for you).  This way we don't have the 50,000 changed lines in the history.

**Comment by martenson** [comment]
@bgruening we have that, right? https://github.com/galaxyproject/galaxy-test-data

**Comment by martenson** [comment]
@dannon we can squash on merge

**Comment by guerler** [comment]
Sounds good, Thanks.

**Comment by bgruening** [comment]
@martenson haha, yes we do :)

**Comment by dannon** [comment]
@martenson Yeah, we *could* squash on merge, but I don't generally want to do that to/for folks; I'd rather they rebase their own branches in most cases and be aware of the commits in the proposed PRs.

And, thanks @guerler!

**Comment by dannon** [comment]
We'll follow up on the examples, across the board for visualizations, using data from external sources (galaxy-test-data?) separately.

**Pull request merged**
