### PR TITLE
[16.01] Fix running workflows in the background when tool bursting is enabled.

### PR DESCRIPTION
**Pull request by jmchilton**
I'm pretty confident this will work but we should wait for the tests.

Should fix https://github.com/galaxyproject/galaxy/issues/2259.

### CODE REVIEW

**Comment by Takadonet** [comment]
Looks like the PR works but getting random jobs failing.  Not 100% sure it's related to tool bursting or other factors.

**Comment by Takadonet** [comment]
So it's tool burst fault.  Issue is that downstream jobs are not waiting for their inputs to be done before running themselves.  The check to ensure all inputs  dataset are 'ok' status is not being called or always returning true.

**Comment by Takadonet** [comment]
Taking a closer look into run.py. It see that __check_implicitly_dependent_step function is getting none Job and simply passing to else statement. https://github.com/galaxyproject/galaxy/blob/release_16.01/lib/galaxy/workflow/run.py#L224

Completely guessing here, could it be related to the new state that has '!' as its icon?

**Comment by dannon** [comment]
@jmchilton With tool bursting, is another thread guaranteed to be handling this and setting `workflow_invocation_step.job_id = job.id` here?  (`if job is None`, that is)

**Comment by jmchilton** [comment]
If `job is None` it is a non-tool step - like a data input step or subworkflow invocation step.

**Comment by dannon** [comment]
@jmchilton Got it -- I took `Job may not be generated in this thread if bursting is enabled` to mean there were multiple threads scheduling and the actual error here was crossing the object streams (which of course you never, ever want to do, per https://www.youtube.com/watch?v=jyaLZHiJJnE).

**Comment by jmchilton** [comment]
@Takadonet do you have workflows with implicitly connected steps - that means steps that are connect by connections that aren't on data parameters - this is a fairly esoteric feature still and there is no UI.

**Comment by Takadonet** [comment]
All my connections should be data parameters. Used UI to create it  and everything should be straight forward.  Here is my full workflow. http://imgur.com/LXx6uUC

**Pull request merged**
