### PR TITLE
Migrate to MyST-Parser for Markdown docs

### LINKED ISSUE #13005: Replace deprecated recommonmark with MyST parser
**Describe the bug**
Once we update to docutils >=0.17 we will hit https://github.com/readthedocs/recommonmark/issues/220 , which is not going to be fixed because recommonmark is deprecated in favour of [MyST parser](https://myst-parser.readthedocs.io/).

### PR DESCRIPTION
**Pull request by nsoranzo**
replacing deprecated recommonmark.

Fix https://github.com/galaxyproject/galaxy/issues/13005 .

Also:
- Drop not very useful ``doc/source/dev/file_upload.md`` .
- Use auto-generated table of contents in tool schema
- Small doc and link fixes
- Document documentation.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. `GALAXY_DOCS_SKIP_SOURCE=1 make -C doc/ html`
  2. Check the files in doc/build/html/ that are built from `.md` files in `doc/source/`

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Test failures unrelated.

**Review by bernt-matthias — COMMENTED** [review]
Thanks for the efforts. 

Wondering if we should include somewhere a link to the syntax of the docs (i.e. the syntax that MyST-Parser understands).

While working on the docs I was wondering why we have rst and md files. Are they treated differently? Do you know this by chance?

**Comment by bernt-matthias** [comment]
When looking at https://github.com/galaxyproject/galaxy/actions/runs/4517248665/jobs/7956302113?pr=15844#step:12:368 and below I was wondering if we could/should be stricter in this job, i.e. fail on any errors ...

**Comment by nsoranzo** [comment]
> While working on the docs I was wondering why we have rst and md files. Are they treated differently? Do you know this by chance?

The original format for Sphinx documentation was reStructuredText, but later support for Markdown was added, initially through recommonmark and now MyST-Parser.

> I was wondering if we could/should be stricter in this job, i.e. fail on any errors ...

The short answer is no, most of these are not real errors. We could try to tweak the `conf.py` to show fewer messages and reduce the noise.

**Comment by bernt-matthias** [comment]
> We could try to tweak the `conf.py`

I leave this up to you :)

**Review by bernt-matthias — APPROVED** [review]

**Comment by nsoranzo** [comment]
> Wondering if we should include somewhere a link to the syntax of the docs (i.e. the syntax that MyST-Parser understands).

Added some documentation about our documentation to `CONTRIBUTING.md`

> We could try to tweak the `conf.py` to show fewer messages and reduce the noise.

I made some decent progress on that, I think this is now good to go.

**Pull request merged**
