### PR TITLE
Remove Button Morphing during Tool Installation

### LINKED ISSUE #8716: remove 'install/cancel installation' button morphing
In 19.09 when in the admin interface you click 'install' on a repository it starts installation and the button is changing depending on the state (cloning/installing deps etc) but it also morphs into 'cancel' button (i.e. if you double click it it will both install and uninstall the repo) without even announcing it.

I suggest we separate install/cancel button and convey the state of installation somewhere next to the button, but not in the button name.

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
fixes #8716

Removes button morphing and separates status.
Adds a tool-tip to the "Reset" Action to communicate it's use.

image

~~This PR does not remove the button morphing, but fixes the simultaneous installing and uninstalling of a tool.
Looking into this issue I discovered that in the current version of Galaxy canceling the installation of a tool doesn't work. The uninstall request is sent, but the tool installation proceeds, and the tool is not uninstalled afterwards.
For this reason I removed the option to cancel an installation.~~

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
> The uninstall request is sent, but the tool installation proceeds, and the tool is not uninstalled afterwards.

That's true, but the state is inferred from the database state of the install process and the cancel operation is mostly meant to help with a installation that is stuck. E.g If you hard restart a Galaxy instance while it is in any of the progress states you still want to be able to "uninstall" the repo, because otherwise you're stuck and you will never be able to uninstall the repo. The whole process is broken, but without truly cancelable operations we can't touch this.

**Comment by ElectronicBlueberry** [comment]
Thank you for clarifying. I gave separating out the buttons a try, this is what it currently looks like:

image

**Comment by mvdbeek** [comment]
That looks great to me!

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
@ElectronicBlueberry Thanks, looks great!

**Comment by martenson** [comment]
@ElectronicBlueberry thanks for taking care of this!

**Pull request merged**
