### PR TITLE
Allow users to upload multiple FTP files within a single request

### LINKED ISSUE #4347: Select all files in FTP Upload has underwhelming performance
When having multiple files in the FTP folder, selecting all of them with the check box on the top left in the `Choose FTP file` window causes Chrome to consume 35% CPU usage and sending a kill-alert since it takes minutes to do this action. 

In my cause: 768 files with 3.9GB size.

I'm not talking about #1090, which is a bigger issue by itself, instead just the selection of the FTP files (which has been mentioned there as well, but is technically not related since this is probably purely client side).

### PR DESCRIPTION
**Pull request by guerler**
This PR adds another tab to the uploader view which allows users to submit multiple FTP files at once. In contrast to the regular upload view, this option does not allow the selection of individual datatypes or genome builds per ftp file. All ftp files are submitted using the same datatype/genome specification. However, the advantage is that all FTP files can be submitted to the upload tool at once, which improves the performance for large sets. Fixes #4347 and #1090.

### CODE REVIEW

**Comment by guerler** [comment]
@martenson we should discuss some potential further improvements, particularly if the goal is to effectively upload all files in a FTP directory or folder.

**Comment by bgruening** [comment]
I would also raise the issue of usability here. FTP is already quite confusing for many users, adding a second route will only complicate this. I have no clue how but we need to communicate this very well.

**Comment by guerler** [comment]
@bgruening I agree, the issue is that one allows to specify datatype and genome build for individual ftp files and the other does not. I am wondering if it would be better to restrict this option for uploading all ftp files in a ftp directory. Alternatively we could disable the ftp uploader in the regular upload view to avoid any confusion. Another problem is that adding all ftp files to a collection still suffers from performance issues. I am open for suggestions. Thanks for looking into it.

**Comment by guerler** [comment]
The last commit helps a lot with the performance of the FTP viewer, it might not be necessary to restrict the upload to 'all' files only, fyi.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
The toolshed test failure was caused by the tool shed being down I think, but the qunit test failure is legitimate I think right?

**Comment by jmchilton** [comment]
Now that I've tried this out - I have to say I'm as concerned as @bgruening about this. Loading up some files in the regular uploader looks a lot like the FTP dedicated uploader:

screen shot 2017-09-03 at 8 41 32 pm
screen shot 2017-09-03 at 8 41 42 pm

The only real visual difference is that I get more flexibility with the regular uploader. Wouldn't the solution to this be to just use the regular uploader and then optimize what happens when you click "Start" so that all FTP uploads get grouped together and uploaded via one call. I get that the programming for that is going to complicate the models - but I feel like it is better to make them more complex than make the interface more complex. I feel like this would make it very natural to apply such an optimization to the collection uploader as well - which a lot of these large uploads I would imagine would be.

I'm a pragmatist - I'd definitely be onboard for advanced UIs that were more limited if they were describing rules and hiding files that would somehow preclude using the existing UI elements - but this doesn't feel fundamentally different, it feels like we just need to optimize the requests generated. That said - I may be totally wrong and the different UI elements like drop downs and such may preclude large lists of files from rendering properly or something. Feel free to correct me if that is the case.

If #4505 is merged, I'll open a PR containing [this commit](https://github.com/common-workflow-language/galaxy/pull/47/commits/9e8f4176913c4e2799134adc1336301f20a4884c) which allows more configurable tool upload requests that would allow for multiple configuration of individual upload URLs ``files_N|`` options. That may be helpful if the backend doesn't quite support the level flexibility that would be representable in the UI form with optimization described above applied.

**Comment by guerler** [comment]
I agree with both of you and appreciate the detailed reviews. @jmchilton points definitely into the right direction. It would be nice to use the same ui for both. This would require additional changes. The difference is that one ui allows to select individual datatypes and genome builds per ftp file using individual requests and the other one fixed type/build through a single request. A solution would be to filter all ftp files which use the same datatype/genome build and pack them into a single request. We would then take these out of the queue. Additionally the individual row-views shown in the regular view need to be augmented to allow pagination or lazy loading in order to display +1k entries. In other words the above experiment would not work for a few thousand files. Since this is a pressing issue I think it would be nice to provide this addition for the next release and then continue with additions as suggested by @jmchilton. I can definitely help. Many of the changes here will be useful regardless which route we take. Ultimately it is up to you guys. I could change the PR by removing the additional tab and reduce the PR to the general improvements which are helpful in either case. Thanks again.

**Comment by guerler** [comment]
I am implementing the lazy loading of views for the regular uploader view fyi.

**Comment by jmchilton** [comment]
Awesome - thanks for working on lazy loading that @guerler - that sounds like a good enhancement.

> A solution would be to filter all ftp files which use the same datatype/genome build and pack them into a single request. 

Maybe we are not on the same page - but this doesn't seem like it should request separate requests for each combination of dbkey and extension. I'd do one request for all the files - the dbkey and extension can be specified on a per-file basis depending on how you structure the request - at least with https://github.com/common-workflow-language/galaxy/commit/711504a2051712827de973c09003419f63702d4e it can. I'd start with a separate ``files_N|`` entry per file and then once that is done we could reduce the request size a bit by combining similar files together but we might never need to go that far.

**Comment by guerler** [comment]
Cool, I did not know that the upload tool allows specifying different build/datatype pairs for multiple ftp files within one request. That would be even better. So regarding the lazy loading we have two options which both work fine now. One is to lazy load all entries as long as the user is scrolling, another one is to limit the view to the first N entries and show a message to the user at the bottom when the limit is reached. If an entry is removed the next in line is shown. Both work fine and are commited within this PRs history but the latter requires less resources which is why I have chosen it for now. Integrating these for composite uploads should be easy too.

**Comment by martenson** [comment]
Do I need to do something else than checkout `guerler/ftp_uploader` and start Galaxy to test this? Because I cannot see the ftp tab.

**Comment by guerler** [comment]
@martenson thats the correct branch, we embedded the performance improvements into the regular uploader and removed the ftp tab. You could test the performance differences by selecting many ftp files in the regular view and then by clicking on start with and without this PR. However the multifile submission with differing dbkey/datatypes is still in the works.

**Comment by martenson** [comment]
That means we are still stuck with the popover-over-modal view into FTP directory. I think we need to improve on this to use actual tree-based folder browser. (And maybe move the whole upload view into mid pane instead of a modal to give it more of a canvas.)

Nevertheless this PR does not seem to be working for me. Nothing gets imported to history.

screenshot 2017-09-06 17 24 30

**Comment by guerler** [comment]
@martenson as I mentioned `However the multifile submission with differing dbkey/datatypes is still in the works`. All you can test are performance differences in working with large ftp file sets. I let you know when the submission feature for the backend works. See also: #4563.

**Comment by martenson** [comment]
@guerler I selected 4 FTP files and nothing got imported into history. All have `autodetect` and `?`. I did not even see a request to upload in the devtools.

**Comment by guerler** [comment]
@martenson that is correct the submission to the backend has to be added. I let you know when we added it.

**Comment by guerler** [comment]
Requires #4563.

**Comment by jmchilton** [comment]
Thanks for moving the milestone @guerler - sorry I wasn't able to get #4563 done in time for the release.

**Comment by jmchilton** [comment]
Very nice - thanks for this!

**Comment by guerler** [comment]
Thank you. Thanks a lot for #4563 and your overall help with this.

**Pull request merged**
