### PR TITLE
Add idpDB and HDF5 sniffers and fix MzSQlite sniffer

### PR DESCRIPTION
**Pull request by chambm**
Move idpDB and MzSQlite formats from proteomics.py to binary.py, because the SQLite sniffer lives there, and more specialized formats must be registered for sniffing before the generic format
Add proper idpDB sniffing logic (akin to MzSQlite) and test case
Add H5 sniffing based on magic number and test case
Add SQLite/IdpDB/MzSQlite/GeminiSQLite and H5 to default datatypes in registry.py

### CODE REVIEW

**Comment by chambm** [comment]
Hurray!

**Comment by martenson** [comment]
yay! :)

**Comment by martenson** [comment]
@galaxybot test this

**Comment by chambm** [comment]
It looks like that build timed out?

**Comment by blankenberg** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
:+1:

**Pull request merged**
