### PR TITLE
Updates interactor to not ignore numbers in user email address 

### PR DESCRIPTION
**Pull request by VJalili**
All the following email addresses would resolved to a common `user--test--com` username:
- user@test.com
- user1@test.com
- user10@test.com

This PR updates the email-to-username regular expression to accept alphanumeric.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thanks @VJalili !

**Comment by VJalili** [comment]
@mvdbeek thanks for merging.

**Comment by mvdbeek** [comment]
Thanks for fixing it! I think this might also solve the failing test in https://github.com/galaxyproject/galaxy/pull/8299

**Comment by VJalili** [comment]
I guess so, I see `user1_for_users_index_test@bx.psu.edu` and `user2_for_users_index_test@bx.psu.edu`, both of these would otherwise resolve to a common email address: `user_for_users_index_test@bx.psu.edu`

**Pull request merged**
