### PR TITLE
Fix "Latest Updates" order in tool shed 2.0

### LINKED ISSUE #16812: the list of newest repositories on TS2.0 is incorrect
it shows the same repos as the "last updated" list

Galaxy_Tool_Shed

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes https://github.com/galaxyproject/galaxy/issues/16812 probably.

## How to test the changes?
(Select all options that apply)
- [x] Instructions for manual testing are as follows:
  1. Deploy to test and see if the respective lists are different now.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
Since that's client-side only, is there a way to check against the test toolshed, similar to what we're doing with `CHANGE_ORIGIN=true GALAXY_URL="https://usegalaxy.eu/" yarn run develop` ?

**Comment by jmchilton** [comment]
I'm not having any luck getting this working. I'd love help though if people have ideas - I've tried to use vite's server proxy stuff and I get stuff like this:

```
{
    "err_msg": "Wrong guid ''eb142648ac45b77092f9904b054a3582ab8ebce106f8a2763d8a48a7b95723c4c971061715c49c74'' specified, unable to decode.",
    "err_code": 400009
}
```

Which I think is coming from the testtoolshed. A cookie issue I suppose.

**Comment by martenson** [comment]
Is this the one you'd like reviewed @jmchilton?

**Comment by mvdbeek** [comment]
Thanks, that makes sense!

**Pull request merged**
