### PR TITLE
Lint for whitespace in tool XML

### PR DESCRIPTION
**Pull request by neoformit**
Address issue #12207 

Whitespace is quite easily introduced into the tool XML `version` and `name` properties through the use of tokens:

```xml
<!-- This results in version=" 0.0.1 " -->
<token name="@TOOL_VERSION@"> 0.0.1 </token>
```

@bernt-matthias suggested it would be better to lint for hazardous whitespace rather than parse it out since there are cases where whitespace may be required in tokens. This PR adds some extra linting to warn users of whitespace in `<tool>` and `<requirement>` `name`/`version` which might cause errors. An additional test was added to `test_tool_xml.py` to cover this linting.

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@neoformit thanks. looks great. can you fix the linter error:

```
 ./test/unit/tool_util/test_tool_linters.py:4:1: I101 Imported names are in the wrong order. Should be general, inputs
```

**Comment by neoformit** [comment]
@bernt-matthias Done :)

**Review by bernt-matthias — APPROVED** [review]
Fine from my side. Thanks a lot.

**Comment by jmchilton** [comment]
Awesome - thanks so much!

**Pull request merged**
