### PR TITLE
Fix data library test case

### PR DESCRIPTION
**Pull request by guerler**
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
Thx @dannon

### CODE REVIEW

**Comment by martenson** [comment]
I scheduled an -api test for this, the results will be here: https://jenkins.galaxyproject.org/job/docker-api/514/

**Comment by guerler** [comment]
Would be interesting to know when/how this behavior changed.

**Comment by jmchilton** [comment]
To me this test case seems to indicate the upload options have changed their defaults, it is totally possible there is a different explanation but I'd like to know the exact commit and reason before merging. I'll try to find some time today to check it out more.

**Comment by nsoranzo** [comment]
@guerler @jmchilton `git bisect` says that https://github.com/galaxyproject/galaxy/commit/abf16905d600a75dbc80c1b011c16bc05ad894f1 is the commit which broke the `test/api/test_tools.py:ToolsTestCase.test_library_data_param
` test.

**Comment by jmchilton** [comment]
@nsoranzo Thanks, yeah I would say we should restore the old upload behavior rather than modify the test case then. `test_tools.py` has upload test cases but they all include trailing newlines otherwise I suspect we would see similar failures with the main tools API as well, which could be a big user-facing deal.

**Comment by guerler** [comment]
Thx @nsoranzo. It seems to be this change: https://github.com/galaxyproject/galaxy/commit/abf16905d600a75dbc80c1b011c16bc05ad894f1#diff-ea323c797d61436a197cc1bc63e0af0bL480
Was discussed in https://github.com/galaxyproject/galaxy/pull/829. Looking more into it.

**Comment by nsoranzo** [comment]
@guerler Reverting only the line you suggested (on the current `dev` branch) does not change the test result.

**Comment by guerler** [comment]
Thx @nsoranzo. I checked it and it seems to be this change: https://github.com/galaxyproject/galaxy/commit/abf16905d600a75dbc80c1b011c16bc05ad894f1#diff-a984f7650cdf2b60a68eac1d14167a81L1047. It was discussed in: https://github.com/galaxyproject/galaxy/pull/829. In dev we already moved further and removed the UploadDataset handling from update_state, if we re-add it the test should pass:
https://github.com/galaxyproject/galaxy/compare/galaxyproject:dev...guerler:fix_library_test_001?expand=1.
@jmchilton called it. The test breaks because update_state does not set the 'to_posix_lines' flag to the default value (='Yes') for the upload tool but populate_state does. We can test this by changing the default value to pass the test case: https://github.com/galaxyproject/galaxy/compare/galaxyproject:dev...guerler:fix_library_test_002?expand=1.

**Comment by jmchilton** [comment]
@guerler So does this mean data library uploads have been broken since we added `to_posix_lines` (i.e. the files would be treated differently by default than the default for the main tool form)?

**Comment by martenson** [comment]
@jmchilton does 'differently'  mean that problems with tool would arise?

**Comment by guerler** [comment]
@jmchilton When was the parameter added? Its not listed in the library specific upload mako: https://github.com/galaxyproject/galaxy/blob/dev/templates/webapps/galaxy/library/common/common.mako.
@martenson I think it means that to_posix_lines is by default set to 'No' for library uploads and 'Yes' for regular uploads.

**Comment by guerler** [comment]
@martenson It means that to_posix_lines is by default set to 'No' for library uploads and 'Yes' for regular uploads.

**Comment by jmchilton** [comment]
:+1:

I'm willing to say that abf16905d600a75dbc80c1b011c16bc05ad894f1 fixed a bug in data library upload code and this test case is being updated to reflect the fix.

We should add a test case to the regular tools API to ensure it is not appending new lines and functional test through the both the library and and normal upload routes to ensure they are creating the same files. We probably won't do these things, but we should :smile:.

**Comment by guerler** [comment]
It seems that this PR fixes an incorrect test case and that the previous PR https://github.com/galaxyproject/galaxy/pull/829 fixed the tools default value handling. The tools default value should have been taken in the first place.

**Comment by guerler** [comment]
Thats good. Thx for the help to track it down.

**Comment by martenson** [comment]
@jmchilton library upload should disappear next release, so we probably do not need test for that

**Comment by guerler** [comment]
I agree. This should be legacy in the next release.

**Comment by nsoranzo** [comment]
:+1: to merge this, any objections?

**Pull request merged**
