### PR TITLE
Increase release delta to 4 months ahead of 17.05.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by martenson** [comment]
👍

**Comment by jmchilton** [comment]
Thanks for the typo fix @martenson!

**Comment by mvdbeek** [comment]
:+1:

**Comment by dannon** [comment]
+1

**Comment by hexylena** [comment]
:+1:

**Comment by bgruening** [comment]
:+1:

**Comment by jxtx** [comment]
+1

**Pull request merged**
