### PR TITLE
GoDocker runner for Galaxy

### PR DESCRIPTION
**Pull request by varunshankar**
**Google Summer of Code 2016: Open genome informatics
_Project Idea 13: Using Go-Docker to enhance Galaxy functionalities_**

A REST based runner for executing Galaxy jobs using GoDocker.

Go-Docker is a cluster management tool using Docker as execution/isolation system. It can be seen like Sun Grid Engine/Torque/… Using Bioinformatics dedicated Docker hub as BioShaDock, it allows Life scientists to use powerful tools in a easy and secure way while finely managing infrastructures resources. Galaxy is a user-friendly web platform originally dedicated to life sciences data analysis. If Galaxy provides amazing functionalities to enhance transparency, accessibility and reproducibility of data analysis related processes, there is still opportunities to provide more reproducibility and flexibility in the manner of using this web platform. This project idea is to integrate the Go-Docker system with Galaxy.

Galaxy is designed to run jobs on your local system by default, but it can be configured to run jobs on a cluster. The front-end Galaxy application runs on a single server as usual, but tools are run on cluster nodes instead. Here, we use GoDocker system to manage authentication, scheduling and execution of jobs.

### CODE REVIEW

**Comment by nturaga** [comment]
hi @varunshankar , it'd be helpful if you post some instructions on how to test your PR.

**Comment by osallou** [comment]
Hi,
I am the mentor of the GSoC project. Testing needs a GoDocker cluster, so not so easy... Varun may share privatly however the credentials and config for the virtual machine we used for testing/validation. Galaxy and GoDocker need to share a directory (Galaxy jobs dir), so you cannot test a local galaxy against a remote cluster. For the project we have setup a VM with Galaxy (latest dev branch) and GoDocker. We used it all along the project with sample tools.
The runner needs to be defined in config, as well as destination with specific params (as documented in config advanced sample). It also makes use of the docker image name in tool config or using default_docker_image param (or something like that, I don't remember exact param name).

**Comment by nturaga** [comment]
@varunshankar You seem to have pylint issues in the PR. And that would be very helpful @osallou (share via email, the credentials needed). Just saw that he was corresponding with @dannon earlier regarding the PR.

**Comment by osallou** [comment]
@varunshankar will share credentials and access with you  to access the VM
we used for testing. He is working on pylint fixes.

@varunshankar please give him also galaxy code location on vm, url access
 etc...

**Comment by osallou** [comment]
@dannon is indeed in the loop as part of the gmod gsoc projects and is our
galaxy team "contact" for this gsoc project.

Le mar. 26 juil. 2016 11:56, olivier sallou olivier.sallou@gmail.com a
écrit :

> @varunshankar will share credentials and access with you  to access the VM
> we used for testing. He is working on pylint fixes.
> 
> @varunshankar please give him also galaxy code location on vm, url access
>  etc...

**Comment by bgruening** [comment]
@osallou if you can create a GO-Docker Docker Image, we can test it easily with the Galaxy Docker Image. For example see this test case for the SLURM scheduler here: https://github.com/bgruening/docker-galaxy-stable/tree/dev/test/slurm

**Comment by osallou** [comment]
GoDocker makes use of docker to run images, so it is not so easy. It also
needs to share galaxy job directory and additional config (project with
galaxy dir). We made this in a test vm, we shared credentials with dannon.

A docker image already exists (osallou/go-docker) .

Le jeu. 4 août 2016 13:33, Björn Grüning notifications@github.com a
écrit :

**Comment by bgruening** [comment]
@osallou sharing the job-working directory is the same for SLURM, so this should be solved already. Docker in Docker is also working as we have support for ht-Condor with the Docker universe enabled.

**Comment by osallou** [comment]
You can use the docker image, there is documentation on docker hub. But
there is config to adapt, a user to create with same uid/gid than galaxy
user and a project to create that galaxy user will use.
I think it will be a little complex.
However, if this is ok for you, i could create a vagrant box with docker
and godocker preinstalled and configured. Then you would only have to
install/setup galaxy in the box. Would it be fine?

Le jeu. 4 août 2016 13:54, Björn Grüning notifications@github.com a
écrit :

**Comment by dannon** [comment]
@osallou I'd actually be interested in that too!

**Comment by osallou** [comment]
Hi,
I have created the vagrant box for Galaxy testing.
Box and instructions are available at:

https://atlas.hashicorp.com/osallou/boxes/godocker-galaxy

I have given credentials etc... Galaxy must be installed under /opt/shared and run with vagrant user.

Olivier

**Comment by dannon** [comment]
Thanks @osallou, can't wait to check this out!

**Comment by dannon** [comment]
@osallou had to jump through a few hoops with virtualbox extensions, but the vagrant box is working great now; testing today.

**Comment by osallou** [comment]
Virtualbox extensions are indded not installed but should not be necessary, i could make simple tests without them.

**Comment by dannon** [comment]
Perhaps linux/osx difference?  The box was attempting to set up shared folders, which would cause it to crash until I ssh'd in and manually installed guest additions on the box.

**Comment by dannon** [comment]
Very strange.  When I merged #2700, this was merged as well?

**Comment by dannon** [comment]
(in any event, I have some tweaks to logging and a few questions, but this was 'safe' to merge as it was)

**Comment by nturaga** [comment]
@dannon Yeah, this is pretty strange. Not sure how it was linked.

**Comment by dannon** [comment]
@nturaga This wasn't actually merged, github is just very, very confused.

**Comment by nturaga** [comment]
Yep, I see that now. It still says "merged" but the changes don't show in the dev branch. Cheers @dannon !

**Comment by nsoranzo** [comment]
@dannon GitHub is not confused, #2700 contains all commits of this PR and then reverts the changes in subsequent commits.

**Comment by dannon** [comment]
@nsoranzo Makes sense.  That's what I get for looking at the files-changed view instead of trawling through all the commits.

**Comment by dannon** [comment]
@varunshankar For future work, it's best to always develop independent features on isolated feature branches so this sort of thing doesn't happen.

**Comment by varunshankar** [comment]
@dannon I apologize for the inconvenience caused. I thought the runner would be merged first and then the document. Anyway, will take care of such things in future.

**Pull request merged**
