### PR TITLE
Make admin user list sortable by last login

### PR DESCRIPTION
**Pull request by cat-bro**
Add a sort function for Last Login column on the Admin User list (paper cut issue https://github.com/galaxyproject/galaxy/issues/13027)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

I haven't written a test for this.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by cat-bro** [comment]
Screen Shot 2022-01-20 at 5 07 39 pm

**Comment by bgruening** [comment]
Nice, can we do this for disc usage as well?

**Comment by cat-bro** [comment]
disk usage is sortable.  The columns that are still not sortable in the list are group count and role count.

**Comment by dannon** [comment]
@cat-bro Thanks, looks good!

**Pull request merged**
