### PR TITLE
Attempted fix for server error on repo preview.

### PR DESCRIPTION
**Pull request by davebx**
This should handle cases where the database record specifies a repository dependency, but the repository in question (and its downloadable changeset) has been updated since the dependency was created.

This should address #2076.

### CODE REVIEW

**Comment by martenson** [comment]
with this applied, when trying to show mummer, I am still receiving the error of 

```
Error - <class 'urllib2.HTTPError'>: HTTP Error 500: Internal Server Error
URL: http://127.0.0.1:8080/galaxy/admin_toolshed/preview_repository?tool_shed_url=https%3A%2F%2Ftesttoolshed.g2.bx.psu.edu&tsr_id=93b4a316b22b85e2
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/base.py', line 131 in __call__
  return self.handle_request( environ, start_response )
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/base.py', line 190 in handle_request
  body = method( trans, **kwargs )
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py', line 89 in decorator
  return func( self, trans, *args, **kwargs )
File '/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py', line 1280 in preview_repository
  toolshed_data[ 'metadata' ] = json.loads( util.url_get( tool_shed_url, pathspec=[ 'api', 'repositories', tsr_id, 'metadata' ] ) )
File '/Users/marten/devel/git/galaxy/lib/galaxy/util/__init__.py', line 1380 in url_get
  response = urlopener.open( full_url )
File '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py', line 437 in open
  response = meth(req, response)
File '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py', line 550 in http_response
  'http', request, response, code, msg, hdrs)
File '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py', line 475 in error
  return self._call_chain(*args)
File '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py', line 409 in _call_chain
  result = func(*args)
File '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py', line 558 in http_error_default
  raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by davebx** [comment]
@galaxybot test this now that #2130 has been merged.

**Comment by martenson** [comment]
this ts test fail seems unrelated to #2130

**Comment by davebx** [comment]
I would tend to agree. I'll have another look at the code, it passed locally last time I checked.

Now, however, it fails. I'll be pushing an update today.

**Comment by martenson** [comment]
thanks @davebx

**Pull request merged**
