### PR TITLE
Misc fixes 202412

### PR DESCRIPTION
**Pull request by nsoranzo**
End-of-the-year clean up of my git stash :)

See individual commit messages for details.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Test failures unrelated.

**Comment by davelopez** [comment]
Would it be interesting to backport any of the fixes? :innocent:

**Comment by nsoranzo** [comment]
> Would it be interesting to backport any of the fixes? 😇

Commit 4e650b4 yes, not sure about the others, but let me know if you have some in mind.

**Comment by davelopez** [comment]
Yes, that looks like an interesting one! Thanks! :pray:

**Review by mvdbeek — APPROVED** [review]

**Pull request merged**
