### PR TITLE
[16.04] Release notes for 16.04

### PR DESCRIPTION
**Pull request by martenson**
generated notes with basic manual curation
please create PRs or directly modify at my fork

@galaxyproject/core

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@martenson How do you want to do #1757?

**Comment by martenson** [comment]
@carlfeberhard you are quick :); I was just adding that - it is done now

**Comment by carlfeberhard** [comment]
Awesome - thanks, @martenson !

**Comment by natefoo** [comment]
Looks like the final bitbucket release message didn't make it into the deprecations?

**Comment by nsoranzo** [comment]
@natefoo I was also wondering about that, but there is still time to add it!

**Comment by martenson** [comment]
Please review and modify as you please @galaxyproject/core - I will push for a release tomorrow.

**Comment by martenson** [comment]
please review and merge

**Comment by jmchilton** [comment]
I'll expand on the tools stuff and merge before doing the release tonight

**Pull request merged**
