### PR TITLE
Merge 16.01 into dev.

### PR DESCRIPTION
**Pull request by nsoranzo**
I've built the JS and less in `static/` with:

```
cd client/
npm install
grunt
grunt style
```

Hope that's correct!

### CODE REVIEW

**Comment by dannon** [comment]
@nsoranzo 'make client' from the root directory should build everything required, calling the other tasks as necessary.  This looks fine to me, though.

**Comment by dannon** [comment]
(merging when tests pass, as a sanity check)

**Comment by nsoranzo** [comment]
@dannon: Thanks for the tip! `make client` ran fine on my branch, producing no changes.

**Comment by dannon** [comment]
Changed my mind -- we haven't typically waited for tests to run in the past for branch merges -- tested locally and it runs, so merging.

@nsoranzo Yep, tried the same thing here, looks good.

**Pull request merged**
