### PR TITLE
Update GPU Jupyterlab interactive tool

### PR DESCRIPTION
**Pull request by anuprulez**
This PR adds two features to the GPU-enabled JupyterLab interactive tool:

1. Run as a tool. This feature has been inspired by Jupytool (https://github.com/galaxyproject/galaxy/pull/13606). This GPU-enabled Jupyterlab can also be used as a tool and it can execute an Ipython script (in `previous` mode) and create datasets in a Galaxy history similar to many other Galaxy tools in addition to opening several default notebooks when run in `scratch` mode.

2. `Root` user has been removed from the Docker container (https://github.com/anuprulez/ml-jupyter-notebook/blob/resize/Dockerfile) as well as from the tool's definition. To provide permissions to the custom notebook user to Galaxy's datasets, `$default_file_path` parameter in job_conf.xml should be set to read-write (`$default_file_path:rw`). Alternatively, to assign necessary permissions to this custom user, the properties `docker_volumes` from job_conf.xml and `outputs_to_working_directory` in galaxy.yml should not be set.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x ] Instructions for manual testing are as follows:
  1. Bring Galaxy's config (galaxy.yml) and job_conf.yml config changes used for running interactive tools (galaxy.yml.interactivetools and job_conf.xml.interactivetools). In addition, in "docker_volumes" of job_conf.xml, the permission of `$default_file_path:rw` should be set as read-write. Since, the notebook's container and associated script run with custom user's permissions, this user does not have permission to use Galaxy's datasets.
  2. Include this tool in the Galaxy's default list of tools (configure in tool conf)

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

gpu_jupyterlab_1

gpu_jupyterlab_2

gpu_jupyterlab_3

gpu_jupyterlab_4

gpu_jupyterlab_5

### CODE REVIEW

**Comment by anuprulez** [comment]
@dannon I think this PR is more relevant as compared to this one: https://github.com/galaxyproject/galaxy/pull/15107. https://github.com/galaxyproject/galaxy/pull/15107 PR I opened erroneously (this points from usegalaxy-eu and not from the latest galaxy dev branch) and was not able to close. 

I will fix the review relevant comments mentioned in https://github.com/galaxyproject/galaxy/pull/15107 by @jdavcs in this PR. What do you think?

**Comment by dannon** [comment]
@anuprulez Ahh, of course!  Sorry we didn't notice the source branch when we were triaging these on the pre-freeze call, and assumed this one was the one opened in error.

**Comment by jdavcs** [comment]
@anuprulez  Is this indeed a replacement for #15107? I'm asking because that PR includes modifications to 32 files, this one - only one. Are all those files/modifications in the previous PR no longer relevant?

**Comment by anuprulez** [comment]
I am closing this because there is another PR (https://github.com/galaxyproject/galaxy/pull/15297) for updating the tool

**Pull request closed without merging**
