### PR TITLE
Allow data parameters to specify optional defaults.

### PR DESCRIPTION
**Pull request by jmchilton**
A lot more could be done here - support for multiple="true" parameters, collections, testing with identifiers, better error reporting if DatasetWrapper methods are used. I'll follow up with those things if people find the current approach acceptable.

Implements #1682.

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
A default file seems useful to me. It could maybe also serve for tool demonstrations too.

I would like to hear from @blankenberg and/or @bgruening on this. Gentlemen?

**Comment by bgruening** [comment]
As I said in the original issue I'm missing a solid use-case that is not addressed by already existing features of Galaxy.

I see two problems:
- Users: The concept of having a default dataset in your `data` select box that is not in your history is confusing. We are teaching that you can select datasets from your history and now there is one dataset that is not part of your history - which you can not see - some kind of black magic.
- Developers: Currently we do have a strict separation between tools and tool-data, this feature will open the door for all kind of bad-practices.

If we want to have something like a profile for each tool with predefined options we should implement this on top of tools.

**Comment by jmchilton** [comment]
I give up I guess, I'm not happy about it.

**Pull request closed without merging**
