### PR TITLE
[18.05] "Fix" rule builder to auto decompress uploaded files.

### PR DESCRIPTION
**Pull request by jmchilton**
Mentioned in other issues and on Slack but it sounds like this is important use case. It can be considered a fix in that the different parts of the UI behave very differently and that is confusing. Also the work arounds for dealing with large collections of compressed data are not quite there yet so this is really needed. This includes a few different fixes for @natefoo's big upload refactoring this release as well and synchronization of the upload.py and data_fetch.py code (the PR is more red than green). If you are wondering why upload.py and data_fetch didn't share more in common earlier - it is because @natefoo and I both had big competing, concurrent refactorings of upload.py this release but his won out - so my synchronizations of data_fetch and upload.py never made it.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hmm, so if I have a list of fastq.gz files and I set the filetype to fastqsanger.gz, will they be decompressed, or does this only apply to `auto` ? 

Also it seems that the ~~only~~ major issues with implicit conversions and collections are in the UI, running workflows on collections that require implicit conversion via the API works fine, last time I tried. Maybe we could instead work on that ?

**Comment by jmchilton** [comment]
> so if I have a list of fastq.gz files and I set the filetype to fastqsanger.gz, will they be decompressed

Sorry for the confusion. Absolutely not, this synchronizes this behavior with the upload API which likewise does not do that. auto_decompress really means I guess "decompress if not sniffed as compressed or explicitly specified as compressed".

> running workflows on collections that require implicit conversion via the API works fine

Hmm.. I didn't know that. We should work on that for sure - I'm not sure if we should do that "instead" of this though.

**Comment by mvdbeek** [comment]
Cool, I agree, that sounds right!

**Comment by martenson** [comment]
Just finished testing it, works well for me. Thanks @jmchilton !

**Pull request merged**
