### PR TITLE
RFC: An example to showcase Vue JS

### PR DESCRIPTION
**Pull request by anuprulez**
This PR showcases a simple usage of Vue JS while converting a mako file to pure javascript.

apikey

Mako file for showing a list of users with their respective API keys for the admin screen is migrated to pure javascript using Vue JS. We make use of the binding property of Vue to stitch a UI element with a model or an event.

For example:

`<tr v-for="user in users">` repeats the creation of `tr` tag
`v-on:click="generateKey( user.uid )"` binds an onclick event to the button

This binding helps us doing away with multiple DOM manipulation operations. With Vue, we can just update the complete model with the fresh data (for example, coming after AJAX update) and the view is updated accordingly with no separate DOM manipulation operation required. There is no recreation of UI elements - just their model needs to be updated. In short, it helps us reduce the lines of code in client-side scripts.

Moreover, the inclusion of Vue library is simple. We can just place the library file at:
`client/galaxy/scripts/libs/vue.js` and access it in our scripts as `libs/vue`. It also coexists with backbone view. HTML template inside the backbone view is bound with a model. 

It is about one day's work. But for complex pages, it can take more time to migrate. 

For repeated elements, we can create [components](https://vuejs.org/v2/guide/components.html). Many side components related to Vue are available [here](https://github.com/vuejs/awesome-vue#components--libraries).

Please let us know your views on this.

Thanks a lot @bgruening

### CODE REVIEW

**Comment by dannon** [comment]
(set 18.01 milestone -- IMO we should do this *after* the freeze and build process updates that'll allow us to avoid adding vue.js to the codebase unpacked, etc)

**Comment by bgruening** [comment]
This PR is meant to try things out and give people more space to test things. It is not intended for being merged. I don't think we have yet decided for Vue or React - so this is just us playing around for the moment.

**Comment by dannon** [comment]
@bgruening Yep, just wanted to indicate it shouldn't hold up release, is WIP, etc.  Looks promising, to me at first glance, easy to replace small bits at a time!

**Comment by martenson** [comment]
This is awesome @anuprulez ! 🎉  Thank you very much for trying Vue out. How do you feel about the paradigm/Vue after trying it on Galaxy?

**Comment by jxtx** [comment]
Very cool. We should probably try to use vue's single file components since that will cleanup the inline templates a lot. But that probably depends on babel?

**Comment by bgruening** [comment]
@dannon es6 is not working for us. `CurrentHistoryView is not defined` and `Uncaught ReferenceError: app is not defined`. `make client` runs fine.

**Comment by dannon** [comment]
@bgruening I'll check it out, thanks for the heads up!

**Comment by anuprulez** [comment]
@dannon I tried to pull code from https://github.com/dannon/galaxy/tree/es6
but got the following error while doing `'make client'`

```
anupkumar@anupkumar-pc:~/galaxy/es6/galaxy$ make client
cd client && yarn
/bin/sh: 1: yarn: not found
make: *** [node-deps] Error 127

```

thanks!

**Comment by bgruening** [comment]
@anuprulez https://yarnpkg.com/lang/en/docs/install/ :)

**Comment by dannon** [comment]
@anuprulez @bgruening Yeah, it looks like I probably broke this in a recent commit to the es6 branch; I'll follow up on that after the 17.09 release and we can move forward from there.

**Comment by anuprulez** [comment]
@martenson 
First of all, I would say Vue is easy to understand and use. Other points include:

- It is lightweight. The library's minified version is ~ 80kB. [[link](https://vuejs.org/js/vue.min.js)]. Minified + gzipped ~ 30kB.

- In many forms/pages in the Galaxy, we require many DOM manipulations. Through the model bindings in Vue, we can reduce these manipulations (and leave them to Vue as we just need to update the bound model to the view/template) and thereby reduce the lines of code. For example, `v-if`, `v-else-if` and `v-else` can be used to have conditional parts in the template itself. It can be helpful in the migration of mako files to pure javascript.

There is a useful and detailed [comparison](https://vuejs.org/v2/guide/comparison.html) between Vue and other frameworks/libraries on multiple parameters like performance, usability in complex applications, learning curve and so on. There is an amazing [performance comparison](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html).

But there are open questions like how to best combine Backbone with Vue. The UI components like form builder - how we should integrate them with Vue undergoing minimal changes and may be others.

I am looking into it more. Thanks!

**Comment by dannon** [comment]
@anuprulez I just talked with @bgruening about our Vue initiative a bit; I'm working in another branch on setting up the libraries, loaders, etc., and it might be nice to salvage some of this work there.  Do you mind if I close this out, rebase the branch (locally, here) to remove the Vue.js library added here, and incorporate it in my efforts?

**Comment by anuprulez** [comment]
@dannon Thank you. Yes, it can be closed as it was just to showcase one of the ways to use VueJS and can be used elsewhere :)

**Comment by dannon** [comment]
@anuprulez Check out #4978; I cherrypicked your PRs over and included them there.  (thanks again!)

**Pull request closed without merging**
