### PR TITLE
Extend the logging of tool dependency status changes.

### PR DESCRIPTION
**Pull request by nsoranzo**
Also merge `handle_tool_dependency_installation_error()` in `set_tool_dependency_attributes()` and consolidate its use.

### CODE REVIEW

**Comment by martenson** [comment]
I like this, will review more thoroughly later today. Thanks @nsoranzo !

**Comment by nsoranzo** [comment]
Jenkins tool shed tests result are at https://jenkins.galaxyproject.org/job/docker-toolshed/21/

There are 3 new failures, but those are due to #1251. @jmchilton can you fix them?

**Comment by bgruening** [comment]
:+1:

**Comment by jmchilton** [comment]
Of course, I took a look at it yesterday briefly and couldn't figure out what the problem is but I'll try again today.

**Comment by jmchilton** [comment]
:+1: - thanks @nsoranzo.

**Comment by martenson** [comment]
lgtm, thanks @nsoranzo !

**Pull request merged**
