### PR TITLE
Fix history grid selenium tests

### PR DESCRIPTION
**Pull request by dannon**
Fixes history grid related selenium tests busted recently.  Also fixes selenium sizzle selector generation for particular environments in https://github.com/galaxyproject/galaxy/pull/10216/commits/3f25d628a82989dee49f7769fbb01130a3b687bf

### CODE REVIEW

**Comment by dannon** [comment]
Missed the other test module; fixing it now.

**Comment by mvdbeek** [comment]
Hmm, this last error looks different:
```
Traceback (most recent call last):
  File "/galaxy/lib/galaxy_test/selenium/framework.py", line 155, in func_wrapper
    return f(self, *args, **kwds)
  File "/galaxy/lib/galaxy_test/selenium/test_uploads.py", line 58, in test_upload_specify_genome_all
    self.perform_upload(self.get_filename("1.sam"), genome_all="hg18")
  File "/galaxy/lib/galaxy/selenium/navigates_galaxy.py", line 521, in perform_upload
    self.upload_set_footer_genome(genome_all)
  File "/galaxy/lib/galaxy/selenium/navigates_galaxy.py", line 105, in _retry
    return retry_call_during_transitions(partial(f, *args, **kwds), attempts=attempts, sleep=sleep, exception_check=exception_check)
  File "/galaxy/lib/galaxy/selenium/navigates_galaxy.py", line 89, in retry_call_during_transitions
    return f()
  File "/galaxy/lib/galaxy/selenium/navigates_galaxy.py", line 602, in upload_set_footer_genome
    self.select2_set_value(selector, genome)
  File "/galaxy/lib/galaxy/selenium/navigates_galaxy.py", line 1533, in select2_set_value
    select_elem = drop_elem.find_elements_by_css_selector(".select2-result-label")[0]
IndexError: list index out of range
```

**Review by mvdbeek — APPROVED** [review]

**Comment by dannon** [comment]
@mvdbeek Yeah, I checked it a few times locally and it's working; not sure how flaky that one usually is.

**Comment by mvdbeek** [comment]
Cool, looks like that was intermittent, and I don't think I have seen that one before.

**Comment by OlegZharkov** [comment]
@dannon thanks a lot!
I will better go and rebase my PRs now

**Pull request merged**
