### PR TITLE
[15.05] Split initialization of galaxy queue worker.

### PR DESCRIPTION
**Pull request by dannon**
Should finally put down my white whale.  Also includes logging improvements.

### CODE REVIEW

**Comment by dannon** [comment]
I would love for someone that has managed to reliably(ish) reproduce this issue to give it a test.  I have seen it _once_ on my own hardware in total, and make a terrible test case for it.

**Comment by jmchilton** [comment]
So I would say this happens to me once every ~30 times I started Galaxy (your previous re-arrangement or other dev setup config changes seemed to decrease this frequency from once every ~15 times). I just switched to this branch and started and killed Galaxy lets say 50 times without hitting the deadlock.

So :+1:  - happy to merge this now - or we can wait for a more reliable tester if you think that is going to come.

**Comment by dannon** [comment]
Thanks for testing!  I'm comfortable with the reorganization even if it doesn't resolve the issue, though I really hope it does, so yeah, let's go ahead and get it in there and hopefully get more hands testing it whether they want it or not ;)

**Comment by dtrudg** [comment]
@dannon - sorry for the delay. Started galaxy 40 times with these changes with no issue. That on the machine that was, and still is giving errors at least every 10 restarts before any of your changes.

**Comment by dannon** [comment]
That's fantastic!  Hopefully this is the end of these issues.   Thanks for testing!

**Pull request merged**
