### PR TITLE
[18.05] Fix repeated inputs

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Review by martenson — APPROVED** [review]

**Comment by martenson** [comment]
@guerler This seems to work locally for me, do you want to take it out of wip?

**Comment by dannon** [comment]
I haven't tested it, but *that* this is the fix scares me ~~a little bit~~.  How much other stuff are we passing around (byref) and manipulating in various places?  I can't find it right now, but this is eerily familiar to another recent bug.  I'll update this if I can find it.

(tldr: all this stuff should be side-effect free...)

**Comment by guerler** [comment]
@dannon we used to handle this like restored here for a long time until recently where we removed the copy but I am on board if you find the other location/bug and then we can review this again.

**Comment by dannon** [comment]
@guerler Yeah, I'm not saying this isn't an okay fix for this *right now*, but we really, really should revisit any of these methods that have side effects.  It's a dangerous design.

**Comment by guerler** [comment]
@dannon this dictionary is used downstream within the form builder only. I am not sure what you mean with side-effects. The copy is required due to the customized change handler at https://github.com/guerler/galaxy/blob/fcde0d669f3e65bf92f05dc517fe550d017c86c4/client/galaxy/scripts/mvc/form/form-section.js#L164.

**Pull request merged**
