### PR TITLE
[17.01] More careful inspection of fixes for MAF tools requiring Galaxy.

### PR DESCRIPTION
**Pull request by jmchilton**
Add two tools that required the hack, and remove one tool that doesn't seem to require it. Tracked in comment on #3934.

### CODE REVIEW

**Review by martenson — APPROVED** [review]

**Comment by nsoranzo** [comment]
@jmchilton What about the `bx` imports? It seems to me that all maf tools should have a requirement on `bx-python` to properly work, especially the ones not on this list.

**Comment by jennaj** [comment]
self ping for updates @jennaj

**Comment by jmchilton** [comment]
maf_limit_size was removed from the list - its Python file imports are as follows:

```
from __future__ import print_function

import sys

import bx.align.maf
```

Since it doesn't import ``galaxy`` - I don't think it needs to be in the list. Galaxy's dependencies such as ``bx`` are still exposed to tools. A lot more would break I think if ``bx`` were to disappear.

**Comment by nsoranzo** [comment]
I'll investigate the `bx-python` requirement issue separately.

**Pull request merged**
