### PR TITLE
Order data parameters before unlinked multiplication

### PR DESCRIPTION
**Pull request by mvdbeek**
The 2 failed tests [here](https://jenkins.galaxyproject.org/job/docker-api-py3/30/testReport/junit/) fail randomly, and at least the first one relies in the order of implicit collections.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Still finding more of these ..

**Comment by mvdbeek** [comment]
This should really be an issue with dictionary ordering -- I can reproduce the failures on python 3.5, but not 3.6, which has stable ordering ...

**Comment by mvdbeek** [comment]
Setting the PYTHONHASH to 3 makes the test always pass, 1 or 2 always fail ...

**Comment by mvdbeek** [comment]
Alright, the last 10 runs all passed (https://jenkins.galaxyproject.org/job/docker-api-py3/), this is ready for review.

**Comment by jmchilton** [comment]
Thanks you so much for deep diving into this!

**Pull request merged**
