### PR TITLE
Show favourited tools independent of version

### PR DESCRIPTION
**Pull request by juleengraham**
Addresses #9623

### CODE REVIEW

**Comment by dannon** [comment]
@juleengraham Would you mind adding a simple unit test for the panel utilities demonstrating the how the two filtering functions here work, with expected outputs?

**Comment by dannon** [comment]
@juleengraham It'd be good to have this in 20.09 -- can you commit to adding this test during the freeze?

**Comment by juleengraham** [comment]
@dannon yes, i will

**Comment by dannon** [comment]
I was about to merge this, but it's (not only not working) breaking the search display.

Searching for 'random' on my galaxy instance yields (as the API response):
```
["random_lines1", "Grouping1", "toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.3.4.3+galaxy0"]
```

In dev, these all get rendered.  On this branch, only bowtie2 is rendered.

**Comment by juleengraham** [comment]
Screen Shot 2020-09-21 at 10 37 33 AM

I get the 3 search results when I search "random" on my branch.

**Pull request merged**
