### PR TITLE
Fix double class declaration in provided_metadata.py.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Review by nsoranzo — APPROVED** [review]
Introduced in 25f84b69b6a8cf0d5cccd12aceba9b50dfe3e765 .

**Comment by mvdbeek** [comment]
The jslint failure is fixed in #7571

**Comment by nsoranzo** [comment]
Why is jslint not failing on CircleCI? @martenson

**Comment by martenson** [comment]
@nsoranzo it passed here, did you have to rerun it?

**Comment by nsoranzo** [comment]
@martenson I mean it should have failed, as the Travis one.

**Comment by martenson** [comment]
@nsoranzo does not fail for me locally on dev, was it fixed in the meantime?

edit: I see the fix now

**Comment by nsoranzo** [comment]
Yes, @mvdbeek merged #7571 in the mean time.

**Comment by martenson** [comment]
It was probably very intermittent, since it was supposed to be introduced in (December) https://github.com/galaxyproject/galaxy/pull/7101 and I've never seen it fail?

**Comment by nsoranzo** [comment]
#7101 was merged an hour ago.

**Comment by martenson** [comment]
@nsoranzo so we are probably approaching the same issue, circleci did not run on merge, travis did?

**Comment by nsoranzo** [comment]
Exactly.

**Pull request merged**
