### PR TITLE
[18.09] Fix stopping DRMAA jobs

### PR DESCRIPTION
**Pull request by natefoo**
I broke them in #6087. Also improve logging around this process.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@natefoo Wrong target branch?

**Comment by natefoo** [comment]
Yep thanks.

**Comment by nsoranzo** [comment]
This looks good as a fix for 18.09, but I was wondering if `stop_job()` in `BaseJobRunner` and subclasses should actually receive a `JobWrapper` object as parameter instead of a `Job` object.
This should simplify this code and put the `stop_job()` method in line with the rest of the `BaseJobRunner` methods.

**Comment by natefoo** [comment]
Yeah, that makes sense to me. In fact, all the ones receiving both the `Job` and `JobWrapper` should probably just receive `JobWrapper`. I think in the past the idea was that things that didn't need a `JobWrapper` should just get a `Job` since it would be quicker not to create a `JobWrapper` when it was unneeded.

**Comment by jmchilton** [comment]
> In fact, all the ones receiving both the Job and JobWrapper should probably just receive JobWrapper. I think in the past the idea was that things that didn't need a JobWrapper should just get a Job since it would be quicker not to create a JobWrapper when it was unneeded.

Perhaps it was a premature optimization - but I've sometimes passed a job parameter directly to something that had access to a job_wrapper to prevent the SA interactions in ``get_job``.

**Pull request merged**
