### PR TITLE
[16.01] Fix unbound error that is possible if using tool bursting.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by guerler** [comment]
:+1:

**Comment by AjitPS** [comment]
Hi, just to confirm, is the <b>UnboundLocalError: local variable 'params' referenced before assignment</b> error issue (encountered when running saved Galaxy workflows with dataset collections) resolved now in the new Galaxy 16.01 ?

**Comment by guerler** [comment]
I think this is related to #2084

**Comment by AjitPS** [comment]
I understand. But, has this problem now been resolved in release 16.01 ? #2084

**Pull request merged**
