### PR TITLE
Allow workflows executed via the API to optionally run with tool upgrades 

### PR DESCRIPTION
**Pull request by blankenberg**
by providing allow_tool_upgrades=True within the payload

### CODE REVIEW

**Comment by martenson** [comment]
I like the functionality. :+1:

**Comment by jmchilton** [comment]
:+1: 

Didn't have luck with the newer API endpoint?

**Comment by blankenberg** [comment]
Actually only using the newer end point...but the `def invoke` doesn't have any help listed, so I added it at the older one.

**Comment by jmchilton** [comment]
This modification only affects the older endpoint though right?

**Comment by blankenberg** [comment]
No, it affects the new one (didn't actually test the older one -- it should affect both, however.)

**Comment by jmchilton** [comment]
Ahh - I get it. You updated the docs for the older one (new one probably doesn't even have docs :(). Awesome - sorry for wasting your time.

**Comment by blankenberg** [comment]
Any other comments or concerns?

**Comment by jmchilton** [comment]
@blankenberg and I discussed in office - we agreed to rename parameter `allow_tool_state_corrections`.

**Comment by blankenberg** [comment]
Changed allow_tool_upgrades to allow_tool_state_corrections.

**Comment by jmchilton** [comment]
Brilliant @blankenberg - thanks a bunch.

**Pull request merged**
