### PR TITLE
Fix project linting for new pep8

### PR DESCRIPTION
**Pull request by dannon**
Version 1.7 of pep8 yields additional warnings and errors.  This should fix the build.

### CODE REVIEW

**Comment by jmchilton** [comment]
Awesome sauce, thanks @dannon.

**Comment by nsoranzo** [comment]
This should be backported to 16.01, PRs are failing there too now.

**Comment by dannon** [comment]
@nsoranzo Good call, on it.

**Comment by nsoranzo** [comment]
@dannon I'm almost done fixing E731 errors if you are interested.

**Comment by dannon** [comment]
@nsoranzo I wasn't sure that'd be a rule we actually want to follow given how many people on the team seem to like that style, which is why I didn't fix it yesterday.  Personally I'm totally fine with that change, but I think it's worth discussing (which, I guess, can be in the form of a PR ;))

**Comment by jmchilton** [comment]
@nsoranzo I'm +1 on "fixing" E731. galaxy-libs only exclusion is for line length and I'd like to keep it that way. I don't love the rule but I think the most important aspect of code style guidelines is to stick with community standards.

**Comment by nsoranzo** [comment]
xref.: #1489

**Comment by carlfeberhard** [comment]
For the record, the use of this script still frustrates and boggles me, I end up caring less about this project, and then I want less to on it or put actual heart into it. I feel like this script is less about consistency and good practice and more about certain people not having to look at code they deem is styled 'wrong'. It's not my call and I'm only one person - so I'm not blocking it (not that I could because none of the PR's had a lot of time before they were merged). 

No reply necessary and not trying to start a style war - just putting my opinion out there since I am, ostensibly, part of the community also.

**Comment by natefoo** [comment]
@carlfeberhard I feel ya, it frustrates the hell out of me at times as well. I do think the net benefit has been positive as our code is much more consistent now, which I think makes it easier to work on, but there are certainly things about the rules that I disagree with.

And you're not ostensibly a part, you are absolutely a part.

**Comment by dannon** [comment]
<-- this guy agrees with everything @natefoo just said

**Comment by jmchilton** [comment]
@carlfeberhard Regarding the fast merge - I think you comments are heard by everyone and even if we ultimately disagree with you - they have an effect - before or after the merge. If you feel strongly enough to -1 on anything - the rules do allow for this after the merge:

```
A -1 vote on any recently merged pull request requires an immediate reversion of the merged pull request. The backout of such a pull request invokes a mandatory, minimum 72 hour, review period.
Recently merged pull requests are defined as a being within the past 168 hours (7 days), so as to not prevent forward progress, while allowing for reversions of things merged without proper review and consensus.
The person issuing the -1 vote will, upon commenting -1 with technical justification per the vetoes section, immediately open a pull request to revert the original merge in question. If any committer other than the -1 issuer deems the justification technical - regardless of whether they agree with justification - that committer must then merge the pull request to revert.
```

**Pull request merged**
