### PR TITLE
Add 3D PCA visualization

### PR DESCRIPTION
**Pull request by xtrojak**
This PR adds a 3D visualization plugin for Principal component analysis (PCA) of mass spectra feature intensities.
The data is given in a tabular format with metadata. The plugin computes PCA using [pca-js](https://github.com/bitanath/pca) library and visualizes the result using [Plotly](https://plotly.com/javascript/) 3D scatter plot.

The user can choose the column where the actual intensities start. All other columns are treated as metadata, and their values are shown in the hover text. Additionally, any metadata column can be used to assign a colour to data points.

ss

There are two known issues caused by the fact that Plotly chart is in an `iFrame` - (1) in Firefox, it does not load on the first try (there is an exception [NS_ERROR_FAILURE](https://bugzilla.mozilla.org/show_bug.cgi?id=941146)) and (2) the plot legend is sometimes cut off (can be reproduced using provided [example file](https://drive.google.com/file/d/1Iog7lUackxSu1B_dvKl0q-4uZ4di-rnx/view?usp=sharing)).

Finally, since the PCA is computed in the browser, it can take some time to load. A loading bar could be added to let the user know that the visualisation is still loading.

## How to test the changes?

- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. upload [example file](https://drive.google.com/file/d/1Iog7lUackxSu1B_dvKl0q-4uZ4di-rnx/view?usp=sharing)
  2. visualise it

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by martenson** [comment]
Before merging we should to address the firefox bug with a workaround. According to https://bugzilla.mozilla.org/show_bug.cgi?id=941146 FF does not like when you set certain properties of a canvas contained inside a `display:none` iframe. Hence this visualization does not work on the first load in FF, you have to interact with the controls and only the second draw will properly display the data points.

I have a hacky solution to this (catching the error and silently failing, then rendering again at `window.onload`, which I will propose later this week unless we come up with something better.

**Comment by martenson** [comment]
I added a hack in f3c8633 which is slightly better than my previous hack. Is this acceptable?

**Comment by martenson** [comment]
circleCI jslint is failing with 

```
#!/bin/bash -eo pipefail
cd client && yarn run prettier-check
yarn run v1.22.17
error Command "prettier-check" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by mvdbeek** [comment]
You'll want to rebase or merge in dev to fix that.

**Comment by martenson** [comment]
Should be fine if nothing else fails I think.

**Comment by dannon** [comment]
@martenson Yep; this will be fine.  Works great in my hands, nice stuff @xtrojak!

**Comment by martenson** [comment]
Thanks for the merge @dannon!

**Pull request merged**
