### PR TITLE
Strip API keys option from admin panel left side

### LINKED ISSUE #6625: infinite site reloading for API keys page
I just started a clean dev galaxy, added a user and made him a admin. When loading the AKIKeys section in the admin panel the page reloads all the time.

### PR DESCRIPTION
**Pull request by dannon**
This is all in the user management grid now.  I don't know if this got added back in a bad merge or if it was erroneously left in, but this fixes #6625

### CODE REVIEW

**Comment by martenson** [comment]
The 'API keys' admin menu also exists in 18.05 but does not work. Can be seen on Main.

**Comment by dannon** [comment]
@martenson Hrmm, thought this was changed more recently than 18.05, but let me take a look.  I can rebase/retarget if that's the same problem.

**Comment by martenson** [comment]
It doe snot end up in a loop on Main, just says `No user information available`

**Comment by dannon** [comment]
@martenson Ok, cool, so we have *two* problems, not one.  Even better :)

**Comment by dannon** [comment]
I think the problem on main is likely that the request that populates the interface is just super slow, and is trying to fetch *all* users and all API keys at once.  Anyway, IMO not worth doing anything about with 18.09 around the corner and this interface going away.

**Comment by martenson** [comment]
You are correct, the request times out and the UI gives no hint of loading or failure.

I remember it working fairly well before. Dunno why the request started to time out.

**Comment by nsoranzo** [comment]
On a small server like ours,`/admin/api_keys` works fine on 18.05.

**Comment by nsoranzo** [comment]
Should we run selenium tests on this PR? (not sure if there's a galaxybot message to trigger them).

**Comment by dannon** [comment]
Huh, I thought we'd re-enabled them.  My intent was to run them against this, since I dropped that selector, yes.

**Comment by mvdbeek** [comment]
I'm working on the failing API test, it's unrelated of course.

**Comment by nsoranzo** [comment]
@mvdbeek I already restarted it, hope that's not an issue for your debugging.

Edit: that's the link to the failed test: https://jenkins.galaxyproject.org/job/docker-api/12800/testReport/junit/test.api.test_workflows/WorkflowsApiTestCase/test_workflow_rerun_with_use_cached_job/

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
> I don't know if this got added back in a bad merge or if it was erroneously left in

I think it was forgotten in https://github.com/galaxyproject/galaxy/pull/6176 .

**Pull request merged**
