### PR TITLE
Remove legacy history from code base

### PR DESCRIPTION
**Pull request by guerler**
Follow-up of #14638. This PR removes the legacy history from the code base and drops the `analysis` bundle size from `20.2MB` back to `18.9MB` (uncompressed local file size)

It also, includes refactoring for the following two makos:
- [x] `history/display.mako` used for shared histories. It is using the bundled `HistoryView` component now, and mounted inside the mako using: https://github.com/galaxyproject/galaxy/pull/14660/files#diff-d0bf6e10f0d44eb04a12c86e53192fa53f6e62444d9f595980fcb9e0b730497aR1
- [x] `history/embedded.mako` is used in Galaxy Pages, which were created using the legacy HTML page editor. In this case embedded legacy histories have been replaced with a `Name`, `Annotation` and a `Link to the History`, also leading to the `HistoryView` component.

Additionally this PR removes the legacy iframe handling:
https://github.com/galaxyproject/galaxy/pull/14660/files#diff-f2e9637ac05c1a49918232a4003c0d3d74c1bd629eec9920e6c0978048870089L5

The window manager is not required to perform location handling anymore:
https://github.com/galaxyproject/galaxy/pull/14660/files#diff-747287c2ddcdbe120610fcdd11f32a0f218a1edb983ea9f10494c5aa0e7e8230L30

Instead it is handled in `route` processing:
https://github.com/galaxyproject/galaxy/pull/14660/files#diff-3dbc3af2db8059af5869467206a457b0bfa9f481f1e87bc0cacf1f7c9ff1521fR73

This PR also contains a fix for handling multiple histories, once retrieved detailed-view properties are now preserved:
https://github.com/galaxyproject/galaxy/pull/14660/files#diff-9f0b0b19054c241dfd008b38f14c385df1073ecef759a3e778d7ffe136e1d2e5L35

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
I played around with this branch and could not find any regression :)
Cool work 11k lines gone - bye-bye old history you served us well over so many years.

**Comment by guerler** [comment]
Thank you for testing this.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
I created https://github.com/galaxyproject/galaxy/issues/14685 to cleanup the tests a bit.

Great work @guerler

**Comment by guerler** [comment]
Thanks again for the timely review, really appreciate it!

**Pull request merged**
