### PR TITLE
Use pysam instead of samtools binary

### PR DESCRIPTION
**Pull request by nsoranzo**
This will make it possible to remove the requirement of having `samtools` installed when testing tools, e.g. in the tools-iuc TravisCI setup: https://github.com/galaxyproject/tools-iuc/blob/master/.travis.yml#L59

This can be tested with `planemo test` of the tool https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/bedToBam.xml .

### CODE REVIEW

**Comment by bgruening** [comment]
Magic! Looks so easy and will help so many people! Only question I have is if we should given a warning/error message when no pysam is available.

Thanks @nsoranzo!
:+1:

**Comment by nsoranzo** [comment]
That'd be up to @jmchilton, who requested the `try/except` for the `import` :stuck_out_tongue:

**Comment by bgruening** [comment]
We could still issue a warning before we set `pysam = None`, right?

**Comment by dannon** [comment]
This looks good to me.  Elsewhere in the codebase when we try/except and set lib=None, we fail not when the import fails, but when trying to use it fails.

**Pull request merged**
