### PR TITLE
Remove references to missing types from sample config file

### LINKED ISSUE #10264: media datatypes not loaded correctly
From https://github.com/mvdbeek/tools-iuc/runs/1150658261?check_suite_focus=true:
```
2020-09-22 16:58:28,705 ERROR [galaxy.datatypes.registry] Error importing datatype module galaxy.datatypes.media
Traceback (most recent call last):
  File "/tmp/tmpb9xmi534/galaxy-dev/lib/galaxy/datatypes/registry.py", line 249, in load_datatypes
    datatype_class = getattr(module, datatype_class_name)
AttributeError: module 'galaxy.datatypes.media' has no attribute 'Mov'
2020-09-22 16:58:28,705 ERROR [galaxy.datatypes.registry] Error importing datatype module galaxy.datatypes.media
Traceback (most recent call last):
  File "/tmp/tmpb9xmi534/galaxy-dev/lib/galaxy/datatypes/registry.py", line 249, in load_datatypes
    datatype_class = getattr(module, datatype_class_name)
AttributeError: module 'galaxy.datatypes.media' has no attribute 'Ogv'
2020-09-22 16:58:28,705 ERROR [galaxy.datatypes.registry] Error importing datatype module galaxy.datatypes.media
Traceback (most recent call last):
  File "/tmp/tmpb9xmi534/galaxy-dev/lib/galaxy/datatypes/registry.py", line 249, in load_datatypes
    datatype_class = getattr(module, datatype_class_name)
AttributeError: module 'galaxy.datatypes.media' has no attribute 'Oga'
2020-09-22 16:58:28,715 ERROR [galaxy.datatypes.registry] Error calling method Mov from class <module 'galaxy.datatypes.media' from '/tmp/tmpb9xmi534/galaxy-dev/lib/galaxy/datatypes/media.py'>
Traceback (most recent call last):
  File "/tmp/tmpb9xmi534/galaxy-dev/lib/galaxy/datatypes/registry.py", line 501, in load_datatype_sniffers
    aclass = getattr(module, datatype_class_name)()
AttributeError: module 'galaxy.datatypes.media' has no attribute 'Mov'
```

### PR DESCRIPTION
**Pull request by jdavcs**
Fixes #10264

### CODE REVIEW

**Comment by nsoranzo** [comment]
@ic4f I think this should target the new release_20.09 branch.

**Comment by dannon** [comment]
Yep, it should.  I went to change it but that's going to involve a (trivial) rebase, so I'll let @ic4f handle that.

**Comment by ic4f** [comment]
> Yep, it should. I went to change it but that's going to involve a (trivial) rebase, so I'll let @ic4f handle that.

@dannon There was no rebase - did I miss something? Also, should we close this one?

**Comment by dannon** [comment]
@ic4f Right; if you change the branch target from dev to 20.09 you'll see the extra commits that should trivially be rebased out.  Let me know if you'd rather I take care of it, I don't mind.

**Comment by ic4f** [comment]
Th

> @ic4f Right; if you change the branch target from dev to 20.09 you'll see the extra commits that should trivially be rebased out. Let me know if you'd rather I take care of it, I don't mind.

Thanks, and no worries - I didn't change the target, just cherry-picked and submitted as #10269. Closing this one.

**Comment by dannon** [comment]
That's fine, too, thank you!

Next time up at the top of the PR you can just 'edit' and change the base, then force-push a rebase against the correct branch to this.  So, if it were mine:

`
<change branch target on github>
git checkout dev_10264
git rebase -i upstream/release_20.09
<drop anything extra>
git push -f
`

**Comment by ic4f** [comment]
Oh yes, I see. I didn't know I could edit the target branch on github after the fact. Will do it this way next time. Thanks for all the details - much appreciated!

**Pull request closed without merging**
