### PR TITLE
Correct ldap authenticator type in example config.

### PR DESCRIPTION
**Pull request by dtrudg**
Thanks to @nsoranzo for spotting.

### CODE REVIEW

**Comment by martenson** [comment]
:+1:

**Comment by dannon** [comment]
This was identical to https://github.com/galaxyproject/galaxy/pull/90/commits, right?

**Comment by dtrudg** [comment]
Oh, sorry. I didn't see that one. Apologies!

**Comment by dannon** [comment]
No problem at all, I just saw the merge pop through on my phone and was _really_ confused for a second since I was sure I'd already done this :)

**Comment by martenson** [comment]
lol, why did github show the diff then? I did vaguely remember I saw it before :D

**Comment by dannon** [comment]
Yeah, I know, that's why I was so confused too!

**Pull request merged**
