### PR TITLE
Allow rerunning uploads from link

### LINKED ISSUE #8420: Restart failed uploads via item
Hi,

Sometimes it happens due to network timeouts on the Galaxy server side that an upload of a job fails. So far there is no option to just restart this upload job. Currently I have to copy&paste all again to the upload dialog.

Feature request: A rerun upload option in case the upload failed.

Thanks for considering.

Best,

Joachim

### PR DESCRIPTION
**Pull request by simonbray**
## What did you do? 
- Set the `__DATA_FETCH__` tool as `workflow_compatible`.

## Why did you make this change?
Fixes https://github.com/galaxyproject/galaxy/issues/8420.

@wm75 and I are currently working on a bot for automatic analysis of SARS-CoV-2 data which uploads data via links into collections, before invoking a workflow, and we would like to be able to automatically rerun uploads that fail due to server issues.

I also thought of achieving the same effect by replacing https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/datasets.py#L572 with `if tool and (tool.is_workflow_compatible or tool.id == "__DATA_FETCH__")`. If this is better, or there's another preferred alternative, please let me know. 

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Upload a file by pasting a link in the UI. The dataset created should have a rerun icon; clicking on it allows rerunning the upload.

## For UI Components
- [ ] I've included a screenshot of the changes

### CODE REVIEW

**Comment by jmchilton** [comment]
I would say I don't love that this would place data fetch in the workflow editor - but since it doesn't appear in the tool panel really I guess it won't appear in the editor by default. So if it is in there someone did something manual and in that case it might be configured in such a way that it makes perfect sense. So yeah... this seems okay to me!

**Review by jmchilton — APPROVED** [review]

**Comment by simonbray** [comment]
Please don't merge this yet - I realised this is not that useful by itself. We would also need the created jobs to be remappable and it seems job submission for this tool needs to be done via a special endpoint: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/tools.py#L28. I need to explore how that works a bit first.

**Comment by innovate-invent** [comment]
Because you are specifically using urls to upload, would it be better to just wrap curl in a tool wrapper and set up a simple parameter input for the workflow?

**Comment by simonbray** [comment]
> Because you are specifically using urls to upload, would it be better to just wrap curl in a tool wrapper and set up a simple parameter input for the workflow?

Maybe that would be more convenient but it would be basically a duplicate of the existing tool, which seems unnecessary.

**Comment by simonbray** [comment]
So we don't need this any more - but maybe it's still useful for someone else (like Joachim who originally created #8420?)

The main downside IMO is that it doesn't look great in the UI:

image

Please go ahead and either close or merge.

**Pull request closed without merging**
