### PR TITLE
[22.05] Allow delete option when history items are shown outside of panel

### LINKED ISSUE #14259: [release-testing] Delete button on dataset details page does not work
In 22.01 it was possible to delete a dataset via the dataset details page (accessed via the `i` icon in the history) - see the button on the right of the screenshot below.

image

In 22.05 clicking this button has no effect.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #14259.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by ahmedhamidawan — APPROVED** [review]
Yep apologies, `isHistPanel` was pretty redundant, I guess changing the default value for `isHistoryItem` was all that was needed in the first place. Thanks!

**Comment by mvdbeek** [comment]
It worked fine before adn was useful, why do you want to disable this ?

**Comment by guerler** [comment]
@mvdbeek Considering our issues with updating I don't think we need this extra feature right now i.e. the item content has to update after the state changes. I also did not intend that users should be able to delete items from that view, it is not well reflected in the UI etc. We can revisit this in the future with proper tests and proper indication of what changes when someone clicks on the item imo. For now I think, its cleaner and more consistent to not allow deletion in secondary views.

**Comment by mvdbeek** [comment]
i think this is important, it worked ever since we had the invocation component, please fix it.

**Comment by guerler** [comment]
Ok, I restored this feature as it worked before but personally I would have preferred to only allow deletion in the context of the history panel since the invocations view does not properly update and reflect changed states of history elements due to: https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue#L108.

**Comment by mvdbeek** [comment]
Thanks for fixing this!

**Pull request merged**
