### PR TITLE
[WIP] Replace tightly-coupled legacy current history models in Libraries components

### PR DESCRIPTION
**Pull request by Nerdinacan**
## What did you do? 

Complete rewrite of libraries.

I noticed several recent issues regarding libraries, I will make sure they are all addressed with the replacement.

Relevant Issues:
https://github.com/galaxyproject/galaxy/issues/12014
https://github.com/galaxyproject/galaxy/issues/12006
https://github.com/galaxyproject/galaxy/issues/12005
https://github.com/galaxyproject/galaxy/issues/12004
https://github.com/galaxyproject/galaxy/issues/12003

Relies on:
https://github.com/galaxyproject/galaxy/pull/12040

## Why did you make this change?

The existing code tightly-couples the global Galaxy legacy events and behaviors to the new Vue components essentially turning Vue into a glorified template engine for Backbone and wrapping the spaghetti code we wanted to remove even tighter.

It needs a completely new implementation that does not rely on the very Backbone models we are trying so hard to remove.

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by OlegZharkov** [comment]
Hey @Nerdinacan, thanks for working on it. I just briefly took a look, what was the problem of just vuefying the backbone modals? I mean, you don't have to re-implement the whole thing from scratch, replacing modals would be enough. 

Anyway... can you put vuefied `LibraryDetails` modal you have in a separate PR, please? So we can replace the existent backbone one. I guess, it'll also reduce the size of the existing PR. 

Also LibrariesList and permissions are don't have any backbone stuff there...

**Comment by Nerdinacan** [comment]
> Hey @Nerdinacan, thanks for working on it. I just briefly took a look, what was the problem of just vuefying the backbone modals? I mean, you don't have to re-implement the whole thing from scratch, replacing modals would be enough.
> Anyway... can you please put vuefied `LibraryDetails` modal you have in a separate PR? So we can replace the existent backbone one. I guess, it'll also reduce the size of the existing PR.

No. I'm re-implementing the whole thing. 

There are a variety of structural problems above and beyond the ones mentioned in the intro description. It will be easier to simply replace rather than moving forward and working around the many problems introduced in the previous implementation.

This is a draft PR, that means it is not ready for review yet. I typically make these to make sure that code is passing while I release incremental commits, and to document intent and to link issues. When it is ready I will change the status away from "draft".

If that is confusing to you, or anybody else, I can stop making draft PRs. I started doing drafts on other PRs to give other contributors a chance to collaborate with their own commits to my branch. It was very successful on a recent PR about database triggers. I'll go ahead and change the name to add WIP if that is more familiar to you.

**Comment by OlegZharkov** [comment]
> No. I'm re-implementing the whole thing. Then I'm going to have to do the same to the Upload module which has similar structural issues that will be faster to replace than attempt to piecemeal, which (as evidenced by the current implementation) creates more problems than it solves.

What problem does it create? It was actually suggested to me to recycle some modals from legacy implementation to finish library pagination PR faster and only then, we take care of other stuff. To be honest, I still don't get what is the problem to rewrite it modal by modal? It's 5-6 small PRs and old modals are gone. It was on my list to re-implement modals as well, but it wasn't really a high priority. (I can change the priority, if you want)

> This is a draft PR, that means it is not ready for review yet. I typically make these to make sure that code is passing while I release incremental commits, and to document intent and to link issues. When it is ready I will change the status away from "draft".

yeah, it's clear I was just hoping to make the PR smaller and kinda steal your `LibraryDetails.vue` and embed it in current implementation :sweat_smile:. However, if LibraryDetails.vue isn't there yet, sorry for disturbance.

Also I don't see a point to re-implementing Libraries and Permissions, since there's no backbone left.

**Comment by Nerdinacan** [comment]
Tell you what, I'll leave this for you. I'll post up my current partial code for you to take or leave. But in my opinion this module is problematic for more reasons than just the backbone turducken issue (Backbone inside Vue inside Backbone). I felt like it would be faster to just replace than to dance around a bunch of tiny PRs that will leave us with weird code artifacts forever.

I dare you to write a unit test for any of this code. :)

**Comment by OlegZharkov** [comment]
Backbone inside Vue at most :wink: 

Just before looking into code, what do you suggest me to recycle from here?  (some explanation would be very useful) Is there re-written modal I could use?

**Comment by Nerdinacan** [comment]
I think if you are dead-set on incrementally reworking Library, that you should stop and actually design your end-goal for the components you're building, then use them as boxes to hold existing code before you replace it. Stop and think about the real functional dependencies of the existing backbone models you want to replace. Try to make a map of what objects require which user inputs and where those inputs should be stored.

Once you know what your chain of dependencies is, then wrap stuff in components. I like providers for this reason. It's a vue component that takes some inputs (props) and emits a dynamic result (slot-props), but the rest of the Vue ecosystem doesn't care what's happening inside that provider. The tech in there can be anything. You can write a unit test for a provider that runs on backbone inside, (or rxjs as I did for history).

As an example, you have a list of histories that is filtered by a couple buttons on the UI. My first step would be to isolate the retrieval of that data and the filtering from the UI that renders the button and to make a couple local model objects that represent the filter selection that the user provides. Draw out a very abstract component layout that just describes the data flow the way you want it to be.

Here's a very abstract and probably not-good-enough starting point.

```html
<LibraryProvider :user="user" :filters="filters" v-slot="{ libraries }">
   <div>
        <FiltersUI :filter.sync="filters" />
        <ListingUI :libraries="libraries" />
   </div>
</LibraryProvider>
<script>
export default {
   props: {
      user: { type: Object, required: true },
   },
   data() {
     filters: new Filters()
   }
}
</script>
```

This doesn't do much other than help you start making a map of the fact that, "hey i need filters that the user can select, where should they live?"

If you want to jam LibraryProvider with a bunch of existing backbone models and fix it later, great! But first make a wrapper that does that, and unit test your provider, then you can replace the implementation at your leisure.

I guess what I'm saying is, when I look at Libraries I see no design goal. There is no incremental path from here to there because you have not stopped to decide what "there" is. It is not reasonable to incrementally change Libraries into what you want because you have not defined what you want.

Good luck man, let me know if you want help structuring this thing.

**Pull request closed without merging**
