### PR TITLE
[22.05] Fix delayed optional data input handling

### PR DESCRIPTION
**Pull request by mvdbeek**
This fixes recording optional data input module use in the expanded tool form (and is closer to how we want to use the API).
It also fixes scheduling workflows where optional input steps are being delayed, and it allows leaving subworkflow optional data inputs disconnected.

Fixes https://github.com/galaxyproject/galaxy/issues/14611, https://github.com/galaxyproject/galaxy/issues/10899, https://github.com/galaxyproject/galaxy/issues/10450

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

**Comment by bgruening** [comment]
Is that still draft?

**Comment by mvdbeek** [comment]
Yep, still needs tests, and I want to check out what's up with https://github.com/galaxyproject/galaxy/issues/10899#issuecomment-1249738463. You shouldn't have to specify optional inputs in the API submission at all.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/actions/runs/3089464955/jobs/4997115418#step:7:1442 should be unrelated, we might have to pin numpy to a version that works on python 3.7

**Comment by nsoranzo** [comment]
The unit tests failures seems related though?

**Comment by nsoranzo** [comment]
> https://github.com/galaxyproject/galaxy/actions/runs/3089464955/jobs/4997115418#step:7:1442 should be unrelated, we might have to pin numpy to a version that works on python 3.7

No, it's actually a [mypy bug](https://github.com/python/mypy/issues/13627), whose fix will be included in the upcoming [mypy 0.980](https://github.com/python/mypy/issues/13385).

**Comment by mvdbeek** [comment]
Just waiting for the API tests to finish before pushing the unit test fix.

**Comment by mvdbeek** [comment]
@jmchilton this has changed a bit from when you approved it, does it still look ok to you?

**Comment by jmchilton** [comment]
Awesome thank you.

**Pull request merged**
