### PR TITLE
[PROCEDURES] Reorganize content

### PR DESCRIPTION
**Pull request by nsoranzo**
- Merge "Issues" and "Galaxy Development" sections from `README.rst` into `CONTRIBUTING.md` .
- Move "Handling Pull Requests" section from `CONTRIBUTING.md` to `organization.rst` .

In this way, `organization.rst` and `CODE_OF_CONDUCT.md` become the only 2 documents handled as PROCEDURES.

| Requirement | Value |
| --- | --- |
| 192 hour window start | 2015-09-07 19:04:09+0000 |
| 192 hour window end | 2015-09-15 19:04:09+0000 |
| 25% quorum | ceil(19 \* .25) = 5, +1 votes |

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: Thanks, this is a very nice reorganization.

**Comment by hexylena** [comment]
:+1:

**Comment by bgruening** [comment]
:+1: from me as well, thanks @nsoranzo

**Comment by dannon** [comment]
+1

**Comment by natefoo** [comment]
:+1:

**Comment by hexylena** [comment]
We've met the time and quorum requirements, merging per procedures. Thanks @nsoranzo! :)

**Comment by dannon** [comment]
@erasche Did we, actually?  2015-09-15 19:04:09+0000 was the end time I thought.

**Comment by hexylena** [comment]
@dannon that time should be in UTC.

```
$ date -u
Mon Sep 14 19:45:05 UTC 2015
```

**Comment by hexylena** [comment]
OH CRAP. One day early

**Comment by dannon** [comment]
I'm not _awesome_ at knowing what day it is, but I _did_ actually check this one this morning :)

**Comment by hexylena** [comment]
(copy of irc):

``` irc
14:47:51        erasche | I read the github comment that said "7 days"                                                                                  │
14:48:03        erasche | what do y'all want me to do? Back out for 24 hours?                                                                           │
14:49:31         dannon | I dunno.  I'm not generally one for hard-and-fast rules, so I'd just let this one go (but revert if anyone actually -1's it,  │
                        | obviously)                                                                                                                    │
14:49:57         dannon | Yes, it was a mistake, but it happens.  We can move on.                                                                       │
14:50:01        erasche | yeah. There's no hard procedure for people being idiots. My apologies                                                         │

```

**Comment by martenson** [comment]
:+1: 
let it be

**Comment by dannon** [comment]
From irc, as well:

```
15:49 < dannon> I dunno.  I'm not generally one for
                hard-and-fast rules, so I'd just let this one
                go (but revert if anyone actually -1's it,
                obviously)

15:49 < dannon> Yes, it was a mistake, but it happens.  We
                can move on.
```

**Comment by hexylena** [comment]
Are any of the IRC bots in a public repo anywhere? 

I'd be happy to extend one to check on PROCEDURES PRs and comment in chat when they're OK to merge, so we don't have humans comparing timestamps?

**Comment by dannon** [comment]
Yep.  https://github.com/dannon/irc-slack-echo should always be alive.  Feel free to add fancy galaxy-specific functionality if you want.

**Comment by dannon** [comment]
(this is g2roboto in the channel)

**Comment by hexylena** [comment]
excellent!

**Comment by jmchilton** [comment]
Why not post right on the PR itself? It would be nice if PROCEDURES and stable branch commits were checked - for time and appropriate number of +1s.

**Comment by hexylena** [comment]
@jmchilton that's definitely an option. Probably even easier to do. I'll write something up :)

**Comment by martenson** [comment]
can we make https://jenkins.galaxyproject.org do it?

**Comment by hexylena** [comment]
@martenson that was my thought exactly. A nice jenkins cronjob that goes through and comments on things appropriately regarding +1s/-1s/etc.

**Comment by hexylena** [comment]
(Given that this isn't the first time I've made a mistake like this, clearly there's room for some automation to take over to ensure we're following rules nicely.)

@dannon @jmchilton @martenson implementation done. https://github.com/erasche/p4 if you have thoughts on this, I'd be happy to hear time.
- Conf is pretty simple: https://github.com/erasche/p4/blob/master/conf.yaml 
- Only comments, doesn't merge anything. No implementation for that yet unless y'all suggest otherwise.

**Pull request merged**
