### PR TITLE
[23.0] Make point release script compatible with docutils 0.16

### PR DESCRIPTION
**Pull request by mvdbeek**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
RO crate unit test failures probably the result of a new pypi release an hour ago - https://pypi.org/project/rocrate/#history. Probably should just pin it in this branch - doesn't have to be part of this PR though.

**Comment by mvdbeek** [comment]
Looks like we should pass in a pathlib object, that should work for the new and old version, I can open another PR with that

**Comment by mvdbeek** [comment]
Oh, it seems like this is a bigger thing and at least the ro-crates that are produced in the unit test were broken, as they added files that don't exist and that wasn't verified by the ro-crate library before ?

This "fixes" the unit tests with the newer ro-crate library:

```diff
diff --git a/lib/galaxy/model/store/__init__.py b/lib/galaxy/model/store/__init__.py
index ec8a9ea1be..33dbcf34d4 100644
--- a/lib/galaxy/model/store/__init__.py
+++ b/lib/galaxy/model/store/__init__.py
@@ -1924,30 +1924,30 @@ class DirectoryModelExportStore(ModelExportStore):
                 as_dict["extra_files_path"] = extra_files_path
             return
 
-        if file_name:
-            if not os.path.exists(dir_path):
-                os.makedirs(dir_path)
-
-            target_filename = get_export_dataset_filename(as_dict["name"], as_dict["extension"], dataset_hid)
-            arcname = os.path.join(dir_name, target_filename)
-
-            src = file_name
-            dest = os.path.join(export_directory, arcname)
-            add(src, dest)
-            as_dict["file_name"] = arcname
-
-        if extra_files_path:
-            try:
-                file_list = os.listdir(extra_files_path)
-            except OSError:
-                file_list = []
-
-            if len(file_list):
-                arcname = os.path.join(dir_name, f"extra_files_path_{dataset_hid}")
-                add(extra_files_path, os.path.join(export_directory, arcname))
-                as_dict["extra_files_path"] = arcname
-            else:
-                as_dict["extra_files_path"] = ""
+        # if file_name:
+        #     if not os.path.exists(dir_path):
+        #         os.makedirs(dir_path)
+
+        #     target_filename = get_export_dataset_filename(as_dict["name"], as_dict["extension"], dataset_hid)
+        #     arcname = os.path.join(dir_name, target_filename)
+
+        #     src = file_name
+        #     dest = os.path.join(export_directory, arcname)
+        #     add(src, dest)
+        #     as_dict["file_name"] = arcname
+
+        # if extra_files_path:
+        #     try:
+        #         file_list = os.listdir(extra_files_path)
+        #     except OSError:
+        #         file_list = []
+
+        #     if len(file_list):
+        #         arcname = os.path.join(dir_name, f"extra_files_path_{dataset_hid}")
+        #         add(extra_files_path, os.path.join(export_directory, arcname))
+        #         as_dict["extra_files_path"] = arcname
+        #     else:
+        #         as_dict["extra_files_path"] = ""
 
         self.dataset_id_to_path[dataset.dataset.id] = (as_dict.get("file_name"), as_dict.get("extra_files_path"))
 

```

Note how `as_dict["file_name"] = arcname` refers to a path inside the archive that doesn't exist outside of the archive.
I worry that this might be true outside of unit tests as well.

**Comment by mvdbeek** [comment]
Fix for that is in https://github.com/galaxyproject/galaxy/pull/16193

**Review by nuwang — APPROVED** [review]

**Pull request merged**
