### PR TITLE
[19.01] Fix dependency installation in UI

### PR DESCRIPTION
**Pull request by mvdbeek**
We need to pass the install kwarg here.
Broken in https://github.com/galaxyproject/galaxy/commit/2d3ab4ce1205aec24664225d74b2a851cb94b2b0

### CODE REVIEW

**Comment by martenson** [comment]
thanks @mvdbeek !

**Comment by nsoranzo** [comment]
@mvdbeek We can then remove `kwds['install'] = True` from https://github.com/galaxyproject/galaxy/commit/2d3ab4ce1205aec24664225d74b2a851cb94b2b0#diff-d67d082895c846a6e64465fea59344e7R256 , I suppose.

**Comment by mvdbeek** [comment]
Yeah, that's right (and also why API installs didn't have the issue). Good enough to do it on dev only ?

**Comment by nsoranzo** [comment]
Of course!

**Comment by davebx** [comment]
Thanks @mvdbeek. This has been applied to and solved the issue on usegalaxy.org

**Pull request merged**
