### PR TITLE
[WIP] Disable continue-on-error for beta selenium tests

### PR DESCRIPTION
**Pull request by mvdbeek**
and slowly check progress for the remaining failing tests

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
@mvdbeek Thanks for opening this up!  We can keep it rebased as fixes come in for a standing indicator of where we're at.

**Comment by mvdbeek** [comment]
Ah, of course this doesn't work, it'll run against the tests as defined on the default branch ...

**Comment by mvdbeek** [comment]
@dannon @Nerdinacan these are the failing tests in the beta history panel tests:
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_collection_operations
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_name_tags_display
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_execution_with_multiple_inputs
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_replacement_parameters
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_replacement_parameters_on_subworkflows
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_runtime_parameters_simple
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_subworkflows_simple
- [ ] FAILED lib/galaxy_test/selenium/test_collection_builders.py::CollectionBuildersTestCase::test_build_simple_list_via_rules_hidden
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_limiting_collection_rendering
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_output_collection_states_terminal
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_paired_display
- [ ] FAILED lib/galaxy_test/selenium/test_pages.py::PagesTestCase::test_simple_page_creation_edit_and_view
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_execution_with_custom_invocation_report
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_execution_with_null_optional_select_from_data
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_execution_with_rules
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_step_parameter_inputs
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_collection_operations
- [ ] FAILED lib/galaxy_test/selenium/test_history_panel_collections.py::HistoryPanelCollectionsTestCase::test_name_tags_display
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_execution_with_multiple_inputs
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_replacement_parameters
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_replacement_parameters_on_subworkflows
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_runtime_parameters_simple
- [ ] FAILED lib/galaxy_test/selenium/test_workflow_run.py::WorkflowRunTestCase::test_subworkflows_simple
~

**Comment by jmchilton** [comment]
I think these are all fixed in #12409 now.

**Comment by mvdbeek** [comment]
Awesome!

**Pull request closed without merging**
