### PR TITLE
Fix RStudio GIE

### PR DESCRIPTION
**Pull request by hexylena**
Updated the rstudio image to base it on `rocker/rstudio` instead of ubuntu/manually built. This image now includes an additional "disable authentication" flag so we can finally get rid of this horrible in-browser RSA that was *always* the flaky portion which kept killing the image. I expect it will be much more stable after here.

~~The new image is not yet ready, I'll move it out of draft when it is.~~

This PR could be very easily backported, for sites that want it.

### CODE REVIEW

**Comment by dannon** [comment]
@jmchilton, @erasche  Did you do anything special to get this working locally?  I'm getting no joy with the specified default image nor the non-release-tagged one on dockerhub.  Did you build it yourself?

**Comment by hexylena** [comment]
I can have a look today dannon, had been working for me, but I tested with
the more production setup

Op wo 8 mei 2019 22:34 schreef Dannon <notifications@github.com>:

**Comment by hexylena** [comment]
But if you have more details @dannon, on what error you were experiencing?

**Comment by mvdbeek** [comment]
The docker image wasn't on dockerhub, at least not yesterday, I guess that'd be one thing

**Comment by hexylena** [comment]
@mvdbeek oh, damn. Thanks for catching. It's on quay.

**Comment by dannon** [comment]
Yeah, the missing image.  Then I tried to use the latest one on dockerhub, which didn't work either (didn't expect it to being from the previous version of this, but it was worth a shot).  Didn't try quay.  Are we expecting folks to know to check there?

**Comment by hexylena** [comment]
Nope, will open a PR to fix. That was a stupid mistake on my part.

Op do 9 mei 2019 12:42 schreef Dannon <notifications@github.com>:

**Comment by dannon** [comment]
No worries, thanks!

**Comment by hexylena** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/7925

**Pull request merged**
