### PR TITLE
Fix metadata elements reset when creating Metadata files

### PR DESCRIPTION
**Pull request by mvdbeek**
This is a fallout out from 9780d069c8646fb4f02de848d62159680d95ae79

I noticed that some metadata elements from MAF files we're missing while working on https://github.com/galaxyproject/galaxy/pull/6627

### CODE REVIEW

**Comment by jmchilton** [comment]
Sorry for breaking this. I've read your comment a few times and I'm still unclear about what is happening. Any clue if this introduces a new flush in there or is this about getting SA to recognize objects that have changed value and it wasn't detecting as changed before?

**Comment by mvdbeek** [comment]
I'm not entirely sure what's going on either ... so what I'm seeing is that inside the loop that sets `dataset._metadata[name]` as soon as we flush here https://github.com/galaxyproject/galaxy/blob/5c889cd5e18e60818a922816884f56cb35262a2e/lib/galaxy/model/metadata.py#L566

we're losing all previously set metadata elements. So my interpretation is that when we flush only certain objects, the "dirty" ? objects are reset. Does that make any sense ?

**Comment by jmchilton** [comment]
> So my interpretation is that when we flush only certain objects, the "dirty" ? objects are reset. Does that make any sense ?

Yuk, I wasn't assuming it worked that way - I need to write a test case and verify that theory - that would be really gross and make what I was doing error prone.

**Comment by mvdbeek** [comment]
I mean, this isn't what's documented in the sqlalchemy docs either ... http://docs.sqlalchemy.org/en/latest/orm/session_api.html?highlight=flush#sqlalchemy.orm.session.Session.flush

**Comment by jmchilton** [comment]
Thanks for the fix!

**Pull request merged**
