### PR TITLE
Use installation monitoring view instead of monitoring grid 

### PR DESCRIPTION
**Pull request by guerler**
Branched from #4818. Currently the toolshed uses two separate types of installation monitoring views although they have the same title and content. The title is 'Monitor installing tool shed repositories'. One is a table and the other a grid mako. One is shown after successfully triggering an installation, the other when clicking on `Monitor installing repositories` in the admin panel. This PR removes the customized grid view and redirects calls to the table. Additionally the `manage_repositories` endpoint is renamed to `install_repositories` for clarification and now strictly returns json instead of html. This revises the last of three toolshed mako grids used in Galaxy's admin panel.

### CODE REVIEW

**Comment by dannon** [comment]
A nice step further would be to consolidate these two separate into a single filterable interface that just shows 'installing' repositories after the install step.

**Comment by guerler** [comment]
The underlying controller endpoint is the same. We could remove the link from the admin panel but then users would not be able to navigate back to the installation monitoring once they navigated away from it.

**Comment by dannon** [comment]
@guerler Yeah, the endpoint being the same is why I think it'd be nice to group it all together more tightly instead of having two views.

**Comment by martenson** [comment]
This might have introduced a regression where the 'messages' are not formatted. See screenshot.

screenshot 2017-10-30 15 14 22

**Comment by guerler** [comment]
Thanks for the details. I agree, that makes sense.

**Comment by guerler** [comment]
I'll look into it. Thx @martenson.

**Pull request merged**
