### PR TITLE
Clone tools in workflows

### PR DESCRIPTION
**Pull request by anatskiy**
This PR adds a new feature which allows cloning the tools preserving all the parameters by either clicking a new button in the tool header or by copy & pasting it (ctrl+c, ctrl+v).

screenshot

### CODE REVIEW

**Comment by bgruening** [comment]
ping @foellmelanie, who requested this feature.

**Comment by hexylena** [comment]
Fixes https://github.com/galaxyproject/galaxy/issues/940

**Comment by foellmelanie** [comment]
This is perfect, thanks a lot :) :cake:

**Comment by dannon** [comment]
~~Working on a few minor fixes for it this morning, will open a PR against the branch shortly.~~ Just going to follow up later; it'll be faster.

**Comment by dannon** [comment]
Merged locally w/ a rebuild to resolve conflicts.  Thanks!

I'll follow up with concerns in a separate PR.

**Pull request merged**
