### PR TITLE
[18.05] backport circleci testing

### PR DESCRIPTION
**Pull request by martenson**
this will prevent for old PRs to have a failed 'check' due to missing configuration

### CODE REVIEW

**Comment by dannon** [comment]
You probably just want to drop jslint from the testing list in this backport.  It's going to fail miserably until current dev (where it was added and all violations are fixed)

**Comment by martenson** [comment]
@dannon done, thanks!

**Review by jmchilton — APPROVED** [review]

**Comment by dannon** [comment]
Thanks, merged forward.

**Comment by martenson** [comment]
thanks for the forward merge!

**Pull request merged**
