### PR TITLE
Send correct dbkey and file_type  during upload from UI

### PR DESCRIPTION
**Pull request by jmchilton**
Seems to be needed on test.galaxyproject.org and for Selenium tests but not just running on my local laptop. I don't understand why this seems to be needed but this does seem to fix the problems.

A passing selenium suite with this change: https://jenkins.galaxyproject.org/view/All/job/jmchilton-selenium/172/.

### CODE REVIEW

**Comment by martenson** [comment]
Can we not require dbkey for upload instead? This feels very bioinformatics-specific.

**Comment by martenson** [comment]
related: https://github.com/galaxyproject/galaxy/issues/4484

**Comment by jmchilton** [comment]
@martenson https://github.com/galaxyproject/galaxy/pull/4790 passes fine for me locally - I don't think this parameter is actually required in general. We will see if it passes under Postgres shortly.

**Comment by jmchilton** [comment]
https://gist.github.com/jmchilton/cf28d17c94a141965c063a216567b88e here that test is passing under Postgres. ``dbkey`` isn't required, it isn't always required from the UI, it is sometimes required from the UI. It doesn't seem to be related to Postgres, or Nginx, or proxy prefix, or datatype configuration, or anonymous vs. logged in... I just really am stumped.

**Comment by natefoo** [comment]
Just to add to the strangeness, it's happening 100% of the time for me on Test, anonymous or logged in, but @guerler says it only happens for him if anonymous.

**Comment by jmchilton** [comment]
> Just to add to the strangeness

It is cursed - starting a new Galaxy - follow developments at https://github.com/jmchilton/galaxy-2.

**Comment by martenson** [comment]
Technically this should be `g3` (see the url `toolshed.g2.bx.psu.edu`)

**Comment by martenson** [comment]
https://test.galaxyproject.org/ on MacOS and Chrome 61 succeeds for me reliably while logged in as admin, fails for me reliably while anonymous.

At this point the only angle I can think of is the difference between web01 and web02.

**Comment by jmchilton** [comment]
> https://test.galaxyproject.org/ on MacOS and Chrome 61 succeeds for me reliably while logged in as admin, fails for me reliably while anonymous.

This is the case for me now also - earlier in the day it was always failing. But we reverted back to before the fix for empty ftp uploads - so I'm not sure how that interacts with this.

**Comment by martenson** [comment]
the request headers look identical, except anon has `null` as history_id, but that is expected...

**Comment by natefoo** [comment]
> At this point the only angle I can think of is the difference between web01 and web02.

Test runs on a single VM.

**Comment by martenson** [comment]
🤦‍♂️  https://github.com/jmchilton/galaxy-2/issues/1

**Comment by jmchilton** [comment]
> https://github.com/jmchilton/galaxy-2/issues/1

I'm not convinced that would be a problem if we were back at dev and test was running something with #4778 included. Earlier in the day when it was I think things failed more uniformly.

**Comment by natefoo** [comment]
Test is running 490dea3d267c1f5f7f5cc87cda759e31d3e4524b and has been most of the day, except when I was bisecting.

**Comment by guerler** [comment]
I opened a PR and added the default `file_type` to the upload request, it restores previous behaviour, see https://github.com/jmchilton/galaxy/pull/59. I think database keys and builds are fine. There are not necessarily bioinformatics-related unless we call them `genome_build`.

**Comment by jmchilton** [comment]
@guerler Thanks - looks good to me.

**Comment by martenson** [comment]
> There are not necessarily bioinformatics-related unless we call them genome_build.

No matter what you call it, the API shouldn't require it I think.

**Comment by jmchilton** [comment]
> No matter what you call it, the API shouldn't require it I think.

I opened a PR (#4790) proving the API doesn't require it - are you asserting the API requires it?

**Pull request merged**
