### PR TITLE
Remove: history_options and options.mako (history options as a page)

### PR DESCRIPTION
**Pull request by carlfeberhard**
I needed a pick-me-up today, so I destroyed the history options page.

### CODE REVIEW

**Comment by martenson** [comment]
:clap: destruction

**Comment by carlfeberhard** [comment]
@galaxybot test this and make all tests pass

**Comment by jmchilton** [comment]
:smiley:

**Comment by carlfeberhard** [comment]
@galaxybot Excellent! Tell the Roombas and the head of Phillip K. Dick's android that phase 3 has begun. HitchBOT, we will avenge you!

**Pull request merged**
