### PR TITLE
[16.01] Fix upgrade messages

### LINKED ISSUE #1546: Unhelpful error message when loading workflow
This is half-bug report, half-debugging help request.

When loading a particular workflow, I'm faced with the following:

selection_552

Whatever is causing that, is the bug I wish to fix.

Those objects are actually empty

selection_553

The keys however indicate two `<sections />` in my tool:

selection_554

which can be seen in the XML here:
- [config File](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/jbrowse.xml#L85)
-  [jbstyle macro](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/macros.xml#L201)
- [jbcolor_scale](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/macros.xml#L139)

The MWE is a workflow with a single step, JBrowse, a single track group, and a single track. No parameters other than the defaults. <s>Testing out #1545 now</s> doesn't help. I'm on 1b8f5280743526ac420280557067460d40362da5

@guerler any suggestions for debugging?

### PR DESCRIPTION
**Pull request by guerler**
Should fix #1546.

### CODE REVIEW

**Comment by hexylena** [comment]
:+1: from me, tested, it worked. Error messages went away nicely.

I'll open a separate issue to track the rest of #1546

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@guerler you cannot trigger travis restart via @galaxybot and I think you cannot fix travis by restarting because it is probably failing on pip problems that are not related to this PR

thanks for fixing this, I will merge it if you remove the WIP label

**Comment by guerler** [comment]
Ok. Thx.

**Pull request merged**
