### PR TITLE
Adding dataset uuid information to job and workflow invocation calls. 

### PR DESCRIPTION
**Pull request by kellrott**
This PR adds additional information to WorkflowInvocationStep records and Job records. This includes uuids of input and output datasets.

### CODE REVIEW

**Comment by jmchilton** [comment]
We discussed this out of channel - @kellrott  was going to follow up by adding the `uuid`s unconditionally and adding a `step_details` query parameter to the workfow invocation API endpoint so that a `collection` view doesn't automatically result in `element` views of its children.

**Comment by kellrott** [comment]
I've added in the changes that @jmchilton requested.

**Comment by jmchilton** [comment]
Ran the workflow API tests and they all still pass. I am very much a :+1: on this.

**Comment by dannon** [comment]
I'm +1, but this targets master.  @kellrott can you retarget dev?

**Comment by dannon** [comment]
(we'll have to close this one out and re-issue)

**Pull request closed without merging**
