### PR TITLE
HIV-TRACE visualization plug-in

### PR DESCRIPTION
**Pull request by stevenweaver**
## A description of why the changes should be made.

As part of a continuing effort to implement [HIV-specific workflows](https://github.com/galaxyproject/tools-iuc/issues/1020) into Galaxy. 

## A description of the implementation of the changes.
Adds a new visualization that handles output from the [hivclustering tool](https://github.com/veg/tools-iuc/tree/master/tools/hivclustering).

## A description of how to test the changes.
* Upload [output](https://veg.github.io/hivtrace-viz/example.json) from hivclustering into galaxy. 
* Click visualizations button. 
* Click HIV-TRACE

apr-09-2018 15-07-12

### CODE REVIEW

**Comment by guerler** [comment]
@stevenweaver Cool, glad it worked out.

**Comment by stevenweaver** [comment]
@guerler -
Yes, it wouldn’t have been possible without your help!

**Comment by dannon** [comment]
@stevenweaver Glad this is working now with the plugin static-handling changes!

How did you build the vendor.js file?  It looks to be webpack, but I'm not seeing the infrastructure to rebuild it here in these commits -- is there a package.json that has been left out?

**Comment by bgruening** [comment]
@stevenweaver you might want to define an own datatype for you tool and your vis, subclassing from json. Otherwise, all json files would show your vis.

Thanks for this nice contribution.

**Comment by stevenweaver** [comment]
Dear @dannon, 

hivtrace-viz is already an npm package, but I didn't see a straightforward way of including it as a dependency. 

* [npm link](https://www.npmjs.com/package/hivtrace-viz)
* [github repo link](https://github.com/veg/hivtrace-viz)

If it is desirable to use webpack to install, I can give it a try. 

@bgruening, 
Thanks, I was following cytoscape's lead. I'll need to investigate how to subclass. 

Thanks for the quick feedback,
Steven

**Comment by dannon** [comment]
@stevenweaver Yeah, what we've done more recently for visualization plugins is, instead of including static dependencies like here, do something like this:  https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/visualizations/nvd3/nvd3_bar/package.json.

There are a bunch of benefits to this, but two big ones are: 1) downstream work can easily rebuild plugins, and 2) we avoid adding large static libraries to the Galaxy codebase.

If you'd rather, I can probably pretty quickly refactor the dependencies here, now that I know hiv-trace is an npm package.

**Comment by stevenweaver** [comment]
@dannon, 

If you do not mind, by all means. I'll be sure to take note of the changes you make in the commit. 

Best,
Steven

**Comment by nekrut** [comment]
@dannon tx for pitching in on this one!

**Comment by dannon** [comment]
@stevenweaver Sure, I can do that.

**Comment by stevenweaver** [comment]
@dannon - Great, thank you. I'm looking into creating a new datatype in the meantime.

**Comment by stevenweaver** [comment]
@bgruening, 

I've created a new subtype for hivtrace in the latest commit. The xml whitespace formatting in config/datatypes_conf.xml.sample was inconsistent, so I went ahead and fixed that as well. 

Best,
Steven

**Comment by bgruening** [comment]
cool thanks @stevenweaver!

**Comment by dannon** [comment]
@stevenweaver Sorry for the delay on this; I've been having some trouble getting hivtrace bundled/shipped correctly, and I think a fix may require some changes upstream (in hivtrace-viz).  I'm going to go ahead and merge this and follow up with you separately on the bundling work.

**Comment by stevenweaver** [comment]
@dannon Thanks for looking into this. We have been moving over to React for proper bundling of DOM elements and JavaScript logic for current development, but `hivtrace-viz` was developed just prior to this shift.

**Pull request merged**
