### PR TITLE
Fix for #781: remove the detail check from the final HDA fetch since …

### PR DESCRIPTION
**Pull request by carlfeberhard**
…details are fetched on tool submission; Dataset-li: remove redundant call to _setUpListeners

As a side note: we're piling up the expensive keys and details - this may cumulatively effect our performance. I'll look for alternate ways to handle these things.

Edit: this fixes the case where an expanded queued or running dataset would enter a ready state but not fetch the additional details need to fully render the dataset view.

### CODE REVIEW

**Comment by dannon** [comment]
This seems to still have the problem with refreshing the dataset contents once the job state changes and is final.  What I'd suggested to @guerler was that on state change we really needed to request new details (when expanded) and do a full rerender.

What bit from 781 does this fix?  Maybe I misunderstood.  (thanks for clarification/edit of the comment above to address what it actually fixes)

**Comment by carlfeberhard** [comment]
@dannon yes - that's what it does and has done in the past.
The main difference here being that you've fetched the details on tool submission and, previously, the on-ready-state fetch and render would not fetch details if it already had them. I've removed that details check.

**Comment by dannon** [comment]
Got it -- that part makes sense, the other bit I was trying to sort out was that I'm seeing details fail to get updated, resulting in views like this:

image

**Comment by carlfeberhard** [comment]
You're seeing that with this commit?

**Comment by dannon** [comment]
Triple checking now, but, yes.

**Comment by carlfeberhard** [comment]
Ok - yeah I see it now. This commit fixed the new functionality but the old is lost now.

**Comment by dannon** [comment]
Looks like the expand logic just needs to force a detail recheck?

**Comment by carlfeberhard** [comment]
Not if we only want to fetch this on the first expansion. Ugh (getting complicated).

**Comment by dannon** [comment]
If the has_details bit is tied to state change (wiped on state change and refreshed), this should work right?  If state hasn't changed, details bit will be accurate.  If state _has_ changed, details bit is not accurate.   (state change dirties the details bit)

**Comment by carlfeberhard** [comment]
At any rate this and the api that lazy-loads and updates is a bit of a Rube Goldberg device at this point. So apologies to Dannon for his having to wade into that. I'll take a longer look at this and see if I can get 'rerunnable' into the summary after the tool submission and straighten some things out.

**Comment by carlfeberhard** [comment]
Closing this in preference to #793.

**Pull request closed without merging**
