### PR TITLE
GIE Galaxy Filesystem Volume

### PR DESCRIPTION
**Pull request by hexylena**
I'm breaking *all* of the IEs :) But this is necessary for Main + EU.

This is not globally optimal. It is not optimal for small sites which don't have the requirements that we do. It is not optimal for Phinch/Bam IOBIO/HicBrowser IEs which just want a single file, and they want it mounted in (and it may be large.)

However it gives us a single way forward with a single way to access files that big sites can use and small sites can live with.

## Galaxy Filesystem

I've developed a docker volume plugin. This is a small service that responds to API requests from Docker and then mounts/unmounts FUSE volumes.

The FUSE mount is a Galaxy FUSE mount, it does the same thing as previous galaxy-fuse filesystems but actually implements the `read` operation (all prior art requires `expose_dataset_path` and just uses symlinks.) It exposes two methods, and ID-only and an ID + "human readable name". It supports dataset collections (list, paired, list:paired). The ID-only version will work well for IEs that just need a specific file (DATASET_ID, HISTORY_ID are passed, should be sufficient to find the path since it will always be `/galaxy/history/...`)

https://github.com/erasche/docker-galaxy-volume

```
$ docker run -it --user 1000:1000 --mount type=volume,destination=/galaxy,volume-driver=galaxy,volume-opt=url=http://localhost,volume-opt=apikey=76d1a621e9d80751c1475c176ae6ee12 python:3.6-alpine /bin/sh
/ $ find /galaxy/
/galaxy/
/galaxy/histories
/galaxy/histories/f597429621d6eb2b
/galaxy/histories/f597429621d6eb2b/f2db41e1fa331b3e_dc
/galaxy/histories/f597429621d6eb2b/f2db41e1fa331b3e_dc/33b43b4e7093c91f
/galaxy/histories/f597429621d6eb2b/f2db41e1fa331b3e_dc/a799d38679e985db
/galaxy/histories/f597429621d6eb2b/f2db41e1fa331b3e_dc/5969b1f7201f12ae
/galaxy/histories/f597429621d6eb2b/f2db41e1fa331b3e_dc/df7a1f0c02a5b08e
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/33b43b4e7093c91f_dc
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/33b43b4e7093c91f_dc/ebfb8f50c6abde6d
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/33b43b4e7093c91f_dc/1cd8e2f6b131e891
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/df7a1f0c02a5b08e_dc
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/df7a1f0c02a5b08e_dc/f597429621d6eb2b
/galaxy/histories/f597429621d6eb2b/f597429621d6eb2b_dc/df7a1f0c02a5b08e_dc/f2db41e1fa331b3e

$ docker run -it --user 1000:1000 --mount type=volume,destination=/galaxy,volume-driver=galaxy,volume-opt=url=http://localhost,volume-opt=apikey=76d1a621e9d80751c1475c176ae6ee12,volume-opt=human_readable=true python:3.6-alpine /bin/sh
/ $ find /galaxy/
/galaxy/
/galaxy/histories
/galaxy/histories/Test __f597429621d6eb2b
/galaxy/histories/Test __f597429621d6eb2b/list __f2db41e1fa331b3e_dc
/galaxy/histories/Test __f597429621d6eb2b/list __f2db41e1fa331b3e_dc/Pasted Entry __33b43b4e7093c91f
/galaxy/histories/Test __f597429621d6eb2b/list __f2db41e1fa331b3e_dc/Pasted Entry __a799d38679e985db
/galaxy/histories/Test __f597429621d6eb2b/list __f2db41e1fa331b3e_dc/Pasted Entry __5969b1f7201f12ae
/galaxy/histories/Test __f597429621d6eb2b/list __f2db41e1fa331b3e_dc/Pasted Entry __df7a1f0c02a5b08e
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/1 __33b43b4e7093c91f_dc
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/1 __33b43b4e7093c91f_dc/Pasted Entry __ebfb8f50c6abde6d
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/1 __33b43b4e7093c91f_dc/Pasted Entry __1cd8e2f6b131e891
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/2 __df7a1f0c02a5b08e_dc
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/2 __df7a1f0c02a5b08e_dc/Pasted Entry __f597429621d6eb2b
/galaxy/histories/Test __f597429621d6eb2b/list:paired __f597429621d6eb2b_dc/2 __df7a1f0c02a5b08e_dc/Pasted Entry __f2db41e1fa331b3e
```

## TODO

- [ ] rewrite all IEs to take advantage of this
- [ ] see if anything else can be ripped out
- [ ] easy deployment of the galaxy docker volume driver

### CODE REVIEW

**Comment by hexylena** [comment]
grafik

```Dockerfile
FROM mikebirdgeneau/jupyterlab
RUN adduser -D jupyter
RUN chown jupyter: -R /opt/app/data
USER jupyter
CMD jupyter lab --ip=* --port=8888 --no-browser --notebook-dir=/opt/app/data --LabApp.token=''
```

run with:

```console
docker run -it -p 8888:8888 --mount type=volume,destination=/opt/app/data/galaxy,volume-driver=galaxy,volume-opt=url=http://localhost,volume-opt=apikey=76d1a621e9d80751c1475c176ae6ee12,volume-opt=human_readable=true qq
```

**Comment by hexylena** [comment]
Accidental closure, sorry for noise.

**Comment by jxtx** [comment]
Glad to hear it since this is so exciting. Rather than re-writing all the GIEs, can we start gradually by just having a GIE assert that it should use this in the config file? 

Is easy deployment then the main barrier to merging this?

**Comment by hexylena** [comment]
> Rather than re-writing all the GIEs, can we start gradually by just having a GIE assert that it should use this in the config file?

We could do this, but there's a large part of me that just wants to rip out as much of the legacy horribleness as possible. But I recognise there are people who won't want this deployment option since it's an extra thing to do, even if it simplifies development. So we will probably end up doing that, and just rewriting in-tree GIEs.

> Is easy deployment then the main barrier to merging this?

Barriers to merging:

- [ ] This PR doesn't include everything yet, e.g. passing IDs correctly such that containers can locate the data in the volume mount
- [ ] The docker volume plugin currently doesn't clean up after itself (filesystems are mounted and then forgotten about. If the service restarts, the previous filesystems are left mounted until the next reboot. There are some ugly edges that can be cleaned up)
- [ ] The docker volume plugin has non-trivial installation that can be simplified significantly before we start pushing this as the way to go.

**Comment by hexylena** [comment]
Still something to do but need to redo everything for ITs. So closing.

**Pull request closed without merging**
