### PR TITLE
Update node-sass, old version not compatible with node 12

### PR DESCRIPTION
**Pull request by innovate-invent**
node 12 is not compatible with sass 4.11
https://github.com/sass/node-sass/issues/2648

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
I don't think we want to update already released code with build dependency changes. I will open a PR against dev. Thanks for bringing this up.

**Comment by innovate-invent** [comment]
@martenson 19.05 fails to build though.

**Comment by martenson** [comment]
Only with newer node though.

**Comment by dannon** [comment]
@innovate-invent Are you able to use the node version shipped with Galaxy?  This exact problem is why we started pinning to, autoinstalling, and using particular node versions.

**Comment by nsoranzo** [comment]
The node version supported in 19.05 is [10.13.0](https://github.com/galaxyproject/galaxy/blob/release_19.05/client/.node_version) .

**Pull request closed without merging**
