### PR TITLE
Set a default value for copy history dialog radio input (to copy *all*).

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by martenson** [comment]
I am not sure this is a reasonable default. I would rather see it as it is (thus forcing people to think) or to 'copy only active' be pre-chosen.

Could there be a side effect of 'copying all' every time like increased difficulties when trying to free the quota or do I get it wrong? ( If you want to purge deleted and you have the same deleted dataset in multiple histories it won't free your space? )

**Comment by dannon** [comment]
I was erring on the side of preserving everything by default, like Galaxy typically does.  It is also the first option (intentionally, I assume), and I'd guess that's what most people use.  This is just my gut feeling though, and (while I wish I did) I don't have hard data for it.

It's a good point about purging, but I think it is hopefully fairly obvious in the history panel these days when you have 'deleted' datasets, so I'm not as worried about the purge issue.

**Comment by martenson** [comment]
@dannon thanks for the reasoning

**Comment by dannon** [comment]
@martenson Sure, anytime.  Thanks for bringing it up, it's definitely worth thinking about these things :)

**Comment by nsoranzo** [comment]
Retroactive :+1:

**Pull request merged**
