### PR TITLE
Expand selenium test coverage for workflows.

### PR DESCRIPTION
**Pull request by jmchilton**
From commit description for b4d6bc0:

Expand and then break out workflow management tests into its own file since these aren't related to the workflow editor per se. Includes new tests of workflow "viewing" and "renaming".

Add a new file with a workflow running test case.

This includes a refactoring of some existing tests related to checking various things in the history panel - as part of building up good history panel abstractions. The previous constructs were ported fairly literally from older CasperJS tests. These abstractions therefore referred to everything has "hda"s instead of history items. The newer abstractions therefore allow for collections and are built around HIDs (a visual thing exposed to the user) instead of HDA IDs. I think this is higher-level and more appropriate for a web functional test.

Additionally, affb939 contains a re-arrangement of a lot of API test helper code so that it can be helper code for multiple kinds of tests - including Selenium. This was needed for quickly importing dynamic workflows for testing.

### CODE REVIEW

**Comment by bgruening** [comment]
I really like this! Your testing work is impressive! Thanks John to care about this important piece of Galaxy!

**Comment by jmchilton** [comment]
This has been rebased a few times over the last few days by me - it now contains Selenium tests for
 - Running workflows with tool upgrades - to ensure the warning message appears.
 - Editing workflows with tool upgrades - to ensure the warning message related to the version change appears.
 - Editing workflows with a tool state corrections - to ensure the message about restoring the default appears.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@jmchilton any idea why these test do not start?

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@bgruening Not a clue - maybe it was overloaded earlier? There were some free slots and it seems to be running now though.

**Comment by bgruening** [comment]
Overloaded can be, but I had hoped to see jobs queued in Jenkins. Soon @martenson will be back! :)

**Comment by bgruening** [comment]
Ok, but now we need also a merge here, sorry.

**Comment by jmchilton** [comment]
@bgruening No problem - I rebased to resolve the problem introduced with the merging of that jerk @jmchilton's PR.

**Pull request merged**
