### PR TITLE
add minor styling to tour popover

### PR DESCRIPTION
**Pull request by martenson**
Additionally the contents of `static/style/blue/bootstrap-tour.css` should probably be converted to .less and moved into newly created `tour.less` 

screenshot 2016-01-19 17 56 34

### CODE REVIEW

**Comment by dannon** [comment]
I'm not sure about the style change (but not -1, if other people like it -- fine); it just feels like a very heavy color to use for popup titles when our other popups don't use similar mastheads.

I would caution against the proposed `bootstrap-tour.css` being translated and copied into this file though.  That file is styling distributed along with bootstrap-tour, and we should continue to use it unaltered in its distributed form to avoid upgrade issues, for now.  There are a few styling issues to work out still, but part of the point of bootstrap-tour was that it would just look 'like Galaxy' out of the box, using our existing bootstrap customizations of .popover, etc., and I'd like to be able to do away with the extra file completely -- just need to do a review of what's missing in our existing bootstrap-based styling.

**Comment by martenson** [comment]
We are currently using popovers (outside of tours) in a different manner - they show up near your cursor when you click. I believe the contrast of the popover is needed in tours as they appear in random locations on the screen and if you have a large screen it is difficult to notice white popover on a white background.
 I am opened to any colors/themes though (this is just the masthead color).

**Comment by jxtx** [comment]
I like having a bolder look, but I'm open to other ways of making the tour popover more emphasized.

**Comment by bgruening** [comment]
In our initial tours we had a backdrop shadow for all elements that are not relevant. For a few use-cases this was really good imho. But this seems feature seems broken in bootstrap-tours in Galaxy for the moment.
I like this change as it is a clear improvement imho, until figured out what’s wrong with backdrop.

**Comment by dannon** [comment]
Sounds good to me, my style choices are broken this morning :)

Thanks @martenson!

**Comment by dannon** [comment]
(merging manually to resolve conflict)

**Comment by martenson** [comment]
@galaxybot test this
(testing bot)

**Comment by martenson** [comment]
Please note that `.popover-title` is not tour-specific so this effects every popover in Galaxy. Now when I think about it the tour.less file was not the best choice :/

**Pull request merged**
