### PR TITLE
Show welcome page with required login

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by dannon** [comment]
Heh.  Iframes, no iframes, iframes, no iframes!

Anyway, this is nice, +1!

**Comment by guerler** [comment]
Yes, sorry for that. I removed the iframes and then realized that some redirects did not look right e.g. after entering a wrong password. Thx.

**Comment by bgruening** [comment]
@dannon @guerler this is also affecting 15.10. Would be nice to fix it in this release for all Galaxy instances that have login required.

**Comment by dannon** [comment]
@bgruening It doesn't go to 15.10 because it's totally new functionality, and not a bugfix, right?  15.07 didn't display the welcome either.

**Comment by martenson** [comment]
Yeah, this is a new feature. We can try to defend it as a 'bugfix' but it would be hard. :D

**Comment by bgruening** [comment]
Ok, we loosed our welcome page hack during the last bug with require_login=True. I need to look at this closer. Thanks.

**Pull request merged**
