### PR TITLE
fix repo search by explicitly casting response to string

### PR DESCRIPTION
**Pull request by martenson**
some change happened recently that broke this, not sure where but
nothing else is probably affected

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by davebx** [comment]
:+1:

**Comment by dannon** [comment]
Do you have a little more context for this?  Just trying to figure out how '%s(%s)' % (subs) ends up as anything but a string.

**Comment by blankenberg** [comment]
Yeah, does seem strange, unless downstream not handling unicode or something. u'a' vs 'a'.

**Comment by martenson** [comment]
I spent some time on this and as I mention I do not know what broke it. Without the `str()` the reponse is 200 but empty even though `log(response)` (in the decorator) would give you the correct `callback({"foo":"bar"})`

**Comment by dannon** [comment]
Ugh.  Passing blanket Except somewhere higher in the stack maybe?

**Comment by martenson** [comment]
Might be - the returning string is not valid json (it is valid javascript though) - but that is why I am using _raw_
edit: Our response contentType is set to json by default but if we enforce it somewhere along the way we should not do it for _raw_ and we should give good exception

**Comment by dannon** [comment]
If you're able to dig more, I think it'd probably be a good thing to resolve whatever is happening higher in the stack -- otherwise this is just passing the buck for another day.  If you're not, that's cool, but we're probably going to have to deal with this same issue again in the future.

**Comment by martenson** [comment]
If I find time I will. For now please merge the PR.

**Comment by dannon** [comment]
Works for me.  I made a trello card so we don't forget about it here:  https://trello.com/c/g4lEE1d9/2622-follow-up-on-issue-in-https-github-com-galaxyproject-galaxy-pull-93-issuecomment-90735938

**Pull request merged**
