### PR TITLE
Use es6 literal for library toolbar header, use icon buttons, left align

### PR DESCRIPTION
**Pull request by guerler**
Suggestion for library toolbar header appearance.

### CODE REVIEW

**Comment by martenson** [comment]
looks nice, we can merge as is if you want

**Comment by guerler** [comment]
I followed-up by adjusting the folder toolbar too.

**Comment by guerler** [comment]
@galaxybot test this

**Review by martenson — APPROVED** [review]
works well, thanks for the pretty formatting too!

**Comment by nsoranzo** [comment]
I think this has introduced a failure in Selenium tests: https://jenkins.galaxyproject.org/job/docker-selenium/5037/testReport/junit/selenium_tests.test_library_contents/LibraryContentsTestCase/test_import_dataset_from_history/

**Comment by nsoranzo** [comment]
The culprit seems to be commit 8702d671a8250fb67d49a76ae72b4a50e675bc43 , according to git bisect.

**Comment by guerler** [comment]
Thanks @nsoranzo. I'll check it out.

**Comment by guerler** [comment]
@nsoranzo #7321 fixes this.

**Pull request merged**
