### PR TITLE
[17.01] Fix tools that use Galaxy sequence utilities for #3364.

### PR DESCRIPTION
**Pull request by jmchilton**
Thanks to @peterjc for reporting and @martenson for grepping.

xref #minor #3364

- [x] ~000/repo_830/fastq_paired_end_splitter.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter, fastqSplitter~ has tool dep
- [x] ~000/repo_816/fastq_filter.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter~ has tool dep
- [x] ~000/repo_794/fastq_paired_end_joiner.py:7:import galaxy_utils.sequence.fastq as fq~ has tool dep
- [x] ~000/repo_820/fastq_to_tabular.py:3:from galaxy_utils.sequence.fastq import fastqReader~ has tool dep
- [x] ~000/repo_813/fastq_trimmer.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter~ has tool dep
- [x] ~000/repo_810/fastq_paired_end_deinterlacer.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter, fastqNamedReader, fastqJoiner~ has tool dep
- [x] 000/repo_54/tools/venn_list/venn_list.py:59:        from galaxy_utils.sequence.fastq import fastqReader (opened PR)
- [x] ~000/repo_797/fastq_manipulation.py:4:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter~ has tool dep
- [x] ~000/repo_220/cgatools/lib/galaxy/datatypes/completegenomics.py:17:import galaxy_utils.sequence.vcf~ datatype
- [x] ~000/repo_811/fastq_to_fasta.py:3:from galaxy_utils.sequence.fastq import fastqReader~ has tool deps
- [x] ~000/repo_811/fastq_to_fasta.py:4:from galaxy_utils.sequence.fasta import fastaWriter~ has tool deps
- [x] 000/repo_41/tools/seq_rename/seq_rename.py:112:        from galaxy_utils.sequence.fasta import fastaReader, fastaWriter (opened PR)
- [x] 000/repo_349/deseq/fonctionsNGS/differential_expression_analysis_pipeline_for_rnaseq_data/DiffExpAnal/fastq_groomer_parallel.py:8:from galaxy_utils.sequence.fastq import fastqReader, fastqVerboseErrorReader, fastqAggregator, fastqWriter (opened PR)
- [x] ~000/repo_827/fastq_stats.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqAggregator~ has tool deps
- [x] 000/repo_16/tools/fasta_tools/fasta_filter_by_id.py:22:from galaxy_utils.sequence.fasta import fastaReader, fastaWriter (opened PR) 
- [x] ~000/repo_805/fastq_trimmer_by_quality.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter~ (has tool deps)
- [x] ~000/repo_823/fastq_combiner.py:3:from galaxy_utils.sequence.fastq import fastqWriter, fastqSequencingRead, fastqCombiner, fastqFakeFastaScoreReader~
- [x] ~000/repo_823/fastq_combiner.py:4:from galaxy_utils.sequence.fasta import fastaReader, fastaNamedReader~ (has tool deps)
- [x] 000/repo_396/tools/seq_primer_clip/seq_primer_clip.py:34:from galaxy_utils.sequence.fasta import fastaReader, fastaWriter (opened PR)
- [x] ~000/repo_793/fastq_masker_by_quality.py:4:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter~ (has tool deps)
- [x] ~000/repo_219/cgatools/lib/galaxy/datatypes/completegenomics.py:17:import galaxy_utils.sequence.vcf~ datatype
- [x] 000/repo_250/fastq_groomer_parallel.py:13:from galaxy_utils.sequence.fastq import fastqReader, fastqVerboseErrorReader, fastqAggregator, fastqWriter (opend PR)
- [x] ~000/repo_250/README:34:    from galaxy_utils.sequence.fastq import fastqReader, fastqVerboseErrorReader, fastqAggregator, fastqWriter~
- [x] ~000/repo_817/fastq_groomer.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqVerboseErrorReader, fastqAggregator, fastqWriter~ has tool deps
- [x] 000/repo_17/tools/fastq/fastq_filter_by_id.py:25:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter opened PR
- [x] ~000/repo_804/fastq_paired_end_interlacer.py:3:from galaxy_utils.sequence.fastq import fastqReader, fastqWriter, fastqNamedReader, fastqJoiner~ has tool deps
- [x] ~001/repo_1876/lib/galaxy/datatypes/completegenomics.py:18:import galaxy_utils.sequence.vcf~ datatype

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks guys. I assume that if and when these tools are updated with an explicit dependency on galaxy_utils_sequence this setting would be harmless?

**Comment by mvdbeek** [comment]
Actually, I think that they wouldn't pick up python conda dependencies, since we only add the conda  environments bin folder to that path, instead of a full conda environment activation. So indeed that would be a problem :(.

**Comment by jmchilton** [comment]
@mvdbeek is definitely right - I want to make another pass at these sequence utils tools. It would probably be better to just add the external library to the virtualenv and delete them from Galaxy. I think that would fix these tools and be future proof with Conda. @martenson do you mind if we delay the release a few more days?

**Comment by peterjc** [comment]
I'll work on getting all my tools using ``galaxy_utils.sequence`` to declare the dependency, so they won't need whitelisting. It would require local Galaxy Admins to update the tool, but as long as they did this via the Tool Shed it should be quite straightforward.

**Comment by peterjc** [comment]
i.e. Make galaxy itself depend on the external ``galaxy_utils_sequence`` library? That does make a lot of sense at first glance.

**Comment by martenson** [comment]
@jmchilton This sounds like a very good solution to me, no objections.

**Comment by jmchilton** [comment]
Cool then - I'll spend the day making sequence_utils look like planemo - do a release, do a starforging, and open a PR against 17.01 on cool new wheel.

**Comment by martenson** [comment]
@jmchilton wheeeeeeee....l 🎉

**Comment by peterjc** [comment]
One of the tools affected is https://toolshed.g2.bx.psu.edu/view/kevyin/fastq_groomer_parallel/ which I assume is the same author as @kevyin here on GitHub.

@kevyin: Due to Galaxy changes affecting tools currently using Galaxy's own internal sequence parsing code, It may be necessary to update your parallel FASTQ groomer by doing something like this: https://github.com/peterjc/pico_galaxy/commit/2e8900eacb7c362d12ae71f281af890262f35dfc

**Comment by peterjc** [comment]
This pull request white-listed six tools from the main Tool Shed using ``galaxy_utils.sequence``.

I have updated these on the TTS and MTS with the new explicit dependency:

 - venn_list - https://toolshed.g2.bx.psu.edu/view/peterjc/venn_list/ba31415fedc5
 - seq_rename - https://toolshed.g2.bx.psu.edu/view/peterjc/seq_rename/e1398f2ba9fe
 - seq_primer_clip - https://toolshed.g2.bx.psu.edu/view/peterjc/seq_primer_clip/9b074c1db68e

That leaves:

 - fastq_groomer_parallel - not mine, see comment above
 - fasta_filter_by_id - mine but deprecated https://toolshed.g2.bx.psu.edu/view/peterjc/fasta_filter_by_id
 - fastq_filter_by_id - mine but deprecated https://toolshed.g2.bx.psu.edu/view/peterjc/fastq_filter_by_id

I'd already updated ``fastq_pair_names`` which is only on the TTS and therefore wasn't included in the white-list in this pull request.

**Comment by peterjc** [comment]
I have now updated all file of my tools white listed in this pull request to declare the new dependency.

Given the concerns raised by @mvdbeek, and the work from @jmchilton to move ``galaxy_utils.sequence`` into an external dependency, should this commit be reverted?

**Comment by martenson** [comment]
@peterjc once we have #3551 we probably want to revert

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/galaxy/pull/3551 undoes these changes - I just deleted the lines. It is not a formal "Git" rollback or whatever but I think it is good enough.

**Comment by peterjc** [comment]
Thanks @jmchilton - undoing the change in #3551 is fine, I didn't mean necessarily via a ``git revert``.

**Comment by kevyin** [comment]
@peterjc I've updated the toolshed repos.

https://github.com/peterjc/pico_galaxy/commit/2e8900eacb7c362d12ae71f281af890262f35dfc

From your commit example am i right to assume that all that's needed is to include the dependency?  python will be able to find and import the utils ?


PS in your example, the ending requirement tag doesn't have a slash ie `</requirement>` is this a typo?

**Comment by peterjc** [comment]
@kevyin yes, the missing slash was an error - thank you. Already fixed in https://github.com/peterjc/pico_galaxy/commit/345775c5428dca961b2b8e114424e931c0f51154 - the ``planemo lint`` commands are useful for checking this.

**Pull request merged**
