### PR TITLE
Break connection in workflow editor if necessary

### PR DESCRIPTION
**Pull request by mvdbeek**
When switching tool versions in the workflow editor connections are
maintained by default. If a tool changes the datatype one may end up
with a connection between incompatible input/outputs. Therefore we
update the datatypes and explicitly destroy invalid connections.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Interesting, no tests are picked up ... :/

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Great - thanks for the fix @mvdbeek !

**Pull request merged**
