### PR TITLE
[16.10] Fix RStudio login

### PR DESCRIPTION
**Pull request by hexylena**
Ping @bgruening @jmchilton

### CODE REVIEW

**Comment by martenson** [comment]
@erasche you might be targeting the wrong branch

**Comment by hexylena** [comment]
Thanks @martenson

**Comment by hexylena** [comment]
Fixed

**Comment by bgruening** [comment]
:+1: go for it @erasche!

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
Thanks for the fixes @erasche!

**Comment by hexylena** [comment]
@dannon how does this get merged forward? Is there a script I can run, or set of commands? I don't want to cause any issues

**Comment by dannon** [comment]
I usually, from an up-to-date local dev branch, just do something like:
```
% git fetch upstream
% git merge upstream/release_16.10
(handle any resolution)
% git commit
% git push upstream/dev
```

@erasche PS:  I'm more than happy to handle this if you want, just let me know if I can help

**Comment by hexylena** [comment]
@dannon, ah, great! I just wanted to learn a bit more about how it worked, perhaps decrease bus-factor :) If you're offering though, that would be really appreciated, thank you!

**Comment by dannon** [comment]
@erasche Sure, definitely a good idea to decrease the bus-factor.  And, of course, handling it now.

**Pull request merged**
