### PR TITLE
[24.0] Fix hasOwner function for histories in client

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
The `hasOwner` function in `api/index.ts` was checking:
```
return "user_id" in history;
```

whereas, it also needed to check:
```
return "user_id" in history && history.user_id !== null;
```

because we assume histories (summaries) initally fetched for the `historyStore` without `user_id` are owned by the current user, but the key is still present in the backend return.

This was causing a really troublesome bug in the `HistoryScrollList` found in the history selector modal, where we would constantly keep fetching `api/histories/count` since we didn't have the expected no. of histories loaded in the component; because `historiesProxy` (which only contains owned histories) would end up being empty.
Interestingly, this was only reproducible on Test and happening if the total number of histories was very small...

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — APPROVED** [review]

**Comment by davelopez** [comment]
The weird part here is that a summary view of a history should not return `user_id` and even less `null` so we need to investigate what else is going on here.

Weirdly enough, the API response that contains the `user_id` is in the test instance.

Test: https://test.galaxyproject.org/api/histories/d8ba3263482062f4?view=summary (has `user_id: null`)
Main: https://usegalaxy.org/api/histories/8c8f2ac386a1ea66?view=summary

**Comment by mvdbeek** [comment]
> Weirdly enough, the API response that contains the `user_id` is in the test instance.

I'm sure we're not updating that very often ;).

If we're passing through the API and we're not excluding unset values we'd expect null for optional fields, so that seems to make sense. If there's anything to fix the question is which endpoint returns the "wrong" response, but also `null` meaning no owner seems fine ?

**Comment by mvdbeek** [comment]
Are we talking about the same endpoint here @ahmedhamidawan ? How did you run into this ?

**Comment by ahmedhamidawan** [comment]
> Are we talking about the same endpoint here @ahmedhamidawan ? How did you run into this ?

So the endpoint that returns `user_id: null` is `api/histories` (or `api/historiest{id}?view=summary`) on Test (not on main); thats how I ran into this; the selector modal for histories keep loading the total count over and over since the hasOwner fn had the bug fixed here. 

This endpoint had user_id as an optional field whereas, since @davelopez 's recent improvements, we dont include the user_id at all in the summary. Which is why this happening at all is weird.

**Pull request merged**
