### PR TITLE
[23.0] Fix bug: Make model serializable

### PR DESCRIPTION
**Pull request by jdavcs**
Ref: https://github.com/galaxyproject/galaxy/pull/17922#discussion_r1554626353

Bug surfaced after adding type hints to the model in #17922

@mvdbeek is this the right implementation?

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
I don't know, you'd have to add a test.

**Comment by jdavcs** [comment]
> I don't know, you'd have to add a test.

Sorry, but I'm not sure what behavior to test.. I used a basic implementation in other models as an example. Is this all that's needed here? i.e., assign the mapped attributes to a dict and return the dict?

The API tests that break against 23.0 run against 23.1, so I don't think those errors are not related to the edits.

**Comment by mvdbeek** [comment]
I did say I would fix it, but I don't have time right now. Mark it as `type-ignore` for now ?

**Comment by jdavcs** [comment]
Thanks for the pointer, I was curious how this part of the code base works. Will try to figure it out.

**Pull request closed without merging**
