### PR TITLE
Cleanup SA objects between workflow invocation scheduling attempts.

### PR DESCRIPTION
**Pull request by jmchilton**
This would seem to be a fairly serious memory leak in the abstract but I don't have data that it fixes anything. None the less if it gets into dev and the tests seem to pass I'll open a PR to backport it to at least 17.05 and maybe back even more.

xref #5044

### CODE REVIEW

**Comment by martenson** [comment]
nice catch

**Comment by hexylena** [comment]
:+1: would love to have this backported!

**Comment by jmchilton** [comment]
@erasche Wanna give it a try #5073? If y'all use it and it doesn't break things in 17.09 I may back port it further - this would seem to be a serious issue potentially.

**Comment by hexylena** [comment]
Absolutely! We'll test it out.

**Pull request merged**
