### PR TITLE
[15.05] Fix purging datasets whose total_size is None.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix the error:

```
Removing disk, file  /opt/galaxy/database/files/000/dataset_192.dat
Error attempting to purge data file:  /opt/galaxy/database/files/000/dataset_192.dat  error:  unsupported operand type(s) for -=: 'Decimal' and 'NoneType'
```

when running:

```
python scripts/cleanup_datasets/cleanup_datasets.py config/galaxy.ini -d 10 -3 -r
```

### CODE REVIEW

**Comment by dannon** [comment]
Thanks for the fix, and the tweaks @nsoranzo!

(well that's what I get for +1'ing before unit tests finish)

**Comment by nsoranzo** [comment]
@jmchilton: can you take a look at the failed unit tests? I have suggested https://gist.github.com/nsoranzo/69a3a41281b8ccf43569 as a possible fix, but @dannon thinks that the tests should be fixed instead using a (mock?) object store. What do you think?

**Comment by dannon** [comment]
Yeah, it doesn't seem correct to me to add that extra special logic to the model just so this test will pass -- in actual usage there will always be an object store in the mix.  It does seem like we should just enhance the mock dataset objects in the test framework.

**Comment by jmchilton** [comment]
https://github.com/nsoranzo/galaxy/pull/1

**Comment by jmchilton** [comment]
:+1: Thanks for the fix @nsoranzo

**Comment by dannon** [comment]
Yep, adding back my +1, @jmchilton's addition to the tests looks perfect.

**Comment by nsoranzo** [comment]
Thanks for the merge! I've merged the commits to `release_15.07` and `dev`.

**Pull request merged**
