### PR TITLE
[16.04] Merge 16.01 to 16.04

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by martenson** [comment]
wip, this needs one more commit

**Comment by martenson** [comment]
once this is merged the message box should work again in 16.04 @natefoo

**Comment by dannon** [comment]
Heh, 6 commits to change two lines ;)   LGTM though.

**Comment by dannon** [comment]
Additional benefit -- before this merge, the 16.04 build was out of date and this merge/rebuild fixes the webpack bundling as well.

**Comment by martenson** [comment]
commits are cheap :)

**Pull request merged**
