### PR TITLE
Rename tool_shed_get to url_get.

### PR DESCRIPTION
**Pull request by davebx**
And put it in lib/util.

### CODE REVIEW

**Comment by jmchilton** [comment]
My general feeling is that stuff requiring `app` should not be placed in `galaxy.util` - nothing that requires Galaxy's god object is generic utility IMO - it is deeply tied to Galaxy. There are exceptions like `biostar.py` that I'm not excited about but I don't think anything in `util/__init__.py` uses `app`.

The goal is also to use `six` for urllib stuff in util so it is Python 3 compatible - this code is not.

So I am -.5 on this as it sits, if there is a compelling reason to move URL handling code out of the tool shed's common util - I'd recommend keeping the common_util method as is but make it a lightweight wrapper around a more generic utility method.

```
def url_get( base_url, pathspec=None, params=None, password_manager=None ):
    """Make contact with the uri provided and return any contents."""
    # urllib2 auto-detects system proxies, when passed a Proxyhandler.
    # Refer: https://docs.python.org/2/howto/urllib2.html#proxies
    proxy = urllib2.ProxyHandler()
    urlopener = urllib2.build_opener( proxy )
    urllib2.install_opener( urlopener )
    if password_manager is not None:
         auth_handler = urllib2.HTTPBasicAuthHandler( password_mgr )
         urlopener.add_handler( auth_handler )
    full_url = url_join( base_url, pathspec=pathspec, params=params )
    response = urlopener.open( full_url )
    content = response.read()
    response.close()
    return content
```

I'm guessing this doesn't address you design goals - is there a reason you want to move code out of `lib/tool_shed/util/common_util.py` - if I understood that I could offer more specific advice on where to move this.

**Comment by davebx** [comment]
@jmchilton My primary motivation is reducing the amount of toolshed code that is in fact not specific to the toolshed, like I tried to do with XML handling the other month.

**Comment by davebx** [comment]
@jmchilton This rendition should be a lot more python3 compatible.

**Comment by jmchilton** [comment]
Thanks for making those changes, I feel more comfortable with the new design! :+1:

**Pull request merged**
