### PR TITLE
[16.04] Fix tag_autocomplete issue in workflow editor.

### LINKED ISSUE #2568: Tagging broken in workflow attributes editor
Responds w/ 500 on main when I try to tag.

### PR DESCRIPTION
**Pull request by dannon**
When we swapped to tag manager the signature changed and some of these were missed.

Should fix #2568

### CODE REVIEW

**Comment by dannon** [comment]
This resolves the back-end issue, but something else is broken causing the autocomplete tags (which are shipped to the client correctly now) to not actually get displayed.

**Comment by dannon** [comment]
Ok, after looking into it more, jquery-autocomplete fixing is going to be a much larger issue.  This fixes the server error which is actually disruptive, and is a reasonable bit to backport to 16.04.  I'm going to work on a more comprehensive (and scary to backport) autocomplete overhaul in dev.

**Comment by carlfeberhard** [comment]
+1

**Comment by carlfeberhard** [comment]
Is this similar to what you're seeing: #1079?

**Comment by dannon** [comment]
@carlfeberhard Didn't see an indexOf error, it was just silently failing after retrieving the autocomplete tag data from the server (once the patch in this PR is applied, of course -- prior to that it just explodes).

The autocomplete library we were using is deprecated and I was tinkering with using the standard jquery-ui autocomplete widget as a replacement, but it's going to be a little bit of work.

**Comment by dannon** [comment]
@carlfeberhard Yeah, just doublechecked.  I see the autocomplete request and response:

```
http://localhost:8080/tag/tag_autocomplete_data?item_id=fb85969571388350&item_class=StoredWorkflow&q=tag
```

```
#Header|Your Tags
tag2|tag2
tags|tags
```

And no errors.  (and no autocomplete selection popup, etc.)

**Comment by carlfeberhard** [comment]
Ok good: that's progress I'd think. I'll close the other.

**Comment by nsoranzo** [comment]
Wow, that was broken since 15.03!

**Pull request merged**
