### PR TITLE
Beacon integration

### PR DESCRIPTION
**Pull request by Paprikant**
This PR aims to support a simple way of supplying genetic variants to the beacon network - directly from the galaxy UI.

## Whats the beacon network
The [beacon network](https://beacon-network.org/) is a search engine for genetic variants developed by the [Global Alliance for Genomics and Health ](https://www.ga4gh.org/).
Variants are provided by a network of individual web services called [beacons](https://beacon-network.org/#/about).

These beacons can be queried for _specific variants_ (chromosome name, start position, reference genome name, reference sequence, alternate sequence) which have to be known to the query issuer. Upon such a query they will respond with "Yes" if the beacon knows of such a variant and "No" otherwise

## Why supply data from galaxy
Making variant data available over a beacon creates opportunities to be found and referenced by other researchers. Most importantly this is achieved **without publishing the actual data**, which removes a major hurdle for some data.

However, requiring researchers to maintain a web service and supply data directly to its database will stop most from participating. Hence the idea to make it available to all galaxy.eu users, directly from the platform they are already using

## What is changed

The actual beacon integration will be handled by a galaxy admin running a [python script](https://github.com/Paprikant/galaxy-beacon-import) which will build a beacon database from datasets shared by galaxy users.
The impact on galaxy is minimal by design. However, galaxy is getting some changes to provide some information and safeguard the datasets.

* A new user preference `beacon_enabled` is added. Data of a user will only ever be accessed after the user has manually enabled this preference (and therefore hopefully read the the associated texts)
* A vue component is added to the user settings, displaying a modal with further information and buttons to change beacon settings and switch to the associated histories
* A new admin preference is added, which enables or disables beacon sharing system wide

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by Paprikant** [comment]
image

**Review by davelopez — APPROVED** [review]
Thank you @Paprikant for updating the branch and fixing the conflicts.

The included API endpoints for managing the `Beacon` setting are considered experimental, at some point, there should be a single endpoint for managing all the user's settings and those will be replaced.

The test failures are unrelated.

**Comment by hexylena** [comment]
@bgruening @mira-miracoli y'all're deploying this, right? Do you have an ansible role for it / some commits where you deployed it that we could extract into a short training?

**Comment by bgruening** [comment]
Do you mean:

* https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/beacon.yml
* https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/beacon-import.yml

Please note, its Beacon v1.

**Comment by mira-miracoli** [comment]
I think generally it can run on the headnode, it was mainly a security measure.
Do you think we should move it from the cluster to bare metal?
My first idea would be to keep as much as possible separated from the headnodes, in order to have easier debugging and less error sources

**Comment by mira-miracoli** [comment]
I see a problem with postgres maybe, the [role](https://github.com/Paprikant/ansible-role-beacon) wants to run postgres in docker and uses port 5432 as default. The [importer-role](https://github.com/Paprikant/ansible-role-beacon_importer) seems to assume that the db is not on the same node.
the [importer-role](https://github.com/Paprikant/ansible-role-beacon_importer/blob/d4535923401596c2f600b303eb4586a4bbcfe043/tasks/main.yml#L10) which runs the import script on cron, wants to install Python 3.9, but that should be fine, I guess?

**Comment by hexylena** [comment]
We can also move this discussion https://github.com/galaxyproject/training-material/pull/3975

**Pull request merged**
