### PR TITLE
Kubernetes job runner

### PR DESCRIPTION
**Pull request by pcm32**
Introduces a first working version of a Kubernetes job runner, plus documentation for the runner in the job_conf.xml.sample_advanced. This runner requires a shared filesystem accesible by Galaxy and Kubernetes (details explained in the documentation). It relies on [pykube](https://github.com/kelproject/pykube) for communicating with the Kubernetes REST API, but since not all the required functionalities (pulled requests) have been approved there, this version relies on an unofficial fork of pykube. It requires a Kubernetes version that supports Jobs in the extensions API (tested with current version 1.2). The runner inherits from AsynchronousJobRunner.

Testing these changes requires a Kubernetes cluster to be accesible, shared filesystem and setting up persistent volumes and persistent volume claims in Kubernetes against this shared filesystem as explained in job_conf.xml.sample_advanced. Then galaxy tools need to be linked to the runner as explained in that same file (see destinations and tools parts). Docker container images for the tools that are linked need to be available at an accessible docker registry for Kubernetes to use them.

The contents of the PR have been tested against a Kubernetes cluster with simple jobs, but there might still be borderline cases to test. This PR addresses issue #1902 .

### CODE REVIEW

**Comment by jmchilton** [comment]
This is very exciting - the code quality is stunning for a first time contribution to the project I'm thoroughly impressed - thanks for the diligence and hard work. 

So my largest concern with the current state of it is important but hopefully you will agree with me that it is fairly superficial. I'd like to see the container reference handling synchronized with the rest of Galaxy's runners to whatever degree possible (and it seems like a high degree is possible). I can help work through the details of the implementation. Based on your work here - it looks like it should be possible to make the runner respect the the image specified in Galaxy tools and use them- right now the runner must specify the image instead of letting the tool use its own? I call what you are doing destination-specified containers - and what I would like is tool-specified containers to work also. The other runners support both.

For destination-centric container specification - it doesn't seem like the way you use `repo`, `owner`, `image`, and `tag` is very kubernates specific (you just concatenate them together) - so I'd prefer to have logic that is reused across runners.

So currently - the other runners support `docker_default_container_id` and `docker_default_container_id` - it seems like Kubernates could support these also in lieu of `repo`, `owner`, `image`, and `tag` and with similar semantics. If you like decomposing these ids - I think that is fine - but it'd be better to do it in such a way that the other runners would do this when "finding" docker identifiers. So maybe - convert these 4 kubernates specific parameters in 8 more general ones the other runners also respect: `docker_override_repo`, `docker_override_owner`, `docker_override_image`, and `docker_override_tag`, `docker_default_repo`, `docker_default_owner`, `docker_default_image`, and `docker_default_tag`. If the `docker_` prefix has outlived its usefulness - another such as `container_` would be fine also.

The difference between "override" and "default" parameters is defined in job_conf.xml.sample_advanced:

```
          <!-- If deployer wants to use docker for isolation, but does not
               trust tool's specified container - a destination wide override
               can be set. This will cause all jobs on this destination to use
               that docker image. -->
          <!-- <param id="docker_container_id_override">busybox:ubuntu-14.04</param> -->

          <!-- Likewise, if deployer wants to use docker for isolation and
               does trust tool's specified container - but also wants tool's not
               configured to run in a container the following option can provide
               a fallback. -->
          <!-- <param id="docker_default_container_id">busybox:ubuntu-14.04</param> -->
```

These concepts should apply equally well to Kubernates I believe? (Allow the deployer to specify a default for tools that don't specify a container - but use the tool's container when possible and if something about that container is problematic for the particular implementation or institute - allow an override).

**Comment by pcm32** [comment]
Thanks for your words @jmchilton and valuable feedback. Yes, you're right, there is no real need to make the separation I did for the parts of the docker image full name, so I'm happy to transition to something that makes more sense with the current treatment given in galaxy for containers. I'll look into this and probably request some further clarification as I dive into this.

Looking at my code I remembered why I wanted to make the separation of the elements of the docker image full name. We want to provide some instances of galaxy with predefined job_confs, and that entails changing the docker registries and containers versions in some cases. So I'll leave things separated and apply the idea of defaults/override that you suggest, plus the logic to use the tool defined container as well.

**Comment by jmchilton** [comment]
Just a follow up - I had very similar comments regarding condor work that also moves Docker resolution up to the runner level - https://github.com/galaxyproject/galaxy/pull/2278#issuecomment-219515333. My work with Galaxy abstractions for that PR can be found here - https://github.com/bgruening/galaxy/pull/10. That PR helps illustrate why setting these abstractions up in a slightly deeper part of the framework will allow innovations of this PR such as decomposing the Docker image identifier - to be reused instantly in other components of Galaxy.

**Comment by pcm32** [comment]
Hi @jmchilton, I'm sorry but I haven't had time to come back to this unfortunately. I intend to do today. However, I'm looking at your #2278, I see that you introduce this `find_container( job_wrapper )` method, which I cannot find implemented anywhere (nor could pycharm). I looked within the condor runner class and its parent classes as well (Async job runner and base runner), but couldn't find it. The only closest I found was a `_find_container( job_wrapper )` on base runner. Is this the method?

If I understand correctly, what you would like me to do is to use that `find_container( job_wrapper )` method to resolve the docker container that the k8s runner should use, adding to it the ability to understand both the single container name convention used by most galaxy runners and the fragmented container name that is introduced on this PR, using the defaults and override that you suggested. Correct?

**Comment by pcm32** [comment]
These new set of commits should address the proposal from @jmchilton regarding default and override modes for containers. This forces though a slight change in the idiom (docker_repo_default instead of docker_default_repo), but only for the case where the docker container id is produced out of its components, as it is proposed on this PR. Current implementation also can use docker containers defined by tools.

I'm seeing some errors/badly handled exceptions on some borderline cases, like manual (through kubectl) deletions of jobs in kubernetes (that are sent from galaxy), or trying to create jobs with ids that already exist. So this is probably not completely ready, but I wonder whether this kind of things should be depurated with more users testing this after being merged or not.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Is this out of "work in progress" state then?

**Comment by pcm32** [comment]
I was just updating my branch to be in sync with galaxyproject/dev. However, today I tried it again and a new error appeared, maybe there were some modifications to the internal galaxy container part in the meantime. But besides this, I would merge if you are happy. I'll come back and report ASAP so that you can merge.

**Pull request merged**
