### PR TITLE
[PROCEDURES] Allow veto overrides for extremely +1'ed PRs.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by blankenberg** [comment]
-1. This change prevents code modifications from being declined prior to merging.

**Comment by bgruening** [comment]
Oh please both stop that ... it makes me sad ...

**Comment by jmchilton** [comment]
@blankenberg Thanks for the justification and feedback. I am sure you are correct, but I don't read that in the language. Can you point to the specific language and describe your logic?

**Comment by carlfeberhard** [comment]
-1 (apparently this is serious)
Technical reason: it's a shitty idea
How about we use an established OS development methodology instead of making one up, Palpatine?

**Comment by blankenberg** [comment]
@jmchilton you literally deleted the block having to due with declining code-modification PRs. All other mentions of veto only relate to [PROCEDURES] PRs.

**Comment by jmchilton** [comment]
@blankenberg Thanks for the clarification - like I said I am sure you are correct.

**Comment by jmchilton** [comment]
@bgruening The optics of this look bad because of a beer fueled disagreement last night brought over into an unrelated repository. I assure you that this PR was absolutely not personal in anyway. This has been discussed many times and I explicitly promised to open a PR like this to another team member as the original organization PR was merged.

This is a completely sane and necessary change - I unfortunately don't think it will ever be merged - but we have given too many people (myself included) too much power. PRs like https://github.com/galaxyproject/galaxy/pull/1024 need a resolution, I really don't like seeing one team member closing another team member's PR - there should be a concrete resolution made as a team - this change would enforce that.

**Pull request closed without merging**
