### PR TITLE
fix data_column cast error when multiple is false

### PR DESCRIPTION
**Pull request by qiagu**
The issue was reported at:
https://github.com/bgruening/galaxytools/issues/753

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
Thanks @qiagu, this looks good to me. Could you perhaps add an additional test to https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/column_param.xml#L13 that tests a double-digit column?

**Review by jmchilton — APPROVED** [review]

**Comment by mvdbeek** [comment]
So I tried testing the fix with a test like https://github.com/mvdbeek/galaxy/commit/1e7d83bc3a9c7f60728cacac3198311a1179ba0d, but I can't make the test fail. @qiagu with which tool were you noticing the bug ?

**Comment by mvdbeek** [comment]
OK, so this only happens when you dump the input section into a configfile. @qiagu I have opened a PR with a test at https://github.com/qiagu/galaxy/pull/1, can you merge this please ?

**Comment by qiagu** [comment]
Cool! Thanks.

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by qiagu** [comment]
An enter/return sign makes the output file look nicer. 😄

**Comment by jgoecks** [comment]
+1 tested and works for me.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by qiagu** [comment]
😭 Remove the enter sign?

**Comment by qiagu** [comment]
Does the uncommon sign mean "no newline"?

**Comment by qiagu** [comment]
When applying `git diff` to the 'configfile.json' file, the result says "\ No newline at end of file".  Also, there is no '\n' at the end of the line in the following command test.
```
$ od -c test-data/configfile.json 
0000000    {   "   c   o   l   "   :       [   1   1   ]   }            
0000015
```
Therefore, I believe the uncommon sign just indicates no newline.
Actually, every other json file generated from configfile says '\ No newline at end of file'. The galaxy source code, to the best of my knowledge, doesn't support a newline output. It seems everything works as expected??
FYI, I found the following reference was helpful.
https://robots.thoughtbot.com/no-newline-at-end-of-file

**Comment by qiagu** [comment]
Another thought. Let galaxy output a newline?

**Comment by jmchilton** [comment]
@galaxybot test this

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Looks good to me.

**Comment by dannon** [comment]
@qiagu Were you trying to make sure there was, or was not, a newline at the end of configfile.json?

**Comment by qiagu** [comment]
@dannon If you click the `Files changed` tab, you may notice there is an uncommon sign at the end of the configfile.json file. I was trying to identify what the sign means. My research guided me to "no newline". I think everything works fine here, unless you want a newline, like most text files do.

**Comment by dannon** [comment]
@qiagu Cool -- Yeah, I see that, and it looks like that was how it was originally added by Marius -- I just wanted to make sure of your intentions here.  Thanks, this looks good to me!

**Comment by qiagu** [comment]
@dannon Thank you for merging!

**Pull request merged**
