### PR TITLE
Data managers - allow removal of entries

### PR DESCRIPTION
**Pull request by selten**
Implements the request from https://github.com/galaxyproject/galaxy/issues/8223

This adds an easy optional change to a data manager to remove data as well. It is fully backwards compatible with the data manager format that was used.
It uses features that the API also uses (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/tool_data.py#L52) to delete entries in a data table. 

It also migrates data managers documentation from https://galaxyproject.org/admin/tools/data-managers/ to https://docs.galaxyproject.org/en/master/.

This change adds a bit more flexibility to data managers where they get the ability to e.g. remove data from a data table that is invalid or might have expired.

### CODE REVIEW

**Comment by jmchilton** [comment]
We already have an API endpoint that does this - so I see no issue with this. I also like having the documentation moved here. @blankenberg I'll give you a couple days to comment, but if I haven't heard from you then I'm going to merge.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by selten** [comment]
Could anyone maybe help me clarify why the `test.api.test_datasets.DatasetsApiTestCase.test_show` from `api test python 3` and the `test.integration.test_upload_configuration_options.AdminsCanPasteFilePathsTestCase.test_admin_path_paste_libraries` from `integration test` would fail?   
    
The odd part is that this only failed `api test python 3` and not `api test` as well as `integration test` and not for `integration test python 3`.

**Comment by jmchilton** [comment]
Probably transient failures - I wouldn't worry about these.

**Comment by jmchilton** [comment]
Awesome - thanks so much!

**Pull request merged**
