### PR TITLE
bump bcftools requirement in set metadata tool

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref https://github.com/bioconda/bioconda-recipes/pull/28871

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Do we need to bump the tool version? And, in such case, duplicate the file?

**Comment by mvdbeek** [comment]
I'd say bumping the tool version is a good idea, but duplicating seems unnecessary, since I don't think the user interface offers a way to run the older tool.

**Comment by bernt-matthias** [comment]
> I'd say bumping the tool version is a good idea, 

Done

> but duplicating seems unnecessary, since I don't think the user interface offers a way to run the older tool.

I guess so -- in particular for such non-standard / non-userfacing tools. Was wondering these days if having a "tool history" is possible for builtin tools.

**Comment by bernt-matthias** [comment]
Also wondering if I'm right that there is already test coverage.

**Comment by mvdbeek** [comment]
> I guess so -- in particular for such non-standard / non-userfacing tools. Was wondering these days if having a "tool history" is possible for builtin tools.

If you copy the tools and reference them again in the tool_conf.xml file, that's the only way we can do this right now.

> Also wondering if I'm right that there is already test coverage.

I don't think so, the only use of bcftools is in https://github.com/mvdbeek/galaxy/blob/867cae13af251a95ea2a059a58bb777388ed7173/lib/galaxy/datatypes/tabular.py#L766
... and this is some magic method that runs with tasks / parallelism tag in tools. I don't think we necessarily need coverage via tool framework tests. Maybe you could do a unit test for the merge method, or just manually check that the command line used there still works.

**Comment by bernt-matthias** [comment]
OK. Then lets break the tool and see if a test fails :)

**Comment by bernt-matthias** [comment]
Not sure if the failing integration test is du to breaking the set metadata tool...?

**Comment by jmchilton** [comment]
```
test/integration/test_cli_runners.py::ParamikoCliTorqueIntegrationTestCase::test_running_cli_job
```

My guess is that it is not related. Can you just rebase to make sure - also can you rev the tool wrapper version to ``1.0.3``. There is no reason to my mind this tool should be bound to the version of bcftools - that tool represents only a small fraction of what this tool does.

**Comment by bernt-matthias** [comment]
> My guess is that it is not related.

Which means that we do not have test coverage for the tool (note the `exit 1` at the end of the command section)? Seems bad, or?

**Comment by mvdbeek** [comment]
> Which means that we do not have test coverage for the tool (note the `exit 1` at the end of the command section)? Seems bad, or?

Not really, the tool itself is used everytime a job is run, right ? As long as it produces the metadata files we know it works. That's why `exit 1` doesn't do anything. If you replace the command line everything would break. `<command detect_errors="exit_code"` is just there to make sure we don't fail if we get a deprecation warning via the stderr.
 
We could parse out the exit code, stdout, sterr etc of the set metadata tool as well, but that seems like overkill.

I think we can remove bcftools. The `merge` method in the datatype is only ever used in the task splitting framework, which does not run via the metadata tool. The splitter runs in the main galaxy process, so that won't use dependencies at all.

**Comment by bernt-matthias** [comment]
Superseded by https://github.com/galaxyproject/galaxy/pull/12472

**Pull request closed without merging**
