### PR TITLE
Install missing tool when workflow upload from web.

### PR DESCRIPTION
**Pull request by manabuishii**
Install missing tool when workflow upload from web

Add Install missing tool button on web (default: false)

Currently this is work if user is admin.

Message is needed to update.

### CODE REVIEW

**Comment by manabuishii** [comment]
GUI looks like this.

screen shot 2017-06-09 at 6 16 53 pm

**Comment by martenson** [comment]
This is a variation of https://github.com/galaxyproject/galaxy/pull/3064 - could you please close that one given this supersedes it?

The problem with this approach is that when admins are installing tools they are presented with options for each repository like what dependency resolution to use for deps installation (Tool Shed vs Conda vs None), what section to install the tool to, and others.

The proposed way of installing tools in this PR _ignores all those decisions and provides no choices in that regard_.

A minor thing is that the option also needs to be shown only when you are an admin.

**Comment by jmchilton** [comment]
> The proposed way of installing tools in this PR ignores all those decisions and provides no choices in that regard.

That is totally fine right? We are now hiding those options by default in the GUI even. Yeah - it would be better if this provided some of the options, and a break down of the repositories, etc... but as a starting point I think this would be fine.

Unfortunately the UI shows up regardless of if the importer is an admin or not - that would need to be resolved IMO. Given that I merged the API PR with some changes and this page has been replaced with a JavaScript client this will need to be redone I think. So @manabuishii I'm going to close this out - I hope that is okay. If this is still important - I'd encourage you to redo it but using the JavaScript version of this form added recently.

**Comment by martenson** [comment]
@jmchilton we are not hiding e.g. section selection

**Pull request closed without merging**
