### PR TITLE
Galaxy Tours - Grouping tours for viewing clarity

### PR DESCRIPTION
**Pull request by selten**
These changes allow a large amount of galaxy tours to be shown in a clear way. Compared to the current list. The current list isn't that clear if you have over 10 tours. By grouping them, this clarity is greatly improved and the usability of galaxy tours for end users is vastly improved.

The implementation adds 2 extra parameter to each tour, namely group and group_name. 'group' is the identifier for the group. 'group_name' is the name that is used for displaying the group. This implementation groups the tours and displays them as groups.

The changes can be tested by going to the interactive tours and seeing that they are grouped. A `<ul>` in the group `<li>`.

### CODE REVIEW

**Comment by bgruening** [comment]
@selten this is awesome. Does this mean that you are using tours heavily? :)
Have you considered to use simple `tags` as in other parts of Galaxy. The UI could then try to group the tags or offer a filter for the tags, like in workflows etc...

**Comment by dannon** [comment]
@bgruening I was thinking the same thing.  I'd love to see some sort of 'domain tags' or the like, and have the tours UI automatically generate these groups.

**Comment by selten** [comment]
I haven't considered using tags because I never developed for the galaxy core. That could be a great change though. I'll look into this later. Thank you for the advice.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@selten I really like where this is headed.  Let me know if you want any help with the tag implementation.  Instead of 'group' and 'group_name', I'm thinking we could just have a single list at the top level of the tour like:

```
...
tour_id: my_workflow
tags:
    - Beginner
    - Workflows
...
```

Tags like this would keep it simple, yet flexible, and would require less coordination across the community on naming I think.

Edit: One other benefit would be that we wouldn't be changing the API response quite as dramatically, either.  I doubt this is a heavily consumed API (currently), but this is something to keep in mind.  In this implementation `api/tours` is changed to actually provide a list of groups, which doesn't seem correct to me.  I think I'd like to see the tags approach, with this endpoint providing a list of tours as expected, just with the additional tags field.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@selten Thanks, I'll check this out today!

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@galaxybot test this

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
@selten Thanks for this, it's a great start towards better tour organization!

**Pull request merged**
