### PR TITLE
Library data and FTP file parameter

### PR DESCRIPTION
**Pull request by guerler**
This PR adds/fixes the library dataset and FTP file tool parameter by adding a new UI input element for lists. The input element can be separately used e.g. for ftp files. It also adds list handling abilities to the default tool parameter wrapper and removes the individual library dataset wrapper. This should help to reduce the number of individual wrappers in the future. Additionally, the PR fixes the section expansion to properly highlight errors in the tool form.

### CODE REVIEW

**Comment by bgruening** [comment]
Hi Sam,

this is really nice! One quick question: Why is this a new `<param>`, can we make it a new button next to the other 3 buttons of a `type=data` tag?

**Comment by guerler** [comment]
Great question. Well first of all the library dataset parameter was a separate input parameter in the old tool form which displayed a modal for the selection of library datasets (it broke someday in the past though). Here we reimplement this parameter (in a basic fashion) for the new form so that we can confidently remove the former tool form. Now to your question. This parameter populates the options from the library api in a significantly different way than regular datasets are populated in a data selector from the history. The validation of values is also distinct. Combining the two tool parameters would introduce significant complexity to the data selector which is why it is probably better to keep them separated. Another similar tool parameter is the ftp file selector which will be easy to cover with most of this PR. Again it makes sense to keep the ftp file selector separate from the regular data selector. However, another reasonable alternative for tool developers is to require users to import datasets first, either from the library or the ftp source, and then in fact use the regular dataset selector.

**Comment by bgruening** [comment]
With complexity you mean on the architecture side? I would argue from the user and tool developer side. 
- A user wants to access the data and there is (usually) one data input field. Why should there be two or three just because the data is technically stored in different backends? For most of the users it's already hard to grasp why the extra step of importing data to a history is needed.
- What is our advise to a tool developer with this new parameter? I don't know beforehand where the data is stored. Do I need to define now all input param's in a conditional (choose: FTP, Library or History)? If we introduce this we need to be really explicit about the usage pattern behind it. Currently, as a tool developer I would not use it, simply to not clutter the user interface.

Sam, is the dataset copied to the history before execution?

**Comment by guerler** [comment]
Yes, it makes sense. However integrating the library selection feature into the data selector is an independent step which would follow this PR. Merging both into one tool parameter would increase the complexity without returning benefits. Here, the goal is to fix the library data selector i.e. backward compatibility. Making a card for your suggestion is very reasonable though. In either case we would have to make sure that the currently available, explicitly defined library_data tool parameter is functional. Currently the dataset is not copied to the history before execution. Should this be changed?

**Comment by bgruening** [comment]
Since it will be only linked to a history and not physically copied, I would vote for it. This makes a "history" more complete.

**Comment by guerler** [comment]
Sounds reasonable. I have added a card in order to keep track of the bullet points. https://trello.com/c/Wu9zDdXX/2640-additions-to-the-library-data-and-ftp-file-tool-parameters.

Its noteworthy that the suggested additions might require to revise the buttons (which are currently shown in the dataset selector), since the number of buttons can quickly grow.

**Comment by jmchilton** [comment]
It was multiple=True by default before - since the implementation is being guided by a desire to preserve backward compatibility shouldn't that be the default? Also is the command block still going to get a list if `multiple="False"`?

**Comment by jmchilton** [comment]
@bgruening Yes - I would not encourage tool developers to use this at all unless there is a compelling use case for particular institution (special data libraries for instance). We can fix this parameter out of some perverse sense that nothing should ever break even if we have no evidence people are using it - but it shouldn't dictate best practices.

@guerler About the buttons - I really think we need to continue to have room to grow - maybe a default form with no buttons and then an advanced mode or something. There are so many important an interesting things to do with data during an analysis that we still cannot do - things more more fundamental than importing data from libraries (though that is also a good use case).

**Comment by jmchilton** [comment]
I think this breaks uploads:

```
galaxy.jobs.runners ERROR 2015-04-20 09:31:18,710 (134) Failure preparing job
Traceback (most recent call last):
  File "/home/john/workspace/galaxy/lib/galaxy/jobs/runners/__init__.py", line 161, in prepare_job
    job_wrapper.prepare()
  File "/home/john/workspace/galaxy/lib/galaxy/jobs/__init__.py", line 852, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 91, in set_compute_environment
    input_paths=compute_environment.input_paths()
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 117, in build_param_dict
    self.__populate_wrappers(param_dict, input_dataset_paths)
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 237, in __populate_wrappers
    self.__walk_inputs( self.tool.inputs, param_dict, wrap_input )
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 150, in __walk_inputs
    do_walk( inputs, input_values )
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 148, in do_walk
    func( input_values, input )
  File "/home/john/workspace/galaxy/lib/galaxy/tools/evaluation.py", line 231, in wrap_input
    input, input_values[ input.name ], param_dict )
  File "/home/john/workspace/galaxy/lib/galaxy/tools/wrappers.py", line 67, in __init__
    self.to_param_dict_string = self.input.to_param_dict_string( self.value, other_values )
AttributeError: 'UploadDataset' object has no attribute 'to_param_dict_string'
```

**Comment by guerler** [comment]
Thx for catching that John and thanks for the comments Bjoern. So:
1. I noticed that wrappers are sometimes imported from galaxy.tools.wrapper and sometimes from galaxy.tools. This is arbitrary particularly since they are not used within galaxy.tools. Assuming that I caught all such locations, the wrappers are now consistently imported from galaxy.tools.wrappers.
2. The command block is getting a list only for multiple=True otherwise a single value is parsed. The initial default value for multiple was false: https://github.com/galaxyproject/galaxy/commit/84e2e155b34743bc4e920d83965686a0256956d5.
3. The call we make here for the library data tool parameter will also apply to the ftpfile tool parameter. So we would in fact either fix or strip two user exposed features.
4. We do not have a consensus yet on how to properly deprecate features which have been exposed to the users for years and are depicted in the wiki but not regarded as particularly useful anymore. See also the discussion here: https://github.com/galaxyproject/galaxy/pull/35. I agree that, wherever possible, we should not expose features and then leave them broken or strip them from the code without proper replacement. I would not call that perverse (: Particularly in this case, since adding the suggested new feature i.e. allow the selection of libraries from the regular dataset selector, would require the same modules. Either way we have to reach a consensus since this discussion holds us back from moving forward with the ongoing tool form integration i.e. stripping the old tool form.

Having said this, I agree that users who are not using this features right now should probably wait until we utilize these modules directly from the regular dataset selector. The discussion on how to arrange buttons etc. is not related to this fix though. I think we are mixing up the desire for a new feature with the aversion against an already existing, user exposed feature. Our options are not to either integrate it as separate parameter or within the regular dataset selector, but to either fix these tool parameters or to deprecate them.

**Comment by jmchilton** [comment]
WRT https://github.com/galaxyproject/galaxy/commit/84e2e155b34743bc4e920d83965686a0256956d5 ... a few weeks later it was changed so that the value is a list by default right? https://github.com/galaxyproject/galaxy/commit/e065c5abba4a2d479aab054b63f97a7514131e49

`multiple="False"` is a better default though - happy to stick with that - since again we have no uses cases, test cases, or spec to "fix" backward compatibility relative too.

The example tool should be updated to reflect this though because this test is now failing:

```
./run_tests.sh -with_framework_test_tools -api test/api/test_tools.py:ToolsTestCase.test_library_data_param
```

**Comment by blankenberg** [comment]
FWIIW, we did have at least one tool running on main that used the Library input parameters. It was used to upload files from libraries, and parse out info from the library info templates on the datasets, as part of mouse Encode.

From a copy I still have laying around, here is the parameter of note:
`<param name="library_datasets" type="library_data" label="Library Datasets" />`

It does rely on multiple="True" as the default behavior.

Edit: So we do have a use case, that we can fall back on, as it was live on main for a while and used in a production capacity for a major project.

**Comment by guerler** [comment]
Interesting. What is the tools name? IMHO it is better to adjust this tool now since the change is minor and would align this parameter with e.g. the dataset or collection selector and others.

**Comment by blankenberg** [comment]
I'll have to check what the tool's id was, but I don't think it is has been running since the switch to TACC.

The point, however, is that if there is one tool using it, there may be more using it, that we don't know about, so "fixing them all" isn't a realistic solution.

**Comment by jmchilton** [comment]
Awesome - thanks for the test case fixes @guerler.

:+1:

**Comment by Public-Health-Bioinformatics** [comment]
Hi folks - I (Damion) just noticed this thread via dev-list feedback (thanks, Aysam).  Our use case for a (multiple) library dataset selector widget:  The tool we developed here in the last year is a Blast reporting tool which augments the list of result hits with a lookup by accession id to one or more local reference databases.  The reference databases are simply fasta accession ids + titles, manually curated.  I have them integrated via .loc file and galaxy data table config.  But its a bit of a hassle to get them in place that way, when all we'd really need is for a Galaxy admin to upload the given reference db files into a data library (nice since it includes versioning somewhat), and enable the tool user to select any of them from there (ideally just a given library folder).  I don't need this to be the old <param type="library_data"> tag since we haven't implemented this yet.  I do need to get back a path to each dataset for use by our tool.

I'll check out what you've done this week I hope, Aysam.

Cheers!

**Comment by jmchilton** [comment]
@guerler I hadn't noticed that you had updated this with @blankenberg's last suggestion - I am very sorry about that. You may help to comment on PRs after making requested updates to get everyone's attention. Is this ready to go then - want me to merge this (not that you have to wait for me or anyone obviously)?

**Comment by guerler** [comment]
No worries, but yes, I think this is ready by now.

**Comment by guerler** [comment]
No worries, but yes, this should be good to go.

**Comment by Public-Health-Bioinformatics** [comment]
First, thanks very much for working on this.  It fits nicely in my reporting tool.  I think there may be a few issues with this <param type="library_data" ...> tag code.  Where should I report them?  I'm on 46a4ef8850b5+ (stable) 
- looking at a tool's history dataset "view details", it isn't reporting the path or id of selected library dataset:
  screen shot 2015-06-25 at 5 18 01 pm
- If there are several datasets in a library, the one sent into galaxy isn't the one selected on menu. This might be in context of a repeat section, I haven't tested outside of one.
- Trying to rerun a tool that has this tag in it causes error:
  ...
  File '/usr/local/galaxy/production1/galaxy-dist/lib/galaxy/tools/parameters/basic.py', line 162 in value_to_basic
  return self.to_string( value, app )
  File '/usr/local/galaxy/production1/galaxy-dist/lib/galaxy/tools/parameters/basic.py', line 2401 in to_string
  return [ldda.id for ldda in value]
  AttributeError: 'int' object has no attribute 'id'
  screen shot 2015-06-25 at 5 17 06 pm

FYI, snap of this field in action in tool:
screen shot 2015-06-25 at 5 17 30 pm

**Comment by guerler** [comment]
The screenshot and the ldda.id error indicates that your instance is at a commit before this PR. See also:
https://github.com/galaxyproject/galaxy/pull/132/files#diff-9baf995401cfeb779edf8731ebaf0d2dL2386

**Comment by Public-Health-Bioinformatics** [comment]
Ah.  I've been pulling galaxy-dist from bitbucket.  Should I be pulling galaxy-central from there, or do I have to convert my install to the github repository?  I thought I was past release_15.05 . But maybe this hg repo somehow doesn't include your code?

My branch etc.

[galaxy@grl-salk galaxy-dist]$ hg branches
default                    17125:e837a68e8d14
release_15.03              17115:a9d766325bd8
release_15.01              17097:8586ba87fdfe
release_14.10              17096:9eaf8d97dfef
release_14.08              17095:74f9d06223e4
stable                     17124:46a4ef8850b5 (inactive)
release_15.05              17123:b7c2f4457ace (inactive)

hg branch
default                    17125:e837a68e8d14

I tried stable branch too.  But still same form presented, and same apparent bugs.

Thanks for your help,

Damion

Hsiao lab, BC Public Health Microbiology & Reference Laboratory, BC Centre for Disease Control
655 West 12th Avenue, Vancouver, British Columbia, V5Z 4R4 Canada

**Comment by martenson** [comment]
@Public-Health-Bioinformatics The code is getting propagated from GH to the bitbucket but expect considerable delays. Switching to git(hub) as a remote is a better solution.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, thanks folks.  I'll do the switch - I was just afraid of getting in trouble with some file differences. I presume its just a matter of copying old hg site config files into new git cloned site (our galaxy data folder is outside the galaxy-dist folder of course).

**Comment by martenson** [comment]
I added a "how to" that should work to the following wiki page(bottom): https://wiki.galaxyproject.org/Develop/SourceCode

**Comment by Public-Health-Bioinformatics** [comment]
ok, nice.  I've updated my galaxy to git according to the instructions.  Now I'm on the latest github dev I think and I can see the form control has changed.  But there's still oddness.  
I can see it is still showing a deleted library.  One of the two "Versioned Data" libraries is actually deleted.
screen shot 2015-06-26 at 5 42 13 pm

Clicking on rerun doesn't error as it did before, so that is good.

**Comment by Public-Health-Bioinformatics** [comment]
In my use, in a repeat block, it looks like selection of correct dataset is failing - a different dataset id is returned - it might be occurring in case where a dataset has several versions.  I just selected a new Euzby 16S dataset, but I got back the old version.  It looks like after selecting a dataset, rerunning the tool, it can't remember the selection correctly.  In snapshot below, returned dataset, highlighted, is not the one selected. It is an archive of a different dataset in the list.

screen shot 2015-06-26 at 6 43 00 pm
Also, perhaps connected, the "view details" link is still showing oddly, above.

The code:
screen shot 2015-06-26 at 6 47 40 pm

**Comment by Public-Health-Bioinformatics** [comment]
Any update on the issue that the right dataset is not being selected from the library?  (May be happening in context of a dataset having multiple versions in library, or if deleted data libraries are being listed incorrectly).
Regards,
Damion

**Comment by martenson** [comment]
this PR should fix the bug with deleted libraries being shown: https://github.com/galaxyproject/galaxy/pull/546

**Pull request merged**
