### PR TITLE
[18.05] Fix size handling in legacy modal view

### LINKED ISSUE #6352: When there are too many issues in a workflow you cannot click continue
auswahl_039

- I could zoom out but this is sub-optimal.
- Yes I know this should never happen.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #6352

### CODE REVIEW

**Comment by martenson** [comment]
I think changing the modal default height is potentially problematic since various places display it for various purposes and this would affect all of them.

**Comment by dannon** [comment]
Agreed dropping it to 50% window height is probably more than some modal-using interfaces are going to handle correctly right now.  Fixing it correctly to use the calculations as intended, though (as in the first changeset, if I read it correctly), will fix existing modals that run off the screen and we should do that.

**Comment by guerler** [comment]
Its not changing the default height. This PR exposes the existing maximum height handling which limits the modal size by the window height. I set the max to 67% of the window height because its more robust and the existing calculation is flawed i.e. the modal footer overlaps with the window bottom. This legacy modal is only used in pages, the workflow editor and sweepster. I checked the use cases and the modals look fine.

**Comment by dannon** [comment]
@guerler Maybe I missed a rebase?  I could swear it was cutting it down more than that.  In any event, if you've tested all the locations that's okay with me.

**Comment by guerler** [comment]
Oh I upped it to 67% after you raised concerns regarding 50%. (: Thanks for the review.

**Comment by dannon** [comment]
@guerler Ok, whew, I'm not going crazy.  Yet.  Sure, anytime man!

**Review by jmchilton — APPROVED** [review]
Tested out various collection modals and they looked fine.

**Comment by dannon** [comment]
Sorry, I forgot to explicitly +1 yesterday.  This looks good to me.

**Comment by dannon** [comment]
I'm going to merge #6364, and will rebuild the client during that, which will incorporate these changes.

**Pull request merged**
