### PR TITLE
Test if parameter present in value to avoid index error.

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes issue #862

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Is it best if that index is left out of rval entirely, or should it be `None`?   That is, something like the following.

```
rval[ input.name ] = input.value_to_basic( value.get(input.name, None), app )
```

(I just don't know the behavior for resetting to a default parameter off the top of my head)

**Comment by mvdbeek** [comment]
Ah, don't merge yet, please.

**Comment by dannon** [comment]
(oops -- pending changes?)  Now that I look at it more closely, I'm not sure how value_to_basic will handle `None` (whether `None` should go to value_to_basic, or be plugged straight into rval directly)

**Comment by mvdbeek** [comment]
@dannon it seems that leaving out the rval gives me a nice error message when editing the workflow.
Setting the parameter value to None does not do that.
Also, there is a mistake in my last commit, but I would like to revert to the first commit.
You're OK with that?

**Comment by dannon** [comment]
@mvdbeek Sure, that sounds good to me.

**Comment by dannon** [comment]
Thanks for the fix, and for taking the time to look into that with me @mvdbeek!

**Comment by mvdbeek** [comment]
Sure, my pleasure.

**Pull request merged**
