### PR TITLE
Move config_manage out of webapps/ into config/

### PR DESCRIPTION
**Pull request by jdavcs**
ping @jmchilton

### CODE REVIEW

**Comment by jdavcs** [comment]
what's the most appropriate area label for this? Should we add area/config to labels?

**Comment by nsoranzo** [comment]
> what's the most appropriate area label for this? Should we add area/config to labels?

@ic4f I've tagged it with the `area/packaging` label.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jdavcs** [comment]
@jmchilton can this be merged? (all tests pass; selenium timed out, but passed previously). It's not critical: I'm working on config processing (config_manage.py at the moment), and the code assumes that config_manage.py is located in config/. If this is merged, I will be able to test new commits on Jenkins. But it can wait.

**Comment by jdavcs** [comment]
thank you!

**Pull request merged**
