### PR TITLE
[16.10] Fix workflow parameter handling

### LINKED ISSUE #3307: Workflow: Post action fail on rename dataset with variable
Testing out the current release branch 16.10 and looks like a regression where you cannot do a post action of renaming a dataset with a variable + extra text. So it WILL work if all you have is a variable i.e ${work}. BUT if you have any text with it, it seems to chop one  beginning and end characters from the name.

So if your rename datasets looks like this : http://imgur.com/JZPNL1F in workflow editor. 

When you attempt to run it as a workflow, it will look like this : http://imgur.com/IEEdt3K
After running it, it looks like the original input found in the workflow editor.

Current on branch release_16.10 on commit 2c833499b130aca72ab78d112692f2a9f0d4d9e6

### PR DESCRIPTION
**Pull request by guerler**
Fixes #3307. Thanks @dannon.

### CODE REVIEW

**Comment by Takadonet** [comment]
Thanks.  Will test Monday morning

**Comment by guerler** [comment]
Awesome. Thank you.

**Comment by Takadonet** [comment]
Works well!

Thanks

**Comment by jmchilton** [comment]
:+1: The failing linting test case is due to the out of band procedures on the security fix. This will be fixed in a separate PR and shouldn't delay this fix.

**Comment by Takadonet** [comment]
Perfect.

**Pull request merged**
