### PR TITLE
[WIP] Reports API routes

### PR DESCRIPTION
**Pull request by hexylena**
People were doing so well with tool dev and docker, that I didn't actually need to be helpful. In the few hours I've started some work on a reports API with plans for a nice and shiny reports SPA that uses said API.

Right now I'm just translating routes and standardising APIs in a way that feels more useful for the future.

The nice feature will be seriously decreasing the size of the reports app to essentially just SA queries. E.g. controllers/jobs.py (1128 lines) decreases to api/jobs.py (219 lines). The original "X_per_year" and "X_per_month" have been refactored into much smaller and more modular filters. The architecture isn't great, but I'm enjoying myself and that's what matters _to me_ ;)

### CODE REVIEW

**Comment by martenson** [comment]
love for reports! HYPE 🎉

**Comment by hexylena** [comment]
Frontend is living here for now. https://github.com/erasche/galaxy-reports



General TODO List:
- [ ] charts
- [ ] heavy caching of values for more informative pages (and maybe even pre-caching)
- [ ] decide on some new view/re-org of existing views
  - some of this is "built in". Given that we have jobs per day resolution and an API that essentially defaults to "zooming" capabilities, we can already collapse into just a couple of views, "jobs", "users", "workflows".
  - that said, there are surely other useful plots to add.
- [ ] Figure out how to integrate a react-js frontend app that will _require_ compilation for running (and I'm strongly against compiled artefacts in repo)

**Comment by ericenns** [comment]
Looking forward to this!

**Comment by bgruening** [comment]
When more workshops means that @erasche will produce more cool features we should give more workshops ;)

**Comment by hexylena** [comment]
Killing this. EU gets all the data we really need from scripts to export data to grafana and some command line tools. No intention to deploy the reports webapp now or in the future.

**Pull request closed without merging**
