### PR TITLE
[23.1] Add missing archived filter in saved histories

### LINKED ISSUE #16469: Archived histories are not listed under User -> Histories
We should list them at least in the advanced search:

Screenshot 2023-07-26 at 20 36 06

so status: could include "active | deleted | archived | all".

`all` should probably also include archived histories, with the `Status` column stating that the history is archived.

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #16469

https://github.com/galaxyproject/galaxy/assets/46503462/91a72c45-c2c6-4d22-a239-18689c69c302

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  - Have some archived histories
  - Go to User -> Histories
  - Use the advanced filters
  - The archived histories should be listed when listing all histories

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hmm, the selenium tests do look related, I'll restart them.

**Comment by davelopez** [comment]
Yep, there is something about he change that selenium doesn't like. I'll investigate...

**Comment by davelopez** [comment]
I changed the filtering keys to support not just the deleted status and I needed to adapt the selenium tests accordingly. I think it should be fine now.

**Comment by mvdbeek** [comment]
Awesome, thank you!

**Pull request merged**
