### PR TITLE
remove logging during tool load to make logs more readable

### PR DESCRIPTION
**Pull request by martenson**
now when the toolbox reloads hot I feel this is convoluting the Galaxy's logs and not bringing enough value

@mvdbeek @natefoo

### CODE REVIEW

**Comment by mvdbeek** [comment]
👍 the part that I am interested in as an admin is when loading the tool has failed, not when it has been loaded successfully ... this I can see more easily from the admin panel. I can't really think of a situation where I look into the log to confirm a tool has been loaded. Perhaps for hidden tools this may be interesting?

**Comment by mvdbeek** [comment]
Also note the variable number of `.`, based on the tool status. Which admin would even notice this??? ;)

**Comment by martenson** [comment]
haha, I did not even notice it and I made this PR :D

**Comment by blankenberg** [comment]
I'm not for this. I like to see the tools that are loading and the order, etc. This is log level debug, and I think quite appropriate to include. If you want less verbose logging, you should change your log level.

**Comment by martenson** [comment]
@blankenberg This is my experience from Main and Test and I want the level to be DEBUG to see all other things but this is just too much. During multi-tool-installation (when you really want to watch the logs) it will reload the toolbox multiple times and each time spitting ~400+ lines into the log making it close to impossible to actually watch the log without some fancy terminal filtering. Changing my log level does not address the situation.

edit: when was the last time your tool did not load and you learned from the log?

**Comment by blankenberg** [comment]
I think the fix in that case it to not reload the entire toolbox, just the new/modified tools, right?

**Comment by dannon** [comment]
Another idea here might be that the other stuff that's getting lost in the DEBUG chatter, if it's more important, should be bumped up to INFO or some other log level.

**Comment by martenson** [comment]
@dannon the other stuff is imo `debug` and these tool logs are imo `spam` - I am however looking into the toolbox reload handling as @blankenberg suggested

**Comment by dannon** [comment]
What's the saying, "one man's spam is another man's debug"  I dunno.  Something like that :)

(in any event, I do totally agree and think the plan always was to reload just the tools that _need_ to be reloaded -- the entire toolbox reload was a temporary improvement)

**Comment by martenson** [comment]
@dannon with the caching the toolbox reload takes ~1s on Test (and probably similar on Main). As I understand it the full-reload approach was chosen as good-enough abstraction level that is easy to implement and fast enough to not care about details.

**Comment by dannon** [comment]
@martenson Interesting, that's fast, way faster than I expected!  Not so bad.  In that case, I agree, the specific reload isn't really a high priority.

**Comment by dannon** [comment]
One followup question -- how often are these tools actually reloading such that it's obscuring important messages?  I didn't expect this to happen much.

**Comment by martenson** [comment]
> During multi-tool-installation (when you really want to watch the logs) it will reload the toolbox multiple times

So every time you install/update a tool.

**Comment by natefoo** [comment]
FWIW I have used this output before to see if a tool is loading. I am not saying that it's explicitly necessary to have this output but in the worst case scenario, a tool you are expecting to load would _silently_ not load, and you wouldn't really have a way to check whether Galaxy even attempted it. If it fails to load due to syntax errors that's one thing and would be logged (at a lower-than-debug level even) but if it doesn't load because you forgot to put it in `tool_conf.xml` or put it in the wrong tool conf (perhaps one that's not being loaded) or because of a bug in Galaxy, losing this output could make it more difficult to troubleshoot.

A bigger problem may be that too many useful messages are debug level, and so it's pretty much never useful to run a Galaxy server at a lower log level. If that was not the case then it'd be no big deal for these to be in the debug level. This should be fixed but it's a biiiiig undertaking.

**Comment by blankenberg** [comment]
Also, re the conversation about reloading the whole toolbox being 'easier/safer' than just reloading targeted tools: https://github.com/galaxyproject/galaxy/issues/2988

**Comment by martenson** [comment]
The implementation is fresh so it has bugs - I do not think that is a fair
point Dan.

**Pull request closed without merging**
