### PR TITLE
Properly handle multiple hidden datasets when populating data select options

### LINKED ISSUE #3823: Tool Rerun Partially Broken on 17.01 with Hidden Datasets
At the top, a hidden dataset gets selected correctly when jbrowse has failed and is being re-run. But at the bottom you see "Annotations from Apollo" instead of the dataset that was actually selected / configured for that step. I have to unhide all of the datasets in my history (losing my nice cleanup that I did so users only see the important things) in order to re-run this tool successfully.

utvalg_101

cc @guerler. (Blurred for focus, not security)

### PR DESCRIPTION
**Pull request by guerler**
Fixes #3823.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Shouldn't this be target at release_17.01 ?

**Comment by guerler** [comment]
Its a minor issue existing for awhile now and this fix would lead to merge conflicts due to recent tagging additions for the data selector. My plan was to fix it in dev first and then carry it backwards if necessary, but if you think its better I can target 17.01 first.

**Comment by nsoranzo** [comment]
@guerler It is surely fine this way, especially if the backported fix is going to be different. I just wanted to double check, because merging forward is usually easier and does not require a second pull request.

Regarding if the backport is necessary at all, I'll defer to the original bug reporter @erasche.

**Review by nsoranzo — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thanks @guerler, I had been very worried when I saw that happening initially.

**Comment by mvdbeek** [comment]
@guerler This was ready for review, right? Hope I didn't merge too early.

**Comment by guerler** [comment]
Yeah, you are good. Thanks.

**Pull request merged**
