### PR TITLE
Update common_startup_functions.sh

### PR DESCRIPTION
**Pull request by nagoue**
Not to override tool_shed config file.

### CODE REVIEW

**Comment by martenson** [comment]
@nagoue could you please describe in a bit more depth what are you fixing here?

**Comment by nsoranzo** [comment]
Code originally introduced in commit 09feaf6f4d46509c7401970013b5a8097a5d4c4e

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nagoue** [comment]
Hi,

I encountered a problem when starting running a local toolshed on our server with a specified IP instead of the localhost name. The fact is that our tool_shed.yml config file was not considered. Previously in the code:
l151: arg_getter_args returned the correct value
l152:  arg_getter_args returned default value crushing the previous one

I am currently using Galaxy 18.01.

**Review by nsoranzo — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
@nsoranzo Nate is out this week I think, so I'm just going to merge it. I think it makes a lot of sense. Thanks so much for the contribution @nagoue!

**Comment by martenson** [comment]
@nagoue I see. Thanks for the fix!

**Pull request merged**
