### PR TITLE
CDATA and linting

### PR DESCRIPTION
**Pull request by hexylena**
- I went ahead and removed useless whitespace from some of the other display applications.
- also replaced any tabs with appropriate numbers of spaces.
- However, this PR is majorly/specifically for these files: https://github.com/galaxyproject/galaxy/compare/galaxyproject:dev...erasche:xml-cdata?expand=1#diff-a0c45413fc1a094b9464a173b573eca7L29

which I complained about on a previous PR https://github.com/galaxyproject/galaxy/pull/70#discussion_r27682208 cc @blankenberg

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by blankenberg** [comment]
I enjoy the visual separation of logical blocks provided by empty lines, so I am -0 on that, but +1 overall.

**Comment by martenson** [comment]
I am with @blankenberg here, I consider the empty lines very useful for reading and providing logical separation.
I am against style changes like the empty lines removal, especially when it introduces styleguide that we do not even recognize at https://wiki.galaxyproject.org/Develop/BestPractices

**Comment by hexylena** [comment]
@martenson noted, I'll leave them in there in the future. Not my personal preference, but I don't especially hate them.

**Comment by martenson** [comment]
Thank you @erasche

**Pull request merged**
