### PR TITLE
[WIP] Hide collection contents by default.

### PR DESCRIPTION
**Pull request by jmchilton**
Branched off a rebase of #4584, attempting to start to implement some of the ideas in #4735 - haven't gotten to the job counts yet or the CollectionJobSet piece but if there are mapping failures there will at least be a red collection for that now.

Pre-building mapped over collections instead of building them at the end with all the jobs and outputs in memory should allow fixing of #1790 and should allow more intuitive state tracking to enable #3883. Should fix some other problems also that I'm not sure have issues yet.

### CODE REVIEW

**Comment by jmchilton** [comment]
Converging toward something ready to be used - I pushed an update that piggy backs cleaning up of history monitoring to also clean up collection state monitoring. Without this I had a problem where new states would be monitored but old state monitoring calls wouldn't go away. As part of this I learned that in multi-history view no state monitoring seems to occur - so dataset states don't change. I guess this is fine in general - but it doesn't mean that since the first state update doesn't happen for implicit collections - they are forever stuck in the gray in-determinate state in that view. This isn't a regression really - but it would probably be worth it to fetch a single state update to get an more correct initial guess about the collection state in that view.

So today I'm going to revise this PR to:

- [x] Do that single fetch for new collections.
- [x] Configurable batching of collection state requests - to reduce the number of API connections needed. (The current state is such that fewer joins happen on the backend - since individual datasets aren't fetched - but more API requests are made). Batching will let me improve the scaling in both metrics I think. I'd also like to do things like fetch the collection state for bigger collections less often for instance.

Hopefully by early tomorrow I can open a new PR with all of this in a ready state.

**Comment by jmchilton** [comment]
Done with https://github.com/galaxyproject/galaxy/pull/4763/commits/f6e41cf254618d3233f86e502b40f03d5d969714 and https://github.com/galaxyproject/galaxy/pull/4763/commits/e3c5b4f8b2bd93cffc08f2f11c00f738f69af88f. I'll open a new PR out of WIP after I clean up the commits through some rebasing either tonight or tomorrow morning.

**Comment by martenson** [comment]
I might have introduced conflicts in https://github.com/galaxyproject/galaxy/pull/4998 but they seem to be resolvable.

**Comment by jmchilton** [comment]
Superseded by #5013.

**Pull request closed without merging**
