### PR TITLE
[18.01] Various fixes for the run scripts

### PR DESCRIPTION
**Pull request by nsoranzo**
- Fix the regression introduced in https://github.com/galaxyproject/galaxy/pull/6239 where the plain `./run.sh` started writing to the log file instead of the standard output (console).
- Check for empty pid file when executing `GALAXY_RUN_ALL=1 ./run.sh --daemon|restart --wait`
- Look for config file inside `galaxy.dependencies.optional()`
- Use consistent preference order for config files

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
Nice work, fixed the restart section too. :smile:

**Comment by nsoranzo** [comment]
Ready for review!

**Review by lparsons — APPROVED** [review]
Looks good, consolidates more of the config file logic. Unfortunately, the logic of these startup scripts has become fairly complicated and opaque, so it's hard to know if this works in all scenarios, but this PR fixes some broken things and reduces duplication, which is good. Nice job @nsoranzo.

**Review by jmchilton — APPROVED** [review]

**Review by natefoo — APPROVED** [review]

**Comment by natefoo** [comment]
Thanks @nsoranzo, this was sorely needed!

**Comment by nsoranzo** [comment]
Thanks @lparsons @jmchilton @natefoo for the reviews! I've merged this forward.

**Comment by lparsons** [comment]
@nsoranzo Hmmm... Seem to have run into a problem:
I now get `IOError: [Errno 2] No such file or directory: '/galaxy/galaxy-app/"/galaxy/galaxy-app/config/galaxy.ini"' `

Looks like some parent directory is getting prepended twice somewhere....

**Comment by nsoranzo** [comment]
@lparsons Can you share how you launch Galaxy and some log/output lines before the error?

**Comment by lparsons** [comment]
Sure, start with:
`GALAXY_RUN_ALL=1 ./run.sh start`

Log output (there are no lines before the error):
```
Traceback (most recent call last):
  File "./scripts/paster.py", line 27, in <module>
    serve.run()
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 1055, in run
    invoke(command, command_name, options, args[1:])
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 1061, in invoke
    exit_code = runner.run(args)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 226, in run
    result = self.command()
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 640, in command
    server = loadserver(server_spec, name=server_name, relative_to=base, global_conf=vars)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 301, in loadserver
    return loadobj(SERVER, uri, name=name, **kw)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 318, in loadobj
    global_conf=global_conf)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 343, in loadcontext
    global_conf=global_conf)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 364, in _loadconfig
    loader = ConfigLoader(path)
  File "/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 443, in __init__
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '/galaxy/galaxy-app/"/galaxy/galaxy-app/config/galaxy.ini"'
Removing PID file web0.pid
```

**Comment by nsoranzo** [comment]
Mmh, that works for me on 18.01 when using galaxy.yml or no config file, but I can reproduce when using galaxy.ini, I'm investigating now.

**Comment by nsoranzo** [comment]
@lparsons That should be fixed by:
```diff
diff --git a/run.sh b/run.sh
index 0210375..08e6627 100755
--- a/run.sh
+++ b/run.sh
@@ -64,7 +64,7 @@ if [ "$run_server" = "python" -a -n "$GALAXY_RUN_ALL" ]; then
     fi
     for server in $servers; do
         echo "Executing: python $server_args --server-name=\"$server\" --pid-file=\"$server.pid\" --log-file=\"$server.log\""
-        python $server_args --server-name="$server" --pid-file="$server.pid" --log-file="$server.log"
+        eval python $server_args --server-name="$server" --pid-file="$server.pid" --log-file="$server.log"
         if [ -n "$wait_arg_set" -a -n "$daemon_or_restart_arg_set" ]; then
             while true; do
                 sleep 1
```

**Comment by lparsons** [comment]
Yup, that seems to do the trick. Thanks again @nsoranzo!

**Pull request merged**
