### PR TITLE
Add Theme support

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
The goal of this PR is to simplify color theming galaxy instances. It adds a themes.yml config file, in which several themes can be specified. These themes are not meant to replace scss theming, but provide a simple alternative for changing the basic look of an instance, without having to modify client files.

In the current iteration only the masthead can be themed, but this system can be built upon to include more colors in the future.

If only one theme is specified, it will act as the default. If several themes are specified, users can switch between them using a theme selector in the masthead. Selected themes persist on the client.

image
*themes.yml.sample applied*

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by guerler** [comment]
Very cool, here is a list of suggestions:
1) Run `make config-rebuild` in the root directory, to update associated config files
2) Rename the option to `theme_config_file` and the actual yml to `theme_conf.yml` to align it with other configuration files.
3) The default config option is `null`, I'd suggest to augment the comment of the config option, indicating that an unused yml example file is available in the config samples directory.
4) Minor, but I'd change the background of the `pride` theme to another color, maybe something slightly lighter, I think that would work better with that theme.

Thank you so much for providing this feature, I think its amazing. Love it.

**Comment by dannon** [comment]
This looks nice.  I'm even more excited about this building into a dark mode eventually :)

The one comment I have is that the current theme isn't something I'd expect to find as a toplevel dropdown in the masthead -- I think it should probably be in preferences.

**Comment by guerler** [comment]
@dannon it only appears in the top-level dropdown if admins provide multiple options.

**Review by guerler — APPROVED** [review]
Looks good to me.

**Comment by dannon** [comment]
> @dannon, @ElectronicBlueberry implemented in such a way that it only appears as a top-level dropdown if admins provide multiple themes.

I know, I think it should be in preferences.  This is a preference that someone will occasionally set and then leave alone, not something that they will click in daily use of Galaxy like the other stuff in the masthead

**Comment by guerler** [comment]
Ah I see, yeah that is true, I think we can move it around in the future and place it elsewhere. I agree.

**Pull request merged**
