### PR TITLE
[17.05] fix image proxy prefix in tool form

### PR DESCRIPTION
**Pull request by martenson**
This fixes https://github.com/galaxyproject/galaxy/issues/4490

The proxy prefix has never been added to the URLs of images in repositories, this adds the prefix dynamically at render time. 
Alternatively I think this could be fixed at the point when this image url is being generated on the backend.

Given that most tools do not have images in help, and those who have have usually one or two this shouldn't slow down things.

I also believe this is a more [robust](https://github.com/galaxyproject/galaxy/issues/4490#issuecomment-353073633) fix since it solves precisely the bug reported and can hardly have any side effects.

### CODE REVIEW

**Comment by dannon** [comment]
> Given that most tools do not have images in help, and those who have have usually one or two this shouldn't slow down things.

This runs an extra underscore _.each loop on the results of a jquery-find on the toolform help template regardless of whether there are images or not every time we build a tool form for display, or rerender.  All so we can put a bandaid on a backbone bug that is fixed, correctly, in the other PRs in question.  If we decide to use tool help elsewhere, we'll have to apply a similar bandaid there, as well.  Lastly, when we swap to a correctly functioning router library, we'll have to remember to take this bandaid *back out*.

The correct fix also has the benefit of always constructing correct URLs, across the board, for uniform behavior *everywhere*, so we won't see this same class of bug in other places.  If we *do* want that applied to 17.05, I'll backport it, but I think this bandaid is a bad idea.

**Comment by jmchilton** [comment]
Thanks @martenson. I'm more comfortable with this fix than with forking bootstrap. Any chance we can restrict this to just URLs that contain ``admin_toolshed``? External absolute URLs and deployment-local relative URLs should work IMO and look like they might be broken by this? If I'm wrong and they do not work currently - I'm +1 on this as is.

**Comment by dannon** [comment]
It's not bootstrap, it's backbone, and it's a 2 line tweak to url handling in a dead project that we're phasing out, not a massive fork that we'll need to maintain.  Buying into wrangling our own URLs here, instead of fixing them across the board, is a bad idea for the exact types of bugs that @jmchilton has pointed out above.

If you two are going to shove this through even though I spent all the time actually debugging and fixing the problem, please at least use jquery selection result's .each().  There's no need to throw two javascript libraries at this.

**Comment by jmchilton** [comment]
Responding to a comment from private chat:

> Nobody *yet* has explained why a minor patch to the library is bad, or pointed out anything it will harm.

@dannon I generally prefer reuse of existing libraries instead using forked ones - even on JS side. I have a clear record on this I think - I preferred the citations rendered with the previous library but I didn't hold back your changes because I admitted it might be worth it to use the more popular, standard library on balance (https://github.com/galaxyproject/galaxy/pull/4978#issuecomment-346054983). To me this situation is pretty analogous.

Update: Spelling fix.

**Comment by dannon** [comment]
Edit: This is a waste of my time; ya'll do what you're going to do.  I'm going to move on and fix more things.

**Comment by jmchilton** [comment]
> The citations rendered with the previous library were forked, and I changed that to use unmodified libraries explicitly so we did not have to fork them, could install from npm, and just use them.

Exactly - I thought there was enough value in using unmodified upstream libraries I allowed this change even though I thought the rendered citations were degraded. In weighing things - I agreed with you at the time that it was better to not fork if all else is equal.

**Comment by dannon** [comment]
@jmchilton I said I'm moving on, do what you want to do.  I don't get a vote here, and I'm tired of wasting so much time arguing with you two constantly.

Also, copying messages from an intentionally private chat and posting them in public?  Classy.

**Comment by martenson** [comment]
the travis (macOS) fails are unrelated

**Comment by natefoo** [comment]
I'm not sure why going with the more performant fix is a bad idea here when both are hacks to some extent, if backbone is really dead and being phased out. If we were keeping it, or it was installed at runtime and not shipped, then hacking it would be a much worse idea. And I think we all agree that hacking external libraries with changes that won't be accepted upstream should not be done without good reason.

I spoke privately with multiple people involved in this and I think there was a general feeling about a lack of public awareness or discussion of future direction, and frustration over the rapid breakdown of discussion. I've disagreed with all of you before on various principles and I think we all want things done properly, with the project's future in mind. So, I hate to see things devolve this way and over a relatively minor technical issue. Cooler heads can prevail.

Concerning this fix, since @dannon has moved on and this is a working solution, I think we should merge this.

**Comment by dannon** [comment]
Just to be clear, they are both working solutions.  We're just apparently split as a team on what the better one is.  I still contend my approach is the right one, and that this is a worse approach, but in the interest of moving on as mentioned above I'm just going to merge this now.  I'm rewriting it all using a new router anyway.

**Pull request merged**
