### PR TITLE
Fix commas that shouldn't be in biotools_mappings.tsv

### LINKED ISSUE #18903: biotools_mappings.tsv includes comma and space separated values leading to incorrect bio.tools IDs.
**Describe the bug**

E.g. this is incorrect, that's not a valid bio.tools ID, instead it's two added together with a space.
https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/iuc/abstracts_by_pmids/abstracts_by_pmids/0.0.2

These all come from https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/ontologies/biotools_mappings.tsv 

You can ctrl-f for ` `  and `, ` to find other values that aren't ideal.

**Expected behavior**

The parser should perhaps be updated so that when it encounters a space separated value, that it emits multiple bio.tools stanzas rather than a single one with an invalid ID. (and probably that file needs validation/linting of some sort)

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes https://github.com/galaxyproject/galaxy/issues/18903

## How to test the changes?
(Select all options that apply)
- [x] Instructions for manual testing are as follows:
  1. I don't know - check the file for commas after the commit I guess 😅 

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
I guess these are coming from an upstream source https://github.com/bio-tools/content if i can believe galaxy.yml.sample ? That repo doesn't exist anymore though, so ... :shipit: ?

**Comment by hexylena** [comment]
@mvdbeek https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/bio-tools/content at least they warned us 😆 

> IMPORTANT : this repo is a sandbox: do not use it for production purposes!  It's entire contents may change, be reorganised or even deleted without notice.

@jmchilton you might also be missing the ones with spaces? e.g. L263 rxlr_motifs. And in that case i would argue both biotools xrefs are relevant. do we need to pick one? is there a way to have both annotations?

**Comment by bgruening** [comment]
> I guess these are coming from an upstream source https://github.com/bio-tools/content if i can believe galaxy.yml.sample ? That repo doesn't exist anymore though, so ... :shipit: ?

Its redirecting to https://github.com/research-software-ecosystem/content ... is the redirect not working for you?

**Comment by hexylena** [comment]
https://github.com/galaxyproject/galaxy/pull/18919/files#diff-fd14abe36b9effe9869962313d1b668af331e9cd4234faa4a08bab8115eed210L135 last one, I think (`sam_merge2` is on two lines, the first "broken link in toolshed", the second looks more correct.)

**Comment by jmchilton** [comment]
>  I think (sam_merge2 is on two lines, the first "broken link in toolshed", the second looks more correct.)

It looks like it already had an entry - so I think we're fine to just delete it.

**Review by hexylena — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @jmchilton

**Pull request merged**
