### PR TITLE
[15.10] Fix change handler association

### LINKED ISSUE #1356: Upload interaction fails after clicking Reset
- Click upload
- Choose a local file
- Click Reset (accidentally...its right next to the start button)
- Click upload local file again and reselect the same file, click Open --> Upload box is not populated.

Have to reload the Galaxy interface in your browser (not just upload) in order to upload the desired file.

release_15.10 and dev are tested as affected (probably farther back as well)

### PR DESCRIPTION
**Pull request by guerler**
Should fix #1356. I am working on enhancements regarding #1088, and duplicate entries in general, in a PR against dev.

### CODE REVIEW

**Comment by martenson** [comment]
:+1:

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
15.10 tests will not pass yet, don't worry about them, sorry @guerler

**Comment by guerler** [comment]
Ok.

**Pull request merged**
