### PR TITLE
Handle sections in view workflow

### LINKED ISSUE #1723: Tools with sections fail during "View workflow"
Filing this officially since I mentioned it in chat once and forgot to file properly.

```
  return render_row_for_param(context,param,value,other_values,prefix,step)
File '/galaxy/database/compiled_templates/workflow/display.mako.py', line 233 in render_row_for_param
  __M_writer(filters.html_escape(unicode(param.get_label() )))
AttributeError: 'Section' object has no attribute 'get_label'
```

Galaxy throws up an internal server error when trying to view workflows which use tools which have sections.

### PR DESCRIPTION
**Pull request by hexylena**
Fixes #1723

ping @guerler.

Corrected title due to opening against wrong branch, also see #1916 

selection_641

### CODE REVIEW

**Comment by guerler** [comment]
:+1:

**Comment by guerler** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@erasche I think we can just close this in favour of #1916, and then merge forward?

**Comment by hexylena** [comment]
@nsoranzo sure, that's fine.

**Pull request closed without merging**
