### PR TITLE
Fix tool recommendation node injection

### LINKED ISSUE #10095: Toolboxes of recommended tools not opening in workflow editor
Toolboxes of recommended tools do not open in the workflow editor after clicking on the recommended tools in the popover. This issue is present in the [dev branch](https://github.com/galaxyproject/galaxy/tree/dev). The currently deployed codebase `release_20.05` on the EU server does not have this issue.

Screenshot from 2020-08-12 18-07-35

### PR DESCRIPTION
**Pull request by dannon**
Fixes https://github.com/galaxyproject/galaxy/issues/10095

### CODE REVIEW

**Comment by bgruening** [comment]
@anuprulez maybe you can convince @OlegZharkov to add a test for this functionality :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @dannon!

**Comment by OlegZharkov** [comment]
I probably can, it would be good if @anuprulez can you show me how to enable/use it

**Comment by anuprulez** [comment]
@OlegZharkov thanks. To enable tool recommendation feature, please set `enable_tool_recommendations: true` in Galaxy config `galaxy.yml.sample`. Once set, tool recommendations can be seen when a tool is executed or in the workflow editor by clicking on the `right arrow` icon on a toolbox.

**Pull request merged**
