### PR TITLE
Use tox testing for TravisCI.

### PR DESCRIPTION
**Pull request by jmchilton**
[There are still problems with the setup - but I wanted to gauge reaction to the move before getting to far.]

Tox is used by Bioblend, Pulsar, and Planemo and provides several benefits over the current setup:
- More flexibility than baking logic directly into .travis.yml.
- Makes the CI testing more portable.
- Generally leads to more parallelism on Travis.
- "prettier" display of results (things are broken down by the kind of test).

For the last two points - compare https://travis-ci.org/galaxyproject/galaxy and https://travis-ci.org/galaxyproject/planemo.

I would like to add the qunit tests to Travis and I see this a good first step toward being able to do that well.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Awesome!

Only 1 question: does it make sense to have both py27-lint and py26-lint ?

**Comment by jmchilton** [comment]
Hmm... py26-lint I believe will catch instances of invalid Python 2.6 syntax (I use this trick to force Python 3.4 syntax in planemo for instance). Is there anything that is invalid Python 2.6 syntax but is fine Python 2.7 (e.g. comprehensions over dicts?) I am not sure - if not that might not ever catch anything.

**Comment by jmchilton** [comment]
Yeah - it does look like some of the 2.7 changes would probably be invalid syntax in 2.6 (https://docs.python.org/2/whatsnew/2.7.html#python-3-1-features)  - set literals for instance.

**Comment by nsoranzo** [comment]
Sorry, didn't know that flake8 is so cool! I will apply something similar to BioBlend.

:+1:

**Comment by jmchilton** [comment]
So for those not on IRC - tox randomizes the [PYTHONHASHSEED](https://testrun.org/tox/latest/example/basic.html#special-handling-of-pythonhashseed) and this has uncovered some bugs in Galaxy and in tests - I pushed out some fixes to this PR branch and I think there is still one more to track down (just waiting for the right seed again :)).

**Comment by jmchilton** [comment]
It also appears our current setup was testing Python 2.6 unit tests with Python 2.7 (maybe we were using Python 2.7's virtualenv and that setup Python as Python 2.7 implicitly?)- working on unit testing fixes for Python 2.6 using `unittest2` (also used in Pulsar and Planemo).

**Comment by jmchilton** [comment]
Ping @carlfeberhard - I tried to fix the Carl-style unit tests for Python 2.6 in a dry fashion by importing a [unittest2](https://pypi.python.org/pypi/unittest2) in `utility.py` as `unittest` if on Python 2.6 and switching all `TestCase` references to use that. Please let me know if you dislike this approach.

**Comment by jmchilton** [comment]
Given that this actually turned into a collection of bug fix commits are there any objections to me closing this out and just targeting `release_15.05` instead?

**Comment by dannon** [comment]
+1 to the suggestion to retarget.

**Comment by jmchilton** [comment]
Okay - will do - the rebase is messier than I had hoped but I'll try to reopen something post-lunch.

**Comment by carlfeberhard** [comment]
@jmchilton looks great to me. Thanks for doing those fixes.

**Pull request closed without merging**
