### PR TITLE
BIOM1 Datatype enhancements

### PR DESCRIPTION
**Pull request by blankenberg**
I am not yet sure that we should store table_rows and table_columns, as these could grow quite large, but could be useful in tools.

### CODE REVIEW

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/tools-iuc/issues/299

**Comment by IyadKandalaft** [comment]
@blankenberg With respect to your comment about storing OTU table metadata, I already ran into problems with storing row/column metadata from OTU tables based on the Mothur OTU datatype.  This was mostly due to SQLAlchemy not allocating the correct column type in MySQL compared to PostgreSQL.  

Yet, OTU tables that have 384 samples with 5000 OTUs are a likely possibility.  I would opt to parse some basic info about the matrices rather than re-capture data as-is from within the file into Galaxy's metadata store.  E.g. just the column IDs and the row IDS vs the entire json.

**Comment by blankenberg** [comment]
@IyadKandalaft thanks for the feedback! I've updated the PR to only store the ids for the rows and columns.

Any additional comments or concerns are greatly appreciated.

**Comment by bgruening** [comment]
@IyadKandalaft @lparsons does this look good to you?

**Pull request merged**
