### PR TITLE
Implement test data resolver for online test data

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref: https://github.com/galaxyproject/galaxy/issues/7900 https://github.com/galaxyproject/galaxy/issues/3714

With this PR it is possible to **specify one or more test data resolvers** for tool tests.
In addition to the local file and git resolvers I **added a resolver of online test data**.

Syntax is currently:

```
<tests>
   <test_data_resolver value="http://www.zenodo.org/..." checksum="sha256$2bec523db6dfa6e97a54d0ecc539023c910b349b72c14cf618485b256a529868"/>
   ...
</tests>
```

multiple resolvers are also possible

```
<tests>
   <test_data_resolver value="http://www.zenodo.org/..." checksum="sha256$2bec523db6dfa6e97a54d0ecc539023c910b349b72c14cf618485b256a529868"/>
   <test_data_resolver value="test-data"/>
   ...
</tests>
```

The current state is that I did one successful test with one of the IUC tools
where I removed the `test-data` directory and used an online zip file.

I guess some tests would be good. If someone has an suggestion how tests
might be implemented best and where (functional tool test / unit test / ...).
I did not touch yet all branches of `stage_data_async`, but only those
necessary to make the planemo test succeed. All the possibilities to get test
data (just local files, test data download via API, etc are still confusing
to me).

Nevertheless the current state should be good to gather some first feedback.

TODOs:

- [ ] add to xsd
- [ ] currently checksum is not enforced, but probbaly it should be?
- [ ] should we restrict to https?
- [ ] add linting for test_data_resolver
- [x] remove debug code 
- [ ] implement test_data_resolver for yaml tools
- [ ] solve TODOs 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
Is there a reason not to just allow URLs in the expected output definitions instead? This seems like an odd level of indirection  in the code and for the end user?

**Comment by bernt-matthias** [comment]
> Is there a reason not to just allow URLs in the expected output definitions instead? This seems like an odd level of indirection in the code and for the end user?

This seems also to be a good idea, in particular if it's only one or many large in/output files. Maybe it would be more convenient to allow to set a prefix URL (essentially like the git resolver) then we have less copy paste (of the URL prefix) in the in and output values.

My use case (which I should have mentioned earlier) is a tool suite (OpenMS) with hundreds of (mostly auto-generated) tests and several hundred mega bytes (>700MB in >3000 files) of test data. So my aim is to have all of this in a online "repo". And of course this online test data needs to be versioned. 

Clearly you have a point if its a good idea to have this monolithic (as single zip file) or as separate files.

- pro monolitic:
  - faster download ... I guess that the separate download of 3000 files would be much slower
  - specifying checksums is more convenient (for manually created tests)
- pro single files:
  - assuming that only a small fraction of the test data changes from version to version it seems like a waste of space to have a single zip.

So maybe the core question (in particular for my use case) is: if there is an online system that allows convenient versioning of single files. I was always thinking of zenodo, but maybe git is even better. We just need to extend the git test data resolver to allow to specify a branch (would be cool anyway to have galaxy-test-data versioned xref: https://github.com/galaxyproject/galaxy-test-data/pull/20#issuecomment-1044865801).

One problem with git is that git repos can be deleted (and my assumption is that this is impossible for zenodo since they have DOIs).

So thanks for the input @jmchilton .. made me think about goals of online test data resolvers:

- persistence (maybe only allow URLs to dx.doi.org)
- versioned (zenodo / git / ... ?)
- fast download (not sure if possible with zenodo if files are stored separately)
- ...

Looking forward to more input :)

**Comment by jmchilton** [comment]
> Maybe it would be more convenient to allow to set a prefix URL (essentially like the git resolver) then we have less copy paste (of the URL prefix) in the in and output values.

We have macros for this right? Also even if you wanted to specify a prefix, I still think URLs are the way to go. 

```
<tests prefix_test_data="http://www.zenodo.org/..." >
   ...
</tests>
```

This downloading a big repository just seems backwards to me. There are a bunch of things we can do to optimize - including caching and hashing the datasets that would make things better in every situation - not just this narrow one where you want to have a zip or repository of data.

I implemented the git data resolver and I think it is an unfortunate hack - it was just something we did to reduce the size of the repository as we switched from hg to git. It don't think it is worth generalizing the idea. On github or zenodo you can just create URLs to specific versioned datasets right? I think that is the best thing to do - at least until we start hitting issues with it.

Also I think it is already implemented now that I think about it - https://github.com/galaxyproject/planemo/blob/master/tests/data/wf11-remote.gxwf-test.yml#L11. Maybe that isn't exposed in the tool XML but the code knows how to do I think.

**Comment by bernt-matthias** [comment]
> Maybe that isn't exposed in the tool XML but the code knows how to do I think.

@jmchilton do you know where the download functionality for workflows is implemented?

**Comment by bernt-matthias** [comment]
Maybe one more argument that may favor a solution like the one suggested here: 

There is test data that is not specified explicitly in the tool tests, ie data that is referred by data table (which is often particularly large). 

> This downloading a big repository just seems backwards to me.

Any arguments for this? Just want to understand. 

I just see that all files are needed anyway in the end, so why not just download them at once?

> There are a bunch of things we can do to optimize - including caching and hashing the datasets that would make things better in every situation - not just this narrow one where you want to have a zip or repository of data.

Actually access should be cached already. But to me it appears that the main application here seems to be tool (and workflow tests). The Galaxy instances used there are temporary and therefore caching seems to be of little use anyway.

**Comment by bgruening** [comment]
I would like to pitch this project a bit: https://github.com/bgruening/test-data-registry

The idea is to have a test data registry external to Galaxy, that can be used by Snakemake and Nextflow as well.

I also included a `unpack` attribute like here https://github.com/bgruening/test-data-registry/blob/main/registry/fasta.yaml#L10 with the same idea as @bernt-matthias in mind I think. For some tools, a tarball might be better, especially for indices etc...

However, this test data registry needs a PR similar to this here to be handled by Galaxy. So maybe we can create a test data resolver" for the test-data-registry project?

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/galaxy/pull/15510

**Pull request closed without merging**
