### PR TITLE
[STABLE] Fix database deadlocks when running large workflows.

### PR DESCRIPTION
**Pull request by jmchilton**
This fix was first tested and initially verified by Marius van den Beek with subsequent parallel verification from Philip Mabon and Aaron Petkau. Many thanks to all three of them and Franklin Bristow for all the help.

Likely these deadlocks were introduced in 14.10 when I added an update time to workflow invocations so we can re-evaluate them over time - an explanation for why the deadlocks are likely occuring can be found in the code comments.

### CODE REVIEW

**Comment by martenson** [comment]
Do you plan on backporting this?

**Comment by jmchilton** [comment]
My understanding is that the current policy is only to backport serious security fixes - so I don't plan on backporting this. If the consensus is I should though I would be happy to.

**Comment by martenson** [comment]
I am currently working on backporting data lib import bug that we introduced during the security fixes all the way to 14.10. Just wanted to make sure we won't cause each other trouble  when doing this.

**Comment by martenson** [comment]
:+1: 
thank you all for tracing this one down!

**Comment by natefoo** [comment]
+1

I believe it's at the discretion of the submitter as to how far they'd like to backport anything other than critical security fixes, although I don't think we defined that formally anywhere.

**Comment by dannon** [comment]
+1

**Pull request merged**
