### PR TITLE
refactors tag manager to use only what it needs…

### PR DESCRIPTION
**Pull request by bwlang**
an sql_alchemy session, not the full app.
This makes it possible to use the tag manager from
the model.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by bwlang** [comment]
@galaxybot test this

**Comment by bwlang** [comment]
looks like a transient failure... (Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out)
does galaxybot listen to me?
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
Well, you should get automatic tests. Any idea why Jenkins is not automatically testing some PRs @martenson?

**Comment by bwlang** [comment]
I think that failure is probably not interesting... some deb mirror is not responding... 
It passed before.
Anything needed before it can be merged?

**Comment by dannon** [comment]
@bwlang After the fix to the toolshed tag manager, this looks great to me.  Thanks!

**Pull request merged**
