### PR TITLE
[19.01] Bugfix: "Run workflow" jumps when clicked

### PR DESCRIPTION
**Pull request by sveinugu**
Fixes a small style annoyance that causes the "Run workflow" button to jump when clicked.

@dannon?

Run workflow button jump

### CODE REVIEW

**Comment by sveinugu** [comment]
@galaxybot test this

**Comment by sveinugu** [comment]
I don't know why the test fails:
```
E       AssertionError: assert None == 'Current on-disk tool is not valid'
E        +  where None = <galaxy.tools.Tool object at 0x7facff0c4d10>.tool_errors
```

**Comment by mvdbeek** [comment]
That's unrelated, this test fails occasionally. We made it more robust on the dev branch.

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by martenson** [comment]
the fix seems good, but I suggest we place it in the workflow stylesheet, not in javascript

**Comment by dannon** [comment]
@sveinugu Thanks for this, it does fix the problem.  @martenson's suggestion is good, too, and I've pushed another change incorporating that.  Thanks again @sveinugu!

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by sveinugu** [comment]
@dannon Looks good to me. I don't know how your process works, but seems to me that this PR can now be merged?

**Review by martenson — APPROVED** [review]

**Pull request merged**
