### PR TITLE
Fix casper tests

### PR DESCRIPTION
**Pull request by davebx**
Ping @carlfeberhard because reasons.

### CODE REVIEW

**Comment by martenson** [comment]
runs on jenkins at https://jenkins.galaxyproject.org/job/docker-casperjs/164/console

**Comment by martenson** [comment]
failed due to possible phantomjs RangeError issue: https://github.com/ariya/phantomjs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+RangeError

now runs at https://jenkins.galaxyproject.org/job/docker-casperjs/165/console

**Comment by carlfeberhard** [comment]
+1 looks fine to me and programmed _to_ the framework: Nice job.

**Comment by martenson** [comment]
This fixes 14 casperjs tests. Thanks a lot @davebx !
https://jenkins.galaxyproject.org/job/docker-casperjs/166/testReport/

**Comment by jmchilton** [comment]
We should backport these to 16.01. Anyone mind if I open a PR?

**Comment by martenson** [comment]
go ahead @jmchilton

**Pull request merged**
