### PR TITLE
[19.09] Add create_time to the signature of Repository constructor.

### PR DESCRIPTION
**Pull request by VJalili**
ping @martenson

### CODE REVIEW

**Comment by martenson** [comment]
@VJalili Please expose the other visible keys from https://github.com/galaxyproject/galaxy/pull/8681/ in similar manner to fix it fully.

**Comment by VJalili** [comment]
@martenson yes, good point. Please see https://github.com/VJalili/galaxy/commit/2fef3ba45924a6b149ca48152fc892bedecb51bd, though not sure why that commit is not shown here!

**Comment by martenson** [comment]
I dunno, but we need the commit here. 🙃

**Comment by VJalili** [comment]
close/re-open?

**Comment by VJalili** [comment]
@martenson does not seem that adding `ratings`, `reviews`, and `reviewers` the same way as `create_time` is necessary. Maybe because they are fetched from other tables?

https://github.com/galaxyproject/galaxy/blob/ad84cef8f8db4766da1135877b5655d7ee19b1d0/lib/galaxy/webapps/tool_shed/model/mapping.py#L258-L274

Without adding those attributes to the signature of the Repository constructor, I can get a json object as the following from API: 


- `GET localhost:9009/api/repositories/`
    ```
    [
        {
            "times_downloaded": 0,
            "user_id": "adb5f5c93f827949",
            "name": "test",
            "deleted": false,
            "deprecated": false,
            "private": false,
            "category_ids": [
                "adb5f5c93f827949"
            ],
            "homepage_url": "",
            "create_time": "2019-12-06T07:43:11.445203",
            "owner": "vahid",
            "model_class": "Repository",
            "type": "unrestricted",
            "id": "adb5f5c93f827949",
            "remote_repository_url": "",
            "description": "some description ..."
        }
    ]
    ```

- `GET localhost:9009/api/repositories/adb5f5c93f827949`
    ```
    {
        "ratings": [],
        "times_downloaded": 0,
        "user_id": "adb5f5c93f827949",
        "name": "test",
        "deleted": false,
        "deprecated": false,
        "private": false,
        "long_description": "some description",
        "reviews": [],
        "homepage_url": "",
        "create_time": "2019-12-06T07:43:11.445203",
        "reviewers": [],
        "owner": "vahid",
        "model_class": "Repository",
        "category_ids": [
            "adb5f5c93f827949"
        ],
        "type": "unrestricted",
        "id": "adb5f5c93f827949",
        "remote_repository_url": "",
        "description": "some description ..."
    }
    ```

and it seems `ratings`, `reviews`, and `reviewers` are already reported. Therefore, I rebased and removed the last commit.

**Comment by VJalili** [comment]
@martenson I guess we're able to expose the [listed properties](https://github.com/galaxyproject/galaxy/blob/e19fe0376a60473b6262570f61c8aa8345ea8c3e/lib/galaxy/webapps/tool_shed/model/__init__.py#L164-L168); any other suggestions?

**Comment by martenson** [comment]
Nope, that's good, thanks!

**Comment by VJalili** [comment]
Thank you.

**Pull request merged**
