### PR TITLE
Add EDAM IDs to datatypes

### PR DESCRIPTION
**Pull request by hexylena**
I made a best-guess attempt at most of these, EDAM doesn't include image datatypes, nor graph datatypes, nor colourspace fastq (among other things, these just came to mind).
- https://trello.com/c/TRgSWfT1/
- http://bioportal.bioontology.org/ontologies/EDAM/?p=summary

Comments/feedback/suggestions welcome.

### CODE REVIEW

**Comment by jmchilton** [comment]
@erasche Thanks for getting the ball rolling on this.

For some the additional context the [CWL project](https://github.com/common-workflow-language/common-workflow-language) has been considering adopting EDAM for data formats - but there is general consensus among participants that tool authors should be allowed to use short identifiers instead of numeric codes. EDAM has labels but they are not considered stable and so the consensus during the last call was to wait for this mapping (the Galaxy->EDAM mapping) and then adopt Galaxy's identifiers for the corresponding EDAM codes as part of the CWL draft standard.

Within this context - I think it would be better if each EDAM term be mapped to at most one Galaxy datatype. Galaxy is able to reason about subtypes (https://github.com/jmchilton/galaxy/commit/fe461599d603baeae1f71ea140b0a12bd0a4cabf) so there shouldn't be any need to label all the bed datatypes with the same EDAM label for instance - just the most generic one that matches it. What do you think @erasche - can you make that change?

If there is any place where the hierarchies don't match that would be very interesting/concerning.

I am usually very eager to merge pull requests - but I kind of want to go slowly with this one - I hope that is okay. Given the stakes - I want lots of eyes to see it and I want Pasteur to weigh in since they are going to be working on this as well (perhaps [this project](https://github.com/edamontology/toolinfowarehouse)) 

Pinging - @hmenager at Pasteur who was working with Olivia Doppelt and Fabien Mareuil (who I cannot find Github handles for) on building this mapping.

**Comment by hexylena** [comment]
@jmchilton Sure. It seemed like low hanging fruit :P 

Hmmm, okay, if galaxy is going to provide extra subtype information on top of the EDAM datatypes, that should be possible to handle. 

EDAM doesn't seem to have the hierarchy I would've expected. I would've expected a pure tree whereby all binary formats are under binary, regardless of what they're used for. However, that seems to not be the case. (Excuse the xml like notation) E.g. BAM indices are under `/formats/Formats (typed)/data index formats/BAI`, and not under `/formats/binary format/`.

Agreed, this is WIP, not ready to merge yet. I was more interested in soliciting feedback at this point. I'll make the changes and ping you again when that's ready.

**Comment by hmenager** [comment]
@jmchilton, Fabien is @fmareuil and Olivia is @odoppelt.

**Comment by jmchilton** [comment]
We modified the approach here a little - ready to take this out of WIP. I plan to review terms and merge Tuesday unless there are objections.

**Comment by jmchilton** [comment]
I am merging this now - awesome collaboration all! Looking forward to seeing more refinements as the team from Pasteur work to add some of the Galaxy datatypes to EDAM. Their progress can be tracked here https://docs.google.com/spreadsheets/d/1vptTpJvQfb5FOtRJOajjftUkL9aZ0eeVdhUPvd9h5wY/edit#gid=0.

The current mapping (galaxy extension to EDAM format) at the time of this merge is https://gist.github.com/jmchilton/0f559033430824f157fe.

**Pull request merged**
