### PR TITLE
Revise selection, options and drilldown wrappers, add tests

### PR DESCRIPTION
**Pull request by guerler**
This PR aligns the pattern/models for select fields, radio buttons, checkboxes and drilldown elements and adds 270 new test assertions.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
yay for new tests! 👻

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Pull request merged**
