### PR TITLE
Fix remaining selenium tests and add headless testing option.

### PR DESCRIPTION
**Pull request by dannon**
This was a race condition with the new logout redirect, I believe.  On fast machines everything works fine because the logout click was happening before the redirect kicked in, so the tests all passed.  On jenkins or on my intentionally slow testing VM, I was able to reproduce the delayed click trying to happen after/during redirect.

I'm going to lump a headless selenium testing option that was very useful for me while testing/reproducing (for at least chrome) into this PR as well.  At least one more commit coming to make it configurable, off by default, and maybe try to get geckodriver doing it as well.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Seems to work! :tada:

The first 2 failing tests passed.

**Comment by guerler** [comment]
Is this good to go? Thanks @dannon

**Comment by dannon** [comment]
@guerler Not quite; I went down the rabbit hole trying to get firefox/geckodriver working to set up (native) headless compatibility for that but it seems to be a mess with firefox 48+ and marionette or whatever.  I'm going to push a tweak for chrome's headless mode to make it configurable and write some documentation and then it'll be ready.  I'll switch it out of WIP then.

**Review by mvdbeek — APPROVED** [review]
Awesome! Thanks @dannon !

**Comment by dannon** [comment]
Thanks for the merge.  @guerler your chrome-based selenium testing should now be natively headless, too, by default without the extra display requirements.

**Comment by guerler** [comment]
Thanks @dannon.

**Pull request merged**
