### PR TITLE
Allow uninstalling multiple toolshed repositories at a time …

### PR DESCRIPTION
**Pull request by blankenberg**
… within the Galaxy UI, using checkboxes with grid multi-actions.

### CODE REVIEW

**Comment by carlfeberhard** [comment]
+1 works. 

When uninstalling two tools, I expected Galaxy to show a page for each tool to be uninstalled/deactivated (with the tool info and checkbox for the uninstall/deactivate choice) but was only shown the page for the first tool. 

Not a deal breaker, it's admin UI, and I know what a pain that sort of 'page queue' would be to implement, but it was unexpected.

**Comment by blankenberg** [comment]
Currently, it should show on one page: all Repositories info (that used to be displayed for the single repo) to be uninstalled and have one checkbox for all to toggle uninstall/deactivate. 

Spacing between the blocks of the repos could be better.

**Comment by martenson** [comment]
:+1: 
works nicely, thank you very much Dan
@carlfeberhard I was shown details for every tool I was uninstalling (on same page), but only one checkbox as Dan described

**Comment by bgruening** [comment]
Fantastic! Any change to get this for installing tool as well ;) I think I saw a biostar post about this.

**Comment by carlfeberhard** [comment]
Oops - my brain squashed them together. Sorry about that.

**Comment by bgruening** [comment]
Jen ask for this feature, so can we move it into the next 15.07?

**Pull request merged**
