### PR TITLE
[15.10] Tool Shed fixes.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix the last 2 broken Tool Shed tests in my local environment.

### CODE REVIEW

**Comment by hexylena** [comment]
Started a jenkins build. https://jenkins.galaxyproject.org/job/docker-toolshed/16/console

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
:+1:

**Comment by hexylena** [comment]
@martenson you aborted it?

**Comment by hexylena** [comment]
@martenson's rationale for cancelling

```
15:44:54     g2roboto | [marten] for some strange reasons TS tests for 15.10 are trying to use sqlite.. :/                      │ perrier__
15:44:55     g2roboto | [marten] <https://jenkins.galaxyproject.org/job/docker-toolshed/18/console>                             │ pescobar   
```

**Pull request merged**
