### PR TITLE
[19.09] Backport #8953 grouping strip newline

### PR DESCRIPTION
**Pull request by bernt-matthias**

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
This is not needed given it is being backported to 19.05 in #8970 .

**Comment by bernt-matthias** [comment]
OK. But odd that tests fail here. Lets see what they are doing for the 19.05 backport.

**Comment by mvdbeek** [comment]
These were failing because of:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
The changes here should at most affect the framework tests.

**Comment by mvdbeek** [comment]
I've merged this forward now.

**Comment by bernt-matthias** [comment]
Thanks

**Pull request closed without merging**
