### PR TITLE
Pinia'ified jobStore.js

### PR DESCRIPTION
**Pull request by kxk302**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
@kxk302 You may need to change the reference in `client/src/store/index.js` where the store is used.

**Comment by martenson** [comment]
Sooo, this component seems unused? We might want to just drop it if this is dead code. Originally added here: https://github.com/galaxyproject/galaxy/pull/10353

**Comment by kxk302** [comment]
> Sooo, this component seems unused? We might want to just drop it if this is dead code. Originally added here: #10353

If it is not going to be used again, yes, its a god idea to just remove it.

**Comment by kxk302** [comment]
Created this PR to remove jobStore: https://github.com/galaxyproject/galaxy/pull/15198

**Pull request closed without merging**
