### PR TITLE
Full Python dependencies update

### PR DESCRIPTION
**Pull request by nsoranzo**
using `make update-dependencies`.

Also use latest pipenv.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Failing due to https://github.com/kvesteri/sqlalchemy-utils/pull/463 and https://github.com/galaxyproject/starforge-recipes/pull/73

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Not sure if the selenium failed tests are related. Otherwise it's green.

**Comment by dannon** [comment]
I get the same two failures locally in selenium

**Pull request merged**
