### PR TITLE
add PasswordToolParameter

### PR DESCRIPTION
**Pull request by kaktus42**
I propose a new field for tools.
It works like a text field (without area option), but everything is hidden with *
It uses the PasswordField from form_builder to create a password field in HTML

### CODE REVIEW

**Comment by jmchilton** [comment]
Something similar has been declined in the past - https://bitbucket.org/galaxy/galaxy-central/pull-request/107/adding-password-datatype-to-tools/diff. I think part of the problems with solutions like this is that the password is saved in plain text in the database and leaks through in the UI/API many ways - I think an acceptable solution would have to somehow store this in a safe way and only allow the tool to consume it.

Perhaps - encrypt these right away on job submission in someway and only decrypt it in tool wrappers and then only expose it as an environment variable and not in the command itself.

**Comment by kaktus42** [comment]
Well - I understand the problem you are stating.
However, it gives a possibility to at least be safe when entering a password, so nobody can see it.
On the other hand it might lead people to believe that what they put in here is safe, although it is not.

**Comment by hexylena** [comment]
I'd...be OK with something like this if it isn't exposed in plain text ever, which would mean...
- encrypt against site secret key during submission
- don't leak plain text _or_ encrypted text through API or UI 
  - don't want to enable easy known-plaintext attacks on the secret key

it's still going to show up on the CLI if you aren't using `<configfiles />` so anyone on the cluster will still be able to see the password, depending on how its being run.

It really is a false sense of security :/

**Comment by jmchilton** [comment]
@erasche I think it should be possible to expose this parameter via an environment variable and not allow it to be used in configfiles or command-lines. May open a PR that allows the tool class to express environment variables anyway - since this will be needed for CWL support (https://github.com/common-workflow-language/common-workflow-language/blob/master/conformance/draft-2/env-tool1.cwl). Still the sense of uneasiness is warranted I think.

**Comment by hexylena** [comment]
@jmchilton I did some tests...

``` bash
#!/bin/bash
export SLEEP_TIME=30
sleep $SLEEP_TIME
```

then as another user...

``` console
gkuty@cpt:/home/gkuty/$ ps aux | grep sleep
esr       7190  0.0  0.0   5912   612 pts/11   S+   17:52   0:00 sleep 30
```

:(

**Comment by hexylena** [comment]
If you're doing

``` bash
PGPASSWORD=$MY_OTHER_PASSWORD
```

and the underlying tool knows to check the environment (like postgres), then it's OK. But based on my knowledge you can't template environment variables into commands without them being expanded to their values

**Comment by jmchilton** [comment]
I see you what you mean @erasche - I guess my previous thinking would be the underlying application - maybe a Python script that makes an authenticated connection using requests directly - consumes the environment variable as an environment variable - not as a command-line argument. Though - I suppose that is a somewhat contrived example and most of the time such applications would be access via command-lines. Even for the command-line passing examples though - the environment variable is better since it wouldn't be expanded in what Galaxy records as the command-line - so history sharing for instance wouldn't risk exposure of this.

I have opened a pull request that allows tools to produce environment variables in #395 - because I have ulterior motives and because I think it would be broadly useful. It is only a small piece but hopefully it helps.

**Comment by hexylena** [comment]
@jmchilton it's not a completely contrived example, postgres works that way! I just wanted to raise the point that templating it in could be dangerous.

Yes, the lack of expansion in the CLI history is a great consideration. That's definitely good.

**Comment by jmchilton** [comment]
Closing this for now - until the described problems are addressed. @kaktus42 if you want more help working through a more secure implementation - please let me know and I will see what I can do.

**Pull request closed without merging**
