### PR TITLE
Fixes for WorkflowContentsManager requiring app during init.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Any idea why a casperjs test failed?

**Comment by martenson** [comment]
I triggered manual re-run, we will see

**Comment by nsoranzo** [comment]
@martenson: Casperjs test still failing.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Yep, fixes the initialization of this manager.

**Pull request merged**
