### PR TITLE
[22.05] Fix tool version inconsistency when downloading workflows with missing outdated tools

### LINKED ISSUE #7982: tool version of subworkflows within workflows not updated
Hello,

when a tool version used in a workflow becomes unavailable, but a newer version of the tool is present, this is automatically used and the user informed about this. For subworkflows within such a workflow the `tool_id` field of the tool is updated but the `tool_version` field is not. This results in the workflow not finding the tool that the subworkflow is looking for. Changing the `tool_version` field to the correct version was sufficient to resolve the issue.

**excerpt form the workflow JSON:**

```
...
"13": {"tool_id": "REPO_LOCATION/REPO_NAME/TOOL_NAME/0.1.1", 
         "tool_version": "0.1",
...
```

Best regards

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #7982 

This will export a consistent `tool_id` and `tool_version` of the tool when downloading a workflow containing an outdated tool in a sub-workflow. 

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Import a workflow that contains any sub-workflow using any tool whose version is outdated.
  2. Download the imported workflow with outdated tool versions
  3. The downloaded workflow file contains the original tool ID and tool version.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
From what I understood from https://github.com/galaxyproject/galaxy/issues/7982 this is a problem when attempting to run and/ or edit the workflow. I am not sure it's a good idea to change the tool version when downloading a workflow, I think you would still want to get the workflow as it is stored in the database. Did you figure out where the discrepancy between tool version and tool id is coming from ? It was my suspicion that we had already fixed this, were you able to reproduce this ?

> is there a way to upgrade the sub-workflow internal tool from the parent?

I think that would be a more extensive project, maybe it would be possible by using the workflow refactoring actions.

**Comment by davelopez** [comment]
I'm afraid I can still reproduce it.

> From what I understood from https://github.com/galaxyproject/galaxy/issues/7982 this is a problem when attempting to run and/ or edit the workflow. I am not sure it's a good idea to change the tool version when downloading a workflow, I think you would still want to get the workflow as it is stored in the database.

Yes, the message is shown when attempting to run or edit, I assumed it was also related to the workflow download since the issue was mentioning the version difference was found in the workflow JSON file. But you are right, it doesn't feel right to modify the file on download, is not modified in the database though. But the tool ID was being modified because of the following...

> Did you figure out where the discrepancy between tool version and tool id is coming from ?

I think I did, at least partially, the discrepancy I found was in `_workflow_to_dict_export` (which creates the version mismatch shown in #7982) the `content_id = module.get_content_id()` gets the updated tool ID from the tool module but keeps the step tool_version that I changed to do the same.

**Comment by davelopez** [comment]
I applied the reverse fix as discussed in the backend meeting.

This has been around for a while... which Galaxy version should I target?

**Comment by mvdbeek** [comment]
22.05 or dev seem fine

**Comment by mvdbeek** [comment]
> Should we conditionally use the `step` original tool versions for downloading and the updated ones when `_workflow_to_dict_export` is called from the refactoring system?

👍

**Comment by mvdbeek** [comment]
The consistency here is definitely a step up, thanks a lot!

**Comment by davelopez** [comment]
The mypy failure is unrelated

**Pull request merged**
