### PR TITLE
Strip URL of download_file and download_by_url install actions.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix installation of latest `package_perl_5_18` which was "broken" in https://github.com/galaxyproject/tools-iuc/commit/6e4dc6da6100035782ebfc223630ee75429587d0 due to the added whitespaces.

Ping @pvanheus and @bgruening.

### CODE REVIEW

**Comment by blankenberg** [comment]
+1

**Comment by pvanheus** [comment]
Testing this on a local install, it works! Thanks! +1

**Comment by blankenberg** [comment]
Good sleuthing @nsoranzo !

**Comment by hexylena** [comment]
Hah, wow, all my fault. My apologies y'all!

**Pull request merged**
