### PR TITLE
Add changeset_revision to tool attributes, avoid self.tool_shed_repos…

### PR DESCRIPTION
**Pull request by mvdbeek**
…itory

This should avoid querying the database, which I introduced with PR #982 :/

### CODE REVIEW

**Comment by mvdbeek** [comment]
ping @jmchilton

**Comment by jmchilton** [comment]
Awesome - thanks a ton for the fast fix @mvdbeek!

**Comment by mvdbeek** [comment]
https://test.galaxyproject.org/ is still super-slow ... did it do the trick?
testing on my macbook with 5 installed ts-tools with this fix:

```
(.venv)mariuss-MBP:galaxy marius$ time curl 127.0.0.1:8080/api/tools > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4790    0  4790    0     0  1145k      0 --:--:-- --:--:-- --:--:-- 1559k

real    0m0.013s
user    0m0.005s
sys 0m0.005s
```

without

```
(.venv)mariuss-MBP:galaxy marius$ time curl 127.0.0.1:8080/api/tools > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4790    0  4790    0     0  70208      0 --:--:-- --:--:-- --:--:-- 70441

real    0m0.076s
user    0m0.004s
sys 0m0.004s
```

**Comment by natefoo** [comment]
@mvdbeek Haven't updated yet, doing this now. Ditto on thanks for the quick fix!

**Comment by natefoo** [comment]
@mvdbeek Fixed. Thanks!

**Pull request merged**
