### PR TITLE
UI revision (panel rendering, iframes and tool forms)

### PR DESCRIPTION
**Pull request by guerler**
This PR revises the UI such that the Analysis panel view i.e. Galaxy root / index.mako is rendered in js without base_panels.mako: https://github.com/galaxyproject/galaxy/pull/706/files#diff-cc03cb56de4268b467cfcabe50ebcd32. The panel content is abstracted from the view itself (see client/galaxy/mvc/app/: https://github.com/galaxyproject/galaxy/pull/706/files#diff-7079cdc7743e7207e726e8144a0b8142). In principal, we should now be able to use other js-based window managers for Galaxy. In this context, the PR introduces a new function (Galaxy.app.display( $el )) which can be used to display content in the center frame without using the iframe. This is illustrated with tool forms from the tool panel (see tools.js: https://github.com/galaxyproject/galaxy/pull/706/files#diff-45b564f67746a0f8c0fdc83a7fb2bc0e). Tool forms are now loaded into a div-element. The old tool form and its mako description have been removed. Now, we can successively continue and replace other views which still use the iframe. The iframe itself is still available and becomes visible when its source (src) attribute is modified. The PR also revises the button views i.e. MenuButton, IconButton etc. which are now collected in one file (see ui-buttons.js: https://github.com/galaxyproject/galaxy/pull/706/files#diff-20409b4f3c2a8571d5a19f6e296ca8bd). An additional variation i.e. ButtonLink has been introduced and is rendered in the panel headers. Finally, code styles and conventions were applied to some arbitrary js-files.

### CODE REVIEW

**Comment by bgruening** [comment]
Impressive work!
If anyone wants to test this easily here is a Docker container with @guerler branch:

`docker run -i -t -p 8080:80 bgruening/galaxy-stable:experimental`

@guerler it's working great for me, but I still see the iframe (`id="galaxy_main"`) is this ok?

**Comment by guerler** [comment]
@bgruening Yes, the iframe is available. There are still views which depend on it.

**Comment by bgruening** [comment]
I can not judge on the JS code but I tested it a little bit and it looks good and feels very fast. I realised a scrolling issue with the tool form on large tools but I guess this was fixed in your last commit.

`+1,517 −1,911` just great!

**Comment by jxtx** [comment]
Magnificent! +1

**Comment by dannon** [comment]
+1, working well for me.  Following up separately with a few extra items.

**Pull request merged**
