### PR TITLE
[16.04] fix/replace biomart data source

### LINKED ISSUE #2148: Galaxy Main Get Data Biomart link broken
Hi,

In Main, if we go to "Get Data" --> BioMart, we get the following error.

Not Found

The requested URL /biomart/martview was not found on this server.

Apache/2.4.18 (Unix) Server at www.biomart.org Port 80

Thank you,
Lynn

### PR DESCRIPTION
**Pull request by martenson**
closes #2148

### CODE REVIEW

**Comment by nsoranzo** [comment]
More info at http://www.biomart.org/notice.html .

**Comment by martenson** [comment]
@nsoranzo I just noticed that ensembl is probably providing only a subset of former biomart data? :/

**Comment by nsoranzo** [comment]
@martenson I suspected that too, but I am no expert.

**Comment by natefoo** [comment]
Better than nothing for the moment. We could put a warning message in the tool explaining the situation, perhaps? You can use an rST warning class for it, e.g.

```
.. warning:: This tool blah blah due to blah blah for more info see this link.
```

**Comment by martenson** [comment]
@natefoo the tool form is never visible on our side; it just opens a new tab for you - so I am not sure we have a good place where to put a warning

**Comment by natefoo** [comment]
Oh, right.

**Comment by dannon** [comment]
@martenson Yeah, my reading of the notice and understanding of how this works leads me to think that this change would reduce the set of available stuff pretty dramatically (and somewhat arbitrarily -- I don't know how many more users would complain if stuff vanished than if it was just temporarily disabled).

Should we just temporarily disable it?

**Comment by martenson** [comment]
I say subset is better than nothing.

**Comment by dannon** [comment]
How'd you pick the ensembl subset over one of the other ones?

**Comment by martenson** [comment]
I picked fairly randomly (browsed a few and this one had the most data). I would be interested in knowing whether the original biomart encompassed all the data from the community servers listed at http://www.biomart.org/notice.html

**Comment by dannon** [comment]
That's what I was afraid of.  And, yeah, my understanding just based on how they phrased the notice leads me to think they did.

**Comment by martenson** [comment]
Alternatively we can create a new section where we would list all these data sources. However I am not sure whether all support the GALAXY_URL redirect...but they might.

**Comment by dannon** [comment]
Eh, we could make it explicit.  PR inc, which if it seems good to you, I'll merge this.  https://github.com/martenson/galaxy/pull/14 seem good?

**Comment by dannon** [comment]
(I'm totally fine with a temporarily reduced subset, as long as it's clear to users that's what they're getting)

**Comment by martenson** [comment]
I went through some more URL listed at the notice and they are surprisingly often dead.

**Comment by martenson** [comment]
moving to WIP until we figure out what to do

**Comment by martenson** [comment]
back to review state; lets fix this with just ensembl and decide later if we want more

**Comment by dannon** [comment]
LGTM, then.  Thanks!

**Pull request merged**
