### PR TITLE
Toolshed client build separation

### PR DESCRIPTION
**Pull request by dannon**
Completely drops toolshed 1.0 from the build process, now that we've deployed 2.0 to test and it's the way forward to focus on.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Congrats for issue/PR #15000!

**Comment by martenson** [comment]
Closing since we have TS 2.0 now which is separated afaik.

**Comment by dannon** [comment]
It's separated, but didn't remove the existing bundles.  We still need to do this, just with one more commit deleting the now separated stuff.  I'll update this with that now.

**Comment by martenson** [comment]
sidenote: This removes our ability to deploy Toolshed 1.0

long live TS2.0!

**Pull request merged**
