### PR TITLE
Enable pytest class-based tests

### PR DESCRIPTION
**Pull request by jdavcs**
#12071

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Number of discovered tests after these edits should remain unchanged compared to previous test runs (applies to all github workflows)

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Can you add an example class or point to one you want to create ? I think the test functions have worked out well so far and I think are much less complex than our unit test classes for instance. I am also confused by the need to treat classes as tests ... as long as you have a test method that test is still going to be executed, right?

Not a fan of placing actual attributes in code only for our testing framework.

**Comment by ic4f** [comment]
I initially proposed this to better organize a test module I'm working on that is going to be quite large. Organizing all those functions into classes would've made navigating the module easier. However, I refactored it since then, and now it's one test function per model, so I don't need any further organizing. So there's no immediate need.

That said, I think it would be nice to have the option. As per docs, classes in pytest are only used for organizing tests into groups (easier to navigate), and then sharing fixtures and applying marks per class. There's no complexity added beyond the class definition; and you can't abuse it, as far as I understand: each test gets its own instance of the class. And yes, I also prefer the simplicity and atomicity of standalone test functions vs. the xUnit approach.

I'm also not a fan of modifying code to accommodate a test framework. But it's a tradeoff: we use that framework, and that makes our code less flexible: we are constrained by how we can name our functions and/or classes and methods. So, the tradeoff is that we either add something to our code saying "ignore this item" or we tell the framework "ignore all items of this type". We currently do the latter, I think it would be more beneficial to do the former, since we'd have the option of organizing tests into classes. But I suspect it's a matter of preference. I don't mind closing this for now, until I come across the next case where the test code may benefit from more structure.

**Comment by mvdbeek** [comment]
> As per docs, classes in pytest are only used for organizing tests into groups (easier to navigate), and then sharing fixtures and applying marks per class

So do we need the change in pytest.ini for that ? As I understood it this is only needed if the class itself would be the test, or am I wrong there ?

**Comment by ic4f** [comment]
> So do we need the change in pytest.ini for that ? As I understood it this is only needed if the class itself would be the test, or am I wrong there ?

Unless I'm mistaken, pytest doesn't treat the class itself as a test. ([Here's the relevant documentation](https://doc.pytest.org/en/latest/explanation/goodpractices.html#conventions-for-python-test-discovery), specifically: "[pytest collects] `test` prefixed test functions or methods inside `Test` prefixed test classes (without an `__init__` method)". So, this:
```py
def test_foo(): pass
def test_bar(): pass
```
is identical to this:
```py
class TestFooBar:
    def test_foo(): pass
    def test_bar(): pass
```
This `pytest.ini` line: `python_classes =` tells pytest to ignore *all* classes. As a result, the 2 methods above will not be collected, and that will be done silently. So, if we organize tests in a class (following pytest documentation), those tests will be ignored, and we may never know.
 [Here's the default behavior of this setting](https://doc.pytest.org/en/latest/reference/reference.html#confval-python_classes); speaking of which, it will *not* ignore `unittest.TestCase` derived classes, so it's more like "ignore tests within all classes except unittest classes, where collection is delegated to unittest".  The change in `pytest.ini` was added to silence a pytest warning that was triggered anytime pytest discovered a `Test` prefixed class with a constructor.

**Comment by mvdbeek** [comment]
Alright, thanks for the explanation. I didn't know that the `unittest.TestCase` derived classes are handled differently, I had just assumed that all classes are collected based on `unittest.TestCase` derived classes

Would it make sense to rename the unit test classes ? The stuff in tool_util we should probably not change, since that is available as a package.

**Comment by ic4f** [comment]
@mvdbeek I think I've renamed all the classes I could without touching packages. The rest use the `__test__ = False` flag. I tried to keep it simple: `TestFoo` >> `Foo` if used within the module, and `TestFoo` >> `MockFoo` if used in other modules.

**Pull request merged**
