### PR TITLE
Remove remaining Vuex stores and dependencies

### PR DESCRIPTION
**Pull request by davelopez**
It seems all major Vuex stores have been already replaced by Pinia stores and the 2 remaining (`tagStore` and `gridSearchStore`) are not used anymore.

Opening PR for smoke testing... and to check if anything is still depending on Vuex

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by davelopez** [comment]
Alright, it seems safe to remove, it may only affect MAKOS that use the Tags and CommunityTags but I don't think we are using any of these MAKOS anymore. It would be nice if someone more familiar with the old MAKOS could take a quick look too.

**Review by jmchilton — APPROVED** [review]
I can't speak to the Makos but I am going to +1 this so you can merge it if no one ever gives the mako thing a second look.

**Review by martenson — COMMENTED** [review]
I gave the makos a second look. Looks good. Thanks for the cleanup @davelopez

**Comment by davelopez** [comment]
Thank you both!

**Pull request merged**
