### PR TITLE
[WIP] [18.05] Increase upload api chunk handling size

### PR DESCRIPTION
**Pull request by guerler**
Attempt to improve upload performance by increasing the chunksize from 65KB to 1MB.

### CODE REVIEW

**Comment by dannon** [comment]
@guerler Out of curiosity, what speedup do you see in changing the chunk size?

**Comment by guerler** [comment]
I opened this PR to follow-up on yesterdays and todays recent discussion, the upload times I am seeing locally do not show delays of minutes so its difficult for me to benchmark this in a realistic environment. On the other hand, I think 65KB is pretty low chunksize when it comes to large files and I want to make sure and discuss with this PR that this is not the cause of the issue.

**Comment by dannon** [comment]
@guerler Yeah, it's not a bad idea -- I'd just love to see data to explain the behavior here.  In my local testing, copying a 200MB file (so, twice our chunk size), the 1MB chunk size for reads is actually consistently slower when using a 1mb chunk vs the 64k chunk.  

(timeit x100 for each function -- if you'd like, I can try this same thing on our tacc hardware to see if there's a difference)

Edit again:  I tried it, with a 203mb sacCer3.fa.  Here are the results I'm seeing.  Maybe there's something else at play?
```
yoplait@malleus:~/work python testcopy.py
64k: 2.67550301552
1mb: 3.22707891464
```

Reran x100 on galaxy04:
```
(.venv)[dbaker@galaxy04 ~]$ python testcopy.py
64k: 3.79702711105
1mb: 4.17350506783
```

(this doesn't take into account potentially copying across filesystems, from one disk to another, or the like -- that'd be worth checking, too, before a stable PR changing the behavior here)

**Comment by guerler** [comment]
@dannon awesome. Thanks for looking into this. Will close this PR.

**Pull request closed without merging**
