### PR TITLE
Restores OpenID post authentication protocols

### LINKED ISSUE #7648: GenomeSpace interaction no longer possible
Due to removal of OpenID (https://github.com/galaxyproject/galaxy/pull/7028), GenomeSpace tools will no longer work.

```
galaxy.jobs.runners ERROR 2019-04-02 17:07:26,665 [p:64478,w:1,m:0] [LocalRunner.work_thread-0] (1353) Failure preparing job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 223, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 871, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 454, in build
    raise e
AssertionError: Invalid token. You must be logged into GenomeSpace through OpenID.
```

### PR DESCRIPTION
**Pull request by guerler**
Fixes #7648. Restores post-authentication protocols for OpenID, demonstrated in the use of GenomeSpace authentication tokens. Feature is accessible in the user preferences panel. This restored version does not interfere with Galaxy's login mechanism and is contained in a separate module.

To test this: Set `enable_openid = true`  in the config file, restart Galaxy, log in and access the user preference page then click `Request GenomeSpace token` and log in to Genomespace. Finally, run a Genome Space tool.

### CODE REVIEW

**Comment by dannon** [comment]
The handshake to get a token works fine for me now.  It might be worth adding a feature to disconnect/drop the genomespace token, but we can do that later.

When I go to run the exporter, I'm getting:
```
Traceback (most recent call last):
  File "/Volumes/work_cs/galaxy/tools/genomespace/genomespace_exporter.py", line 6, in <module>
    from genomespaceclient import GenomeSpaceClient
  File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/__init__.py", line 1, in <module>
    from .client import GSDataFormat  # noqa
  File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/client.py", line 8, in <module>
    from genomespaceclient import storage_handlers
  File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/storage_handlers.py", line 5, in <module>
    from cloudbridge.cloud.factory import CloudProviderFactory, ProviderList
ImportError: No module named cloud.factory
```
but that's a separate error from this work ~I think?~.

**Comment by blankenberg** [comment]
> The handshake to get a token works fine for me now. It might be worth adding a feature to disconnect/drop the genomespace token, but we can do that later.
> 
> When I go to run the exporter, I'm getting:
> 
> ```
> Traceback (most recent call last):
>   File "/Volumes/work_cs/galaxy/tools/genomespace/genomespace_exporter.py", line 6, in <module>
>     from genomespaceclient import GenomeSpaceClient
>   File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/__init__.py", line 1, in <module>
>     from .client import GSDataFormat  # noqa
>   File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/client.py", line 8, in <module>
>     from genomespaceclient import storage_handlers
>   File "/Volumes/work_cs/galaxy/.venv/lib/python2.7/site-packages/genomespaceclient/storage_handlers.py", line 5, in <module>
>     from cloudbridge.cloud.factory import CloudProviderFactory, ProviderList
> ImportError: No module named cloud.factory
> ```
> but that's a separate error from this work I think?.

That should be fixed with https://github.com/galaxyproject/galaxy/pull/7647

**Comment by dannon** [comment]
@blankenberg Great, thanks!

**Comment by blankenberg** [comment]
> @blankenberg Great, thanks!

To be fair though, I didn't actually test the exporter, just the importer (which had the same cloud.factory error during tool load).

**Pull request merged**
