### PR TITLE
Add "All" and "None" buttons to copy dataset view. And fix 2 minor bugs

### PR DESCRIPTION
**Pull request by blankenberg**
Bugs:
- Fix for displaying empty history message in copy datasets.
- Fix for copy datasets to respect the '-OR-' and only copy to a new history when name is provided.

### CODE REVIEW

**Comment by blankenberg** [comment]
copy_datasets

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
