### PR TITLE
[19.09] do not force library tags to be `name:` tags + backport

### PR DESCRIPTION
**Pull request by martenson**
similar to https://github.com/galaxyproject/galaxy/pull/8947/files#diff-698ed36fb7f872235431642ca06a0dfcR108

cc @mvdbeek @nsoranzo

### CODE REVIEW

**Comment by nsoranzo** [comment]
@martenson Can you also add here the backport of the change to lib/galaxy/managers/library_datasets.py you linked above?

**Comment by martenson** [comment]
@nsoranzo right, I forgot that went to dev, sorry

**Comment by nsoranzo** [comment]
BioBlend PR to test this: https://github.com/galaxyproject/bioblend/pull/301 and corresponding failing 19.09 Travis job: https://travis-ci.org/galaxyproject/bioblend/jobs/612200831

**Comment by martenson** [comment]
I backported commits from https://github.com/galaxyproject/galaxy/pull/8947 to this PR.

**Comment by nsoranzo** [comment]
The new BioBlend tests pass on 19.09 now, thanks @martenson!

**Comment by martenson** [comment]
Thanks to you @nsoranzo !

**Pull request merged**
