### PR TITLE
[15.10] Fix grid bulk operations

### PR DESCRIPTION
**Pull request by dannon**
Graft of #971 for stable

### CODE REVIEW

**Comment by guerler** [comment]
:+1:

**Comment by guerler** [comment]
@galaxybot test please

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Anyone care to verify this cherry-pick?

**Pull request merged**
