### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by galaxybot**
Run `make update-dependencies`.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Green and ready for review.

**Comment by jmchilton** [comment]
This makes so much more sense to me! Thanks for fixing the way dev dependencies work. Hopefully no-one is relying no the fact that the dev dependencies had the other ones mixed in (planemo, CI for various things, etc...).

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
> This makes so much more sense to me! Thanks for fixing the way dev dependencies work.

Having the core dependencies duplicated in the `dev-requirements.txt` was due to `poetry export` behaviour, the `--only` option that I've added here has just been added in 1.2.0 and mostly fixes it.

> Hopefully no-one is relying no the fact that the dev dependencies had the other ones mixed in (planemo, CI for various things, etc...).

Yep, I had the same thought, but when were using pipenv this was already the case. And it's quite easy to detect and fix.

**Comment by natefoo** [comment]
Not a huge deal, but any idea why this introduced a pin on setuptools? The ansible role previously pinned it lower, that was fixed in https://github.com/galaxyproject/ansible-galaxy/pull/175 but that made it install the latest so sometimes there'll be a downgrade. There probably is no harm in removing any explicit setuptools version handling in the role (pip should upgrade it on its own if necessary) so I'm removing that in https://github.com/galaxyproject/ansible-galaxy/pull/174. But it's fairly common to do a `pip install --upgrade pip setuptools` on your venv, so this upgrade/downgrade may occur in other scenarios. Again, not a huge deal, but if we don't need to pin setuptools maybe we shouldn't, since pip may care what its version is, and we don't (and shouldn't) pin pip.

**Comment by nsoranzo** [comment]
Many of our dependencies have a dependency on setuptools, although none has an exact pin (only minimum version). Our script uses Poetry to lock all dependencies, not sure why setuptools wasn't pinned before, maybe it was excluded in Poetry <1.2.
https://github.com/galaxyproject/ansible-galaxy/pull/174 looks good to me, we can always come back to this if an issue comes up.

N.B.: In theory we shouldn't pin pip, but we may still need to in the unlikely case pip drops support for a Python release before we do.

**Comment by natefoo** [comment]
Ok, this makes sense, thanks!

**Pull request merged**
