### PR TITLE
Add genbank.gz datatype

### PR DESCRIPTION
**Pull request by Delphine-L**
This PR adds genbank.gz and gbk.gz datatypes. It will allow compressed genbank files to be used with Snpeff tool to build databases for variant annotation.

### CODE REVIEW

**Comment by martenson** [comment]
I might have given @Delphine-L a bad guidance here. Now when I think about it I do not see a good reason for including `gbk.gz` as a separate format. Is there?

**Comment by davebx** [comment]
It could also be argued that this is like `fasta.gz` but for genbank files

**Comment by martenson** [comment]
@davebx I am not following

**Comment by davebx** [comment]
@martenson I was arguing against a strawman, disregard me.

**Comment by nekrut** [comment]
@martenson @davebx is there anything, which prevents us from merging this?

**Comment by davebx** [comment]
@nekrut nope, looks solid to me

**Comment by martenson** [comment]
@nekrut yes, it is not working properly, that is why I switched it to WIP and will fix it today

**Comment by martenson** [comment]
I added the commit that should make the sniffing functional and adds doctests. We ought to make this support better (xref https://github.com/galaxyproject/galaxy/issues/5790) but this should get this PR merged. 

I will gladly refactor once we have a different framework in mind.

**Pull request merged**
