### PR TITLE
Generalize allow_library_path_paste to allow_path_paste.

### PR DESCRIPTION
**Pull request by jmchilton**
Enable pasting paths in the history upload GUI & general purpose tools API for admin users if enabled.

### CODE REVIEW

**Comment by bgruening** [comment]
So we can provide planemo with a `file://` uri to start workflows?

**Comment by jmchilton** [comment]
@bgruening This work is toward a similar end for sure - I'm trying to run some large workflows through Planemo and I can't even get the datasets to load - this should help significantly I hope.

**Comment by bgruening** [comment]
I guess for running workflows from planemo it would be also nice to make use of the linking dataset functionality - and not need to copy the data - iff on the same host.

**Comment by jmchilton** [comment]
@bgruening Fair point - that would be even more efficient. Is this "interface" still good or should I implement that as an option before this gets merged so we can reason about everything all together?

**Comment by bgruening** [comment]
This is great as it is! Thanks.
I was just thinking that you are working on the `planemo run wf.ga --input_1 foo.fq` idea and that linking would be also nice.

**Review by bgruening — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Pull request merged**
