### PR TITLE
Add an Invocations Panel for the Invocations activity

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Requires #18088 

https://github.com/galaxyproject/galaxy/assets/78516064/b708cc10-2d2e-4095-9014-e80cfc505e9b

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
This is a step backwards in usability, can we revert that for the time being ?

**Comment by mvdbeek** [comment]
I guess it'd have been nice to have a little bit of time to review this, but maybe it is worth getting this in front of users. Could we get the full invocation list button at the top of the panel, and is it possible to keep the invocation activity we have on 24.0 as an option that people like me could continue to use ?

**Comment by mvdbeek** [comment]
(to be fair the 1 hour is likely more than that, with rounding)

**Comment by dannon** [comment]
Thank you for the screenshot.  This PR has been open over a week, and the timestamps you're showing there are showing the simple rebase on top of the parent.  I don't know what point you are making.

**Comment by mvdbeek** [comment]
That it was a draft.

**Comment by dannon** [comment]
Sure, a draft so we could discuss it like we did during the call last week, and in draft waiting on the parent PR to be merged so it could be rebased.  Again, this was not rushed, there's been a week post-discussion.

**Pull request merged**
