### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### galaxyproject/galaxy now has a Chat Room on Gitter

@bgruening has just created a chat room. You can visit it here: [https://gitter.im/galaxyproject/galaxy](https://gitter.im/galaxyproject/galaxy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/galaxyproject/galaxy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by jxtx** [comment]
-1. We already have IRC, and open broadly supported chat platform. We don't need a) yet another venus for communication, b) for it to be a proprietary commercial platform.

**Comment by hexylena** [comment]
I'm +1 because...
- it has github integration, for PRs and Issues this is really convenient.
- Biojs uses the IRC bridge and it works pretty well from my experience https://github.com/gitterHQ/irc-bridge https://gitter.im/biojs/biojs
- email notifications if I'm mentioned/email updates when I'm missing stuff (so..what slack does for devteam, except free for all of us)

-1 for 
- yet another proprietary commercial platform :(
- yet another communication channel (but that problem goes away with the irc bridge)

We'll call this a +0.

**Comment by hexylena** [comment]
Summary of IRC discussion:
- why not just link to freenode webchat
- irc requires some activation energy, this is a positive thing
- github integration isn't that important to devs
  - just post the full URL rather than using number syntax (e.g. #367)
  - we all get github emails/notifications so notifications of new PRs/issues isn't so important
- devteam uses slack, if you want slack interface/email notifications, just set up your own slack-irc connector, the bridge is open source

**Comment by bgruening** [comment]
Sorry, this was more by accident. Didn't know that gitter is really trying to create a PR. That said, if we should advertise the IRC on the readme file as @erasche proposed.

**Comment by martenson** [comment]
@bgruening I think @jxtx is cooking a PR along these lines

**Pull request closed without merging**
