### PR TITLE
[18.05] add static for release

### PR DESCRIPTION
**Pull request by martenson**
This is the `static/scripts` after `make client-production`. Do we need to add anything else?

ping @dannon @jmchilton @guerler

### CODE REVIEW

**Comment by dannon** [comment]
@martenson Shouldn't need to add anything else, but bundled/N.N shouldn't have been included here, only the core 'analysis'/etc. ones.

(and, I am really hesitant to open the can of worms again, but I thought we had all agreed we were dropping maps for this one since people can trivially easily build using the now-built-in infrastructure)

**Comment by martenson** [comment]
I removed the bundled. Maps are not included as we agreed previously.

**Comment by martenson** [comment]
I re-added the core bundled scripts.

**Comment by dannon** [comment]
@martenson Just saw you fixed it up with f61c605 as I was typing -- yeah, it's just the chunked ones we want to leave out, we do want the final bundles.  This looks pretty good to me, let me verify it builds the same on my end and I'll merge it.

**Comment by martenson** [comment]
@dannon I also might have had some local maps or something in the very first commit (I force pushed it later), but never intended to include maps

**Comment by dannon** [comment]
@martenson No worries, yeah, that's what I saw and was commenting on.  Map status looks perfect now, thanks :)

**Comment by jmchilton** [comment]
>  I thought we had all agreed we were dropping maps for this one since people can trivially easily build using the now-built-in infrastructure

I still dissent. These artifacts should include the sourceMappingURLs that admins can compile and put in place.

**Comment by dannon** [comment]
Maybe we revisit that down the road, if we really need to.  For now, let's go with the compromise we came up with when we walked through all this before, at length.

@martenson This looks correct to me, builds the same on my end, and I think we're good to go here.  Thanks!

**Pull request merged**
