### PR TITLE
[23.2] Always store multi select data input values in fixed order

### PR DESCRIPTION
**Pull request by guerler**
partial fix for https://github.com/galaxyproject/galaxy/issues/17320

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
In my testing this resolves the change in ordering multi select inputs. Merging this should remove the release blocker. Thanks @guerler !

**Comment by martenson** [comment]
@guerler check https://github.com/guerler/galaxy/pull/32 please

**Comment by guerler** [comment]
@martenson thank you, the test case looks good to me.

**Comment by jdavcs** [comment]
Thank you, @martenson and @guerler for unblocking the release!

**Pull request merged**
