### PR TITLE
[17.01] Annotate converters that appear to need galaxy on PYTHONPATH.

### LINKED ISSUE #3499: Trackster will not load gff datasets at http://usegalaxy.org
Error with trackster

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/converters/gff_to_interval_index_converter.py", line 16, in 
>     from galaxy.datatypes.util.gff_util import convert_gff_coords_to_bed, GenomicInterval, GFFReaderWrapper
> ImportError: No module named galaxy.datatypes.util.gff_util

@galaxyproject/guac @martenson Not sure if related to 17.01 upgrade/prep

### PR DESCRIPTION
**Pull request by jmchilton**
Should fix #3499 (thanks for the explicit heads up @mvdbeek).

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Review by mvdbeek — APPROVED** [review]
Thanks @jmchilton! The TS test failure is not related. 
On a sidenote, perhaps we should aim to test the converters and all the tools galaxy comes with.

**Comment by jmchilton** [comment]
Certainly it would be a good idea to test all the things - I'll maybe create an issue for converters specifically.

**Comment by gregvonkuster** [comment]
@mvdbeek @jmchilton I hope I'm not hijacking this, but regarding the ability to test all tools, I will soon be introducing several tools into  the tools-iuc repo, and these tools require the use of extremely large data hierarchies that are installed by a Galaxy Data Manager tool.  Is there a way to (or a plan for being able to) have functional tests for these kinds of tools that require access to large datasets installed by a data manager?

**Comment by jmchilton** [comment]
@gregvonkuster These tools might be great but I would encourage you and the IUC to establish a different repository for such tools or maybe just a different folder in the repository. I feel like it isn't a "best practice" tool if it can't be quickly and easily tested. That isn't to say it isn't a great tool or an important tool - I wrote many such tools for the Galaxy-P project that just wouldn't work with current IUC best practices - but they were still important tools.

Second - my recommendation would be to write workflow tests. There doesn't really exist documentation per se at this point but the Galaxy Format 2 workflow definitions I presented at the GCC 2016 can include data manager steps and can have subsequent steps depend on the data manager step. I'd work through the details of that, build the workflow test case (again presented but not really documented well), and then establish some sort of planemo test pattern where ``planemo test <tool>`` would look for workflows tests next to the tool and execute them if present.

It isn't easy yet and it isn't ready to go - but that is how I would proceed.

**Comment by mvdbeek** [comment]
@jmchilton that is what I was thinking as well. 
True workflow testing would be absolutely amazing and well worth some dev time. 
And if we reach that point it wouldn't be too far to pass a workflow file to colleagues that don't know / don't want to know galaxy and say `planemo run_workflow workflow.yml` and you get a nice result. Not sure if that's the scope of planemo, but in principle I think that could be quite attractive.

I may add that for such tools maybe we can have some tests that are closer to unit tests. The idea would then that you just test that the correct parameters are generated, but you don't actually run it.

**Comment by bgruening** [comment]
Running workflows tests is really needed. But I don't think this is the only answer to this problem. What we could do here, and what is probably easier to do, is to introduce something like a prefetch-test command. A test can specify a URL that is downloaded by planemo/Galaxy before running the tests and the content is extracted into local test-data.

Such a functionality is really needed for all tools with bigger test data and would solve @gregvonkuster as well, imho.

**Comment by martenson** [comment]
@gregvonkuster @jmchilton @mvdbeek @bgruening Your discussion is well hidden here, would you mind creating an issue for it instead?

**Comment by gregvonkuster** [comment]
@martenson I've added an issue for this here https://github.com/galaxyproject/galaxy/issues/3714 Thanks!

**Pull request merged**
