### PR TITLE
add new tabular file formats cns,cnr and cnn to datatypes_conf.xml.sample file as they are neaded for cnvkit galaxy tools

### PR DESCRIPTION
**Pull request by khaled196**
add new tabular file formats cns, cnr and cnn to datatypes_conf.xml.sample file as they are needed for cnvkit galaxy tools

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Are those well defined? If they are intended to be used to limit dataset selection to valid options maybe a metadata filter works?

**Comment by bernt-matthias** [comment]
Otherwise some description or link to docs on the datatype might be good to have.

**Review by mvdbeek — APPROVED** [review]
Thank you!

**Comment by mvdbeek** [comment]
> If they are intended to be used to limit dataset selection to valid options maybe a metadata filter works?

IMO that is not a good alternative, metadata filters are much more heavyweight from a tool dev and performance view. this really is why we have this simple subclass mechanism.

**Comment by mvdbeek** [comment]
> link to docs on the datatype might be good to have.

this would be nice if you have something we can point to.

**Comment by khaled196** [comment]
> > link to docs on the datatype might be good to have.
> 
> this would be nice if you have something we can point to.

Thank you, @bernt-matthias @mvdbeek, for looking into this,

Those file formats are tabular outputs or inputs for the tool collection CNVkit, which I wrapped earlier. I was creating a tutorial to show how to use this tool, so I gave it a run on Galaxy. 
At first, when I wrapped the tools for the first time, I called them tabular in XML script, but now I think about calling them by their type to make it easier to call the output files for another related tool. 

 [cns file](https://github.com/ELIXIR-UK-DaSH/tools-iuc/blob/cnvkit/tools/cnvkit/test-data/sample.cns)
 [cnr file](https://github.com/ELIXIR-UK-DaSH/tools-iuc/blob/cnvkit/tools/cnvkit/test-data/sample.cnr)
 [cnn file](https://github.com/ELIXIR-UK-DaSH/tools-iuc/blob/cnvkit/tools/cnvkit/test-data/reference.cnn)

**Comment by jdavcs** [comment]
Thank you, @khaled196! 
(test failures unrelated)
@bernt-matthias: I think the comment above with the provided links is sufficient documentation in this case. If we need something more substantial than that, we can have a separate PR.

**Pull request merged**
