### PR TITLE
Present unavailable options to logged-out users

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Relevant issues: #11372 #10418

This PR presents anonymous users (logged-out users) the options they would have when logging in / registering as disabled options, with a mouse-over prompt to log-in, in the History and Toolbox Panels.

This serves as an incentive to sign-up, acts as an additional indicator of being logged-out, and reduces confusion of why some options are missing.

image
image
image
image

This PR also reorders the history options panel.
The new order can be thought of in four sections:
* Multiview
* Job/Tool - Relevant Options (resume all, structure view)
* File Operations (Copy, Delete, Export, ...)
* Permission Options (Share, Permissions, Private)

image

I attempted to roughly order these sections by frequency of use, while maintaining blocks of available options when logged out, so the menu doesn't feel too scattered to anonymous users. Feedback is welcome.

This PR also standardizes the terminology of "log in"

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
I like this a lot.  We probably need to standardize terminology here a bit though.  I think 'login' works as a noun or adjective, but not as a verb, where it should be 'log in'.  So "Log in to view favorites", instead of "Login to view favorites", etc.

Might be a couple other places already in the app to fix, too, like:
image

**Comment by ElectronicBlueberry** [comment]
@dannon I renamed all verb occurrences of "login" I could find to "log in"

**Review by dannon — APPROVED** [review]
Thanks!

**Comment by davelopez** [comment]
Thank you @ElectronicBlueberry it looks great!

(The failing tests are unrelated)

**Pull request merged**
