### PR TITLE
Fix Library Folder performance

### LINKED ISSUE #10538: data libraries interface speed regression
After the rewrite in 20.09 the DLs interface feels much slower. One of the reasons could be that there is a lot of additional javascript calls in unnecessary places illustrated below.

Galaxy
Galaxy

Galaxy___UMSA___Data_Libraries_and_New_Issue_·_galaxyproject_galaxy

### PR DESCRIPTION
**Pull request by OlegZharkov**
Do not reload entire component, when user moves into another folder. 

fixes https://github.com/galaxyproject/galaxy/issues/10538

### CODE REVIEW

**Comment by OlegZharkov** [comment]
hmmm, GHA doesn't work for drafts anymore?

**Comment by mvdbeek** [comment]
This looks like a rather big change to 20.09, I would prefer if you would target dev with this.

**Comment by OlegZharkov** [comment]
> This looks like a rather big change to 20.09, I would prefer if you would target dev with this.

Wait, I can remove pagination

**Review by mvdbeek — APPROVED** [review]
Very nice!

**Comment by OlegZharkov** [comment]
> Very nice!

@mvdbeek thanks :)

**Comment by martenson** [comment]
Thanks for taking care of this @OlegZharkov !

**Comment by OlegZharkov** [comment]
> Thanks for taking care of this @OlegZharkov !

Thanks for reporting! I should've done this way from the beginning.

**Pull request merged**
