### PR TITLE
Remove twill functional tests we don't actively run.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this.

**Comment by martenson** [comment]
@jmchilton could you please defend a bit the position of removing these against the position of actively running them?

**Comment by jmchilton** [comment]
Argument in 4 parts
- They do not work.
- If they did work, they won't ever work with JavaScript
- Time put into setting up CI would be better spent on the Casper tests
- Time put into fixing the test would be better spent writing new one that could potentially work with JavaScript.

**Comment by martenson** [comment]
splendid

**Pull request merged**
