### PR TITLE
changed exit code and regex parsing

### PR DESCRIPTION
**Pull request by bernt-matthias**
... Just a little idea that I just had ...

I thought it could be handy to be able to combine exit codes and regexes that are derived from 
the command tag and those from the stdio tag. 

For instance one could make use of the detect_errors == "aggressive" regexes and add tool specific 
regexes via the stdio tag. 

Haven't thought about compatibility. Also documentation is missing and probably some other pieces of code (tests) need updates.

A possible alternative would be to add a property/element to the stdio tag that allows to load predefined sets of regexes and exit codes. I'm thinking of 
- language specific errors (e.g. the annoying zoo of JAVA oom messages)
- user defined error mesages (that may depend on the local computing platform)

Maybe this would be even nicer.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@bernt-matthias there are some unit tests in https://github.com/galaxyproject/galaxy/blob/84597a12356aaa5b5d59ba95c30691739fed2300/test/unit/tools/test_parsing.py#L187, I think it would be straightforward to extend those.

**Comment by bernt-matthias** [comment]
@mvdbeek thanks for the link. Wanted to see if this change would is considered useful and acceptable by the community .. or if the possible alternative I discussed at the end might be even better.

**Comment by mvdbeek** [comment]
This is definitely useful and reduces clutter by allowing the combination of stdio regex and `detect_errors="exit_code"`, I don't think there are any downsides. 

I am not convinced about the suggested alternatives though, it seems to me that a grid manager is supposed to kill the OOM jobs, resulting in a sigkill. If for some reason galaxy doesn't register the exit code we can work on this, but it definitely does for torque, which I am using and I suspect (but have no proof) that this is the case for the majority of job runners.

The example we discussed in https://github.com/galaxyproject/tools-iuc/pull/2141#discussion_r230790163 in that light is not exactly what I would expect to happen IRL. Once I have a little more time I can set up an integration test case for kubernetes or the CLI runners.

In essence I don't think we should tailor tools to whatever weird thing the DRM is doing. If needed we can override things in the job runner code.

**Comment by bernt-matthias** [comment]
ping @jmchilton @natefoo @bgruening

**Comment by bernt-matthias** [comment]
Does somebody know something about the failing selenium test?

**Comment by mvdbeek** [comment]
You can ignore that, it's been fixed in another PR

**Comment by jmchilton** [comment]
Totally solid enhancement, thanks a bunch! More or less agree with @mvdbeek's review on future directions note with the caveat that "language specific errors" makes sense to me as a good idea even if "computing platform errors" should be avoided.

**Pull request merged**
