### PR TITLE
Minor fixes for new locales, rebuild of client.

### PR DESCRIPTION
**Pull request by dannon**
(this fixes the client build)

### CODE REVIEW

**Comment by nsoranzo** [comment]
@dannon Any clue about the failed qunit tests?

**Comment by dannon** [comment]
Yeah, pushing a fix as soon as the client build finishes.

**Comment by dannon** [comment]
(side note, it'd be great to 'make client' with a standard environment prior to running tests -- that's why this wasn't caught in the initial PR)

**Comment by anuprulez** [comment]
Can this PR for locales fix be merged as the checks are successful? Thanks :)

**Comment by bgruening** [comment]
Thanks @dannon!

**Pull request merged**
