### PR TITLE
Notifications on job completion

### PR DESCRIPTION
**Pull request by astrovsky01**
This PR adds push notifications on job completion. The toggle for the setting is in user preferences.

Next steps:
* User select which kinds of jobs (on data upload or not?)
* User preferences based on workflows (every tool, or only on completion of final tool?)

### CODE REVIEW

**Comment by astrovsky01** [comment]
Currently will notify on any job completion, including cancellation.

**Comment by astrovsky01** [comment]
Updates:
* Altered message on job pass/fail
* No message on job cancellation
* Red icon for job failure
** Red icon will also be used for browser tab updates as referenced in https://github.com/galaxyproject/galaxy/issues/8399

**Comment by astrovsky01** [comment]
Next task: return the tab to original favicon and remove job completion number on page view.

**Comment by astrovsky01** [comment]
Tab now resets on viewing the page, also linked the tab icon's ability to change with the user's notification preference.

ezgif com-video-to-gif (1)

**Comment by bernt-matthias** [comment]
Like the general idea, but I could imagine that popup notifications might become annoying if you run a workflow (which have their own email notification system). In particular if many jobs are processed in parallel.

Maybe it's an idea to disable it for jobs in workflows? Or replace the pop-up with a more decent signal, eg make the tab greenish/reddish if there are new finished/failed jobs. 

In general I like the idea of a notification system. Eg a checkbox next to the execute button to get mail notification could be really handy for long running tools.

**Comment by astrovsky01** [comment]
@bernt-matthias the next idea is to make it so push notifications are a job-specific thing, where a user would have a check box next to the execute button to request a notification on update. In that case, the notification would remain on screen until the user specifically dismisses it. The tab's update will be for all jobs running, so a number completed will show in the tab's text if completed while tabbed away. The color change of the favicon will also only be on notification request.

**Comment by bernt-matthias** [comment]
Agreed. But I'm thinking more of jobs that run for days or weeks. Then I would find a mail handy. Otherwise the user would need to repeatedly connect to galaxy to see the job status. 


Instead of a checkbox I could also imagine a user specific option specifying a time span for jobs to send an email upon completion.

**Comment by astrovsky01** [comment]
I was thinking of using SLURM functionalitu for the email, and I like the time span idea.

**Comment by astrovsky01** [comment]
I really like that idea (maybe a slider on the preferences?) I think SLURM has that functionality, but not all HPCs we run it all do, so I'll check out alternatives!

**Comment by dannon** [comment]
@astrovsky01 @bernt-matthias Check out the workflow editor's "email notification" action, which sends an email when a particular step in the workflow completes.  It's implemented as a post job action and the same functionality could be used for individual jobs without much extra work.

**Comment by bernt-matthias** [comment]
@dannon great idea

**Comment by astrovsky01** [comment]
@dannon I was looking at the account verification email, but that would probably work better. Thanks!

**Comment by dannon** [comment]
@astrovsky01 Yep, it should.  There's already a hook to execute PJAs on job completion, so you'll just need to add a way to *create* new PJAs on individual job submission.

**Comment by bgruening** [comment]
@astrovsky01 this might be also interesting and related. Would love to get this in as well: https://github.com/galaxyproject/galaxy/pull/5439

**Comment by dannon** [comment]
@galaxybot test this

**Pull request merged**
