### PR TITLE
[16.01] Fix handling of time in fluent logger

### PR DESCRIPTION
**Pull request by dannon**
This makes the fluent logger functional.

### CODE REVIEW

**Comment by nsoranzo** [comment]
I kind of prefer the fix in the first commit, but that would need a small change to the `log()` method call in another file (`lib/galaxy/webapps/galaxy/api/metrics.py`).

**Comment by dannon** [comment]
@nsoranzo Yeah, I preferred it too, you can see my internal struggle in the commit messages ;)

I'll probably go back to that approach, since usage of this seems pretty low and it'd be easy enough to change the signatures.

**Comment by carlfeberhard** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

I guess we need another +1 before merging since the PR was modified after @carlfeberhard's approval.

**Comment by davebx** [comment]
Looks pretty straightforward to me, and making things actually work is always worth a +1. For what it's worth, the current solution looks better to me, rather than using `time` as a regular variable.

**Comment by blankenberg** [comment]
+1

**Pull request merged**
