### PR TITLE
WIP: Add ability to assert metadata properties on input dataset parameters.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by bgruening** [comment]
This is cool! What is needed to get this in?
A validator to only show tabular files with 3 columns, or columns with a specific name ... very nice!

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by bernt-matthias** [comment]
Yeah, lets revive this ..

**Comment by jmchilton** [comment]
@bernt-matthias I'm going to close this out - but feel free to rebase and reopen if you're still interested!

**Pull request closed without merging**
