### PR TITLE
Chira visualization for Chimeras

### PR DESCRIPTION
**Pull request by OlegZharkov**
Squashed commits from https://github.com/usegalaxy-eu/galaxy/pull/59 https://github.com/usegalaxy-eu/galaxy/pull/60 https://github.com/usegalaxy-eu/galaxy/pull/61

PR introduces Chira visualization:
https://galaxyproject.eu/posts/2020/03/24/rna-interactome/

image

image

image

Thanks a lot to original author @anuprulez !

### CODE REVIEW

**Comment by OlegZharkov** [comment]
I just realized, that I didn't provide HOWTO.

For those, who wants to try it out, please upload [this example dataset](https://files.gitter.im/anuprulez/F78H/Galaxy9--Galaxy12--sqlite_db_of_data_11-.sqlite-.chira.sqlite) and select ```chira.sqlite``` as datatype. Then it would be a regular visualization procedure 
image

Working example is already deployed on [usegalaxy.eu](https://usegalaxy.eu/visualizations)

**Comment by dannon** [comment]
Thanks!  Works well for me.

**Review by dannon — APPROVED** [review]

**Comment by OlegZharkov** [comment]
Thanks @dannon!

**Comment by anuprulez** [comment]
Thanks @dannon @OlegZharkov 
Ping @pavanvidem

**Pull request merged**
