### PR TITLE
Update against the latest changes in galaxy-lib

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Can we elaborate on these changes?

Changes to galaxyproject/galaxy-lib don't undergo the same sort of review that galaxyproject/galaxy generally does, and a more useful description here would help me out a lot.

**Comment by jmchilton** [comment]
Reviewing these I believe none of these should affect a modality Galaxy the core project runs in - it is modifications for downstream projects that consume this code as libraries.

The relevant galaxy-lib PRs are:
- Improved linting for planemo https://github.com/galaxyproject/galaxy-lib/pull/44
- Allow Global Conda installs for planemo https://github.com/galaxyproject/galaxy-lib/pull/41 and https://github.com/galaxyproject/galaxy-lib/pull/43
- Mulled testing improvements thanks to Marius https://github.com/galaxyproject/galaxy-lib/pull/39
- Implement quiet option to fix bug in planemo https://github.com/galaxyproject/galaxy-lib/pull/45

**Comment by dannon** [comment]
@jmchilton Thanks, that's exactly what I'm looking for.

**Comment by jmchilton** [comment]
@dannon I will in the future include a summary like this when submitting these update PR against dev. Sorry for the lack of context.

**Comment by dannon** [comment]
Awesome, much appreciated.

**Pull request merged**
