### PR TITLE
Add JupyTool, user-configurable interactive Jupyter-based tool.

### PR DESCRIPTION
**Pull request by blankenberg**
Uses existing quay.io/bgruening/docker-jupyter-notebook:ie2 image. 

- You can specify any number of user-defined inputs using the repeat input, providing `name` value, selecting the type of input, and then providing values.
- You can make the JupyTool reusable in a workflow, by allowing the user to specify input values for the defined input blocks.
- Inputs can be accessed by `name` from the automatically provided `GALAXY_INPUTS` dictionary.
- Outputs can be written automatically to the user's history by writing to the `outputs` directory for one individual file or to the `outputs/collection` directory for multiple files.
- Using collection tools, you can parse out the individual elements from the collection, as needed.

image

Screenshot from 2022-03-23 16-09-37

Screenshot from 2022-03-23 16-12-00

Screenshot from 2022-03-23 16-12-40

### CODE REVIEW

**Comment by bgruening** [comment]
@blankenberg I think this should replace the original one. It's a great, overdue enhancement!

**Comment by mvdbeek** [comment]
@blankenberg very cool enhancement. Are there any todo's before we can merge this ?

**Comment by bgruening** [comment]
Can we merge this into the jupyter one? There is no need to keep both, isn't it?

**Comment by dannon** [comment]
@bgruening I don't know of a good reason to keep both; I don't have a preference about the naming here if it should be 'jupytool' or just the next iteration of Galaxy's Jupyter IT

**Comment by mvdbeek** [comment]
@blankenberg I've edited the tool id to match the original tool id, so users can switch between versions. If that's OK with you can you take this out of draft ?

**Pull request merged**
