### PR TITLE
[23.0] Fix tool recommendations shown in a d3 js tree

### PR DESCRIPTION
**Pull request by anuprulez**
Fixes the d3 js part of tool recommendation in issue: https://github.com/galaxyproject/galaxy/issues/15723

### CODE REVIEW

**Comment by anuprulez** [comment]
Fixed comments based on https://github.com/usegalaxy-eu/galaxy/pull/153

**Comment by anuprulez** [comment]
Should I open this PR against the `dev` branch?

**Review by martenson — APPROVED** [review]

**Comment by martenson** [comment]
@anuprulez looks good, and is already deployed on EU, right?

**Comment by anuprulez** [comment]
Thank you @martenson for merging. Yes, it was already deployed on the EU.

**Pull request merged**
