### PR TITLE
[15.10] Fixes for dataset 'cleanup'/association linking when extracting workflows from a history.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: ... ... but tests would be nice :smile:.

**Comment by jmchilton** [comment]
This is a bug fix that has been open for 5 days, will someone else please :+1: this.

**Comment by carlfeberhard** [comment]
I'm not sure you're counting votes right, galaxybot, but +1, too.

**Comment by jmchilton** [comment]
Thanks Carl, also @galaxybot is correct I forgot about the special @jmchilton rule where I get to vote as much as I would like and they all count.

**Pull request merged**
