### PR TITLE
Interactive Tours

### PR DESCRIPTION
**Pull request by dannon**
Interactive tours branch that @bgruening and I have been tinkering with.  It has 'bugs' as discussed on IRC that we'll fix this week, but we'd like to get the feature in 16.01 (so, merged before freeze).

Creating the PR now, but the first bug should be fixed shortly -- merging with dev (the masthead tweaks from just a few commits ago) seems to have broken the display of tours.

More documentation forthcoming -- bit of a rush to get this into 16.01 prior to freeze right now.

### CODE REVIEW

**Comment by bgruening** [comment]
Obviously, looks good to me! If no one else merges this wonderful feature I will do this as first thing in the morning.
Thanks a bunch @dannon!

**Comment by martenson** [comment]
@bgruening The last thing I want to do is slow tours down but as @dannon pointed out this does not work yet (`Galaxy.app.display(new Tours.ToursView());` gives `TypeError`) so I wouldn't be too quick on the merge before fix.
Thanks for the work guys! Looking forward to this.

**Comment by jmchilton** [comment]
I've opened a PR https://github.com/dannon/galaxy/pull/8 with modifications to the backend.

**Comment by dannon** [comment]
@martenson Yep, that was broken upon merging w/ dev (worked prior to branch merge) and the new menu.js and I'm looking at it now.

**Comment by dannon** [comment]
#1424 Should fix the bug preventing this from displaying correctly, will merge in once that's merged.

**Comment by jmchilton** [comment]
I don't think this should be merged until the deployment configuration issues brought up in https://github.com/dannon/galaxy/pull/8 are worked through.

**Comment by jmchilton** [comment]
Just to clarify, none of my critiques in https://github.com/dannon/galaxy/pull/8 - which were presented as a pull request (work done and ready to be merged, with tests) and not as mere comments on a pull request - are personal. I have a long record of supporting both .yml as _THE_ correct extension for YAML files and supporting Galaxy configuration options that simplify deployment by not forcing deployers to modify things in GALAXY_ROOT. Here is the evidence of each:

.yml files:
- [.planemo.yml](https://github.com/galaxyproject/planemo/blob/master/docs/.planemo.yml)
- [.shed.yml](https://github.com/galaxyproject/tools-devteam/commit/325ecbf3f764bfff8051551659677c2f4d2262a7)
- [app.yml](https://github.com/galaxyproject/pulsar/blob/master/pulsar/main.py#L4) in Pulsar.
- [tool.yml](https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/simple_constructs.yml)

Not forcing Galaxy deployers to modify directories maintained by Galaxy:
- [Bitbucket PR 204](https://bitbucket.org/galaxy/galaxy-central/pull-requests/204/random-plugin-modifications/diff)
- tool_path resolution on config files https://github.com/galaxyproject/galaxy/commit/3d9da261d1dcbad2414d1edc2f25fbdab0cb1bc3
- Fixing datatypes so they don't have to modify registry.py https://github.com/galaxyproject/galaxy/commit/ce54045b20996584f1b83a1966d4f526f3f4fdf2
- Reworking Docker container to leave a pristine Galaxy https://github.com/bgruening/docker-galaxy-stable/issues/6

**Comment by martenson** [comment]
:+1: 

I will merge this once mergeable. Thank you all.

**Comment by dannon** [comment]
Don't merge yet, I'm fixing one more issue w/ pre|post-click, and then will resolve merge conflicts.

**Comment by jmchilton** [comment]
Thanks for the merge @dannon, :+1: from me. Good work!

**Comment by dannon** [comment]
Basic UI tour takes advantage of identifiers no longer in teh masthead post-merge w/ dev, pending fix.

**Comment by guerler** [comment]
@dannon Im on it. Edit: https://github.com/galaxyproject/galaxy/compare/dev...guerler:fix_ids_000.

**Comment by bgruening** [comment]
This is working fine for me now. The basic functionality is working and we can improve the tour during the next days. I will work on this one (https://gist.github.com/bgruening/22b4eaee875e63165b2e) and create a documentation PR asap.

Thanks you guys, you rock! All of you!

ping @jennaj! This is a huge win for Galaxy training in general.

**Comment by natefoo** [comment]
This is great! Thanks all!

**Comment by bgruening** [comment]
If anyone wants to help during the next release we have a follow-up issue here: https://github.com/galaxyproject/galaxy/issues/1423

**Pull request merged**
