### PR TITLE
repack bundled libs

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by jmchilton** [comment]
This staled - so I guess it has been fixed in dev?

**Comment by martenson** [comment]
@jmchilton This is still not fixed for me. I rebased.

**Comment by jmchilton** [comment]
Your file has a git merge problem statement in it I think - unless I'm reading it wrong.

https://raw.githubusercontent.com/martenson/galaxy/357522a7786db8b9ad37894d842e16d44314001d/static/scripts/bundled/libs.bundled.js.map

It starts with:

```
<<<<<<< HEAD
```

**Comment by martenson** [comment]
stupid rebase

**Pull request closed without merging**
