### PR TITLE
[16.07] Unused import cleanup for #2856

### PR DESCRIPTION
**Pull request by dannon**
Had a pending PR open https://github.com/natefoo/galaxy/pull/6 for #2856, but it was merged before this could be merged in.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: - sorry about that @dannon.

**Comment by martenson** [comment]
hard to notice :/

**Comment by dannon** [comment]
@martenson Sorry, thought it'd be obvious enough.  I'll try to leave an extra comment indicating pending PRs from now on.

**Comment by martenson** [comment]
~~@dannon obvious how?~~ ah I see what you mean

**Comment by dannon** [comment]
@martenson Not a big deal at all -- it obviously wasn't obvious enough :)

I'll leave a comment from now on for pending changes.  Thanks for the merge.

**Pull request merged**
