### PR TITLE
Added data density-aware zoom selection for requesting bigwig data for trackster via byte-range.

### PR DESCRIPTION
**Pull request by msauria**
I have limited data calls to between 1000-4000 data points per canvas and created a promise chain for resolving which zoom level ultimately returns data. This should fix issue #3854 without breaking for high-density data.

### CODE REVIEW

**Comment by martenson** [comment]
Hi @msauria - sorry for taking this long, we have just had a discussion about this PR yesterday and we concluded there is not a person (in the meeting) that understands/uses trackster enough to review this. 

Hopefully we will do better for the 18.01.

**Comment by jxtx** [comment]
@jgoecks should be able to review this. He's the only one who has touched this specific code.

**Comment by martenson** [comment]
The review of this should probably follow the merge of https://github.com/galaxyproject/galaxy/pull/5261

Therefore I am pushing it to 18.05.

**Comment by dannon** [comment]
After I wrap up #5261, I'll also have touched this code and should be able to get this reviewed/merged.

**Comment by jxtx** [comment]
Thank you!

**Pull request closed without merging**
