### PR TITLE
Fixes #13542: Click targets for folder explorer seem off

### LINKED ISSUE #13542: Click targets for folder explorer seem off
Reported by @elichad in GAT

> UI bug - the folder links don't work right in the tool input dataset selector. Wherever the cursor changes to the hand, clicking doesn't open the folder - you have to click outside the link in the padding or the other columns

out

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
As mentioned in #13542 , clicking on the div surrounding the folder name in the folder explorer wouldn't do anything. I made tiny changes to the DataDialogueTable.vue component by removing the @click.stop functionality. Now, clicking anywhere on the row opens up the folder.

https://user-images.githubusercontent.com/78516064/159378014-8a463a27-1d50-414a-b815-db64bfc5f773.mov

I would appreciate if this could be tested by another user because my folder was empty and I want to make sure that clicking on folders that aren't empty works as well.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by ahmedhamidawan** [comment]
@dannon I would appreciate if you could check this out if it works for populated Data Libraries!

**Comment by mvdbeek** [comment]
Here's some more context on why it was the way it was: https://github.com/galaxyproject/galaxy/pull/12641
Does that still work ? Can you select a folder for exporting now ?

**Comment by ahmedhamidawan** [comment]
> Here's some more context on why it was the way it was: #12641 Does that still work ? Can you select a folder for exporting now ? I think that's why the selenium integration test is failing.

I can't seem to figure how to get the Data Libraries folder populated (on my local app). Also, I don't see the "Choose remote files" button on my local app:
image

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thank you @ahmedhamidawan!

**Pull request merged**
