### PR TITLE
[16.01] Update help text rST note/warning/error box styling for change in div class from toolHelpBody to ui-form-help.

### PR DESCRIPTION
**Pull request by natefoo**
Fixes the regression pointed out by @bgruening in #685

### CODE REVIEW

**Comment by martenson** [comment]
@natefoo changes in base.less should only result in additional changes in base.css so I assume that the additional JS files are forgotten client build

**Comment by natefoo** [comment]
I was wondering about that as well, but it looks like these specific files update more frequently (look at their histories). If they're pulled from external sources that would explain it? Sorry, I don't know enough about the client code to comment intelligently here.

**Comment by dannon** [comment]
Differing dependency versions have been known to pack/bundle the files slightly differently in the past, and that could explain it as well.

**Comment by martenson** [comment]
@dannon but not functionally differently I hope?

**Comment by dannon** [comment]
@martenson Yay github email delay :)

No, they still both seemed to work fine, just slightly different packing algorithms.

**Pull request merged**
