### PR TITLE
Rebuild to provide new localization.

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by dannon** [comment]
#4080 needed to build the client to use the changes within.

**Comment by nsoranzo** [comment]
`/admin` interface is broken without a `make client` for me on `dev` branch.

**Comment by dannon** [comment]
@nsoranzo Check out #4079; I noticed this too and issued #4078 to fix it, but I think something else is going on with the cache busting that's causing this (current -dev tip works fine for me)

**Comment by martenson** [comment]
@nsoranzo after rebuild do you have any local changes?

**Comment by nsoranzo** [comment]
@martenson Yes, `static/scripts/bundled/libs.bundled.js` and `static/scripts/bundled/libs.bundled.js.map`

**Comment by dannon** [comment]
@nsoranzo Those can build differently depending on nodejs versions, etc., so it isn't necessarily indicative of substantive changes.  If you reset the rebuild, does it fail again?

**Comment by nsoranzo** [comment]
That's true, I think the real problem is that we are not tracking in git these files: `static/scripts/bundled/admin.bundled.js` and `static/scripts/bundled/admin.bundled.js.map`

If you delete them (or use a fresh git clone), you can reproduce the almost blank page under `/admin`.

This should be fixed by https://github.com/galaxyproject/galaxy/pull/4088 .

**Comment by martenson** [comment]
@nsoranzo that is a good point, they were probably gitignored before

**Comment by dannon** [comment]
(to close the loop on this one, all of /static/scripts/bundled is .gitignored because there are extra bundling artifacts in there that we don't care/need to track -- new bundles within the folder need to be manually added to git, after which they'll track normally)

**Pull request merged**
