### PR TITLE
Add blib datatype for Mass Spectrometry spectral library

### PR DESCRIPTION
**Pull request by jj-umn**
blib is a SQlite schema for a Mass Spectrometry spectral library.  
https://skyline.ms/project/home/software/BiblioSpec/begin.view?

### CODE REVIEW

**Comment by jmchilton** [comment]
@jj-umn Thanks a bunch, looks great to me! Any chance you can build a tiny example file and include it in ``lib/galaxy/datatypes/test/``, we've really increased our test coverage for sniffing during the last release cycle. If you have a tiny example it is really easy to add a test case for the sniffing order and such (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/sniff.py#L464).

**Comment by jj-umn** [comment]
@jmchilton  Thanks John.

**Comment by jj-umn** [comment]
@jmchilton  Does the failing selenium test have anything to do with the datatype that was added?

**Comment by jmchilton** [comment]
Those are almost certainly unrelated @jj-umn - don't worry about them. Sorry about that.

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
@jj-umn I made some small changes to the PR, I hope that is okay. One the columns you were checking for for instance wasn't present in the test data you supplied.

**Comment by jj-umn** [comment]
@jmchilton Thanks.

**Pull request merged**
