### PR TITLE
Allow '.' and '_' for public names

### LINKED ISSUE #2593: Galaxy user ids too restrictive for LDAP integration
With our server, user authentication is provided by an external LDAP server. While things work from an architectural point of view, there are some restrictions on galaxy user IDs that are quite problematic with existing LDAP servers. For example user ids in LDAP can have underscores, but not on Galaxy.

This can be an issue with pluging galaxy to existing Single-Sign On infrastructure

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix #2593 (but we may want to allow even more characters in the future).
Also:
- standardise error messages
- validate public name when auto-registering a user

### CODE REVIEW

**Comment by bgruening** [comment]
Oh yes, very useful!

**Comment by martenson** [comment]
@nsoranzo Please see https://github.com/nsoranzo/galaxy/pull/4

**Comment by nsoranzo** [comment]
@martenson Thanks, merged!

**Review by martenson — APPROVED** [review]

**Comment by martenson** [comment]
Thank you for improving this @nsoranzo !

**Pull request merged**
