### PR TITLE
Add download option to workflow editor menu

### PR DESCRIPTION
**Pull request by anuprulez**
The PR adds a "download" workflow option to the dropdown menu (on the right) of the workflow editor screen. It fixes the feature request in https://github.com/galaxyproject/galaxy/issues/6566.

download_opt

### CODE REVIEW

**Comment by anuprulez** [comment]
@bgruening If someone tries to download an unsaved workflow, the browser already gives a warning whether to "stay" on page or "leave". A user should save the workflow and then download.

**Comment by hexylena** [comment]
@anuprulez would the button maybe be more user-friendly as "save and download" then?

**Comment by anuprulez** [comment]
@erasche To have such a feature, a new API needs to be registered which should call two APIs (to update a workflow and then download). Every time a user clicks on "save and download", both the APIs are called (which may be unnecessary if the workflow is already saved). Due to these reasons, I kept the "download" feature separate.

**Comment by hexylena** [comment]
@anuprulez couldn't you just call the existing save API from the client, and then when that returns successfully, redirect to the download API? I did not imagine that it would need a new server side API.

And an unnecessary save call is never harmful. But if you were worried about that, isn't there a dirty flag on the workflow, or similar that could let you tell if a save was needed?

Edit: just call `save_current_workflow` before redirecting? That even includes the check for an unnecessary save.

**Comment by dannon** [comment]
I'm actually in favor of two explicitly separate actions here, leaving this feature as currently implemented by @anuprulez, but maybe I'm in the minority?

To me, this way is simpler, and on the off chance a user has edited but not saved, the existing 'warn before doing anything' paradigm is totally fine IMO.

(I was going to merge as-is, but intended to dig into the need for the empty action function)

**Comment by hexylena** [comment]
No, makes sense, small minority won't have saved. Works for me. Let's merge :)

**Comment by dannon** [comment]
Sounds good, then!  @anuprulez Do you remember why you needed to have the empty action function?  That seemed like something that we should be able to simplify.

**Comment by anuprulez** [comment]
@dannon I needed to create an `anchor` tag in the dropdown menu and in the file `/galaxy/client/galaxy/scripts/ui/popupmenu.js` requires an `action` attribute (`line 47`). Otherwise, it throws console error.

**Comment by dannon** [comment]
@anuprulez Hrmm.  I thought action was intended to be optional, but anyway, I can look into that later.  Thanks for the contribution!

**Pull request merged**
