### PR TITLE
[16.04] Backport of tabular display line duplication fix.

### PR DESCRIPTION
**Pull request by dannon**
xref #2527

### CODE REVIEW

**Comment by nsoranzo** [comment]
Do not merge yet, I'm seeing something strange when testing.

**Comment by dannon** [comment]
@nsoranzo Can you elaborate?

**Comment by nsoranzo** [comment]
Sure, I was double-checking. Try to change:

```
display_chunk_size = 6553
```

in `config/galaxy.ini`, restart Galaxy, upload the `test.txt` dataset, click on the eye icon. Everything seems fine, but if you scroll to the end of the file (which should be line 1000), funny things happen (more lines appear, starting from 4 or 10...).

This did not happen before the fix.

**Comment by dannon** [comment]
@nsoranzo Worse than that, with a very small display_chunk_size it actually displays many _more_ duplicate lines.

**Comment by dannon** [comment]
WIPing this and working on a better fix, which we'll merge forward and fix the almost-there fix in -dev.

**Pull request closed without merging**
