### PR TITLE
[18.05] Pages - fixes for encoded ids in the database

### PR DESCRIPTION
**Pull request by dannon**
xref #6617, when we updated the secret for usegalaxy.org, we broke all the internal hashed identifiers that pages were saving.

This PR converts the pages to read both encoded and unencoded ids out of the database (for backwards compatibility), display to the user using encoded ids (both in view and edit modes), but always save using unencoded ids.  It also actually validates page contents on save, now, including items.

It additionally includes a script for admins to fix 'mangled' pages, where the secret has been changed and the page hashes are no longer valid.  It uses beautifulsoup to quickly rewrite identifiers in an encoded form.

### CODE REVIEW

**Comment by dannon** [comment]
Looks like the contents pruning was too aggressive and we actually need some of that placeholder stuff for good editor display.  Reworking a tad.

**Comment by dannon** [comment]
I added a bonus bugfix for some busted javascript that was causing embed insertions like this, which failed to correctly pull in the item names:

image

**Comment by dannon** [comment]
@natefoo Were you able to test this?

**Comment by natefoo** [comment]
Tested and run on Main, thanks @dannon!

**Comment by martenson** [comment]
post mortem 👍

**Pull request merged**
