### PR TITLE
Improve workflow layout algorithm

### PR DESCRIPTION
**Pull request by hexylena**
I wrote [a rubbish workflow plotter](https://github.com/hexylena/galaxy-workflow-plotter) forever ago and someone asked about it today. I was annoyed I never added a better layout algorithm and so I went looking today for a better algorithm while my blast runs.

I found this: https://github.com/kieler/elkjs 

> [ELK] is a layer-based layout algorithm that is particularly suited for node-link diagrams with an inherent direction and ports (explicit attachment points on a node's border). It is based on the ideas originally introduced by Sugiyama et al.

So I tried my hand at replacing Galaxy's layout with it. What do y'all think? Personally I like it a lot better.

**Default**
image

**ELK**
image

**Default**
image

detail image (:musical_note: Where did you come from, where did you go? :notes:)

image

**ELK**

image

Some admittedly imperfect things there, but, I'd argue an improvement. No longer noodle soup :ramen:!

For reference, the manual layout i'd been using, which only looks good on that version of galaxy due to the very different noodle bezier parameters.

image

- ~~Current bug: noodles bug out until you manually touch nodes. Dunno how to fix that sorry.~~ JK, old variable. Thanks CircleCI for catching it.
- This (somewhat intentionally) throws out the retaining of any user control over layout that the original considered.

### CODE REVIEW

**Comment by dannon** [comment]
Ahh.  My one concern is the size of the library.  Let me see what I can do here to make it load async?

**Comment by hexylena** [comment]
Sure, that makes sense.

**Comment by dannon** [comment]
Should be a deferred load on demand now, thanks @hexylena.

**Comment by hexylena** [comment]
The layout can probably be improved a bit by knowledge of where the noodle attaches, for what it's worth. [Example from their docs](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=ports%2FportConstraints). Not sure how to translate that to JS yet,

Added two other options I found in one of their demos and that helps a bit too:

Before | After 6974ede8d6
--- | --- 
image | image

**Comment by hexylena** [comment]
After 3d9e0555d9, I've added connections via 'ports' which have some specific positioning on the node (east/west/etc). This can probably be further refined but honestly it looks good enough to me now, using the most important features of the library for layout.

Before | After 
--- | ---
image | image

I'm quite happy with this, so, ready from my side :shipit:

**Comment by dannon** [comment]
@hexylena This is great; the layout is much, jmuch better.  Thanks again.

**Comment by hexylena** [comment]
Cheers @dannon! Appreciate the review once again. I look forward to using it!

**Comment by guerler** [comment]
So much better! Thank you @hexylena

**Pull request merged**
