### PR TITLE
[23.0] Add 2 indexes to WorkflowRequest* tables on the workflow_invocation_id field

### PR DESCRIPTION
**Pull request by jdavcs**
Ref #15728

Add 2 indexes (model changes + migrations); add utilities for index migrations

Names match those added earlier to main. If index exists, migration step will be skipped with a log message; 
downgrade step will be skipped if index does not exist.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by dannon** [comment]
@jdavcs We also need to update what the `23.0` upgrade/downgrade tag is, right?

**Comment by jdavcs** [comment]
> @jdavcs We also need to update what the `23.0` upgrade/downgrade tag is, right?

Definitely, thanks! Adding a commit now.

**Comment by martenson** [comment]
> We also need to update what the 23.0 upgrade/downgrade tag is, right?

would be rad to have a CI check on that

**Review by martenson — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thanks @jdavcs!

**Pull request merged**
