### PR TITLE
Remove IPython IE, which was replaced by Jupyter IE.

### PR DESCRIPTION
**Pull request by bgruening**
This PR will remove the IPython IE which can be replaced by the new Jupyter IE that was introduced in #1400. Jupyter offers all features of IPython and more and does not change the user experience.

To completely migrate from IPython to Jupyter the Galaxy admin still needs do migrate the config file.

I'm fine with not removing IPython in the next version and just deprecate it and ship both IE's for 16.01.

### CODE REVIEW

**Comment by hexylena** [comment]
:+1: to deprecate and remove in 16.04. Might be a nasty surprise otherwise? Really wish we knew how many people were using this in production...

**Comment by martenson** [comment]
iPython is not in the release, right? I would not bother deprecating if it was only in dev.

**Comment by bgruening** [comment]
It is since half a year or so :)

**Comment by martenson** [comment]
@bgruening wow it seems iPython was in 15.01... 
:+1: to deprecate then

**Comment by jmchilton** [comment]
Merged - 16.01 has been branched.

**Pull request merged**
