### PR TITLE
Swapping from svgfig to svgwrite

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by dannon** [comment]
WIP, refactoring and style tweaks inc.  And wheels (so this will not currently pass any tests, I wouldn't guess -- though it'll work fine enough locally if you install svgwrite).

**Comment by bgruening** [comment]
LGTM, @dannon you changed the title but it is still labelled as WIP.

**Comment by dannon** [comment]
@bgruening Yeah, I was still going to tweak the style a little bit more today.  Give me a few minutes, then I'll actually take it out of WIP.

**Comment by dannon** [comment]
@bgruening Now it's ready, the fonts and sizing match the original behavior.

**Comment by bgruening** [comment]
:+1:

**Pull request merged**
