### PR TITLE
Fix bug with detection of Jenkins BUILD_NUMBER.

### PR DESCRIPTION
**Pull request by jmchilton**
Introduced in 74c4ac3662257776a08bc724a2919547856da819.

Sorry @martenson

### CODE REVIEW

**Comment by martenson** [comment]
@jmchilton The selenium tests still seem to not create the xunit XML file. (see https://jenkins.galaxyproject.org/job/selenium/ws/ )

**Comment by jmchilton** [comment]
It would have but the container that should start Galaxy didn't start. I'm not sure what the problem is but I'm pretty sure all selenium tests are broken - not this PR.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
pull request builder is broken, bot won't trigger it, details: https://github.com/jenkinsci/ghprb-plugin/issues/441

**Pull request closed without merging**
