### PR TITLE
Relocate the external set_metadata script to the galaxy_utils package.

### PR DESCRIPTION
**Pull request by natefoo**
A temporary script in the job working directory will be created to
import and call it (trusting that `$PYTHONPATH` in a job script is
always set to `galaxy/lib`). This is so the auto-detect button can defer
command line generation until job preparation time for the case that
handlers and web processes run from different paths.

Related Trello card: https://trello.com/c/v2eCOYZi

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/F4Il0Vdd) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/7.patch) for testing.

**Comment by natefoo** [comment]
This is incomplete, there are absolute paths in the params that I didn't consider. Do not merge.

**Comment by natefoo** [comment]
Okay, this is ready for review, if anyone's interested.

**Comment by jmchilton** [comment]
Why `galaxy_utils.metadata` - seems an odd place for the package?

**Comment by natefoo** [comment]
Yeah, I waffled on that quite a bit. It avoids circular import troubles with a few of the other places I tried. Any suggestions on a better place?

**Comment by jmchilton** [comment]
Does `lib/galaxy/metadata` cause circular import problems? Seems like `galaxy_utils` is more for bioinformatics helpers than core infrastructure stuff to me. If it needs to be outside of `galaxy` maybe create a `galaxy_scripts/metadata` or something?

Couple more comments:
- I think you are still importing `from galaxy.objectstore import build_object_store_from_config` in the set_metadata - but it looks like maybe you do not need it anymore.
- I think this will cause running jobs to fail during the upgrade to this version right? Should we keep the old set_metadata.sh in place for one release and then kill it - or will the other changes prevent it from running?

**Comment by natefoo** [comment]
Great points, I have updated with your suggestions. I believe simply restoring the old versions should prevent any failure - by the time a job is running, its set_metadata arguments have already been generated, which should be valid with the old set_metadata.py (and that version does not depend on any of the modified code).

**Comment by jmchilton** [comment]
Awesome - now we just need to remember to delete those files someday :).

:+1:

**Comment by natefoo** [comment]
No worries, I have the best memory for these sorts of things... for everything really...

_cough_

**Comment by dannon** [comment]
+1

**Pull request merged**
