### PR TITLE
[21.01] galaxy.webapps.tool_shed to webapp.tool_shed

### PR DESCRIPTION
**Pull request by almahmoud**
This might not actually be a good change, but came across it randomly and thought I'd PR so someone who might know better can decide, just in case these three were omitted by mistake from the refactoring in  https://github.com/galaxyproject/galaxy/pull/8949

### CODE REVIEW

**Comment by mvdbeek** [comment]
Thanks @almahmoud!

**Comment by jmchilton** [comment]
I mean - I think this is incorrect. We shouldn't be modifying those test files that are supposed to be used to test what linting older versions of those configs looked like. It is probably fine though.

**Comment by mvdbeek** [comment]
At the minimum we want to update `lib/galaxy/config/config_manage.py` though, right ? And if the unit tests don't fail I think this is fine ?

**Comment by jmchilton** [comment]
I think you're right that that part does need to be changed.

**Pull request merged**
