### PR TITLE
[16.07] Fix: Remove the old HubAssembly class

### PR DESCRIPTION
**Pull request by remimarenco**
Hi!

I was looking at the datatype `TrackHub` which has been integrated into the core (thanks again!), and it seems we have added the old class (`HubAssembly`) with the new class (`UCSCTrackHub`).

This PR to fix it ;)

### CODE REVIEW

**Comment by nsoranzo** [comment]
This was added in #2348 and moved to `lib/galaxy/datatypes/tracks.py` in #2646.

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by martenson** [comment]
Is this a bug or just dead code?

**Comment by dannon** [comment]
Do we expect that anyone actually has huba datatypes that we need to worry about this breaking?

**Comment by remimarenco** [comment]
@nsoranzo arg sorry for the confusion. I have changed the name `hubAssembly` / `huba` to `UCSCTrackHub` / `trackhub` per @bgruening [comment](https://github.com/galaxyproject/galaxy/pull/2348#discussion-diff-62968663), in [this commit](https://github.com/galaxyproject/galaxy/pull/2348/commits/e0ffb2d8d021248019c3a9a9d9e18ca0cdd9cf26) while the review of #2646. I understand it was a bit difficult to read, not sure how I should have notify the commit was related to the comment.

@martenson Just dead code :). It is not used anywhere, and will never be because the HubArchiveCreator tool which outputs `huba` extension has never been released in `toolshed`.

I guess it also answers to @dannon at the same time ^^. Nobody has this datatype, `huba` is the old extension name of my HubArchiveCreator tool output :D.

**Comment by nsoranzo** [comment]
:+1:

**Pull request merged**
