### PR TITLE
[23.2] Associate default history with session when creating a new session

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes the missing history panel when opening Galaxy the first time as an anon user.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — APPROVED** [review]
Thank you! It works well now!

**Comment by nsoranzo** [comment]
@mvdbeek I think this broke the ToolShed tests on 23.2 .

**Comment by mvdbeek** [comment]
Yep, definitely does

**Comment by davelopez** [comment]
Sorry my bad, I thought it was the flakiness that we have been seeing recently on Toolshed tests I didn't properly check because I thought this wouldn't affect Toolshed stuff at all. I will be more careful next time.

**Pull request merged**
