### PR TITLE
Update galaxy.tool_util.cwl for latest changes in CWL branch.

### PR DESCRIPTION
**Pull request by jmchilton**
Needed for https://github.com/galaxyproject/planemo/pull/978 but we may want to pull out just the changes to schema.py and backport them to 20.01.

### CODE REVIEW

**Comment by jmchilton** [comment]
Breaks something else in Planemo:

```
Exception [tool_proxy must be called with non-None uuid]
```

Tightened up how tools are loaded to try to ensure tools were loaded in consistent ways during the last CWL push and this broke non-internal Galaxy applications it seems.

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
The failure of unit test `test_validate_simple_config` is due to the ruamel.yaml update to 0.16.0, whose changelog says: "duplicate keys are now an error when working with the old API as well".

**Comment by jmchilton** [comment]
https://github.com/common-workflow-language/cwltool/commit/762532d42f3ab1dc172494d780ec7764c554b2e1

Looks like we could pin it to something in the 0.15 branch line for now? How does that sound?

**Comment by nsoranzo** [comment]
> [common-workflow-language/cwltool@762532d](https://github.com/common-workflow-language/cwltool/commit/762532d42f3ab1dc172494d780ec7764c554b2e1)
> 
> Looks like we could pin it to something in the 0.15 branch line for now? How does that sound?

@jmchilton I think it would be better to workaround the duplicate-key weirdness of uWSGI's YAML files in `_validate()` in `lib/galaxy/config/config_manage.py` . I can try to implement that if you agree.

**Comment by jmchilton** [comment]
@nsoranzo sounds good to me if you have an idea how to do that.

**Comment by nsoranzo** [comment]
All green! What do you guys think of how I've addressed the YAML issue?

**Comment by mvdbeek** [comment]
That looks very good to me, thanks @nsoranzo!

**Comment by jmchilton** [comment]
Thanks @nsoranzo - looks great!

**Comment by jmchilton** [comment]
Any appetite for backporting this to 20.01 for Planemo and such or should we just start cutting 20.5-dev packages?

**Comment by mvdbeek** [comment]
Yes, please, I'll open a PR

**Comment by jmchilton** [comment]
Awesome - that will bring us closer to a stable release of galaxy-tool-util and such. But I'll publish dev packages when this is merged into 20.01.

**Comment by nsoranzo** [comment]
Thanks both! I still had a couple of unsubmitted review comments, I'll move them to #9210.

**Comment by jmchilton** [comment]
```
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/toolbox/base.py", line 663, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/toolbox/base.py", line 855, in load_tool
    tool = self.create_tool(config_file=config_file, tool_shed_repository=tool_shed_repository, guid=guid, **kwds)
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/__init__.py", line 284, in create_tool
    raise e
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/__init__.py", line 279, in create_tool
    tool_location_fetcher=self.tool_location_fetcher,
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/parser/factory.py", line 39, in get_tool_source
    as_dict = ordered_load(f)
  File "/Users/john/workspace/galaxy/lib/galaxy/util/yaml_util.py", line 70, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 400, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/Users/john/workspace/galaxy/lib/galaxy/util/yaml_util.py", line 50, in construct_mapping
    value = loader.construct_object(value_node, deep=deep)
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/Users/john/workspace/galaxy/lib/galaxy/util/yaml_util.py", line 50, in construct_mapping
    value = loader.construct_object(value_node, deep=deep)
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/Users/john/workspace/galaxy/lib/galaxy/util/yaml_util.py", line 50, in construct_mapping
    value = loader.construct_object(value_node, deep=deep)
  File "/Users/john/workspace/galaxy/.venv/lib/python3.6/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/Users/john/workspace/galaxy/lib/galaxy/util/yaml_util.py", line 54, in construct_mapping
    "found duplicated key (%s)" % key, key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "/Users/john/workspace/galaxy/test/functional/tools/simple_constructs.yml", line 105, column 9
found duplicated key (has_line)
  in "/Users/john/workspace/galaxy/test/functional/tools/simple_constructs.yml", line 107, column 9
```

I guess my own fault really though...

**Pull request merged**
