### PR TITLE
Merge ``Target`` class with ``CondaTarget``

### PR DESCRIPTION
**Pull request by nsoranzo**
Refactoring commits extracted from my current work to fix mulled container testing.

Also:
- Many type annotation improvements
- Misc type-related fixes
- Reuse `skip_unless_executable` test decorator for conda and singularity

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Can we finish this before https://github.com/galaxyproject/galaxy/pull/15614 (just need to remove the last commit).

**Review by jmchilton — APPROVED** [review]
Tricky, stressful refactoring but it looks really solid to me. Nice work @nsoranzo - thank you.

**Comment by bernt-matthias** [comment]
> Can we finish this before https://github.com/galaxyproject/galaxy/pull/15614

What I meant is to merge https://github.com/galaxyproject/galaxy/pull/15614 1st

**Comment by nsoranzo** [comment]
@bernt-matthias Gosh, I missed all the great type annotation work in your PR, so much duplicated work, sorry about that! But it looks like we mostly annotated the same way at least.
I think your PR would be easier to review if merge this first (same reason why I split this out from my incoming PR), what about if I take care of the rebasing?

**Comment by bernt-matthias** [comment]
> I think your PR would be easier to review if merge this first (same reason why I split this out from my incoming PR), what about if I take care of the rebasing?

Completely fine with me. Let me just remove the unrelated commits from my PR ..

**Comment by bernt-matthias** [comment]
> Completely fine with me. Let me just remove the unrelated commits from my PR ..

Done

**Pull request merged**
