### PR TITLE
Fix zip file download

### PR DESCRIPTION
**Pull request by qiagu**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by mvdbeek** [comment]
This breaks the zip download, as you can see in the tests (ignore `test_pause_outputs_with_deleted_inputs`, that one is flaky). Can you describe what you're trying to fix ?

**Comment by qiagu** [comment]
I didn't touch the `upstream_mod_zip` yet. The `StremingResponse` seems to only take an Iterator object, not a generator. Both `yield`s have to be removed from the response method to return the right class. To make a test case, try to download an html or composite dataset (zero bytes are downloaded from current dev branch).

**Comment by mvdbeek** [comment]
We have a lot of these tests, and they are breaking with this change. Here's the documentation for StreamingResponse: https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse.

**Comment by qiagu** [comment]
Interesting. Maybe I need to clean up my python environment. The change fixed the download issue on my laptop though.

**Comment by qiagu** [comment]
I have more insight. The `StreamingResponse` either takes `AsyncIterable` or `Iterator`. Another potential fix might be adding `async` before the response method.
https://github.com/encode/starlette/blob/master/starlette/responses.py#L227-L230

**Comment by mvdbeek** [comment]
Can you maybe first describe what exactly the problem is? How do i reproduce what you're seeing? Both composite datasets and html files are being downloaded correctly for me, and in the tests.

**Comment by qiagu** [comment]
That's strange. I tried reinstalling my Galaxy. The dev branch gives me the same issue: the size of downloaded zip file is zero bytes.

**Pull request closed without merging**
