### PR TITLE
Extend the list of attributes to be reported.

### PR DESCRIPTION
**Pull request by VJalili**
In addition to attributes reported, report `create_time` for `collection` view, and `create_time`, `ratings`, `reviews`,  and `reviewers` for `element` view.

### CODE REVIEW

**Comment by nsoranzo** [comment]
> In addition to attributes reported, report `create_time` for `collection` view, and `create_time`, `ratings`, `reviews`, and `reviewers` for `element` view.

Just a warning: I wouldn't expect many ratings/reviews, that's an almost unused feature of the Tool Shed.

**Comment by VJalili** [comment]
True, though that view is supposed to return as much info as possible for a given entry. If a value for those fields are set, we can use them, otherwise, we can just ignore them.

**Comment by dannon** [comment]
Unrelated test failures, going to go ahead and merge this as it seems reasonable to expose these attributes via the API.

**Comment by VJalili** [comment]
Thanks for merging this.

**Pull request merged**
