### PR TITLE
added route api/datasets/show_params to get a dict containing paramet…

### PR DESCRIPTION
**Pull request by ratzeni**
…ers used for the job associated with an HDA

### CODE REVIEW

**Comment by martenson** [comment]
You are describing the endpoint as "parameters used for the job" which implies to me that the info should sit somewhere under `/api/jobs/{job_id}`

**Comment by ratzeni** [comment]
Well, but /api/datasets/show_params is based from dataset/show_params which is implemented on datasets controller

**Comment by martenson** [comment]
I think API does not need to reflect internal code architecture - in my opinion it should reflect the logical structure of objects based on REST. 
Comments? @jmchilton @blankenberg @carlfeberhard

**Comment by nsoranzo** [comment]
Ciao Rossano!
Please fix the lint errors detailed at https://travis-ci.org/galaxyproject/galaxy/builds/67849555 .

**Comment by dannon** [comment]
I would think the dataset summary dict should contain the source job identifier, which you could then query to see the parameters.

**Comment by ratzeni** [comment]
Ciao Nicola,
I fixed the error. Thank you,

**Comment by carlfeberhard** [comment]
-1

This has a lot of problems (improper http errors, code duplication, strange code pathing, string errors in new code), but the main problem (and the one we'd have to support in a backwards compatible way) is the one Martin pointed out: this needs to be RESTful as a noun under jobs:  /api/jobs/{job_id}/params

**Comment by martenson** [comment]
Unless there is some followup from @ratzeni I will close this PR soon.

**Comment by ratzeni** [comment]
@martenson i'm agree with you: close this PR. :)

**Pull request closed without merging**
