### PR TITLE
[15.10] Test timeout fixes?

### PR DESCRIPTION
**Pull request by jmchilton**
Continuation of work started by @nsoranzo here 92a152d89c507168a6085cc34acfa13566b6eda9. In addition to increasing the max timeout it will now print the timeout in the assertion error so we can see if it is being overridden and attempt to adjust timeouts too small.

See also #1061.

### CODE REVIEW

**Comment by nsoranzo** [comment]
So, one target seems to be https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_workflow_extraction.py#L360

**Comment by jmchilton** [comment]
@nsoranzo got it with 177f73f.

**Comment by martenson** [comment]
thanks guys

**Comment by nsoranzo** [comment]
I shouldn't have merged this yet, requires another +1, sorry. Can anyone else approve it or should I revert it?

**Comment by jmchilton** [comment]
Don't revert, 15.10 hasn't been released I don't think it needs two but we can treat @martenson's comment as a +1 :).

**Comment by martenson** [comment]
:+1:  (and yeah, 15.10 is unreleased, we are safe)

**Pull request merged**
