### PR TITLE
Client structure refactoring for packaging

### PR DESCRIPTION
**Pull request by dannon**
This work standardizes client package structure in preparation for breaking a few things apart and working towards real packaging.  ~Client unit tests work(ed, before I broke them again removing all the styles from qunit tests, intentionally) and the app does function, but I'm sure something else is going to break.~

~And I need to~
- [x] look for more busted symlinks
- [x] fix static-safe mappings
- [x] swap remaining 2 qunit tests to not require styles

New client structure: 

```
.
├── docs
│   ├── README.md
│   ├── bootstrap.md
│   ├── galaxy-buttons.md
│   ├── ...
├── node_modules
│   ├── ....  all the node modules
├── src
│   ├── app
│   ├── assets
│   │   └── images
│   ├── components
│   ├── config
│   ├── entry
│   ├── layout
│   ├── legacy
│   ├── libs
│   ├── mvc
│   ├── nls
│   ├── onload
│   ├── reports
│   ├── store
│   ├── style
│   ├── toolshed
│   ├── ui
│   ├── utils
│   ├── viz
│   ├── bundleEntries.js
│   ├── galaxy.interactive_environments.js
│   ├── galaxy.library.js
│   ├── galaxy.pages.js
│   ├── i18n.js
│   ├── polyfills.js
│   └── style.js
├── tests
│   ├── karma
│   ├── mocha
│   └── qunit
├── Dockerfile
├── README.md
├── gulpfile.js
├── package.json
├── prettier.config.js
├── styleguide.config.js
├── webpack.config.js
└── yarn.lock
```

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
This is awesome! I can't fully speak to the correctness of this all, but this works for me and I imagine this is going to get stale quickly, so 👍.

**Comment by dannon** [comment]
> This is awesome! I can't fully speak to the correctness of this all, but this works for me and I imagine this is going to get stale quickly, so 👍.

And it immediately goes stale :)  Thanks for taking a look and testing it.  I'll give it a little bit this morning for folks to look, then I'll rebase and get it in.

**Comment by bgruening** [comment]
Builds, runs and overall looks good :+1:

**Review by bgruening — APPROVED** [review]

**Review by OlegZharkov — APPROVED** [review]

**Comment by dannon** [comment]
Thanks for the quick reviews @bgruening @OlegZharkov @mvdbeek

**Pull request merged**
