### PR TITLE
[WIP] Rewrite Admin-DataTables with Vue

### PR DESCRIPTION
**Pull request by anatskiy**
I couldn't wait until #4978 is merged, so I already rewrote `Admin-DataTables` with Vue. This PR replaces Mako templates which are used to render Data tables:

screen shot 2017-11-10 at 23 57 43

### Issues

- Backbone Router doesn't work as expected. The following history leads to an empty page: `Data tables -> Data types -> Browser's "Back" button`. I guess the function `show_data_tables()` from `./client/galaxy/scripts/apps/admin.js` is not triggered at all.

### Questions

1. I assume many client's parts will be rewritten with Vue in the nearest future. How should we organize Vue components now? There will be many of them.

2. I counted 3 different table styles in the admin section. Would it be a good idea to unify the look?

   - The one above.
   - Data tables -> Data manager
    screen shot 2017-11-11 at 00 06 45
    - User Api Keys
    screen shot 2017-11-11 at 00 09 13

P.S. Thanks @dannon for the Vue integration and @bgruening for overall help!

### CODE REVIEW

**Comment by dannon** [comment]
@anatskiy Hah, nice!  Yeah, it's a lot of fun to work with, I'll check this out ASAP.  I'm going to work vuex for state management into the other PR prior to merge, and can look into the router stuff, too.

Yes, for sure the table styles should be standardized and use the same framework, across the entire application (not just the admin interface).  This is something @guerler has worked on already in his various Grid enhancements.

As an afterthought -- (and, don't get me wrong, this is definitely 100% awesome!), but it's worth keeping in mind that it might not be great to get the cart too far ahead of the horse in terms of translating everything right away.  I'm hoping to work out these kinks in the other branch, which this will have to be rebased against.

**Comment by dannon** [comment]
@anatskiy Mind if I cherrypick https://github.com/galaxyproject/galaxy/pull/4980/commits/75e8d53b517a0a0d26da46a13c8578e98f027d27 over to a new branch with a few updates, and get it merged in that way?

**Comment by anatskiy** [comment]
@dannon not at all! Do it :)

**Comment by dannon** [comment]
@anatskiy Awesome, thanks, will do!

**Pull request closed without merging**
