### PR TITLE
[PROCEDURES] Add Ahmed as a committer

### PR DESCRIPTION
**Pull request by dannon**
Ahmed has made many fantastic contributions since joining (https://github.com/galaxyproject/galaxy/pulls?page=1&q=is%3Apr+author%3Aahmedhamidawan), has done some great work especially on the UI/UX side while also making an impact on Galaxy's authentication handling and other backend code.

Quick to help others and communicate, proactively reaching out about design choices and issues, and fast to follow up in communication, he will be a valuable addition to the committers group.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by bgruening — APPROVED** [review]
:tada: :tada:

**Review by bernt-matthias — APPROVED** [review]

**Review by ElectronicBlueberry — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Review by nuwang — APPROVED** [review]

**Review by natefoo — APPROVED** [review]

**Review by blankenberg — APPROVED** [review]

**Review by guerler — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]
Awesome!

**Review by hexylena — APPROVED** [review]

**Review by davelopez — APPROVED** [review]
:100:

**Comment by ahmedhamidawan** [comment]
Thank you everyone, I feel honored to have become a part of the committers group!!! 😊 I have learned a lot from all of you (as well as everyone in the wider Galaxy community) since joining the team, and I look forward to contributing to the evolution and improvement of Galaxy as a platform! ❤️

**Pull request merged**
