### PR TITLE
Update david identifier types

### PR DESCRIPTION
**Pull request by pavanvidem**
David identifier types seem to be changed. Some of them are no more available on david web server.

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by bgruening** [comment]
I guess this can be applied to 16.01 as well.

**Comment by jmchilton** [comment]
Thanks @pavanvidem!

**Comment by bgruening** [comment]
@jmchilton can we cherry-pick this to 16.01 as well? This tool produces wrong results with a few options.

**Comment by jmchilton** [comment]
@bgruening Done https://github.com/galaxyproject/galaxy/commit/bf4e736c3ca8e129ff8c75f8261c08f303c76080

**Pull request merged**
