### PR TITLE
Remove workflow search from activity bar

### PR DESCRIPTION
**Pull request by itisAliRH**
Requires: #16607. This PR removes the workflow search from the activity bar.
xref: https://github.com/galaxyproject/galaxy/pull/16607#issuecomment-1943978784

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
What I was saying in my comment is that the search bar conflicts with the search on page. In no way do I want the workflow activity to be dropped.

**Comment by itisAliRH** [comment]
> What I was saying in my comment is that the search bar conflicts with the search in the center panel. In no way do I want the workflow activity to be dropped.

@mvdbeek Me neither, but the workflow activity without a search bar is used less and duplicates the masthead workflow.
However, #17289 I can implement this one and replace the search fields with favorite/recent workflows (using the `ActivityPanel`)

**Comment by mvdbeek** [comment]
I think it is wrong that all activity bar items need a side panel, this is insane. Also, the workflow activity did not have the side panel on 23.0 and that was perfectly fine. As commented, https://github.com/galaxyproject/galaxy/issues/17289 is not a good idea. Can you please, please, either fix the synchronization of the search or simply drop the search from the side panel.

**Review by mvdbeek — APPROVED** [review]
Thank you, that looks great!

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/actions/runs/7919456233/job/21623311924?pr=17479#step:11:2337 might be a relevant error ? I've triggered a rerun.

**Comment by itisAliRH** [comment]
@mvdbeek It passed successfully, thanks. I've cherrypicked this PR changes to the main one and will close it now

**Pull request closed without merging**
