### PR TITLE
Cytoscape bugfix for SIF files

### PR DESCRIPTION
**Pull request by anuprulez**
This PR includes a bug fix for SIF to JSON file conversion for Cytoscape charts plugin.

- Nodes are now correctly arranged according to SIF file specification

For the following SIF description:
```
nodeA xx nodeB
nodeB xx nodeC
nodeC xx nodeD
nodeD xx nodeA nodeB nodeC
nodeB xx nodeD
nodeZ
```

the resulting graph is:

271555ea-1ae9-11e7-801e-21c12f1b3c21

### CODE REVIEW

**Comment by dannon** [comment]
@anuprulez You should not need to do those dev merges like that, for what it's worth.  This looks much better, though.

**Comment by dannon** [comment]
+1, works well now.  Thanks for fixing it up @anuprulez.

**Comment by anuprulez** [comment]
@dannon I pushed my changes and then did the merge with dev. Should I do the other way?

**Comment by dannon** [comment]
@anuprulez Unless there's actually a conflict, there is no need to do either -- the only merge in many situations will be the one that happens when a committer merges this back *into* dev (like what happens when "merge pull request" is clicked).

Even if there *are* conflicts, as long as they're just build artifacts, those are also trivial to resolve by the committer at merge time.

**Comment by martenson** [comment]
Please watch milestone and label presence when merging. Or give @galaxybot a chance to catch that (he ignores closed issues).

**Pull request merged**
