### PR TITLE
Misc Admin TS Panel Fixes

### PR DESCRIPTION
**Pull request by dannon**
@davebx This fixes the navigation issues we were talking about, and adjusts some spacing in the repo information display titlebar where things were running together.

### CODE REVIEW

**Review by davebx — APPROVED** [review]
The code is cleaner, and everything works.

**Comment by davebx** [comment]
Thanks @dannon

**Comment by bgruening** [comment]
@davebx should be add some Selenium tests as well if this becomes the new default UI?

**Comment by davebx** [comment]
@bgruening absolutely, and my goal is definitely to make this good enough to be the new default

**Pull request merged**
