### PR TITLE
Downgrade some annoying warnings

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by dannon** [comment]
@erasche I'm not a tool author, but these *seem* like important things to fix that we'd want folks to be warned about.  How many tools are throwing these?

**Comment by hexylena** [comment]
@dannon they're important warnings that *tool authors* should receive. As a server admin I don't care since this information isn't actionable, we aren't going to go through the XML files on disc under shed-tools and make changes that might affect reproducibility.

I wish my sentry was online so I could send a screenshot but it's safe to say that every server reboot generates on the order of 500 messages for this. We have so many old tool versions installed where people made things we have now decided are "bad".

**Comment by jmchilton** [comment]
These things are broken and Galaxy has many different users and use cases. Running big server with tool shed install tools you don't want to touch is one common use case - but if someone is running a server with locally written tools or is doing development with Galaxy these warning might be more important. And some of this is not stuff that is easily caught with Planemo (ext for datatype not existing - that is a deployment issue not a tool author issue in some ways). Could we create a logger just for tool warnings that could be easily disabled by admins who don't want to see it?

**Comment by hexylena** [comment]
> locally written tools or is doing development with Galaxy these warning might be more important

Shouldn't we be pushing them to planemo lint stuff in this case?

> And some of this is not stuff that is easily caught with Planemo (ext for datatype not existing - that is a deployment issue not a tool author issue in some ways). 

this is a good point, I hadn't thought about that but you're right, planemo might not be able to catch that as easily.

> Could we create a logger just for tool warnings that could be easily disabled by admins who don't want to see it?

A special logger would be great.

**Comment by hexylena** [comment]
This is a pretty normal boot-up log for us: [log.txt](https://github.com/galaxyproject/galaxy/files/1927920/log.txt)

```
[hxr@mk:~]$ grep -c 'a when tag has not ' log.txt
112
[hxr@mk:~]$ grep -c 'Datatype class not found' log.txt
143
[hxr@mk:~]$ grep -c docutils -i log.txt
88
```

**Comment by martenson** [comment]
+1 for tool logger, probably enabled by default?

**Comment by hexylena** [comment]
Yeah, just another case of the datatype issue. I'm "stuck" with this message forever unless we downgrade these warnings, edit the old tools (changing repro), or have a separate logger. (We've reported this bug upstream, but apparently no one else is annoyed by this in the past 2+ years.)

I'd try and implement that but with new logging config I am not confident in my ability to do that.

```
galaxy.model WARNING 2018-04-23 10:27:17,172 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,172 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,225 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,226 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,226 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,227 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,228 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,228 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,285 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,286 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,286 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,286 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,286 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,287 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,340 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,341 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,341 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,341 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,342 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,342 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,394 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,395 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,395 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,395 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,395 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
galaxy.model WARNING 2018-04-23 10:27:17,396 [p:259211,w:3,m:0] [uWSGIWorker3Core2] Datatype class not found for extension 'fastqsangar'
```

**Comment by dannon** [comment]
Random wild thought here -- I think we should consider annotating the tool form itself with these warnings when rendering the tool.  @erasche's point is valid in the sense that the server admin might not be the one to fix it, or be burdened with tracking it down, though I'd say both the tool user and tool author need to know.  So maybe putting a (!) warning tags on the rendered tool panel redirects that pressure more correctly from admin->author to user->author?

**Comment by martenson** [comment]
I am pushing this back to 18.09 since there seems to be an ongoing decision making.

**Pull request closed without merging**
