### PR TITLE
Uninstall a tool by default (vs. deactivating it)

### PR DESCRIPTION
**Pull request by afgane**

### CODE REVIEW

**Comment by martenson** [comment]
I am fine with changing the default but we should make it more thorough and smooth than just flipping the switch.

**Comment by afgane** [comment]
What do you mean by _thorough and smooth_? Flipping the switch is equivalent to what I've seen every user do whenever using this feature.

**Comment by martenson** [comment]
@afgane sorry for the confusion, for some reason I thought you wanted to remove the deactivation feature completely (which I think I am fine with) - so I was referring to wording on the page, dead code etc. 

👍

**Comment by dannon** [comment]
+100 on swapping the default, +1 on removing the 'deactivation' feature entirely (after deprecation).

(the test failures are relevant, here, btw @afgane -- you'll want to update those or I can maybe help out with it tomorrow)

**Comment by afgane** [comment]
I didn't get far in adjusting the tests and probably won't make much progress in the coming days so feel free to jump in (but I'll be happy to get back to it).

**Comment by martenson** [comment]
I am not sure about the approach to failing tests taken here. Instead of rewriting deactivation tests to uninstallation tests (which we already had) shouldn't we just fix the deactivation tests so they test the proper behavior?

**Comment by afgane** [comment]
OK; not knowing what all is actually being tested I wasn't sure which path to take and I can’t get these tests to run locally so was basically testing the testing so just updated a few of them. I'll look at taking the other path.

**Comment by martenson** [comment]
@afgane I will help with this tomorrow

**Comment by afgane** [comment]
I'm going to need to help with getting these tests sorted out. When I run the following locally `sh ./run_tests.sh --toolshed test/shed_functional/functional/test_1020_install_repository_with_repository_dependencies.py:ToolWithRepositoryDependencies`, I get a number of errors like the following - but nothing that resembles the output from Jenkins: 
```
======================================================================
ERROR: Deactivate the emboss_datatypes repository without removing it from disk.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ea/projects/ppy/galaxy/gxy-my-fork/test/shed_functional/functional/test_1020_install_repository_with_repository_dependencies.py", line 121, in test_0025_deactivate_datatypes_repository
    self.deactivate_repository(installed_repository)
  File "/Users/ea/projects/ppy/galaxy/gxy-my-fork/test/shed_functional/base/twilltestcase.py", line 360, in deactivate_repository
    url = '/admin_toolshed/deactivate_or_uninstall_repository?id=%s' % self.security.encode_id(installed_repository.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

Further, it seems the `deactivate_repository` method should be doing the correct thing and _deactivate_ a tool: https://github.com/galaxyproject/galaxy/blob/dev/test/shed_functional/base/twilltestcase.py#L364
but that is not the case: https://jenkins.galaxyproject.org/job/docker-toolshed/8586/testReport/junit/shed_functional.functional.test_1020_install_repository_with_repository_dependencies/ToolWithRepositoryDependencies/test_0025_deactivate_datatypes_repository/

**Comment by martenson** [comment]
~~At least some of the deactivation tests seem to be broken even though they do not fail. I am looking into it more.~~

edit: They might be working after all, I think I fixed the PR now.

**Comment by afgane** [comment]
Thanks for working on this @martenson (although I am still confused as to why this makes a difference).

**Review by nsoranzo — APPROVED** [review]

**Comment by martenson** [comment]
@afgane I think this is because input type=checkbox does not send its value if it is not checked

**Pull request merged**
