### PR TITLE
Add missing file from #784

### PR DESCRIPTION
**Pull request by jmchilton**
Good catch :bird::eyes:!

### CODE REVIEW

**Comment by blankenberg** [comment]
+1

**Comment by dannon** [comment]
So the test passed without this file, or are these not run via jenkins?

**Comment by martenson** [comment]
@dannon jenkins does not run API tests

**Comment by dannon** [comment]
Hrmm.  Dunno why I was thinking it did.  How much work would it be to have it do so?

**Comment by martenson** [comment]
@dannon sorry I mixed jenkins and travis (damn foreign names) :)
Jenkins used to run API tests but it is in the middle of transition to dockerize things so it does not run currently.

**Comment by martenson** [comment]
I created a task for dockerless api test that should pass: https://jenkins.galaxyproject.org/job/G-API-dockerless/

**Pull request merged**
