### PR TITLE
Scratchbook tour

### PR DESCRIPTION
**Pull request by guerler**
This PR adds a Scratchbook tour, and identifiers for tool parameters and the upload settings popup. It also contains minor refactoring. The previously displayed todo list has been moved to #1423.

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome! I could use some of the new ID's also in my tour :)
I guess this is documentation and should target 16.01.

@guerler you can drag and drop in tours. You can upload data during a tour and you can drag and drop scratchbook windows around.

**Comment by martenson** [comment]
@bgruening This looks like a refactoring to me, it is probably fine to put it in 16.01 during freeze but I wouldn't start a habit of circumventing our own rules.

@guerler scratchbook tour hype! :100:

**Comment by guerler** [comment]
I agree with @martenson. I was not considering to place the tour into 16.01 unless people are in favor since it is not a bug fix and there are a few more things on the todo list.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Reveals a bug in the tour resuming approach: https://www.dropbox.com/s/sfle2ohydj5xmhf/Screenshot%202016-01-14%2009.35.59.png?dl=0

This contribution is solid though, merging, nice work Sam!

**Pull request merged**
