### PR TITLE
Fixed missing trackster navigation pane (issue #946)

### PR DESCRIPTION
**Pull request by msauria**

### CODE REVIEW

**Comment by guerler** [comment]
Is the packed version ('grunt style') up to date?

**Comment by msauria** [comment]
Yes.

**Comment by guerler** [comment]
Interesting. Can you check if the tool and the history panels in the Analyze view are scrollable for you?

**Comment by msauria** [comment]
The history is, the tool panel is not. However, moving the overflow trait down to the next style definition (#left > div.unified-panel-body, #right > div.unified-panel-body) seems to fix that issue.

**Comment by guerler** [comment]
Yeah that makes sense. This would look good with this fix. Thx.

**Comment by msauria** [comment]
Sam, is that an acceptable fix, and if so is there an easy way to update the pull request?

**Comment by martenson** [comment]
@msauria if you update dev branch in your fork this PR will update automatically

**Comment by guerler** [comment]
I think so. You should be able to just push changes using the same branch.

**Comment by guerler** [comment]
:+1: Thanks.

**Pull request merged**
