### PR TITLE
Managers, histories: when setting a history to 'current' update the u…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…pdate_time of the history

### CODE REVIEW

**Comment by nsoranzo** [comment]
Why? When I look at "Saved Histories" I find useful that "Last Updated" means I've done something with it, not just opened it.

**Comment by carlfeberhard** [comment]
Well - don't forget: you're a power user and 'done something with it' won't mean the same to me and you as it would to our target users. I'm guessing that they would be puzzled if they recently changed to a history but it is still displayed at the bottom of their history list.

I understand your thinking, tho.

**Comment by nsoranzo** [comment]
I'm still not convinced: a user may want to view a history finished in (let's say) March at multiple times, using the "Last Updated" as a search key, because she knows that the analysis was done in that month.

If you also want the possibility to sort by view time, then maybe a new field in the database is the way to go.

But in case this is approved as is, the mako template should be changed from "Last Updated" to "Last used" or something like that.

-1

**Comment by carlfeberhard** [comment]
I'm going to go ahead and close this since it seems to be at a stalemate and I think I may have a different way to accomplish the same thing.

I'd point out, though, that adding a new field in the database (such as 'last current') would also, as a side effect, change the updated time on the model, and would effectively be the same thing - just with a new, superfluous field.

**Pull request closed without merging**
