### PR TITLE
Revise masthead route handling and component

### PR DESCRIPTION
**Pull request by guerler**
Branched from #14505. This PR consolidates the client route format and handling for consistency. The route prefix of the Galaxy service is now consistently applied within the window helper instead of being distributed in different variations throughout the code. Urls/routes specified in configurations remain unmodified until a path is actually visited i.e. we can set and read these configurations without having to mutate them. Another change is that masthead tabs are now parsed as `props`. This allows us to re-use and modify the masthead component. The masthead component now emits an `open-url` event instead of depending on the window manager or the global `Galaxy` object functions (https://github.com/galaxyproject/galaxy/pull/14523/files#diff-0d8147049c7a36df3f47f0804414de65795612c7c0e9db6bd452a1bcdf1595e9R10).

This PR also performs some cleanup by removing the wrapper around the window manager when loading it in `App.vue`. Legacy mako-templates which mount the masthead like e.g. the current multi-history view, do not require the window manager. Instead they can evaluate the route request themselves (https://github.com/galaxyproject/galaxy/pull/14523/files#diff-62db9719011285bcd354c272c4da1db30d2af7edc67c344f60bcea25d5c50ae6R19).

Additionally, this PR suggests to determine the active/highlighted tab within the masthead component and without modifying the native router mechanisms and flow, by matching the current route to all routes listed within the masthead (https://github.com/galaxyproject/galaxy/pull/14523/files#diff-eeacf227ee15c2b83bf881aee335a1913f0876b6e7b89bdebc9ac9b53168c295R1).

Overall this PR is a step towards consistent route handling, a more modular masthead and less usage of the Galaxy object. 

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
I have very little vested interest in whether the active tabs work - I want a reactive masthead that I can build a minimal workflow runner interface around (https://github.com/galaxyproject/galaxy/pull/9030 / http://bit.ly/simplified-workflow-ui). This project has been will documented for years now, has many stakeholders, and I've taken multiple cracks at it - if you're unwilling to accept my attempts - can you please address the use case?

**Comment by guerler** [comment]
@jmchilton I see, and yes that use case can be addressed, it was not on my map before but now it is. This particular PR just handles the active tab highlighting.

**Review by itisAliRH — APPROVED** [review]

**Comment by guerler** [comment]
Failing integration test is unrelated.

**Comment by guerler** [comment]
Rebasing with dev.

**Comment by guerler** [comment]
@jmchilton thank you for pointing out that use case. Given this PR, a minimal/custom 'App' e.g. a minimal workflow runner interface would look like this here: https://github.com/guerler/galaxy/tree/custom_app/client/src/entry/mygalaxyui. The custom app would be individually bundled and could redirect from or to the analysis app. The custom app could mix-and-match routes and components (with associated risks).

**Comment by bgruening** [comment]
Works for me. During testing I found the following routes that are still doing a full page reload, this is unrelated to this PR but I thought to document it here:

* the HOME button
* workflow page -> create new
* data libraries
* "all workflows" in the tool panel
* everything that is linked on the user-preference page

**Review by bgruening — APPROVED** [review]

**Comment by guerler** [comment]
@bgruening thanks for the review and for reporting some of the pages which still require a reload. This PR is a prep to handle those cases too, and I intend to, step-by-step, switch some of these pages to avoid full page reloads like e.g. the preferences and the create forms etc., on the other hand, in order of priority, the "Home", "Admin" and also maybe even the "Library" link will keep reloading the page.

**Pull request merged**
