### PR TITLE
[19.05] Fix implicitly converted datasets unused when mapping over

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes https://github.com/galaxyproject/galaxy/issues/8801
Also sets `textable` when dataset needs to be converted, so users can enter columns up front.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I successfully tested trinity on this this branch. Hooray. Thanks a lot. 

Out of interest, why is this change targeting 19.05 and not dev?

**Review by jmchilton — APPROVED** [review]

**Comment by mvdbeek** [comment]
Damn, we don't have access to conda dependencies in the API tests. I'll see if I can get another conversion to work.

**Comment by mvdbeek** [comment]
> Out of interest, why is this change targeting 19.05 and not dev?

It fixes a bug ... one that never worked, but it was supposed to work. It's a relatively small change.

~~Turns out though that selecting columns from implicitly converted datasets also doesn't work.
For that I'll target against dev because it seems that more changes are necessary.~~

**Comment by jmchilton** [comment]
This is really elegant and awesome!

**Comment by bernt-matthias** [comment]
Thanks a lot. Again out of interest: how will this find its way to 19.09 and dev?

**Comment by mvdbeek** [comment]
We'll merge this forward ... this can either happen via PR (if you want to see the tests passing) or direct commit. Forward merges don't need approval (though I don't think we explicitly state this in https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst#handling-pull-requests).

**Comment by nsoranzo** [comment]
@mvdbeek It's in https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst#direct-commit-access : "A committer may only commit directly to the Galaxy repository... cherry-picking and/or merging of existing approved commits to other branches."

**Comment by bernt-matthias** [comment]
Superb. Will this happen automatically? If there is a chance to forget it, then I would volunteer to backport it.

**Comment by mvdbeek** [comment]
It's not automatic, but @nsoranzo probably did this, as there are no commits in 19.05 that are not in 19.09 and dev (https://github.com/galaxyproject/galaxy/compare/release_19.09...release_19.05?expand=1)

**Comment by bernt-matthias** [comment]
Thanks for the clarification, and for reminding me that this tool exists on the github page.

**Pull request merged**
