### PR TITLE
[15.10] Fix for getting shed_config_dict when an old/invalid shed_config_filename has been stored. 

### PR DESCRIPTION
**Pull request by blankenberg**
Fixes issue updating repositories that have had shed_tool_conf.xml changed since installation.

### CODE REVIEW

**Comment by martenson** [comment]
:+1: 
When does this happen? (the config naming inconsistency)

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
I would still like to know when this happens.

**Comment by blankenberg** [comment]
@martenson 
- Start Galaxy
- Install Tool from Toolshed
- Stop Galaxy
- Rename shed_tool_conf.xml and change config in galaxy.ini
- Start Galaxy (everything looks fine)
- Have update to tool repo occur w/o version bump. (Test with local toolshed)
- Try to update to latest. _Update Fails_
- Apply patch, update to latest. _Update works_

**Comment by martenson** [comment]
Thank you for the explanation @blankenberg , makes a lot of sense. I think we have had trouble with this when the configs moved (and 'solved' it by changing the database entries :)

**Pull request merged**
