### PR TITLE
Refactor Histories API controller

### PR DESCRIPTION
**Pull request by davelopez**
Preliminary refactorings in preparation for FastAPI migration of the Histories API.

For detailed information about the changes, please see each commit message.

## How to test the changes?
- [X] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by Nerdinacan** [comment]
Oooh

**Comment by Nerdinacan** [comment]
> > Oooh. Can't wait to see this. All I ask is that if you want to change the "near" endpoint which the beta history depends on, let me know so I can make sure it continues to work. Good luck, sir!
> 
> Thank you @Nerdinacan! This PR will contain only refactorings around the [api/histories.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/histories.py) file, then I will create another PR replacing the legacy endpoints with FastAPI endpoint, and later, I will try to do the same with the [history_contents.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/history_contents.py), so I will definitely ask you to have a look.
> I am struggling a bit to make everything 100% backward compatible, but hopefully, I won't break much of the existing API 😅

If you can't make it perfectly backwards compatible, all I ask is that you make it sane. I recognize that to make it "sane" you will probably have to change some functionality and I'm ready to switch the history around to jive. Just ping me any time.

**Comment by Nerdinacan** [comment]
@davelopez 
What do you think about the idea of versioning our api either in the route definition or as a content request header?

Ex: /api/histories/v2/contents?blah=blah
 
Or in the ajax request headers?

const headers =  { "Api-Version": 2.2323 };
axios.get(url, { headers });

**Comment by davelopez** [comment]
Yeah, I like the idea of supporting multiple versions of the API going forward. I guess using something like https://github.com/DeanWay/fastapi-versioning#examples will make sense or just mounting multiple FastApp applications. This will allow having also different versions of the interactive docs.
This is probably something interesting to discuss or maybe it was already discussed? Anyway, for now, I will try to maintain the compatibility as much as I can. I think most of the struggling is because of me being relatively new to Python and Galaxy in general :laughing:

**Comment by davelopez** [comment]
This first batch of refactorings around the histories API ([api/histories.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/histories.py)) is ready to review.

The bulk of the changes consist mostly of moving code from the legacy controller to the manager and create/use pydantic models for the parameters and simplify a bit the code.

There is a tiny bit of temporal duplication in a couple of methods (see *TODO* comments [here](https://github.com/galaxyproject/galaxy/pull/12195/files#diff-ba2f1698ef177fe3b44d3c46eaccd9dd343fae96d7d29d81bd6cbec90c253dc2)) but this will go away in the next refactorings for `api/history_contents.py` and `api/datasets.py` :sweat_smile:

**Comment by jmchilton** [comment]
I pushed 1286f2023b405988b9e634bba583034a7fc8c52e to reduce dependence on ``app``, feel free to strip it out if it doesn't work or if you hate it.

Overall though I think this amazing - it is a big component with a lot of dependencies and this is exactly how we should be handling them I think!

**Comment by davelopez** [comment]
Thank you @jmchilton well spotted!
Much better now!, the `app` dependency was definitely a YAGNI.

**Comment by jmchilton** [comment]
Wonderful - thanks!

**Pull request merged**
