### PR TITLE
[17.05] Hide error highlighting if user interacts with highlighted field

### LINKED ISSUE #4131: workflow parameters show red at run time even after entering an appropriate value
e.g. 
https://usegalaxy.org/u/bradlanghorst/w/test-param-validation 

image

The workflow can still be executed, so maybe this is not so urgent...

### PR DESCRIPTION
**Pull request by martenson**
ThisPR is a proper version of https://github.com/galaxyproject/galaxy/pull/4143 that I broke with wrong merge. Doing a separate PR for clarity. Sorry @guerler :(

Fixes #4131. If an input field is highlighted with an error message in run tool forms (regular and workflow) the error message persists until another execution attempt has been made, even if the user updates the field value. This can be confusing. This PR resolves this by removing the error message if the field value changes after highlighting. The value is revalidated upon execution.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
No worries. (:

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
