### PR TITLE
Download fixes

### PR DESCRIPTION
**Pull request by dannon**
Prevents 'download' directive from behaving badly on firefox.  (even a right click attempts to download the file, so you can't copy the url).

Adds the download URL to multifile download icons, allowing copy/paste.  We preventDefault, so the menu still works as expected, and the `void(0)` is unnecesssary.

### CODE REVIEW

**Comment by mvdbeek** [comment]
I confirm this fixes the issue, thanks @dannon, I'll just rebuild the client and merge.

**Comment by dannon** [comment]
Thanks @mvdbeek; I pushed a rebuild.  I saw a failing tool form selenium test, but I don't remember seeing it before.  Trying again locally to make sure it isn't related to this code.

Followup: Selenium test mentioned https://jenkins.galaxyproject.org/job/docker-selenium/665/ passes fine locally (and may on rerun, here -- seems a transient failure).

**Comment by mvdbeek** [comment]
Hmm,
```
"value": ["/", "t", "m", "p", "/", "6", "3", "6", "0", "9", "9", "b", "e", "1", "f", "c", "9", "0", "8", "9", "d", "3", "b", "a", "f", "a", "9", "d", "a", "6", "c", "9", "0", "3", "7", "c", "8", "/", "u", "p", "l", "o", "a", "d", "8", "9", "9", "1", "0", "3", "4", "4", "5", "7", "2", "9", "2", "3", "4", "1", "4", "1", "8", "f", "i", "l", "e", "/", "1", ".", "f", "a", "s", "t", "a"]}
```

that looks weird, like we're iterating on a string while we should be iterating on something else ... .
There were supposed to be screenshots for failing tests, right ?

**Comment by dannon** [comment]
Yeah, in https://jenkins.galaxyproject.org/job/docker-selenium/665/artifact/

(it looks like maybe from that screenshot it just didn't wait long enough)

**Comment by mvdbeek** [comment]
I guess it's a timeout https://jenkins.galaxyproject.org/job/docker-selenium/665/artifact/665-test-errors/test_run_data2017121410581513249081/stacktrace.txt

**Comment by mvdbeek** [comment]
Hmm, it failed again, and the history clearly has a hid. I wonder if it's checking the wrong history?
Is https://github.com/galaxyproject/galaxy/blob/dev/test/galaxy_selenium/navigates_galaxy.py#L207 really guaranteed to return the current history ?

**Comment by dannon** [comment]
I'd think we would have noticed that before now, but I guess it's possible?

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/5211
The problem isn't this PR.

**Comment by dannon** [comment]
Rebuilt again.

**Comment by bgruening** [comment]
works for me as well...

**Comment by dannon** [comment]
Thanks @bgruening!

**Pull request merged**
