### PR TITLE
Fix `test_callback_nonce_validation_with_bad_nonce` unit test

### PR DESCRIPTION
**Pull request by nsoranzo**
Broken in PR #13572.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
@nsoranzo Thanks, sorry I missed this one -- I should have looked more closely at the `test_galaxy_packages` failures instead of assuming it was noise.

**Review by dannon — APPROVED** [review]

**Comment by nsoranzo** [comment]
@dannon No worries! Unfortunately I had to add other 2 commits, rabbit holes!

**Comment by nsoranzo** [comment]
And another one for good measure: we have been caching a non-existing venv directory instead of the correct path since #12632 !

**Review by bgruening — APPROVED** [review]
Very nice! Good catch @nsoranzo!

**Pull request merged**
