### PR TITLE
Don't require admin user to list ``/api/tool_data``

### PR DESCRIPTION
**Pull request by jozh2008**
To use bioblend.galaxy.tool_data.get_data_tables(), I changed require_admin from Tru to False in tool_data.py for index.
Without this change I got the following error. 

- bioblend.ConnectionError: GET: Error 403: b'{"err_msg": "You must be an administrator to access this function.", "err_code":403006}', 0 attempts left: {"err_msg": "You must be an administrator to access this function.", "err_code":403006}
 
Additionally, I changed the self.assert_status_code_is(index_reponse,200) in the test_admin_only function in test_tool_data.py, because now you don't have to be an admin to use index.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [X] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thanks, that looks good!

**Comment by nsoranzo** [comment]
Can you please run `make update-client-api-schema` and commit the changes it makes to `client/src/api/schema/` ?

**Comment by tuncK** [comment]
Hi @jozh2008, thanks a lot for the speed.

Question: were you not originally suggesting we should relax the admin requirement on some other read-only functions? Such as:
https://github.com/galaxyproject/galaxy/blob/cf0c0afa3ee7fc2b687f604db1a0b87b2e37aaa2/lib/galaxy/webapps/galaxy/api/tool_data.py#L80
https://github.com/galaxyproject/galaxy/blob/cf0c0afa3ee7fc2b687f604db1a0b87b2e37aaa2/lib/galaxy/webapps/galaxy/api/tool_data.py#L100
https://github.com/galaxyproject/galaxy/blob/cf0c0afa3ee7fc2b687f604db1a0b87b2e37aaa2/lib/galaxy/webapps/galaxy/api/tool_data.py#L115

Or am I confusing things? (If so, you might need to again change the corresponding tests).

**Comment by nsoranzo** [comment]
@jozh2008 This is ready for merging, so let us know if you prefer to address @tuncK's suggestion here or in a separate PR.

**Comment by mvdbeek** [comment]
I could see a reason for those being private, that'll need additional review, so I'm going to merge this one now.

**Comment by jozh2008** [comment]
Thank you, I will do a separate PR.

**Pull request merged**
