### PR TITLE
tool_util: switch to mambaforge on non-32bit; add arm64 support

### PR DESCRIPTION
**Pull request by mr-c**
tool_util: switch to mambaforge on non-32bit; add arm64 support

Why: speed up conda creation & dependency resolution, support an up-and-comping arch (arm64)

Creating a new environment & installing seqtk via `rm -Rf cwltool_deps; cwltool --debug --beta-conda-dependencies tests/seqtk_seq.cwl  tests/seqtk_seq_job.json`

Using mambaforge: `196.82user 11.66system 3:51.10elapsed`

Using miniconda: `306.56user 14.97system 5:27.07elapsed`

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
>  speed up conda creation & dependency resolution

awesome!

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Yes, the selenium errors are already fixed. It seems we're not testing the result of the merge (anymore?)

**Comment by martenson** [comment]
@mvdbeek different branch I think

**Comment by mr-c** [comment]
Some timing information:

Creating a new environment & installing seqtk via `rm -Rf cwltool_deps; cwltool --debug --beta-conda-dependencies tests/seqtk_seq.cwl  tests/seqtk_seq_job.json` 

Using mambaforge: `196.82user 11.66system 3:51.10elapsed`

Using miniconda: `306.56user 14.97system 5:27.07elapsed`

Now I'm going to go test on an arm64 box to confirm that part.

**Comment by mr-c** [comment]
Previous behavior for arm64:
```
installing: python-3.7.3-h0371630_0 ...
/tmp/conda_installegrf3tg3.sh: line 370: /home/crusoe/cwltool/cwltool_deps/_conda/pkgs/python-3.7.3-h0371630_0/bin/python: cannot execute binary file: Exec format error
Conda installation requested and failed.
```

With this PR, the new conda environment is created; though `seqtk` is not yet available from bioconda for arm64.

**Comment by martenson** [comment]
thanks a bunch @mr-c !

**Pull request merged**
