### PR TITLE
[16.10] Fixes for the new in-history tool help functionality.

### PR DESCRIPTION
**Pull request by dannon**
xref https://github.com/galaxyproject/galaxy/pull/3051

### CODE REVIEW

**Comment by dannon** [comment]
(following up on this post-freeze, as bugfixes)

**Comment by martenson** [comment]
The bugs described in #3051 are now deployed on Main.

**Comment by dannon** [comment]
@martenson Thanks.

**Comment by martenson** [comment]
The button looks fine now but still does not do anything on the canvas for me, it triggers 2 ajax requests but thats it.

**Comment by dannon** [comment]
Thanks for checking it out.  I have an idea or two as to what it might be, I'll check it out.

**Comment by bgruening** [comment]
@dannon can we have a rebase here and merge it? 
For our users it's a wired bug that doesn't do anything :)

**Comment by dannon** [comment]
@bgruening Does the new version work for you guys?  And, you know I'm not a fan of rebases in general, especially since it's just build artifacts :)  How about the committer that merges resolves the conflict?  That's what I always do.

Edit: To elaborate, my workflow for merging PRs with build artifact conflicts is something like:

```
git checkout dev
git merge remote/branch
make client
git add static
git commit
git push upstream dev
```

**Comment by nsoranzo** [comment]
In the above workflow, it should be `release_16.10` instead of `dev` for this PR. Generally, the branch the PR was opened against.

**Comment by dannon** [comment]
@nsoranzo Yep, that was just an example.

**Comment by bgruening** [comment]
Maybe I did something wrong but this is not working for me on FF and Chrome.

**Comment by dannon** [comment]
To close the loop from IRC -- it looks like normal users are working fine now, but anonymous user access is the problem.  Working on a fix.

**Comment by dannon** [comment]
Latest commit requires a logged-in user.  I didn't want to change the auth requirements for the API endpoint in this bugfix, but it's something we can revisit moving forward.

**Pull request merged**
