### PR TITLE
Populate env.sh files with X_ROOT_DIR.

### PR DESCRIPTION
**Pull request by davebx**
Where X is tool_dependency.name.upper()

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome! Do we have a test for the env.sh files?
This will save us a lot of lines in packages :)

**Comment by jmchilton** [comment]
I'm `-0` on this. This is not how other packaging systems work (we need to get away from environment variable manipulations not make them easier) and so implicit reliance on this will make it harder to transcode recipes. I get it though - it will be useful in the shorter term and it will make certain packages easier to define - feel free to merge over my `-0`.

**Comment by bgruening** [comment]
@jmchilton This is exactly what would be nice to know. Is it worth to spend time in improving it or not. 
I don't see this dramatic change coming so fast. Every change that helps us with the current situation is welcome, imho. 
This also holds for this one here, which would make things a lot easier: https://trello.com/c/lLoJ6vfe

**Comment by jmchilton** [comment]
@bgruening I agree radical changes are not coming as fast as I would hope, I also believe improving the current situation is definitely worth it (I don't work much on the tool shed but I have made some improvements over the last year). I just wish we were improving it to be more like Hombrew/Nix/etc... not to be more like its own thing. It is a -0 not a minus -.5 or a minus -1 - feel free to +1 and merge this - I just needed to say my peace.

**Comment by bgruening** [comment]
You know I agree with you, but I don't see how we can improve the dependency management with baby-steps in this new direction.
Let me know if you have a concrete step-by-step plan and I will try to support it.

For the time being my :+1:

**Comment by jmchilton** [comment]
@erasche  This is a huge change - definitely not `minor` right?

**Comment by jxtx** [comment]
I don't see this as a packaging issue but as a runtime issue. `env.sh` is how we inject a given package (after it has been packaged and installed) into the environment. This just makes writing `env.sh` files easier. I always envisioned it as akin to modules (though much simpler). And modules work by doing exactly this, manipulating paths. Also, isn't this how `brew env` works in https://github.com/platform-brew/? I'm all for getting rid of all of this and coming out with a new dependency solution, but in the meantime, this is not a bad thing.

+1

**Comment by hexylena** [comment]
@jmchilton you're right, erroneous tag. However, I'm :+1: on this as well, let's get it in.

**Comment by hexylena** [comment]
@jmchilton discussion on minor tag: is this really a huge change? We've really been having to do this manually in our packages, now Galaxy handles some of that for us. This feels like a very minor change.

**Pull request merged**
