### PR TITLE
Data libraries - Import from paths - encoding special characters in the path

### PR DESCRIPTION
**Pull request by ashvark**
Fix for the issue #6674

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@nsoranzo @martenson this is similar to the spaces and `+` in tool id / versions in https://github.com/galaxyproject/galaxy/pull/6737, do we like this ?

**Comment by martenson** [comment]
per @mvdbeek suggestion I have made an alternative fix that should resolve this (and similar situations for other importing code paths) : https://github.com/galaxyproject/galaxy/pull/7432

**Comment by mvdbeek** [comment]
I'm gonna close this, https://github.com/galaxyproject/galaxy/pull/7432 is merged and should fix this as well. Thanks alot for taking a look @ashvark!

**Pull request closed without merging**
