### PR TITLE
[18.01] Add queryname sorted and input sorted datatypes

### PR DESCRIPTION
**Pull request by mvdbeek**
The queryname sorted datatype (BamQuerynameSorted) ensures that the file is
queryname ordered.  The BamInputSorted datatype can be used to describe the
output of aligners, which usually keep mate pairs adjacent. The BamInputSorted
datatype allows using tools that require mates to be adjacent, without
requiring an explicit sorting step.  This can reduce the time and space
required for duplicate marking tools, HiC tools and structural variant
detection tools that require mates to be grouped together in an alignment file.

The BamQuerynameSorted has a converter that works for all datatypes that can be
consumed by samtools. There is no converter for BamInputSorted, since
BamQuerynameSorted is valid input for tools requiring BamInputSorted
input.

I'm targeting 18.01 since I think it would be very unfortunate if we start
annotating aligners with the very loose BamNative datatype, since this datatype
does not make any promises about sort order at all.

This closes https://github.com/galaxyproject/galaxy/issues/5497, goes a long way towards the problems mentioned in https://github.com/galaxyproject/galaxy/issues/5496
and would make https://github.com/galaxyproject/tools-iuc/pull/1732 and https://github.com/galaxyproject/tools-iuc/pull/1591 better

### CODE REVIEW

**Comment by bgruening** [comment]
Cool thanks a lot @mvdbeek! :+1: from my site.

**Comment by jmchilton** [comment]
Great thanks a bunch @mvdbeek !

**Comment by jmchilton** [comment]
Is it odd that we call these "xxx.bam" but bam native "bam_native". Should we make a last minute change to call ``bam_native`` ``native.bam`` instead?

**Comment by mvdbeek** [comment]
I think that would be good, yes. Maybe even unsorted.bam ?

**Pull request merged**
