### PR TITLE
Update of tours overview according to #5860

### PR DESCRIPTION
**Pull request by selten**
Default view:
afbeelding

Filtered view:
afbeelding

### CODE REVIEW

**Comment by dannon** [comment]
@selten Thanks for taking a poke at this, it's definitely going to be an improvement.  The logic for toggling tags looks like it's not applied quite right, though.  Given the default tours here:
image

If you do something like uncheck "UI", then uncheck "History", then recheck "UI" both related tours come back into the list.  I'd probably have the displayed list logic be such that tours are displayed if they match *any* of the top tags.

**Comment by selten** [comment]
Altered behaviour, now all tags that belong to a tour need to be set by the buttons.

afbeelding

afbeelding

**Comment by dannon** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@selten Works well for me.  I re-triggered the tests and will merge when they pass.

**Pull request merged**
