### PR TITLE
[17.01] Allow display of install_resolver_checkbox when installing data manag…

### PR DESCRIPTION
**Pull request by mvdbeek**
…er tools.

Ping @nsoranzo, I think this should solve the issue where a datamanager installation from the TS doesn't trigger installation of conda dependencies.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Thanks @mvdbeek!
Unfortunately even with these changes, you don't get a list of the dependencies that needs to be installed. I think we should remove `templates/admin/tool_shed_repository/select_shed_tool_panel_config.mako` in favour of `select_tool_panel_section.mako` , which should then be modified by puttin the tool panel section inside an `#if includes_tools_for_display_in_tool_panel:` .

So `lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py` could be simplied by removing lines 1217 and 1241-1268. Would that work?

**Comment by mvdbeek** [comment]
Yes, I think that would simplify a few things.

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by yhoogstrate** [comment]
image

image


This works for me, thanks!

**Pull request merged**
