### PR TITLE
Fix for valid height/width definitions in workflow rendering code.

### LINKED ISSUE #623: ToolShed workflow SVG display broken
Steps to reproduce:
1. Go to the Tool Shed https://toolshed.g2.bx.psu.edu or Test Tool Shed https://testtoolshed.g2.bx.psu.edu
2. Click "Search for workflows" (top of left pane, under "Search")
3. Click "Search repositories" (no search text so get all of them)
4. Pick a repository, e.g. blast_top_hit_species
5. Under "Contents of this repository", click on the workflow
6. View mockup of the workflow.

Or more directly,
1. Click on https://toolshed.g2.bx.psu.edu/view/peterjc/blast_top_hit_species
2. Under "Contents of this repository", click on the "Species of top BLAST hits" workflow
3. View mockup of the workflow.

The resulting page has this text:

```
Species of top BLAST hits
Boxes are red when tools are not available in this repository
(this page displays SVG graphics)
```

_Expected results:_ Inline SVG graphic

_Safari results:_ No image, no error

_Firefox results:_ No image, error text:

```
XML Parsing Error: no element found
Location: https://toolshed.g2.bx.psu.edu/repository/generate_workflow_image?workflow_name=77e15ba155420f0527c13a1d005a5e6360ba4f06%3A53706563696573206f6620746f7020424c4153542068697473&repository_metadata_id=7f60e3e1f5201579
Line Number 1, Column 1:
^
```

Spotted by @jj-umn

### PR DESCRIPTION
**Pull request by dannon**
Should resolve #623

### CODE REVIEW

**Comment by dannon** [comment]
I still don't know _why_ this just started breaking, but it does resolve the issue as I reproduced it here, locally.

**Comment by dannon** [comment]
I added another commit that resolves a second issue which wasn't preventing rendering, but would cause warnings and generate invalid XML nonetheless.

**Comment by martenson** [comment]
@dannon  wants to merge 2 commits into galaxyproject:dev from dannon:release_15.07

did you want this to go 15.07?

**Comment by dannon** [comment]
@martenson Pfft, yes, good catch!  Thanks, retargeting.

**Pull request closed without merging**
