### PR TITLE
Integration of charts into the generic visualization framework

### PR DESCRIPTION
**Pull request by guerler**
This PR augments the visualization framework by adding features which were initially established for charts visualization plugins e.g. now visualization input parameters and data groups are described in the visualization XML instead of charts js-config files. The associated form builder has been moved to core and can be used by other visualizations too. The chart selection grid with logos has also been moved to core and is used for all visualizations as default interface of the unified visualization framework. Individual chart visualization types/plugins have been re-intregated into the augmented visualization framework. This PR will require follow-ups.

### CODE REVIEW

**Comment by guerler** [comment]
Hey, just got visualizations back working with the last commits. Now we can restructure things according to best practice. Particularly with regard to the d3 import in the mako (instead of node) and the nvd3 code insertion. The nvd3 library we are using has been adjusted to allow zooming all 2D-plots. This is an ongoing discussion see: https://github.com/novus/nvd3/issues/474 where they discuss using the approach we developed for this particular nvd3-file. I noticed that the d3 import does not work when using this file, so I left it in the mako for now. There are a couple other things I would like to refactor in the next few days but it looks promising e.g. shared formatters, helpers and css handling. Thanks a lot for your contributions @dannon, building using parcel works great.

**Comment by dannon** [comment]
@guerler Instead of adding the 14,000 lines back to the codebase, can we patch the prototype on load when we need to?  (I'm happy to implement this if it means we can strip that back out -- we're trying hard to never bloat the repo like this.  If we *do* want to do that, maintaining a modified nvd3, I'd prefer it be added as an external node dependency, which I can also do for you if you want)

**Comment by guerler** [comment]
Yeah sure that sounds good. Its not related to the goal of this PR but it would be a good addition.

**Comment by dannon** [comment]
@guerler Ok, I'll do that.  Do you want me to do the rebase to remove the extra lines, or would you rather?

**Comment by dannon** [comment]
@guerler Looks like that merge was bad, undoing all the rebase work?

(update for anyone watching -- we've fixed the branch weirdness)

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
Closed in favor of #5505.

**Pull request closed without merging**
