### PR TITLE
Allow uploading strict BED datatypes.

### PR DESCRIPTION
**Pull request by blankenberg**
It all depends upon how much you are willing to trust the user.

### CODE REVIEW

**Comment by blankenberg** [comment]
@lparsons comments, desires?

**Comment by lparsons** [comment]
Not quite sure I understand the downside of this, since right now my users end up selecting a bed6 file as input a tool that requires bed12 since there is no way to distinguish the difference. While I can see there might be confusion, I would think the sniffers could tell the difference, and properly identify the filetype and thus reduce the instances of errors... So, I'm in favor of this.

**Comment by hexylena** [comment]
:+1:

**Comment by hexylena** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
more freedom, more responsibility ...

**Pull request merged**
