### PR TITLE
Add implicit conversions target extension to hda name when listed as selection option

### PR DESCRIPTION
**Pull request by guerler**
Related to #2704. ping @remimarenco.

### CODE REVIEW

**Comment by dannon** [comment]
+1, works well.

**Comment by remimarenco** [comment]
Do you think it is possible to merge forward up to 16.04? (Or even before if the regression was there?)

**Comment by nsoranzo** [comment]
@remimarenco see #2779.

P.S.: The correct term in this case is a backport. "Merge forward" is when the changes to an old release branch, say `release_16.01`, are merged in `release_16.04`, then `release_16.04` is merged in `master` and in the unreleased `release_16.07` and finally `release_16.07` is merged in the `dev` branch.

**Comment by remimarenco** [comment]
It makes sense! Thanks for taking the time to explain @nsoranzo, greatly appreciate

**Pull request merged**
