### PR TITLE
Labels for individual tools in tool panel.

### PR DESCRIPTION
**Pull request by jxtx**
Allow one or more labels to be attached to a tool in the tool panel.
These will be rendered to the right of the tool's link using the
boostrap label style. Styles for specific labels can be defined in CSS,
specific colored labels for "new" and "beta" are defined.

It's not perfect because the tool is the actual object used in the 
tool panel section's dictionaries, but inserting a wrapper to capture
the labels for each place the tool is used is going to require deeper
surgery on the panel.

### CODE REVIEW

**Comment by jxtx** [comment]
For example:

image

**Comment by hexylena** [comment]
Oooh exciting! Looks great too.
- are these searchable?
- can we label sections too? (Might be nice for admins installing a whole section of tools, e.g. bcftools to mark the whole section)

**Comment by jxtx** [comment]
> are these searchable?

Not currently.

> can we label sections too? (Might be nice for admins installing a whole section of tools, e.g. bcftools to mark the whole section)

Agreed. We've been doing this just in the section name for a while, but I think this would be better. The problem is it looks like it would require a lot of duplication at the moment. Top level sections, nested sections, tools are all handled a little differently in the panel. I think it makes sense to try to clean that up first. Just have arbitrarily nestable ToolPanelElement's or something. But that touches a lot of things (integrated tool panel). I got intimidated.

**Comment by hexylena** [comment]
@jxtx fair enough! I've wanted properly recursive sections for a while but there's so much JS that I'm not good enough at to even begin to touch it. I'm not really qualified to review this (so no +1 from me) but as a deployer I'm sure excited for it!

**Comment by jxtx** [comment]
Searchable now.

**Comment by dannon** [comment]
Merged manually to rebuild style and resolve conflict in base.css.  Works well!

**Comment by bgruening** [comment]
@jxtx this works fantastic at our server. Just documentation is missing. Where do you think documentation should go? We do not have a ToolBox wiki page, right?

**Comment by martenson** [comment]
@bgruening How do you use it? I am about to label some tools on Main. What labels do you use and how do you structure it? 
I will write down documentation for this, thanks for the reminder.

**Comment by bgruening** [comment]
I just use the predefined ones, `beta` and `new`. We labelled a few test-tools that are not IUC approved yet with `beta` and all new tools that I installed during the last days or updated as `new`.

**Comment by martenson** [comment]
@bgruening how do you manage the labels? Manually?

**Comment by bgruening** [comment]
Yes, currently yes. I'm thinking about offering this as option during the Tool Installation, but than again you need to have a mechanism to remove them. It would be really nice to have a ToolBox editor at some point.

**Comment by jxtx** [comment]
@bgruening Probably documentation goes here? https://wiki.galaxyproject.org/GalaxyToolPanel

That page probably shouldn't have a ToolShed logo since it is about configuring the Galaxy menu, though the ToolShed is of course involved.

**Comment by martenson** [comment]
I modified and linked and polished the wiki at: https://wiki.galaxyproject.org/Admin/ToolPanel

**Comment by combesf** [comment]
Following the link of the latest post , I read : 
"You can add labels="text" to the XML element to render a label next to the tool in the tool panel."
Please could you precise : does this mean in the XML file of the tool, 
or in the 'integrated_tool_panel.xml' file ? 
or another file ? 
Thank you.

**Comment by martenson** [comment]
@combesf here is an example:
`<tool file="toolshed.g2.bx.psu.edu/repos/gregory-minevich/cloudmap_in_silico_complementation/5389dc5a0be3/cloudmap_in_silico_complementation/CloudMap_InSilico.xml" guid="toolshed.g2.bx.psu.edu/repos/gregory-minevich/cloudmap_in_silico_complementation/in_silico_complementation/1.0.0" labels="deprecated">`

I will also add it to the wiki linked above. Thanks for the input.

**Pull request merged**
