### PR TITLE
[17.05] Fix drag and drop from history for Firefox

### PR DESCRIPTION
**Pull request by guerler**
This PR fixes the drag-and-drop feature for Firefox.

### CODE REVIEW

**Comment by dannon** [comment]
Argh, this was 17.05.  Can I get another +1 in the next ~3 minutes, or should I revert?

**Comment by bgruening** [comment]
+1

**Comment by dannon** [comment]
Thanks @bgruening ! :)

**Comment by guerler** [comment]
Thanks!

**Comment by nsoranzo** [comment]
I had the same issue and can confirm it's fixed now, thanks! :+1:

**Comment by FredericBGA** [comment]
Thanks, it works for me too.

**Pull request merged**
