### PR TITLE
Integrate masthead option listing all available visualizations

### LINKED ISSUE #5481: Clean Up masthead
- [x] Move VIZ after workflow, rename to visualize?
- [x] Create a view with data list selector
- [x] Add all visualizations as thumbnails to the view
- [x] Remove drop down
- [x] Clicking on it gives you a listing page with all vizualizations

### PR DESCRIPTION
**Pull request by guerler**
Resolves #5481.

### CODE REVIEW

**Comment by guerler** [comment]
Switched this back to WIP to add some fixes for built-in visualizations.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
I thought we were going to rename the masthead option to "Visualize". Did you decide against that?

**Comment by guerler** [comment]
@jmchilton "Visualize" is fine. I changed it. I plan to drop the drop-down menu in a follow-up and then directly show the list of available visualization types when the masthead tab has been clicked. Currently the list requires a second click on "Create Visualization". Thanks for looking into this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by dannon** [comment]
@guerler The charts look fine here, but Trackster embedded in the center panel isn't working very well for me.  A few quick things are that the first dialog on creation is majorly clipped, only showing half of the first line of text, and when exiting the viz, I end up back at a big json blob.  To keep from bloating this PR more, can you maybe just toggle it back to use the 'standard' Trackster entrypoint, to revisit again in the future?

**Comment by guerler** [comment]
@dannon Thanks for looking into it. I will follow-up on this immediately after this PR. The reason for embedding it here (temporarily) is that this will allow me to reduce the underlying makos in Trackster, Circster etc. Currently these makos describe their own masthead. After that the visualizations will be loaded in unembedded fashion again.

**Comment by dannon** [comment]
I understand we talked about that followup PR, I'm just saying this actually breaks a few things, and the 'entrypoint' link for trackster could just be toggled to the other view in this, leaving it functional in dev while you work on the followups?

**Comment by dannon** [comment]
@guerler Thanks, that last changeset was exactly what I was asking for.

**Comment by dannon** [comment]
Last question/nitpick, I promise.  Can we revert the bit swapping the URL to "plugins" from "visualizations"?  `usegalaxy.org/plugins` is a much less descriptive route than `usegalaxy.org/visualizations`, not to mention that we continue to refer to everything listed there as 'visualizations' and not plugins.

**Pull request merged**
