### PR TITLE
[15.07] Binary sniffing; along with the registry forcing case insensitivity t…

### LINKED ISSUE #753: RData file gets recognized as a "gzipped file" on upload
screen shot 2015-09-18 at 1 04 09 pm

### PR DESCRIPTION
**Pull request by dannon**
…hrough lower() which was implemented a while back, the un/sniffable formats lists should as well.  This resolves #753

Ping @nitesh1989

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is this worth a specific test case?

**Comment by nturaga** [comment]
+1 

@dannon Thanks.

**Comment by nturaga** [comment]
@dannon Does this PR to 15.07 reflect in dev also?

**Comment by dannon** [comment]
@nitesh1989 Not automatically, but once it has been applied to 15.07 I'll merge it forward.

@nsoranzo It's a tough one to check since the logic for this stuff is a little sparse and we access lists directly in some places, etc.  (That said, if someone wanted to put in the work to refactor and write tests, I think it would be fantastic)

**Comment by nsoranzo** [comment]
@dannon I mean something like https://github.com/galaxyproject/galaxy/blob/dev/test/functional/test_get_data.py#L291 , but for an `.RData` file.

**Comment by jmchilton** [comment]
@nsoranzo I can add a test case, give me 15 minutes.

**Comment by jmchilton** [comment]
Test case requires changes too complex for 15.07, will merge this as is and open a PR to dev with changes. :+1:

**Comment by nsoranzo** [comment]
@jmchilton Sure, thanks!

**Pull request merged**
