### PR TITLE
Remove legacy library interface

### PR DESCRIPTION
**Pull request by guerler**
This PR removes the legacy library interface. The main challenge is that the api controller uses the web controller functions. This PR attempts to unwind the two. While unwinding it turns out that many of the validation checks, parameters and code paths used through the controller are not working/not used when called through the API. Access validation e.g. is tested through the api but the result is not used to prohibit the operation, see: https://github.com/galaxyproject/galaxy/pull/4908/files#diff-a74fb51de19ecbcb13be07dea19fde07R316.

### CODE REVIEW

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/1995

**Comment by martenson** [comment]
I signed up as a reviewer for this since I am interested and working on related code atm.

**Comment by guerler** [comment]
ping @martenson, I am refactoring a few things to reduce redundancies. Sorry, should have done that earlier. I think it'll will simplify the review process.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
When adding datasets from user directory:

```
galaxy.web.framework.decorators ERROR 2017-11-10 12:22:58,257 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/api/library_datasets.py", line 480, in load
    trans, 'api', kwd, os.path.basename(file), file, 'server_dir', library_bunch))
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/api/library_datasets.py", line 568, in _make_library_uploaded_dataset
    link_data_only = params.get('link_data_only', 'copy_files')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by martenson** [comment]
also errors when using import directory or path

```
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/api/library_datasets.py", line 495, in load
    trans, kwd, library_bunch, 200, '')
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/api/library_datasets.py", line 521, in _get_path_paste_uploaded_datasets
    uploaded_datasets.append(self._make_library_uploaded_dataset(trans, 'api', params, name, path, 'path_paste', library_bunch, folder))
TypeError: _make_library_uploaded_dataset() takes at most 8 arguments (9 given)
```

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
My branch was busted, with a clean checkout the errors above are not thrown anymore.

**Review by martenson — APPROVED** [review]
Looks well, works well. Thanks Aysam.

**Comment by guerler** [comment]
Thanks a lot for the review man. I know it was quite a bit of work.

**Pull request merged**
