### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by galaxybot**
Run `make update-dependencies`.

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by davelopez** [comment]
Thanks @nsoranzo for the ping. I'm afraid https://github.com/galaxyproject/galaxy/pull/12856 is still relevant since the new [version of fastapi (0.70.1)](https://github.com/tiangolo/fastapi/releases/tag/0.70.1) does not yet support Starlette 0.17.0 and the `BrokenResourceError` may happen. I suspect we need to pin `fastapi==0.68.2` until, at least, Starlette 0.17.0 is supported.

**Review by davelopez — COMMENTED** [review]
Thank you @nsoranzo the fastapi version restriction looks correct.

I tried to rerun the integration tests but the failure seems legitimate:

`FAILED test/integration/test_cli_runners.py::ParamikoCliTorqueIntegrationTestCase::test_running_cli_job`

```
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/__init__.py", line 146, in run_next
    method(arg)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/cli.py", line 65, in queue_job
    shell, job_interface = self.get_cli_plugins(shell_params, job_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/cli.py", line 38, in get_cli_plugins
    return self.cli_interface.get_plugins(shell_params, job_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/util/cli/__init__.py", line 32, in get_plugins
    shell = self.get_shell_plugin(shell_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/util/cli/__init__.py", line 43, in get_shell_plugin
    self.active_cli_shells[requested_shell_settings] = shell_plugin_class(**shell_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/util/cli/shell/rsh.py", line 69, in __init__
    self.connect()
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/util/cli/shell/rsh.py", line 81, in connect
    timeout=self.timeout)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/client.py", line 679, in _auth
    key_filename, pkey_class, passphrase
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/client.py", line 588, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, ***
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/paramiko/pkey.py", line 355, in _read_private_key
    "encountered {} key, expected {} key".format(keytype, tag)
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
```

**Comment by nsoranzo** [comment]
> I tried to rerun the integration tests but the failure seems legitimate:

@davelopez Yep, it should be fixed in the latest commit.

**Comment by nsoranzo** [comment]
Green!

**Pull request merged**
