### PR TITLE
Added sorting ability to jobs per tool page in reporting

### PR DESCRIPTION
**Pull request by OldWorldBoa**

### CODE REVIEW

**Comment by martenson** [comment]
The lint is failing on the following:

```
lib/galaxy/webapps/reports/controllers/jobs.py:410:1: W293 blank line contains whitespace
lib/galaxy/webapps/reports/controllers/jobs.py:413:1: W293 blank line contains whitespace
lib/galaxy/webapps/reports/controllers/jobs.py:444:5: E301 expected 1 blank line, found 0
```

You can access the results by clicking on 'Details' next to the failed Travis build

**Comment by jmchilton** [comment]
:+1: - works for me. Thanks!

**Comment by nsoranzo** [comment]
Should there be a `jobs_errors_per_tool.mako` file in `templates/webapps/reports/` ?

**Comment by OldWorldBoa** [comment]
There should be after db105db. I added another page, and I pushed since there was a fix in b985851 for the jobs per tool page. I don't know how to just add one part of my work to this pull request, but I'm trying to figure out how so this doesn't happen again.

**Comment by nsoranzo** [comment]
@Airistotal If you go to the `Files changed` tab of this pull request, you can see that `jobs_errors_per_tool.mako` file is not present. You should do something like:

```
git add templates/webapps/reports/jobs_errors_per_tool.mako
git commit -m "Add jobs_errors_per_tool.mako ."
git push
```

**Comment by martenson** [comment]
@Airistotal whatever you change in your `Airistotal:dev` branch will get propagated to this PR. Also best practice is to work on a feature-branch in your fork (so something like `Airistotal:reports-job-per-tool` and then when you are waiting for the PR to get reviewed and merged you can conveniently work on other features/branches)

**Comment by OldWorldBoa** [comment]
Okay, will do.

**Comment by martenson** [comment]
seems working well at my local instance, let's give it a spin at Test
thank you for the contribution @Airistotal !

**Pull request merged**
