### PR TITLE
Luke's AnVILFS conditional dependency

### PR DESCRIPTION
**Pull request by almahmoud**
Moving anvil fs as a conditional requirement upstream to reduce diff from anvil fork

### CODE REVIEW

**Comment by jmchilton** [comment]
I pushed a lint fix. Can you take this out of draft and I'll merge it?

**Review by dannon — APPROVED** [review]

**Comment by almahmoud** [comment]
Thanks @jmchilton ! It's in draft for now since @luke-c-sargent is working on the writing back functionality in case something is needed in `anvil.py` for that. Will take it out of draft after he confirms

**Comment by jmchilton** [comment]
I don't think this needs to wait on that. We're not pinning versions here so we would just pickup the fixes from that package automatically.

**Comment by mvdbeek** [comment]
Should we backport this to 21.01 ?

**Comment by almahmoud** [comment]
If you don't mind, that'd be great!

**Pull request merged**
