### PR TITLE
Fix default option for repeats

### LINKED ISSUE #1016: <repeat> default="1" not working
Running with `planemo serve` `default="1"` does not show the param. `min="1"` does.

```
<repeat name="repeat_test" default="1" title="Test">
  <param name="RP" type="text" value="" label="RP"/>
</repeat>
```

### PR DESCRIPTION
**Pull request by guerler**
Fixes #1016.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by jmchilton** [comment]
This should target 16.01 instead right?

**Comment by guerler** [comment]
Thanks. I agree. I'll prepare it.

**Comment by guerler** [comment]
Closing this in favor of #1635.

**Pull request closed without merging**
