### PR TITLE
Reimplement menu onclick functionality that appears to have been drop…

### PR DESCRIPTION
**Pull request by dannon**
…ped (probably a bad merge?) in the webpack PR.

### CODE REVIEW

**Comment by dannon** [comment]
My guess is it got lost in what was surely a really nasty merge ;)

ping @guerler @carlfeberhard

**Comment by martenson** [comment]
That sucks if we are losing stuff while merging. Shouldn't happen :/

**Comment by martenson** [comment]
@galaxybot test this

**Comment by carlfeberhard** [comment]
+1 Sorry for the trouble.

**Comment by martenson** [comment]
Do we know how it happened and more importantly how to prevent it from happening?

**Comment by dannon** [comment]
(original PR ref:  #1142)

@martenson Webpack change involved moving a _lot_ of stuff around and I'm sure the merge was really awful to do.  Smaller PRs make things like this easier to spot, but it's not always doable -- like with webpack -- it made sense to have that as one huge PR, I think.

Just gotta be careful, I reviewed the PR and I didn't even notice it had been dropped at the time, until I tried to use the functionality yesterday.

**Comment by guerler** [comment]
:+1:

**Pull request merged**
