### PR TITLE
tests need to count data sets and collections

### PR DESCRIPTION
**Pull request by bernt-matthias**
Otherwise `expect_num_outputs` seems not to work as expected IMHO.

https://github.com/galaxyproject/tools-iuc/pull/2127 is an example that does not work without this change.

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

**Comment by martenson** [comment]
could use a squash/rebase

**Comment by bernt-matthias** [comment]
> could use a squash/rebase

@martenson wonderful idea. but as you see I failed horribly :( still struggling with git and could need some help here.

**Comment by mvdbeek** [comment]
I think in your case it would be easiest to just cherry-pick b22ba0f and 0198164 into a clean new branch. In practive I'd do `git checkout -b clean_new_branch origin/dev` (assuming origin is galaxyproject), `git cherry-pick b22ba0f 0198164`, push and make sure all is good. Then delete the local branch `git branch -D bernt-matthias:topic/test-colouts` and rename `clean_new_branch` to `bernt-matthias:topic/test-colouts` (`git checkout -b bernt-matthias:topic/test-colouts`).

Then you just need to force-push and the PR will only contain the commits in the cleaned-up branch.

**Comment by bernt-matthias** [comment]
Thanks @mvdbeek.

**Review by martenson — APPROVED** [review]
thanks @bernt-matthias !

**Pull request merged**
