### PR TITLE
[16.01] Quota API issue with serialization to JSON of Decimal

### PR DESCRIPTION
**Pull request by dannon**
Applies patch from Fabien Mareuil to resolve json serialization of Decimal error.  For more information see http://dev.list.galaxyproject.org/quota-api-error-td4669081.html

### CODE REVIEW

**Comment by dannon** [comment]
Reproduce the error by creating a quota, assigning a user (with data uploaded and nonzero usage), and viewing that particular quota's detail page.  `"total_disk_usage": 15,` is the bit that breaks without the cast from Decimal.

**Comment by dannon** [comment]
Failing toolshed test unrelated, due to toolshed being temporarily down.

**Comment by nsoranzo** [comment]
What happened to the Travis tests here? :fearful:

**Comment by davebx** [comment]
@galaxybot test this

**Comment by davebx** [comment]
@nsoranzo The one failing test was because the toolshed was unavailable yesterday.

**Comment by nsoranzo** [comment]
@davebx This PR is missing the results for the **Travis** tests, not Jenkins tests! Anyway is not important for this PR in particular, just wanted to be sure there are no problems with the Travis integration.

**Comment by martenson** [comment]
@nsoranzo Both of you are right and both tests are working now. Seems like a hiccup.

**Pull request merged**
