### PR TITLE
fix syntax of xsd tool schema

### PR DESCRIPTION
**Pull request by martenson**
found by @nsoranzo

### CODE REVIEW

**Comment by martenson** [comment]
@nsoranzo I suspect circleci did not test this since it tested this commit for `martenson/galaxy` repo (https://circleci.com/workflow-run/c8e35b49-5fb2-43f2-b82b-75e7cb6080ba). Still annoying though since it does not show the results here.

**Comment by nsoranzo** [comment]
@martenson See https://bioconda.github.io/faqs.html#circlecimacos , I think we should disable building on our forks.

**Comment by martenson** [comment]
@nsoranzo I disabled builds on my fork. For this reason: https://twitter.com/drazisil/status/1102704259718672386

Maybe circleci will be generous to us as well, we should ask them for macos allocation.

**Comment by thermokarst** [comment]
Thanks @nsoranzo & @martenson! I didn't realize that I needed to specify my new `complexType` as a top-level type, rather than inline (as done in #7400). Thanks for fixing this!

**Comment by martenson** [comment]
@thermokarst fwiw I think your spec was xsd-valid, just our parsing does expect it like this

**Pull request merged**
