### PR TITLE
Fix comment starttag in oidc sample

### PR DESCRIPTION
**Pull request by dannon**
(ligatures are the best)

### CODE REVIEW

**Comment by nsoranzo** [comment]
Target 19.05?

**Comment by dannon** [comment]
@nsoranzo Sure; just realized it was busted in the previous version of this line as well.

**Comment by dannon** [comment]
The rebase/retarget/forcepush confused jenkins, test failures unrelated.

**Comment by dannon** [comment]
Thanks.  I'll merge this forward and deconflict it.

**Comment by martenson** [comment]
I wonder if we should do some basic linting on all XMLs to catch syntactic problems.

**Pull request merged**
