### PR TITLE
[16.10] Use OSX-compatible sed syntax

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix problem reported at https://github.com/galaxyproject/galaxy/commit/7c030ebf2f51c6800966a2fc2d1b0048f0930f1d#commitcomment-20108366

### CODE REVIEW

**Comment by martenson** [comment]
:/
```
sed -i.bak -e 's|.. code:: xml|.. code-block:: xml|g' source/dev/schema.rst
# Insert table of contents
sed -i.bak -e '/^``tool``$/i\
.. contents:: Table of contents\
   :local:\
   :depth: 1\
..\
' source/dev/schema.rst
sed: 1: "/^``tool``$/i.. content ...": command i expects \ followed by text
make[1]: *** [source/dev/schema.rst] Error 1
make: *** [docs] Error 2
```

**Comment by nsoranzo** [comment]
Mmmh, trying to fix a bug involving sed, Makefile and OSX while being on Linux it's not easy apparently...

**Comment by martenson** [comment]
@nsoranzo yeah, I tried few things too, no luck :/

**Comment by nsoranzo** [comment]
@martenson: I've added a new commit that fixes it for me under OS X.

P.S.: BSD sed is really crap!

**Comment by martenson** [comment]
Thanks @nsoranzo !!

**Pull request merged**
