### PR TITLE
[17.01] Fix annotation display for data inputs

### LINKED ISSUE #3633: Workflows - input dataset names do not appear on launch form
Since the update to 17.01 on Main the names and annotation/notes of input datasets assigned in the workflow editor do not appear on the workflow launch form. This is the case for workflows starting from standard and collection-based input.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #3633. Only for 17.01.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Great - many thanks for the fix @guerler!

**Pull request merged**
