### PR TITLE
[16.07] Allow link buttons to trigger regular click events

### PR DESCRIPTION
**Pull request by guerler**
This feature is used by the history refresh button.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@guerler GitHub complains about conflicts that must be resolved.

**Comment by martenson** [comment]
yeah, it is because of the merge #2744 - needs repack :(

**Comment by dannon** [comment]
For merging:   Just merge locally, make client, then 'git add static' to resolve teh conflicts.

**Comment by dannon** [comment]
+1, seems to be working well for me, fixes history refresh and I don't see it causing issues anywhere else.

**Pull request merged**
