### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Remove `python_version` pin for `monotonic` and `python-dateutil` packages
- Fix errors reported by the new flake8 3.6.0
- Ignore W504

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test py3

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Comment by nsoranzo** [comment]
The failed selenium tests on Python3 are unrelated, they fail also on unrelated PRs, e.g. https://github.com/galaxyproject/galaxy/pull/6910.

**Comment by mvdbeek** [comment]
Thanks @nsoranzo !

**Pull request merged**
