### PR TITLE
fix displaying the interactive environment spinner

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by hexylena** [comment]
- Does this _actually_ fix the issue? The problem is that `galaxy_root` is undefined in that context, I investigated it before but quit/gave up on it because it was a lot of work to pass that variable into the JS file as it's only known in the python context. There wasn't a nice place to shim it into the top of rendered html page either, as the JS that's run is in `<head/>`.
- should we just remove `galaxy_root` and allow IEs to ship with their own, custom spinners? I could imagine having "pretty"/"fun" spinners for IPython/RStudio notebooks which would be different.

**Comment by bgruening** [comment]
@erasche yes, this working here. You can get galaxy_root with `h.url_for( "/" )` in your mako as far as I know.

**Comment by hexylena** [comment]
@bgruening okay, that's good to hear but doesn't fix the underlying problem. There's no easy way to get the galaxy_root variable INTO the JS code. 

In order to do this properly with the real `h.url_for("/")` value of `galaxy_root`, you'd have to:
- inject in `load_notebook()` in https://github.com/bgruening/galaxy/blob/IE-spinner-fix/config/plugins/interactive_environments/ipython/templates/ipython.mako#L56
- add to `load_notebook()` in https://github.com/galaxyproject/galaxy/blob/226e8265e4f9a7de9b83960af71e46313f81b650/config/plugins/interactive_environments/ipython/static/js/ipython.js#L36
- add to function signature of `test_ie_availability()` in https://github.com/bgruening/galaxy/blob/IE-spinner-fix/client/galaxy/scripts/galaxy.interactive_environments.js#L28
- and finally pass to `display_spinner()`

**Comment by hexylena** [comment]
That's why I didn't bother doing it. It's too ugly. 

However! If this works for you, would you mind just getting rid of the unused `galaxy_root`? Then you have my +1

**Comment by bgruening** [comment]
@erasche sorry to be not clear enough. This is working for me in the sense of galaxy_root is `/` in my setup. That's the reason we need to remove the beginning `/`.

**Comment by hexylena** [comment]
@bgruening yes, I understand that, but `galaxy_root` is STILL undefined (or is it different for you?) 

In the JS, there's no way for galaxy_root to be available, it's not in scope, the url should be evaluating to `src="static/style/largespinner.gif"` for you.

**Comment by bgruening** [comment]
It's really working for me. `alert()` gives me back a `/`.

**Comment by hexylena** [comment]
Weird!! Ok, +1 from me
2. jun. 2015 13.28 skrev "Björn Grüning" notifications@github.com:

**Pull request merged**
