### PR TITLE
Show DCE count in collection and HDCA views

### LINKED ISSUE #400: show information about collections
It would be nice  to be able to see information about collections in the history.
At least how many elements the list has.
Further maybe a summary of the content (if possible)

### PR DESCRIPTION
**Pull request by carlfeberhard**
Upshot: 
- returns the element count for HDCAs from the API by default 
- and displays them in HDCA subtitles (e.g. 'a list of 9 datasets')

Adds a serialization method for `element_count` to the HDCA API serializer used by history_contents (i.e. history/{:id}/contents). This returns the count of datasets (or subcollections in the case of list of pairs) in the HDCA. This field isn't returned by default and needs to be specifically requested using the `keys` parameter:

```
http://localhost:8080/api/histories/{:id}/contents?keys=type_id,element_count 
```

This PR waits 2 secs after the history contents have been loaded (so as to not bog down the initial load) and fetches the element_count for all HDCAs. This should allow the UI to remain responsive.

We'll have to see how bad this is when 1000s of HDCAs are being updated (and how that fits into #2126).

Resolves #400

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@galaxybot test this

**Comment by carlfeberhard** [comment]
Updated to *only* return `users_shared_with` if the user making the request is the owner.

**Comment by dannon** [comment]
image

**Comment by dannon** [comment]
Looks good, shows up right away and updates totals 2 seconds after.

**Pull request merged**
