### PR TITLE
Fix E201 and E202 style errors

### PR DESCRIPTION
**Pull request by nsoranzo**
Remove all whitespaces after `(` and before `)` and removes E201 and E202 from the ignored linting errors.

As discussed on Gitter/IRC, this brings us closer to the official PEP8 standard and makes our code more uniform.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Wonderful, but this is going to get stale super quickly. Happy to merge if you can rebase against the latest changes.

**Comment by nsoranzo** [comment]
@mvdbeek Rebased.

**Comment by jmchilton** [comment]
I'm definitely going to grow to hate you @nsoranzo as I have to rebase thousands of lines against this and this will make tracking git commit history for everything I've ever touched more difficult - but right now when we are still friends and since I don't hate you yet I thank you for doing this and congratulate you on moving [ahead of me in the rankings](https://github.com/galaxyproject/galaxy/graphs/contributors?from=2006-11-12&to=2017-08-17&type=d).

**Comment by nsoranzo** [comment]
Thanks @jmchilton :heart: 
And I'm ahead of you only for deletions...

**Comment by jmchilton** [comment]
If anyone else is in the position of having to rebase large branches against this change - I think have found a winning strategy - I'm half way through rebasing my thirty or so commits of the CWL branch against it using this approach:

```sh
# Create a backup of your branch pre-rebase and push to github.
git checkout -b my_branch_pre_rebase && git push origin my_branch_pre_rebase && git checkout my_branch

# Do a normal rebase against the last commit before the huge white space change
# this was we can be sure most of what we are rebasing against is just white space fixes
git rebase -i 008a1d849c4eb86ab52fd032ae611e4844c3cf09

# Do a rebase against just the whitespace changes
git rebase -i 68e8abc89aba1263f82c643d1bde89da53d70bc9

# For rebase will stop at each commit with a conflict, review -
# ideally what you see you want is the branch content but with white
# space changes - just verify this visually and quickly.
git diff

# Then checkout your branch content and apply whitespace fixes to it
# add it back in and continue the rebase
git checkout --theirs lib test && .ci/autopep8.sh && git add -u lib test && git commit && git rebase --continue

# After it is finally done - push to github and view changes - if everything is okay continue to rebase
# against latest dev.
git rebase -i upstream/dev
```

**Comment by peterjc** [comment]
Its great to see this merged 🥇 

Did anything need updating in the TravisCI / Tox settings to now enforce flake8's E201 and E202 checks?

(I've been looking at the files and ``/.ci/`` folders and didn't find where the ignore/select list is done)

**Comment by martenson** [comment]
@jmchilton already rebased my stuff yesterday but thanks for the guide

**Comment by nsoranzo** [comment]
@peterjc The changes are in `setup.cfg` .

**Comment by VJalili** [comment]
Finally I can enable pycharm code formatting :)

**Pull request merged**
