### PR TITLE
Refactor client API packages

### LINKED ISSUE #16841: Move API related logic in client to `api` package
It was briefly discussed in the UI/UX matrix channel, creating an issue for further discussion, visibility, and tracking.

## Summary
Currently, there is no fixed rule on where to put functions to call our API endpoints. They are a bit all around, we have them beside components in a service module (like https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Dataset/services.ts), directly inline in the middle of components (like https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/admin/JobLock.vue) and also under the stores/services folder (https://github.com/galaxyproject/galaxy/tree/dev/client/src/stores/services). All of these options are fine, but it is hard to know which functions we have already declared somewhere else and some of them provide extra handling that we don't want to duplicate.

## Proposed solution
@dannon proposed in the chat the following solution: to place all those functions under their respective modules inside the `api` package:

```
client/src
    ...
    api
        schema
           - contains the current `src/schema` modules
        index.ts
           - contains common type definitions or exports
        histories.ts
        datasets.ts
        user.ts
        ...
```

### PR DESCRIPTION
**Pull request by davelopez**
Closes #16841

- [x] Move the current `src/schema` package into `src/api/schema`
- [x] Move some API-related queries to their own modules in `src/api/{module}` for easier discoverability and reusability.
  - Some APIs don't need to be moved as they are unlikely to be generally used across the client codebase like:
    - `api/storage`: lives under `client/src/components/User/DiskUsage/Management/services.ts`
- [x] Try to consolidate naming conventions:
  - Use the word `fetch` to explicitly convey that it will trigger a server request as opposed to simply `get` that may or may not trigger a request (for example when getting the cached values from a store). Examples:
    - When we define a fetcher for an endpoint like `GET api/whatever` we can name the fetcher as `whateverFetcher`:
      ```ts
      export const whateverFetcher = fetcher.path("/api/whatever").method("get").create();
      ```
    - When we require a custom fetcher with some extra parameters or response handling we can use as function name `fetchWhatever`:
      ```ts
      interface MagicalItem { ... }
      
      const whateverFetcher = fetcher.path("/api/whatever").method("get").create();
      
      export async function fetchMagicalWhatever(extraThing = "something"): Promise<MagicalItem[]> {
          const { data } = await whateverFetcher({ use_magic: true, extra_thing: extraThing });
          return data as MagicalItem[];
      }
      ```
- [x] Include a small best practices guide under `client/docs/querying-the-api.md`

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
I definitely agree a best practice and greater consistency in the code around these packages would be good. Thank you for working on this.

> reusability

I would argue that building reusable components in part means targeting specific, clean parts of the API that can likewise be decomposed. Centralizing the modules feels like a step backwards in terms of isolation which I think is a key aspect of reusabilty. A component that targets our license API or the TRS APIs would be great and could be used outside the context of Galaxy readily I would think given that these APIs are isolated well and highly structured. Shipping the component together with its API interaction layer would seem to be the right way to handle that - but maybe there are frontend idiosyncrasies that make it substantially different than the backend. 

I'm not opposed to these changes at all - this comment doesn't need a response and shouldn't block the PR anyway. Just wanted to say my peace on isolation and convey my lessons learned on working on the backend components with a similar eye toward reusability.

**Comment by davelopez** [comment]
@jmchilton I appreciate the comment! That is a good point, I sometimes struggle with how to organize big code bases, I really want to come up with a solution that can be considered best practice and feels consistent across the entire project and I'm totally willing to adapt to alternatives.

My line of thought was... I would like to query the API for some particular object in a component, what do I do?
- Do I look for existing queries that return what I need? For that, we need a somewhat centralized place like this `src/api`.
- Create my own queries (even if they exist elsewhere)? It is probably not a lot of duplication, but some parameters and responses for queries might require a bit of massaging that needs to be duplicated.
- Use a composable (or a Pinia store) and relay to it the "querying"? I guess this would be similar to the centralized case and we might not always be required to store query results.

The whole idea of this was to actually come up with something that we are all happy with and we can all agree on, so I'm glad you commented and I'm more than happy to rewrite it :)
Maybe just focusing on naming things consistently would be enough. We use sometimes the term "service" and in other cases "queries".

**Comment by mvdbeek** [comment]
I understood

> Move API-related queries to their own modules in src/api/{module} for easier discoverability and reusability.

to be just that ? The schema portion is pure interfaces, my understanding is that once you push bundles (which are JS so don't contain the interfaces) those would be gone. And when you publish individual components those get pulled apart as well.

**Comment by davelopez** [comment]
That is also a good point @mvdbeek, I'm no expert on that, but when the final bundle is done is supposed to have only what you actually imported as you mentioned, that is why we try to import individual functions instead of whole modules (I learned the lesson by doing the importing wrongly often but was catch in reviews :laughing:)

**Comment by mvdbeek** [comment]
I should qualify this is my belief on how things should magically work (TM) with no foundation in the real world.

**Comment by davelopez** [comment]
I've included a draft for a best practices guide in `client/docs/querying-the-api.md`, please don't hesitate to comment with your concerns and ideas for improvement so we can create a set of best practices that we all are comfortable with :)

**Comment by davelopez** [comment]
Look like test failures are unrelated. Taking it out of draft for the first wave of reviews :)

**Review by dannon — APPROVED** [review]

**Comment by davelopez** [comment]
Thank you!

**Pull request merged**
