### PR TITLE
Enhance the VTK datatypes to support cell data in addition to point

### PR DESCRIPTION
**Pull request by gregvonkuster**
data.
Replaces https://github.com/galaxyproject/galaxy/pull/1189.

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@martenson @bgruening @nsoranzo @erasche Can this be merged or is there something remaining for me to do?

**Comment by martenson** [comment]
Looks fine to me.

**Comment by bgruening** [comment]
:+1:

**Comment by gregvonkuster** [comment]
Thanks so much!

**Pull request merged**
