### PR TITLE
Workflow Editor PJA Argument Display

### PR DESCRIPTION
**Pull request by dannon**
In workflow editor PJAs we don't care to see this, and removing the overriding of 'argument' option fixes it.

### CODE REVIEW

**Comment by dannon** [comment]
Ping @guerler, make sure this looks like what we talked about.

**Comment by dannon** [comment]
Additionally resolves the regression noted in #674, adding input options back to the help text.

**Comment by bgruening** [comment]
@dannon is the regession fix worth to get into stable?

**Comment by guerler** [comment]
:+1:

**Pull request merged**
