### PR TITLE
Allow resizing of regular multi-select boxes

### PR DESCRIPTION
**Pull request by guerler**
resize-example

### CODE REVIEW

**Comment by martenson** [comment]
xref: https://trello.com/c/TSB0sIvD/2787-ui-optional-revert-to-ctrl-shift-multiselect-widget-for-hundreds-of-options-in-huge-data-column-parameters

**Comment by martenson** [comment]
Looks like the right thing to do. ping @fubar2

**Comment by fubar2** [comment]
Looks good to me. 
ping redirected to @bgruening

**Comment by bgruening** [comment]
Works for me as well! :+1: 
Thanks @guerler!

**Comment by guerler** [comment]
Cool. Thx.

**Pull request merged**
