### PR TITLE
[21.05] Fix remote file upload if Galaxy is served under a prefix

### PR DESCRIPTION
**Pull request by almahmoud**
Fixing uploading remote files when not on home page

## How to test the changes?
(Select all options that apply)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thank you @almahmoud!

**Comment by bgruening** [comment]
Nice! I think this has bitten us as well. Thanks a lot, @almahmoud for fixing it!!!

**Comment by almahmoud** [comment]
Tested and seems to work so i think it's ready for merge when the tests pass

**Comment by mvdbeek** [comment]
I could have sworn the selenium tests ran against a proxy prefix, but they don't. Maybe we omitted a variable when we moved the tests to github workflows. That would have caught it earlier. Thanks again @almahmoud!
Screenshot 2021-06-17 at 12 57 25

**Comment by jmchilton** [comment]
They used to when I was still using selenium server and the docker compose. I hadn't restored that testing functionality on Jenkins in the single container test - but maybe you did at some point? 

xref https://github.com/galaxyproject/galaxy/blob/release_18.09/.ci/jenkins/selenium-compose/run_tests.sh#L110

**Pull request merged**
