### PR TITLE
[15.05] include new logo in the new release

### PR DESCRIPTION
**Pull request by martenson**
Preview:
screenshot 2015-04-29 14 39 55

### CODE REVIEW

**Comment by martenson** [comment]
new preview
screenshot 2015-04-29 15 40 44

**Comment by blankenberg** [comment]
Probably should have pointed this out earlier, but this icon was originally a set of 2 intervals, with the second being subtracted from the first, with the result being the yellow interval, with the yellow interval not overlapping with the second, but does overlap with the first.

**Comment by martenson** [comment]
Nice history insight. :)

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Any chance we want to adjust this to match what @blankenberg points out, before pushing it as our 'official' logo in the masthead?  I'd be for it.

**Comment by martenson** [comment]
Work on logo began in January and I spent prolonged time discussing it with all interested parties (no remorse). I would much rather have the designer work on logos for CloudMan, Pulsar, or design for our new wiki/homepage and us working on features for GCC than revisiting something we agreed on 4 months ago.

In my opinion bro @blankenberg just needs to come up with a cool new story for the new logo ;)

**Comment by dannon** [comment]
@martenson I'm fine with that if @blankenberg is :)

**Comment by martenson** [comment]
ping @blankenberg

**Comment by blankenberg** [comment]
I think it was worthwhile to provide the context behind the original logo, and that its nice to have a reason to give for the question of 'what is meaning of the logo'/'where did it come from', but don't let me be the only thing standing in the way of getting it merged.

**Pull request merged**
