### PR TITLE
Fix for toolshed escape method, where an error/log message contains non-ASCII characters.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by hexylena** [comment]
is this to fix #503?

**Comment by blankenberg** [comment]
Not at all -- it fixes a unicode/binary to ascii casting issue that was observed as a server error when a installation/compilation log of a dependency failed and had non-ascii characters in it.

**Comment by hexylena** [comment]
Ah, okay, I mis-read that then. Thanks for the clarification. :) This looks good to me.... but is there a package known that throws non-ascii characters that could be used to test?

**Comment by dannon** [comment]
+1

**Pull request merged**
