### PR TITLE
[16.07] Create a uWSGI postfork function registry and start the tool conf watcher thread post-fork

### PR DESCRIPTION
**Pull request by natefoo**
`process_is_uwsgi` being in `galaxy.util.postfork` is maybe not the best place, but it's not any worse than in `galaxy.config` where it was.

This will hopefully fix the dead uWSGI worker issue we've been having on Main.

xref unbit/uwsgi#1149

### CODE REVIEW

**Comment by dannon** [comment]
@natefoo Nice!  Checking it out now.

**Comment by dannon** [comment]
@natefoo With the addition of https://github.com/natefoo/galaxy/pull/4, this solves it for me.  I added a bunch of extra debugging and verified that the update manager was the only other thread running (again, for my configuration) at launch time.

Edit: Added trimmed down debugging to launch time, just prior to webapp return/fork to make it easier to find potentially problematic threads down the road.

**Comment by natefoo** [comment]
Ah, that should be disabled by default. Did you explicitly enable it? If not, sounds like there's a bug.

Thanks! Glad to know we can confirm that it's the threads that's causing these issues.

**Comment by dannon** [comment]
@natefoo That'd be enable_tool_shed_check right?  (answering my own question: yes, and I did have it enabled on that test box)

**Comment by natefoo** [comment]
Ok good. It (like all threads) needed to be started postfork as well, so your change is good regardless. Should I wait for your uwsgidecorators investigation to merge natefoo#4 or can I merge as is? It's good from my perspective.

**Comment by natefoo** [comment]
Saw your comment on the PR so I merged it. Thanks for working on this!

**Comment by dannon** [comment]
@natefoo Want to include the warning in https://github.com/natefoo/galaxy/pull/5?

**Comment by nsoranzo** [comment]
I still have workers failing to start if `watch_tools = polling` , see https://gist.github.com/nsoranzo/41b5df22b73396421a168fa0c23f5a17

**Pull request merged**
