### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by nsoranzo**
Also merge dev dependencies in default Pipfile.

### CODE REVIEW

**Comment by nsoranzo** [comment]
It would be nice to have https://github.com/galaxyproject/starforge-recipes/pull/5 merged before this.

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
Green!

**Comment by martenson** [comment]
Thanks @nsoranzo !

**Pull request merged**
