### PR TITLE
[17.09] Only collect required attributes of linked steps

### LINKED ISSUE #5265: workflow run form initialization is very resource-demanding and causes browser crashes
originally reported by @blankenberg 

screenshot 2018-01-04 13 04 14

>it looks to be happening in the `_configure` function on the tool-form-composite
while running through each step of the WF it creates a very high stack of `fn.extend`
and takes 50s before it actually calls `render`
together with the 18s of getting data from API it makes ~80s loading time on ‘run form’ of a workflow
also it creates a very big heap, that is probably the reason why every subsequent operation on that tab has huge problems and/or crashes
I failed to measure just how big yet, because it crashes the developer tools while gathering it
the closest culprit for the stack is `visitInputs` in form-data https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/form/form-data.js#L197
`context = $.extend( true, {}, context );` maybe?
I think this line is what is causing the stack height
because visitInputs is recursive the context really bloats

edit: I analyzed the profile on the following workflow: https://usegalaxy.org/u/martenson/w/imported-browser-go-boom-mothur-miseq-sop-mod (which is a slightly modified version of https://github.com/galaxyproject/training-material/tree/master/topics/metagenomics/tutorials/mothur-miseq-sop/workflows/)
 
edit2: cpu profile from chrome devtools: https://files.gitter.im/galaxyproject/Lobby/y4lM/CPU-20180104T125048.cpuprofile

### PR DESCRIPTION
**Pull request by guerler**
Fixes #5265.

### CODE REVIEW

**Comment by dannon** [comment]
( We think it's exponential (or infinite) recursion into the steps being pushed back in by input matching search. )

**Comment by martenson** [comment]
I tested this branch with the test workflow and test history from @blankenberg locally and it fixes it. Thanks @guerler .

**Comment by martenson** [comment]
when looking at the increasing heap timeline it seems the callstack there is 


- timer fires [setTimeout( function() { promise.resolve() }, 0 );](https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/tool/tool-form-composite.js#L321)
- [process.reject();](https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/tool/tool-form-composite.js#L289)
- `setTimeout( function() { promise.resolve() }, 0 );` invoked
- [this.deferred.execute( function( promise )](https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/tool/tool-form-composite.js#L265)
- this starts new initialization on form-view [initialize: function( options ) {](https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/form/form-view.js#L7)
- the form starts rendering
- form-section goes through inputs `_.each( this.inputs, function( input ) { self.add( input ) } );`
- huge stack of `fn.extend`s follows

and this goes on and on (every 'red triangle' is a timer fired)

screenshot 2018-01-05 13 58 39


**edit: this is just trying to find the culprit, the heap does not seem unbound with this PR in place**

**Comment by dannon** [comment]
I think part of the problem is our approach to deep copying objects in a lot of this code.  I had another branch I was working on removing that (and doing some other misc cleanup, of course) that I'll PR to dev as soon as I'm sure it all still works without the deep copies, here:  https://github.com/galaxyproject/galaxy/compare/dev...dannon:client_deepcopy_fix?expand=1

**Comment by martenson** [comment]
@dannon if they are not necessary I am big +1 for dropping both `$.extend(true, )`s

**Comment by dannon** [comment]
@martenson Yep, that's what I've still got to figure out ;)

And, even if that *currently* breaks things (mainly the second deep copy removal in that PR, is what I'm worried about and need to test more -- the first is safe), I think we can restructure the data such that we don't need them.

(edit: and I'm going to check through the rest of the client to see where else we're doing similar things)

**Comment by guerler** [comment]
How about reducing the deep-copy to a flat-copy to improve the performance? This context variable is only used in form-composite: https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/tool/tool-form-composite.js#L173.

**Comment by dannon** [comment]
@guerler That's ~~definitely~~ (edit: potentially, I need to look at the context data structure in more depth -- it may not actually help much) an incremental improvement, but I'd like to follow up on a complete removal of the copy like I mentioned in the other branch.  I find it hard to believe we really must copy the context and can't remove the duplication and pass forward the context, potentially restructuring access so that all consumers work correctly.

In any event, if this fixes it in 17.09 (the first commit only) we should commit that and move forward, and follow up in -dev with other optimizations.

**Comment by guerler** [comment]
Im fine with that and appreciate it a lot that you are working on this. There is only one consumer for that context-based call. It's the one mentioned above in the previous comment. As far as I know at least a flat copy will be required but should not have any significant performance implications. Having said this, even removing the entire context block does not resolve the issue of this PR.

**Comment by dannon** [comment]
@guerler Right, that's why I was saying I was going to do it in a separate PR (targeting dev, not a stable branch), if we can just go ahead and get the first commit here in -- it's an additional improvement beyond the exponential recursion that was the core problem.

**Comment by martenson** [comment]
This fixes the crashing, I am 👍  on this, whether only first commit or both does not matter.

**Comment by dannon** [comment]
Sam and I talked and we're going to follow up on all the copying optimizations in -dev.  This definitely fixes the core problem which was the exponential recursion in input search.

**Comment by dannon** [comment]
(merging forward now)

**Pull request merged**
