### PR TITLE
flake8 test/tool_shed/ . Fix 8 Tool Shed functional tests.

### PR DESCRIPTION
**Pull request by nsoranzo**
- Fix 3435 flake8 errors.
- Fix a regression introduced in commit 0f2e2152ee17532488a8231cf1220ed9ddddb3aa .
- Fix 8 broken Tool Shed functional tests.

I'd suggest to look at the changes adding `?w=1` to [ignore whitespace changes](https://github.com/blog/967-github-secrets).

### CODE REVIEW

**Comment by martenson** [comment]
Looks good to me and what is more important: 
Ran 586 tests in 1094.786s OK
:+1:

**Comment by jmchilton** [comment]
AMAZING!!!!!! :+1:  +:100:

**Comment by bgruening** [comment]
Great stuff @nsoranzo! I wish I had more time for Galaxy these days.

**Comment by nsoranzo** [comment]
Thanks guys for reviews and compliments!

Have you considered adding to `.travis.yml` a new "py27-toolshed" tox environment executing `run_tests.sh -toolshed` or will it take too long?

**Comment by jmchilton** [comment]
I would be a `-.5` for adding it to Travis. They need to run and it needs to be visible though, I'd like to get jenkins or something to execute them at some point and report on PRs.

**Comment by martenson** [comment]
@natefoo agreed to prepare VM for our Jenkins, we should be able to make this and other pieces of the puzzle more visible soon

**Comment by hexylena** [comment]
@jmchilton ask and ye shall receive :) http://gx.hx42.org/job/galaxy/

Update: qunit tests failed due to missing grunt. I've since added grunt.

**Comment by hexylena** [comment]
(Until @natefoo / @martenson get y'all's jenkins VM online)

**Comment by natefoo** [comment]
@martenson @erasche Okay, I have a box ready, @martenson you should be able to log in to n2.galaxyproject.org.

**Comment by bgruening** [comment]
@natefoo let's turn it on :)

**Comment by natefoo** [comment]
@martenson https://jenkins.galaxyproject.org/

**Comment by martenson** [comment]
@bgruening and whoever else has galaxy-centric jenkins jobs: please create an account at https://jenkins.galaxyproject.org/ and send me a note with your name, I will give you permissions

**Comment by bgruening** [comment]
Awesome! Thanks @martenson I have an account.

**Comment by natefoo** [comment]
@martenson I am `nate`.

**Comment by martenson** [comment]
@bgruening you got the rights!
@natefoo you got the rights!

**Comment by nsoranzo** [comment]
xref: #391

**Pull request merged**
