### PR TITLE
Fix for mapping tools with paired collection input and a structured_like tag over list:paired collections

### LINKED ISSUE #3202: list:paired collections fail as input to tools with collection_type="paired"
If you create a simple list:paired collection and try to use this with the iuc's sickle (which accepts paired collections), the job submission fails with
```
The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool: Problem decoding element identifier {'src': 'new_collection', 'collection_type': '', 'name': u'r', 'element_identifiers': [{'__object__': <galaxy.model.HistoryDatasetAssociation object at 0x7fd43d0f00d0>, 'name': u'forward'}, {'__object__': <galaxy.model.HistoryDatasetAssociation object at 0x7fd420577950>, 'name': u'reverse'}]} - must contain a 'src' and a 'id'.
{
    "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/sickle/sickle/1.33",
    "tool_version": "1.33",
    "inputs": {
        "readtype|single_or_paired": "pe_collection",
        "readtype|input_paired": {
            "values": [
                {
                    "hid": 11,
                    "id": "54f2a3a23292eb07",
                    "map_over_type": "paired",
                    "name": "list of pairs",
                    "src": "hdca"
                }
            ],
            "batch": true
        },
        "qual_threshold": "20",
        "length_threshold": "20",
        "no_five_prime": "false",
        "trunc_n": "false"
    }
}
```
My understanding is that this should work and create a new job per paired dataset in the list collection, right?
I'm checking now if this is a recent regression (I'm on the latest dev).

### PR DESCRIPTION
**Pull request by mvdbeek**
collection input and a `structured_like` tag over list:paired collections.

I'm trying to fix #3202 here. This currently works, but is most likely a terrible way to do this,
and I can't get the test tool to pass.

@jmchilton do you have any advice here?

### CODE REVIEW

**Comment by mvdbeek** [comment]
So it looks like the tool test framework doesn't allow mapping over, i.e I can't pass a list:paired collection as input to a tool with paired input.
And the API testing framework doesn't seem to support the `structured_like` tag in tools, as that fails with
```
galaxy.tools: ERROR: Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "/home/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 1192, in handle_single_execution
    job, out_data = self.execute( trans, incoming=params, history=history, rerun_remap_job_id=rerun_remap_job_id, mapping_over_collection=mapping_over_collection, execution_cache=execution_cache )
  File "/home/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 1272, in execute
    return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
  File "/home/mvandenb/src/galaxy/lib/galaxy/tools/actions/__init__.py", line 349, in execute
    known_outputs = output.known_outputs( input_collections, collections_manager.type_registry )
  File "/home/mvandenb/src/galaxy/lib/galaxy/tools/parser/output_objects.py", line 123, in known_outputs
    collection_prototype = inputs[ self.structure.structured_like ].collection
AttributeError: 'NoneType' object has no attribute 'collection'
```

**Comment by jmchilton** [comment]
I pushed a fix to your test case - it wasn't executing the API call correctly to exhibit a subcollection mapping. I think it does now.

**Comment by jmchilton** [comment]
If you take it out of WIP I will merge this. Thanks for fixing this up - I'd be happy to +1 a backport of this as well.

I would say though that structured_like should never really be used with inputs that are definitely ``paired``. The more concrete you can be about outputs - the better Galaxy can reason about them upfront (I think the tools would be more intuitive also).

**Comment by mvdbeek** [comment]
> I would say though that structured_like should never really be used with inputs that are definitely paired. The more concrete you can be about outputs - the better Galaxy can reason about them upfront (I think the tools would be more intuitive also).

I agree, but how would you deal with read-trimming tools like trimmomatic and sickle, that take paired collections as input and output paired collections (I'm surprised no-one has hit this issue yet ... this seems like something everyone doing NGS needs to do). My understanding is that you could make them "list:pair" aware, and iterate over each pair individually (generating a single job per collection), but then you would lose the intrinsic parallelism of mapping a tool over a list. Or am I missing something obvious to do this?

**Comment by jmchilton** [comment]
@mvdbeek Do sickle or trimmomatic need to know about the whole collection to process the collection? I'd think simple mapping over a tool that consumes a ``paired`` and explicitly produces a ``paired`` would be fine. So use

```
  <outputs>
      <collection name="output" type="paired" label="Trimmed Pair">
  </outputs>
```

instead of

```
  <outputs>
      <collection name="output" structured_like="input" label="Trimmed Pair">
  </outputs>
```

I don't think ``structured_like`` in this context buys you anything that the explicitly ``paired`` output doesn't. Is there something I am missing - was the ``structured_like`` doing something I don't understand?

**Comment by mvdbeek** [comment]
Yep, but by default the element identifier will not be carried over (or is that a bug as well?!).
I suppose this could be set explicitly in the output collection (or the galaxy.json file).

**Comment by jmchilton** [comment]
That is a bug unknown to me. Are you sure about that?

**Comment by mvdbeek** [comment]
> That is a bug unknown to me. Are you sure about that?

I just tried it again (sickle without the `structured_like` tag), and it does keep the element identifier. Sorry for the false alarm.

**Comment by nsoranzo** [comment]
> I don't think `structured_like` in this context buys you anything that the explicitly `paired` output doesn't. Is there something I am missing - was the `structured_like` doing something I don't understand?

@jmchilton @mvdbeek Sickle needs to use `structured_like` in conjunction with `inherit_format="true"` because it can handle all various FASTQ subtypes, see https://github.com/galaxyproject/tools-iuc/pull/412 .

**Comment by jmchilton** [comment]
Does ``inherit_format`` not work without ``structured_like``? That sounds like a bug.

**Comment by mvdbeek** [comment]
Taking out `structured_like` but leaving in `inherit_format="true"` produces elements of type data. I'm not sure that without specifying what input to to inherit from you could really make sensible decisions though.

**Comment by jmchilton** [comment]
Okay - I was confusing ``inherit_format`` with ``format_source``. I'm not sure I'm very happy that I ever added ``inherit_format`` to the tool XML language. I understand what I was thinking - but it seems to encourage heterogeneous collections. I guess given the state of things - the current wrapper that uses ``structured_like`` is fine. Sorry for the confusion on my part.

**Pull request merged**
