### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by nsoranzo**
Cleaning up my stashed changes...

See individual commits for details.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
@mvdbeek I think the failing py34-unit test (which I can reproduce locally) may be due to https://github.com/galaxyproject/galaxy/pull/7071/files#r239664690

**Comment by mvdbeek** [comment]
Yes, but I don't think it matters, the repeat elements may be in any order for `expand_meta_parameters`. But I agree this isn't made clear in any way, I can fix it.

**Comment by nsoranzo** [comment]
In fact I was not sure what should be the content of those dictionaries, should I just strip the commit?

**Comment by mvdbeek** [comment]
Sure, I can add a separate PR with the commit and and the fix.

**Comment by nsoranzo** [comment]
@mvdbeek I've stripped the commit.

It seems that https://github.com/galaxyproject/galaxy-test-data/pull/2 broke `test/api/test_tools.py::ToolsTestCase::test_test_data_download_composite` though.

**Comment by mvdbeek** [comment]
yeah, it's 5 items now, can you fix the test?

**Comment by mvdbeek** [comment]
I've fixed the API test in #7171

**Comment by mvdbeek** [comment]
Thanks @nsoranzo !

**Pull request merged**
