### PR TITLE
Remove workflow export mako

### PR DESCRIPTION
**Pull request by guerler**
This PR migrates the workflow export Mako/Controller to Vue/Api. This is a replication of the original mako and required to move forward with #14687. The PR adds the `slug` attribute to the instance response dictionary and enables the component to request data directly from the regular api. Legacy controllers and makos have been removed and tests have been added.

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — COMMENTED** [review]
Looks good! :+1: 

For some reason generating an SVG from a workflow in my case throws a 500 error, because of that, I found out that there is still a reference to `/workflow/sharing.mako` in the `get_image` endpoint of the workflow controller around line 491.

**Comment by guerler** [comment]
Thanks for reporting this @davelopez. Can you verify that it displays a better message now? Thank you.

**Review by davelopez — APPROVED** [review]
Yes, a proper error message is now displayed, thank you!

It is being displayed on a new page though so you have to go back and reload, anyway, this can be improved in future revisions of the export UI, mako is gone so :rocket:

**Comment by guerler** [comment]
@davelopez thanks a lot for the quick and careful review, this helps a lot with moving forward and removing makos.

**Pull request merged**
