### PR TITLE
Global and profile-bound language configuration

### PR DESCRIPTION
**Pull request by abretaud**
Hi and happy new year!
I've started working on a possible solution to #4048, here's a first draft.

I added the new `default_locale` config option in galaxy.ini to let admins force a default language for their instance.
I also added a new user pref to allow each user to choose its preferred lannguage (overriding the global defaul_locale if defined).

This is my first attempt at modifying the client side code of Galaxy, so be indulgent :D 

Currently this code is not working properly because `window.Galaxy.config` is not defined when `utils.localization.js` is imported. I added some code to delay the locale loading after `window.Galaxy.config` is defined, but it doesn't work for all strings (some strings are localized before the `onloadLocaleConfig` callback gets executed)

Also, looking at [this TODO](https://github.com/galaxyproject/galaxy/compare/dev...abretaud:i18n?expand=1#diff-d8c7130ac6a2bfb0b66c5548f8a0c188L19) I wonder if I'm working on the good part of the client code.

If someone could guide me on the best way to go now it would be great!

### CODE REVIEW

**Comment by dannon** [comment]
@abretaud Thanks for taking a stab at this!  I worked on something similar a while back, and for the most flexible loading it looked like we should use a combination of the user preference interface and browser storage (`window.sessionstorage`, similar to the way I manage Galaxy tour transitions between pages).  Basically, on user login, or on preference save/reload, (when window.Galaxy is available), my plan was to set the locale in window.sessionstorage, which we could then use for that session, regardless of an existing full Galaxy context.

Does that help?  It would give us a way to handle the situation you describe when window.Galaxy is not available.  If you'd like for me to PR your branch implementing what I had in mind there, let me know!

**Comment by abretaud** [comment]
Sorry for the delay, yes it helps thanks! I'll make these changes as soon as I find a moment

**Comment by dannon** [comment]
@abretaud No worries at all, just let me know if I can help!

**Comment by abretaud** [comment]
It should be closer to what you have in mind now, what do you think?
It's not ready yet because currently you need to refresh the whole page for the user setting to take effect
Feel free to modify/PR if you have time!

**Comment by nsoranzo** [comment]
@abretaud That was not WIP any more, right? Just double checking.

**Comment by abretaud** [comment]
Ah yes, sorry, it's no more WIP, I just forgot to remove it after merging Dannon patch in https://github.com/abretaud/galaxy/pull/2

**Pull request merged**
