### PR TITLE
[15.07] Show tool parameter errors on initial tool form load. 

### PR DESCRIPTION
**Pull request by blankenberg**
Needed for e.g. proper rerun display behavoir.

### CODE REVIEW

**Comment by guerler** [comment]
+1 Makes sense and works.

**Comment by guerler** [comment]
I'll add this to a PR targeting dev.

**Comment by martenson** [comment]
@guerler we can just safely merge this to save the hassle

**Comment by guerler** [comment]
It would cause a conflict with the PR i am integrating it into.

**Comment by martenson** [comment]
got it, sorry

**Comment by guerler** [comment]
Hmm...for some tools and an empty history this does not look welcoming.
error_highlighting

**Comment by blankenberg** [comment]
I think that is correct, right. The (lack of) option selected by default on this tool form is invalid, so the user will have to change it before submitting the form.

**Comment by martenson** [comment]
I agree with it beeing correct but I also consider it scary for the user. Let's think about some friendlier/smoother way how to represent this.

**Comment by guerler** [comment]
Yeah, I was wondering what you guys think about the aesthetics of it, considering that the 'No tabular dataset available.' label already conveys the same information. Show only first one maybe?

**Comment by blankenberg** [comment]
Dataset could be optional, so 'no tabular dataset available' can be valid and not red.

**Comment by guerler** [comment]
How about showing only the first one?

**Comment by martenson** [comment]
So one thing that is not correct in my opinion is that we know we dont have a datasets selected so it is bloody obvious we do not have any columns. In spite of this we mark two sections red because of it.

**Comment by blankenberg** [comment]
Then the user would fix the one red one, click execute and the next ones would turn red.

**Comment by martenson** [comment]
Also it states 'Please try again' which is misleading, because the user might be trying this for the first time. Same with invalid option...the user just came and he/she is already being 'screamed at in red' with `invalid option`.

**Comment by guerler** [comment]
I agree and yes, the errors are often related. I think we should mark optional fields differently and not distinguish them by error messages if that is an issue.

**Comment by martenson** [comment]
Basically our form is punishing without giving the user a chance to even try. Can we turn these messages to 'info' on first open and reword them for this usecase?

**Comment by blankenberg** [comment]
Please try again is just bad wording on this particular tool's message in the `<validator>` -- its not a standard Galaxy message.

**Comment by guerler** [comment]
I think we agree that it does not look good enough, its too much red going on.

**Comment by martenson** [comment]
@blankenberg but that is because `validator` is expecting to be submitted at least once to actually validate things

**Comment by blankenberg** [comment]
I think it looks good actually. A user should really be aware that they need datasets before they run tools that need datasets for input.

**Comment by blankenberg** [comment]
You would still always need to validate against an input if it was available, and the validation should fail on first load if wrong (e.g. missing a particular species in the metadata, etc)

**Pull request merged**
