### PR TITLE
Update Client dependency, swap to node 16

### PR DESCRIPTION
**Pull request by dannon**
Now that we've branched for the freeze, it's time for our regularly scheduled early-cycle dependency updates for the client.

One large-ish change we should be careful of is the swap to node 16 (which is now the active LTS release), from 14, which is maintenance mode.

I have also dropped styleguidist here.  It hasn't proved to be useful and keeping it functional has been more work than it is worth.  Storybook now has a nice vue plugin, and I want to experiment with using that for a component workbench/demo tool down the road.

## How to test the changes?
(Select all options that apply)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
Hrmm.  That integration test that failed has to be unrelated, but I'll rerun it.

**Comment by mvdbeek** [comment]
Yeah, I can imagine the openpbs being flaky unfortunately. Certainly unrelated.

**Comment by dannon** [comment]
Should be good to go now.

**Review by guerler — APPROVED** [review]

**Comment by guerler** [comment]
I removed my local copies, rebuild everything and ran client tests using your branch and everything worked well.

**Pull request merged**
