### PR TITLE
Merge 21.01 -> dev

### PR DESCRIPTION
**Pull request by dannon**
Resolved conflicts below:

```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
    both modified:   client/src/components/Upload/UploadModal.test.js
    both modified:   client/src/components/WorkflowInvocationState/WorkflowInvocationDetails.vue
    deleted by us:   lib/galaxy/dependencies/pipfiles/default/pinned-requirements.txt
    both modified:   pyproject.toml
```

### CODE REVIEW

**Comment by davelopez** [comment]
I think this #11243 fix didn't make it to the merge.

**Comment by dannon** [comment]
@davelopez It looks like this branch includes that code to me; what are you seeing incorrect?

**Comment by davelopez** [comment]
@dannon I may be wrong, but I couldn't find [these commits](https://github.com/galaxyproject/galaxy/pull/11243/commits) in the commit list or the changes in the [Files Changed](https://github.com/galaxyproject/galaxy/pull/11292/files) 😅

**Comment by dannon** [comment]
It's because they were already merged forward, they wouldn't be listed here explicitly.  Test with:
```
> git branch --contains 934a905
```

**Comment by davelopez** [comment]
>It's because they were already merged forward, they wouldn't be listed here explicitly. 

Ohh! I see now!
Thanks for clarifying it and sorry for the noise 😅

**Comment by dannon** [comment]
No worries at all, thank you for taking a look at this!

**Comment by nsoranzo** [comment]
I think there's a mistake in merging the requirements, we should have `pulsar-galaxy-lib` pinned at `0.14.1` in `pyproject.toml` and `lib/galaxy/dependencies/pinned-requirements.txt` .

**Comment by dannon** [comment]
@nsoranzo Thanks -- I knew the client bits were right but I wasn't sure if those needed to be pinned in dev.  I'll fix this up.

**Comment by dannon** [comment]
(the last commit there includes the change in #11294 as well)

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
