### PR TITLE
[21.01] Single User Mode - Disable irrelevant and broken options

### PR DESCRIPTION
**Pull request by dannon**
## What did you do? 
- Assorted enhancements to generally hide interface options that are either broken or pointless in single user mode.

## Why did you make this change?
- #11413 

## How to test the changes? 
- [x] Instructions for manual testing are as follows:
  1. set `single_user` in galaxy.yml; observe UI and note 'sharing' and other options are gone.  Also, please look for things I missed that still don't make sense.

## For UI Components
- [x] I've included a screenshot of the changes

image

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
LGTM. There's still a lot of contextual menus pointing to shared links (e.g the workflow/history share menus), but this is a step up and we should probably set this in planemo serve, which is always going to be run in single user mode.

**Comment by jmchilton** [comment]
> we should probably set this in planemo serve

I think we're at least trying to do that. That is why we added the option I think.

```
planemo/options.py
680:def single_user_mode_option():
682:        "galaxy_single_user",
683:        "--galaxy_single_user/--no_galaxy_single_user",
687:              "is just one user and this user is automatically logged it. Use --no_galaxy_single_user "
1142:        single_user_mode_option(),

planemo/galaxy/config.py
569:    if kwds.get("galaxy_single_user", True):
570:        properties['single_user'] = user_email
```

**Comment by mvdbeek** [comment]
Hadn't used serve in a while ... that's cool then, thanks @jmchilton!

**Comment by dannon** [comment]
Thanks @mvdbeek!  Yeah, I was just trying to get a first pass in on most of the toplevel views -- I'm sure we'll keep finding stuff and can follow up on more later.

**Pull request merged**
