### PR TITLE
Update fastapi to 0.65.2 and dependencies

### PR DESCRIPTION
**Pull request by davelopez**
This supersedes https://github.com/galaxyproject/galaxy/pull/12128 and upgrades `fastapi` and also its dependencies as some of them include security fixes:
- `fastapi` from 0.63.0 to 0.65.2 see changes [here](https://github.com/tiangolo/fastapi/releases)
- `starlette` from 0.13.6 to 0.14.2 see changes [here](https://github.com/encode/starlette/releases)
- `pydantic` from 1.7.3  to 1.8.2 see changes [here](https://github.com/samuelcolvin/pydantic/releases)

I tried running `poetry update` but for some reason, in my machine, it keeps running for several hours and seems to be stuck in a loop. In the end, I tried to update the dependencies manually, but maybe someone has more luck/experience with `poetry` to make it work.

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by davelopez** [comment]
Investigating the failed tests...

**Comment by davelopez** [comment]
Ok, apparently the only breaking change is that now clients that send requests with JSON payload must specify the `Content-Type`  explicitly in the headers, [see this comment](https://github.com/tiangolo/fastapi/pull/2118#issuecomment-858155064)

It looks like we do so in the POST but not in PUT or DELETE (or any other method that may accept body payload) in the `GalaxyInteractorApi`. In https://github.com/galaxyproject/galaxy/pull/12136/commits/348922552b677188653e753fb3b1493d8f037a1b there is a quick&dirty patch to fix the tests, but I guess it would be nice to add the `as_json` parameters to them as well and maybe even use `True` as default. Maybe in its own PR?

**Comment by bgruening** [comment]
Can you add a "todo" to the last commit? I guess this hack needs to go away sooner or later.

**Comment by davelopez** [comment]
I guess the timeout in the failed test is unrelated since I only added the TODO comments in the last commit.

**Comment by mvdbeek** [comment]
> I guess the timeout in the failed test is unrelated since I only added the TODO comments in the last commit.

Yeah, timeout is unrelated. The preceding tests are uploading datasets but are not waiting until the upload is finished, so the job queues up and doesn't finish within 60 seconds. You can see it in the logs, job 21 is the job we're waiting for, while job 17/18/19/20 are still running

**Pull request merged**
