### PR TITLE
[15.10] Testing: update casperjs functional tests; change expected size strin…

### PR DESCRIPTION
**Pull request by jmchilton**
…g; remove nice_size from expected history api keys; remove test for rerun button on uploaded dataset; attempt to fix linux+python unicode error in hda api tests

(Back port of #944 to release_15.10).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Seems to fix 2 out of the 5 failing casperjs tests.

**Comment by jmchilton** [comment]
@nsoranzo Want to merge it then, I'll look into the remaining three.

**Comment by bgruening** [comment]
Aweseome!

**Comment by jmchilton** [comment]
I did a quick search and couldn't actually find anything that fixed those three failing tests :(. Leaving for the better part of a week now if someone wants to take up the hunt - it would be awesome to get these working in 15.10.

**Pull request merged**
