### PR TITLE
[20.05] Improve tool recommendations

### PR DESCRIPTION
**Pull request by anuprulez**
This PR improves tool recommendations by:
- Training on the latest workflows from the EU Galaxy server
- Showing recommendations coming from published and non-deleted workflows at the top (if available)
- Predicting recommendations even for tools present in low frequency in workflows (balancing training data by uniform random sampling)

This PR is dependent on the PR mentioned below:
The new model is available at https://github.com/galaxyproject/galaxy-test-data/pull/15

Some comparisons:

Category | Tool (or tool sequence) | Current recommendations | New recommendations
-- | -- | -- | --
Assembly | spades | bwa_memBowtie2fasta_filter_by_lengthprokkaabricatequastfasta-statsbandage_imageantismashmlst | 'bandage_image', 'fasta-stats', 'Bandage_info', 'bowtie2', 'bwa_mem' 'fasta_filter_by_length', 'prokka', 'abricate', 'quast', 'staramr_search', 'mlst', 'PlasFlow', 'busco'
Chemical TB | ctb_remDuplicates | None | ctb_remIons
  | ctb_remDuplicates,ctb_remIons | ctb_chemfp_mol2fps,ctb_compound_convert | 'ctb_chemfp_mol2fps', 'ctb_compound_convert'
  | ctb_remDuplicates,ctb_remIons,ctb_chemfp_mol2fps | ctb_simsearch,ctb_chemfp_butina_clustering | 'ctb_chemfp_butina_clustering', 'ctb_chemfp_nxn_clustering', 'ctb_simsearch', 'comp1'
RAD-Seq | stacks_procrad | Grep1,bwa,fastq_filter | 'fastqc', 'Grep1', 'bwa', 'fastq_filter', 'stacks_denovomap', 'bwa_wrapper'
Genome annotation | maker | gffread | 'gffread', 'maker_map_ids', 'jcvi_gff_stats'
Imaging | ip_filter_standard | None | 'ip_threshold', 'ip_count_objects', 'ip_histogram_equalization'
Mass spectrometry | mass_spectrometry_imaging_preprocessing | Mass_spectrometry_imaging_combine,Mass_spectrometry_imaging_mzplots,Mass_spectrometry_imaging_ion_images,mass_spectrometry_imaging_classification | Mass_spectrometry_imaging_preprocessing,Mass_spectrometry_imaging_mzplotsmass_spectrometry_imaging_qcMass_spectrometry_imaging_combineMass_spectrometry_imaging_segmentationsmass_spectrometry_imaging_ion_images
Single cell | raceid_main | None | 'seurat', 'raceid_trajectory'
  | rna_starsolo | 'dropletutils' | 'dropletutils', 'multiqc'
  | rna_starsolo,raceid_trajectory | None | 'raceid_inspecttrajectory
  | scanpy_regress_variable | Tool not available | scanpy_scale_data
  | scanpy_regress_variable,scanpy_scale_data | Tool not available | 'scanpy_run_pca', 'scanpy_find_variable_genes'
  | scanpy_find_cluster | scanpy_run_tsne,scanpy_find_markers,scanpy_run_umap | 'scanpy_find_markers', 'scanpy_run_tsne', 'scanpy_run_umap', 'scanpy_plot_embed'
SC HiC | schicexplorer_schicqualitycontrol | Tool not available | schicexplorer_schicnormalize
  | schicexplorer_schicqualitycontrol,schicexplorer_schicnormalize | Tools not available | 'schicexplorer_schicclustersvl', 'schicexplorer_schicconsensusmatrices', 'schicexplorer_schicplotclusterprofiles'
Animal detection on acoustic recording | vigiechiro_idvalid | None | 'vigiechiro_bilanenrichipf', 'vigiechiro_bilanenrichirp'

### CODE REVIEW

**Comment by anuprulez** [comment]
Is there any chance that this can be considered for 20.05 release? 
Thank you!

**Comment by guerler** [comment]
Please rebase, it'll clean up the commit history.

**Review by dannon — COMMENTED** [review]
It'd be nice to make this a configurable model, and remove it from the repository long term.  This way people could also generate their own based on the available toolset, etc., or download a pre-baked one for particular analyses.  It also frees updates to the model from the codebase, if people can always fetch the latest version regardless of their galaxy deployment revision.

**Comment by guerler** [comment]
As far as I understand, this is mostly how this feature has been implemented. The prediction model itself is not part of the code repository, the newest model is retrieved regardless of the Galaxy version and custom models can be selected through a configuration option.

**Comment by dannon** [comment]
Wow.  Yeah, you're right; I had opened both tabs (the galaxy-test-data one and this one) and got it all mixed up between when I opened them and came back to comment.  Oops :)  Disregard that completely, this looks fine, but +1 to cleaning up the unnecessary merge history here.

**Comment by anuprulez** [comment]
@dannon tool recommendation model and Galaxy version repository are separate. This model is created using a tool (will also be updated soon)

https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fcreate_tool_recommendation_model%2Fcreate_tool_recommendation_model%2F0.0.1

using workflows collected using this script (https://github.com/usegalaxy-eu/gxadmin/blob/master/parts/22-query.sh#L102)

The model can be created periodically (say every month or two months) using this tool using the latest workflows and can be uploaded to `galaxy-data` repository. We may think about automating this process.

Galaxy API 

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py#L637

will access this new model to recommend tools.

**Comment by anuprulez** [comment]
@guerler I tried to rebase it against `release_20.05` branch, but I do not think it was successful. Can we still work with it or shall I create another PR with the same changes with `release_20.05` base branch? Thanks!

**Comment by guerler** [comment]
@anuprulez yes please (:

**Comment by dannon** [comment]
@anuprulez Would you like for me to rebase it?

**Comment by anuprulez** [comment]
@dannon Yes, I will be very thankful :)

**Comment by dannon** [comment]
@anuprulez Done; the point at which I force-pushed was identical to the preexisting branch.  I then ran a `make config-rebuild` to sync up with upstream.

**Comment by guerler** [comment]
@dannon thank you!

**Comment by anuprulez** [comment]
@dannon thank you for merging this PR. But, these changes are related to the model coming from this another PR: https://github.com/galaxyproject/galaxy-test-data/pull/15
This should be merged as well otherwise the following config option 

https://github.com/galaxyproject/galaxy/blob/release_20.05/lib/galaxy/webapps/galaxy/config_schema.yml#L3048

would still point to the old model. Please also merge this one: https://github.com/galaxyproject/galaxy-test-data/pull/15

Thanks a lot!

**Comment by anuprulez** [comment]
@dannon sorry, @bgruening already merged it. Please ignore my previous comment :)

**Pull request merged**
