### PR TITLE
[16.04] Remove redundant ui divs, move masthead into #everything

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by guerler** [comment]
ping @carlfeberhard

**Comment by carlfeberhard** [comment]
+1

**Comment by dannon** [comment]
The way the masthead loads on some pages now seems jarring to me.  Removing the masthead div from galaxy.panels and adding it later makes pages like the workflow list, etc., load the content and then all of a sudden a dark blue masthead pops into existence at the top of the page.  Previously it was just the text which loaded in later (which I wasn't a huge fan of, but now it's _very_ obvious).

This seems like the type of component we should really ship a barebones display of with the original page, customizing menu contents later instead of just adding the whole thing at that time.

Which bug was this resolving?  It might still be worth doing this and working on something better later, if it's fixing something important, otherwise I'm not sure.

**Comment by guerler** [comment]
Ok, let me see if I can revise and resolve this.

**Comment by dannon** [comment]
Thanks for the fix, looks better!

**Pull request merged**
