### PR TITLE
Tour routing overhaul

### PR DESCRIPTION
**Pull request by dannon**
Now tour links actually work, don't look crazy, are shareable, etc.

### CODE REVIEW

**Comment by martenson** [comment]
Could the routing approach be described as:
 start with a client route whitelist (this PR) --> then proceed with blacklist (return 'the app' most of the time) --> finish with nolist (always return 'the app'). 
or am I missing something?

**Comment by dannon** [comment]
So, this particular PR really just resolves tour issues, but I was actually hoping it'd inform more route development.  Good eye :)

Adding the 'whitelist' style routes via add_client_route, like I have the two tour routes in this PR, is probably the solution I'd recommend.  I think it's important that the application actually return a 404 for known non-good routes, so I'd argue against just always returning root:index ('the app').

**Comment by martenson** [comment]
:+1: on this PR, good change

**Comment by bgruening** [comment]
Nice one. Thanks  @dannon !

**Pull request merged**
