### PR TITLE
Attempt to fix msa and phylocanvas vis plugins

### PR DESCRIPTION
**Pull request by gregvonkuster**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by gregvonkuster** [comment]
This doesn't cover all plugins here https://github.com/galaxyproject/galaxy/tree/dev/config/plugins/visualizations, many of which are not on this list. 

 I've found in Galaxy that both the msa and phylocanvas plugins throw a "Load function 'load' not found" error and do not display.  So I'm hoping this PR will correct this, although I'm not sure of more changes are needed.

**Comment by dannon** [comment]
@gregvonkuster I'll take a look at this today.  I think there's more to do here, at least for msa -- last time we updated that I had to perform a bit of surgery (https://github.com/galaxyproject/galaxy/pull/12782) to get it to work right again and the autobuild won't cover it.

**Comment by gregvonkuster** [comment]
Thanks @dannon!  Hindsight tells me I probably should have opened a ticket instead of this PR.  I'm happy to close it if that would be better.

**Comment by dannon** [comment]
@gregvonkuster Yeah, this is going to be more involved.  Feel free to close this out and I'll work on it this week if you want.

**Comment by gregvonkuster** [comment]
Thanks @dannon - much appreciated!  :)

**Pull request closed without merging**
