### PR TITLE
History structure

### PR DESCRIPTION
**Pull request by anuprulez**
This pull request replaces makos with VueJS for the history's "show structure" and history list's "view" functionalities. It should also fix the issue https://github.com/galaxyproject/galaxy/issues/5307.

**Note**: There were a couple of recursive routines written in mako to create the template for "show structure". I have moved these to a python script (/lib/galaxy/util). The logic here is a bit complicated to decouple the data dictionary and template in order to create the complete HTML at the client side.

### CODE REVIEW

**Comment by dannon** [comment]
@anuprulez Nice!  Checking this out now.  Also, note that there's no need to commit /static artifacts anymore -- we are no longer shipping prebuilt client files in the dev branch.

**Comment by anuprulez** [comment]
@dannon Thank you. The static files I pushed in were remaining to be committed even after doing "make client-production". I will just revert the last commit to remove all the static files (in that commit) and push in only the required file(s).

**Comment by dannon** [comment]
@anuprulez No worries, it's a new change.  Just leave /static files out of any commits/PRs moving forward and builds will be taken care of for release branches.  Ultimately it should make things way easier for contributors so we don't have to rebase and/or merge and rebuild as a part of the review process (in addition to preventing repository bloat).

**Comment by martenson** [comment]
We have pushed this to 18.05 but it may happen that we find time to get this to 18.01.

**Comment by martenson** [comment]
The fix has been backported to 17.09 (https://github.com/galaxyproject/galaxy/pull/5327)

**Comment by anuprulez** [comment]
@dannon I rebased this PR against dev and did not take out the static files which I already committed before.

**Comment by bgruening** [comment]
Restarted the failing selenium tests.

**Comment by dannon** [comment]
@bgruening Tests should be good to go; I was just waiting for someone else to merge since I added those commits above.

**Review by dannon — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @anuprulez and @dannon!

**Comment by anuprulez** [comment]
ping @bgruening

**Pull request merged**
