### PR TITLE
Add makefile target for release process

### PR DESCRIPTION
**Pull request by hexylena**
https://github.com/galaxyproject/galaxy/issues/715#issuecomment-169148056

Completely untested due to pushes to upstream. Lacks code to create a github issue because I was lazy. I'll add that later probably.

### CODE REVIEW

**Comment by natefoo** [comment]
@erasche awesome! Thank you!

**Comment by bgruening** [comment]
@erasche can we make `upstream` configurable. This would enable easy testing without changing remotes.

**Comment by hexylena** [comment]
@bgruening great idea! Done.

**Comment by hexylena** [comment]
Neat, thanks @jmchilton

**Comment by martenson** [comment]
thank You, Eric

**Pull request merged**
