### PR TITLE
Admin grid roles revision

### PR DESCRIPTION
**Pull request by guerler**
Removes grid and form makos used for the admin grid role handling. Branched from #4377.

### CODE REVIEW

**Comment by jmchilton** [comment]
Do you consider these new API endpoints part of the Galaxy API?

**Comment by guerler** [comment]
No, its still a controller endpoint. I am just using the decorator to enable API-like response behavior. Should we use a differently named copy of that decorator to avoid confusion? I could do that in a follow-up before release.

**Comment by jmchilton** [comment]
> Should we use a differently named copy of that decorator to avoid confusion? I could do that in a follow-up before release.

My broad concern is the general approach of not working with the API first - though a narrow, perhaps more pressing concern is that people might think this is a stable API. If we parameterized the newer expose API decorator (this older one should never be used for new stuff at this point right?) and made a variant that ignored API keys and only allowed the session to be used so that it wouldn't be functional as an API endpoint - that would make me feel better for sure.

**Comment by guerler** [comment]
I totally agree. The goal for the future of grids and forms is to work solely through actual API endpoints. The approach here is transitional and transforms the already existing controller endpoints to return json instead of html. This allows us to get rid of all grid-related makos first without modifying the API itself.

**Pull request merged**
