### PR TITLE
Add show/hide deleted/hidden links when history is filtered...

### PR DESCRIPTION
**Pull request by chambm**
by the find box; addresses #4103

I'm totally naive about editing the client (including adding a test to check this), but it works AFAICT...

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by chambm** [comment]
Also, the 'show deleted' and 'show hidden' language tokens are probably new (and unlocalized). I didn't think I could get counts of hidden and deleted files also matching the find criteria. But I didn't try, so maybe it would have worked.

**Comment by dannon** [comment]
@chambm Thanks for this, checking it out now.  

One quick note though is that you will need to make the client as well - `make client` from the galaxy root folder, and commit those changes.  I PR'd what that'd look like here:  https://github.com/chambm/galaxy/pull/2, which you can merge, or you're welcome to close that and do it yourself.

**Comment by dannon** [comment]
Still tinkering with it, but one minor defect here is that [No matching datasets found] is no longer rendered when clicking 'show hidden', etc., when there are no results.

**Comment by chambm** [comment]
I confess to not understanding where that message box comes from in the old code. It seems to come from the base template in history-view.js, but I don't understand how my changes prevent that from showing (but then I also don't understand why the old code was allowing to show either).

**Comment by dannon** [comment]
@chambm I'll take a look and see what I can figure out

**Comment by chambm** [comment]
Did you find out what caused the no matches infobox to disappear?

**Comment by dannon** [comment]
I made a lot of progress, but no solution yet.  I was about to merge this and bugfix that bit after the fact, so we don't hold up the release freeze (with the issue being purely cosmetic, and minor).

Basically, it looks like model attributes aren't being recognized, so the check to see "Do we know what we need to know to say there are no results?" fails incorrectly.

**Comment by chambm** [comment]
Yeah I do think it's a very minor bug because you get the "Found 0" caption in any case. Thanks!

**Pull request merged**
