### PR TITLE
[23.1] Fix toolshed sessionless access to a few APIs broken with..

### PR DESCRIPTION
**Pull request by jmchilton**
... https://github.com/galaxyproject/galaxy/commit/12b34ff47c3e4bb86e2ba5d8813a050c44b506bf

Likely the source the bootstrap script being broken as reported by @davelopez here https://github.com/galaxyproject/galaxy/pull/18538. 

## How to test the changes?
(Select all options that apply)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Still draft @jmchilton ?

**Comment by jmchilton** [comment]
I've retargeted this at 23.1 since that is where the tool shed is at. The tool shed was non-responsive the night I opened this PR and I couldn't figure out which version it was at.

**Comment by mvdbeek** [comment]
I don't think we're going to update the TS before we move to 2.0, can we just do dev ?

**Comment by jmchilton** [comment]
This fix is only for the old tool shed so I can start testing the new tool shed locally again 😆. This is not code that would be in use with the new tool shed.

**Pull request merged**
