### PR TITLE
[STABLE] fix metadata string formatting error @martenson reported yesterday

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by carlfeberhard** [comment]
+1

**Comment by blankenberg** [comment]
wouldn't this be better as something like this, where we let log handle the replacements, etc
log.exception( "Skipping file %s since it does not seem to be a valid exported Galaxy workflow: %s",
                                                   relative_path,  e )

**Comment by dannon** [comment]
That's definitely the _correct_ way to do it (and something pylint will complain about, for example), but it's not how we'd do it basically anywhere else.  Happy to update this if we want to start logging correctly :)

**Comment by dannon** [comment]
(then again, since this is a stable PR, I might lean towards explicitly fixing the string replacement issue and changing our logging approach going forward in dev)

**Comment by jmchilton** [comment]
:+1: For leaving as is in stable - stable PRs should be as small as possible IMO.

**Comment by blankenberg** [comment]
:+1: for logging correctly going forward

Don't let me stop someone else from merging this :)

**Comment by jxtx** [comment]
We do use log.exception properly in many places, so I don't think there is a consistency issue here. It should _always_ be used correctly period.

But, +1 for not worrying about it in stable.

**Comment by jmchilton** [comment]
If you guys feel so strongly about there being an "_always_" "correct" way to log "period" - we should probably add to the [BestPractices](https://wiki.galaxyproject.org/Develop/BestPractices).

**Comment by dannon** [comment]
@jxtx I'm not referring to log.exception use in general (we do get this right most of the time, these days -- it's something I usually fix myself), but for using log function string formatting correctly by supplying multiple arguments instead of in-place replacement using % (arg1, arg2) and so on.

**Comment by dannon** [comment]
@jmchilton good idea.  For this one, the _correct_ way to do this IMO is:

`log.exception( "Skipping file %s since it does not seem to be a valid exported Galaxy workflow", relative_path)`

With log.exception, there's no reason to include the exception in the message, that's automatic (this is the only distinction between Dan's suggestion above and this version).

**Pull request merged**
