### PR TITLE
Webpack bundle overhaul and initial dynamic loading.

### PR DESCRIPTION
**Pull request by dannon**
My first target for dynamic loading was the rule collection builder, since it and its dependencies (not shared, single parent) are huge.  

This pulls about **2.5MB** out of the compressed bundle loads and shifts it to being dynamically loaded on-use, fairly dramatically improving page load time.

Before (and keep in mind, this is *local* on gigabit ethernet):
image

After:
image

I have also dropped the gulp script/lib transpilation steps which were for providing the (deprecated) directly-accessed scripts for external consumption.  Everything is using webpack entrypoints now, whether via bundleEntries or a proper entrypoint like analysis, etc.

This also speeds up the client build significantly.  **I'm seeing build time drop from ~26 seconds to ~16.**

Opening draft to get selenium tests running.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Travis and CircleCI tests don't run on draft PRs, I'd keep using the `[WIP]` tag and `status/WIP` label for now.

**Comment by dannon** [comment]
@nsoranzo It's intentional, I actually just want the selenium test suite running, no need for travis/circle on this yet (I've run the relevant tests locally already and am happy with them).

**Comment by nsoranzo** [comment]
Cool, I was not sure that was the intention when I read `Opening draft to get tests running.`

**Comment by dannon** [comment]
@nsoranzo No worries.  I will update it to specify *selenium* tests.

**Comment by dannon** [comment]
I'm going to follow up separately with more bundle refactoring.  I think this is probably a good enough incremental for inclusion.

**Comment by dannon** [comment]
~(this will be rebased on top of #7544, when it is merged)~

And done.

**Comment by martenson** [comment]
Nice job. Lazy loading the 1MB of rule based uploader is valuable already and the future promise is great.

**Comment by dannon** [comment]
@martenson It's actually 2.6MB with its unique dependencies, larger than the entire analysis interface bundle, it's huge! Thanks for the merge.

**Comment by martenson** [comment]
@dannon see my questions in committers channel

**Pull request merged**
