### PR TITLE
Enforce client build deps are up-to-date.  Rebuild style with lessc > 2.5 

### PR DESCRIPTION
**Pull request by dannon**
(which everyone needs to update to now or we'll have battling commits of packed css)

`npm update` from your <galaxy>/client dir should do the trick.

Subsequent commits here also enforce node_modules versions are appropriate, which is the 'enhancement' bit.

### CODE REVIEW

**Comment by carlfeberhard** [comment]
Pre-emptive +1

**Comment by dannon** [comment]
(don't merge _quite_ yet, adding another update that'll force grunt to actually verify npm_modules are up to date.)

**Comment by dannon** [comment]
Thanks @carlfeberhard for noticing it wasn't actually enforcing versions.  Should now.

**Comment by guerler** [comment]
@galaxybot test this please

**Comment by jmchilton** [comment]
Is is odd to me that it won't run if you have extra modules, I needed to uninstall canvas. Is that reasonable?

```
Running "check-modules" task
Warning: Command failed: npm ERR! extraneous: canvas@1.2.2 /home/john/workspace/galaxy/client/node_modules/canvas                                                                     
npm ERR! not ok code 0                                                                     
 Use --force to continue.                                                                  

Aborted due to warnings.
```

**Pull request merged**
