### PR TITLE
[18.01] jobscript - check memory later

### PR DESCRIPTION
**Pull request by hexylena**
This tried to write to cwd before cd'ing and our upload jobs thus failed due to RO filesystem

### CODE REVIEW

**Comment by dannon** [comment]
Want to just backport https://github.com/galaxyproject/galaxy/pull/5880 ?

**Comment by hexylena** [comment]
That looks like it's still before the `cd`?

**Comment by hexylena** [comment]
@dannon looking again that was for an `scontrol` somewhere else on path so it had to be below the environment setup. That isn't my issue, mine is the filesystem is RO until galaxy moves into the temp dir.

**Comment by dannon** [comment]
@erasche Got it, that makes sense.  Is `$memory_statement` ever relevant to `$instrument_pre_commands`?  (just trying to nail down the correct ordering here, since we'll have to reconcile this change with malex's in merge)

Or, should it be:

```
cd
$memory_statement
$instrument_pre_commands
```

Looks like it'd likely handle your problem and malex's, leaving the memory statement available for those commands?

**Comment by hexylena** [comment]
unknown. @natefoo

**Comment by mvdbeek** [comment]
For the issue we were fixing it was only important that   `_galaxy_setup_environment` be before memory_statement, so this would be fine as well.

**Comment by dannon** [comment]
@mvdbeek Yeah, I'm sure this will work for that, too -- my main question is about the `$instrument_pre_commands` relying on `$memory_statement`.  I tried grepping around but I'm not familiar enough with it to know the implications of reordering those.

**Comment by jmchilton** [comment]
```python
class CorePlugin(InstrumentPlugin):
    """ Simple plugin that collects data without external dependencies. In
    particular it currently collects value set for Galaxy slots.
    """
    plugin_type = "core"
    formatter = CorePluginFormatter()

    def __init__(self, **kwargs):
        pass

    def pre_execute_instrument(self, job_directory):
        commands = []
        commands.append(self.__record_galaxy_slots_command(job_directory))
        commands.append(self.__record_galaxy_memory_mb_command(job_directory))
        commands.append(self.__record_seconds_since_epoch_to_file(job_directory, "start"))
        return commands
```

I think GALAXY_MEMORY_MB should be set before the instrument commands run. So #5880 looks better to me.

**Comment by dannon** [comment]
@jmchilton Ah-ha, thanks for digging that up, exactly what I was worried about.  To fix both of these, would my suggestion above work?

```
cd
$memory_statement
$instrument_pre_commands
```

**Comment by hexylena** [comment]
Is there any reason not to `cd` first? thereby avoiding any future similar incidents?

**Comment by jmchilton** [comment]
Sorry if this was waiting on me - yeah I think @dannon's suggestion is right - cd first absolutely now that I see what memory_statement is actually doing. Took my a while to realize this was in fact a different problem than the other one - sorry for being dense.

**Comment by martenson** [comment]
Do we have a consensus for this? Can we merge?

**Comment by dannon** [comment]
@martenson One sec.  I'll push a fix to this branch, and then it'll be ready.

**Comment by dannon** [comment]
@erasche Pushed one change here, what I had suggested in https://github.com/galaxyproject/galaxy/pull/5925#issuecomment-382756647.

**Comment by hexylena** [comment]
Sounds good @dannon

**Review by mvdbeek — APPROVED** [review]

**Pull request merged**
