### PR TITLE
Update the Copyright year in the LICENSE.txt.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Looks like a future job for p4.

**Comment by martenson** [comment]
@erasche can we just write like (c)2100 ? :D

**Comment by hexylena** [comment]
(@martenson in case you weren't joking, no, you cannot. It sure would make things easier though)

**Comment by jmchilton** [comment]
(@erasche in case you weren't joking about P4 - https://xkcd.com/1205/ - it better only take you 25 seconds to implement :stuck_out_tongue_winking_eye:)

**Comment by martenson** [comment]
@erasche I have always thought the whole copyright message useless as authorship rights are implicit in all countries with developed justice. This updating of years on random notices around the codebase is useless imo.

**Comment by martenson** [comment]
@jmchilton I am pretty sure @erasche has that table memorized and could draw it blindfolded.

**Comment by hexylena** [comment]
> This updating of years on random notices around the codebase is useless imo.

yep, agreed, but IANAL.

**Comment by martenson** [comment]
@erasche I bet you would be a better lawyer than many lawyers

**Pull request merged**
