### PR TITLE
[PROCEDURES] Clarify how +1 votes on PRs can be expressed v.3

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Review by dannon — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]

**Comment by blankenberg** [comment]
I think for the `approvals` to count as likely intended, under the current rules, actual plus ones should be cast.

**Comment by hexylena** [comment]
:+1:

**Comment by mvdbeek** [comment]
👍

**Comment by nsoranzo** [comment]
It seems this PR has enough votes (35.3%) and has been opened for more than 192 hours, so it could be merged.

**Comment by bgruening** [comment]
:+1:

**Comment by dannon** [comment]
+1 (literal +1)

**Pull request merged**
