### PR TITLE
Refuse to load interactive debugging middleware under uwsgi

### PR DESCRIPTION
**Pull request by dannon**
It doesn't work in a multiprocess environment.

### CODE REVIEW

**Comment by jmchilton** [comment]
Cool - good idea. :+1:

**Comment by dannon** [comment]
[Going to apply the same to the other apps, might as well, don't merge quite yet]

**Comment by dannon** [comment]
Applied to other apps, done refactoring, ready for actual review and merge.

**Comment by jmchilton** [comment]
Re-reviewed it, still like it. :+1:

**Pull request merged**
