### PR TITLE
Refactor History contents API

### PR DESCRIPTION
**Pull request by davelopez**
Preliminary refactorings in preparation for FastAPI migration of the Histories `contents` API, follow up to #12195.

For detailed information about the changes, please see each commit message.

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by davelopez** [comment]
I think this is ready for review.

Most of the work is around adding type annotations and pydantic models to be more explicit with the parameters needed in each action. As well as moving the logic out of the controller and into the `HistoriesContentsService` class to be reused by the future FastAPI router. Also, I tried to simplify a bit the logic when possible.

@Nerdinacan, I barely touched the `contents_near` action in this iteration, so it should be working as it was before (the API tests are passing) but if you want to manually test a bit just in case that would be great. About the `q/qv` filter parameters syntax I also find it a bit strange and verbose, but I guess the reason for using it like that was to differentiate a filter query parameter from any other kind of query parameter? I'm not sure :man_shrugging:

**Comment by jmchilton** [comment]
Very lovely! So much wonderful typing.

**Comment by nsoranzo** [comment]
I suspect this broke filtering history contents by types, at least for BioBlend : https://github.com/galaxyproject/bioblend/actions/runs/1047086204

@davelopez Can you have a look please?

**Comment by bgruening** [comment]
@nsoranzo David is on vacation for the next weeks.

**Comment by simonbray** [comment]
@nsoranzo it seems that in the old API `types` could be either a list or a comma-separated string. David restricted it here to accept only the latter (I assume that's deliberate and the whole point of adding types to the API).

So perhaps we fix it in BioBlend?

**Comment by davelopez** [comment]
Sorry for the late reply!
I will have a look, most likely I messed up with the restrictions because I tried to maintain full compatibility with the legacy API. But it's true that some endpoints are (maybe) *too flexible* in the sense that there are too many ways of expressing the same operation, with values in the query parameters or the body or both mixed and sometimes not totally consistent from one endpoint to another. It would be nice to agree on a `canonical` way and unify the API, but maybe on API v2.

**Pull request merged**
