### PR TITLE
Fix an error with getting the size of an object from Azure.  Attempte…

### PR DESCRIPTION
**Pull request by dannon**
…d to future-proof it if the library is fixed.

### CODE REVIEW

**Comment by dannon** [comment]
This is the bug followup mentioned in #2621

**Comment by mvdbeek** [comment]
The toolshed test failures are unrelated, they were introduced in #2554. I'll open a PR to fix those.

**Comment by dannon** [comment]
@zfrenchee To test this, you can just delete a dataset out of your object_store_cache (to force a re-fetch from azure).  Try to access this deleted dataset, and prior to this change, you'd see an exception bubble up and the dataset wouldn't be fetched. This makes it all work smoothly.

**Comment by jmchilton** [comment]
Thanks for the thorough testing @dannon - looks solid to me!

**Pull request merged**
