### PR TITLE
[release_15.07] Fix for valid height/width definitions in workflow rendering code, and fix identifiers.

### PR DESCRIPTION
**Pull request by dannon**
This is a retarget of #624 because I can't PR correctly.  Thanks @martenson.

### CODE REVIEW

**Comment by martenson** [comment]
This is actually targeting an issue found on both Galaxy and TS side. I have just seen this hapenning in an older Galaxy (GVL 3.04) and am trying to find what version is that.
edit: that was 14.10

**Comment by dannon** [comment]
Yep, this code hasn't changed in a long time -- I think the problem is likely that chrome or firefox (or the underlying osx library?) just got way more strict w/ SVG parsing and what we were generating before was malformed in a couple ways.  So, it's probably _always_ been broken -- browsers just didn't care and handled it correctly until now.  Just a theory, but all I can come up with right now :)

**Comment by martenson** [comment]
That reasoning sounds legit. Seems like all of the browsers are depending on the same XML parsing library because Chrome, FF, Safari all have problems :)

**Comment by martenson** [comment]
:+1:

**Comment by nsoranzo** [comment]
:+1:

**Comment by dannon** [comment]
Thanks for the merge.  Per @martenson's suggestion on irc, I'm going to backport this to 15.01 and merge forward.

**Pull request merged**
