### PR TITLE
Fix invalid quota amount

### LINKED ISSUE #14913: Quota with empty name causes internal server error
Creating a new quota in the admin panel and leaving all fields blank, causes an 500 internal server error. The server console shows the following error: `ValueError: Could not parse string ''`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev 23.01
Commit: c65237b6a914af0557b2a6de46fbb05eccef9051

**To Reproduce**
1. Logged in as admin, go to `/admin/quotas`
2. Click on `Add new quota`
3. Press `Save`

**Expected behavior**
A error message prompting to enter a valid name.

**Screenshots**
image

**Additional context**
I would expect an error message similar to the one found when following the same steps for `/admin/roles`:
image

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #14913

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by davelopez** [comment]
The failing Galaxy packages tests are unrelated

**Review by dannon — APPROVED** [review]

**Comment by mvdbeek** [comment]
I think this targeted the wrong branch. While I'm here, shouldn't we catch the invalid amount in the API ?

**Comment by davelopez** [comment]
> I think this targeted the wrong branch. While I'm here, shouldn't we catch the invalid amount in the API ?

:boom: 

Sorry I will cherry-pick and create another one targeting 22.05 :sweat_smile:

**Comment by mvdbeek** [comment]
> Do you mean in the pydantic model? We can probably reuse the regex + the other possible values ("unlimited", "none", "no limit")

I think that would be cool, yes.

**Pull request merged**
