### PR TITLE
Do not require stored workflow id for subworkflows

### PR DESCRIPTION
**Pull request by guerler**
Editing and saving an imported workflow containing subworkflows triggers an error. The subworkflow does not seem to have an associated stored_workflow. Is this here a reasonable fix? ping @jmchilton.

### CODE REVIEW

**Comment by jmchilton** [comment]
Do you know when this was broken? I don't think this has always been broken right? I'd like to see the change and how it worked before to jog my memory.

**Comment by nsoranzo** [comment]
The original code was introduce in commit https://github.com/galaxyproject/galaxy/commit/157939aa8f46b7599f48011d9f1e2c40c9f6cd47 .

**Comment by jmchilton** [comment]
I missed the key word *imported* - I guess this may have been broken and just not tested.

**Comment by guerler** [comment]
This changed with using the `update` endpoint of the workflow api to save workflows. In contrast to the previous controller endpoint, the api endpoint completes the request by returning a dictionary instance of the updated workflow, see: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py#L356. This fails for subworkflows which are part of imported workflows due to the missing stored workflow resource. I wonder where/if the stored workflow id is used for subworkflows.

**Review by nsoranzo — APPROVED** [review]

**Comment by jmchilton** [comment]
Thanks for the fix @guerler!

**Comment by guerler** [comment]
Awesome. Thx for the quick review.

**Pull request merged**
