### PR TITLE
[19.01] Improve string escaping and changeset validation on toolshed

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by nsoranzo** [comment]
This should target 18.05, I think.

Also, I'm going to push a commit that should fix https://jenkins.galaxyproject.org/job/docker-toolshed/13508/testReport/junit/shed_functional.functional.test_0000_basic_repository_features/TestBasicRepositoryFeatures/test_0130_verify_handling_of_invalid_characters/

**Comment by martenson** [comment]
the previous similar PR from January went to 18.09, but I am not against backporting

**Comment by jmchilton** [comment]
We shouldn't support tool sheds and haven't really promised to anywhere - let alone 18.05 tool sheds - I feel like targeting 19.01 is sufficient.

**Comment by nsoranzo** [comment]
@jmchilton Since we release the Tool Shed source code together with Galaxy's, I don't see how the Security Policy doesn't apply to it. Obviously we could amend the policy, if we decide to.

**Comment by jmchilton** [comment]
The security policy over and over mention's Galaxy's version, Galaxy instances, etc... it doesn't mention "code" or "code shipped with Galaxy" or alternative servers, or the Tool Shed. I think my reading of it is entirely reasonable.

**Comment by nsoranzo** [comment]
There has never been a separate Tool Shed repository or separate Tool Shed releases, Galaxy source code imports TS and viceversa. This clearly indicates to me that "Galaxy" in the Sec. policy refers to the entire "project".

**Comment by martenson** [comment]
Unless there are big obstacles/conflicts I volunteer to backport it.

**Comment by nsoranzo** [comment]
@martenson I've fixed the tests, can you double check that this still fix the original issue?

**Comment by martenson** [comment]
from gitter

> @nsoranzo I suspect there are more than 3 statuses
we might use 'warning'?
and I don't think we use 'info'
info seems like a reasonable default though, so let's just add warning?

**Comment by nsoranzo** [comment]
Thanks @martenson , I've rebased the latest commit adding `warning`.

**Comment by martenson** [comment]
@nsoranzo bleach seems to work well in my testing of these endpoints. This is ready I think.

**Review by nsoranzo — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
Merged forward.

**Comment by martenson** [comment]
backport: https://github.com/galaxyproject/galaxy/pull/7626

**Pull request merged**
