### PR TITLE
Fix to 4a61a4c: add hids for dataset inputs

### PR DESCRIPTION
**Pull request by carlfeberhard**
re: #2411 

@jennaj

### CODE REVIEW

**Comment by jennaj** [comment]
@carlfeberhard fabulous! thanks for this :)

**Comment by dannon** [comment]
This adds the hid in parameter listing, but not the inheritance chain.  Did we want to include both?

image

**Comment by martenson** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Didn't hear back, so this works fine and if we wanted to follow up with inheritance chain changes they can be in a separate PR.

**Pull request merged**
