### PR TITLE
Release notes for 21.05

### PR DESCRIPTION
**Pull request by mvdbeek**
## What did you do? 
- Create a draft of the 21.05 release notes

Don't remove the `.. enhancement/bug/etc` tags until we're about to merge the PR and finish the release process please.

### CODE REVIEW

**Comment by hexylena** [comment]
Added user facing.

**Comment by hexylena** [comment]
Weren't we going to start adding the contents of `scripts/release-diff.py` to document which options were new between this/previous release?

**Comment by mvdbeek** [comment]
Sure, just need to run it and add it, haven't added it to the release script yet.

**Comment by mvdbeek** [comment]
I think content-wise this is ready, just need to remove the markers when the last PRs are merged.

**Review by jmchilton — APPROVED** [review]

**Comment by hexylena** [comment]
This doesn't have the config file changes. Did you mean for me to do that @mvdbeek?

**Comment by mvdbeek** [comment]
The script didn't show any config changes, and I don't think there was anything ?

**Comment by hexylena** [comment]
https://github.com/usegalaxy-eu/infrastructure-playbook/pull/300/files#diff-5ade95009bcf33745dab730e600e2421e4302e2e732d1ff768a0837da5e08e09R716 This was new in 21.05 I know for sure, I wonder what happened.

This actually crashes for me, due to someone putting a tab in the user prefs conf.yml

```
$ python scripts/release-diff.py release_21.01
Traceback (most recent call last):
  File "scripts/release-diff.py", line 165, in <module>
    main(args.old_revision, args.new_revision)
  File "scripts/release-diff.py", line 135, in main
    new_contents = yaml.load(
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 70, column 7:
          	description: Your Dropbox account
          ^
```

which is there

image

After running I see

```
Configuration Changes
=====================

Added
-----

The following configuration options are new

config/user_preferences_extra_conf.yml.sample
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  preferences.dropbox.inputs
-  preferences.dropbox.description
-  preferences.owncloud.description
-  preferences.owncloud.inputs


Changed
-------

The following configuration options have been changed

config/user_preferences_extra_conf.yml.sample
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  preferences.localization.inputs has changed from ``[{'name': 'locale', 'label': 'Prefered language', 'type': 'select', 'required': False, 'options': [['Navigator default', 'auto'], ['Chinese', 'zh'], ['English', 'en'], ['French', 'fr'], ['Japanese', 'ja']]}]`` to ``[{'name': 'locale', 'label': 'Prefered language', 'type': 'select', 'required': False, 'options': [['Navigator default', 'auto'], ['中文', 'zh'], ['English', 'en'], ['Español', 'es'], ['Français', 'fr'], ['日本語', 'ja']]}]``


New Configuration Files
-----------------------

The following files are new, or recently converted to yaml

-  ``config/file_sources_conf.yml.sample``
```

**Comment by hexylena** [comment]
Which also doesn't list matomo/plausible, so, hmm. Ok, that's not good.

**Comment by hexylena** [comment]
Nothing is being discovered as it's all commented out in galaxy.yml. I guess it needs to check the diffing the schemas.

**Comment by hexylena** [comment]
ok, here's the final report of config diffs:

```
Configuration Changes
=====================

Added
-----

The following configuration options are new

config/user_preferences_extra_conf.yml.sample
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  preferences.dropbox
-  preferences.owncloud

config/galaxy.yml.sample:galaxy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  mapping.galaxy.mapping.cache_dir
-  mapping.galaxy.mapping.enable_celery_tasks
-  mapping.galaxy.mapping.flush_per_n_datasets
-  mapping.galaxy.mapping.matomo_server
-  mapping.galaxy.mapping.matomo_site_id
-  mapping.galaxy.mapping.plausible_domain
-  mapping.galaxy.mapping.plausible_server
-  mapping.galaxy.mapping.statsd_mock_calls


Changed
-------

The following configuration options have been changed

config/user_preferences_extra_conf.yml.sample
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  preferences.localization.inputs has changed from ``[{'name': 'locale', 'label': 'Prefered language', 'type': 'select', 'required': False, 'options': [['Navigator default', 'auto'], ['Chinese', 'zh'], ['English', 'en'], ['French', 'fr'], ['Japanese', 'ja']]}]`` to ``[{'name': 'locale', 'label': 'Prefered language', 'type': 'select', 'required': False, 'options': [['Navigator default', 'auto'], ['中文', 'zh'], ['English', 'en'], ['Español', 'es'], ['Français', 'fr'], ['日本語', 'ja']]}]``

config/galaxy.yml.sample:galaxy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  mapping.galaxy.mapping.citation_cache_data_dir.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.citation_cache_lock_dir.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.mulled_resolution_cache_data_dir.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.mulled_resolution_cache_lock_dir.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.openid_consumer_cache_path.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.template_cache_path.path_resolves_to has changed from ``data_dir`` to ``cache_dir``
-  mapping.galaxy.mapping.tool_cache_data_dir.path_resolves_to has changed from ``data_dir`` to ``cache_dir``


Removed
-------

The following configuration options have been completely removed

config/galaxy.yml.sample:galaxy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-  mapping.galaxy.mapping.transfer_manager_port


New Configuration Files
-----------------------

The following files are new, or recently converted to yaml

-  ``config/file_sources_conf.yml.sample``
```

**Comment by mvdbeek** [comment]
The changed section doesn't need to be in there, it's just internal changes that shouldn't matter to admins.

**Comment by hexylena** [comment]
Ok, it can be manually edited then. The preferences change to add spanish is, yeah, maybe important to admins, if they've edited the samples they won't get that update.

**Pull request merged**
