### PR TITLE
Fix for 13ea86753ad778aaaf6e6470a9370190fc2e91a0.

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes tests and functionality broken with 13ea86753ad778aaaf6e6470a9370190fc2e91a0 as spotted by eagle eye @nsoranzo here https://github.com/galaxyproject/galaxy/commit/13ea86753ad778aaaf6e6470a9370190fc2e91a0#commitcomment-13245289.

### CODE REVIEW

**Comment by martenson** [comment]
eagle :eyes: @nsoranzo

**Comment by hexylena** [comment]
@martenson :bird: :eyes: *

:P

**Comment by martenson** [comment]
@erasche that is cuckoo

**Comment by nsoranzo** [comment]
:laughing:

**Comment by nsoranzo** [comment]
Thanks @jmchilton! Now all API tests pass for me except for test_export_editor (see #734). Tool Shed tests also still pass.

**Pull request merged**
