### PR TITLE
[23.0] Fix build on macOS 12

### PR DESCRIPTION
**Pull request by jarrah42**
Using run.sh on macOS 12 results in an error when building the pysam package. This updates the version of pysam to 0.21.0 which appears to fix the problem.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jarrah42** [comment]
When I run `sh run.sh` it tries to build the wheel. Is there an option or something that needs to be passed to prevent this? Otherwise the "out of box" experience fails for macOS.

**Comment by martenson** [comment]
@jarrah42 What python are you using. Can you post the startup log?

**Comment by nsoranzo** [comment]
We are actually [disallowing pysam 0.21.0](https://github.com/galaxyproject/galaxy/blob/dev/pyproject.toml#L88) because it mistakenly brings in Cython as runtime dependency.

**Comment by mvdbeek** [comment]
python 3.11 wasn't supported on < 0.21.0 ... i would say that's probably worth the unnecessary cython dependency as a tradeoff ?

**Comment by nsoranzo** [comment]
Since this PR is against 23.0, adding a 0.20.0 wheel for Python 3.11 to wheelforge is probably more appropriate?

**Comment by mvdbeek** [comment]
It doesn't build on python 3.11

**Comment by jarrah42** [comment]
Did you try 3.11.1?

```
$ python --version
Python 3.11.1
$ pip install pysam==0.21.0
Collecting pysam==0.21.0
  Downloading pysam-0.21.0.tar.gz (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython (from pysam==0.21.0)
  Using cached Cython-0.29.34-py2.py3-none-any.whl (988 kB)
Building wheels for collected packages: pysam
  Building wheel for pysam (pyproject.toml) ... done
  Created wheel for pysam: filename=pysam-0.21.0-cp311-cp311-macosx_12_0_arm64.whl size=7191587 sha256=fb036dbc1185e71545ec2185dfda310f535c3fb7949a2eb9f4438df5484df0a1
  Stored in directory: /Users/gw6/Library/Caches/pip/wheels/52/2d/ed/b1e5c4ad36c535940dc1b1da900d05f571f88ff26f7be95f4c
Successfully built pysam
Installing collected packages: cython, pysam
Successfully installed cython-0.29.34 pysam-0.21.0
```

**Comment by mvdbeek** [comment]
Sorry, I'm saying your PR is fine because 0.20.0 does not build on 3.11, precluding a wheel on wheelforge.

**Comment by jarrah42** [comment]
> Sorry, I'm saying your PR is fine because 0.20.0 does not build on 3.11, precluding a wheel on wheelforge.

I see, thanks!

**Comment by nsoranzo** [comment]
@jarrah42 I've fixed this (and a couple more issues) in PR https://github.com/galaxyproject/galaxy/pull/16082 , which was just merged. I've targeted the dev branch for it because I believe that the macOS+Python 3.11 combination is too niche (not the typical production environment) to warrant multiple dependency updates in a stable release. Is it OK if we close this?

**Comment by jarrah42** [comment]
Sure, thanks!

**Pull request closed without merging**
