### PR TITLE
Initial implementation of data library search

### PR DESCRIPTION
**Pull request by martenson**
Kinda naive but works surprisingly well. I will work on this further.

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this please

**Comment by martenson** [comment]
@galaxybot test this please

**Comment by martenson** [comment]
galaxybot test this

**Comment by martenson** [comment]
Please review, this is not a WIP despite the wording of my first comment.

**Comment by carlfeberhard** [comment]
+1 Nice

Minor: may want a separate message when a search returns no results ('none found') instead of 'There are no libraries visible to you here'.

**Comment by martenson** [comment]
@carlfeberhard thanks for merge and feedback, will fix

**Pull request merged**
