### PR TITLE
Add stub fetch_eggs.py/check_eggs.py

### LINKED ISSUE #1030: scripts/fetch_eggs.py removed
File `scripts/fetch_eggs.py` was present in the last release (Oct 2015): https://github.com/galaxyproject/galaxy/blob/release_15.10/scripts/fetch_eggs.py

Recent work on the dev branch (by @natefoo etc) has removed various code to do with Python eggs. The removal of `scripts/fetch_eggs.py` has broken my TravisCI script which runs `python scripts/fetch_eggs.py` as part of setting up a test Galaxy instance. Currently only the stable branch Galaxy still works, the dev branch is broken, e.g.

https://travis-ci.org/peterjc/galaxy_blast/jobs/87703129

```
...
$ python scripts/fetch_eggs.py
python: can't open file 'scripts/fetch_eggs.py': [Errno 2] No such file or directory
```

What would the bootstrapping equivalent be for fetching Python dependencies? Use `pip install -r requirements.txt` perhaps?

### PR DESCRIPTION
**Pull request by natefoo**
...for people whose build/test/run pipelines may have been running these by hand. Print hopefully helpful information and return 1. Fixes #1030

### CODE REVIEW

**Comment by blankenberg** [comment]
`status/review`?

**Comment by natefoo** [comment]
@blankenberg yep, thanks

**Comment by blankenberg** [comment]
+1

**Comment by peterjc** [comment]
Looks good - seems very clear, thanks!

**Pull request merged**
