### PR TITLE
Migrate more CasperJS API tests to the API test framework.

### PR DESCRIPTION
**Pull request by jmchilton**
- Replace visualization tests (api-visualizations-tests.js -> test_visualizations.py).
- Replace dataset API tests (api-dataset-tests.js -> test_datasets.py).
- Start work on migrating history dataset API tests (api-hda-tests.js -> test_history_contents.py).

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@bgruening That selenium test is going to stay yellow I think because that test doesn't have the PR watcher enabled anymore. The only tests that would potentially fail for this PR are the Travis linting tests and the API tests - and they both pass. I think this should be an easy merge.

**Comment by bgruening** [comment]
And here we go :)

**Comment by bgruening** [comment]
Thanks John!!!!!

**Comment by jmchilton** [comment]
Thanks @bgruening!

**Pull request merged**
