### PR TITLE
Masthead Revision

### LINKED ISSUE #17476: clarify the visual language of selected masthead vs activity bar
Different items in activity bar are linked to different places in the masthead. Both activity bar and masthead have a "highlight" feature for the active item. It would be good to unify handling of this to prevent double highlighting.

See highlights for workflow invocation list below.

Screenshot 2024-02-14 at 3 02 12 PM
Screenshot 2024-02-14 at 3 02 22 PM

### PR DESCRIPTION
**Pull request by guerler**
The goal of this PR is to achieve consistency and reduce redundancy in the Masthead and align its functionality with the Activity Bar. The PR also contains improvements to the Activity Bar and Masthead as recently discussed during the UX team meeting.

1) @mvdbeek suggested that hidden and less frequently used activities should still be readily accessible. To account for that, the `Settings` activity has been replaced with a `More` activity. Users may still use this activity to add or remove items from the activity bar. Additionally, now users may also directly navigate to any activity using this panel.

2) @davelopez suggested that the username should be visible to the user and that accessing user preferences should remain in the masthead dropdown. This idea has been implemented, the username has been added to the masthead, user preferences and logout are accessible through the user tab. 

Resolves #17476, #17109, #17513.

https://github.com/galaxyproject/galaxy/assets/2105447/a8b16076-792b-4c05-b864-c9156b7d3ac8

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by martenson** [comment]
minor bug: Clicking on the storage graph as an anon user yields a client error, the link is supposed to be disabled without login.

The graph itself gained more prominence because everything around has disappeared and it also got bigger. It is now a dominant masthead item and I am not sure this information is that important, especially if you are way under the limit. I would support only showing the graph in cases where you reach certain threshold (maybe 75% of quota) and even in those cases I'd advocate for making it smaller. It is already dominant, it does not have to be large.

Screenshot 2024-06-28 at 12 11 58 PM

**Comment by guerler** [comment]
@martenson thanks for catching the anon/disable dashboard issue. I added a commit to fix it. Regarding further adjustments to the quota meter, I do actually like that it is displayed consistently and does not switch between just text and progress bar. I did try different sizes but was not entirely satisfied with the result, however we could have a focussed follow-up trying to improve its appearances in a separate PR moving forward. In this PR the focus was particularly on modernizing the underlying component and displaying it consistently.

**Comment by martenson** [comment]
Displaying username in masthead should probably trigger trimming at some point.
Screenshot 2024-06-28 at 1 28 51 PM

**Review by dannon — APPROVED** [review]

**Comment by martenson** [comment]
the brand is misaligned
Screenshot 2024-06-28 at 3 13 01 PM

**Comment by guerler** [comment]
@martenson thanks for the detailed review, added a commit to improve the brand alignment. The question mark click refresh issue was fixed in earlier commits. The GTN issue is related to the webhook implementation and unrelated to this PR.

**Review by martenson — APPROVED** [review]

**Comment by guerler** [comment]
Thanks for the review, I will follow-up with some of the suggestions regarding moving the data libraries to the activity section and revising the about page!

**Comment by martenson** [comment]
This is great @guerler ! I really like the clean masthead and focus on AB for the functionality

**Pull request merged**
