### PR TITLE
Run workflow form revision

### PR DESCRIPTION
**Pull request by guerler**
In order to reliably replicate the behavior of the current run workflow form, this PR contains a minimal, controller-consistent workflow api endpoint. It would be fine to remove this endpoint within this PR and redirect the client, once we understand why currently existing api endpoints and legacy variations are unable to replicate the basic behavior expressed by the current workflow controller endpoint. I think that the presented endpoint can assist to understand the differences.

Please set the galaxy.ini flag `run_workflow_toolform_upgrade` to `True` in order to activate the new run workflow.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by jmchilton** [comment]
I'm quite adamant that we should not introduce another workflow running endpoint - I know the implementation is complex but I've put a lot of work into testing, allowing many different options in a backward compatible way, and unifying every bit of copy and paste that went into the existing endpoints.

One problem with the invocation endpoint that backgrounds workflows is that it doesn't handle data inputs on workflows other than through formal workflow inputs. We could imagine connecting disconnected data inputs to new input modules automatically when loading an older workflow in the run workflow form and saving an updated workflow. I'd be totally willing to implement two Python functions or API endpoints like `requires_upgrade_for_api` and `upgrade_for_api` to enable the workflow run form to do this.

One problem is that this looses type information on the data inputs and it doesn't handle optional inputs. I have an issue for this and some WIP:
- https://github.com/galaxyproject/galaxy/issues/1325
- https://github.com/jmchilton/galaxy/tree/workflow_inputs
- https://github.com/jmchilton/galaxy/commit/e5c90192a8596799d941c85ddf24336aa6ebfc1a

Which sort of ground to a halt on `editor_form_generic.mako` not really being what we wanted going forward. I'd recommend a path forward on this as:
- @guerler taking over 1325 and building a better front-end form (and a framework that the newer input parameters to workflows introduced with https://github.com/galaxyproject/galaxy/pull/1306 and https://github.com/galaxyproject/galaxy/pull/1306/commits/45962f32344a00162f5d04b94096c8a570f2adf1 can plug into)
- @jmchilton implementing the upgrade API endpoints described above
- @guerler updating the run workflow form to check and auto-upgrade workflows as needed
- @guerler reworking this to use the invocation endpoint and requesting @jmchilton to add API functionality required to implement this

**Comment by guerler** [comment]
As I said, I am fine with redirecting the api endpoint to an existing endpoint. I am still not sure why this is not possible, particularly since the endpoint introduced here has just a ~100 lines and reproduces the most basic behavior. Why are current endpoints unable to reproduce this? This is the exact behavior displayed by the current run workflow form controller. The goal of this PR is to reproduce the behavior of the currently existing workflow form and not to introduce new features. My plan is to continue separating uncontroversial components from this PR, fix some remaining issues and revisit the endpoint issue at another time, maybe by the end of next week. If the consensus is to link it to an endpoint which does not fully comply with the existing forms functionality, I would be fine with that too.

**Comment by jmchilton** [comment]
You may be able to get this to POST to `/api/workflows/<id>` but that is deprecated and gives you fixed outputs - I'm not going to stand in the way of you doing that. But I do want to express that I think it isn't the right approach - I don't think it is worth building an GUI around those things. That fails for whole classes of workflows that will run today and allows behaviors we want to deprecate - the background workflow scheduler isn't some future goal that should be targeted - it works today and it works much closer to how we want workflows to operate long term.

**Comment by guerler** [comment]
The GUI can be quickly adjusted to any other endpoint we agree upon and I would be happy doing that, even within this PR, as long as the other endpoint is functional.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
Ok, so here is a list of previously existing features which regressed with the existing `invokations` api endpoint:
- Sending the outputs to one or multiple new histories
- Linked batchmode
- Unlinked batchmode
- Support for workflow parameters
- Support for data selection within steps
- Support for resolving output dataset ids and names
- Unaddressed queuing effect that the history does not auto-refresh anymore

The minimal api endpoint introduced here supports these features just like the existing controller endpoint. However, since we want to move away from prescheduling workflows, I modified the new endpoint such that it now always queues workflows just like the `invokations` endpoint. As a consequence the last two items in the above list are now outstanding again. Fortunately they are not critical and all other features are still supported. In fact it should be possible to transfer the reimplemented missing components from the new endpoint to the existing endpoint to revert the regression.

**Comment by jmchilton** [comment]
> Support for workflow parameters

This is supported I believe - https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_workflows.py#L1324.

> Sending the outputs to one or multiple new histories

I don't think you should build a WorkflowRunConfig directly - there is an existing abstraction that both API endpoints use and it seems to cover this functionality:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/run_request.py#L214

`build_workflow_run_config` would also cover workflow parameters if used properly.

> Linked batchmode
> Unlinked batchmode

The implementation here is okay and could probably be adapted in the invocation API? I wish it reused the tools stuff and I wish there logic wasn't placed 

> Support for data selection within steps

If this works - my intuition suggests either you are not properly backgrounding the workflow or encoded IDs are being saved to the database. I can fix the invocation endpoint to accept these - but previous @dannon and I purposely decided that we should discontinue support for non-input data selection. I don't know if his opinions have changed - but mine have't - it is a mistake to allow it. I've outlined how I believe it should be approached - but if you do not wish to do that and insist the API needs to support the data parameters we hoped to deprecate - I will begrudgingly update `build_workflow_run_config` and the invocation endpoint to allow this (will require a database migration I believe).

> Support for resolving output dataset ids and names
> Unaddressed queuing effect that the history does not auto-refresh anymore

This needs to be resolved longer term (there is an open issue about limitations regarding history updates - fixing it at the history level would help dynamic tool outputs, collection stuff, GIEs that publish to the history, this workflow endpoint, etc...) - but as a basic starting point the invocation landing page could take the invocation ID and poll the workflow and update the history as new datasets are created. Do you want me to do the UI for that?

**Comment by guerler** [comment]
xref: #2464

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
Thanks for the detailed response. Yes, please fix the invocation endpoint to accept these and add any other regressed feature to existing API endpoints such that they are consistent with the existing controller endpoint e.g. thanks for adopting the missing linked and unlinked batch mode features which were re-implemented in this PR by merging #2464. Without this feature users would have not been able to use any batch mode options with the new run workflow form. Correct me if I am wrong, but I noticed another feature which is not supported by existing API endpoints but by the endpoint presented here which is that data input modules should be able to submit multiple selections if associated with a multiple input data parameter. Now, the new API endpoint, which is the focus of this discussion and which is blocking the introduction of the new run workflow form, contains only about 50 lines.

**Comment by jmchilton** [comment]
@guerler  I'm disappointed, but if you fix the conflicts I will merge the PR.

**Comment by jmchilton** [comment]
I'm a strong `-.9` on this PR - it is a real step backward for running workflows in Galaxy. I spent months attempting to centralize and de-duplicate code for executing workflows and implementing a invocation-centric back-end for workflows that had some hope for interesting scheduling, features, and scaling.

**Comment by jmchilton** [comment]
@guerler I've chatted with a few people about this and been thinking about it myself - I have gotten the sense that perhaps you were just eager to get this done with so you can move on the tool form work? I'm not eager to take up the UI work needed to do this well - but if you are eager to just move on I'd rather do the work myself (or with the help of @martenson) than let this PR into a Galaxy release in this form.

If  over the next few months, I take over the form work you started would you be willing to revert this PR? Would this free you up to work on something you feel more passionate about - such as viz?

**Comment by dannon** [comment]
I don't want to speak for @guerler here, but it looks like he's tried to make this work with existing endpoints for quite some time before going this route.  In my opinion backing it out of the release isn't necessary if this serves a useful (if temporary, as specified in the PR summary) stepping stone for his work on the workflow editor.

Would adding words of warning to the endpoint documentation stating that it's not expected to be a permanent API addition, etc, be a reasonable compromise?  

```
Temporary API endpoint to support new workflow editor development -- this endpoint may disappear at any time, continue to use other endpoints for external API consumption.
```

Or, perhaps change the route name as well?

```
api/workflows/beta_run
```

There's a precedent for this sort of work being in releases in the history contents API and the handling of the 'dev' key, which swaps to index_v2, below, with different options and behavior. https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/history_contents.py#L470

**Comment by jxtx** [comment]
What about moving it to a location/route that is not under `/api`, to be clear it is not a supported stable API, and then remove it once the UI work to support the new endpoint is complete?

**Comment by dannon** [comment]
@jxtx I like that, too.

**Comment by guerler** [comment]
The issue is not really UI related, the problem is that the `newer` endpoints come with better scheduling behavior which we would like to benefit from but have skipped existing features to be fixed by others such as both batch mode options, data inputs within modules and proper history refreshing. Claiming that the `newer` endpoints are backward compatible or that they were just not used right without specifying how to use them, even within this thread, has caused severe delays and literally blocked our efforts to replace the existing workflow form and to work on the real challenges related to the new run workflow form i.e. performance/load times. It took till June 1 to accept that at least certain features are missing i.e.  `The implementation here is okay and could probably be adapted in the invocation API`. Although it was not part of this project, we had to demonstrate that an endpoint containing about ~50 lines of code is actually capable of replicating the currently existing behavior in order to remove the block placed on our efforts. Until today almost every workflow has been executed like this. In that sense this endpoint is not backward but current. I again suggest to integrate the dropped features into the `newer` endpoints and document their usage. It is trivial to redirect or adjust the workflow submission data to any other functional endpoint.

**Comment by martenson** [comment]
@guerler I agree the UI is not the challenge here and I also support @jxtx with moving the new (temporary) endpoint to something like `/beta` with the strong reason of making the API consistent, well-defined and _stable_. Hopefully by 16.10 we will be able to consolidate these endpoints into a uniform API that will strongly support both @guerler's and  @jmchilton's efforts.

**Comment by jxtx** [comment]
Maybe not `beta` but something like `private` or `internal` to make it clear noone should rely on it staying or becoming stable.

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/2622

**Comment by jmchilton** [comment]
There is no "regression' in the workflow invocation API - I don't like this framing and I don't think it is at all appropriate. The invocations endpoint was initially designed to replace the old workflow run API - and it is feature complete with respect to that - or at least the portion of that which has tests and which I understand. The act of replacing the workflow run form to target the API instead of a controller method is work undertook by @guerler and I guess is the scope of this PR. I don't think it is at all fair to claim I "skipped existing features to be fixed by others" - it is work I'd be willing to do, eager at this point, but we are going to ahead with a new API endpoint instead of continuing work on the existing API endpoint.

As for the 3 "regressions":
- I tried to engage in a conversation about the non-input module data inputs and there was no counter point made - it was an explicit design decision that three of us made in the past not to support them. I offered alternatives, I'd be willing to have a conversation about updating the data model to support them, but there is no conversation being had on this point.  Simply labeling this as a "regression", a feature the API never explicitly supported, is wildly unfair.
  - The batch mode inputs are things I would be willing to implement if this PR is backed out of and if I am confident future work on the API will be consumed by the GUI. I was busy leading up to the GCC and BOSC - but trying to salvage the motivation to work on this component I've poured my life into for the last two years is my top Galaxy priority at this moment.
  - As for history refreshing - the "new" invocations endpoint is meant to be RESTful. I'm not sure how the API would trigger history refreshes without websockets - I'd say it is clearly the job of the client to grab the invocation ID and refresh the history as it is scheduled. Both the API tests and the bioblend test suite have examples of doing this.

**Comment by jxtx** [comment]
@jmchilton Do you object to the compromise of having the workflow UI use a non-public non-API endpoint for the next release, and then working on changing the client / API / both to come up with a better solution in the next release? This lets us make some incremental progress while we reconcile the work you've done on creating an improved workflow invocation endpoint with the additional capabilities the workflow client UI needs (but, as you point out, were never part of the invocation API).

**Comment by jmchilton** [comment]
@jxtx I'm still discouraged, but I did merge #2622 which does exactly this.

**Pull request merged**
