### PR TITLE
make the 440 version linter an error

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref https://github.com/galaxyproject/galaxy/issues/15945#issuecomment-1514367877

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
The tool loads - this should be a warning as I originally defined them. We keep getting bit by the tools-iuc not blocking PRs on warning but that isn't a reason to change warnings to errors.

**Comment by nsoranzo** [comment]
> The tool loads - this should be a warning as I originally defined them. We keep getting bit by the tools-iuc not blocking PRs on warning but that isn't a reason to change warnings to errors.

It does load, but it's in the wrong place in the tool lineage, which I'd say it's an error not a warning.

**Comment by bernt-matthias** [comment]
>  The tool loads - this should be a warning as I originally defined them.

Then lets either add this PR or tighten the definition and doc of what an error / warning is

**Comment by bernt-matthias** [comment]
IUC fails now on warn. So I'm happy. 😎

**Pull request closed without merging**
