### PR TITLE
[24.0] Drop release notes webhook

### PR DESCRIPTION
**Pull request by dannon**
With the notification system in place we will be utilizing that moving forward.  This also allows instances to customize release notifications (e.g. can help in the situation where a site skips a release or wants to add more to the notification -- something like "we've upgraded from 23.1 to 24.0, see these two sets of release notes", etc).

If desired, we could have migrations or some other mechanism for generating these release note notifications (or something like that), but I think deferring to admins and seeing how they use this at first could be fine.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
LGTM!

**Comment by martenson** [comment]
Adding an admin highlight here as I believe this should be communicated to admins and showcased with a nice markdown example of how such a site-wide release notification looks like.

**Comment by dannon** [comment]
@martenson Good call, thank you!

**Review by martenson — APPROVED** [review]

**Comment by martenson** [comment]
thanks @dannon for remembering!

**Pull request merged**
