### PR TITLE
Vue component dangling bracket style fix (prettier upgrade)

### PR DESCRIPTION
**Pull request by dannon**
In a new release today the prettier folks have resolved a long-standing gripe we (and many, many others) have had when using it on Vue components, so I've upgraded and rerun it here.

This will likely conflict some existing PRs, but ping me and I will help you get it fixed up.

We can also wait until after the freeze and branch to get this into dev, if it's going to mess folks up for things we're trying to get into the release.

## How to test the changes?
(Select all options that apply)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
While I agree the current style is ... unattractive, I think it is more practical and the right choice. This style change (moving away from the default) will cause more PR conflicts. The contents of a "list" of things (in a broad sense) shouldn't affect how the "list" ends - this is why both black (https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas) and ESLint (https://prettier.io/docs/en/options.html#trailing-commas) now default to using trailing commas for literal lists, dicts, etc... I assume - even though on balance it isn't as attractive code. Giving each attribute its own line - including the last attribute - is the right thing to do IMO and should reduce the number of PR conflicts.

**Comment by dannon** [comment]
@jmchilton Personally I think the readability of the code outweighs the merge issue, but I get that it's personal preference.  We should just take a vote I guess.  I was pretty excited about this one though, I know it was the one thing about Prettier that drove James and I crazy when we first added it.

**Comment by jmchilton** [comment]
I think a vote is fine.

I think readability is important and part of that is clean diffs. I would say calling something unreadable because it is ugly is not how I use that word - I think this change makes the code prettier but it slightly hurts readability.

**Comment by OlegZharkov** [comment]
So how do we vote for it? Do you want to create an issue about it?

**Comment by dannon** [comment]
@OlegZharkov I'll toss this on the agenda for the UI/UX meeting next Tuesday, we can discuss and then toss a separate issue up for voting depending on what folks want to do.

**Comment by dannon** [comment]
Per conversation in UI/UX WG meeting, consider this comment a placeholder for voting.  Indicate 👍 or 👎 on this comment and we'll go from there.  Meanwhile, I'm going to rebase this and make sure nothing weird pops up.

**Review by OlegZharkov — APPROVED** [review]
Thanks a lot @dannon! That's a nice thing to do! I guess the voting has been made! :)

**Pull request merged**
