### PR TITLE
[16.01] Prepass on remote user header based on maildomain and normalize confi…

### PR DESCRIPTION
**Pull request by dannon**
…g.  This resolves an error reported on -dev with maildomain and user being set incorrectly due to changes in #1801 

Refactoring and cleanup to come in current branch, not applicable to 16.01.

### CODE REVIEW

**Comment by dannon** [comment]
Swapped to review for testing.  Since this will be applied to 16.01, I'm going to continue the refactoring in a separate PR; a big part of that is removing the toolshed's very slightly customized remote_user middleware and using a single consistent module and I don't want to backport that.

**Comment by dannon** [comment]
@martenson Do you know if the toolshed test that failed is one of the intermittent ones?

**Comment by martenson** [comment]
yeah, that is the only one expected to fail on 16.01 (as we retroactively disabled mercurial push)

**Comment by dannon** [comment]
@martenson Awesome, thought so.  Thanks for the confirmation!

**Comment by martenson** [comment]
@galaxybot test this

**Comment by nturaga** [comment]
+1

**Comment by dannon** [comment]
@nturaga Thanks for taking the time to test this!

**Comment by dannon** [comment]
(merging it forward through dev now)

**Pull request merged**
