### PR TITLE
Adjust link to the new Galaxy HUB site

### PR DESCRIPTION
**Pull request by bgruening**
Not worth to also commit static files I guess.

### CODE REVIEW

**Comment by nsoranzo** [comment]
This can maybe go in https://github.com/galaxyproject/galaxy/pull/3754 .

**Comment by bgruening** [comment]
This one is currently not redirected afaik. But I can close and PR against @dannon branch if needed.

**Comment by dannon** [comment]
@bgruening I can check for and add the redirect now, feel free to PR that branch of mine if you want, so we can collect it all there.

**Comment by dannon** [comment]
Edit:  Disregard, looks like we had a second *copy* of this page for editing purposes.  Anyway, redirect in place now, and we'll update this with the large set in #3754!  Thanks for noticing it!

**Pull request closed without merging**
