### PR TITLE
Use Galaxy logo instead of Logo/Text combo, refactor masthead to composition api

### PR DESCRIPTION
**Pull request by guerler**
Breaks out parts from: #14802.

- Refactors of Vue components to composition api.
- Replace default logo, consisting of logo and text with Galaxy Project logo:

Before:
image

After:
image

Note that this change deprecates the `display_galaxy_brand` configuration option, admins can instead use `logo_src` to replace the default logo and brand title.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Could we maybe use a logo with just "Galaxy" instead of "Galaxy Project". It's more concise, and I associate Galaxy with the application and Galaxy Project with the "organisation" that develops Galaxy and several other projects.

**Review by itisAliRH — APPROVED** [review]

**Comment by bernt-matthias** [comment]
logo_src is an image? Wouldn't like the idea to need to use an image editor to brand instances...

**Comment by bgruening** [comment]
@bernt-matthias I could be wrong but this option was just a boolean that displayed the "Galaxy" text next to the logo. The `brand` text that we add "Europe" or anything else is controlled by https://github.com/galaxyproject/galaxy/pull/15082/files#diff-ca364883be277c8546c5f46d50f68baa59bb3af32ded2f8dc0082a8898696962R1072 which stays and I agree its important to be easily changeable.

**Review by bgruening — APPROVED** [review]
Thanks @guerler and @itisAliRH for the review!

**Pull request merged**
