### PR TITLE
[21.05] Add timeout to all urlopen and requests.* methods

### PR DESCRIPTION
**Pull request by mvdbeek**
We've been seeing indefinitely hanging connections to the ENA ftp server.
Setting the timeout should help.
Fixes https://github.com/galaxyproject/galaxy/issues/11987.

In general I think it's best practice to set a timeout on all requests, so I've done that here as well.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Cool, its a bit unfortunate that we can not set this timeout globally. Thanks for going through all the code.

**Comment by mvdbeek** [comment]
We could set the global socket timeout, but that seems like it could have unintended consequences, within the libraries we're using... i wasn't sure about that, but that is an option.

**Comment by bgruening** [comment]
You could also argue that explicit is better than implicit, I just wonder how we can ensure that future additions are also adding the timeout. And a global setting would solve that. @jmchilton @natefoo ?

**Comment by natefoo** [comment]
Setting the global default to something very high (e.g. an hour) might be reasonable?

**Comment by mvdbeek** [comment]
> Setting the global default to something very high (e.g. an hour) might be reasonable?

Let's do that on dev ?

**Pull request merged**
