### PR TITLE
Expose tool config file path to admins via the API.  This is useful (…

### PR DESCRIPTION
**Pull request by dannon**
…not to mention already kinda exposed when using wrappers) for interfacing with planemo for the smc work and I would expect other automation tasks.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: - awesome thanks @dannon.

**Comment by bgruening** [comment]
Travis said: `'Bunch' object has no attribute 'user_is_admin'`?

**Comment by dannon** [comment]
@bgruening That's what we get for using a fake trans for testing..  Let me try to fix the tests.

**Comment by dannon** [comment]
Turns out that's a method!  Yay for tests, I think.  We'll see.

**Comment by dannon** [comment]
So the test actually was broken, but I found a bug anyway.  Should work w/ this last commit.

**Comment by kellrott** [comment]
Hope to see this merged soon ;-)

**Comment by bgruening** [comment]
Great, thanks @dannon!

**Pull request merged**
