### PR TITLE
Reduce server sided refresh requests to changes in data associated input fields

### PR DESCRIPTION
**Pull request by guerler**
This PR avoids server sided form refresh requests when numeric or text fields are modified which would significantly reduce the number of requests while configuring tools. A refresh is triggered when data assoicated fields are modified, or fields specified with the `refresh_on_change=True` flag. A refresh is also triggered when repeat blocks are removed or added, or a conditional parameter is modified.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Nice, cuts down on build requests a lot.

**Pull request merged**
