### PR TITLE
Visualization for free style image annotation

### PR DESCRIPTION
**Pull request by anuprulez**
This pull request adds an image annotator for `.jpg` and `.png` files. It can be used to draw freestyle shapes using different coloured pens. It comes with several other options like `redo`, `undo`, `erase`, `download` and so on. The downloaded images include the annotated image and an another image with just the annotations (both as `.png`). This visualization is built [paperjs](https://github.com/paperjs/paper.js) and jquery.

image

Annotated (downloaded) image:

original-with-annotations 4

Only annotations (downloaded):

only-annotations 4

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
@anuprulez I appreciate your effort in adding an image annotator tool to galaxy. My wishlist:

- free color definition
- polygon tool
- save to history tool
- support of tiff (time, n-channels, 3D, ...)

I'm happy to help, if you need support.
Inspiration: https://github.com/CSAILVision/LabelMeAnnotationTool
Also checkout: https://github.com/galaxyproject/galaxy/issues/7066

**Comment by martenson** [comment]
I am pushing this to 19.05 with aim to re-package this via the new plugin process so we do not have to include jquery and other libs.

**Comment by jmchilton** [comment]
@erasche gave me permission to push to 19.09, hoping to have a clearer path for viz by then.

**Comment by jmchilton** [comment]
@galaxybot test this

**Review by martenson — COMMENTED** [review]
@anuprulez could you please update this PR so it reflects the current best practices as defined in https://training.galaxyproject.org/training-material/topics/dev/tutorials/visualization-charts/tutorial.html ?

Namely it is converting all scripts included with things similar to `${h.javascript_link( app_root +  "js/d3.min.js" )}` into javascript `import * as d3 from "d3";` commands in the 'entrypoint file'.

We also want to include all the dependencies in the package.json file instead of copies of actual files and then committing them only once minified using the parcel app.

The viz itself seems to work fine, the only issue I've found is that using Chrome it only downloads the annotation, but not the full pic. Works fine under Firefox.
Inbox_-_emulatorer_gmail_com_-_Gmail

I'll keep this in 19.09 milestone until Friday. If it is not ready by then it will get pushed to 20.01. 

I like this viz, thanks for the contribution!

**Comment by anuprulez** [comment]
@martenson thanks for your review. I am facing a few issues with this PR while migrating it to `charts` visualization. I am able to download `paper`JS using `yarn`

```
(base) anupkumar@anupkumar-laptop:~/galaxy/my_fork/annotate_images_viz/galaxy/config/plugins/visualizations/annotate_image$ yarn add paper
yarn add v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved 1 new dependency.
info Direct dependencies
└─ paper@0.12.3
info All dependencies
└─ paper@0.12.3
Done in 3.57s
```

But, when I try to build it using `yarn run build` I get following error:

```
(base) anupkumar@anupkumar-laptop:~/galaxy/my_fork/annotate_images_viz/galaxy/config/plugins/visualizations/annotate_image$ yarn run build
yarn run v1.17.3
$ parcel build src/script.js -d static
⚠️  Could not load existing sourcemap of "../node_modules/paper/dist/paper-full.js".
🚨  /home/anupkumar/galaxy/my_fork/annotate_images_viz/galaxy/config/plugins/visualizations/annotate_image/node_modules/paper/dist/paper-full.js:16906:12: Unterminated string constant (16906:12)
  16904 | 			}
  16905 | 			if (/^(inline|both)$/.test(sourceMaps)) {
> 16906 | 				code += "\n
        | 				       ^
  16907 | 						+ self.btoa(unescape(encodeURIComponent(
  16908 | 							JSON.stringify(map))));
  16909 | 			}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The `paperJS` library is not getting bundled correctly using `yarn`. Other issues are related to the icons/images and CSS files native to this visualizations. I am not sure where to keep them under the `viz`? I tried to keep them `annotate_image/static/images` folder, but it does not seem to find those. 

I work on it and try to find maybe a better library for image annotation which can be easily integrated with Galaxy's viz/charts platform. I will try my luck with OpenLayers viz now.

https://github.com/galaxyproject/galaxy/pull/7888

**Comment by dannon** [comment]
@anuprulez Have you pushed a branch where you tried setting up the build process?  I can take a look today.

**Comment by anuprulez** [comment]
@dannon I checked-in the new code. thanks a lot for looking into it :)

**Comment by dannon** [comment]
@anuprulez It's not quite working yet, but I'm making progress.  We'll get this into the release.

**Comment by anuprulez** [comment]
@dannon thanks for your help. The viz works now as "charts" plugin. Users can download the annotated images (the positions of the annotations are preserved as such in the downloaded files). 

image_annotator

**Comment by martenson** [comment]
so if I understand correctly the paperjs cannot be 'parcelified' and has to be hard included?

**Comment by dannon** [comment]
@anuprulez if you're done with other changes now I'll reconcile this with the work I was doing yesterday to clean up and will push back to this branch.   I'm also going to rebase and strip out all the intermediate static builds.

@martenson that's part of what I was doing, I'll include it in an update after deconflicting this

**Comment by anuprulez** [comment]
@martenson When I use `import * as paper from "paper"`, this library does not get loaded. I had to use it from `node_modules`

@dannon Yes, all other changes are done from my side.

**Comment by dannon** [comment]
@anuprulez Ok, thanks.  I'll finish my part up then and will get it in.   I didn't expect more changes from you this morning so I think we overlapped a lot here, but I'll sort it out.

**Comment by martenson** [comment]
Heads up that today is the last day before the freeze. 

At the moment the viz seems to work fairly well, the download of annotated image in chrome has been fixed. Issues I found:

* when viz is saved in Galaxy, and loaded from 'saved visualizations' I only see the image without annotation
* there are bunch of js  errors on load:
Galaxy

**Comment by anuprulez** [comment]
@martenson I already had a look at the "saved visualizations" not saving the annotated images. I am not sure why. It does not seem to take the latest "canvas" object. I face the same issue with [map visualizations](https://github.com/galaxyproject/galaxy/pull/7888). It seems to store the source file.

I also checked the console log in Mozilla and Chrome but unable to see those errors you mentioned. The files like `jquery.migrate.js` are getting downloaded. I used incognito mode of the browsers.

Chrome:

chrome

Mozilla:

mozilla

**Comment by guerler** [comment]
Works for me! 👍

**Pull request merged**
