### PR TITLE
[16.07] UI, Modal: re-build dom on render

### PR DESCRIPTION
**Pull request by carlfeberhard**
Moves templating to render (and updates dom node attributes after)
to reset modal and prevent inline styling and other modifications
to the singleton from persisting between calls to show.

Edit:
To clarify, the issue solved here is that dom nodes added or modified on the modal (such as modal sizing, added sections, or removed headers/titles, etc.) would persist to the next modal.show call. This change allows the modal to render cleanly each time.

`Galaxy.modal.show({ title: 'testing', body: 'turned blue' })`
screen shot 2016-09-22 at 11 50 16 am

`Galaxy.modal.$body.css('background', 'blue')`
screen shot 2016-09-22 at 11 50 47 am

(then press 'Copy History') 
screen shot 2016-09-22 at 11 51 05 am

### CODE REVIEW

**Comment by carlfeberhard** [comment]
@galaxybot test this

**Comment by carlfeberhard** [comment]
@galaxybot test this

**Comment by carlfeberhard** [comment]
@galaxybot test this

**Comment by martenson** [comment]
very useful change
👍

**Comment by guerler** [comment]
👍

**Comment by martenson** [comment]
@carlfeberhard this is marked WIP, let me know if you want to merge it

**Comment by carlfeberhard** [comment]
@martenson All good now - we're set. 
Thanks for looking it over.

**Pull request merged**
