### PR TITLE
[17.01] Various bits of hardening from #4604

### PR DESCRIPTION
**Pull request by natefoo**
Forward merge of #4804 + backport of #4604.

### CODE REVIEW

**Comment by nsoranzo** [comment]
The changes look good, but I dont't think the rebase was a good idea. I tried to re-merge `release_16.10` in your branch and there were multiple conflicts.

**Comment by natefoo** [comment]
Interesting, I thought I did the same with no conflicts, but apparently not. =(

**Comment by nsoranzo** [comment]
Thanks @natefoo, I'll double-check again and merge later.

**Comment by natefoo** [comment]
Thanks! For what it's worth, the rebase was done to avoid having the same 5 commits duplicated 5 times when we finally get it all merged down to dev. I probably should have just squashed them on 16.07 so there'd only be 1 commit to merge forward.

**Pull request merged**
