### PR TITLE
This is an extra hammer swing at #1531 / #1542

### PR DESCRIPTION
**Pull request by dannon**
Historically this issue has been really, really hard to reproduce and figure out what is happening. 

@remimarenco Let me know if this resolves your issue.

### CODE REVIEW

**Comment by martenson** [comment]
xref #1531 / #1542

**Comment by remimarenco** [comment]
Thanks @dannon, both commits solve the issue.

**Comment by jmchilton** [comment]
:+1: Thanks @dannon.

**Comment by remimarenco** [comment]
Fun thing, I relaunched my workflow and it failed again but it did not prevent my tool to use the data generated (maybe because it uses the extra_files...but I am not sure what is the job cycle there).

The full error is:

```
Traceback (most recent call last):
  File "/home/galaxy/galaxy/lib/galaxy/jobs/runners/local.py", line 128, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/home/galaxy/galaxy/lib/galaxy/jobs/__init__.py", line 1321, in finish
    ActionBox.execute(self.app, self.sa_session, pja.post_job_action, job)
  File "/home/galaxy/galaxy/lib/galaxy/jobs/actions/post.py", line 563, in execute
    ActionBox.actions[pja.action_type].execute(app, sa_session, pja, job, replacement_dict)
  File "/home/galaxy/galaxy/lib/galaxy/jobs/actions/post.py", line 434, in execute
    sa_session.refresh(input_dataset.dataset.creating_job)
AttributeError: 'NoneType' object has no attribute 'creating_job'
```

Here is the screenshot, let me know if we need more informations.
screen shot 2016-06-15 at 8 23 53 pm

**Comment by remimarenco** [comment]
Reverting to the first commit (f7a6a2323d188b2eca7ed03d26c59dbcb636b30b) seems to be enough to get the workflow running apparently fine.

**Pull request merged**
