### PR TITLE
[WIP] Nose update with --debug option added to run_tests

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by jmchilton** [comment]
This nose update breaks planemo testing - I am looking into the planemo part of that but it abuses nose data structures in similar ways to the tool shed install and test framework - that is a greater concern in my mind.

**Comment by dannon** [comment]
Ach, yeah, I was focused on the Galaxy side.  I'll try the shed tests.

**Comment by jmchilton** [comment]
Unfortunately there are no tests for the install and test framework (https://trello.com/c/VHGB33Xp).

**Comment by dannon** [comment]
Yeaaah, this breaks more than I expected.  I was exclusively testing against the broken API tests that got me started going down this road.  Updating title with WIP to keep plugging at it without a merge.

**Comment by jmchilton** [comment]
Okay - actually and luckily it seems the IPluginInterface has remained pretty stable - so perhaps we don't have to worry so much about the install and test framework. The problem I encountered in planemo is due to XUnit plugin upgrades - and the tool shed does not use the xunit report.

Previously the XUnit report looked like this:

`<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="0" failures="0" skip="0"><testcase classname="functional.test_toolbox.TestForTool_cat" name="functional.test_toolbox.TestForTool_cat.test_tool_000000" time="13" /></testsuite>`

Now it looks like this:

`<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="0" failures="0" skip="0"><testcase classname="functional.test_toolbox.TestForTool_cat" name="test_tool_000000" time="11.776"></testcase></testsuite>`

Planemo just needs to do a better job parsing the class name and name together when building its report.

If you give me a day to upgrade Planemo and do a new release - I will happily :+1: this as it stands.

**Comment by dannon** [comment]
No rush at all, sure.

**Comment by jmchilton** [comment]
:+1:

**Pull request merged**
