### PR TITLE
Use eggs.require() instead of pkg_resources in lib/galaxy/datatypes/ .

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix https://github.com/galaxyproject/galaxy/issues/809#issuecomment-145107037 .

All the following tests pass for me:

```
tox -e py27-lint
tox -e py27-unit
tox -e qunit
./run_tests.sh -framework # on SQLite
./run_tests.sh -with_framework_test_tools -api # on PostgreSQL
```

Ping @bgruening.

### CODE REVIEW

**Comment by bgruening** [comment]
This looks great and it fixes my issue. But why is this needed did I miss Nate's egg/wheel work?
:+1:

**Comment by martenson** [comment]
@bgruening Wheels are not ready yet afaik. I think this is independent.

**Comment by martenson** [comment]
@nsoranzo FYI the `./run_tests.sh -with_framework_test_tools -api # on PostgreSQL` is now being run on every PR by jenkins, the results are next to the travis results;
once we have the other tests (api, toolshed, casperjs) passing, I will plug them in the same way

**Comment by nsoranzo** [comment]
@martenson I think jenkins runs `./run_tests.sh -framework`, not `./run_tests.sh -with_framework_test_tools -api` .

In some cases I like to run these tests before submitting a PR. Anyway, thanks a lot for working on the Jenkins tests!

**Comment by martenson** [comment]
@nsoranzo my mistake, however it runs them all, api are just not passing yet so we do not publish the runs :(

**Pull request merged**
