### PR TITLE
[20.09] Don't fail if object to copy is a MutationList instance

### PR DESCRIPTION
**Pull request by mvdbeek**
Also fixes
```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/workflow/modules.py", line 1761, in execute
    workflow_resource_parameters=resource_parameters
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/execute.py", line 103, in execute
    execute_single_job(execution_slice, completed_jobs[i])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/execute.py", line 74, in execute_single_job
    execution_tracker.record_success(execution_slice, job, result)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/execute.py", line 432, in record_success
    self.job_callback(job)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/workflow/modules.py", line 1759, in <lambda>
    job_callback=lambda job: self._handle_post_job_actions(step, job, invocation.replacement_dict),
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/workflow/modules.py", line 1812, in _handle_post_job_actions
    ActionBox.execute(self.trans.app, self.trans.sa_session, pja, job, replacement_dict)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/actions/post.py", line 517, in execute
    ActionBox.actions[pja.action_type].execute(app, sa_session, pja, job, replacement_dict)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/actions/post.py", line 103, in execute
    app.datatypes_registry.change_datatype(dataset_instance, action.action_arguments['newtype'])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/registry.py", line 590, in change_datatype
    data.init_meta(copy_from=data)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2783, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/data.py", line 171, in init_meta
    dataset.metadata = copy_from.metadata
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2705, in set_metadata
    self._metadata = self.metadata.make_dict_copy(bunch)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/metadata.py", line 161, in make_dict_copy
    rval[key] = self.spec[key].param.make_copy(value, target_context=self, source_context=to_copy)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/metadata.py", line 281, in make_copy
    return copy.deepcopy(value)
  File "/cvmfs/main.galaxyproject.org/deps/_conda/envs/_galaxy_/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/custom_types.py", line 232, in __deepcopy__
    return MutationList(MutationObj.coerce(self._key, copy.deepcopy(self[:])))
AttributeError: 'MutationList' object has no attribute '_key'
```
alternative to https://github.com/galaxyproject/galaxy/pull/10924

### CODE REVIEW

**Comment by nsoranzo** [comment]
Can't we use [sqlalchemy.ext.mutable.MutableList](https://docs.sqlalchemy.org/en/13/orm/extensions/mutable.html#sqlalchemy.ext.mutable.MutableList) instead of our own implementation (which predates the upstream one)?
For 20.09 we can just drop the `__deepcopy__()` method, which, deriving from `list`, is not necessary: it was added due to a Python 2.6 bug in commit 826f69fb6235c94bd1177d25616baa68cef37796 and upstream `MutableList` doesn't have it: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/mutable.py#L749

**Comment by dannon** [comment]
@nsoranzo +1, I had mentioned the same idea on chat.  The only reason we had to do this was there was no upstream solution back then.  Since there is, we should just swap over.  That said, I think it might be best to get this minimal fix into 20.09 as-is, and try the full swap in dev?

**Comment by mvdbeek** [comment]
Arg, just deleting the `copy` methods doesn't seem to be enough:
```
In [1]: from galaxy.model.custom_types import Mutation
   ...: List

In [2]: import copy

In [3]: x = MutationList([1,2,3])

In [4]: copy.deepcopy(x)
------------------------------------------------------
AttributeError       Traceback (most recent call last)
<ipython-input-4-4c90fdcacde0> in <module>
----> 1 copy.deepcopy(x)

~/.pyenv/versions/3.8.2/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173
    174     # If is its own copy, don't memoize.

~/.pyenv/versions/3.8.2/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    286             for item in listiter:
    287                 item = deepcopy(item, memo)
--> 288                 y.append(item)
    289         else:
    290             for item in listiter:

~/src/galaxy/lib/galaxy/model/custom_types.py in append(self, value)
    227
    228     def append(self, value):
--> 229         list.append(self, MutationObj.coerce(self._key, value))
    230         self.changed()
    231

AttributeError: 'MutationList' object has no attribute '_key'
```
Let's just replace it with the upstream solution.

**Comment by mvdbeek** [comment]
Well, that doesn't work because the sqlalchemy's MutationList/MutationDict don't track nested state and we use this in for instance in the HDA metadata dict. It does look like https://pypi.org/project/sqlalchemy-mutable/ would work, so trying that now.

**Comment by mvdbeek** [comment]
Ah, this library needs python >= 3.6 ...

**Comment by mvdbeek** [comment]
Targeting dev with https://github.com/galaxyproject/galaxy/pull/10935, and fixing the bug in a different way with https://github.com/galaxyproject/galaxy/pull/10934

**Pull request closed without merging**
