### PR TITLE
Fix large gap between labels and form elements

### LINKED ISSUE #16470: Large gap between labels and form elements
**Describe the bug**
The addition of html labels introduced a large gap between a form elements label and its associated input.

image

23.1:
image

23.0:
image

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
closes #16470

before | after
--- | --
image| image

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — APPROVED** [review]
Awesome CSS magic! :sparkles: 

(still forbidden dark magic for me... :laughing:)

**Comment by nsoranzo** [comment]
Maybe we could also add a bit more space between the "end" of a parameter block (usually the help, if present) and the label of the following parameter?

**Comment by ElectronicBlueberry** [comment]
I've made the changes and updated the "after" image in the PR.

**Review by nsoranzo — APPROVED** [review]
Looks great, thanks!

**Comment by dannon** [comment]
Definitely looks better here -- did you do a quick survey of other label[for] locations in the app, if that's a global override change?

**Comment by martenson** [comment]
thanks @ElectronicBlueberry !

**Pull request merged**
