### PR TITLE
Beta history current history mismatch with legacy code.

### PR DESCRIPTION
**Pull request by Nerdinacan**
## What did you do? 
- Added another sync subscription from Vuex -> legacy client to update the Galaxy.currHistoryPanel when the current history is changed by a user in the beta history panel.
- Modified the 2-way cache monitor to correct a flaw that was excluding some otherwise valid search results due to a logic error.

## Why did you make this change?
(Cite Issue number OR provide rationalization of changes if no issue exists)
(If fixing a bug, please add any relevant error or traceback)

Creating a new history from the beta history interface fails to properly update the current history to some of the legacy code. The flaw was noticed specifically when using the ever-broken desperately-in-need-of-replacement upload dialog.

@OlegZharkov noticed the issue while fixing another feature:
https://github.com/galaxyproject/galaxy/pull/11847

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. log in
  2. switch to beta history from the gear menu
  2. create a new history with the plus icon
  2. click open the upload tool by following the link in the empty history warning from your new history
  3. upload a new file
  4. wait for it to appear as a dataset in the (proper) currently displayed history in the beta history view

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

## For UI Components
- [ ] I've included a screenshot of the changes

### CODE REVIEW

**Comment by Nerdinacan** [comment]
Ok this fix is ready but it is actually conditional on several other PRs right now so I'm leaving it in draft status until they get merged.

The way I've been testing it is to load up a new history, click open the upload tool, upload a new file and wait for it to appear in the current history. The upload tool uses legacy code, the beta history (obviously) uses the new beta Vuex history code, and none of the updates will register until the polling can see the update_time changes.

Content provider debugging including polling and history switching...
https://github.com/galaxyproject/galaxy/pull/11693

Modifies update time so polling recognizes new uploads...
https://github.com/galaxyproject/galaxy/pull/11849

Fixed simple link to upload box...
https://github.com/galaxyproject/galaxy/pull/11847

**Comment by mvdbeek** [comment]
> register until the polling can see the update_time changes.

I've picked the last commit and cherry-picked it on top of https://github.com/galaxyproject/galaxy/pull/11849/commits. Upload works correctly and doesn't switch the history, and the "matches" indicator updates correctly, but the contents do not for some reason.

Screenshot 2021-04-19 at 09 25 42

**Comment by Nerdinacan** [comment]
> > register until the polling can see the update_time changes.
> 
> I've picked the last commit and cherry-picked it on top of https://github.com/galaxyproject/galaxy/pull/11849/commits. Upload works correctly and doesn't switch the history, and the "matches" indicator updates correctly, but the contents do not for some reason.

Ahh thank you, when I wrote that message my assumption was that the polling wasn't registering the change due to the imminate update_time changes on the database, I'll investigate further.

**Comment by Nerdinacan** [comment]
I know what the problem is, it's a flaw in my logic for the result aggregation.

**Comment by Nerdinacan** [comment]
This is all set.

**Comment by mvdbeek** [comment]
Hmm, yes, the first upload now works correctly, but when you upload a second item or you run a tool the new outputs don't appear (but the matches counter keeps incrementing correctly).

**Comment by Nerdinacan** [comment]
> Hmm, yes, the first upload now works correctly, but when you upload a second item or you run a tool the new outputs don't appear (but the matches counter keeps incrementing correctly).

For reals? Back to the drawing board...

**Comment by Nerdinacan** [comment]
Sometimes the legacy code is creating a new history when we simply want to switch to an existing one and sometimes not. I need to unravel this a bit.

**Comment by dannon** [comment]
Race condition with the server/session linked 'current history'?

**Comment by Nerdinacan** [comment]
> Race condition with the server/session linked 'current history'?

Could be. I'm going to trace back all the ajax calls to the backbone code and see what order they go out in. I have a fishy feeling that the server is deciding to make a new history when I delete the current history though.

**Comment by dannon** [comment]
Ahh, yeah, if you're actually deleting the current history then yes it could totally be a new one getting created -- that was (maybe still is, but definitely was at some point) the default behavior.

**Comment by Nerdinacan** [comment]
> Ahh, yeah, if you're actually deleting the current history then yes it could totally be a new one getting created -- that was (maybe still is, but definitely was at some point) the default behavior.

That's the way I keep testing it. delete the last test history. Make a new one. Upload a file. And it's in the wrong place.

**Comment by mvdbeek** [comment]
I don't think that is what is happening for the case I posted above. If the client wants to take over the history management (which is reasonable), we can turn off the new history creation when you delete the history that is marked as current.

**Comment by Nerdinacan** [comment]
> I don't think that is what is happening for the case I posted above. If the client wants to take over the history management (which is reasonable), we can turn off the new history creation when you delete the history that is marked as current.

@mvdbeek 
I definitely do think we should eliminate any surprise data creation on the server (unless we get a push-service working). I'm explicitly selecting the next "currentHistory" with a separate ajax call at present. When we delete the current history, I pick the first one off the list in the store, and if there's nothing in the store THEN I create a new one. I have a feeling that this can result in 2 new histories in certain circumstances if what you say is true.

But as for the flaw you pointed out, I'm seeing something similar that looks like a graphics bug but is really a consequence of the way the scroller works. It looks like a similar issue to the one you pointed out when I created the new scroller. The new rows are appearing above the area of interest and I had to manually scroll up to see them:


https://user-images.githubusercontent.com/290292/115610355-9a773180-a29d-11eb-9e9e-1bf7bd173152.mp4

I think this is a rendering problem that I have to figure out a solution for, but at least now I'm fairly certain we're tracking the right history.

**Comment by Nerdinacan** [comment]
I think I'm going to do another PR to adjust the scroll window as updates come in so it more naturally tracks the most recent updates (assuming they are at the top). My suggestion is to merge this because the history tracking part I think is finished.

I'll open another (hopefully easy) PR to address repositioning.

**Pull request merged**
