### PR TITLE
remote test data: add test for multiple=true

### PR DESCRIPTION
**Pull request by bernt-matthias**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Hi @davelopez just discovered that remote test data does not work yet for the `multiple="true"` case. I stumbled around in the code for some hours but have no idea how to fix this. 

Any ideas where to start would be appreciated.

**Comment by mvdbeek** [comment]
What did you try ? The framework tests do not use the test interactor.

**Comment by bernt-matthias** [comment]
I tried to planemo test this tool and in my attempts to debug it appeared that the upload got the comma separated URLs. Test just told me input staging problem.

**Comment by davelopez** [comment]
I guess the comma-separated URLs is not supported as `util.download_to_file` will not like it here:

https://github.com/davelopez/galaxy/blob/ecbf0972b57934c3f03fab34482339abd45e7a9f/lib/galaxy/tool_util/verify/interactor.py#L869

**Comment by bernt-matthias** [comment]
Where/how is the `test_data_downloader` used for staging input data? I can only understand how it works for output verification.

**Comment by bernt-matthias** [comment]
I guess we need to do the splitting earlier. It appeared to me that for `value` the splitting is done here: https://github.com/galaxyproject/galaxy/blob/62df2b0a987037e285e732a3717ec75767f6d757/lib/galaxy/tools/test.py#L190 (seems that this code is called when preparing the test dictionary ). 

Location is also used there, but only for determining the basename. I tried to also split it there .. but then realised that its not used :( 

At this point I got stuck yesterday.

**Pull request closed without merging**
