### PR TITLE
Improve resilience of filter detection, add error messages, fix identifiers

### PR DESCRIPTION
**Pull request by guerler**
When enabling toolbox filter examples from `galaxy.ini` without providing the associated python functions the `Toolbox filter` view is not accessible. A single error message indicating a backend error is displayed instead. With this revision the view is loaded and missing filter modules are highlighted individually. This PR also fixes faulty identifiers for section and label specifications.

untitled

### CODE REVIEW

**Comment by jmchilton** [comment]
This doesn't sound right - I just cloned a clean Galaxy and it started up without an exception. We have a Travis test that verifies it starts cleanly as well.

Do you have a missing filter set in your galaxy.ini? I would hope and probably expect Galaxy to fail to start if a filter is configured and cannot be found. I'm happy to see the message it fails to start with improve though.

**Comment by guerler** [comment]
@jmchilton, you are correct. It's related to declaring filter modules in `galaxy.ini` without providing the module files. I'll edit the description above. Thanks.

**Comment by dannon** [comment]
I'm with John here, I think that should be a fatal configuration error that requires a fix before Galaxy will start.

**Comment by guerler** [comment]
I was not clear. Galaxy starts up but the filter view in the user preferences does not appear. I'll see if I can improve the ui error message.

**Comment by guerler** [comment]
Thanks @dannon.

**Pull request merged**
