### PR TITLE
[STABLE] HDA API: deserializing None in misc_info/info as the empty string

### PR DESCRIPTION
**Pull request by carlfeberhard**

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/Pp54Xu6U) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/41.patch) for testing.

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
The PR is targeted at `#dev` instead of release.
Other than that this looks good.

**Comment by carlfeberhard** [comment]
Re-targeted: https://github.com/galaxyproject/galaxy/pull/43

**Pull request closed without merging**
