### PR TITLE
Don't show the pip progress bar when installing under CI

### PR DESCRIPTION
**Pull request by natefoo**
The CircleCI output is currently full of pip progress bars, this should greatly reduce the output.

### CODE REVIEW

**Comment by mvdbeek** [comment]
This doesn't seem like it had any effect on circle-ci ? https://circleci.com/gh/galaxyproject/galaxy/25358?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

The travis output seems reduced though, so perhaps they're not setting the CI variable ?

**Comment by martenson** [comment]
@mvdbeek it should https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by natefoo** [comment]
and it says it is here: https://circleci.com/gh/galaxyproject/galaxy/25352#tests/containers/0

**Comment by natefoo** [comment]
[This](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) is probably relevant:

> **Note:** You cannot use a built-in environment variable to define another environment variable. Instead, you must use a run step to export the new environment variables using BASH_ENV.

**Comment by martenson** [comment]
Do we care about the progress bar in any case?

**Comment by natefoo** [comment]
It's useful when you're running it from the command line.

**Comment by natefoo** [comment]
That's gotten it.

**Comment by mvdbeek** [comment]
Except for `test_galaxy_packages`, can you also add this to `packages/test.sh` ?

**Review by mvdbeek — APPROVED** [review]
Awesome, thanks so much @natefoo !

**Comment by nsoranzo** [comment]
Apparently this broke BioBlend tests on Travis: https://travis-ci.org/nsoranzo/bioblend/jobs/556564769
Not sure why, ideas?

**Pull request merged**
