### PR TITLE
Use HTTPS for phinch display application

### PR DESCRIPTION
**Pull request by hexylena**
At least here we're using https for this to psu. But do y'all want a https://phinch.galaxyproject.org? We're happy to host it (if y'all set the dns entry.)

### CODE REVIEW

**Comment by blankenberg** [comment]
Unfortunately this causes an issue with mixed content when the Galaxy instance isn't served from https.


image

**Comment by hexylena** [comment]
well.... the galaxy admins should use https then. Sigh, ok. I'll just keep this local

**Comment by blankenberg** [comment]
It would be cool if everyone could use https easily out of the box with out any additional steps. 

A cool thing to consider might be to automatically switch between http and https based upon the Galaxy instance's accessed URL, but it is probably more trouble than it is worth given the simplicity of copying the .sample to not .sample and adding one character.

**Comment by hexylena** [comment]
fyi: https://usegalaxy.eu/phinch/ 

Edit: Our version is patched for the following:
- @blankenberg's patch for URL loading
- remove chrome-only restriction
- remove google analytics (GDPR).

**Pull request closed without merging**
