### PR TITLE
Fix status handling for grids

### PR DESCRIPTION
**Pull request by guerler**
Fixes the status handling for grid messages. Ping @martenson. Does this fix the issue you mentioned in #4833? Thanks for reporting it.

### CODE REVIEW

**Comment by dannon** [comment]
This looks like it should fix it to me.

**Comment by jmchilton** [comment]
Sorry about the broken tests - I'm looking into it.

**Comment by martenson** [comment]
with this PR after trying to update TS status of a repo I get this in the JS console

```
Uncaught ReferenceError: str is not defined
    at Object.message (grid-template.js:443)
    at L.n.init_grid (grid-view.js:118)
    at Object.success (grid-view.js:719)
    at l (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at n (jquery.js:8757)
    at XMLHttpRequest.<anonymous> (jquery.js:9123)
```

**Comment by dannon** [comment]
I think @martenson's error is the line before; `String` vs `str`.

**Comment by guerler** [comment]
Thx I fixed that.

**Comment by jmchilton** [comment]
Is it surprising or not surprising at all that I was sitting here debugging Selenium tests in dev and noticed this ``str`` thing in [the error logs](https://jenkins.galaxyproject.org/view/All/job/jmchilton-selenium/429/artifact/429-test-errors/test_delete_and_undelete_history2017110116471509569252/browser.log.json). This fixes Selenium tests that are broken in dev. I need to get my act together on testing these PRs - we would have caught this ahead of time.

Thanks for the fix @guerler!

**Comment by guerler** [comment]
Me too.

**Pull request merged**
