### PR TITLE
[PROCEDURES] Issue procedure linkage

### PR DESCRIPTION
**Pull request by dannon**
Reopen of #974, because rules.

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1:

**Comment by jmchilton** [comment]
I think it may need to be opened with [PROCEDURES] in the title... but :+1: in case no one actually objects.

**Comment by hexylena** [comment]
:+1:

**Comment by martenson** [comment]
:+1:

**Comment by dannon** [comment]
@jmchilton You're probably right, I forgot about that in my annoyed state.  Tweaked, nobody saw it :)

**Comment by bgruening** [comment]
:+1:

**Pull request merged**
