### PR TITLE
Fix syntax of error parameter of tryCatch in setup_r_environment action.

### LINKED ISSUE #919: R installations possibly broken
details here: https://github.com/galaxyproject/galaxy/pull/893#commitcomment-13766844

ping @yhoogstrate @mvdbeek @bgruening @jmchilton

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix #919.

Ping @bgruening @yhoogstrate @martenson @mvdbeek.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
I got this one in dexseq:

```
* installing *source* package ‘Cairo’ ...
** package ‘Cairo’ successfully unpacked and MD5 sums checked
configure: error: Cannot use cairo-ft backend, although cairo claims it is working. Please check your caito installation and/or update cairo if necessary or set CAIRO_CFLAGS/CAIRO_LIBS accordingly.
ERROR: configuration failed for package ‘Cairo’
```

I am not sure whether it's your PR or cairo

Edit:
package_deseq_2_8_2 works

**Comment by mvdbeek** [comment]
@yhoogstrate it's cairo. This is very interesting. I have a fix over in https://github.com/galaxyproject/tools-iuc/pull/312 that I can separate out from the PR. Haven't tested this PR ( PR #929 ) right here yet.

**Comment by yhoogstrate** [comment]
deseq2 1.8.2 and package_r_edger_3_11_0 install flawless, and the error logs don't contain weird error messages in STDERR that should be picked up

package_r_ggplot2_0_9_3 fails with a compilation-failed-error and ends up in error state in Galaxy as it should:

```
 Rscript -e "tryCatch( { install.packages(c('rcpp_0.9.9.tar.gz'), lib = '/tmp/galaxy_r_fix/galaxy/tool_dependencies/ggplot2/0.9.3/iuc/package_r_ggplot2_0_9_3/07de191649b4', repos = NULL, dependencies = FALSE) }, error = function(e) { print(e); quit(status = 1) }, warning = function(w) { if ( grepl('had non-zero exit status|is not writable|installation of one of more packages failed', as.character(w)) ) { print(w); quit(status = 1) } } )"
STDERR
* installing *source* package ‘Rcpp’ ...
** libs
In file included from ../inst/include/Rcpp/sugar/logical/logical.h:27:0,
                 from ../inst/include/Rcpp/sugar/sugar_forward.h:29,
                 from ../inst/include/RcppCommon.h:324,
                 from ../inst/include/Rcpp/Date.h:25,
                 from Date.cpp:28:
../inst/include/Rcpp/sugar/logical/SingleLogicalResult.h:36:2: error: recursive type ‘Rcpp::sugar::conversion_to_bool_is_forbidden<x>’ undefined
  conversion_to_bool_is_forbidden<x>{
  ^
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
```

The fix of @nsoranzo seems to do the job correctly.

**Comment by bgruening** [comment]
:+1: from me as well.

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
