### PR TITLE
Support different authentication methods

### PR DESCRIPTION
**Pull request by nsoranzo**
This is a revised version of [BitBucket PR #555](https://bitbucket.org/galaxy/galaxy-central/pull-request/555/customauth-module-support/).

Initial modules:
- ActiveDirectory (LDAP)
- LocalDB (fall back to Galaxy user database)
- AlwaysReject (blacklist)

Sysadmin documentation at: https://docs.google.com/document/d/1CJp_m3vW7QKtAyBTMbE1MLgV6FAMuG3VO4HR-wHPkGk

Problems:
- still needs a yapsy egg (@jmchilton volunteered to port the code to the Galaxy plugin system)

Tested and approved by original author @andrewjrobinson .

### CODE REVIEW

**Comment by natefoo** [comment]
A bit more previous discussion on this PR can be found at galaxyproject/galaxy-beta1#4

**Comment by jmchilton** [comment]
Here is how I would rip out yapsy - 
- [ ] Make `AuthProvider` and abstract interface instead (methods seem right though). https://github.com/galaxyproject/galaxy/blob/d1cd4ab4d28c72f365852b75e2f2026c6b76ebbd/lib/galaxy/workflow/schedulers/__init__.py
- [ ] Delete all `-yapsy` files and just give auth implementation classes a short identifier as a class attribute (e.g. `plugin_type`).
- [ ] End implementation files with `__all__ = [ ImplementationClassName ]`.  This is kind of messy, not the way `__all__` should be used - feel free to fix.
  https://github.com/galaxyproject/galaxy/blob/d1cd4ab4d28c72f365852b75e2f2026c6b76ebbd/lib/galaxy/workflow/schedulers/core.py#L46
- [ ] Refactor `galaxy/auth/__init__.py` to basically produce some authentication manager object or something that could be stuck onto Galaxy app. (May be optional - the module-centric stuff instead of object-centric stuff is interesting and we could argue about - but Galaxy mostly configures stuff into objects attached to `app` for better or worse).
- [ ] Add helper to load plugins to the auth manager 

```
from galaxy.util import plugin_config
```

```
   def __plugins_dict( self ):
         return plugin_config.plugins_dict( galaxy.auth.providers, 'plugin_type' )
```

(E.g. https://github.com/galaxyproject/galaxy/blob/d1cd4ab4d28c72f365852b75e2f2026c6b76ebbd/lib/galaxy/workflow/scheduling_manager.py
or
https://github.com/galaxyproject/galaxy/blob/d1cd4ab4d28c72f365852b75e2f2026c6b76ebbd/lib/galaxy/tools/deps/__init__.py)
- [ ] Eliminate Yapsy plugin manager - but above dict should be pretty equivalent to `getPluginByName`.

**Comment by nsoranzo** [comment]
@jmchilton This WIP commit https://github.com/nsoranzo/galaxy/commit/b55edfe60d2dd0db72d81bfa9f07a6b92398ed12 should address your first 3 points.

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/NwyybQ8v) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/1.patch) for testing.

**Comment by jmchilton** [comment]
Picked up where @nsoranzo left off and merged directly - let me know if I broke anything. I made a lot of cosmetic changes to the code to make it mesh with Galaxy standards but the end-user usage should remain largely unchanged - no difference for deployers and plugin developers need to stick a `plugin_type` class attribute on their plugins instead of writing out a yapsy configuration file.

Many thanks to @nsoranzo and @andrewjrobinson and the people who reviewed the pull request in its various forms!

**Comment by martenson** [comment]
Thank you @jmchilton for driving this and @nsoranzo for the contributions. :+1: :+1:

**Comment by andrewjrobinson** [comment]
Thanks @nsoranzo and @jmchilton for your help here and others for your reviews.

I have tested the changes against the tests I used during development and found one bug with the auto-registration.  I have fixed this issue and retested.  The fix is currently sitting in my fork of this repo (https://github.com/andrewjrobinson/galaxy dev branch).  Should I submit another pull request or do something else to get it merged?

**Comment by nsoranzo** [comment]
Thanks @jmchilton for finishing and polishing it! I posted a comment on commit 9fd6685f4b165323b74be437fc82e78eb5fb2cb3 for you.

@andrewjrobinson I think a PR would be ideal!

**Comment by dannon** [comment]
@andrewjrobinson Yep, sending another PR is the best way to incorporate a bugfix.

**Comment by jmchilton** [comment]
Some possible follow up tasks here - https://trello.com/c/sxz9SM2R if anyone is bored.

**Pull request closed without merging**
