### PR TITLE
Remove legacy sample tracking api endpoints

### PR DESCRIPTION
**Pull request by guerler**
This is a follow-up on #4526 and contains parts of #4493. Recently we removed the sample tracking controller endpoints with its 35 makos which cleared up the admin ui and our front-end structure. Removing it's legacy api endpoints will allow us to perform a similar cleanup for the backend. The sample tracking features are well embedded with corner-cases in several base classes and legacy form functions. There are about +3k lines of code which can be stripped from core. This PR is the first step towards that goal.

### CODE REVIEW

**Comment by martenson** [comment]
- I would like to have this officially deprecated for at least a release.
- i would like to have feedback from people that were protective of the features in this API (e.g. @blankenberg  I think)

Besides that, I am +1 on stripping this down to model (and just leaving the DB untouched).

**Comment by guerler** [comment]
Did we not deprecate this feature in 17.09?

**Comment by martenson** [comment]
@guerler in RN we promised to keep API if configured (https://github.com/galaxyproject/galaxy/blob/release_17.09/doc/source/releases/17.09_announce.rst#deprecation-notices)

**Comment by guerler** [comment]
Ah I see.

**Comment by martenson** [comment]
@guerler the release is not out yet (🙄), so we can change if we have consensus

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
I noticed that the `deferred_job_queue` object was removed from the `job_manager` in 9b7775be03728f724c025a83bc7ffa9e28c2c932 and I wonder if users could still be using the sample tracking feature in a reasonable fashion through the api without submitting deferred jobs, see (legacy?) call to queue: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/samples.py#L91. 
ping @natefoo

**Comment by natefoo** [comment]
Deferred jobs were originally written to allow background transfers of data from sequencers, and were triggered internally via the web controllers. If they ever worked via the API I wasn't aware.

**Comment by guerler** [comment]
Thanks, that makes sense and explains why I am seeing hints of it in the api.

**Comment by jmchilton** [comment]
Red is my favorite color!

**Pull request merged**
