### PR TITLE
Render arbitrarily large collections in the UI.

### LINKED ISSUE #3795: Opening a huge collection in history fails
I have a tool in a workflow which can produce huge (>5000 datasets) collections. If I try to open it by clicking on the collection name in the history, nothing happens for some seconds till the Galaxy uwsgi workers goes out-of-memory and is killed.

I've enabled slow query logging (thanks @dannon for this), and I sometimes see this in the logs:
```
galaxy.model.orm.engine_factory DEBUG 2017-03-21 18:10:36,519 Slow query: 2.156251(s) for SELECT history_dataset_association.id AS history_dataset_association_id, history_dataset_association.history_id AS history_dataset_association_history_id, history_dataset_association.dataset_id AS history_dataset_association_dataset_id, history_dataset_association.create_time AS history_dataset_association_create_time, history_dataset_association.update_time AS history_dataset_association_update_time, history_dataset_association.state AS history_dataset_association_state, history_dataset_association.copied_from_history_dataset_association_id AS history_dataset_association_copied_from_history_dataset_a_1, history_dataset_association.copied_from_library_dataset_dataset_association_id AS history_dataset_association_copied_from_library_dataset_d_2, history_dataset_association.name AS history_dataset_association_name, history_dataset_association.info AS history_dataset_association_info, history_dataset_association.blurb AS history_dataset_association_blurb, history_dataset_association.peek AS history_dataset_association_peek, history_dataset_association.tool_version AS history_dataset_association_tool_version, history_dataset_association.extension AS history_dataset_association_extension, history_dataset_association.parent_id AS history_dataset_association_parent_id, history_dataset_association.designation AS history_dataset_association_designation, history_dataset_association.deleted AS history_dataset_association_deleted, history_dataset_association.visible AS history_dataset_association_visible, history_dataset_association.extended_metadata_id AS history_dataset_association_extended_metadata_id, history_dataset_association.hid AS history_dataset_association_hid, history_dataset_association.purged AS history_dataset_association_purged, history_dataset_association.hidden_beneath_collection_instance_id AS history_dataset_association_hidden_beneath_collection_ins_3, dataset_1.id AS dataset_1_id, dataset_1.create_time AS dataset_1_create_time, dataset_1.update_time AS dataset_1_update_time, dataset_1.state AS dataset_1_state, dataset_1.deleted AS dataset_1_deleted, dataset_1.purged AS dataset_1_purged, dataset_1.purgable AS dataset_1_purgable, dataset_1.object_store_id AS dataset_1_object_store_id, dataset_1.external_filename AS dataset_1_external_filename, dataset_1._extra_files_path AS dataset_1__extra_files_path, dataset_1.file_size AS dataset_1_file_size, dataset_1.total_size AS dataset_1_total_size, dataset_1.uuid AS dataset_1_uuid 
FROM history_dataset_association LEFT OUTER JOIN dataset AS dataset_1 ON dataset_1.id = history_dataset_association.dataset_id 
WHERE history_dataset_association.id = %(param_1)s
```

The `LEFT OUTER JOIN` looks suspicious to me here.

xref #3054 from my colleague @anilthanki.

### PR DESCRIPTION
**Pull request by jmchilton**
This builds on #5038 (render arbitrarily nested lists in the UI) and fixes #3795 (which is both a usability problem with large collections and serious backend memory issue). Only around 1000 elements of a collection will be rendered now and these will be fetched much more efficiently. It'd be nice if we could paginate or progressively fetch more elements beyond that - but that should probably wait for a major rewrite and be tied with search and such to make navigation of such collection possible.

This problem is tackled along three prongs. 

1. Reduces the transfer size, number of database fetches, and number of database joins to pull out the history collection structure for rendering a collection in the UI. a475f9c
2. Introduces the concept of "fuzzy count" limit when fetching large collections - to limit the order-of-magnitude-per-level-of-depth of the collection fetched via the API while still fetching the collection at every level of depth for nested collections. 62c3e9c
3. Updates the UI for more consistent collection subtitles, display of element counts, and warns the user if only a subset of elements are being display.

This screenshot generated on Jenkins from this PR is of a collection that is rendering a more limited number of elements (the test case overrides the client to reduce the fuzzy count limit from 1000 to 2 to verify the limiting works).

### CODE REVIEW

**Comment by jmchilton** [comment]
A cool, unintended upshot of this is that when the long standing issue #3782 occurs and the UI just decides not to render some collection elements - there is now a warning that this occurring. Still disturbing that it happens at all - but better there is some feedback.

Here is a screenshot from a test case that exhibits this on the Selenium server.



Prior to this PR that failure would look like this - just dropping an element without a warning.

**Comment by martenson** [comment]
Mayhem! :)
screenshot 2017-11-30 15 21 20

**Comment by jmchilton** [comment]
Meh - you say mayhem - I say if people who have "list:list:paired:paired:paired:paired:paired" data structures can now see their data 😆.

Update: For people concerns about this - it is limited to the multi-history view right? You can descend more cleanly in your own active history in the analysis view.

**Comment by martenson** [comment]
@jmchilton your update is correct, sorry I did not clarify

**Comment by jmchilton** [comment]
Rebased.

Clarified the concept of the fuzzy_count a bit in the above description. But here is the chat I had with @martenson on it in Gitter. 

```
Martin Cech @martenson 15:25
@jmchilton how many collection elements do you expect to see with fuzzy_count=10?

John Chilton @jmchilton 15:25
in a list?

Martin Cech @martenson 15:25
deeply nested lists
I thought the idea of fuzzy count was to limit the absolute number of elements fetched no matter the depth

John Chilton @jmchilton 15:26
like "list:list" or more deeply?

Martin Cech @martenson 15:26
10 levels of depth

John Chilton @jmchilton 15:27
you need to stop creating the data structures!

Martin Cech @martenson 15:27
hey, just testing mate :wink:

John Chilton @jmchilton 15:27
umm... I'm not sure - I guess I would expect to see just one element at every level
It isn't a hard limit for sure - it meant to be a sort of "within an order of magnitude" limit

Martin Cech @martenson 15:28
https://gist.github.com/martenson/8cda8a40ca04e6e124d991fd1cdf35c6
(the request is in the end of gist)

John Chilton @jmchilton 15:29
well with paired stuff in there - I would expect it to grab one pair from each level of list and both elements of each pair
which... it seems to be doing?

Martin Cech @martenson 15:30
I just expected less than 449 elements for fuzzy_count=10
this is probably hard cornercase though

John Chilton @jmchilton 15:32
So it is always going to grab a full pair - since 2 isn't an order or magnitude more than 1... but if it does that at every level of depth - you can see how this would happen. Is it at least just grabbing one element or the top list?

Martin Cech @martenson 15:33
yeah, it seems to be exact third of the original elements
(that are shown when there is no limit)

John Chilton @jmchilton 15:34
I wouldn't expect anyone to ever have a list:paired:paired or anything but one paired at the end of these chains - so I wouldn't expect grabbing both parts of the paired to affect the total count more by more than a factor of 2. Clearly it can though. I still think I'm doing the right thing - I just need to explain it better-er

Martin Cech @martenson 15:40
That makes sense.

John Chilton @jmchilton 15:40
Does it though? I've reworded the PR to claim it restricts the order-of-magnitude-per-level-of-depth instead of just the order of magnitude

Martin Cech @martenson 15:41
It does, until we have more structure than list and pair
then we should revisit
But that is kinbda obvious.

John Chilton @jmchilton 15:44
Also in its defense 449 seems big - but if you had 1000 elements in that top list - it would still only grab one of those crazy pairs in that large list and it would left hundreds of thousands of datasets on the server - and the 2^{number of nested pairs} would more closely approximate the small positive constant I was sort of claiming it to be.
yes - I have plans for records - but I'm probably going to just approximate them as lists for this calculation
```

**Comment by mvdbeek** [comment]
Sorry to be late to the game here, but could we have the white square around the elements always go through to the right side ? That would give us more screen space to display buttons

**Comment by jmchilton** [comment]
@mvdbeek It is certainly a good plan - I didn't actually touch the style sheet at all in the PR it just sort of magically worked. We should take a stab at cleaning that up a bit though - I agree. Eliminating the right padding/margin is a good idea. Maybe alternating the color of that white border as we go deeper would be a good idea also for more visual distinction between the levels.

I honestly wasn't very familiar with this view of collections at all - I've never really used them with the multi-history panel. Do you think it would be good to at least have an option to navigate collections this way in the main history panel? Like throw a + button in the view somewhere to expand them in an embedded way instead of in the digging deeper way? (Now that I've actually touched all that code it seems like that would be an easy thing to implement if it would be useful.) Not sure it is worth the added complexity / visual clutter though.

**Comment by mvdbeek** [comment]
> Do you think it would be good to at least have an option to navigate collections this way in the main history panel?

You mean expanding collections in the single-history view like we do in the multi-history view ? That would certainly make drag-and-drop of collection elements easier, but also scanning collections for elements would be a easier that way.

**Comment by martenson** [comment]
@mvdbeek Expanding subthings in a thing that already expands needs to be very careful. There is not much canvas to use and UX might easily  downgrade.

**Comment by jmchilton** [comment]
@mvdbeek This is what I meant.

@martenson Is there something about the multi-history view lends it to being okay that the main history view doesn't allow?

**Comment by martenson** [comment]
I think it is confusing it behaves differently in two very similar interfaces. IMHO the way to go is to improve on what is in multi_view and drop the full drilldown that we use in history view currently (ie using the expanding collections everywhere).

edit: now when I read this thread again I think we totally agree

**Pull request merged**
