### PR TITLE
Expose workflow versions

### PR DESCRIPTION
**Pull request by mvdbeek**
This displays a list of workflow versions in the workflow editor and allows loading previous versions into the editor.

screen shot 2018-09-10 at 20 44 20

screen shot 2018-09-10 at 20 44 55

Re-opened from https://github.com/galaxyproject/galaxy/pull/6409 (Apparently can't re-open if force pushed to a branch ...)

### CODE REVIEW

**Comment by mvdbeek** [comment]
At this point this works pretty well, but I do want to add Selenium and API tests for this.

**Comment by dannon** [comment]
@mvdbeek Before or after merge (freezing today)?

**Comment by mvdbeek** [comment]
In a follow-up PR would be fine for me.

**Comment by dannon** [comment]
@mvdbeek Works for me.

**Pull request merged**
