### PR TITLE
Vuefy interactive tools

### PR DESCRIPTION
**Pull request by OlegZharkov**
Since previous interactive tools view has some problems, I thought it would be a good idea to port it to Vue.
A few fixed bugs:
   - [x] - If you sort by ```Job Info``` galaxy webpage hangs and you get: 
image
- [x] After you stop your interactive tool, it doesn't disappear from history

### CODE REVIEW

**Comment by bgruening** [comment]
@blankenberg you might want to have a look at this one.

**Review by jmchilton — APPROVED** [review]
Amazing - thanks so much!

**Comment by jmchilton** [comment]
Screen Shot 2020-03-16 at 2 11 58 PM


Screen Shot 2020-03-16 at 2 12 06 PM

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by OlegZharkov** [comment]
Thanks, @jmchilton ! 
Is everything fine with the screenshot?

**Comment by jmchilton** [comment]
Looks great, works great for me! Thanks so much, awesome stuff.

**Pull request merged**
