### PR TITLE
[16.04] Add hg38 to main for ucsc_build_sites.txt.sample

### PR DESCRIPTION
**Pull request by blankenberg**
ping @afgane 
xref https://github.com/galaxyproject/galaxy/pull/2670#issuecomment-235640497

### CODE REVIEW

**Comment by dannon** [comment]
Retroactive +1, since this was a stable PR requiring 2.

**Comment by afgane** [comment]
Just a clarification - do +1's on a different branch not count? Remi had +1d this same change on the original PR.

**Comment by jmchilton** [comment]
The prevailing culture we have created is to get 2 +1s (on the PR, not on the changes) and is backed up by the procedure language here:

"Pull requests modifying pre-existing releases should be restricted to bug fixes and require at least 2 +1 binding votes from someone other than the author of the pull request with no -1 binding votes."

I do think there is an unfortunate loophole though in the procedures that I read allows anything in dev to be backported by any committer:

"The Galaxy committers group may only commit directly to Galaxy (i.e. outside of a pull request and not following the procedures described here) the following two categories of patches:
- Cherry-picking and/or merging of existing approved commits to other branches."

**Comment by dannon** [comment]
I just doublechecked, but Remi isn't currently a committer and does not have a binding vote.

**Comment by dannon** [comment]
@jmchilton Should we change that language to include merge direction?  Something more like 'cherry-picking and/or merging existing approved commits _forward_'?

**Comment by jmchilton** [comment]
@dannon I'm +0.5 on that.

**Pull request merged**
