### PR TITLE
UI, collections: fix DatasetCollectionElement and DatasetAssociation …

### PR DESCRIPTION
**Pull request by carlfeberhard**
…id collision in DCECollection by preserving Element id in idAttribute 'element_id'

This should help with the dataset collections that weren't displaying all their contents in the UI.

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks a bunch @carlfeberhard - I assume this fixes this http://dev.list.galaxyproject.org/problem-with-view-of-list-collection-in-history-view-td4667442.html?

**Comment by jmchilton** [comment]
:+1:

**Comment by carlfeberhard** [comment]
@jmchilton Sorry for not responding sooner: yep and Cameron's bug as well (hopefully).

**Comment by kaktus42** [comment]
:+1: thanks @carlfeberhard.
I will try this ASAP

**Pull request merged**
