### PR TITLE
Change response body from str to bytes

### PR DESCRIPTION
**Pull request by qiagu**
UWGI HTTP server complains about the str type.

### CODE REVIEW

**Comment by qiagu** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Thanks @qiagu , looks OK to me. Do you have a stacktrace for the error though?

**Comment by qiagu** [comment]
I don't have concrete examples for `nginx_x_accel_redirect_base` or `apache_xsendfile`, but if we change the line `body = iterate_file(body)`([link]( https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/framework/base.py#L501)) to `body = [""]` and click a dataset preview, the error message can be shown up in the backend log. 

With uWSGI server:
```
127.0.0.1 - - [17/Oct/2020:10:46:41 -0700] "GET /datasets/df7a1f0c02a5b08e/display/?preview=True HTTP/1.1" 200 - "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
[ERROR] Unhandled object from iterator: '' (0x1031f22f0)
```
It's clearer with paste:
```
127.0.0.1 - - [17/Oct/2020:10:52:09 -0700] "GET /datasets/df7a1f0c02a5b08e/display/?preview=True HTTP/1.1" 200 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50608)
Traceback (most recent call last):
  File "/Users/guq/galaxy_dev/.venv/lib/python3.8/site-packages/paste/httpserver.py", line 1092, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/guq/galaxy_dev/.venv/lib/python3.8/site-packages/paste/httpserver.py", line 460, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Users/guq/galaxy_dev/.venv/lib/python3.8/site-packages/paste/httpserver.py", line 455, in handle_one_request
    self.wsgi_execute()
  File "/Users/guq/galaxy_dev/.venv/lib/python3.8/site-packages/paste/httpserver.py", line 308, in wsgi_execute
    self.wsgi_write_chunk(chunk)
  File "/Users/guq/galaxy_dev/.venv/lib/python3.8/site-packages/paste/httpserver.py", line 168, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```

**Review by nsoranzo — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thanks @qiagu!

**Pull request merged**
