### PR TITLE
Tours enhancement: Allow to search for tools 

### PR DESCRIPTION
**Pull request by blankclemens**
This will trigger the keyup event when text is inserted in the tool search, allowing to search for tools inside a tour.

### CODE REVIEW

**Comment by dannon** [comment]
@blankclemens I'm wondering why the search is only listening to ```keyup``` and not ```change```.  Did you look into this?  It may be better to address the search portion, rather than adding the additional logic here.

edit:  And, sorry I did not see the other PR sooner!

**Comment by dannon** [comment]
To follow up, can you check out #3808 and see if that works for you?

**Comment by blankclemens** [comment]
@dannon Sorry, I was busy yesterday. The other PR I closed to clean up the commits. Yes, I totally agree that wasn't the most clean solution and #3808 fixes that. Thanks a lot!

**Comment by dannon** [comment]
@blankclemens No worries, glad this works for you!

**Pull request closed without merging**
