### PR TITLE
entrypoints - use timeout instead of interval to prevent stacking requests

### LINKED ISSUE #15276: Entry point requests pile up
`api/entry_points?running=true` is always being polled at a set interval, even if the response is not coming in. This leads to a pileup of requests that (if no countermeasure are taken on the server side) will lead to degraded performance. A fix could be to:
- use setTimeout instead of setInterval
- not to fire the request if the page isn't visible

we're doing that already in watchHistory, I think the pattern could probably be extracted into a composable (if vueuse doesn't already have something we can reuse).

### PR DESCRIPTION
**Pull request by martenson**
closes #15276

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thanks @martenson! I think you may also want to stop polling when the page is inactive. That made a big difference to the server load for the history watcher (which does fire more frequently, but there's no point polling if the page isn't visible IMO).

**Comment by dannon** [comment]
> Thanks @martenson! I think you may also want to stop polling when the page is inactive. That made a big difference to the server load for the history watcher (which does fire more frequently, but there's no point polling if the page isn't visible IMO).

+1, and we could definitely generalize this foreground-only-watcher behavior to something reusable.

Thanks for the quick work on this one @martenson.  Here's a ref to how the history does it: https://github.com/galaxyproject/galaxy/pull/14264/files

**Comment by guerler** [comment]
Thanks for fixing this @martenson, +1 on the generalization suggestion. We should probably consider to queue these in a centralized registry and handle it together with the history poll requests.

**Comment by martenson** [comment]
I will look into making this a bit more optimized. Thanks for the merge in the meantime (just got power back 🤨).

**Pull request merged**
