### PR TITLE
Add interactive tools activity

### PR DESCRIPTION
**Pull request by guerler**
Requires #16265. Introduces an interactive tools activity, which appears when an interactive tools is actively running and requires interaction. This PR also revises the notification indicator by displaying the number of unread notifications in the activity bar instead of just showing a red-circle.

We might want to replace the icon in a follow-up and after more discussions.

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by itisAliRH — APPROVED** [review]

**Comment by martenson** [comment]
Thanks @guerler !

I am fine with whatever icon is decided to be used but I think one activity should not have 2 distinct icons in the app. Let's have the discussion.

**Comment by martenson** [comment]
(on a related not workflow and invocations icons form the screenshot are currently also used differently in the app)

**Comment by bgruening** [comment]
@martenson do we need an issues here or are you discussing that in the WG meeting?

**Comment by martenson** [comment]
@bgruening I added it to the WG meeting discussion and also made an issue here: https://github.com/galaxyproject/galaxy/issues/16288

**Pull request merged**
