### PR TITLE
include more information in default welcome.html

### PR DESCRIPTION
**Pull request by martenson**
screenshot 2015-04-30 11 31 03

### CODE REVIEW

**Comment by afgane** [comment]
'Hello world' is a basically a CS term - how about changing that altogether? Perhaps 'Galaxy is running'.

**Comment by jmchilton** [comment]
I agree "Hello World" should be replaced - but @martenson did not add it so I am definitey :+1:.

**Comment by martenson** [comment]
screenshot 2015-04-30 13 23 50

**Comment by bgruening** [comment]
Can we have back the Flying Spaghetti Monster ;) _hiding_
@martenson what about 'Happy research!' or similar?

**Comment by martenson** [comment]
@bgruening go away, monster!

Is it allowed to use happy and research in the same sentence?

**Comment by afgane** [comment]
One more minor comment: 'see _our_ wiki' - as a community project, it should be everyone's wiki so maybe better just 'see the wiki'?

**Comment by dannon** [comment]
+1, nice tweaks!

**Pull request merged**
