### PR TITLE
Documentation fixes and improvements

### PR DESCRIPTION
**Pull request by nsoranzo**
- Update lib documentation
- Simplify `updaterst` target in `doc/Makefile`
- Fix some links and syntax errors in tool XML documentation
- Document `<hook>` sub-element of `<code>`

### CODE REVIEW

**Comment by martenson** [comment]
You are reverting some of my changes I made to improve readability. The following screenshots illustrate this (imho) regression.

screenshot 2017-06-02 10 56 30
screenshot 2017-06-02 10 56 53

**Comment by dannon** [comment]
@martenson Which is which, in the screenshots?  I prefer the one on the right in both cases I think.

**Comment by martenson** [comment]
@dannon left is this PR. Right is current dev.

**Comment by jmchilton** [comment]
@nsoranzo I like that this PR is automating the update of those top level API pages - I think that is important. Maybe do it with a sed command instead of an include though so we can preserve the formatting that @dannon and @martenson prefer?

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
@martenson Yes, it says so in the commit message and I've requested your review for this reason. The problem is that the current version requires manual updating instead of the simple:
```
make -C doc/ updaterst
```
which is used to update the rest of the lib documentation. It also leaves missing docs in the lib documentation.

If that's considered important, I can create a sed script as suggested by @jmchilton.

**Comment by martenson** [comment]
I prefer readability. It is not just that index page, bus also the actual contents:

screenshot 2017-06-02 11 21 07


Also the `galaxy.webapps.galaxy.api package` (and tool shed api) links in the left menu seem confusing.

**Comment by nsoranzo** [comment]
@martenson @dannon I've the Makefile rules almost ready, is it OK for you to have `annotations module`, `authenticate module`, etc.
I slightly prefer them over just `annotations`, `authenticate`, etc...

**Comment by martenson** [comment]
@nsoranzo that is fine I think, the biggest culprit there is the repeating prefix

**Comment by nsoranzo** [comment]
@martenson Try now.

**Comment by martenson** [comment]
Thanks @nsoranzo !

**Pull request merged**
