### PR TITLE
Address @bgruening's concerns about UI in #351

### PR DESCRIPTION
**Pull request by hexylena**
[Devteam tools](https://github.com/galaxyproject/tools-devteam/blob/master/tools/tophat2/tophat2_wrapper.xml#L188) don't follow [IUC best practices](http://galaxy-iuc-standards.readthedocs.org/en/latest/best_practices/tool_xml.html#parameter-help) for supplying the --argument, thus we write a special case to take care of them. Specifically if the help text is equivalent to the argument, like many devteam tools, we don't auto-generate and add the help string.

As noted by @bgruening, simply PRing to fix the tools wouldn't fix the underlying issue that devteam tools would show up with help texts of `help="--arg (--arg)"`

### CODE REVIEW

**Comment by hexylena** [comment]
xref #351 since apparently github doesn't do that from the title.

**Comment by jmchilton** [comment]
None of the devteam tools have arguments defined though do they? When we modified the tool to add an argument - wouldn't we just remove it from the help?

**Comment by hexylena** [comment]
`:|` sometimes I write code before thinking it out. This would be one of those cases.

**Comment by erasche** [comment]
@bgruening

**Comment by hexylena** [comment]
Thanks @jmchilton

**Comment by nsoranzo** [comment]
@jmchilton @erasche If we want to support also old Galaxy versions, we should not remove the argument from `help`, but use the `(--arg)` syntax there.

**Comment by jmchilton** [comment]
I would rather have older versions of Galaxy have a slightly less informative help display than maintaining cruft around in the code and in the tool indefinitely.

**Comment by bgruening** [comment]
Oh boy, this is true. I go to bed. Sorry.

**Comment by hexylena** [comment]
@bgruening you and me both, no worries :)

**Pull request closed without merging**
