### PR TITLE
Remove unused abstraction layers from Visualizations Registry

### PR DESCRIPTION
**Pull request by guerler**
This consolidates the visualization framework by folding back unused abstraction layers. It should not change any functionality. Previously a base plugin manager was inherited by a page serving plugin manager which then was inherited by the visualization registry across directories while each was overloading substantial functionality. The code reduction in this PR highlights that. Only the visualization registry used this inheritance chain. For other plugin types such as webhooks and tours inheriting these base classes was not helpful. Also moving forward it does not seem that these base classes will be needed anywhere else than for visualizations (which should probably be referred to as pageserving plugins).

This PR will make it easier for us to work with the visualization framework and to integrate "Charts" as its client-side interface, see also #4256.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@guerler I think you have to remove some unit test files:
- test/unit/web/base/test_HookPluginManager.py
- test/unit/web/base/test_PageServingPluginManager.py
- test/unit/web/base/test_PluginManager.py

**Comment by guerler** [comment]
@nsoranzo awesome, thank you for pointing that out.

**Comment by jmchilton** [comment]
Thanks for working on this @guerler - looks pretty good to me!

**Pull request merged**
