### PR TITLE
Delete cloudauthz record from database instead of marking it as deleted

### PR DESCRIPTION
**Pull request by VJalili**
@martenson can we modify this migration script? I guess no newer script exists, and previous script was not included in 19.01 release.

### CODE REVIEW

**Comment by martenson** [comment]
@VJalili there is no migration-consistency check, so instances running `dev` will not re-run the migration and will be stuck with the column. Which is probably fine.

**Comment by VJalili** [comment]
Agree.

**Comment by jmchilton** [comment]
Agree also, merging fast to minimize the damage though. Thanks!

**Comment by VJalili** [comment]
Thanks @jmchilton

**Pull request merged**
