### PR TITLE
[16.07] Add dependency_resolvers_conf.xml.sample to common_startup.sh

### PR DESCRIPTION
**Pull request by bgruening**
Thanks to @lparsons!

### CODE REVIEW

**Comment by jmchilton** [comment]
-.99 on this - we have moved more and more toward not writing these sample files over. If in 2015 this file had been written this way - everyone would need to update it to get the latest and greatest defaults and conda would be much harder to adopt.

I'm still not even comfortable with the current defaults - so I'd rather not have everyone have them forever.

**Comment by bgruening** [comment]
Following this argumentation shouldn't we remove all other `.samples` as well? The current behaviour is confusing, see Lance comment in the IUC document. Also there is a warning generated that no `dependency_resolvers_conf.xml` could be found.
Better to fix the warning and remove all samples from the common_startup.sh script?

**Comment by jmchilton** [comment]
These are files that Galaxy writes:

```
     config/migrated_tools_conf.xml.sample
      config/shed_tool_conf.xml.sample
      config/shed_tool_data_table_conf.xml.sample
     config/shed_data_manager_conf.xml.sample
```

I guess they should remain - the other files should indeed be removed but it requires code changes. I recently made the required changes for tool data files for instance. The "warning" should be an "info" I think - that would be a PR I can get behind.

**Comment by jmchilton** [comment]
This PR is blocking the release - can I close it?

**Pull request closed without merging**
