### PR TITLE
Remove unused echo tool

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by martenson** [comment]
are you sure these are unused? I thought @natefoo uses them for nagios checks

**Comment by hexylena** [comment]
Not mentioned in `contrib/nagios`

**Comment by natefoo** [comment]
The nagios echo tools (for Main) are here: https://github.com/galaxyproject/usegalaxy-playbook/tree/master/files/galaxy/usegalaxy.org/nagios

**Comment by natefoo** [comment]
+1

**Pull request merged**
