### PR TITLE
Add a custom "TRACE" log level for even more verbosity.

### PR DESCRIPTION
**Pull request by dannon**
Import logging as usual and within the galaxy namespace you should be able to use it with log.trace().

Includes one example swapping a statement over.

I found the existing NullHandler logging bits in `galaxy` and added this there, though we could maybe move both to `galaxy.logging` if we think our logging config might get much more sophisticated.

### CODE REVIEW

**Comment by jmchilton** [comment]
Can we do this differently - this is some nice magic and it works well for "Galaxy the application" - it is very elegant. The downside is I don't think monkey patching a standard library module is a good behavior for a library - so I'd like not to do this in galaxy-lib for instance. I'd prefer not not monkey the logger and just import a "trace" function from the ``galaxy.util`` module that takes the arguments and the logger and does this.

If I'm voted down on this can we at least allow both methods of tracing and then use the alternative, less elegant galaxy.util.trace for methods in galaxy-lib?

**Comment by dannon** [comment]
@jmchilton Yeah, I don't mind.  I actually started out with something similar in `galaxy.logging`, and then realized how this might work so much more cleanly.  It's a good point about galaxy-lib, though; I should be able to tweak this pretty easily.

**Comment by dannon** [comment]
(and, I think we can actually *drop* the other pre-existing logging patch here -- that's only for python2.6 which we don't support anymore)

**Comment by dannon** [comment]
Refactored, removed some python 2.6 cruft as well.  Looks like I may need to touch up a few things though, so, WIPing it for a bit.

(renaming log to logging backfired in a big way w/ relative imports in py27)

**Comment by nsoranzo** [comment]
@dannon Now that #4671 has been merged forward, this PR is conflicting.

**Comment by dannon** [comment]
@nsoranzo Yeah, I'll fix it up.  I'm mostly out today due to jury duty.

**Comment by jmchilton** [comment]
Thanks for working on this @dannon, looks very solid!

**Comment by dannon** [comment]
Sure, thanks for the nudge towards doing it this way; I'm happier with how it turned out.

**Comment by natefoo** [comment]
So, one side effect of this change is that when switching from `dev` to any older release branch, `lib/galaxy/util/logging/__init__.pyc` is left behind, resulting in `AttributeError: 'module' object has no attribute 'getLogger'` in lots of `galaxy.util` modules (the ones that have been changed to use absolute imports in this PR) on startup. This can be worked around by doing a `find lib -name \*.pyc -print0 | xargs -0 rm`, but that's a pain to have to do every time you switch branches (although it's occasionally been necessary at other times, but it's never been *required* that I can recall).

It can also be worked around by backporting `absolute_import` to old releases, but I am not sure that recovering from an annoyance only encountered when switching branches in development is in the spirit of stable bugfixes. Although it's worth noting that it would break release downgrades from 18.01 to 17.09 or older, if someone wanted to do that.

We could also add the `find` (and probably locate empty dirs and `rmdir` them) to `run.sh` and backport that, but it'd further increase startup times for something that is rarely necessary.

Other ideas?

**Comment by dannon** [comment]
I dunno about backporting the fix or renaming it, since this is just a temporary 'problem'.  The naming seems right as-is, and you're right, the backport doesn't really feel like a stable bugfix.

One option is a commit hook to act on changing branches, but those aren't really easily shared :/

edit: I definitely do feel like we had this happen in the past and we just used it as a moment to educate folks (developers encountering it) about how to clean up old .pyc.

**Comment by martenson** [comment]
I disagree with `temporary` here. Eevery committer will experience this daily for next 1 month, and then weekly for next 6 months and then it will make security patches even more annoying.

**Comment by jmchilton** [comment]
Seems like a safe thing to back port and we have backported for similar problems before. https://github.com/galaxyproject/galaxy/pull/4565 was backported really far and I think it was a solid choice. There will be admins that hit this problem IMO - it won't just be developers.

**Comment by dannon** [comment]
I'm fine with the backport, if folks think something must be done.  We have definitely had other (temporary) similar situations (in the past and we did not go to these lengths, though. (`find . -name "*.pyc" -delete` solved problems)

**Pull request merged**
