### PR TITLE
Update openapi-typescript dependency to version 6.7.6

### PR DESCRIPTION
**Pull request by davelopez**
xref https://github.com/galaxyproject/galaxy/pull/18093#discussion_r1670444490

This is not the latest version, but version 7.0.0+ introduces breaking changes that we need to investigate in more detail.
Updating to this version fixes an issue with https://github.com/galaxyproject/galaxy/pull/18093#discussion_r1662523778 but also changes some of the generated API types to what looks like more accurate ones. So I had to fix some of the issues that popped up when building the client, including fixing the return type (or rather non-return type) of the copy collection API endpoint.

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Looks like solid improvements, thank @davelopez!

**Comment by mvdbeek** [comment]
Also curious to see what 7.0 does, if you want to open a PR we can look at whether changes are reasonable.

**Comment by davelopez** [comment]
Sure! I will open a PR, I think it was something with the transforms, but I didn't investigate further it may very well be that we don't need those anymore or require some adaptation :+1:

**Comment by davelopez** [comment]
> Also curious to see what 7.0 does, if you want to open a PR we can look at whether changes are reasonable.

I opened a follow up in https://github.com/galaxyproject/galaxy/pull/18532

**Pull request merged**
