### PR TITLE
Install node and yarn on startup if running a non-release branch

### LINKED ISSUE #5347: make Galaxy build client on startup
autosetup nodeenv and friends, perform client check on startup and `make client(-production?-maps?)` so dev is again clone-and-go

xref: https://github.com/galaxyproject/galaxy/pull/5128

~~We probably want this for 18.01~~ This only applies to dev, releases have built client for now as pointed out below.

ping @natefoo @dannon @mvdbeek @nsoranzo

### PR DESCRIPTION
**Pull request by natefoo**
With the client build artifacts removed from the dev branch it's now necessary to perform the build after first checkout and upon update. @dannon added a client build state check in #5128, this takes it one step further thanks to the suggestion from @nsoranzo and installs node into the virtualenv using [nodeenv](https://github.com/ekalinin/nodeenv) and yarn into the virtualenv using the venv's npm.

This is done at startup time for non-release branches only and can be skipped with `--skip-client-build`. Because everything is contained in the virtualenv, if you prefer to use your own versions of node/yarn, you can simply `make client` without the virtualenv activated.

Fixes #5347

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton I think this is still ok for #5371 which I just saw?

**Comment by nsoranzo** [comment]
Thanks @natefoo for implementing this, LGTM, but I haven't tested it.

My only doubt is if the nodeenv requirement should be in the main requirements.txt instead. We may end up having to instruct people to install it in the virtualenv.

**Comment by jmchilton** [comment]
> nodeenv requirement should be in the main requirements.txt instead

\+ 💯 ... no ulterior motives for me wanting this or anything  👀

**Comment by natefoo** [comment]
@nsoranzo I changed it in this PR so that if you run `common_startup.sh` on a non-release branch, you get the dev wheels as well.

**Comment by nsoranzo** [comment]
Right, I missed it, thanks!

**Comment by dannon** [comment]
This is working well for me.  I still don't love that it's automatic and opt-out, instead of opt-in, but I'm pretty sure I lost that argument -- and it's easy enough to `export GALAXY_SKIP_CLIENT_BUILD=1` if you never want it to kick off.

(and it fixed a `probabably` typo I had made, too!)

**Review by dannon — APPROVED** [review]

**Pull request merged**
