### PR TITLE
Make tours reloadable

### PR DESCRIPTION
**Pull request by jdavcs**
Add a watcher for the tours directory (`/config/plugins/tours`)
Add `watch_tours` config option to the schema

Note/todo: this lacks an integration test. 
ping @dannon

### CODE REVIEW

**Comment by martenson** [comment]
This is missing the corresponding config sample.

**Comment by dannon** [comment]
@ic4f This was even less code than I thought it'd be when I suggested it, wow, thanks!  :)  I'll check it out.

**Comment by jdavcs** [comment]
> This is missing the corresponding config sample.

Yep, I'll run config-rebuild.

**Comment by jdavcs** [comment]
> @ic4f This was even less code than I thought it'd be when I suggested it, wow, thanks! :) I'll check it out.

I hardly had to add anything - all the functionality was already there.

**Comment by dannon** [comment]
@ic4f I enabled this to test and I see the following on server startup:
```
galaxy.util.watcher DEBUG 2019-11-25 09:23:40,378 [p:34671,w:1,m:0] [database_heartbeart_main.web.1.thread] Watching for changes in directory: /Users/yoplait/work/galaxy/config/plugins/tours
galaxy.model.database_heartbeat DEBUG 2019-11-25 09:23:40,383 [p:34682,w:4,m:0] [database_heartbeart_main.web.4.thread] main.web.4 is config watcher
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
!!! uWSGI process 34682 got Segmentation Fault !!!
galaxy.util.watcher DEBUG 2019-11-25 09:23:40,386 [p:34682,w:4,m:0] [database_heartbeart_main.web.4.thread] Watching for changes in directory: /Users/yoplait/work/galaxy/config/plugins/tours
*** backtrace of 34682 ***
0   pyuwsgi.so                          0x000000010aa7a86c uwsgi_backtrace + 44
1   pyuwsgi.so                          0x000000010aa7ada3 uwsgi_segfault + 51
2   libsystem_platform.dylib            0x00007fff6b84cb1d _sigtramp + 29
3   Python                              0x00007fff3f10d6dc PyThread_release_lock + 53
4   libdispatch.dylib                   0x00007fff6b5faad6 _dispatch_xref_dispose + 100
5   CoreFoundation                      0x00007fff34190b47 __CFRunLoopModeDeallocate + 217
6   CoreFoundation                      0x00007fff34273068 _CFRelease + 265
7   CoreFoundation                      0x00007fff34144ffd __CFBasicHashDrain + 345
8   CoreFoundation                      0x00007fff34273068 _CFRelease + 265
9   CoreFoundation                      0x00007fff341903a0 __CFRunLoopDeallocate + 318
10  CoreFoundation                      0x00007fff34273068 _CFRelease + 265
11  CoreFoundation                      0x00007fff34186827 __CFTSDFinalize + 107
12  libsystem_pthread.dylib             0x00007fff6b8553cf _pthread_tsd_cleanup + 551
13  libsystem_pthread.dylib             0x00007fff6b85812f _pthread_exit + 70
14  libsystem_pthread.dylib             0x00007fff6b857d41 _pthread_override_qos_class_end_direct + 0
15  libsystem_pthread.dylib             0x00007fff6b85458f thread_start + 15
*** end of backtrace ***
```

**Comment by jdavcs** [comment]
Doesn't happen on linux. Trying on a Mac..

**Comment by jdavcs** [comment]
@dannon I can't reproduce it. Tried enabling and using on Linux, Mac. Rebased on dev, no issues.

**Comment by dannon** [comment]
@ic4f Interesting.  Reliably happens when I set ` watch_tours: true` at the tip of this branch (so, not rebased or anything).  This is my python2.7 env, though -- let me test on 3 and see if it's the same.

**Comment by dannon** [comment]
@ic4f Same problem in a brand new python3 env.

**Comment by dannon** [comment]
To update this; chatted out of band and this only happens with multiple processes and my intuition is that the watcher initialization needs to be pushed postfork.  @ic4f is on it.

**Comment by dannon** [comment]
@ic4f I pushed the entire watcher instantiation (not just the `start` bit) into a little postfork function and it's still a problem.  What does ~fix it~  (oops -- lazy-apps does indeed prevent the segfault and starts, but it doesn't actually start the watchers this way)  is swapping the entire uwsgi configuration to lazy-apps mode, which is pretty interesting.  I'm wondering if that indicates that there's still some bit of prefork configuration that's happening in the standard mode that we can push postfork, after which it'll all work?  Anyway, I just wanted to test that hunch; I'm hands off again for now so let me know what you figure out.

**Comment by jdavcs** [comment]
So far I've found that this is not related to this particular watcher, or any watcher in particular: a segfault happens when **any** watcher is enabled (under postgres, on a Mac, with processors>1. The lazy-apps mode does not result in a segfault because `database_heartbeat` thread is never started (registering a postfork function has no effect). I'm investigating this, but as it is unrelated to this particular PR, I'll open a separate issue. Ping @dannon

**Comment by dannon** [comment]
Sounds good to me to follow up on the watcher bit later.  My one further suggestion related to this PR is that currently *all* tours are reloaded when any single one is touched.  It'd be nice for that to only reload what has changed.  Is that something you can squeeze in here?

**Comment by jdavcs** [comment]
> Sounds good to me to follow up on the watcher bit later. My one further suggestion related to this PR is that currently _all_ tours are reloaded when any single one is touched. It'd be nice for that to only reload what has changed. Is that something you can squeeze in here?

Possibly. ~~Looking into it.~~ Done.

**Comment by selten** [comment]
Am I correct in thinking that this closes https://github.com/galaxyproject/galaxy/issues/4692?

**Comment by jdavcs** [comment]
@selten I believe so. I suppose once it's merged we can close that issue.

**Pull request merged**
