### PR TITLE
[22.05] Backport fix #14854

### PR DESCRIPTION
**Pull request by davelopez**
Backport to 22.05 of #14854

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thank you!

**Comment by davelopez** [comment]
> ModuleNotFoundError: No module named 'dns'

:disappointed:

**Comment by davelopez** [comment]
I'm not sure what else is wrong with the dependency here... :thinking:

**Comment by nsoranzo** [comment]
> I'm not sure what else is wrong with the dependency here... thinking

In release from 21.05 to 22.05 you need to add normal dependencies also to `lib/galaxy/dependencies/dev-requirements.txt` because all normal deps are duplicated in that file as well, so `./scripts/common_startup.sh` uses just the `dev-requirements.txt` in non-release branches.

**Review by nsoranzo — APPROVED** [review]

**Comment by davelopez** [comment]
Ohh I see! Thank you very much!

**Pull request merged**
