### PR TITLE
remove reference to a non-existent component

### PR DESCRIPTION
**Pull request by martenson**
xref https://github.com/galaxyproject/galaxy/pull/17634

@ahmedhamidawan does this seem ok? 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by ahmedhamidawan** [comment]
So this removes the upload button from the tool panel, and the upload activity will be the only place for uploads, that's the idea here right?

**Comment by dannon** [comment]
@ahmedhamidawan I thought it was already gone from the tool panel in dev?

**Comment by ahmedhamidawan** [comment]
> @ahmedhamidawan I thought it was already gone from the tool panel in dev?

Something weird happened with a forward-merge somewhere and the import got removed, but i only "removed" it (by adding a `v-if=props.workflow` for the workflow editor version.

**Comment by dannon** [comment]
@ahmedhamidawan Yes, exactly.  That's one of the reasons I had in mind with https://github.com/galaxyproject/galaxy/pull/17701.  I had assumed it was intentional that it was removed, but an oversight that someone might turn the activity bar back off and not be able to upload :)

**Comment by martenson** [comment]
@ahmedhamidawan it is not just the import, the component does not exist on dev

**Comment by ahmedhamidawan** [comment]
@martenson 
Yes, I think something happened with a merge and it got removed in dev, but now it seems useful to remove it since the `ActivityBar` is default

**Review by dannon — APPROVED** [review]

**Pull request merged**
