### PR TITLE
Add Proteomics datatypes proBAM and proBED 

### PR DESCRIPTION
**Pull request by jj-umn**
Add datatypes proBAM and proBED for genomic alignment and annotation of
proteomic analysis results.

### CODE REVIEW

**Comment by jmchilton** [comment]
Came across this in my Twitter feed today: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1377-x. Seems like a good idea to include these to me. Thanks @jj-umn.

**Comment by bgruening** [comment]
Can we get them into 18.01, I guess we will need them soon.

**Comment by bgruening** [comment]
@jj-umn let us know if you want to have them into 18.01.

**Comment by chambm** [comment]
Bit late on this but proBAM is supposed to be backward compatible with BAM tools. Will tools that only take BAM be able to read proBAM? I.e. is there some kind of inheritance support with the datatypes?

**Comment by bgruening** [comment]
> Will tools that only take BAM be able to read proBAM? I.e. is there some kind of inheritance support with the datatypes?

Yes and yes :)

**Pull request merged**
