### PR TITLE
[15.07] Fix for fix for fix for handling of unix permissions in .zip files.

### PR DESCRIPTION
**Pull request by nsoranzo**
Append `common_prefix` to `extraction_path` only when returning.

Ping @davebx and @nuwang.

### CODE REVIEW

**Comment by nuwang** [comment]
@nsoranzo Thanks for fixing this! I'll check this commit during our next scheduled build.

**Comment by davebx** [comment]
:+1: Hopefully nothing else needs to be fixed, the layers are getting deep.

**Comment by martenson** [comment]
I am +1 on this and will merge once @nuwang has a chance to report back after his build.

**Comment by nuwang** [comment]
I've cherry picked this commit and a new build is underway. I'll report back on whether snpeff installs correctly, but I don't really know how to test the permissions stuff (presumably, you need an archive with non-unixy origins?)

**Comment by nsoranzo** [comment]
I've successfully installed `package_picard_1_56_0` and `package_snpeff_4_0` with their tool dependencies on `release_15.07` with this commit.

I've also tested with `./run_test.sh -toolshed` and there is no change in the number of (unrelated, fixed in `dev`) failing tests.

@nuwang: I think that if package installation finishes without errors and the tools work, that should be enough.

**Comment by bgruening** [comment]
I could test this with some picard tools, it works with this version again.

**Comment by bgruening** [comment]
:+1:

**Comment by nuwang** [comment]
@martenson @nsoranzo The build has gone through and the tools install correctly. Thanks for fixing this so quickly.

**Comment by martenson** [comment]
Thanks @nsoranzo et al.

**Pull request merged**
