### PR TITLE
Use a newer conda version by default

### PR DESCRIPTION
**Pull request by bgruening**
We were able to test most of the IUC and devteam tools as indicated here: https://github.com/galaxyproject/tools-iuc/issues/1071

This PR also seem to work with latest conda:
https://github.com/galaxyproject/tools-devteam/pull/375

So maybe we can upgrade dev and test it in the next month more extensively.

### CODE REVIEW

**Comment by mvdbeek** [comment]
This will not upgrade pre-installed conda. Should we attempt to upgrade conda to a minimum version as well? And/or display a prominent warning to admins?

**Comment by bgruening** [comment]
Not sure, I had hoped to inform admins via the release notes to upgrade conda - do you think more is needed? A warning during startup?

**Comment by mvdbeek** [comment]
I guess release notes is enough, though I would think more people look at the startup log than the release notes.

**Comment by nsoranzo** [comment]
Should we also start using Miniconda3? That's what used in Bioconda for their testing environment.

**Comment by mvdbeek** [comment]
> Should we also start using Miniconda3? That's what used in Bioconda for their testing environment.

I'd say yes, but as long as we haven't addressed https://github.com/galaxyproject/galaxy/issues/3299#issuecomment-268621811 we may run into additional problems

**Pull request merged**
