### PR TITLE
Fix bug introduced in #8660

### PR DESCRIPTION
**Pull request by jdavcs**
Also ref #8668

### CODE REVIEW

**Comment by guerler** [comment]
@ic4f I still see a forbidden (403) error when attempting to install toolshed repositories through the api using the client interface in the admin panel.

**Comment by jdavcs** [comment]
@guerler from what I can tell, I don't think this is related to #8660. However, I am not sure: I'm not very familiar with how TS works. 
Ping @martenson : if we revert those changes ( https://github.com/galaxyproject/usegalaxy-playbook/commit/294f464d67bc30a898ce223aad37cd6aa77ff1d5 ) and that fixes the problem, I'll look again. Otherwise, I don't think I know TS well enough (not yet) to fix this quickly.

**Comment by guerler** [comment]
@ic4f I think it is.

**Comment by jdavcs** [comment]
@guerler try to set the 2 config options from the usegalaxy-playbook i referred to in my comment. If it works, that means 8660 did not resolve that issue correctly. If it doesn't work, that would mean than  something else is  happening (other than 8660). [edited]

**Comment by nsoranzo** [comment]
This will be resolved when 19.09 is merged forward.

**Pull request closed without merging**
