### PR TITLE
Vue rewrite of admin data manager (local data) in steps

### PR DESCRIPTION
**Pull request by scrathat**
Contains the same changes as #6558 in standalone working steps. Every commit contains selenium tests for the rewritten component.

Index page
* Added Alert component: Light bootstrap-vue b-alert wrapper.
 - Hides automatically when given message is empty.
 - Translates galaxy state keywords into bootstrap ones.
* Added vue-router integration: Display (future) Data Manager Jobs and Job
  components inside router-views.
 - Added router-view component DataManagerView.
* Rewrite (old mako, new json interface, new vue component)
 - Index page (index.mako, data_managers_list, DataManager)
* Added Selenium test for DataManager component (index page)

Manager page
* Rewrite (old mako, new json interface, new vue component)
 - Manager page (manage_data_manager.mako, jobs_list, DataManagerJobs)
* Added Selenium test for DataManagerJobs component (manager page)

View job page
* Rewrite (old mako, new json interface, new vue component)
 - View job page (view_job.mako, job_info, DataManagerJob)
* Added Selenium test for DataManagerJob component (view job page)

Manage data table page
* Rewrite (old mako, new json interface, new vue component)
 - Manage data table page (manage_data_table.mako, tool_data_table_info, DataManagerTable)
* Added Selenium test for DataManagerTable component (Manage data table page)

### CODE REVIEW

**Comment by dannon** [comment]
@scrathat Thanks for cleaning this up a bit and for writing tests for it.  Sorry I didn't get to it before the 18.09 release freeze, but I hope to get this in shortly.

**Comment by dannon** [comment]
@galaxbot test this

**Comment by dannon** [comment]
@galaxbot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
Thanks @scrathat!

**Comment by dannon** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test py3

**Comment by dannon** [comment]
@scrathat This looks like a good step in the right direction, to me.  Thanks for the work, and especially for your patience on this one!  I was going to open a PR to your repo refactoring "Alert" a bit, but will just follow up on that bit separately, since we're so early in the dev cycle.  We're basically fully embracing bootstrap-vue and I think it'd help to minimize extra component wrappers like this -- especially where we're already using b-alert in many other places, I'd rather keep the one single, consistent way to do things.

Anyway, thank you again for the contribution, and especially for your patience here!

I did push one minor change to fix the rerun button opening a nested Galaxy, but this is great.

**Pull request merged**
