### PR TITLE
Bump pysam, remove 'already_compressed' usage due to new wheel with a…

### PR DESCRIPTION
**Pull request by dannon**
…utodetect

(wheels still building, will bump with hashes when available)

### CODE REVIEW

**Comment by jmchilton** [comment]
The wheel is still unavailable on wheels.galaxyproject.org it seems - may I attach a WIP tag to this?

**Comment by dannon** [comment]
@jmchilton Sure, feel free to do that whenever.  I had just left off the 'review' tag until it was ready, but explicit is better.  (and, copying over the wheels now -- I got derailed when I went to do that yesterday and didn't get back to it)

**Comment by dannon** [comment]
Wheels copied, bumped hashes, ready to test.

**Comment by nsoranzo** [comment]
Thanks @dannon!

**Pull request merged**
