### PR TITLE
Write datatypes registry xml to working directory

### PR DESCRIPTION
**Pull request by mvdbeek**
This addresses https://github.com/galaxyproject/galaxy/issues/4299.

@natefoo can you review this ? I think you'd be happy if that ended up in 17.09, but since we classified this as a bug we may get around that. 
Also I'm not sure about the changes to the pulsar runner, does this look OK to you @jmchilton ?

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks a ton @mvdbeek - if you want to continue unwinding this thread I created #4609 ;)

**Comment by natefoo** [comment]
Thanks @mvdbeek! I didn't get a chance to fully review it before the merge but i'll let you know if I notice anything when I do get a chance to look at it.

**Comment by mvdbeek** [comment]
Thanks for the merge! #4609 sounds like a very good idea.

**Comment by nsoranzo** [comment]
I've started seeing #4299 frequently, not only when the cron job deletes the temporary file, but also when the handler is restarted while the job is running (I think). Can we backport (part of) it?

**Comment by nsoranzo** [comment]
> the handler is restarted

Actually I think it changes also when the toolbox is reloaded.

**Comment by mvdbeek** [comment]
Yeah, I can backport it.

**Pull request merged**
