### PR TITLE
[24.0] Fix source history update_time being updated when importing a public history

### PR DESCRIPTION
**Pull request by jmchilton**
Includes a failing test for history copying updating the history update_time.

I believe I've seen this behavior for a long time but I'm happy to work on a fix for it and a test is a good place to start.

Fixes https://github.com/galaxyproject/galaxy/issues/17702

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jdavcs** [comment]
I think the update bug does not appear at the model level because the functionality is defined correctly at the model level. I have another unit test to verify this (from a draft, post-SA2.0 branch): https://github.com/galaxyproject/galaxy/pull/17662/commits/ce174832a39b5619e44e2494ffbb28f71035458c - it checks that history.update_time is updated after a history hda is created or updated, but not after a history hda is copied - i.e., as expected.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/17728/commits/e3f135dfd100e57b67af28dd28ce76a5a98980e2 should fix it. I debugged this by checking at which point the history update_time changed, which was right after creating the HDA. I then removed the source hda via session.expunge and committing the session, which emitted an sqlalchemy warning that the copied_from_history_dataset_association backref could not be followed. Simply setting just the id instead of adding in the whole instance fixed it.

**Comment by mvdbeek** [comment]
well, that's fun, the `copied_from_history_dataset_association_id` just disappears after commit ... 😆

**Comment by martenson** [comment]
sidenote: We might be doing the same thing with `copied_from_library_dataset_dataset_association` and others?

**Comment by jdavcs** [comment]
most likely, when you changed the arg to copy, it broke something. For example, you are no longer assigning `copied_from_history_dataset_association` in the hda constructor. In general, there should be nothing wrong with passing the hda and not assigning the hda.id: doing self.foo = bar should not add bar to session.dirty, I think. So that's not the root cause here, I think.

**Comment by mvdbeek** [comment]
It is though, see https://github.com/galaxyproject/galaxy/pull/17728#issuecomment-2009850186

**Comment by mvdbeek** [comment]
That still doesn't make sense, since removing `copied_from_history_dataset_association=self` fixes the test, and we're still copying the metadata

**Comment by mvdbeek** [comment]
and dirty is just some heuristic that doesn't necessarily mean anything is getting updated, see https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.dirty

**Comment by mvdbeek** [comment]
This fixes the unit test:

```
diff --git a/lib/galaxy/model/__init__.py b/lib/galaxy/model/__init__.py
index 3b8dc6fa2d..53d238ee7a 100644
--- a/lib/galaxy/model/__init__.py
+++ b/lib/galaxy/model/__init__.py
@@ -4985,7 +4985,6 @@ class HistoryDatasetAssociation(DatasetInstance, HasTags, Dictifiable, UsesAnnot
         self,
         hid=None,
         history=None,
-        copied_from_history_dataset_association=None,
         copied_from_library_dataset_dataset_association=None,
         sa_session=None,
         **kwd,
@@ -4999,7 +4998,6 @@ class HistoryDatasetAssociation(DatasetInstance, HasTags, Dictifiable, UsesAnnot
         self.hid = hid
         # Relationships
         self.history = history
-        self.copied_from_history_dataset_association = copied_from_history_dataset_association
         self.copied_from_library_dataset_dataset_association = copied_from_library_dataset_dataset_association
 
     def __strict_check_before_flush__(self):
@@ -5100,10 +5098,10 @@ class HistoryDatasetAssociation(DatasetInstance, HasTags, Dictifiable, UsesAnnot
         hda.purged = self.purged
 
         hda.copy_tags_to(copy_tags)
-        object_session(self).add(hda)
+        session = object_session(self)
+        session.add(hda)
         hda.metadata = self.metadata
         if flush:
-            session = object_session(self)
             with transaction(session):
                 session.commit()
         return hda

```
which I admit is crazy ...

**Comment by jdavcs** [comment]
> That still doesn't make sense, since removing `copied_from_history_dataset_association=self` fixes the test, and we're still copying the metadata

I didn't test that with your latest commit: so `copied_from_history_dataset_association`  *is* passed to the new hda in my test. And, it appears that upon creating the copied hda, the metadata is modified on the source hda.

**Comment by mvdbeek** [comment]
It's a good commit, however on my branch the source HDA isn't marked dirty at all, so accessing `HDA.dbkey` isn't automatically marking that HDA as dirty, there's still step X involved. I'll pull in your commit

**Review by mvdbeek — APPROVED** [review]

**Comment by jdavcs** [comment]
Yep, found step X. Accessing `hda._metadata` *does* add the 2 attributes to `hda.__dict__`, but that's not what marks it as dirty. That happens in the HDA constructor when we do this:
```new_hda.self.copied_from_history_dataset_association = source_hda```
I don't know exactly *where* that happens inside SA, but it does happen and it's due to the `back_populates` ties between the 2 relationships defined on the HDA model. I don't think this is incorrect. In this branch it doesn't happen because we bypass the relationship (we no longer make that assignment) and instead assign the id directly. And bypassing this step (and all the ORM logic that it triggered) is a good thing, I think. So, 2 fixes in 1 PR!

**Review by jdavcs — APPROVED** [review]

**Pull request merged**
