### PR TITLE
[WIP] Added default indexing for bcf files

### PR DESCRIPTION
**Pull request by nekrut**
Added indexing for bcf datatypes, which would allow vt and bcftools integration. Tests will follow

### CODE REVIEW

**Comment by bgruening** [comment]
Nice feature! We need to document this properly, samtools and bcftools are recommended in $PATH.

**Comment by nekrut** [comment]
DO NOT MERGE YET - I'LL ADD TESTS

**Comment by nekrut** [comment]
Please look and merge now. Thanks. a.

**Comment by jmchilton** [comment]
Clever test, I like this a lot. :+1:

**Comment by blankenberg** [comment]
:+1:

**Comment by nekrut** [comment]
Tx to @natefoo (for `file`) and @blankenberg  (for metadata explanation)

**Pull request merged**
