### PR TITLE
Return of RStudio

### PR DESCRIPTION
**Pull request by hexylena**
Fixed up the image a fair bit. Should be functional again. Thanks @nturaga for helping out.

The JS changes are minor, mostly a refactoring and removing some dead code. Username and password are now hardcoded to `rstudio`, which simplifies container startup.

Images will be out soon.

### CODE REVIEW

**Comment by dannon** [comment]
@erasche This is ongoing work right, with @nturaga trying to get the datasets connecting properly?  Should we mark this WIP for now?

**Comment by dannon** [comment]
Thanks @nturaga :)

**Comment by hexylena** [comment]
@nturaga are things working for you?

**Comment by nturaga** [comment]
@erasche yes, this was the last time I tried it.

**Comment by hexylena** [comment]
@nturaga sosafe to merge?

**Comment by nturaga** [comment]
Sure!

**Comment by hexylena** [comment]
@martenson this is safe to merge. Any chance of getting in 16.10?

**Comment by jmchilton** [comment]
Awesome - thanks all!

**Pull request merged**
