### PR TITLE
[18.01] Allow schema to validate

### PR DESCRIPTION
**Pull request by hexylena**
- [x] fix pbkdf2 descrpition
- [x] fix logging block

### CODE REVIEW

**Comment by hexylena** [comment]
Still need help here on the logging config I'm afraid.
https://github.com/galaxyproject/galaxy/pull/5919/files#diff-a73e218444bd4a6820a525616a23f40dL1335

**Comment by hexylena** [comment]
@jmchilton can you possibly provide some guidance on the logging validation?

**Comment by martenson** [comment]
ping @jmchilton

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
"Fixed" the logging block, I hate the hack to switching the nulls to '' with a passion but https://github.com/Grokzen/pykwalify/issues/77. Why are there no adequate YAML validation tools?

Take it out of WIP?

**Pull request merged**
