### PR TITLE
Fix for loading tools when tool.lineage is None.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
As a bugfix this looks good to me. When I'm back from vacation I'll have a look if we can't make all tools have a lineage.

**Comment by mvdbeek** [comment]
@blankenberg how did you encounter this bug ? Were you using the `watch_tools` option in galaxy.ini ? In that case https://github.com/mvdbeek/galaxy/commit/5adc58491d95843d3816001ce230cb5d74a11f41 would fix it with the added benefit that the lineage should be properly registered.

**Comment by nsoranzo** [comment]
@mvdbeek @blankenberg Should we also add a `log.warning()` in the 2 changes here if `tool.lineage` is None?

**Comment by mvdbeek** [comment]
If https://github.com/mvdbeek/galaxy/commit/5adc58491d95843d3816001ce230cb5d74a11f41 works instead of this PR I would like to undo this change, so the logging wouldn't be necessary. I think loaded tools should always have a lineage. IMO there is no good reason why some tools can't have a lineage, I just didn't think about the `quick_load` functionality.

**Comment by nsoranzo** [comment]
Fine for me!

**Pull request merged**
