### PR TITLE
Uploadbox tweaks

### PR DESCRIPTION
**Pull request by dannon**
(includes the now-cherrypicked-back #4897; leaving open for continued usability work on the uploadbox in this branch targeting dev)

xref #4639.  It's incredibly misleading right now when you try to actually add multiline paste content, or manually add multiple lines to the upload field.

Using `pre` instead of `nowrap` will allow newlines to actually separate content, while still not breaking very long lines (as was the intent)

Ping @guerler.  
(reported via IRC by @bgruening)

### CODE REVIEW

**Comment by dannon** [comment]
(WIP for a sec, looks like the scrollbars need a little love, too)

**Comment by dannon** [comment]
Ok, the scrollbar missing is FF-only, and not a new change.  It's just because the area is *SO TINY* to paste stuff in.  I think, as a separate issue, we should look into the 'active' upload line expanding to the viewable area.

The most relevant portion of this interface when you're trying to add content is crammed down into about 15% of the used space, here:
image

I'd imagine that, when actively entering, growing to fill at least that whole empty portion.

**Comment by dannon** [comment]
I also renamed "Download from web, or upload from disk" to "*Fetch* from web or upload from disk"; I think 'Fetch' is more clear (and it avoids the download/upload juxtaposition).

**Comment by martenson** [comment]
@dannon you might want to target 17.09 for this, since the change to nowrap we introduce there.

**Comment by dannon** [comment]
@martenson Good call; I'll do that.  (well, I'll cherrypick the one bugfix there -- leaving the renaming in -dev I guess)

**Comment by guerler** [comment]
Looks good to me. Thanks for touching this up.

**Comment by jmchilton** [comment]
@galaxybot selenium test this

**Comment by jmchilton** [comment]
@galaxybot selenium test this

**Comment by jmchilton** [comment]
@galaxybot I hate you! Anyway - I doubt this will fail any of the upload tests - 👍 from me.

**Comment by martenson** [comment]
We should address that regression regarding the size of the text area. That is really almost unusable.

**Comment by dannon** [comment]
Closing this out since most of it was merged as a backport and has now been merged forward, and the rest is very out of date.

**Pull request closed without merging**
