### PR TITLE
Subtract 10 seconds from last update time

### PR DESCRIPTION
**Pull request by mvdbeek**
This is an ugly hack that seems to be necessary for refreshing the
dataset status in a history to running (=yellow) with some job runners.
The basic local runner does not show this problem. I haven't completely
understood where this issue is coming from. It shouldn't really be a
wrong clock, since in my testing server and client are the same machine.

### CODE REVIEW

**Comment by dannon** [comment]
@mvdbeek I'm not familiar with your use-case here, but did you try changing the `UPDATE_DELAY` instead?

**Comment by mvdbeek** [comment]
Awesome, yes that works.

**Comment by mvdbeek** [comment]
Hmm, that works only sometimes now. I'll play around with this some more.

**Comment by dannon** [comment]
@mvdbeek Ok, cool, let me know if I can help!

**Comment by mvdbeek** [comment]
It may be the job runners' fault ... there seems to be a correlation between how long a job is in queued state and whether the UI will refresh.

**Pull request closed without merging**
