### PR TITLE
[19.09] fixes for ITs + new ITs

### PR DESCRIPTION
**Pull request by bgruening**
Some updates for various ITs from usegalaxy.eu, including 3 new ITs.

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton this will collide with https://github.com/galaxyproject/galaxy/pull/8897 .... if your gets merged I will update this one.

**Comment by nsoranzo** [comment]
This is also using changes from https://github.com/galaxyproject/galaxy/pull/8517 without proper attribution, I think.

**Comment by martenson** [comment]
@bgruening could you please resolve conflicts?

**Comment by martenson** [comment]
I hope this is superseded by https://github.com/galaxyproject/galaxy/pull/9141 and https://github.com/galaxyproject/galaxy/pull/8517

At this point I think we do not need to get it into 19.09

**Pull request closed without merging**
