### PR TITLE
don't uppercase envoverride

### PR DESCRIPTION
**Pull request by xgaia**
@erasche,

Sorry for the second PR,

I think it is better like this, Only default env var are uppercased, but user env (env_override) are not.

What do you think ?

### CODE REVIEW

**Comment by hexylena** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
@xgaia yes, I like this better. Since the upper case env vars are effectively part of the GIE API contract, this at least gives authors more flexibility in passing vars to underlying software.

**Comment by natefoo** [comment]
Unfortunately, this change has broken automatic fetching of the dataset from which the GIE is launched since `$additional_dataset_ids` is now passed uncapitalized. However, I am not sure of the best solution here since it seems that both functionalities are needed (capitalize some `env_override` keys, don't capitalize others).

**Comment by xgaia** [comment]
Hello @natefoo ,

maybe we can replace `dataset_hid` and `additional_dataset_ids` by `DATASET_HID` and `ADDITIONAL_DATASET_IDS` in all the mako files.

[here](https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/interactive_environments/jupyter/templates/jupyter.mako#L38)

I can make the PR if it's OK

**Comment by natefoo** [comment]
I thought about this, but some of these are used lowercase [elsewhere](https://github.com/galaxyproject/galaxy/blob/562465ffe9c6d1ecb8e67375798d35acce441475/templates/webapps/galaxy/visualization/gie.mako#L54) so I am not sure if it's entirely safe.

**Comment by natefoo** [comment]
@xgaia see #4760 for a proposed solution.

**Comment by xgaia** [comment]
sounds good to me :+1:

**Pull request merged**
