### PR TITLE
Don't override search url 

### PR DESCRIPTION
**Pull request by dannon**
This currently affects main where Help->Search ends up at root.com...

### CODE REVIEW

**Comment by dannon** [comment]
@guerler Tool search appears to continue working fine, and I didn't see where this was actually being used, but I renamed it instead of removing it in case we _do_ want it.

**Comment by martenson** [comment]
Nice catch! We probably want this in 15.10 I think.

**Comment by dannon** [comment]
@martenson Yep, you're right, will do.

**Comment by dannon** [comment]
Closing in favor of a correctly targeted PR ;)

**Pull request closed without merging**
