### PR TITLE
GPU support for Galaxy

### PR DESCRIPTION
**Pull request by jashwantraj92**
We are adding automated GPU support tin Galaxy to run GPU-enabled tools. This effort is a part of Galaxy academic project at Penn State funded by NSF. We are open for feedback and kindly want this be pushed to the main upstream repository.

### CODE REVIEW

**Comment by jashwantraj92** [comment]
This test is failed because the machine where github is running the test needs to have GPU libraries.
How can we overcome this problem?

**Comment by bgruening** [comment]
@jashwantraj92 do you know any CI provider with GPU support? If not we could ask @natefoo and @gmauro if we could get a Jenkins runner with GPU libraries installed.

**Comment by mvdbeek** [comment]
Can you please remove the racon sources from this PR ?

**Comment by jashwantraj92** [comment]
> Can you please remove the racon sources from this PR ?

Sure i can remove them

**Comment by jashwantraj92** [comment]
> @jashwantraj92 do you know any CI provider with GPU support? If not we could ask @natefoo and @gmauro if we could get a Jenkins runner with GPU libraries installed.

i am not aware of any. @natefoo  can you help us.?

**Comment by natefoo** [comment]
I don't have any GPU hardware, but we could add one to our Jenkins server if a node were available.

**Comment by jashwantraj92** [comment]
> I don't have any GPU hardware, but we could add one to our Jenkins server if a node were available.

That would be  great Nate.
For the time-being, i can another condition to check if GPU libraries are present before importing GPU packages in python.

**Comment by ic4f** [comment]
We don't edit `config/galaxy.yml` directly. Instead, you need to edit `lib/galaxy/webapps/galaxy/config_schema.yml`, after which you run `make config-rebuild`.

**Comment by gmauro** [comment]
@jashwantraj92 Which GPU libraries do you need?

**Comment by jashwantraj92** [comment]
> @jashwantraj92 Which GPU libraries do you need?

libnvidia-ml.so.1

**Comment by jashwantraj92** [comment]
> > @jashwantraj92 Which GPU libraries do you need?
> 
> libnvidia-ml.so.1

Hi Everyone,

Can we probabaly have an offline discussion to see what possible options would be best?

**Comment by simonbray** [comment]
Hi @jashwantraj92, thanks for making this PR, I'd like to stay informed about your progress. Being able to at least use the `GPU_ENABLED` variable in Galaxy tools would be really handy.

**Comment by bgruening** [comment]
Something weird happened here. I merged https://github.com/galaxyproject/galaxy/pull/12697 but this one was getting merged as well? I did not merge that one. But it has 0 commits and 0 file changes. Can/should we revert that merge? At least in the GUI the button is also missing. :( sorry, not sure what is happening here.

**Comment by bgruening** [comment]
@gulsumgudukbay was your push with 0 commits intended, or was that a mistake?

**Pull request merged**
