### PR TITLE
UI: Infinite scrolling for history contents

### LINKED ISSUE #1374: The history contents API & scaling histories
### API
- [x] paginate history contents (both collections and datasets) in the style of the histories API
### UI
- [x] paginate and load more when at the 'end' of the panel

### PR DESCRIPTION
**Pull request by carlfeberhard**
This limits the number of contents loaded into any history View (the current panel, `history/view`, published histories) to 100 entries. When the user scrolls to the bottom of the view's list, another 50 entries are loaded. This is an effort to allow analysis with especially large histories (35k contents) and to have that interface scale well.

The use of infinite scrolling may be a questionable choice compared to the alternative of simple pagination. From what I understand, infinite scrolling is most suited to lists that are used for browsing items and I believe most users aren't browsing their histories but are looking for a specific item or relationship. 

Pagination, however, presents another set of problems in that it generally requires more controls and the history (at least the current history panel) is low on real estate for that. Add in that most users are more concerned with their most recent items and that the search-ability of the interface may handle the  use-case for finding a specific dataset/collection.

There's undoubtedly bugs in here - the previous versions of many of the history features relied on having the complete list of contents (deleted/hidden, search, expansion, multiselect, etc.). Thanks for any feedback or bug reports.

There's also:
- a bit of cleanup and using backbone better
- removal of client side type id generation for the heterogenous contents collection
- initial search causes a progressive loading of datasets (instead of one call to load all details)
- deleted/hidden contents are not included by default by the contents and these are fetched over ajax
- a move from bootstraping data in web controller methods to ajax on page load in order to move toward SPA
- [EDIT] move to an API view of histories that doesn't iterate over `.datasets` to get state or deleted/hidden status

Future:
- I'd like to expand into `mvc/base/` more, breaking up base-mvc and creating some base views as well

May resolve: #1374

### CODE REVIEW

**Comment by bgruening** [comment]
@carlfeberhard this is awesome! Can't wait to test it.

**Comment by carlfeberhard** [comment]
@bgruening thanks! I hope it works. Ready to test/review now.

**Comment by blankenberg** [comment]
+1 

Working well for me with my ~60k item history, and smaller ones.  Multiple history view loaded nicely with several larger histories on screen.

Just a few comments, that should not detract from how awesome this PR is:
- Should add infinite scroll to the collection view as well, as I made the mistake of clicking on a 5kish one. 
- It would be nice if there was a good way to jump to different offsets within the history.
- Not sure that blocks of 100/50 are large enough, as for a modest 1k history that is a noticeable number of loadings/on-demand waiting when scrolling from top to bottom (and when searching the history), maybe triggering the fetching of the next chunk before the end of list is viewed would help.

**Comment by carlfeberhard** [comment]
@blankenberg awesome feedback - thanks!
1. We'll need more API to do that AFAIK
2. Yeah - the pagination question. Can you describe the task/use-case/scenario for this a bit more?
3. Ok. Anymore than 50 and I start seeing a slow down in the fetching. I'll recheck on a better db and see if 200/100 would make more sense. Where would you say you spend most of your history browsing time? the most recent ~200? or more?

> modest 1k

heh.

**Comment by blankenberg** [comment]
> 2) Yeah - the pagination question. Can you describe the task/use-case/scenario for this a bit more?

A basic one would be wanting to jump to the start of a large history to examine the output of an early step, especially when investigating a failure at the end. But you might want to jump to like approximately 30% of the history to manually sample the output of an item, or view displays of intermediate steps, etc. Remembering the exact labels for output dataset can be hard sometimes. This also works well with the current behavior of collections, where you have a wall of datasets that are from the same workflow step.

> 3) Ok. Anymore than 50 and I start seeing a slow down in the fetching. I'll recheck on a better db and see if 200/100 would make more sense. Where would you say you spend most of your history browsing time? the most recent ~200? or more?

The last items added to a history when running a workflow aren't always the most interesting to look at. I like being able to grab the slider and drag down to a position. Maybe we could do something where blocks don't need to be fetched linearly and can backfill later.

**Comment by blankenberg** [comment]
Small issue report: Exiting (via escape key or clicking x) on the history search can crash your browser when the history is very large. Probably because the entire history is loaded (since it was loaded during the search) and attempted for rendering.

The search also took quite a while to finish: ~2 hours (postgres database), 58k items

```
[12/Apr/2016:11:33:19 -0400] "GET /api/histories/01b9236ee4903f72/contents?limit=50&offset=0&view=summary&keys=name%2Cfile_ext%2Cgenome_build%2Cmisc_blurb%2Cmisc_info%2Cannotation%2Ctags&details=&order=create_time&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True HTTP/1.1" 200
...
[12/Apr/2016:13:12:59 -0400] "GET /api/histories/01b9236ee4903f72/contents?limit=50&offset=57750&view=summary&keys=name%2Cfile_ext%2Cgenome_build%2Cmisc_blurb%2Cmisc_info%2Cannotation%2Ctags&details=&order=create_time&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True HTTP/1.1" 200
```

**Comment by martenson** [comment]
Could an approach of triggering a server-side search for histories > 500 items make sense? Possibly using Whoosh or some other search index? We have experience with this from tool panel, TS repositories, libraries etc.

**Comment by carlfeberhard** [comment]
@blankenberg Ok - more good feedback - thanks again. Looks like this needs to change direction. I should have expected the crash but I didn't think even 60k would take 2 hours.

@martenson possibly - I'll look a bit further. In any event, this needs to go back to WIP.

**Comment by blankenberg** [comment]
fwiiw, I'm still going to be using this branch on my instance with the large histories :)

**Comment by carlfeberhard** [comment]
@blankenberg Can you check the timing with the updated query (or share one of the mega-histories with me on test)? Rendering hasn't been changed yet - so clearing the search may still crash your browser.

**Comment by blankenberg** [comment]
timing:

```
[19/Apr/2016:14:57:23 -0400] "GET /api/histories/01b9236ee4903f72/contents?limit=500&offset=0&view=summary&keys=name%2Cfile_ext%2Cgenome_build%2Cmisc_blurb%2Cmisc_info%2Cannotation%2Ctags&details=&order=create_time&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True

[19/Apr/2016:15:08:20 -0400] "GET /api/histories/01b9236ee4903f72/contents?limit=500&offset=57500&view=summary&keys=name%2Cfile_ext%2Cgenome_build%2Cmisc_blurb%2Cmisc_info%2Cannotation%2Ctags&details=&order=create_time&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True
```

**Comment by carlfeberhard** [comment]
Thanks. If I can cut that 11 minutes down to 2-3, would you consider that reasonable for searching 60k datasets? I might be able to try loading details with 5 ajax calls and not just one.

[Edit: keep in mind this would only be for the first search after the page load. All additional searches would already have the data and would be much quicker]

**Comment by blankenberg** [comment]
2-3 minutes doesn't sound too bad, especially for the first load. 

I wonder if it would be possible to display the searched item count or a progress bar as things go along, as a spinner doesn't give the best feedback to the user ("is it even still working?").

**Comment by carlfeberhard** [comment]
Hmmm. It's appending found contents when it gets the batches of 500 items, but that's not as apparent as I thought it was. I can do the progress, too. Thanks

**Comment by blankenberg** [comment]
Ah, yes, the found things popping up in realtime are nice and are good indications when the search hits often, but when the search matches infrequently, only at the end, or never it is less effective. Thanks!

**Comment by carlfeberhard** [comment]
@blankenberg Can you try https://github.com/carlfeberhard/galaxy/tree/history-contents.pagination instead of this branch? 

Instead of infinite scrolling, it has the histories divided into sections of hids (currently 100) which are somewhat like pagination but also somewhat like 'minimizing' groups of contents (keeping them in the scrollable area).

Would something like what it does better suit the user story of moving between the end and the beginning? Does it preserve the ability to drag down to an (approximate section)?

If this ends up being a good fit, we can look to auto-expanding sections or even creating a sort of fish-eye-lens loading scheme with the scrollbar.

**Comment by blankenberg** [comment]
I'm not a fan of having to click to load the chunks, although it does provide for very quick navigation. 

Its a bit hard to look at things that fall across the numbered boundaries.

If we could make the current viewport load automatically, that might be helpful.

**Comment by carlfeberhard** [comment]
@blankenberg I'm finding auto-expansion (at least my ham-handed implementation thereof) clumsy and hard to control. You can try it here: https://github.com/carlfeberhard/galaxy/tree/history-contents.pagination

Difficult to describe the problem but may be mainly due to the scrollbar having to work across two different scales: the open section's datasets and the other sections. It's a bit like trying to use stairs that are occasionally different heights.

I doubt I'll pursue the auto-expansion much past the above commits and most likely will fallback to the sections that need to be clicked - since that, while very slightly onerous, allows the better control. Open to suggestions, tho.

**Comment by blankenberg** [comment]
Had a chance to try the auto-expansion and it seems nice in general. But there are issues as you mentioned:
-  thumb jumping around in the  scrollbar upon expansion
- difficulty in placing the cursor for the next block to draw (especially when using pgup and pgdn)
- Scrolling up doesn't seem as intuitive as scrolling down (e.g. you end up at the top of expanded block instead of the bottom)
- Previously expanded section is no longer expanded, can't view across boundaries

I wonder if it could be helpful to show smaller non-expanded blocks on the screen, but then expand as a larger block, and place the user at the selection area of the smaller block.
Something like

```
100-150
150-200
200-250
250-300
```

which after the user pauses over 200-250 the 0-500 block could be fetched and the user focus is placed at 200. This could maybe give the user more control, without needing more API calls.

Not sure of the best approach, but needing to click and not being able to look across block boundaries seem like significant impediments.

**Comment by carlfeberhard** [comment]
Ok - good feedback - thank you.

I agree the 'where does it jump to when expanding?' is a problem. It's designed to jump to the beginning when scrolling into the unexpanded sections from the top, and scroll to the bottom when scrolling in from below. Your subsections are an interesting idea - I'll think on that.

I think the two scales on the same scrollbar is what really makes it clumsy (at least with auto-expansion using the scrollbar) and is most likely a no go.

> Not sure of the best approach, but needing to click and not being able to look across block boundaries seem like significant impediments.

I agree completely on the 'look across block boundaries' but I wouldn't call the need for a single click to be a significant impediment. A click to the next page is common in paginated displays. Is there a reason why it would be deal breaker here?

**Comment by carlfeberhard** [comment]
Prototype 4(?): pagination using the scrollbar:
scrollable-pages

Pages are rendered in horizontally scrolling sections. Scrollbar 'gravitates' to the page boundaries This allows still 'dragging to a spot/time in the history' but circumvents needing to render all contents at once. Sections are independently scrollable vertically which also allows comparing across page boundaries.

Cons: 
- breaks cardinal rule of UI to not override the scrollbar behavior
- janky on firefox
- viewing sequential across boundaries is still awkward. Really the only way to solve this is half-pages: 1-100, 50-150, 101-200, etc. and those will involve clicking.
- relies on the still-_almost_ cross-browser flexbox
- complicates the code more than it helps the UI

Pros:
- no clicking

@blankenberg Since I have not heard from you on this, I have to assume your priorities have changed. I'm going to start cleaning this up and using a more conservative, click-based approach for pagination.

**Comment by bgruening** [comment]
@carlfeberhard sorry for being late to the game. I still like the first iteration the most.
What about a minimap that gets displayed next to your history (thinner than a normal code-minimap) maybe even with some markers (1k, 2k, 3k, 10k, 20k ...). 

The minimap could also recognise different tools/filetypes, assuming there are 1000 entries of FASTQ files, minimap could indicate with a small thin line that everything underneath is FASTQ ...

Just a few idea ...
Thanks for working so hard on this!

**Comment by carlfeberhard** [comment]
@bgruening Understood. Thanks for letting me know re: first iteration. I don't think that infinite scrolling is the best way to do this or assists many of our user tasks well.

And thanks very much for the idea. The main issue with a minimap (besides the amount of space it might take) and other methods (like viewporting - drawing only what's being displayed in the scrollable window) is that the DOM layout sizes (i.e. mostly the heights of datasets/collections) have to be rendered/known before hand. Our contents are variable height and wouldn't be able to be calculated until they're added to the DOM tree. 

So, these strategies that need to do the exact thing we're trying to avoid (render the entire history) don't seem like they can work. Or at least, I haven't figured out or found a way to do so.

I had considered a custom scrollbar with all hids somewhat _like_ the idea of a minimap (but with no 'structure' or miniature drawing) but the above does this as well. By scrolling horizontally, the user can move 'back in time' to the earliest hids. By separating the two scales onto two axes, (horizontally: course grain 'pages' of 100 hids, vertically: fine grain individual contents) I _think_ you can give the user a predictable, easy to use interface. So, finding 'data 648' becomes something like flipping through a book: move right to page 600-700, scan down to 648.

**Comment by bgruening** [comment]
@carlfeberhard thanks for your points!

I do think your last iteration can work and is a nice solution. However, I feel that we make the history to complicated for users that do not have > 2000 datasets. I would like to avoid additional clutter for normal users and only add a more complex interface for power users.

For example a minimap like approach could be optional and only displayed if > 2000 datasets with the possibility of hiding at any time. Moreover I do not see the minimap approach as a real-time view to the history, it should more or less indicate some interesting marks to jump to. For example 100, 1000, 10.000 or cluster of fastq-files, cluster of BAM files etc ... here it is not important to be accurate or to estimate the exact height of the history, important is to move to BAM files or to jump to the 10.000 dataset.

How frequent is the use-case that someone wants to jump to dataset 648 immediately? I think an estimation is enough and if such a use-case is really frequent we should think about a more powerful search-interface or a complete different history view for power-users.

Just want to keep the default interface as simple as possible.
Thanks again @carlfeberhard!

**Comment by carlfeberhard** [comment]
Yeah - I should've mentioned that the pages only display after some number of contents are added to the history. The interface remains the same for smaller histories.

**Pull request closed without merging**
