### PR TITLE
make LICENSE file reflect wiki

### PR DESCRIPTION
**Pull request by martenson**
our wiki license: https://wiki.galaxyproject.org/Admin/License

We might want to redirect the wiki completely to here?

disclaimer: I did not diff the full text

### CODE REVIEW

**Comment by natefoo** [comment]
Should PSU be the sole copyright holder?

**Comment by martenson** [comment]
ping @jxtx @tnabtaf @nekrut

**Comment by dannon** [comment]
Are all silk images gone?  If not, the silk creator states that, while CC BY 3.0 is fine, they would "...appreciate a reference to my authorship of the Silk icon set contents within a readme file or equivalent documentation for the software which includes the set or a subset of the icons contained within.", so we probably shouldn't remove that bit.

**Comment by natefoo** [comment]
@dannon They're still in use in the old libraries.

**Pull request closed without merging**
