### PR TITLE
[16.07] API, history contents: allow 'source' in payload

### PR DESCRIPTION
**Pull request by carlfeberhard**
In create, checks both kwd and payload for 'source' parameter when
creating a new hdca. This allows source to be passed in the body and
not query string.

This fixes the copy call in history-contents when copying an hdca
by drag and drop in the multi history view.

Fixes: #2807

### CODE REVIEW

**Comment by carlfeberhard** [comment]
Hmm. Not sure why the build artifacts are being shown as changed. Taking out of WIP.

**Comment by dannon** [comment]
@carlfeberhard I've been seeing some of that lately too.  My random guess is that it's differing versions of nodejs (or something else in the stack) causing the bundles to be different due to sorting/packing/whatever algorithm changes.

**Comment by martenson** [comment]
@dannon @carlfeberhard I agree, that's what it was the last two times I think. You only need one person to differ in the buildstack and we see these :/

**Comment by carlfeberhard** [comment]
You're both probably right. Hopefully we can get the artifacts out soon.

**Pull request merged**
