### PR TITLE
Add pre-commit config

### PR DESCRIPTION
**Pull request by mvdbeek**
[pre-commit](https://pre-commit.com/) is a nice utility that automates
setting up pre-commit hooks. You can use this with multiple tools, but
for now I've only set it up for black. If you choose to use pre-commit
(you don't have to!) you do `pre-commit install` once and then black
will run for each commit.

We could also just put the file under .gitignore if developers want
to set up their own custom config file, but I suppose having one for
everyone is probably nice?

(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Shouldn't we use https://github.com/akaihola/darker#using-as-a-pre-commit-hook instead?

**Comment by mvdbeek** [comment]
We could do that, but I finally tend to think maybe we shouldn't ship a config. I've added isort, and it's too slow to be workable for my taste. Maybe we can just ship a "sample" file ?

**Comment by mvdbeek** [comment]
I've updated the file as I'm using it now and moved it to `.pre-commit-config.yaml.sample`. So if you're happy with the sample you can just symlink it to `.pre-commit-config.yaml` or else you can put your own config.
I don't think we need darker, as pre-commit already runs the pre-commit hook on the changed files only.

**Comment by dannon** [comment]
@mvdbeek Not 100% working yet, but using make instead of the prebuilt hooks is going to be the way to go for the eslint hook; there are too many issues with changing directories and configs and `make` wraps that all up nicely.

**Pull request merged**
