### PR TITLE
Allow recovering a normalized version of workflow request state from API

### PR DESCRIPTION
**Pull request by jmchilton**
Implements https://github.com/galaxyproject/galaxy/issues/18981

Also made small improvements to the schema for running workflows. Filled in a bunch of stub descriptions, dropped ``step_parameters`` which never existed in the API. There is a random check that it isn't in the request because it a field that is included in the test format - but it shouldn't have been part of the schema.

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
I've included a sort of breaking change to the workflow invocation API here - it is isolated to https://github.com/galaxyproject/galaxy/pull/18985/commits/cc8f1b65b8da880d1b22135eea39220c3198b9c0. If you call a workflow by workflow ID and not a stored workflow ID - I think you should run that workflow and not the latest workflow. It feels quite jarring to say this is the particular instance ID I want to run and then get the latest version IMO. In either case if you explicitly pass a version - it will still run the workflow at that version.

**Comment by jmchilton** [comment]
Rerunning a failed test here - I haven't seen this before and it might be related. 

```
FAILED test/integration/test_workflow_refactoring.py::TestWorkflowRefactoringIntegration::test_upgrade_all_steps - AssertionError: assert '0.1.0' == '0.1.1'
  - 0.1.1
  ?     ^
  + 0.1.0
  ?     ^
```

**Comment by mvdbeek** [comment]
I have seen this quite a few times, I don't think it's related

**Comment by mvdbeek** [comment]
This is excellent, thanks a lot @jmchilton!

**Pull request merged**
