### PR TITLE
[18.05] Fix for use of `log.trace` in Slurm runner

### PR DESCRIPTION
**Pull request by natefoo**
Not sure why this hasn't cropped up before but I was hitting it in development.

### CODE REVIEW

**Review by dannon — APPROVED** [review]

**Comment by bernt-matthias** [comment]
SInce I would like to learn a bit I have to ask: why is  using `logging.getLogger` a problem? There are so many places where this is used...

**Comment by natefoo** [comment]
@bernt-matthias It's only a problem if you want to use `log.trace()`, which is a non-standard extension that's only available through `galaxy.util.logging`. It's hardly used at the moment, unfortunately.

**Comment by bernt-matthias** [comment]
cool. thanks

**Comment by bgruening** [comment]
Second :+1: from me. Feel free to merge.

**Pull request merged**
