### PR TITLE
[23.2] Npz sniffing: do not read the whole file

### PR DESCRIPTION
**Pull request by bernt-matthias**
Backport of https://github.com/galaxyproject/galaxy/pull/17672

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
@bernt-matthias This (as well as https://github.com/galaxyproject/galaxy/pull/17672 ) broke some integration tests, can you check please?

**Comment by mvdbeek** [comment]
I think I found a nice way to check this by checking if any zipped file is a `.npy` file in #17679

**Comment by bernt-matthias** [comment]
Hrm. Seems that npz files are just zip files .. contrary to the docs the only property that distinguishes them from zip files https://github.com/numpy/numpy/issues/26004

I could implement this test, i.e. get a file listing from the zip and check if all are `.npy`.  Otherwise I would suggest to drop the sniffer.

**Comment by mvdbeek** [comment]
except it's valid for some files not to be .npy files, so I'm using `any()` ... I don't think we care since sniffing doesn't have to be perect

**Pull request merged**
