### PR TITLE
[24.0] Clarify the object store relocate functionality

### PR DESCRIPTION
**Pull request by martenson**
Also include the configuration option in the samples.

# before
Screenshot 2024-04-19 at 1 27 14 PM

# after
Screenshot 2024-04-19 at 1 26 51 PM

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
It doesn't move - the bytes are where the bytes have always been - move seems like the wrong verb.

**Review by jmchilton — APPROVED** [review]

**Comment by martenson** [comment]
@jmchilton I understand that but I don't think the user needs to. They are moving it from bucket with one quota to another one. I made the change though -- thanks for the review.

**Comment by ahmedhamidawan** [comment]
Very minor but would it be useful to add an icon to the button
image
and/or change the variant to primary
image
to attract more attention to it...?

**Comment by martenson** [comment]
@ahmedhamidawan I think we should only be adding icons where either we have already clearly established visual language that goes with the function or where we aim for doing so. This feels like neither to me. Perhaps later, when we have more places that offer the function we could introduce a unified visual clue.

**Review by ahmedhamidawan — APPROVED** [review]

**Pull request merged**
