### PR TITLE
[23.0] Update interactivetool_ml_jupyter_notebook.xml

### PR DESCRIPTION
**Pull request by anuprulez**
Add changes to GPU Jupyterlab tool based on Jupytool

(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
@dannon is it ok if we get this one into 23.0?

**Comment by dannon** [comment]
@bgruening Sure, I've updated the base.  If you're happy with it go ahead and merge it in.

**Comment by bgruening** [comment]
Its running great on EU. Blog post coming soon... Lets get it in!

**Comment by bgruening** [comment]
Oh wait, @anuprulez I think you need to rebase it.

**Comment by anuprulez** [comment]
@dannon thanks for your changes. Should we also change the `profile="22.01"` to `profile="23.0"` to point it to the right Galaxy version? The branch is already ahead of `galaxyproject:dev`

**Comment by dannon** [comment]
@anuprulez Looks like this had dev merged in and should be rebased against 23.0 dropping the post-freeze dev-branch changes.  My understanding is that the profile should be the minimum compatible Galaxy version, not necessarily the current release.

**Comment by anuprulez** [comment]
Looks like it is rebased

**Comment by dannon** [comment]
It looks like the rebase went awry; I'll redo it to strip out the extra commits there.

**Comment by anuprulez** [comment]
Thank you @dannon

**Pull request merged**
