### PR TITLE
Add WorkflowBox to Activity bar Side Panel

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Add a "WorkflowBox" to the new ActivityBar side panel:
It has links to workflow activities/routes, as well as an advanced search workflow menu for the `WorkflowList`

https://github.com/galaxyproject/galaxy/assets/78516064/941c4d3a-4500-4a94-bcfb-986b4a156d35

<br ><br >

# Alternative Ideas for the future:
### A `WorkflowBox` identical (in terms of UI) to the `ToolBox` with all workflows (with just their names) in the client side search:
https://user-images.githubusercontent.com/78516064/236548780-ccd6d10b-3cdb-4a5b-b118-2c771c9f71ca.mov

### Only showing the bookmarked workflows in the panel (with more details for each workflow in view)
https://github.com/galaxyproject/galaxy/assets/78516064/60f8723f-c9a4-4526-91eb-c90109861a32
## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by ahmedhamidawan** [comment]
## Future idea? 🤔 
In the future (if we have the `ActivityBar` permanent), remove the search bar from the `WorkflowList` since we will already have a simple Workflow panel search as well as an advanced search that shows results in the center, like so:

https://user-images.githubusercontent.com/78516064/236549500-36c8c01f-43e0-4363-bec3-11d3ed8066ab.mov


We could hence, also get rid of the `Workflow` button from the Masthead since we'll already provide ways to navigate to that view through the panel

**Comment by mvdbeek** [comment]
I tested this and I think this suffers from a similar problem as @guerler's favorite workflow tooltip implementation: There's not enough context to differentiate workflows from each other. I think tags, description and update time are probably always required, and maybe the sharing status if this is to include public workflows. Could we simply not show the toolbox if we're not on the tool activity for now ?

As an alternative, could the workflow activity function as an extended search interface that is synced up to the current workflow list component ?

**Comment by ahmedhamidawan** [comment]
@mvdbeek Thanks for taking a look!
> I tested this and I think this suffers from a similar problem as @guerler's favorite workflow tooltip implementation: There's not enough context to differentiate workflows from each other. I think tags, description and update time are probably always required, and maybe the sharing status if this is to include public workflows. 

More fields could easily be displayed in the panel if needed, so stuff like `tags` or `update_time` could be added (don't know about description since we have only so much space in the left panel). This would also mean that the UI for the Workflow Panel would look very different from the Tool Panel; so we could then add section names like `tags` (and other fields) to the tools in the Tool Panel as well, to match the UIs.

> Could we simply not show the toolbox if we're not on the tool activity for now ?

By tool "activity", if you mean the active tab (like "analysis", "workflow" etc.), that could be done, but only concern might be that this would be a drastic change from the familiar UI where Tools are always toggled into view by default in the left panel when you load up Galaxy. But yes, we could definitely make it so that depending on what activity/tab you are on, the relevant panel is toggled into view by default. Keep in mind that even with the current implementation, the toggled state is saved if you refresh etc.
 
> As an alternative, could the workflow activity function as an extended search interface that is synced up to the current workflow list component ?

Did you manage to take a look at this from the comment i left above: https://github.com/galaxyproject/galaxy/pull/15944#issuecomment-1536669953
It's basically the same idea as the current `ToolsList` produced by the Advanced Tool Search. This would be a step taken when we decide to remove the `Workflow` button from the Masthead.

**Comment by ahmedhamidawan** [comment]
https://github.com/galaxyproject/galaxy/assets/78516064/60f8723f-c9a4-4526-91eb-c90109861a32

> Maybe you could have a first row with "Create new", "Import" and "Search" and then make that the default if you've clicked on the "Workflow activity" ?

@mvdbeek Is this better in that case.

So in this view, I'm still showing the favorited/bookmarked workflows, should we even show those? Or just for the bookmarked workflows, I think it also looks better to retain the same appearance as the Toolbox tools (like in the screencast at the top) with just the workflow names (again, only showing the `config.stored_workflow_menu_entries`).

**Comment by mvdbeek** [comment]
The 3 buttons are nice (and maybe you could keep the search expanded), but I personally don't like the workflows being displayed in the activity bar. I just can't imagine how I would use this and find it more useful than the center panel view.

Maybe one way to fill the screen estate is to have collapsible sections that correspond to workflow tags, so if you click on a tag it applies a filter in the center panel, similar to how file browsing works in the OSX finder (imagine that tags could act like folders):

Screenshot 2023-05-30 at 17 21 52

**Review by guerler — APPROVED** [review]
Thanks for the adjustments. Works well!

**Pull request merged**
