### PR TITLE
Reports: new pages and improvements

### PR DESCRIPTION
**Pull request by ghost**
The last merge request ( Dev reports #2334 ) has been corrected.

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@BalthazarPavot please see https://github.com/BalthazarPavot/galaxy/pull/2

**Comment by dannon** [comment]
Opened as #2664 with additional changes from @martenson.

**Comment by martenson** [comment]
given how close we are to the 16.07 release we will speed things up a bit, hope you don't mind @BalthazarPavot 

this is superseded by #2664

**Pull request closed without merging**
