### PR TITLE
Initial selenium tests for libraries.

### PR DESCRIPTION
**Pull request by jmchilton**
- Test importing datasets from histories.
- Test basic importing of a dataset from a path.
- Test creating a folder.
- Test create library, renaming a library, filtering libraries by name, and sorting of libraries.
- Test various buttons (e.g. details, help).

### CODE REVIEW

**Comment by martenson** [comment]
Awesome! 🎉

**Comment by martenson** [comment]
this might need a rebase to get rid of https://github.com/galaxyproject/galaxy/pull/4543/commits/a91c03d4403ad57336ce5cc235b22cf4be5ebd6d

**Comment by jmchilton** [comment]
Thanks @martenson - will do.

I have admit I spent a couple more hours on this last night and I still cannot get this working consistently. The biggest problem is that I cannot get the search box to work in Selenium. The search box for the published histories grid just works with selenium's ``send_keys(text)`` method - but the keyUp handler that libraries uses don't seem to recognize this. I've tried a number of work arounds - I'll keep trying though.

**Comment by jmchilton** [comment]
Rebased on top of #4732 and significantly cleaned up - a lot closer to consistently passing now.

**Comment by martenson** [comment]
Github is showing some weird diff for this PR

**Comment by martenson** [comment]
I checked out this branch again and the changes in e.g. `client/galaxy/scripts/mvc/history/history-view.js` are still there (comapred to up-to-date dev). That feels wrong?

**Comment by jmchilton** [comment]
Rebased and the diff is much cleaner now.

**Comment by martenson** [comment]
splendid, thanks a lot @jmchilton !

**Pull request merged**
