### PR TITLE
Bugfix - do not initiate empty FTP uploads.

### PR DESCRIPTION
**Pull request by jmchilton**
Broken with #4513.

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot selenium test this.

**Comment by jmchilton** [comment]
@galaxybot selenium test this

**Comment by jmchilton** [comment]
Thanks @galaxybot! This is definitely an issue that seems fixed by my local testing and was reported by @martenson yesterday. I don't understand the Selenium failures though - they don't happen locally so I launched a test against dev to try to figure out if this PR broke it or if it is simply broken against dev in some way that wasn't an issue in the branch of #4757.

Update: Yeah - dev seems to just be broken with Jenkins' Selenium... never with Selenium on my machine of course.

**Comment by guerler** [comment]
👍 Thanks for fixing this.

**Pull request merged**
