### PR TITLE
Allow user customization of the activity bar

### PR DESCRIPTION
**Pull request by guerler**
This PR allows users to show, hide and re-order individual activity bar items. This PR only provides the framework for these operations, we should separately discuss which activities should be available once the framework is in place. All current activities are purely for demonstration reason. The activity bar state is currently persisted on the client, a separate PR will persist the state in the database.

https://github.com/galaxyproject/galaxy/assets/2105447/306dfd07-bc28-45bf-9f08-26c8dae5fece

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
* if you enable "invocations" the bar gets thicker and jumps
* if you click on one of the activities, it would be nice if the focus/cursor would be in the opened page - e.g the search bar in the workflow list page
* Would a very thin line as a separator between the activity bar and toolbar and/or the normal pages maybe look cleaner? Currently, there is only a color difference between grey and white 

And here is a tricky one. It seems the items have a small border that is clickable - you see the item flashing as with a normal click, but the page is not opening. Try going to the right border of an item, as far as you can but so that it's still clickable - it's a very tiny area. I could reproduce that with Chrome and FF.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Very cool! Works nicely for me.
With the activity bar, we see unfortunately easily how inconsistent our design is across various pages :)

I like the UX and the infrastructure behind it - I hope we can build on that to make our features more visible.

**Comment by bedroesb** [comment]
@bgruening and @guerler Hello! I recently stumbled upon the addition of borders for the panels. I just wanted to share that in a world where I see borders on the web disappearing, like in Google (docs)/Facebook/Office, I am surprised to see new ones appearing here :) Very nice work nonetheless!

**Comment by martenson** [comment]
I think we're safe from border-free world yet :)

Google_Docs
Mail_-_Cech__Martin_-_Outlook

**Comment by bedroesb** [comment]
ok my turn :) 
Google apps new vs old:
image

Slack old vs new:
image

Nextcloud new vs old:

image

In these screenshots you see all a similar trend in the latest design changes of these platforms: everything more rounded, and lots of more use of slight opacity differences/color differences

**Comment by bedroesb** [comment]
(off course one will still find borders! But I don't know many examples of places where a new border was added in there latest design changes, but the opposite is quite easy)

**Pull request merged**
