### PR TITLE
[PROCEDURES] Add Laila as a committer

### PR DESCRIPTION
**Pull request by dannon**
Laila has made many fantastic contributions since joining (https://github.com/galaxyproject/galaxy/pulls?q=is%3Apr+author%3AElectronicBlueberry), has been very helpful and constructive in code review, and has provided valuable insight in technical discussions and decision making -- especially in the UI/UX group, but reaching into other areas as well.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
🎉🎉🎉

**Review by natefoo — APPROVED** [review]

**Review by nsoranzo — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]
Very exciting - huge +1 from me.

**Review by bgruening — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]

**Review by nuwang — APPROVED** [review]

**Review by martenson — APPROVED** [review]

**Review by blankenberg — APPROVED** [review]

**Review by davelopez — APPROVED** [review]
:+1: :100: :+1:

**Comment by martenson** [comment]
Welcome Laila, we are so happy you joined!

**Pull request merged**
