### PR TITLE
Add iRODS resource name in calls to irods

### PR DESCRIPTION
**Pull request by kxk302**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by natefoo** [comment]
This looks good to me, I can deploy to test.galaxyproject.org before it's merged to make sure it fixes the issue we were seeing.

Is a resource name required for fetch/get operations? My only concern here would be that at some point we hope to replicate some datasets to tape and then delete them from the disk resource. If you don't specify a resource I would hope that it fetches from whatever resource has a copy (although if there are multiple replicas I don't know how it chooses which one to fetch if you don't specify - if it's on both disk and tape we obviously would want to fetch from disk).

**Comment by kxk302** [comment]
> This looks good to me, I can deploy to test.galaxyproject.org before it's merged to make sure it fixes the issue we were seeing.
> 
> Is a resource name required for fetch/get operations? My only concern here would be that at some point we hope to replicate some datasets to tape and then delete them from the disk resource. If you don't specify a resource I would hope that it fetches from whatever resource has a copy (although if there are multiple replicas I don't know how it chooses which one to fetch if you don't specify - if it's on both disk and tape we obviously would want to fetch from disk).

Right now we only have a single storage resource. If we want to try fancier setups, we need to have a coordinating resource at the root, which manages how the children storage resources serve the requests. In that case, we configure irods in Galaxy to use the coordinating resource name.

**Comment by natefoo** [comment]
Ah so in that case we would provide the root coordinating resource name with the get request?

**Comment by natefoo** [comment]
I reset the default resource for our iRODS server back to `demoResc`, deployed your branch on Test, ran a job, and it looks good:

```
[g2test@galaxy07 ~]$ ils -L 9/7/7/dataset_977f7756-1894-4fca-a219-806851f16230.dat
  g2test            0 testRootResc;testCorralResc            0 2021-12-16.14:16 & dataset_977f7756-1894-4fca-a219-806851f16230.dat
        generic    /galaxy/test/Vault/home/g2test/9/7/7/dataset_977f7756-1894-4fca-a219-806851f16230.dat
```

Deleting from the cache and re-fetching also works.

**Review by natefoo — APPROVED** [review]

**Review by mvdbeek — APPROVED** [review]
Thanks @kxk302

**Pull request merged**
