### PR TITLE
add isa-rwal to default pipfile

### PR DESCRIPTION
**Pull request by martenson**
it is in pinned already

followup to https://github.com/galaxyproject/galaxy/pull/5787

### CODE REVIEW

**Comment by nsoranzo** [comment]
Some of the isa-rwal dependencies are missing from requirements.txt, I'll push a fix to your branch if that's OK.

**Comment by martenson** [comment]
@nsoranzo that is very ok

**Review by nsoranzo — APPROVED** [review]

**Comment by mvdbeek** [comment]
There are some other things that are not quite right in https://github.com/galaxyproject/galaxy/pull/5787, is anyone on this already ?

**Comment by nsoranzo** [comment]
@mvdbeek I'm not.

**Comment by martenson** [comment]
@mvdbeek I don't think so.

**Comment by nsoranzo** [comment]
@mvdbeek Small follow-up in commit https://github.com/galaxyproject/galaxy/pull/6921/commits/21189b213f10687ca0e211bd5fc379f5316e2769 .

**Pull request merged**
