### PR TITLE
removed config.ini parameter from cleanup scripts

### LINKED ISSUE #5941: cleanup scripts and config.ini -> config.yml
I have a kind of question/issue. Do the cleanup script need to be updated to the new yml config file? I guess this would be only the .sh files.

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/galaxyproject/galaxy/issues/5941

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
It would be nice to have this backported to 18.01 (before or after the merge).

**Comment by bernt-matthias** [comment]
Which would mean to open another PR against 18.01? Or how would one do this?

**Comment by nsoranzo** [comment]
If you open a PR against 18.01, then after it's merged it will be merged forward to the `dev` branch. If instead this one is merged, a new backport PR for 18.01 will need to be created.

**Comment by bernt-matthias** [comment]
done.

**Pull request closed without merging**
