### PR TITLE
Beta History: display 'processing' message while running bulk operations

### PR DESCRIPTION
**Pull request by davelopez**
Requires #13783

See individual commits for details.

operation-message

## How to test the changes?
- [x] Instructions for manual testing are as follows:
  - Run any history operation in bulk (with more than 10 items)

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
Testing this locally I just ran into a bit of a glitch when switching histories; it got stuck here, never updating:

image

Let me nail down an exact sequence of events that caused it.

**Comment by davelopez** [comment]
Thanks for the feedback @dannon!

> Testing this locally I just ran into a bit of a glitch when switching histories; it got stuck here, never updating:

Yeah, that is probably missing the change status event when the operation ends... I'll investigate :+1: 

> Another issue while experimenting with this on smaller histories:

Ok I know what's happening here... I thought it would be better to show the message only on 'bigger'' bulk operations but apparently is better to show it always :sweat_smile: I will fix it right away!

**Review by dannon — APPROVED** [review]
@davelopez Thanks for the quick fixes!  Looks great, working well for me.

**Comment by guerler** [comment]
I noticed that the bulk selector now closes when the `x` is clicked, previously it just unselected all. Is that intentional?

**Comment by davelopez** [comment]
Definitely not intended! Thanks for the catch, will fix it!

**Pull request merged**
