### PR TITLE
Converters: Unify dcd, trr, xtc

### PR DESCRIPTION
**Pull request by bernt-matthias**
Unifies the converters for the dcd, trr, and xtc datatypes.

- [ ] toolshed has a similar tool: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/blob/master/tools/mdfileconverter/md_converter.xml
that covers a few more cases. Could be extended here as well.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by bgruening** [comment]
@bernt-matthias how is the UX here:

grafik

This is more confusing isn't it for the user?

**Comment by bernt-matthias** [comment]
Ahh. I see, we should have considered this here https://github.com/galaxyproject/galaxy/pull/12185. For the biom converters this is already done.

Any idea where the list is generated?

**Comment by bernt-matthias** [comment]
Also odd that not the name of the converter is used, it should be derived from `name="Converter for XTC, DCD, and TRR"`, or?

**Comment by bernt-matthias** [comment]
Guess I fixed this in https://github.com/galaxyproject/galaxy/pull/12230 .. thanks for checking this.

**Comment by simonbray** [comment]
Cool, thanks @bernt-matthias

**Pull request merged**
