### PR TITLE
Reports newpage

### PR DESCRIPTION
**Pull request by OldWorldBoa**
Continues #408

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1: - this all looks really nice. Very cool enhancements @Airistotal - please keep up the excellent work.

I opened a PR against this branch to separate things out a little - https://github.com/Airistotal/galaxy/pull/1 - so that Galaxy doesn't need to load reports-specific CSS on every page. Any thoughts?

**Comment by OldWorldBoa** [comment]
I really like that. Putting the styles into the base.less was annoying since it was decently hard to find things.

**Comment by martenson** [comment]
I will copy my comment from https://github.com/Airistotal/galaxy/pull/1 here also, in case we lose the fork.

@jmchilton I think the concept of having one base.css is to prevent loading dozens of style files which is more resouce-costly than having base.css few dozens/hundreds lines longer (esp given that it is getting minified)

@Airistotal the styles can still be in its own file reports.less but would be included in base.less as an import (so you wouldn't need to search base.less)

I believe we should have a debate before we abandon this concept, even for reports, as we were trying to keep this approach consistent before. @carlfeberhard @jxtx ?

**Comment by jmchilton** [comment]
Yeah - agreed. This was a half baked change on my part. Continuing with the logical separation bit adding a less import would still be a good idea right?

**Comment by OldWorldBoa** [comment]
^ I like that idea. That'll make my job easier.

**Comment by martenson** [comment]
@jmchilton I believe so.

**Comment by martenson** [comment]
looking very good, the only problem I have found is a server error when attempting to show `jobs per user` resulting in this exception: https://gist.github.com/martenson/f23013b4b2929bf645a3

**Comment by OldWorldBoa** [comment]
There you go @martenson. That should fix the problem.

**Comment by martenson** [comment]
looks great @Airistotal - thank you very much for working on this!

**Comment by bgruening** [comment]
Can't wait to play with this! 
@Airistotal thanks so much! Keep rocking!

**Pull request merged**
