### PR TITLE
[16.01] Undo user icon in masthead

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by jmchilton** [comment]
I'd be interested in commentary about why? I like the change but I'll always defer to you on these things so you can have my :+1:, but I'd be interested to know why.

**Comment by martenson** [comment]
@jmchilton 

```
14:22:41      jxtx | Okay, I apparently totally missed this. Who changed the User tab to an icon?                                             │ mrscribe
14:23:11    dannon | https://github.com/galaxyproject/galaxy/pull/1407 I think.                                                               │ natefoo
14:23:13  mrscribe | Title: Masthead/Scratchbook revision and test cases by guerler · Pull Request #1407 · galaxyproject/galaxy · GitHub (at  │ nitesh
                   | github.com)                                                                                                              │ nsoranzo
14:24:22      jxtx | not a fan, sorry guerler, it makes user look like it is grouped with scratchbook rather than the tab menu.               │ perrier_
14:24:39   guerler | I guess, I should highlighted it more. I'll change it back.                                                              │ pescobar
14:25:24      jxtx | (mine is only one opinion)                                                                                               │ pvh_sa
14:25:43    dannon | I conveyed the same exact opinion to him a week ago, so that's 2 ;)                                                      │ relrod
14:26:00 ceberhard | And a week back for me = 3.                                                                                              │ saskia
14:26:29 ceberhard | I’d also mention the disabled menus.                                                                                     │ shiltemann
14:27:54   guerler | disabled menus?                                                                                                          │ takadonet
14:28:18 ceberhard | Previously an anonymous user would see the visualizations and workflow menus disabled.                                   │ the_cull
14:29:02   guerler | ok                                                                                                                       │ vk
14:33:14   guerler | https://github.com/galaxyproject/galaxy/pull/1493

```

**Comment by guerler** [comment]
This change is at least controversial, so I rather undo it and wait until we have consensus on how to style the masthead.

**Comment by jmchilton** [comment]
Thanks for the context!

**Pull request merged**
