### PR TITLE
[18.09] Keep xlsx files compressed

### LINKED ISSUE #6849: sniffing of xlsx file as blastxml
reported on galaxy-dev, example file: [Book1.xlsx](https://github.com/galaxyproject/galaxy/files/2465937/Book1.xlsx)
screenshot 2018-10-10 14 18 04

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes #6849

### CODE REVIEW

**Comment by nsoranzo** [comment]
LGTM, should we have a unit test for this?

**Comment by martenson** [comment]
@nsoranzo I started one earlier today, I will finish it and push to @mvdbeek branch

**Comment by mvdbeek** [comment]
I think it'd be nice to test the shipped test data in an integration test case with and without auto_decompress, but I'd target dev with that.

**Comment by nsoranzo** [comment]
> I think it'd be nice to test the shipped test data in an integration test case with and without auto_decompress, but I'd target dev with that.

Agreed, but for 18.09 we could just add a unit test to verify that xlsx are sniffed correctly.

**Comment by mvdbeek** [comment]
It's not that I don't want to add a unit test for sniffing, but it wouldn't have caught the issue here, since the sniffing worked fine before, unless that would be a more intricate unit test that tests the  upload_util module.

**Comment by nsoranzo** [comment]
Isn't https://github.com/galaxyproject/galaxy/issues/6849 about xlsx sniffed as blastxml ?

**Comment by mvdbeek** [comment]
Yes, but it's not the sniffer's fault, if you have a datatype that is not marked as compressed the first file in the archive will be unpacked and sniffed, which in the case of xlsx files is a xml manifest.

**Comment by martenson** [comment]
@mvdbeek The manifest should still not be sniffed as blastxml given the process described by @peterjc. However given the work in https://github.com/galaxyproject/galaxy/pull/6869 I think unit tests is not getting us much here and we are pretty unlikely to touch this in release branch I guess.

**Pull request merged**
