### PR TITLE
Only keep the last path element when naming files uploaded via the URL paste method

### PR DESCRIPTION
**Pull request by natefoo**
As requested by @nekrut. It won't do anything with ugly parameters, though. We could strip those too if we wanted.

### CODE REVIEW

**Comment by martenson** [comment]
@The change makes sense, however every single screenshot or screencast will now be different from what you will actually see. Worth noting I think.

Also, from @natefoo:

> also if anyone has scripts that modify the name as part of a pipeline that could break

**Comment by jmchilton** [comment]
I'd also wait for the tests - I wouldn't be surprised if some need to be updated. I can do that if any do.

**Comment by nekrut** [comment]
screenshots and videos I can live with. this is a GIGANTIC usability improvement for users

**Comment by bgruening** [comment]
I second @nekrut this is good for UX, but it can probably break workflows as people (proteomics for example) might use the name from a dataset :(
Let's put this in the release notes.

**Pull request merged**
