### PR TITLE
Rename mvc/tools to mvc/tool

### PR DESCRIPTION
**Pull request by guerler**
All other ui components are singular i.e. workflow, dataset, history, grid, job etc. This fix avoids confusion and brings the directory structure into alignment.

The PR can be tested by loading a tool using 1) the regular tool panel, 2) the re-run icon in the history panel, 3) the workflow editor and 4) a tool URL such as http://127.0.0.1:8080/root?tool_id=addValue.

### CODE REVIEW

**Comment by carlfeberhard** [comment]
This will be fun to merge: https://github.com/carlfeberhard/galaxy/commit/d285c01108f59d1b054955f312b16c3b978aa97a

**Comment by dannon** [comment]
Since this isn't a functional change, maybe we hold off on it pending the webpack move, after which it'll be easy?

**Comment by guerler** [comment]
I am fine with merging it after the web pack PR.

**Comment by carlfeberhard** [comment]
Wasn't asking for a wait. Merely pointing out I had done this already ~5 days ago and it would be interesting to try and merge the versions. Don't hold up on my account - I'll work it out.

**Comment by guerler** [comment]
Closing this since it has already been done in another upcoming PR.

**Pull request closed without merging**
