### PR TITLE
Remove biomart_test tool, http://test.biomart.org/ is down.

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by jmchilton** [comment]
Are we pretty confident it is not just temporarily down, should we e-mail them or something? I have googled around and I cannot find any announcement that it has been taken down permantently - but I have also not found any announcement that it ever existed :).

**Comment by nsoranzo** [comment]
An e-mail from the Galaxy team to confirm that may be indeed a good idea. Anyway there is still `data_source/biomart.xml` .

**Comment by nsoranzo** [comment]
Also `wormbase_test` is broken:

Not Found

The requested URL /db/seq/gbrowse/c_elegans/ was not found on this server.

**Comment by jmchilton** [comment]
Okay - it has been several days and it is still down and web searches are still failing me so I am merging this. Thanks for the fix @nsoranzo.

**Comment by martenson** [comment]
:+1:

**Comment by blankenberg** [comment]
We should have contacted the external services about this before merging this.

**Comment by jmchilton** [comment]
@blankenberg If you contact them and they bring the server back up I will glad open a new PR to roll this back - in the meantime this was broken.

**Pull request merged**
