### PR TITLE
Reports homepage

### PR DESCRIPTION
**Pull request by OldWorldBoa**
Changed the default page of the galaxy report webapp to be informative graphs rather than jobs per day this month

### CODE REVIEW

**Comment by jmchilton** [comment]
Wonderful - this is a very cool little control panel. I am :+1: on this.

We just changed up the flake stuff this morning so I have opened a PR to resolve the conflict and bring your branch in line with the latest dev. https://github.com/Airistotal/galaxy/pull/2.

**Comment by OldWorldBoa** [comment]
I just have one last commit to do which is moving the script and style to the proper places, but I'm glad you like.

**Comment by OldWorldBoa** [comment]
I also need to remove snap.svg. It turns out I don't need it.

**Comment by dannon** [comment]
@Airistotal Seeing several errors here, missing files?

```
GET http://localhost:9001/report/static/images/reports_webapp/home-icon-hov.png [HTTP/1.0 404 Not Found 1ms]
GET http://localhost:9001/report/static/scripts/reports_webapp/run_stats.js [HTTP/1.0 404 Not Found 4ms]
GET http://localhost:9001/report/static/scripts/reports_webapp/run_stats.js [HTTP/1.0 404 Not Found 1ms]
ReferenceError: create_chart is not defined
```

Edit:  Needs a grunt build.  Sending PR.

**Comment by dannon** [comment]
(to be clear, -1 until the fixes from https://github.com/Airistotal/galaxy/pull/3 are addressed in some way)

**Comment by dannon** [comment]
One more d3 fix incoming and then this will look great to me!

**Comment by martenson** [comment]
Is it supposed to look like this? Why are the graphs on the side much smaller than the middle ones? I can barely read the axes. Could it be caused by the lack of data?
screenshot 2015-08-03 10 03 30

**Comment by dannon** [comment]
@martenson They resize on focus (which I'm not sure I like, either).  You can click them to make them larger/smaller.

**Comment by martenson** [comment]
Cool! I like it. @Airistotal can you please think of some hint to users that they can click on graphs to zoom? I did not figure that out myself. :smile:

**Comment by dannon** [comment]
That's a good idea.  I'll try to get that last d3 fix I mentioned above done today and this should be more or less ready then.

**Comment by dannon** [comment]
Now I'm unable to reproduce the d3 error I had last week.  The problem was d3.event.path being undefined (on mouseover of one of the bars) -- has anyone else seen this?  If not, I'm happy to write it off as a local config issue and move on w/ a +1.

**Comment by OldWorldBoa** [comment]
I can't say I've seen that error yet, but it could easily be an edge case in my calculations. I'll look them over again and see if anything stands out.

**Comment by OldWorldBoa** [comment]
Also, instead of writing a tip, what if I make the cursor change to a zoom icon when hovering over the graphs? I'll do that and see what you think of it.

**Comment by OldWorldBoa** [comment]
I've looked it through and there wasn't anything out of place @dannon . Let me know if you experience the error again and I'll look into it.

**Comment by martenson** [comment]
@Airistotal I like the change. Thank you very much for your work!

**Pull request merged**
