### PR TITLE
Tool form error messages and rerun fixes

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by bgruening** [comment]
:+1:

**Comment by dannon** [comment]
Wow, way too fast of a merge.   @blankenberg Can you elaborate on the form error fix?  (+1 to the other bit, though)

**Comment by blankenberg** [comment]
Try to rerun an upload job previous to these commits, you'll sit there staring at a blank white window indefinitely, without any feedback.

**Comment by dannon** [comment]
That part was fine, I agree that the API should respond like that.  I was wondering about the new, empty form logic: https://github.com/galaxyproject/galaxy/pull/766/files#diff-b2dc7e14d68766f211fa40a53c2eeb5dR121

Since this was already merged, I'll follow up with a PR reflecting what I'd have suggested.

**Pull request merged**
