### PR TITLE
[16.10] Display tool requirements for conda-only tools

### LINKED ISSUE #3257: find a remedy for Conda-only tools in Conda-less Galaxies
The current situation is that if you don't have Conda (which is optional and a config option) and you try to install Conda-only tool (which are some now, including major ones like fastqc) you will be presented with an installation dialogue completely ignoring dependencies. You are not even notified about this situation during the installation. After the tool is installed (without any deps) it will **not run** or run with **random binary from PATH**. This is bad.

Basically you are forced to somehow provide the binary manually and you are losing reproducibility. 

We should do something with it, for 16.10. At least a warning and info about how to enable Conda.

Thoughts? @mvdbeek @jmchilton @bgruening

### PR DESCRIPTION
**Pull request by mvdbeek**
With this PR we display tool requirements as defined in the tool xml during
the install confirmation dialog. If a tool dependency is defined in the
tool XML, but not in a tool_dependencies.xml, a warning is shown if
conda is not activated.
This should close #3257.

Ping @martenson

### CODE REVIEW

**Comment by mvdbeek** [comment]
This is what it looks like if conda is installed (and in that case the dependency has been previously installed as well):
dep already installed through conda

And this is when conda is not active and you try to install a conda-only tool:
conda_unavailable

**Comment by martenson** [comment]
Heh, just after I promise in #3257 that we will fix this, you come up with a solution in a PR. This is great! Thanks a lot @mvdbeek !!!

**Comment by mvdbeek** [comment]
Hehe, so aim for 16.10, or backport later?

**Comment by martenson** [comment]
aim 16.10 would be my choice

**Comment by martenson** [comment]
thanks again @mvdbeek - you maintain an impressive track of contributions!

**Pull request merged**
