### PR TITLE
Option to sort counts in Count1 aka tools/filters/uniq.xml

### PR DESCRIPTION
**Pull request by peterjc**
Adds the option to sort the tally table in increasing or decreasing count order (defaulting to the current behaviour of sorting on the entry value). Includes tests for this proposed new features.

I am using the output from the `Count1` for the Galaxy Pie Chart visualization, which appears to show the entries in the order from the file (starting at the top of the pie, then going clock-wise). It is therefore especially useful to be able to have the output from `Count1` pre-sorted as per this enhancement.

Replacement for pull request #15, which was re-based to include the trailing space fix (see #13), and fix numerical sorting versus alphabetical sorting (note the test input file was expanded to ensure the counts now include double digits).

P.S. This also bumps the version number again.

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/CKKX7U23) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/16.patch) for testing.

**Comment by jmchilton** [comment]
Like it. One small thing though - as a general rule we are no longer putting files in `test-data` if it is only used for tool testing (and we have carefully stripped the history of that directory). I have added these test files to the new test data repository with https://github.com/galaxyproject/galaxy-test-data/commit/2331ec6871c664f2cc492bb84b4f86dbbba24590 - so these tests will continue to work if the test data is removed (they did in my tests anyway).

So can you rebase this PR so that test data never existed :)? If you don't mind me messing with the integrity of your commits I am happy to rewrite them myself and merge directly. Up to you.

(People should let me know if this request is overkill - stripping out a 100 Mb trinity test case is a much different scale than a handful of small tabular data files).

Otherwise, a strong :+1: from me.

**Comment by peterjc** [comment]
Hi John - I'm happy for you to tweak the commits to strip the test file history - otherwise I can do that next week. Thanks!

**Comment by jmchilton** [comment]
Awesome, I'll try to do that soon. Just to clarify - this includes everything from #13 right?

**Comment by peterjc** [comment]
Yes, this pull request branch continued from the branch I used for #13, so you get everything here.

Note minor merge conflict with the tool version with the merger of #14 done.

**Comment by jmchilton** [comment]
Rebased without test data and merged directly. Thanks for the fixes Peter!

**Pull request closed without merging**
