### PR TITLE
Fix integration test for default Conda mapping.

### PR DESCRIPTION
**Pull request by jmchilton**
It worked locally simply because I had R already installed on my system globally.

Ping @mvdbeek - I know you are working on the mapping stuff so I'm pinging you in case you run into the same testing bug.

### CODE REVIEW

**Comment by mvdbeek** [comment]
huh, I hadn't noticed this, we should really be running those integration tests!
👍

**Comment by jmchilton** [comment]
It is a bit of a chicken and egg problem with these tests (integration and Selenium). I can't fix them fast enough to keep them stable long enough to feel confident enable PR checking.

**Comment by mvdbeek** [comment]
But if you enable them we can adjust them if ~~we want to get the PR merged~~ warranted ... :).

**Comment by jmchilton** [comment]
@galaxybot test this

**Pull request merged**
