### PR TITLE
Fix the ChangeDirectory.execute_step() method and enhance the

### PR DESCRIPTION
**Pull request by gregvonkuster**
"directory" recipe step classes to perform within the temporary working
directory created by the InstallEnvironment.make_tmp_dir() method (via
the use of a new $TMP_WORK_DIR reserved word in recipes) in addition to
the $INSTALL_DIR reserved word (which has always been supported in
recipes).

This commit grew out of a fix for the following code in the
ChangeDirectory.execute_step() method, which does not perform as the
comment describes:

```
# Change directory to a directory above the current working directory,
but within the defined work_dir.
dir = target_directory.replace( os.path.realpath( work_dir ), ''
).lstrip( '/' )
```

The resulting directory is always within the current working directory
rather than "above" it.  The new $TMP_WORK_DIR reserved word points to
the actual temporary working directory, so recipes now have a way to do
perform actions within that directory during the compilation and
installation process.  This is very useful for more complex recipes that download and install more than one file.

For example, if you want to install Python and then install numpy into that Python, you can now do the following (notice the use of $TMP_WORK_DIR in the numpy section).

```
<!-- by default Python is not looking at LD_INCLUDE_PATH and Co. -->
<action type="shell_command">sed -i -e "s/if host_platform == 'atheos':/if True:/g" setup.py</action>
<action type="autoconf">--enable-shared</action>
<action type="download_file">https://bitbucket.org/pypa/setuptools/get/5.2.tar.bz2</action>
<action type="shell_command">tar -xjf 5.2.tar.bz2</action>
<action type="change_directory">pypa-setuptools-f493e6c4ffd8</action>
<action type="shell_command”>
   $INSTALL_DIR/bin/python setup.py install --prefix=$INSTALL_DIR
</action>
<!-- Install and compile numpy 1.9 as a package in the above Python -->
<action type="make_directory">$TMP_WORK_DIR/numpy</action>
<action type="change_directory">$TMP_WORK_DIR/numpy</action>
<action type="download_file" target_filename="numpy-1.9.0.tar.gz">https://pypi.python.org/packages/source/n/numpy/numpy-1.9.0.tar.gz#md5=510cee1c6a131e0a9eb759aa2cc62609</action>
<action type="shell_command">tar xfvz numpy-1.9.0.tar.gz</action>
<action type="change_directory">numpy-1.9.0</action>
<action type="shell_command">
    $INSTALL_DIR/bin/python setup.py install --prefix=$INSTALL_DIR
</action>
```

Before this PR, the "make_directory” and “change_directory” actions would only function from within the current working directory "downward", so the numpy file would have been downloaded to a directory under pypa-setuptools-f493e6c4ffd8 within the python directory hierarchy. This became messy with multiple downloads.   Now, everything can be handled from the temporary working directory, so you would have something like:

<TMP_WORK_DIR>/python/…
<TMP_WORK_DIR>/numpy/…
etc.

This “more clean” approach makes it easier to debug complex installs because each package is contained within it’s own clean directory hierarchy.

These changes should not affect backward-compatibility for older recipes because the "directory" actions that do not make use of the $TMP_WORK_DIR reserved word should behave as they always did.

### CODE REVIEW

**Comment by jmchilton** [comment]
I am not so much worried that this is too much magic - just that it is different and implemented differently than our other magic. Could we just add add `TMP_WORK_DIR` to `basic_util.get_env_var_values` so that it would be used the same way as `REPOSITORY_INSTALL_DIR` or `INSTALL_DIR` - for instance some people would expect a `$` at the beginning of a substituted variable or might want to use this variable in a shell command.

Is there a problem with this approach? It probably means we would need to pass more things through `evaluate_template` but that seems like it would be a good thing to me anyway. Thoughts?

**Comment by gregvonkuster** [comment]
@jmchilton Sure, I can rebase the PR to use that approach.  I assume you would like TMP_WORK_DIR to include the "$", making it $TMP_WORK_DIR.  Let me know if not.  Thanks

**Comment by bgruening** [comment]
@gregvonkuster I think the idea is to use the same mechanisms as `$REPOSITORY_INSTALL_DIR` and `$INSTALL_DIR`.

**Comment by gregvonkuster** [comment]
@jmchilton @bgruening Please le me know if this looks ok when convenient.  I had several code merges to perform since there were several PRs accepted that altered these same files since my initial PR.  I've tested fairly thoroughly.

**Comment by jmchilton** [comment]
Yeah - this is what I meant I think - looks nice. Thanks for the change @gregvonkuster. :+1:

**Comment by jmchilton** [comment]
Before patch the tool shed tests report `FAILED (errors=47, failures=27)` after `FAILED (errors=47, failures=27)` - so I am going to merge this :worried:.

**Comment by gregvonkuster** [comment]
@jmchilton  Thanks for merging!

**Comment by martenson** [comment]
thanks for contribution @gregvonkuster !

**Pull request merged**
