### PR TITLE
ENH: multifile zip testing

### PR DESCRIPTION
**Pull request by thermokarst**
This changeset introduces the ability to individually test zip archive members --- useful for working with multi-file zip archives (_ahem_, looking at you, @qiime2).

```xml
<has_archive_member path="testdir1/dir1/file3">
    <has_line_matching expression="subdirfile" />
</has_archive_member>
```

This PR attempts to emulate the changes introduced in https://github.com/galaxyproject/galaxy/pull/7301 (detailed testing of HDF5 attributes).

I am open to [other alternatives](https://github.com/galaxyproject/galaxy/pull/7297#issuecomment-459973607) for solving this problem, but given the discussions in #7297 & #7301, it _seems_ like this might be the "right" way to go. Anyway, thanks for entertaining this idea, look forward to chatting more about it!

ccing @ebolyen

### CODE REVIEW

**Comment by thermokarst** [comment]
One [failing test](https://travis-ci.org/galaxyproject/galaxy/jobs/496678692#L2131-L2133) on travis (`ToolBoxTestCase::test_tool_reload_for_broken_tool`) --- I don't _think_ my changeset is causing this...

**Comment by nsoranzo** [comment]
> One [failing test](https://travis-ci.org/galaxyproject/galaxy/jobs/496678692#L2131-L2133) on travis (`ToolBoxTestCase::test_tool_reload_for_broken_tool`) --- I don't _think_ my changeset is causing this...

Not your fault at all, it's a long-standing locking issue which makes this test fail ~20% of the times.

**Review by bgruening — COMMENTED** [review]
Looks good to me. However, would a `has_archive_member` be better?

Thanks @thermokarst for working on this!

**Comment by thermokarst** [comment]
Thanks @bgruening! I was not dead-set on the naming, so `has_archive_member` works for me! Please see 8e82fc7 for the rename. Thanks!

**Comment by bgruening** [comment]
@thermokarst thanks!

Do you think we can also enhance the python function in a way that it does not matter if the to-be-checked file is zip, tar.gz, tar ...

**Comment by thermokarst** [comment]
Sure! I think that could happen now, or in future PRs - what is your preference?

**Comment by bgruening** [comment]
Obviously, I would like to see more awesome features in Galaxy as soon as possible, but I understand if this is not a priority for you. If we have the syntax correct and we can extend this I'm fine with it :)

In this case, could you make it more clear in the XSD that this is only for zip atm.

**Comment by blankenberg** [comment]
This is great :)

**Comment by thermokarst** [comment]
Thanks @blankenberg!

@bgruening --- I will take a stab at adding in tar and tar.gz right now. Stay tuned!

**Comment by thermokarst** [comment]
Hey there @bgruening --- I added in tar & tar.gz support in 091fe81. One question: do we have a better / canonical way for sniffing filetypes? I just set up a really simple `try/except` using python stdlib operations, but I am not in love with it and am certainly open to ideas. Thanks!

**Comment by mvdbeek** [comment]
@galaxybot test py3

**Comment by mvdbeek** [comment]
@galaxybot test this

**Review by mvdbeek — APPROVED** [review]
This looks very nice! I don't think there's a better way for tar/zip files at this point.

**Comment by martenson** [comment]
thanks @thermokarst !

**Comment by martenson** [comment]
the additions to the galaxy.xsd are failing our doc build: https://jenkins.galaxyproject.org/job/latest-Sphinx-Docs/lastFailedBuild/console

edit: should be fixed by https://github.com/galaxyproject/galaxy/pull/7462

**Pull request merged**
