### PR TITLE
Optimized workflow invocation step update.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think I fixed the problem in a simpler way, with the following patch my handler seems to work again:

``` diff
diff --git a/lib/galaxy/model/mapping.py b/lib/galaxy/model/mapping.py
index 1fec979..8054435 100644
--- a/lib/galaxy/model/mapping.py
+++ b/lib/galaxy/model/mapping.py
@@ -2301,8 +2301,7 @@ mapper( model.WorkflowInvocation, model.WorkflowInvocation.table, properties=dic
         uselist=True,
     ),
     steps=relation( model.WorkflowInvocationStep,
-        backref='workflow_invocation',
-        lazy=False ),
+        backref='workflow_invocation' ),
     workflow=relation( model.Workflow )
 ) )

```

I am now running tests to check this does not break anything else. Looks good to you @jmchilton?

**Comment by jmchilton** [comment]
@nsoranzo There are many times we want to not lazily grab that list - I guess it might be better to go in and figure out when those are and just be explicit in those. Let me think about it and let me know how the tests work out - I wouldn't expect them to fail - the downside would be like slower workflow scheduling iterations for instance. 

Update: Looking over there error - this looks fixable - it isn't a logic error or anything - just a type problem under Postgres. This would still be more optimized than just making those steps lazy load since it wouldn't require a database fetch at all.

**Comment by nsoranzo** [comment]
@jmchilton All tests passed for my patch. Opening a PR now.

Edit: I think the non-lazy loading will hit us in other places otherwise.

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Alternative solution in https://github.com/galaxyproject/galaxy/pull/2978 .

**Pull request merged**
