### PR TITLE
[16.04] Remove unused ui divs

### PR DESCRIPTION
**Pull request by guerler**
ping @carlfeberhard, Thanks for reporting it.

### CODE REVIEW

**Comment by carlfeberhard** [comment]
Heya, @guerler - thanks for taking a look

Actually I emailed to report duplicate mastheads and mastheads outside the `#everything` div. Looks like this happened during some cleanup last December.

This change still has the masthead outside `#everything` on the index page. You might try using `jQuery.replace` or `jQuery.replaceWith`?

**Comment by guerler** [comment]
Right, this PR only removes the empty dom with the same name. I will issue a separate PR to move the masthead back into #everything and maybe also frames, and modals for consistency.

**Comment by martenson** [comment]
@guerler do you want this to be merged or do you want to add the things you listed above to it?

**Comment by martenson** [comment]
ah, ok :)

**Comment by guerler** [comment]
Closed in favor of #2182

**Pull request closed without merging**
