### PR TITLE
python 3 porting

### PR DESCRIPTION
**Pull request by caleb-easterly**
Fixes 48 errors and 6 failures in unit tests.

xref. #1715

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
@galaxybot test this

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Thanks a lot @caleb-easterly! This PR alone fixed almost 20% of the failing unit tests!

**Comment by martenson** [comment]
@caleb-easterly !
4f61f53e-0c62-4882-9e0c-d10987fb8561

**Pull request merged**
