### PR TITLE
catch Exception and properly log errors

### PR DESCRIPTION
**Pull request by martenson**
in user.py

### CODE REVIEW

**Comment by dannon** [comment]
+1, good idea.  A (very) minor suggestion is that you could use log.exception and not have to pass 'e' along since it's pulled straight out of the context:  https://docs.python.org/2/library/logging.html#logging.Logger.exception

So,

`log.exception( 'Subscribing to the mailing list has failed.')`

**Comment by martenson** [comment]
@dannon I like the log.error more, thanks for the tip though!

**Comment by martenson** [comment]
merging, as it is already in 16.01

**Comment by martenson** [comment]
@galaxybot because if it had a milestone it would have create a duplicate in that milestone

**Pull request merged**
