### PR TITLE
Add tox startup (run.sh) test and test on OS X and linux

### PR DESCRIPTION
**Pull request by mvdbeek**
This fetches @jmchilton's sqlite template, runs common_startup.sh and run.sh, and checks that curl can contact galaxy. On the .travis.yml side, this test is run on linux and os x.

### CODE REVIEW

**Comment by martenson** [comment]
very nice @mvdbeek !

**Comment by jmchilton** [comment]
What a wonderful idea, this is awesome.

It is unrelated to this PR so feel free to ignore the request, but I will grant bonus points if you update the travis matrix to run the py27 unit tests under Mac OS X also.

**Comment by mvdbeek** [comment]
Yay! Bonus Points !! :moneybag: 
The startup test on osx is supposed to fail ( Issues #1633 / #1640).

**Comment by mvdbeek** [comment]
@natefoo is it to be expected that common_start.sh / run_tests.sh are still fetching `pip-8.0.2+gx1` ?
https://travis-ci.org/mvdbeek/galaxy/jobs/106509804#L2522

**Comment by natefoo** [comment]
Yes, until #1652 is merged and release_16.01 is merged back to dev. After that, if you rebase this PR it should fetch `8.0.2+gx2` and the startup test on OS X should pass.

**Comment by mvdbeek** [comment]
Alright, thanks!

**Comment by mvdbeek** [comment]
Seems to work now. Should I rebase anything? 
Also, I'm not sure anymore that testing run.sh is really necessary, given that #1640 would have been caught by py27-unit testing on os x.

**Comment by jmchilton** [comment]
@mvdbeek I still think exercising the recent migrations and a full start of the server is a good exercise. I like this the way it is.

**Comment by mvdbeek** [comment]
@jmchilton 
Seeing issue #1563 made me think that perhaps testing run.sh on a bunch of docker images for common distributions wouldn't be the worst idea either ... but it will slow down testing. 
Perhaps doing docker-based testing on [wercker](http://devcenter.wercker.com/docs/faq/migration-tips-v2.html) would be an option?

**Comment by mvdbeek** [comment]
@jmchilton 
From my side this would be ready for merging.
More testing is probably worthwile (I saw at least one OS X related failure with run_tests.sh -framework (awk having slightly different options ...), but that would be a new PR.

**Pull request merged**
