### PR TITLE
[24.1] xsd: allow `change_format` and `actions` also in statically defined collection elements, and break recursion

### PR DESCRIPTION
**Pull request by bernt-matthias**
also those contained in collections. Used for instance here:

https://github.com/galaxyproject/tools-iuc/blob/695ea582a8d3bf7845dd4cddbc8b591e4b6c4e82/tools/hybpiper/hybpiper.xml#L198 https://github.com/galaxyproject/tools-iuc/blob/695ea582a8d3bf7845dd4cddbc8b591e4b6c4e82/tools/krakentools/extract_kraken_reads.xml#L145

The recursive static definition of nested collections is not clear to me. Could not find any example. 

Could also target 24.1

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
If these work then we should add this as a bug fix to 24.1

**Comment by bernt-matthias** [comment]
In the commit message of https://github.com/galaxyproject/galaxy/pull/17236 you noted that `change_format` is not implemented: https://github.com/galaxyproject/tools-iuc/blob/695ea582a8d3bf7845dd4cddbc8b591e4b6c4e82/tools/krakentools/extract_kraken_reads.xml#L145

I'm not sure about this, the parser [uses the same function](https://github.com/galaxyproject/galaxy/blob/543ad8b5959a58fbb4a221c70529ee9954c026ad/lib/galaxy/tool_util/parser/xml.py#L482C17-L482C23) for `data` in `collection` elements as for top level `data` elements. 

I think the recursion in the xsd has been introduced also i this PR, or?

**Comment by bernt-matthias** [comment]
Should be about it. One question and two TODOs (but comments to all are welcome)

- [ ] I think `discover_datasets` in `collection` - `data` makes no sense. I will remove it.
- [ ] Would like to test if `filter` in  `collection` - `data` works. Would be fancy, but I can not think of a use case.
- [ ] Add a test for `action` in  `collection` - `data`

**Review by mvdbeek — APPROVED** [review]
That looks like a solid cleanup, thank you!

**Pull request merged**
