### PR TITLE
Add Selenium tests for the Saved Histories

### PR DESCRIPTION
**Pull request by anatskiy**
This PR includes the following tests:
- List of saved histories
- Standard search
- Advanced search (by name and tags)
- History popup menu (switch, view, publish, rename, delete, undelete, delete permanently)
- Multiple histories editing (delete, undelete)
- Sort by name
- Creating tags in the grid
- Clicking on tags in the grid

### CODE REVIEW

**Comment by jmchilton** [comment]
Awesome - thanks @anatskiy. I made some modifications in e2730ca - let me know if any of that is a problem.

I'm a bit nervous about the publishing test in here - I know it runs fine on its own - but would it break the other publishing tests you contributed previously if they were all run together the way Jenkins would do it? Perhaps it is worth reworking both tests to just check items and orders of items in the list - rather than assert the full content of the published list - this way they would work together just fine. What do you think?

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by anatskiy** [comment]
@jmchilton what if both tests will generate random history names and just check their presence in the grids? Will it solve the potential problem?

**Comment by jmchilton** [comment]
@anatskiy Yeah - I like that a lot.

**Comment by anatskiy** [comment]
@jmchilton I've just pushed the changes, please take a look.

Is there a way to wait until the grid is fully reloaded/refreshed? This would make the tests even more robust and remove extra `time.sleep()`

**Comment by jmchilton** [comment]
@anatskiy I can't think of a way to wait on that exactly - I feel like the approach of trying the assertion checking if there are problems should cover that. That is what those function decorators do. If I come up with something more direct I will let you know though.

**Comment by jmchilton** [comment]
Awesome thanks for the changes - this is great stuff!

**Comment by anatskiy** [comment]
@jmchilton thanks to you for the improvements! :)

**Pull request merged**
