### PR TITLE
[PROCEDURES] Remove Dave C. from committers list

### PR DESCRIPTION
**Pull request by mvdbeek**
Dave Clements has moved on to Anaconda to find a new challenge.

Thanks so much for the countless things you've done @tnabtaf, you know
the Galaxy community wouldn't be what it is without you!

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
Being a committer is based on judgement and not your position, Dave is still in the same field and has valuable years of experience and wisdom relevant to the kinds of divisive issues the committers might have to deal with. My +1 on this is entirely contingent on the fact that I assume he doesn't care to be on this list and if he wishes to be here at all I'm a strong and instant -1 on this.

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
> Being a committer is based on judgement and not your position, Dave is still in the same field and has valuable years of experience and wisdom relevant to the kinds of divisive issues the committers might have to deal with. My +1 on this is entirely contingent on the fact that I assume he doesn't care to be on this list and if he wishes to be here at all I'm a strong and instant -1 on this.

Given that Dave has removed himself from the committers Matrix channel, I assume that's his desire, but happy to be contradicted!

**Review by nsoranzo — APPROVED** [review]

**Review by jdavcs — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Review by dannon — APPROVED** [review]

**Review by tnabtaf — APPROVED** [review]
Hi All, 

Thanks for your consideration, but I should be removed from the committers group.  I will still be around (hoping to remain active in steering committee, and GCC2022 org), but I am unlikely to touch code again.

Thanks everyone,
Dave C

**Comment by davelopez** [comment]
Thank you so much Dave for being Dave! :smile: 
Although I've been here too little time and we haven't had the chance to meet that much, I've only heard wonderful words about you and your work. Thank you!

**Review by davelopez — APPROVED** [review]

**Review by martenson — APPROVED** [review]
Thanks for all the fish @tnabtaf.
tnabtaf

**Review by blankenberg — APPROVED** [review]

**Review by natefoo — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
