### PR TITLE
Remove makos for published list grids

### PR DESCRIPTION
**Pull request by guerler**
Removes makos for published visualization and workflow grids.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
I remerged to trigger tests. @galaxybot was not reacting.

**Comment by guerler** [comment]
Hey @jmchilton is this test occasionally failing by itself.

**Comment by jmchilton** [comment]
Yes - I've created an issue here https://github.com/galaxyproject/galaxy/issues/4218 just now.

**Pull request merged**
