### PR TITLE
History MultiView drag-drop on history picker creates new history

### LINKED ISSUE #16552: create new history on dataset drop in history side by side view
Galaxy

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Fixes https://github.com/galaxyproject/galaxy/issues/16552
Allow drop on `Select Histories` to create a new history with the dragged item.

https://github.com/galaxyproject/galaxy/assets/78516064/88b4e074-c71e-4f75-a93a-2a245d1e61f5

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by davelopez** [comment]
Nice!
What do you think about adding a confirmation before actually creating a new history with the dropped file on it? Something I just fat finger the left mouse button and drag or drop stuff unwillingly :sweat_smile:

**Comment by ahmedhamidawan** [comment]
> Nice!
> What do you think about adding a confirmation before actually creating a new history with the dropped file on it? Some times I just fat-finger the left mouse button and drag or drop stuff unwillingly :sweat_smile: 

Interestingly, i asked that same question in the UI/UX meeting last time (whether there should be a confirmation modal when the item is dropped). The consensus was that no, just creating a new history is fine.

Should we stick to that or actually have a confirmation?

**Comment by davelopez** [comment]
Hah! That's why I can't miss any meeting :rofl: 
If it was already discussed and decided it is fine, just wanted to make sure it was considered. Actually, now that I checked again, the drop target text changes to tell you exactly that, so it is completely fine, I missed that the first time :+1:

**Review by davelopez — APPROVED** [review]

**Review by dannon — APPROVED** [review]

**Comment by martenson** [comment]
Thanks a bunch @ahmedhamidawan !

**Pull request merged**
