### PR TITLE
Allow supplying name of pasted data

### PR DESCRIPTION
**Pull request by FredericBGA**
#4162
thank you @guerler for helping me to set this up.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Functionally this makes a lot of sense and seems to work for me. The styling is just a tad off relative to the rest of the form but that is completely subjective. @guerler do you want to touch up the styling before merging, if I don't hear from you I'll merge as is.

screen shot 2018-07-05 at 1 24 37 pm

**Review by jmchilton — APPROVED** [review]
Thanks a bunch!

**Comment by martenson** [comment]
This changes the default Galaxy dataset name of pasted content from `Pasted Entry` to `New File 1`. Together with the styling concerns I think we should polish this before merging.

**Comment by FredericBGA** [comment]
I let you see if the styling concerns are an issue.
From my point of view it's not really the case, it shows that this input can be modified. isn't' it ?

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
Thanks @FredericBGA for the naming fix. I agree that the styling is not a big deal.

**Review by martenson — APPROVED** [review]

**Pull request merged**
