### PR TITLE
Add avatar to published item components

### PR DESCRIPTION
**Pull request by guerler**
Requires #14687. Restores the avatar displayed and removes the item rating functionality from published pages.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jdavcs** [comment]
The package tests are failing due to the `md5` import in the model and managers modules. The md5 function is part of the web framework package, and it should not be imported into the data package (to maintain a clean dependency DAG for galaxy packages). (ping @jmchilton )

My suggestion would be to move the md5 function into the util package: it's a utility, and it is used as such in multiple places.

**Comment by jmchilton** [comment]
I would add ```md5_hash_str``` to galaxy.util.hash_util to match the ``md5_hash_file`` already there and then import that.

**Comment by mvdbeek** [comment]
The ratings seem .... not helpful? ... can we drop them ?

**Comment by guerler** [comment]
@mvdbeek removed it, and also thank you @jdavis and @jmchilton for helping with the conflicting import.

**Review by mvdbeek — APPROVED** [review]
Nice!

**Comment by guerler** [comment]
Thank you guys for all your help during this most recent mako removal transition!

**Pull request merged**
