### PR TITLE
[18.01] File sizes not being annotated in GRT

### PR DESCRIPTION
**Pull request by hexylena**
sorry @natefoo

### CODE REVIEW

**Comment by martenson** [comment]
@natefoo works as promised?

**Comment by hexylena** [comment]
Probably needs more testing, sorry, didn't get to it.

**Comment by hexylena** [comment]
@natefoo I'm looking over this and I'm not seeing anything *horribly* wrong. I think I fixed the one comment I saw in our chat log about `ValueError: No JSON object could be decoded`.

I'm worried I'm still screwing things up but who knows. At least we can always re-export data later :/

**Comment by martenson** [comment]
With this in place export.py still does not seem to export file sizes for me locally. I assume it is one of the `<core>` metrics that does not need special job_metrics_conf entry?

**Comment by hexylena** [comment]
> does not seem to export file sizes for me locally

ugh really?

> I assume it is one of the <core> metrics that does not need special job_metrics_conf entry?

no, it's on the of the dataset attributes, `model.Dataset.total_size`. :(

**Pull request merged**
