### PR TITLE
[16.04] Backport of 2613

### PR DESCRIPTION
**Pull request by martenson**
This PR backports https://github.com/galaxyproject/galaxy/pull/2613

I think we can make a case that this is a bugfix worth porting: We support tools that create reasonable outputs that are never shown in history in spite of being returned by API.

I had some trouble with backporting this as `var subtitleTemplate = BASE_MVC.wrapTemplate` did not exist in 16.04 so I also backported the introduction of it (first two commits here). I would really appreciate if you could have a look at this @carlfeberhard. Thank you.

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Thanks so very much for this @martenson and @carlfeberhard.  This fix is needed for the ChIP-exo flavor and I really appreciate both the fix and the back port to 16.04!  ;)

**Comment by jmchilton** [comment]
:+1:

**Comment by carlfeberhard** [comment]
Sure. +1

**Comment by dannon** [comment]
Merged locally to resolve conflicts and rebuild client.

**Pull request merged**
