### PR TITLE
Trivial: Replace unnecessary duplicated var check with 'else if'

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dannon** [comment]
@einon When editing files in client, you'll want to rebuild as well.  See more details here:  https://github.com/galaxyproject/galaxy/blob/dev/client/README.md

I can also just issue a PR against your branch doing this.

**Comment by nsoranzo** [comment]
You need to updated also the files `static/scripts/mvc/tools.js` and `static/maps/mvc/tools.js.map`.

**Comment by ghost** [comment]
no problem, will do.

**Comment by dannon** [comment]
(https://github.com/einon/galaxy/pull/1 is what it should look like after building)

**Pull request closed without merging**
