### PR TITLE
[16.01] mention planemo in the error message for disabled TS pushing

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by davebx** [comment]
I like it. Would suggest "to upload your changes" as more natural-sounding to me, but that's an aesthetic preference.

**Comment by nsoranzo** [comment]
+1 to @davebx's suggestion.

**Comment by martenson** [comment]
rephrased :) thanks @davebx

**Comment by martenson** [comment]
hiccup, dont merge

**Comment by martenson** [comment]
squash magic applied, ready to review

**Pull request merged**
