### PR TITLE
New testing image

### PR DESCRIPTION
**Pull request by mvdbeek**
Strips a couple of unneeded packages and add ffmpeg for #4949

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test py3

**Comment by mvdbeek** [comment]
@galaxybot test py3

**Comment by mvdbeek** [comment]
If this looks good I can push a new image to the Galaxy namespace and change the image name here before merging.

**Comment by martenson** [comment]
@mvdbeek looks good to me and that idea is also good.

**Comment by mvdbeek** [comment]
Alright, I pushed the image and updated run_tests.sh

**Comment by martenson** [comment]
thanks a bunch @mvdbeek !

**Pull request merged**
