### PR TITLE
[20.05] Don't close fds, dont pass subprocess cwd to mercurial calls

### PR DESCRIPTION
**Pull request by mvdbeek**
Should allow using posix_spawn, which may get us around
```
OSError: [Errno 12] Cannot allocate memory
  File "galaxy/tool_shed/util/hg_util.py", line 175, in update_repository
    subprocess.check_output(cmd, stderr=subprocess.STDOUT, cwd=repo_path)
  File "python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
Exception: Error updating repository: [Errno 12] Cannot allocate memory
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/srv/toolshed/main/venv/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/srv/toolshed/main/venv/lib/python3.8/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "/srv/toolshed/main/venv/lib/python3.8/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 145, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 224, in handle_request
    body = method(trans, **kwargs)
  File "tool_shed/webapp/controllers/repository.py", line 439, in browse_repository
    hg_util.update_repository(repo_path)
  File "galaxy/tool_shed/util/hg_util.py", line 180, in update_repository
    raise Exception(error_message)
```
This occasionally also happens when we still have 2 out of 8GB free.
I don't know if this actually helps, but worst case this should
execute slightly faster.

### CODE REVIEW

**Comment by nsoranzo** [comment]
I don't think this will work unfortunately, `posix_spawn` is used only if the executable path (`hg` in our case) contains a directory: https://docs.python.org/3/whatsnew/3.8.html#optimizations

I've verified in my `/usr/lib/python3.8/subprocess.py`:
```python
        def _execute_child(self, args, executable, preexec_fn, close_fds,
                           pass_fds, cwd, env,
                           startupinfo, creationflags, shell,
                           p2cread, p2cwrite,
                           c2pread, c2pwrite,
                           errread, errwrite,
                           restore_signals, start_new_session):
            """Execute program (POSIX version)"""

            ...

            if executable is None:
                executable = args[0]

            if (_USE_POSIX_SPAWN
                    and os.path.dirname(executable)
                    ...):
                self._posix_spawn(args, executable, env, restore_signals,
                                  p2cread, p2cwrite,
                                  c2pread, c2pwrite,
                                  errread, errwrite)

```

**Comment by mvdbeek** [comment]
Thanks @nsoranzo ... I had looked at the conditions myself and missed it still! What do you think about using `galaxy.util.which` to get the path to the executable ?

**Comment by nsoranzo** [comment]
Integration test failures seem relevant?

**Comment by mvdbeek** [comment]
Yeah. Spaces in the shebang of `hg` seem to break execution. We could check to see if there is a whitespace in the path of the mercurial executable as a proxy and then use `hg` instead of the full path, but that seems like a very brittle hack.
https://github.com/galaxyproject/usegalaxy-playbook/commit/f2427d69caf792bd8a6092cfc8893d7fb68cbb7d seems to work well so far, and I think I've already invested too much time here.

**Pull request closed without merging**
