### PR TITLE
Remove duplicate help target

### LINKED ISSUE #1979: makefile grooming
_list under construction_
- [x] every make command starts with 

```
Makefile:170: warning: overriding commands for target `help'
Makefile:19: warning: ignoring old commands for target `help'
```
- [x] `lint` target lints everything in the folder and seems to ignore setup.cfg? - I have hundreds of failures in test/ scripts/ lib/ (e.g. E128 which should be ignored)
- [ ] `make docs` will yield `no theme named 'sphinx_rtd_theme' found (missing theme.conf?)` unless you `pip install sphinx_rtd_theme` - do we want to stress this out?
  - [ ] maybe even add these to the requirements-dev.txt along with e.g. pygithub that is also needed?

### PR DESCRIPTION
**Pull request by hexylena**
And reformat for using existing help-text helper

xref #1979

cc @martenson @jmchilton

### CODE REVIEW

**Comment by jmchilton** [comment]
The other PR grew very stale but had been opened before your cool makefile changes that also added help. Thanks for the fix @erasche.

**Comment by hexylena** [comment]
@jmchilton ahh that explains the "conflicts: makefile" in your commit. All makes sense now! :)

**Comment by jmchilton** [comment]
Updated this PR to include a fix for `make docs` as well. (Hope this is okay @erasche.)

**Comment by hexylena** [comment]
@jmchilton absolutely :) wouldn't've given you push access to my branches if I didn't trust you to make good contributions like this.

**Comment by nsoranzo** [comment]
:+1: 

I would merge if you set status to review.

**Comment by hexylena** [comment]
@nsoranzo done

**Pull request merged**
