### PR TITLE
[PROCEDURES] Describe tags used to construct release notes.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
Promised rework of #663, see discussion on #868.

**Comment by jmchilton** [comment]
My preference at this point would be to document tags somewhere else in the codebase and just update the PROCEDURES to state that the merger of the pull request is responsible for ensuring the tags are in compliance with that document. This way we can have a sane, non-PROCEDURES discussion of tag policy.

**Comment by hexylena** [comment]
In the [discussion](https://github.com/galaxyproject/galaxy/pull/868#issuecomment-146564177) mentioned above, I'm in favour of this, and of documenting meanings/usages elsewhere and just merger must tag. 

I'd go further to say that maybe it would be sensible to _not_ limit ourselves to those three tags, and just say "the person merging the PR must ensure the PR has appropriate tags, please see X for our tag hierarchy/meanings/requirements", but I was not part of other discussions regarding tag taxonomy so perhaps those three really encompass the entirety of what we need to communicate with issue tagging.

**Comment by nsoranzo** [comment]
> My preference at this point would be to document tags somewhere else in the codebase and just update the PROCEDURES to state that the merger of the pull request is responsible for ensuring the tags are in compliance with that document.

@jmchilton I agree, than probably it's faster to close this PR and open a new one with this splitted in the new doc?

**Comment by dannon** [comment]
@jmchilton Like I mentioned on the other thread in question, we've had some working-group style discussion on this and I'll be opening a new issue once I've written up the proposal.  I'm not sure it's worth updating this right now (especially with the release notes already in-process for 15.10), and would favor just looking at and iterating on the proposal once I get it formalized and posted.

**Comment by jmchilton** [comment]
Closed in lieu #902 and anticipated follow up actions.

**Pull request closed without merging**
