### PR TITLE
make pgcleanup also delete HDAs

### PR DESCRIPTION
**Pull request by bernt-matthias**
follow up to https://github.com/galaxyproject/galaxy/pull/3572

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Not sure if the change in https://github.com/galaxyproject/galaxy/pull/3572 is actually as intended (as far as I got it). It seems that Galaxy still ends up with HDAs with deleted = False and purged = True. 

Also not sure if the old cleanup script is doing deleting purged histories.

**Review by natefoo — APPROVED** [review]
This makes it consistent with purging histories from the UI/API, although I still disagree with the premise.

**Comment by bernt-matthias** [comment]
> I still disagree with the premise.

My main concern is that pgcleanup does not delete data sets (at least @nsoranzo told me so :) I have only little clue) if one of their data sets is purged but not deleted. One could also change this. 

But I guess consistency is important.

**Comment by natefoo** [comment]
It currently [shouldn't care](https://github.com/galaxyproject/galaxy/blob/de36ef10d6d46481c1a741b2dd7b2a31fbae2db2/scripts/cleanup_datasets/pgcleanup.py#L916) about the HDA deleted flag when deciding to delete a dataset. Or am I misunderstanding the issue?

**Comment by bernt-matthias** [comment]
My original problem (and I'm not sure yet if this PR solves it.. ) is that pgcleanup does not **purge** many of my deleted data sets. The suggestion of @nsoranzo was that HDAs with deleted=f (and purged=t) could be the problem.

**Comment by nsoranzo** [comment]
> My original problem (and I'm not sure yet if this PR solves it.. ) is that pgcleanup does not **purge** many of my deleted data sets. The suggestion of @nsoranzo was that HDAs with deleted=f (and purged=t) could be the problem.

This surely is a problem for `scripts/cleanup_datasets/cleanup_datasets.py` : https://github.com/galaxyproject/galaxy/blob/dev/scripts/cleanup_datasets/cleanup_datasets.py#L360-L364

**Comment by bernt-matthias** [comment]
As @nsoranzo noticed another place where HDAs are purged but deleted is here: 

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/history.py#L344

he might come up with a fix soon. Maybe we can add this here?

**Comment by nsoranzo** [comment]
@bernt-matthias I think a separate PR for that would be better. Given @natefoo approved, I'm going to merge this.

**Comment by bernt-matthias** [comment]
@nsoranzo ok

Was just wondering how to trigger purging of data sets (using pgcleanup) which already have an HDA with deleted=false and purged=true. Should one trigger again: 

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/migrate/versions/0134_hda_set_deleted_if_purged.py

**Comment by nsoranzo** [comment]
I can re-add the migration as migration 0160 as part of my upcoming PR. In the mean time, you can obtain the same effect by executing this SQL statement: `UPDATE history_dataset_association SET deleted=TRUE WHERE purged AND NOT deleted;`

**Comment by bernt-matthias** [comment]
Thanks @nsoranzo . I tried this on my dev instance. Lets see if the pgcleanup cron job cleans everything tomorrow...

**Comment by nsoranzo** [comment]
@bernt-matthias Both the issue in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/history.py and the migration postponing are addressed in https://github.com/galaxyproject/galaxy/pull/8940 .

**Pull request merged**
