### PR TITLE
fix job_conf sample name

### PR DESCRIPTION
**Pull request by bernt-matthias**
consistent to other sample files

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
> it ending with .yml means editors pick it up as a YAML file without additional effort.

True. but then this should be done for the other yaml sample files as well. 

I just stumbled over this because I wanted to link to this file from the docs and expected the same naming scheme as we have for other samples. This of course resulted in a broken link and needed me a while to find the reason. 

So I thought a wee bit more consistence might not hurt :) 

> I think this was intentional 

Maybe also because the `TestAdvancedJobConfYamlParser` test didn't work back in the days (https://github.com/galaxyproject/galaxy/pull/7854) the possibility to use file handles for pykwalify was not yet given (https://github.com/Grokzen/pykwalify/commit/a1919fa614c637e31d0f9bd4d1bb2e6cb092957e)?

**Comment by natefoo** [comment]
Yes, as John mentioned, I'd prefer we do this the other direction (rename everything else to `foo.sample.ext`).

**Comment by bernt-matthias** [comment]
This gets a bit out of hand :) .. Admittedly suffixing with `.sample` is easier than infixing programmatically. How about prefixing all sample config files with `sample_`?

**Comment by natefoo** [comment]
> This gets a bit out of hand :) .. Admittedly suffixing with `.sample` is easier than infixing programmatically. 

Yes, true.

> How about prefixing all sample config files with `sample_`?

We could - I'd like a little more attention from other committers though rather than making this decision unilaterally though, it could be controversial. =)

**Comment by mvdbeek** [comment]
I would prefer not to change this at all. It has the potential to cause some grief for marginal benefits.

**Comment by bernt-matthias** [comment]
OK. I leave it as is. Fine with merging or closing this (but I still think that the gained consistency does not hurt).

**Pull request closed without merging**
