### PR TITLE
Swap the deprecated unescape() for decodeURIComponent

### PR DESCRIPTION
**Pull request by dannon**
More info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

### CODE REVIEW

**Comment by guerler** [comment]
Thanks for catching this @dannon. Definitely something we should fix. I was unaware that `unescape` deprecated. I remember to have tried `decodeURIComponent` but under certain circumstance it triggers an error if the parsed string is not a compatible. See here: https://jsfiddle.net/8jga87c7/.

**Review by nsoranzo — APPROVED** [review]

**Comment by dannon** [comment]
@guerler Let me check that out before this is merged; I can add some error handling too, but my guess is that the example there isn't a properly encoded string.

**Comment by dannon** [comment]
@guerler See the encoding difference in https://jsfiddle.net/8jga87c7/2/ ?  My guess, if the backbone router is encoding this stuff, is that it's doing it in a way compatible with decodeURIComponent.  Have you seen an error with actual tool ids?

**Comment by guerler** [comment]
Makes sense, have not seen it with actual id's. Thanks.

**Comment by dannon** [comment]
@guerler Ok, cool.  Let me know if we do, and I can definitely add extra error handling here.

**Comment by guerler** [comment]
Sounds good. Thanks again for catching and enhancing this.

**Pull request merged**
