### PR TITLE
[21.05] Ignore sigpipe in ``Show beginning1`` tool 

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes https://github.com/galaxyproject/galaxy/issues/12093

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Can you tell me what is causing the error?

**Comment by nsoranzo** [comment]
> Can you tell me what is causing the error?

https://matrix.to/#/!JLyNgmIlYnnCOwcFAQ:gitter.im/$UFcNlSxZ7MtuLy3lLhEcfpLl7nNGBFa5RZ0yTvBZc2Y?via=gitter.im&via=matrix.org

**Review by bernt-matthias — APPROVED** [review]

**Comment by bgruening** [comment]
Is that fixing it for you @natefoo?

It seems that it still crashes for us with `cat: write error: Broken pipe`.

**Comment by mvdbeek** [comment]
Do you have an example ? What's the exit code ?

**Comment by natefoo** [comment]
> Is that fixing it for you @natefoo?

Yes, we were having many tool failures per day prior to updating on June 11. Afterward there has only been 1 failure.

**Comment by wm75** [comment]
Command Line | set -eo pipefail; cat '/data/dnb03/galaxy_db/files/0/c/d/dataset_0cd4cc39-1788-4bbe-bf28-c31b3bcee4e7.dat' \| head -n 5 >> '/data/dnb03/galaxy_db/job_working_directory/026/936/26936483/outputs/galaxy_dataset_003441c9-5e3b-44ee-b1cb-574a5365c2b0.dat'
-- | --
Tool Standard Output | empty
Tool Standard Error | cat: write error: Broken pipe
Tool Exit Code: | 1
Job Messages | { "code_desc": "", "desc": "Fatal error: Exit code 1 ()", "error_level": 3, "exit_code": 1, "type": "exit_code" }

Sure enough that same tool "succeeds" with exit code 141 on test.galaxyproject.org (usegalaxy.org data uploads stuck at the time of writing) with the same input file.
So why would the exit code be 1 instead of 141 on usegalaxy.eu?

**Comment by wm75** [comment]
Different implementations of cat mabye? @bgruening which cat is used by the .eu tool?

**Comment by bgruening** [comment]
```
cat (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjörn Granlund and Richard M. Stallman.
```

From conda.

**Comment by bgruening** [comment]
```
(__coreutils@_uv_) root@sn06:~$ bash /tmp/foo.sh
ENST00000253255.7_cds_0_0_chr22_46256561_r      27
ENST00000648057.3_cds_0_0_chr22_50546244_f      26
ENST00000327423.11_cds_5_0_chr22_31712083_r     20
ENST00000302097.3_cds_0_0_chr22_22514002_r      14
ENST00000216268.6_cds_1_0_chr22_49883663_f      13
(__coreutils@_uv_) root@sn06:~$ echo $?
141
```

Any idea why we could get an error code of 1 with Galaxy?

**Comment by bgruening** [comment]
```
cd working; /bin/bash /data/dnb03/galaxy_db/job_working_directory/026/981/26981930/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/dnb03/galaxy_db/job_working_directory/026/981/26981930'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
export PATH=$PATH:'/usr/local/tools/_conda/envs/__bcftools@1.5/bin' ; python "metadata/set.py"; sh -c "exit $return_code"
echo $? > /data/dnb03/galaxy_db/job_working_directory/026/981/26981930/galaxy_26981930.ec
```
Normal isn't it?

**Comment by bgruening** [comment]
Awesome!

```
(__coreutils@_uv_) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ cd working; /bin/bash /data/dnb03/galaxy_db/job_working_directory/026/981/26981930/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/dnb03/galaxy_db/job_working_directory/026/981/26981930'; 
(__coreutils@_uv_) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ echo $return_code 
141
(__coreutils@_uv_) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ sh -c "exit $return_code"
(__coreutils@_uv_) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ echo $?
141
(__coreutils@_uv_) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ 
```

**Comment by wm75** [comment]
only relevant commit to cat since 8.25 is https://github.com/coreutils/coreutils/commit/492dcb2eb191b844a2fd5e51db3eed85289bea1f#diff-902166c03b0e16d4df7435bd552e3e329590bc7e9feb42977c929c6ecedd7e60
which at least smells like it could be the cause?

**Comment by bgruening** [comment]
```
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ cat --version
cat (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund and Richard M. Stallman.
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ cd working; /bin/bash /data/dnb03/galaxy_db/job_working_directory/026/981/26981930/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/dnb03/galaxy_db/job_working_directory/026/981/26981930'; 
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ sh -c "exit $return_code"
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ echo $?
141
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ echo $return_code 
141
(mulled-v1-70aa10870575258d38e51a3c201c4ad44a33e8463acb68afdf27e52a2f51fb58) galaxy@sn06:/data/dnb03/galaxy_db/job_working_directory/026/981/26981930$ 
```


All cat versions are returning 141 in my testing, for unknown reason Galaxy reports 1 :(

**Comment by mvdbeek** [comment]
Is the job running on Pulsar?

**Comment by bgruening** [comment]
No, but they are running in cgroups. Maybe that has an influence?

**Comment by wm75** [comment]
@mvdbeek @bernt-matthias @natefoo @bgruening we still haven't figured out why this tool returns with exit code 1 on usegalaxy.eu instead of 141, and we're still getting bug reports because of that.

Revisiting this, why do we even need `<param name="header" type="boolean" label="Dataset has a header" help="if checked the header is kept and is not counted as a kept line"/>` in this tool?
If the user knows there is a header line can't they just add 1 to the number of lines to keep themselves? If we really want to keep the param for ultimate user convenience and maybe for symmetry with the Show tail1 tool (were it serves a real purpose), then why not go with what @hexylena once suggested on matrix, i.e.:
```
if header
  head -n $((n+1)) file > out
else
  head -n $n file > out
fi
```

**Comment by mvdbeek** [comment]
The second option sounds good to me, once we have that functionality I don't think we should change it.

**Pull request merged**
