### PR TITLE
walltime_limit added for the k8s jobs

### PR DESCRIPTION
**Pull request by telukir**
* walltime_limit added for the k8s jobs
* default is also set to the k8s_walltime_limit in job specification
* Tested with minor tests

### CODE REVIEW

**Review by mvdbeek — CHANGES_REQUESTED** [review]
Thanks a lot @telukir, this is a nice feature.
Could you please target the dev branch ?
Let me know if you need any assistance in that.

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Review by jmchilton — APPROVED** [review]

**Comment by afgane** [comment]
Thanks @telukir for diving into this and @mvdbeek for solidifying it.

**Pull request merged**
