### PR TITLE
Add `command_inject` to Interactive Environments.

### PR DESCRIPTION
**Pull request by bgruening**
This makes it possible to modify the executed `docker run` command from the config file by specifying options like `-u UID`.

### CODE REVIEW

**Comment by hexylena** [comment]
LGTM.

**Comment by hexylena** [comment]
Fixes https://github.com/bgruening/galaxy-ipython/issues/24

**Comment by jmchilton** [comment]
Awesome, thanks for taking this on!

**Comment by hexylena** [comment]
@bgruening just debugged an issue with @carlfeberhard w/r/t this PR.

The issue was essentially that because `-u` wasn't set, the container couldn't read/write to `/import/` and crashed immediately. What would you think of something like:

``` python
ci = self.attr.viz_config.get("docker", "command_inject")
if " -u" not in ci:
  ci += " -u %s" % os.geteuid()
```

i.e. test for whether they've overridden the user, and if not, inject it?

**Pull request merged**
