### PR TITLE
Improve color relationships between text and background

### PR DESCRIPTION
**Pull request by guerler**
This PR follows-up on our style consolidation efforts. It consolidates the control on foreground colors (for regular-text, muted-text and borders) by deriving them consistently from `$brand-dark` and then contrasting them with background colors derived from `$brand-light`. The default color theme remains unchanged, except minor contrast improvements for `$text-muted` elements and the substitution of custom gray tones. 

Screen Shot 2019-07-30 at 3 56 30 PM

**For Example:** 
Previously background and text colors were mostly derived from one channel i.e. by darkening brand-light. This required brand-light to be an actual light color. @jxtx thanks for pointing this out. With this PR we separate text and background colors into two contrasting channels. Swapping brand-light and brand-dark, and replacing primary/secondary brand colors with orange now results in a legible theme (Example 1, below). A remaining challenge is that primary/secondary brand colors have to contrast brand-light and brand-dark. This might be something to be addressed in another follow-up if necessary.

1. Setting `$brand-dark=#f8f9fa`, `$brand-light=$2c3143` and `$brand-primary/secondary=orange` results in:
image

2. Setting `$brand-primary: red; $brand-secondary: green; $brand-light: black; $brand-dark: orange;` results in:

Screen Shot 2019-07-31 at 1 22 40 AM

3. Setting `$brand-dark:#003399` results in:

Screen Shot 2019-07-31 at 12 13 32 AM

4. Setting `$brand-dark:#003399` and increasing the darkness of `$text-color` by 20% results in:

Screen Shot 2019-07-31 at 12 23 24 AM

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by hexylena** [comment]
love this! It makes it so much easier. A few things for discussion maybe:

1. Should the select2 be styled as well?
   
    image

2. and the buttons here, I guess I should set brand secondary here, it can't easily be a derived colour or?

   image

3. I could see an argument for making the background white here? Since that will skew people's colour perception

   image

4. With `$brand-light: white; $brand-dark: red; $brand-secondary: green;`, the borders seem to disappear? looks like the following could be overridden

   ```
   .ui-select .select2-container .select2-choice { border: white } 
   ```

   image

5. Some job states are a bit unreadable, but this feels like a really hard problem to solve generically? If I set `-light` to really a light colour it looks OK, if it's a dark and `-dark` is a light colour, then it's an issue. Is there any chance to ensure a contrasting colour for the text, white if it is dark / black if it is light?

   image

**Review by martenson — APPROVED** [review]

**Comment by guerler** [comment]
@erasche thank you so much for the quick review and helpful comments.

**1.** I added the styling to select2 popups.

**4.** This can be fixed by changing the factor of the border-color brightening. In e236758f50617534d2c6acc6251537727030253c I moved this option directly below the brand colors in the theme file and named it `$border-color` for easier access.

**3.** If you are ok with it I would rather leave the background of the color picker as is for now. I want to avoid placing fixed colors into elements as much as possible.

**2. & 5.** are related and probably the main limitation of the theming right now. It requires that primary/secondary brand colors contrast brand light and brand dark. Resolving this limitation would make it much easier to pick viable themes. Both should be fixable in a follow-up. They require revisiting how bootstrap theme colors are derived from brand colors to ensure that colors with proper contrast are picked. The bootstrap theme colors are defined at the bottom of our theme file. I would rather leave this enhancement to a follow-up PR.

Thanks again.

**Review by hexylena — APPROVED** [review]
Sounds great!

**Comment by guerler** [comment]
Thank you for the review!

**Comment by hexylena** [comment]
Thanks for making it so much easier to theme things!

**Pull request merged**
