### PR TITLE
Fix broken browser tests

### PR DESCRIPTION
**Pull request by carlfeberhard**

### CODE REVIEW

**Comment by martenson** [comment]
:+1:

**Comment by dannon** [comment]
Reinstalling casper to actually test it, but I'd support targeting 15.05 with this since we want to get all tests passing prior to release (with the release).  Happy to cherrypick and merge it forward if you don't want to retarget.

**Comment by jmchilton** [comment]
:+1: on targetting 15.05 - it would be wonderful to get the tests passing pre-release.

**Comment by dannon** [comment]
I tried to figure out why this shouldn't be applied to 15.05 but didn't come up with an answer.  Merging and cherry-picking it.

**Comment by dannon** [comment]
+1

**Pull request merged**
