### PR TITLE
Replace get_tool_shed_repository_by_tool_shed_name_owner_changeset_re…

### PR DESCRIPTION
**Pull request by mvdbeek**
…vision with get_repository_for_dependency_relationship.
This also takes care of dependencies that have never been installed and should avoid https://github.com/galaxyproject/galaxy/issues/1865#issuecomment-192396467

### CODE REVIEW

**Comment by mvdbeek** [comment]
Ping @martenson

**Comment by martenson** [comment]
`./lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py:5:1: F401 'and_' imported but unused
`

**Comment by martenson** [comment]
we might actually want to port this to 16.01 I think

**Comment by davebx** [comment]
+1 to this, and +1 to putting it in 16.01

**Pull request merged**
