### PR TITLE
Add API route to show galaxy version

### PR DESCRIPTION
**Pull request by hexylena**
Tired of asking "what version of galaxy are you running" only to receive blank stares because there's no easy way for users/admins to find out without being familiar with deployment details

### CODE REVIEW

**Comment by dannon** [comment]
I think at some point when we talked about this we considered this endpoint should maybe be admin only, though now that I think about it I'm not sure it really needs to be.  Anyone else remember that discussion?

**Comment by jmchilton** [comment]
It exists `/api/version`, it is `@expose_api_anonymous_and_sessionless`ed.

Edit: Or do you want something more specific than the major version?

**Comment by hexylena** [comment]
Huh, how'd I miss that `-_-`. Thanks y'all

**Comment by dannon** [comment]
Ah-ha!  Knew we'd talked about it, forgot we'd actually _done_ it already :)

**Pull request closed without merging**
