### PR TITLE
Package locking for node modules.

### PR DESCRIPTION
**Pull request by dannon**
This may prevent some of the weirdness we have with seemingly random client rebuilds.

### CODE REVIEW

**Comment by martenson** [comment]
damn that's long

**Comment by dannon** [comment]
@martenson Took me forever to write it!   ;)

**Comment by martenson** [comment]
@dannon could you please explain a bit how this works and what happens when e.g. one of the included versions becomes unreachable?

**Comment by dannon** [comment]
https://docs.npmjs.com/files/package-lock.json should explain most of it, but the idea is that everything used to build the client is locked to consistent versions, regardless of who's building.

*edit: regarding upgrades, or when versions are unreachable, it's easy to overwrite the lock file with a new one with a lock_delete/rebuild.

**Comment by bgruening** [comment]
We saw this as well. Thanks @dannon let's see if this makes things better.

**Pull request merged**
