### PR TITLE
Fix an incorrect indentation.

### PR DESCRIPTION
**Pull request by VJalili**
ping @qiagu

### CODE REVIEW

**Comment by qiagu** [comment]
I spent one whole day to trace this issue. When the function quota_amount returns 0, you won't notice anything bad, but weird thing happens when it returns a non-zero value, messing total_disk_usage of user, and the quotameter as well. 😄

**Comment by qiagu** [comment]
wow, probably we misunderstood the code. The 'for…else'  clause has special meaning, which seems to fit here better.

**Comment by VJalili** [comment]
Right, but I think you mentioned this indentation solves the problem of the incorrect dataset size you have been facing. So, if it is not a solution for that problem, then I will close this PR.

**Comment by martenson** [comment]
Even if this PR at this state fixes an issue, it also creates another one.

**Comment by qiagu** [comment]
Sorry, I find another possible reason caus ing my problem later. please see https://github.com/galaxyproject/galaxy/issues/5948

**Pull request closed without merging**
