### PR TITLE
WIP: Unlinked input tool form

### LINKED ISSUE #6058: Enable linked control in regular tool form
xref: https://github.com/galaxyproject/tools-iuc/pull/1865#issuecomment-386442515

This is helpful if you have a collection whose elements you want to run against another collection, i.e
the simple case where you have 1 control and many treatments, as is common in chip-seq, but also operations where you want to run all-against-all.

This can be done through the API by setting the `linked` parameter to false, and in the workflow run form you can disable the linked mode if you have collection inputs. It would be great to enable this for the regular tool form as well.

### PR DESCRIPTION
**Pull request by mvdbeek**
This enables running all collection contents against all other
collection contents and allows things like galaxyproject/tools-iuc#1865 (comment)

Closes #6058 

screen shot 2018-05-04 at 12 47 03

### CODE REVIEW

**Comment by mvdbeek** [comment]
Putting this back to WIP because this happens when running an unlinked collection against another collection from the workflow run form:
```
galaxy.workflow.run ERROR 2018-05-04 13:40:59,577 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/workflow/run.py", line 80, in __invoke
    outputs = invoker.invoke()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/workflow/run.py", line 186, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/workflow/run.py", line 262, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/workflow/modules.py", line 850, in execute
    collection_info = self.trans.app.dataset_collections_service.match_collections(collections_to_match)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/collections.py", line 413, in match_collections
    return MatchingCollections.for_collections(collections_to_match, self.collection_type_descriptions)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/dataset_collections/matching.py", line 91, in for_collections
    matching_collections.__attempt_add_to_linked_match(input_key, hdca, collection_type_description, subcollection_type)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/dataset_collections/matching.py", line 57, in __attempt_add_to_linked_match
    raise exceptions.MessageException(CANNOT_MATCH_ERROR_MESSAGE)
```

This however seems to happen on dev as well ...

**Comment by mvdbeek** [comment]
Maybe that's some complexity we don't really want ? These options aren't available in the workflow editor anyway. I'll just reduce this to cd79b107f9d8c4c0856ac0a876c7578c1b3ae6a9

**Comment by jmchilton** [comment]
I'm not sure what Galaxy does in every case, but I'll throw out that I originally added linking and unlinking in the tool API to allow like Cartesian products over single input parameters - so if pass two unlinked collections to a tool that produces a single file - it would give a nested list back with all the identifiers from the first collection as the first level and for each of those all the identifiers from the second collection.

I'm not sure I had thought through multi-data parameters... but it would seem like unlinked parameters in that case don't make sense at least in the same way? If I had to pick semantics - I might say the first multi-data parameter reduces the first list and the second one gets mapped over the second list so you'd have flat list outputs?

I could be misunderstanding https://github.com/galaxyproject/tools-iuc/pull/1865#issuecomment-386442515 and I need to process this all more, but my intuition says this should not work this way. In terms of things being linked or unlinked - an dataset alone versus a single dataset in a list should behave differently.

**Comment by mvdbeek** [comment]
> I'm not sure what Galaxy does in every case, but I'll throw out that I originally added linking and unlinking in the tool API to allow like Cartesian products over single input parameters - so if pass two unlinked collections to a tool that produces a single file - it would give a nested list back with all the identifiers from the first collection as the first level and for each of those all the identifiers from the second collection.

that's more or less what's happening here:

screen shot 2018-05-04 at 14 09 46

So control was a list with 1 dataset and Treatment had 2 datasets (as in the PR description). This seemed to intuitively do the right thing, but since this doesn't work in workflows I'm inclined to think it may be too complex ?

**Comment by jmchilton** [comment]
It not working in workflows probably shouldn't stop us IMO? It might be one small bug away from working?

If the semantics are that one list is reduces an the other is mapped over, that is great - I think we should do that. But we'd need to give the user the ability to select which is which right - that is what I'd be concerned about.

Or is all this complexity wrong and we should just use collection operation tools to build interesting collections and keep the tool form semantics simple. I guess that is the path we've been going down and it seems to be working okay?

I don't have any answers this morning it seems, but I appreciate you working on this and pushing the platform @mvdbeek!

**Comment by mvdbeek** [comment]
> It not working in workflows probably shouldn't stop us IMO? It might be one small bug away from working?

This is a "step level" control, and we don't have control over these things in the workflow editor (and probably rightly so, since it alters the workflow structure substantially)

> Or is all this complexity wrong and we should just use collection operation tools to build interesting collections and keep the tool form semantics simple. I guess that is the path we've been going down and it seems to be working okay

I agree, that seems like the simpler approach from the user side.

**Pull request closed without merging**
