### PR TITLE
added GALAXY_MEMORY_MB_PER_SLOT variable

### PR DESCRIPTION
**Pull request by bernt-matthias**
When starting to use GALAXY_MEMORY_MB I realized that some tools want to know the total memory and some the memory per thread. I found it cumbersome if tool developers need to calculate that value in the tool script. 

So here is my suggestion. 

The two if statements may simplify the integration of statements for further cluster schedulers. Some seem to report total memory (apparently SLURM) and others per thread (UNIVA: https://github.com/galaxyproject/galaxy/pull/4857).

### CODE REVIEW

**Comment by jmchilton** [comment]
Ping @natefoo - any thoughts? Seems like an okay change to me.

**Comment by natefoo** [comment]
Yeah, seems reasonable. Just a minor request, can it be `$GALAXY_MEMORY_MB_PER_SLOT` instead?

**Comment by bernt-matthias** [comment]
renamed it.

**Comment by bernt-matthias** [comment]
Where could I add a bit of documentation for this?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/blob/0be36ef4fce3b50bec37d199af2a404f3372ed65/lib/galaxy/tools/xsd/galaxy.xsd#L2659 seems like a good place

**Comment by bernt-matthias** [comment]
Maybe also add some more details here:

https://planemo.readthedocs.io/en/latest/writing_advanced.html#cluster-usage
https://galaxyproject.org/admin/config/galaxy_slots/

?

**Comment by natefoo** [comment]
Both those places seem like good candidates. The Hub page should probably move to docs.galaxyproject.org though.

**Comment by bernt-matthias** [comment]
@natefoo Is the docs docs.galaxyproject.org content also on github?

**Comment by nsoranzo** [comment]
It's generated from files in `doc/source/` subdirectory of this repository.

**Comment by jmchilton** [comment]
Thanks again - this good stuff and updating documentation is such a great idea (I should try that for something I do someday - meh probably not).

**Pull request merged**
