### PR TITLE
Update to 2022 NAR paper

### PR DESCRIPTION
**Pull request by mschatz**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by jdavcs — APPROVED** [review]

**Comment by mvdbeek** [comment]
The paper doesn't seem to properly link out to authors, or at least I'm not seeing it. Can we revert this until it's fixed ?

**Comment by mschatz** [comment]
We opted for the primary by-line to read "The Galaxy Community" (https://academic.oup.com/nar/article/50/W1/W345/6572001?login=true) so that is why I trimmed the individual authors. If there is strong interest for calling out the individual authors, there is an alphabetically listing of ~100 authors in the appendix. What does everyone want to do?

**Comment by mvdbeek** [comment]
I would say NAR should register the authors ? Didn't they say that's how it works ? Or at least when you click on the authors it would show ?

**Comment by jdavcs** [comment]
They are listed as contributors: https://academic.oup.com/nar/article/50/W1/W345/6572001?login=false#367389438

**Comment by mvdbeek** [comment]
Screenshot 2022-12-06 at 20 52 24
that's what I mean, but the paper also doesn't appear in any of my other records (pubmed, orcid etc)

**Comment by mschatz** [comment]
I think it is a separate question as to what NAR does vs what we want on the Hub. I vote for "The Galaxy Community" to emphasize the role of the community but am interested to hear what everyone else thinks

**Comment by mvdbeek** [comment]
I disagree, we were told the community would be authors, but since that hasn't been registered correctly we should push to have this be fixed. Right now it's not even the community, it's just the PIs that are linked to the paper.

**Comment by mschatz** [comment]
I agree, we should contact NAR to ask to correct this

**Comment by jdavcs** [comment]
I suggest leaving this merged, as this is the formal citation record of the latest Galaxy paper as of now. And +1 on addressing this issue with NAR separately.

**Comment by mvdbeek** [comment]
Sounds good👌. I hadn't checked the crosslinks until now, so if we can get this fixed that'd be 🥇

**Comment by jdavcs** [comment]
@afgane :point_up: pinging you, just in case, as the corresponding author.

**Pull request merged**
