### PR TITLE
Memory and performance fixes for upload tool

### LINKED ISSUE #5622: Upload and sniffer performance problems and bugs
There are multiple issues (dating back quite a long time, it would appear) with uploads:

1. The sniffers are still run even when a datatype has been explicitly selected
2. Many sniffers for text types attempt to read files by line, and thus can easily run out of memory trying to read the first "line" of a binary file
3. Even if you don't run out of memory (the binary file is < the memory allocated for the job, or there is a newline byte somewhere before the amount of allocated memory), processing files through every sniffer when they can read GB of data each is extremely slow
4. Each sniffer opens and reads some amount of uploaded datasets repeatedly. We could read a fixed amount into memory once and give sniffers an `itertools.tee()`'d iterator (but this may not be a big performance problem if sniffers were guaranteed to only read a few KB to a few MB)

A few potential solutions:

1. Don't run sniffers when a datatype is explicitly selected.
2. Modify all sniffers (and ensure all future sniffers) only read files by chunks of fixed size, instead of by line (this should probably be done anyway due to #3796).
3. ~~Default to sniffers being "binary unaware" and only allow sniffers that assert themselves as "binary aware" to sniff binary files.~~ Only run sniffers of datatypes subclassed from the Binary datatype on binary files.
4. ???

### PR DESCRIPTION
**Pull request by natefoo**
Fixes for memory consumption in the upload tool and other general code/performance improvements. PRing for tests which I can't seem to get running correctly locally.

Should fix #5622

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton Rebased!

**Comment by natefoo** [comment]
The failing selenium test fails differently for me locally, but it also fails in this same way running from dev, so I don't know whether this is my fault or not:

```pytb
======================================================================
ERROR: test_list_creation (selenium_tests.test_library_to_collections.LibraryToCollectionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nate/work/galaxy3/test/selenium_tests/framework.py", line 203, in setUp
    self.setup_with_driver()
  File "/home/nate/work/galaxy3/test/selenium_tests/framework.py", line 382, in setup_with_driver
    self.setup_shared_state()
  File "/home/nate/work/galaxy3/test/selenium_tests/test_library_to_collections.py", line 39, in setup_shared_state
    self.libraries_open()
  File "/home/nate/work/galaxy3/test/galaxy_selenium/navigates_galaxy.py", line 610, in libraries_open
    self.home()
  File "/home/nate/work/galaxy3/test/galaxy_selenium/navigates_galaxy.py", line 151, in home
    self.wait_for_visible(self.navigation.masthead.selector)
  File "/home/nate/work/galaxy3/test/galaxy_selenium/has_driver.py", line 89, in wait_for_visible
    **kwds
  File "/home/nate/work/galaxy3/test/galaxy_selenium/has_driver.py", line 165, in _wait_on
    return wait.until(condition, message)
  File "/home/nate/work/galaxy3/.venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/home/nate/work/galaxy3/.venv/local/lib/python2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 127, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/home/nate/work/galaxy3/.venv/local/lib/python2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 402, in _find_element
    raise e
UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.0-0.bpo.3-amd64 x86_64)
```

**Comment by jmchilton** [comment]
The test is unrelated to this PR.

**Comment by natefoo** [comment]
Can we disable flaky tests until we get them sorted out?

**Comment by jmchilton** [comment]
@natefoo I've been trying to solve these issues for three days - https://github.com/galaxyproject/galaxy/pull/5714 might be successful finally. I'll let you know.

```
John Chilton @jmchilton Mar 15 09:18
What do we think about just ignoring the error code on the Selenium tests - so they always come back green. That way people reviewing client changes could still go in and look at the results manually but a random failure or two on non-client code changing PRs don't fail the whole PR. Other ideas I'm thinking about include stepping back to requesting a review from Jenkins in order for one to launch and partitioning the selenium suite into more, smaller jobs that run faster and could be re-run on errors more quickly.

Dave B. @davebx Mar 15 09:20
for those who are only on irc, the rest was "partitioning the selenium suite into more, smaller jobs that run faster and could be re-run on errors more quickly."

Dannon Baker @dannon Mar 15 09:20
Heh, just booted up my gitter tab to read the rest.

Dave B. @davebx Mar 15 09:21
silly 20th century 512-character limit

Dannon Baker @dannon Mar 15 09:21
It'd definitely be good to cut down on the noise, and load, but I worry that the sort of 'allowed failures' will just end in stuff staying broken.
That, or maybe worse, not noticing when things do break unrelated features (like the tool driven tours, or something, that you might not think to check)

Dave B. @davebx Mar 15 09:22
yeah, we had that issue when I joined the team, with buildbot constantly red and nobody willing to put in the hours/days/weeks to fix the tests

Dannon Baker @dannon Mar 15 09:22
^ exactly.

Dave B. @davebx Mar 15 09:22
(it ended up being a few days, if memory serves)

Dannon Baker @dannon Mar 15 09:23
Is it just completely random tests you're seeing failing, or can we keep marking stuff with the flaky-fail notation until we make it more robust, while allowing robust tests to continue to be useful?

John Chilton @jmchilton Mar 15 09:29
It is a complex mix of the two - it used to be that there were a few tests that would fail at 10% frequency and then random tests would fail at like 1% - but there is now this problem of the timeouts which I haven't gotten my head around yet but we cannot fix those with flakey annotations. The other complexity is the transient failures correspond to actual Galaxy bugs in some cases (galaxyproject/galaxy#5692 and https://github.com/galaxyproject/galaxy/issues/3782).

Dannon Baker @dannon Mar 15 09:34
Seems to me the decision hinges on whether or not we can sort out the timeouts problem.
If we can fix the timeouts, then we should continue to let things fail (and show the failures), at least somewhat predictably.

John Chilton @jmchilton Mar 15 09:38
Alright - thanks for the input @dannon. I'll see what I can do.

Dannon Baker @dannon Mar 15 09:39
Sure thing, let me know if I can help.
```

**Comment by natefoo** [comment]
Thanks for the context.

**Comment by natefoo** [comment]
@jmchilton if you feel strongly this is the wrong approach to dealing with line lengths I'm not going to be upset if you think we should scrap it (although there are a few improvements that we should keep). I think we ought to switch all the text sniffers to read chunks instead of lines, but this was sort of a "failsafe" approach in cases where new poorly behaved sniffers might sneak in even if we fix all the existing ones.

**Comment by jmchilton** [comment]
@natefoo I wasn't trying to say I was opposed to these changes - I just think we also need to fix all the sniffers - none of them should be allowed to use unbounded amounts of memory.

**Comment by natefoo** [comment]
Ok, I agree with that.

**Comment by natefoo** [comment]
Thanks!

**Pull request merged**
