### PR TITLE
Editor as visualization 

### PR DESCRIPTION
**Pull request by OlegZharkov**
Implementation of https://github.com/galaxyproject/galaxy/issues/9352
Current look:
image
Or if you hide tools and history:
image

Works as expected, you can edit your dataset and export its modified version to history (with special characters/tabs/spaces).
You're always welcome to propose changes (maybe background color, should I change it to canonical white?) 
Tags are not copied from original file. Does anyone know how to upload file already with tags? At least not an option in [upload.xml](https://github.com/galaxyproject/galaxy/blob/dev/tools/data_source/upload.xml)
Otherwise, feel free to try or just take a look at ```editor.mako```

### CODE REVIEW

**Comment by anuprulez** [comment]
Do you really have `413` files for this visualisation?

**Comment by dannon** [comment]
@anuprulez Looks like it's the build dependencies for the ace editor here; we should be able to repackage that like the other visualizations have been done recently, and rebase out the static files.  I can help follow up on that.  (not a big deal, though -- and this is very cool @OlegZharkov!)

**Comment by simonbray** [comment]
This looks awesome Oleg, thanks a lot!

I am more in favour of the white background, I think it fits better with the rest of the Galaxy colour scheme.

**Comment by OlegZharkov** [comment]
@anuprulez yeah, that was ace-editor. It took me a little while, but everything is squeezed in single ```script.js``` file with webpack. File structure should look way better now. 

@simonbray so I changed backgroud color to white 
image
Export button is semi-transparent, but it will be highlighted on hover

@dannon do you know if it's possible to preserve tag? Do we actually need this feature?

If someone wants to try it locally, you would need to run this now:
```
cd galaxy/config/plugins/visualizations/editor
npm install
npm run build
```

and then standart ```make client``` at galaxy root dir

Thanks a lot for testing!

**Comment by simonbray** [comment]
@OlegZharkov, thanks, looks better than the dark theme IMO. Is it possible to make the export button a bit more visible against the white background?

**Comment by OlegZharkov** [comment]
@simonbray sure, it's possible. But the idea was to make it semi-transparent, so it will not cover the text behind it. Example:
image

To avoid confusion, it's highlighted if you hover the mouse

image

**Comment by OlegZharkov** [comment]
@galaxybot test this

**Comment by OlegZharkov** [comment]
I guess, we are good to go here. A huge thanks to @dannon and @mvdbeek!
@simonbray I will create another PR to EU after it gets merged

**Review by dannon — APPROVED** [review]
@OlegZharkov Thanks for the work on this, it looks great, and it's working well for me!

**Comment by OlegZharkov** [comment]
@dannon 
Thanks a lot !!

**Comment by simonbray** [comment]
Thanks everyone!

**Comment by OlegZharkov** [comment]
@simonbray I guess, you can close https://github.com/galaxyproject/galaxy/issues/9352

**Pull request merged**
