### PR TITLE
[19.01] Fix analyze 75 datatype upload

### LINKED ISSUE #7412: Analyze 75 upload does not work in 19.01 version
Hi, 

I tried to upload Analayze 75 files to usegalaxy.org and I got the following error message: 

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 329, in <module>
    __main__()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 320, in __main__
    metadata.append(add_composite_file(dataset, registry, output_path, files_path))
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 243, in add_composite_file
    stage_file(name, composite_file_path, value.is_binary)
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 223, in stage_file
    sniff.convert_newlines(dp, tmp_dir=tmpdir, tmp_prefix=tmp_prefix)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 122, in convert_newlines
    for i, line in enumerate(io.open(fname, mode="U", encoding='utf-8')):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Planemo with 18.09 is working with Analyze 75 files but not Planemo with 19.01 version: 
https://github.com/galaxyproteomics/tools-galaxyp/pull/350

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes #7412

### CODE REVIEW

**Comment by nsoranzo** [comment]
Should we also add a test for the upload of this composite datatype?

**Comment by mvdbeek** [comment]
Yes, I'm testing this manually now, but I'd like to enhance the existing datatype testing to composite files, targeting -dev. I already started some additional work for ~~large bam files~~ bam files with large contigs and indexes.

**Comment by mvdbeek** [comment]
I've tested this against the galaxyp repo and it fixes the failing test (well, there are newline differences, but that's probably to be expected). Reverting the commit gives me the same error as in https://travis-ci.org/galaxyproteomics/tools-galaxyp/jobs/497867827

**Review by nsoranzo — APPROVED** [review]

**Review by bgruening — APPROVED** [review]
Oh cool, that was fast!

Danke!

**Comment by nsoranzo** [comment]
@mvdbeek Wrong target branch?

**Comment by mvdbeek** [comment]
Yep, switched the branch just now.

**Comment by martenson** [comment]
thanks @mvdbeek !

**Pull request merged**
