### PR TITLE
gsummary python3 fix

### PR DESCRIPTION
**Pull request by bernt-matthias**
the conda requirement implies python3 for this tool. 

affects also 17.09 

xref. #1715

### CODE REVIEW

**Comment by hexylena** [comment]
Locally we have the following change, in addition to removing the `b`

```
diff --git a/tools/stats/gsummary.xml b/tools/stats/gsummary.xml
index 86c7407..b35ec58 100644
--- a/tools/stats/gsummary.xml
+++ b/tools/stats/gsummary.xml
@@ -4,6 +4,7 @@
     <edam_topic>topic_2269</edam_topic>
   </edam_topics>
   <requirements>
+    <requirement type="package" version="2.7">python</requirement>
     <requirement type="package" version="2.7.8">rpy2</requirement>
   </requirements>
   <stdio>
```

**Comment by bernt-matthias** [comment]
@erasche I could add this or increase rpy2 to the latest version (which does not work with python2). Any preferences? I guess it does not matter for the basic statistics done here.

**Comment by nsoranzo** [comment]
@bernt-matthias `rpy2` is available in conda-forge for Python 2.7, 3.5 and 3.6, see https://anaconda.org/conda-forge/rpy2/files . I don't think any python requirement should be needed.

**Comment by bernt-matthias** [comment]
Sorry confused this with pip. Anyway, then I leave it as is and do not add the python requirement.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
