### PR TITLE
External Login Flow: Redirect users if account already exists

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
https://github.com/galaxyproject/galaxy/issues/14670
## Existing Flow:
**Previously**, if a user tried to log in to Galaxy using OIDC, with an account that has the same email as an existing Galaxy account, we would raise an exception (in `custoz_authnz`) and show this:
image

# Changes added in this PR:

## Same external email as local account:

In this PR, instead of just throwing an exception, we have redirected the user so that they can log in and then connect the existing account. Which leads the user to the **User Preferences** section, where they can connect via OIDC, like so:

https://user-images.githubusercontent.com/78516064/233507878-469d2452-dd7e-4b09-b90f-fac6565e5315.mov

## Linking external IDP, with same email as other local account:

Also, if a user tries to link an external IDP, with the same email address as another, existing Galaxy local account, we let the user know that the link has been made but there does exist an account with the same email as their linked IDP:

https://user-images.githubusercontent.com/78516064/233508138-a4b8fbc5-ca4c-41dd-9947-cc3d25dfb80c.mov

## Boolean flag that allows a `NewUserConfirmation` page for a given provider:

Added a boolean flag **`<require_create_confirmation>`** in `oidc_backends_config.xml` that makes the `NewUserConfirmation` page optional:
```
<provider name="Custos">
  <url>https://dev.custos.usecustos.org/apiserver/identity-management/v1.0.0/</url>
  <client_id> ... </client_id>
  <client_secret> ... </client_secret>
  <redirect_uri>http://localhost:8080/authnz/custos/callback</redirect_uri>
  <require_create_confirmation>true</require_create_confirmation>
  <...>
</provider>
```

As seen implemented above and working below, it is set default to true for Custos, optional for Keycloak (can be added for any other provider if needed):

https://user-images.githubusercontent.com/78516064/236653006-a372c1ae-d43d-4e1c-b92e-db240450e890.mov

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by madeline3000** [comment]
Hey @ahmedhamidawan is there a way I can review the front end UI/UX flow of this updated version?

**Comment by ahmedhamidawan** [comment]
> Hey @ahmedhamidawan is there a way I can review the front end UI/UX flow of this updated version?

Hello @madeline3000! Yes, you could pull this branch locally and then see how the implementation works out.
I could rebase with dev if needed?

**Comment by neoformit** [comment]
Hey @ahmed - I've just been through a review with Maddie, she's gonna get some feedback to us soon.

We had some thoughts on the login order.

It would be great if this option is generic, rather than specific to custos:

```yml
# galaxy.yml
  prefer_custos_login: true  # should probably be prefer_oidc_login?
```

Perhaps an `order` tag in OIDC providers makes sense for when multiple providers are configured? This would specify vertical ordering of login options in the login/register UI.

```xml
<!-- oidc_backends_config.xml -->
    <provider name="keycloak" preferred="true">  <!-- what does preferred do? -->
        <order>1</order>  <!-- Should we add something like this? -->
        <url>https://my.idp.com/</url>
        <client_id>123-456-abcd</client_id>
        <client_secret>xyz-secret</client_secret>
        <redirect_uri>http://localhost:8080/authnz/keycloak/callback</redirect_uri>
        <well_known_oidc_config_uri>https://my-odp/.well-known/openid-configuration</well_known_oidc_config_uri>
        <icon>https://my-icon/icon.png</icon>
    </provider>
```

Happy to work on this (and Maddie's UI feedback) when we reach an agreement on the design.

**Comment by Ahmed** [comment]
Wrong Ahmed?

**Comment by neoformit** [comment]
My bad! :joy:

**Comment by ahmedhamidawan** [comment]
> It would be great if this option is generic, rather than specific to custos?
> 
> ```yaml
> # galaxy.yml
>   prefer_custos_login: true  # should probably be prefer_oidc_login?
> ```

The way I had set it up, prefer_custos_login changes the ordering of the `RegisterForm` so that the `ExternalLogin` shows up first. The naming should have been better though and it should've been `prefer_oidc_login`

> Perhaps an `order` tag in OIDC providers makes sense for when multiple providers are configured? This would specify vertical ordering of login options in the login/register UI.
> 

This is a great idea, we can modify the implementation so at the front end, the order tag is used to position the various idps. 

Would love to discuss future directions in detail. Thank you!

**Comment by madeline3000** [comment]
Hey @Ahmed & @neoformit 

I have reviewed the current implementation and have some UI/UX proposed changes documented here: 

https://docs.google.com/document/d/1ZIAg8-Ziaw_qwQP9z2wfZaJV0yyKwirFTQHt95ey2p4/edit#

Are we able to arrange a meeting to discuss this in the next week?

**Comment by Ahmed** [comment]
Is that the same Ahmed as the previous one? 🤔

**Comment by madeline3000** [comment]
Hey @ahmedhamidawan are you available to meet now?

**Comment by ahmedhamidawan** [comment]
> @dannon 

Done! And added a screencast above

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
@ahmedhamidawan I updated the config sample, can you double check that the default handling is correct in the code that loads it?

**Comment by ahmedhamidawan** [comment]
> @ahmedhamidawan I updated the config sample, can you double check that the default handling is correct in the code that loads it?

Done, and manually tested! You can see in the latest commit that now we force the confirmation page for custos (if the config flag isn't set)

**Pull request merged**
