### PR TITLE
[18.01] Fix library to list of pairs collection builder.

### PR DESCRIPTION
**Pull request by jmchilton**
Thanks to @nsoranzo for reporting!

### CODE REVIEW

**Comment by martenson** [comment]
Works well for me locally. 👍

**Comment by nsoranzo** [comment]
I've applied the patch, restarted the server, rebuilt the client with `make client-production`, but I still can reproduce the issue. Am I missing something?

**Comment by mvdbeek** [comment]
@nsoranzo try reloading with the javascript console open and having "disable cache" disabled in the network tab (that's for chrome). Sometimes it takes many reloads to take effect for me without this procedure

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
I should have rebuilt the client and then restart the server, works now, sorry for the noise!

**Pull request merged**
