### PR TITLE
Allow uploading to collections.

### PR DESCRIPTION
**Pull request by jmchilton**
This builds on collection builder enhancements from open PR #3806.

This adds a new upload tab for "Collections".
  - This has a new option to select "Collection Type" in footer.
  - Collection upload geared toward homogeneous datasets - must specify genome and file format for all files.
  - Add a new button "Build" after all individual datasets have finished their upload to the server.
  - Clicking "Build" launches the appropriate collection builder for selected collection type.
  - The original datasets of the uploads will be hidden by default after the collection is built (though this can be disabled by unchecking an option in the collection builder form).

This includes Selenium web tests for all three collection types as well as for hiding/not hiding the original datasets and the file extension selector.

image
image
image
image
image

### CODE REVIEW

**Comment by martenson** [comment]
Just a note: to test this you need to rebuild client as this PR does not include the built scripts and css. (might be an oversight @jmchilton ?)

**Comment by jmchilton** [comment]
@martenson It is intentional - rebuilding the client makes rebasing difficult - but you are correct I should have pointed this out.

**Review by martenson — APPROVED** [review]
It is fully functional and fairly intuitive. 

The UX would benefit from the de-atomization of the upload requests (thus allowing the `build` button to be available almost instantly) discussed in https://github.com/galaxyproject/galaxy/issues/1090

**Comment by martenson** [comment]
thanks @jmchilton - big step forward in improving collection user experience

**Comment by jmchilton** [comment]
Yay - thanks for the detailed review and merge @martenson!

**Pull request merged**
