### PR TITLE
Revise tool parameter handling, remove redundancies

### PR DESCRIPTION
**Pull request by guerler**
This is a continuation of #1572 and #115 and our ongoing effort to unify the tool parameter handling, remove hacks, legacy handling and redundancies.
- Remove former populate_state and update_state: https://github.com/galaxyproject/galaxy/pull/1711/files#diff-1bef786a2b2ea704c1748e41cd25dd33L1210
- Remove redundant check_param_from_incoming, and unnecessary get_incoming_value:
  https://github.com/galaxyproject/galaxy/pull/1711/files#diff-1bef786a2b2ea704c1748e41cd25dd33L2781
- Unify and extend visit_input_states:
  https://github.com/galaxyproject/galaxy/pull/1711/files#diff-c2872901d34ca0c09ded74872356dd7bL14
- Remove source specification layer and unify check_param:
  https://github.com/galaxyproject/galaxy/pull/1711/files#diff-c2872901d34ca0c09ded74872356dd7bR60 
- Replace DummyDataset with regular RuntimeValues:
  https://github.com/galaxyproject/galaxy/pull/1711/files#diff-9baf995401cfeb779edf8731ebaf0d2dL1649
- Simplify update state handling for workflow steps:
  https://github.com/galaxyproject/galaxy/pull/1711/files#diff-5cab48d5f01fec3fa30d17f4bf5d1848L1048
- Remove unused legacy collection handling:
  https://github.com/guerler/galaxy/commit/050adad1ea20f80472fa7f41a301b2d9d4d38d3d

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Looks like there are some legitimate failures in the test cases, if the problem just becomes test cases using deprecated features though let me know I can update the tests.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by carlfeberhard** [comment]
Looks good to me: +1

**Comment by guerler** [comment]
No worries and thanks a lot for the comments.

**Comment by guerler** [comment]
I tested composite file uploads within a docker image and i did not notice anything odd.

**Comment by jmchilton** [comment]
Thanks this is a substantial cleanup and simplification of various complex things - this should set the stage for awesome things down the road.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by martenson** [comment]
@guerler it is merged, bot will ignore it I think

**Pull request merged**
