### PR TITLE
Fix for GenomeSpace importer/exporter

### PR DESCRIPTION
**Pull request by nuwang**
Closes: https://github.com/galaxyproject/galaxy/issues/5527

This needs to be patched into the 18.01 branch, as it's currently broken on Galaxy main.

### CODE REVIEW

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@nuwang this is targeting the wrong branch if the title is correct

edit: the source branch is not clean 18.01 so we will need to backport this after merge, I will update the title to reflect that

**Comment by nuwang** [comment]
@martenson It's currently broken on both Galaxy main (18.01) and the dev branch.

**Comment by martenson** [comment]
@nuwang Understood, I will make sure it is fixed in 18.01. Thank you!

**Comment by martenson** [comment]
backported here: https://github.com/galaxyproject/galaxy/commit/8c941ae35a37f8dd087222c6827c122ddfdcc966

**Comment by nuwang** [comment]
@martenson Great, thanks for patching it in!

**Comment by martenson** [comment]
@nuwang should get to Main later today

**Comment by nuwang** [comment]
@martenson I forgot to ask - this needs a client rebuild - does that happen automatically now?

**Comment by martenson** [comment]
@nuwang yep, you need not to worry about that anymore

**Comment by martenson** [comment]
@nuwang deployed

**Comment by nuwang** [comment]
@martenson Works now, thanks!

**Comment by martenson** [comment]
thank you for fixing it

**Pull request merged**
