### PR TITLE
[18.01] Fix 'share with another user'

### LINKED ISSUE #6356: After sharing a history with one user, you cannot share with additional users
Steps to reproduce:

- Create a history
- Share history
 - Share with a user
 - Provide an email
 - Submit
 - Share with a user. *Button does not function.*

Short term workaround:

- unshare with your previous users
- re-share with all of them in a new comma separated list.

Affects:

- usegalaxy.eu
- usegalaxy.org

### PR DESCRIPTION
**Pull request by dannon**
Looks like this was broken in 225ad7fb45b.

Fixes #6356

### CODE REVIEW

**Comment by nsoranzo** [comment]
> Looks like this was broken in 225ad7f.

@dannon Can you target 18.01 then?

**Comment by dannon** [comment]
@nsoranzo Sure, I guess.

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
Thanks @dannon

**Review by hexylena — APPROVED** [review]

**Comment by jmchilton** [comment]
Sorry about that, thanks for the fix!

**Pull request merged**
