### PR TITLE
[18.01] Showed up in sentry as referencing fname before assignment

### PR DESCRIPTION
**Pull request by hexylena**
Appeared in 18.01, affects 18.{01,05,09} Targetting dev but this ports pretty cleanly, should I target another branch?

### CODE REVIEW

**Comment by dannon** [comment]
Might as well target 18.01, I guess -- should be a trivial merge forward (which I'm happy to do) if you want to swap it.

**Comment by hexylena** [comment]
Done

**Comment by nsoranzo** [comment]
Closed/reopened to properly restart tests.

**Review by nsoranzo — APPROVED** [review]

**Comment by dannon** [comment]
Merged forward

**Pull request merged**
