### PR TITLE
Allow disabling default history filters

### LINKED ISSUE #13866: Beta History: filter applied on summary counts doesn't take into account multiple dataset states
Reported by @guerler

> While testing I noticed that the history can become corrupted after a bulk operation. For this I executed a large bulk op and then clicked on the filter selection, while the processing was ongoing:

https://user-images.githubusercontent.com/2105447/166716715-e3c7e674-6756-4b7c-83c5-3a682722ce3e.mov

### PR DESCRIPTION
**Pull request by guerler**
Resolves: #13866. This PR fixes the filtering search field by refining how default parameters are used. Previously default filters were always consequently merged with custom filters. Now there is differentiation. The set of default parameters is only taken into account if none of them were explicitly specified. Here are some examples: `extension=pdb` will silently be treated as `extension=pdb visible=true deleted=false`, but entering `extension=pdb deleted=true/false` or `extension=pdb visible=true/false` into the search field, will not add the other default parameter to the query. Here is a diagram illustrating this logic.

```mermaid
flowchart LR
  A(FilterText) -->B{Is Empty?}
  B -->|Yes| C(Return Defaults)
  B -->|No| D{Contains Defaults?}
  D-->|Yes| E(Return FilterText)
  D-->|No| F(Return FilterText & Defaults)
  style C fill:lightblue,color:black
  style E fill:lightblue,color:black
  style F fill:lightblue,color:black
```
Thanks @dannon for suggesting the [mermaid](https://mermaid-js.github.io/mermaid/#/) markup.

Additionally this PR expands the handling of default filters in the advanced panel allowing three options i.e. true, false and not being set at all.

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by ahmedhamidawan — APPROVED** [review]
Looks good! Shouldn't cause the conflicting deleted/hidden view issues now, though not sure if my recently merged changes would have caused any conflicts here. I can see that the `HistoryFilters.test.js` failed but that's only because I changed it from checking if the emitted `filterText` `contained` a `filterValue` to instead checking/comparing the literal string value for `filterText`. That can be fixed by changing the order of the parameter from:
`Expected: "create_time>'January 1, 2022' create_time<'January 1, 2023' extension=ext-filter hid>hid-greater hid<hid-lower name=name-filter state=state-filter tag='tag filter'"`
to
`Received: "name=name-filter extension=ext-filter tag='tag filter' state=state-filter hid>hid-greater hid<hid-lower create_time>'January 1, 2022' create_time<'January 1, 2023'"`
This change is to be made here:
https://github.com/galaxyproject/galaxy/blob/f704edc40e065da6c287caa7f2dbfb7d35af3108/client/src/components/History/CurrentHistory/HistoryFilters.test.js#L77-L81
**Becomes:**
```
await expectCorrectEmits(
    wrapper,
    false,
    "name=name-filter extension=ext-filter tag='tag filter' state=state-filter hid>hid-greater hid<hid-lower create_time>'January 1, 2022' create_time<'January 1, 2023'"
);
```

**Review by dannon — APPROVED** [review]

**Review by hujambo-dunia — APPROVED** [review]

**Comment by mvdbeek** [comment]
Does that mean we can't show everything now (which I'd assume is what an empty filter box should be) ?

**Comment by dannon** [comment]
That should be 'any' for both deleted and hidden.  An empty filter box would just be the defaults (no hidden or deleted)

**Comment by guerler** [comment]
@dannon since `any` is unequal to `true` it will treat it as false, so the filter translates to: `deleted=false visible=false`. This being said @mvdbeek is correct, and the suggestion to allow explicitly allow `any` makes sense.

**Comment by dannon** [comment]
@guerler Yeah, I'd figure 'any' to be `true or false`.

**Pull request merged**
