### PR TITLE
Explore remote tool test data

### PR DESCRIPTION
**Pull request by davelopez**
xref: https://github.com/galaxyproject/galaxy/issues/7900 https://github.com/galaxyproject/galaxy/issues/3714 https://github.com/galaxyproject/galaxy/pull/13495

First attempt at allowing URLs as input data in tool tests.

This is probably not the ideal solution and there might be something already implemented that goes in the right direction but I couldn't find it. Opening the PR for discussion and getting feedback.

The idea is to be able to specify a remote URL to retrieve the input data for tool testing. Although we should always try to keep the test data as tiny as possible and always available to the tool, there are some situations where this is not possible. This tries to alleviate those situations.

## How it works
Just use the `location` attribute in a test `param` in the following way:

- without `value`: It will directly upload the input file from the `location` as a pasted URL to Galaxy
  ```xml
  <test>
      <param name="input" location="https://raw.githubusercontent.com/galaxyproject/planemo/7be1bf5b3971a43eaa73f483125bfb8cabf1c440/tests/data/hello.txt"/>
      <output name="output">
          <assert_contents>
              <has_line line="Hello World!"/>
          </assert_contents>
      </output>
  </test>
  ```
- with `value` defined but the file is not present on disk: It will behave exactly as the previous case
  ```xml
  <test>
      <param name="input" value="does_not_exists.txt" location="https://raw.githubusercontent.com/galaxyproject/planemo/7be1bf5b3971a43eaa73f483125bfb8cabf1c440/tests/data/hello.txt"/>
      <output name="output">
          <assert_contents>
              <has_line line="Hello World!"/>
          </assert_contents>
      </output>
  </test>
  ```
- with `value` defined and the file is present: It will just ignore the location and use the input file as always
  ```xml
  <test>
      <param name="input" value="simple_line.txt" location="https://raw.githubusercontent.com/galaxyproject/planemo/7be1bf5b3971a43eaa73f483125bfb8cabf1c440/tests/data/hello.txt"/>
      <output name="output">
          <assert_contents>
              <has_line line="This is a line of text."/>
          </assert_contents>
      </output>
  </test>
  ```

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] Instructions for manual testing are as follows:
  - Run `./run_tests.sh -framework -id remote_test_data_location`

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Marvelous. Wondering about a potential use case of combining `value` and `location`. 

More xref https://github.com/galaxyproject/planemo/issues/1268 https://github.com/galaxyproject/tools-iuc/pull/2908

**Comment by davelopez** [comment]
Thanks for the references @bernt-matthias!

> Wondering about a potential use case of combining value and location.

So, with these changes right now, using both `value` and `location` will prioritize using the `value` if it can be found in the `test-data` folder otherwise it will use the `location` as a fallback to paste it directly into the Galaxy upload. So the actual file is directly uploaded to Galaxy and is not downloaded "locally" and then uploaded to Galaxy. This has its advantages and disadvantages... of course.

Another possibility, on the Planemo side and possibly more in line with the references you provided, is to pre-populate the `test-data` folder of each tool before actually running the test. This will again check if the `value` file is already there and if not, download it to that particular *file name* using the `location` as a source so it is available at the time of testing as a regular test-data file. Is this what you are referring to? If so, I can try to explore this option in Planemo too.

**Comment by bernt-matthias** [comment]
Thanks for the explanations.  Still not entirely convinced that allowing to mix `value` and `location` is a good idea.

> Another possibility, on the Planemo side ...

I think this should be implemented independent of planemo. ..

**Comment by bernt-matthias** [comment]
Have you thought about optional checksums to check the downloaded data, or would this require that Galaxy's upload tool would need to support checksums?

**Comment by davelopez** [comment]
> Have you thought about optional checksums to check the downloaded data, or would this require that Galaxy's upload tool would need to support checksums?

Unfortunately, AFAIK, indeed, this would require the upload tool to support checksums.

This would be one of the disadvantages of this approach (along with the possible network unavailability), but on the other hand, you don't have to maintain a copy of the test data locally just to be uploaded to Galaxy when you run the test.

**Pull request closed without merging**
