### PR TITLE
[16.04] Fixes the proxy naming

### PR DESCRIPTION
**Pull request by bgruening**
Thanks for spotting @pvanheus!

### CODE REVIEW

**Comment by thobalose** [comment]
Hi @bgruening,

Also have a look at https://git.io/vrJXi.

**Comment by hexylena** [comment]
Oh crap that was 16.04. cc @jmchilton for another +1

**Comment by jmchilton** [comment]
16.04 still hasn't been released so this is fine - :+1: anyway though.

**Comment by hexylena** [comment]
Thanks :)

**Comment by bgruening** [comment]
Thanks @erasche and @jmchilton! That was quick!

**Pull request merged**
