### PR TITLE
IE Updates

### PR DESCRIPTION
**Pull request by hexylena**
- These updates switch IEs over to using the environment to configure them, rather than a yaml file.
- Updates to the proxy to provide for our <s>special snowflake</s> RStudio IE.

To resolve before merging:
- [x] @bgruening, with this we'll need to push a new branch/tag for the next release of IPython, and then pin Galaxy to it here. What release number should that be/what branch? :)

Labelled WIP due to above, single commit that has to happen before OK to merge.

CC @bgruening @jmchilton

### CODE REVIEW

**Comment by bgruening** [comment]
Obviously +1 from me :)
We need the `get_conf_file()` function also for  other IE's.

@erasche if we now label every release and make Galaxy releases tracking them, we could track master (aka :latest) and not use `:dev` in IPython, otherwise `Galaxy:dev` should track `IPython:dev`. In the latter case master is not really used, we could sync master with the _latest-stable_ branch.

[Edit: s/write_/get_/]

**Comment by hexylena** [comment]
`write_conf_file()` you renamed to `get_conf_dict()`...is there any way you could modify your other IEs to use the environment instead? Or maybe add something into your startup scripts for them that would write out a yaml file? Sorry...just want to avoid bringing that back since I like the environment so much more than special yaml files.

@bgruening hmm, ok. So I should set the image to `bgruening/galaxy-ipython-notebook:dev` then? I'll do the same for RStudio.

**Comment by bgruening** [comment]
@erasche everything fine, was a `s/write_/get_/` typo.
`bgruening/galaxy-ipython-notebook:dev` sounds good.
I need also to change the `next-stable` branch of Galaxy to `bgruening/galaxy-ipython-notebook:15.05`

**Comment by hexylena** [comment]
This should be ready to go as-is, @jmchilton

**Comment by jmchilton** [comment]
Have you tried this with the latest IPython dev image - I'm having trouble getting this to work but I don't know if it is user error, this change, an IPython change, or Docker issues inside the VM?

**Comment by hexylena** [comment]
@jmchilton will play with it shortly...

**Comment by hexylena** [comment]
@jmchilton okay, I can confirm that the ipython:dev (1d542ae65161) is working fine for me. This is on a test branch with `ie-updates2` and `rstudio` merged in. You have any debugging information regarding it?

**Comment by hexylena** [comment]
Notes to self/@bgruening: this is the latest change to IE framework. https://github.com/jmchilton/galaxy/commit/f3e81f148f4b13ef0e5846593c355d270f7baece

**Comment by bgruening** [comment]
@jmchilton also works for me. Is the container starting at all?

**Comment by jmchilton** [comment]
Container is starting but my proxy is stating "Proxy target undefined". I'll keep working on this - thanks for the confirmation.

**Comment by jmchilton** [comment]
Finally got it - found a bug in bgruening/docker-ipython-notebook I think and will follow up there. On this end - everything looks really good! Thanks a ton @bgruening and @erasche - the awesomeness never stops with you guys.

**Comment by bgruening** [comment]
Great! Thanks for merging!

**Pull request merged**
