### PR TITLE
Dependency update and doc fixes

### PR DESCRIPTION
**Pull request by nsoranzo**
* Pin pysam to 0.15.2
* Update all dependencies
* Sphinx `doc/source/conf.py` modifications:
  - Update recommonmark configuration
  - Do not build rst files starting with `_`
  - Do not exclude releases docs when setting ``GALAXY_DOCS_SKIP_SOURCE``
- Doc bugfixes
- Use proper cross-referencing with `:doc:`

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Comment by mvdbeek** [comment]
Ahhh ... surprisingly the failing API test passes on 3.6. I can fix the 2 failing ones.

**Comment by nsoranzo** [comment]
@mvdbeek One I've fixed already and working on the second one, but I cannot reproduce the Py3 integration one.

**Comment by nsoranzo** [comment]
@galaxybot test py3

**Comment by nsoranzo** [comment]
Green!

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thanks @nsoranzo. We should keep an eye on that integration test.

**Pull request merged**
