### PR TITLE
Add cache_dir to schema

### PR DESCRIPTION
**Pull request by jdavcs**
Addresses #11200.
Is this sufficient?

### CODE REVIEW

**Comment by mvdbeek** [comment]
Excellent, I think that should cover it!

**Comment by hexylena** [comment]
This is fantastic @ic4f!

**Comment by mvdbeek** [comment]
Our friend `ERROR test/integration/test_config_defaults.py - KeyError: 'cache_dir'` says hello! :)

**Comment by ic4f** [comment]
I know, I know :-) And extra level in path-resolves-to broke the integration test testing config defaults - so at least it's the test that's broken. Shouldn't be a problem, fixing..

**Pull request merged**
