### PR TITLE
do not wrap lines in the upload url fetch

### PR DESCRIPTION
**Pull request by guerler**

### CODE REVIEW

**Comment by martenson** [comment]
I am open to treating this as a bugfix and getting it to 17.09.

**Comment by dannon** [comment]
+1 to lump it into 17.09.   Is there any reason to do the replace/split('\n') shuffle, and not just split() without args, letting python handle the whitespace logic?  (could be a good reason, but at first glance it seems like it'd be simpler and more robust to just do `url_paste = url_paste.split()`)

**Comment by guerler** [comment]
Is that what you meant?

**Comment by martenson** [comment]
for split()

> If the optional second argument sep is absent or None, the words are separated by arbitrary strings of whitespace characters (space, tab, newline, return, formfeed).

**Comment by dannon** [comment]
@guerler I meant dropping both replaces and just having the split().  By default, it should cover all whitespace including space, \n, and \r.

**Comment by guerler** [comment]
Got it. Thanks.

**Comment by blankenberg** [comment]
But what about a URL that has spaces in that haven't been properly converted to `%20`?

I know URLs are not technically supposed to have spaces in them, but most modern things are smart enough to handle them: chrome, firefox, wget, curl, etc. In this case I think it could be a matter of usability rather than technically correct.

**Comment by martenson** [comment]
@blankenberg Usability is what we are trying to improve here I think, what do you suggest to do with spaces then?

**Comment by blankenberg** [comment]
The help text states `You can tell Galaxy to download data from web by entering URL in this box (one per line). You can also directly paste the contents of a file.`

I would suggest turning off line-wrapping in the paste/fetch data box, instead have scrollbars -- then uploaded data will match what is shown on the screen to the user.

**Comment by martenson** [comment]
@blankenberg I like that.

**Comment by guerler** [comment]
Me too. Thats a good idea. I restored the previous statements and tested the line wrap changes for FF and Chrome.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@guerler wanna rename this so it reflects its target milestone?

**Comment by martenson** [comment]
@guerler I took the liberty to do that

**Pull request merged**
