### PR TITLE
Update gsummary dependencies.

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by blankenberg** [comment]
Seems kind of odd to have both of the requirements listed twice.

**Comment by jmchilton** [comment]
:+1: But I am with @blankenberg - I would rather see the `python-module` dropped.

**Comment by dannon** [comment]
I'm out of the loop on this maybe, but why do we need to list R twice, once with a version and once without?

**Comment by bgruening** [comment]
If you want to have the tool from `tool_deps/tool/default` you need a package definition without a version number. Unfortunately, a package with version number does not default automatically to `/default` if the specified version is not found, afaik.

**Comment by jmchilton** [comment]
No - it does now - at least for non-shed stuff. I think you can remove the unversioned version.

**Comment by bgruening** [comment]
@jmchilton since when?

**Comment by jmchilton** [comment]
BitBucket doesn't have a nice link to the PR - maybe I committed it directly:

https://bitbucket.org/galaxy/galaxy-central/commits/98a91b2610abbffd0a299c6ae9bae075ca5561f4

**Comment by dannon** [comment]
(+1 to this pending removal of the bare R dep)

**Pull request merged**
