### PR TITLE
Prettier version update to new release

### PR DESCRIPTION
**Pull request by dannon**
## What did you do? 
- Update and rerun prettier.  

## Why did you make this change?
Was hoping for better dangling angle bracket handling, but this does have some nice improvements in arrow expression formatting and in making (overly...) long class lists readable

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by OlegZharkov** [comment]
is it possible somehow to merge this with eslint? (so we don't use both?)

**Comment by dannon** [comment]
@OlegZharkov There are bindings for running prettier within eslint, and eslint within prettier, but with our configuration (and in general) I think it makes the most sense to keep tools atomic.  The prettier docs also recommend not bundling it all.

Most folks should just have VSCode (or whatever) set up to automagically run prettier so you never have to think about it right?  I know that's how I do it.

**Comment by OlegZharkov** [comment]
> Most folks should just have VSCode (or whatever) set up to automagically run prettier so you never have to think about it right? I know that's how I do it.

Yeah, I have 2 shortcuts for prettier and eslint. I just wanted to click one button, instead of two. But I guess it's my own problem, which I kinda have to fix myself :sweat_smile: 
Anyway, thanks for PR :)

**Comment by mvdbeek** [comment]
> Most folks should just have VSCode (or whatever) set up to automagically run prettier so you never have to think about it right?

Do you have a pointer or a snippet for this ? I have it in my pre-commit-hooks, but not always the right version available globally.

**Comment by dannon** [comment]
@mvdbeek I have the Prettier extension installed in vscode and you can set `Prettier Path` and `Prettier Config` in the settings to use the ones bundled with Galaxy.  You can use "Format on Save" to automate it completely.

**Comment by mvdbeek** [comment]
That works beautifully, thanks @dannon !

**Pull request merged**
