### PR TITLE
Remove the default value requirement for numeric tool parameters

### PR DESCRIPTION
**Pull request by guerler**
ping @nsoranzo

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by jmchilton** [comment]
I'm -0 on this change for the reasons I've already articulated.

**Comment by guerler** [comment]
Right, I have no opinion about this, although I do not think it hurts. On the other hand it might be confusing for a user to not have a default parameter and then receive an error when attempting to leave that field empty on job submission. I leave it up to you guys. Just wanted to provide the changeset since the discussion came up with some supporting +1s.

**Comment by nsoranzo** [comment]
To clarify, with this change a tool author will not be forced to add `value=""` to a non-optional integer/float `<param />` (e.g. https://github.com/galaxyproject/tools-iuc/blob/master/tools/macs2/macs2_macros.xml#L29 ), which is also what the schema says about `value` (Required: False, see https://docs.galaxyproject.org/en/latest/dev/schema.html#id18 ).

@jmchilton We can still have Planemo emit a warning for it.

Ping @galaxyproject/iuc

**Comment by gregvonkuster** [comment]
+1 on merging this - I have several tools that require a help text with something like "Zero values have no affect" since the value must include a number without this change.

**Comment by nsoranzo** [comment]
@gregvonkuster Adding `optional="true"` should already be enough for your use case, IIUC. Remember to check in the `<command>` if the optional integer/float `param` has been set before using it by casting it to string, e.g.:
```
#if str($my_numeric_param)
    -p $my_numeric_param
#end if
```

**Comment by gregvonkuster** [comment]
@nsoranzo Ah, good to know - I'll use that approach - thanks!  ;)

**Comment by guerler** [comment]
I thought a bit more about it. How about we set the default value to `0` if the user does not specify any? That would then be consistent with other parameters e.g. the text parameter and others.

**Comment by nsoranzo** [comment]
@guerler That cure would be worse than the disease, sorry. Consistency is leaving the field empty if no default value is specified by the tool author (i.e. what this PR does). Or we force the author to specify a (potentially empty) value, i.e. the status quo.

**Comment by guerler** [comment]
Makes sense.

**Comment by guerler** [comment]
Closing this for now since it does not seem to move forward. Feel free to re-open if needed.

**Pull request closed without merging**
