### PR TITLE
Merge changes in release_15.03 to dev

### PR DESCRIPTION
**Pull request by natefoo**
I suppose we do this directly via PR now?

### CODE REVIEW

**Comment by dannon** [comment]
This is an automated message. Thanks for your contribution, a [Trello card](https://trello.com/c/kXmHGzr6) to track this issue has been created. [Apply this patch](https://github.com/galaxyproject/galaxy/pull/50.patch) for testing.

**Comment by jmchilton** [comment]
Yeah - I guess. Seems pretty heavy now - when it merges cleanly it would be good to automate this so we can skip the PR.

:+1:

**Comment by dannon** [comment]
+1, and agreed that it's a little onerous but automation is going to be sketchy for anything touching /client.  I'd almost favor merges like this being acceptable as direct commits  (dev only).

**Comment by davebx** [comment]
Besides, the commits in this pull request are already in the codebase, and thus one would tend to believe that they were solid.

:+1:

**Comment by martenson** [comment]
I have one more stable fix to go, don't merge yet please

**Comment by jxtx** [comment]
I think merges from release to dev can be done without a PR.

**Comment by natefoo** [comment]
@martenson you can always merge again.

Thanks for the discussion all (and the ruling, @jxtx, I certainly prefer not to have to PR these merges).

**Comment by martenson** [comment]
@natefoo yeah. I thought you are creating new minor release

**Comment by natefoo** [comment]
@martenson, nope, just merging.

**Pull request merged**
