### PR TITLE
Pysam 84 update [16.01]

### LINKED ISSUE #1608: pysam.ctabix
I'm reimplementing deprecated (upstream) functionality for ctabix to prevent in-place modification and precompressed flag, roll new wheel.  Has to go with 16.01.

### PR DESCRIPTION
**Pull request by dannon**
This closes #1608  and #1128

### CODE REVIEW

**Comment by natefoo** [comment]
+1 if tests pass. Jenkins framework and Travis py27-unit both fetched the new wheel.

**Comment by jmchilton** [comment]
Failing test can be executed via:

```
./run_tests.sh -framework -id metadata_bam
```

**Comment by dannon** [comment]
Failure looks like it might be legit, looking into it.

**Comment by dannon** [comment]
I think 3.bam is actually invalid.

`samtools view -H 3.bam` with the rest of the headers chopped yields:

`@PG  ID=Bowtie   VN=0.11.3   CL="bowtie -p28 -v1 -m1 -S /home/gordon/genomes/hg18_ebwt/hg18 --al solution.mother.whole_genome.1mismatch_v.aligned.one_side.bow.txt --un solution.mother.whole_genome.1mismatch_v.not_aligned.one_side.bow.txt --max solution.mother.whole_genome.1mismatch_v.repeats.one_side.bow.txt /home/erlich/Joubert/sequence_solution/s_7_sequence.txt,/home/erlich/Joubert/sequence_solution/s_8_sequence.txt bowtie_hits_mother_sloution_whole_genome.1mismatch_v.one_side.sam"`

Note the use of '=' instead of ':' in the key:value pairs.  This isn't valid per the bam spec (https://samtools.github.io/hts-specs/SAMv1.pdf)  as far as I can tell, and the updated pysam is (correctly?) now complaining that it has an invalid header line with `ValueError: malformatted header: no ':' in field`.

I guess the question is, how was 3.bam generated, and is this rule now being enforced by pysam reasonable?

I assume if the program line is correct that this was generated with an ancient version of bowtie.  Are these '=' defined headers something we should reasonably expect to see in Galaxy these days?  Or do I need to hack yet another customization into pysam?

**Comment by dannon** [comment]
ping @blankenberg @peterjc and @bgruening regarding bam header tolerances per @jmchilton's advice.

**Comment by peterjc** [comment]
This is about https://github.com/galaxyproject/galaxy/blob/dev/test-data/3.bam and yes, it looks invalid to me:

```
$ samtools view  -H 3.bam | grep "^@PG"
@PG ID=Bowtie   VN=0.11.3   CL="bowtie -p28 -v1 -m1 -S /home/gordon/genomes/hg18_ebwt/hg18 --al solution.mother.whole_genome.1mismatch_v.aligned.one_side.bow.txt --un solution.mother.whole_genome.1mismatch_v.not_aligned.one_side.bow.txt --max solution.mother.whole_genome.1mismatch_v.repeats.one_side.bow.txt /home/erlich/Joubert/sequence_solution/s_7_sequence.txt,/home/erlich/Joubert/sequence_solution/s_8_sequence.txt bowtie_hits_mother_sloution_whole_genome.1mismatch_v.one_side.sam"
```

Stepping back to the original revision based on https://github.com/galaxyproject/galaxy/commits/dev/test-data/3.bam it was still broken:

```
$ git checkout bcd6751cdf2293e4a8b4666c629fa7fbbaf0d8d6
$ samtools view -H 3.bam | grep "^@PG"
@PG ID=Bowtie   VN=0.11.3   CL="bowtie -p28 -v1 -m1 -S /home/gordon/genomes/hg18_ebwt/hg18 --al solution.mother.whole_genome.1mismatch_v.aligned.one_side.bow.txt --un solution.mother.whole_genome.1mismatch_v.not_aligned.one_side.bow.txt --max solution.mother.whole_genome.1mismatch_v.repeats.one_side.bow.txt /home/erlich/Joubert/sequence_solution/s_7_sequence.txt,/home/erlich/Joubert/sequence_solution/s_8_sequence.txt bowtie_hits_mother_sloution_whole_genome.1mismatch_v.one_side.sam"
```

_Edit_: Fixed cut and paste of second example

**Comment by dannon** [comment]
@peterjc Thanks for the confirmation, I was hoping that was the case.  So it's OK to use this newly enforced rule in pysam?  My main concern was that if the standard was very loosely adhered to, as one might guess if bowtie (if an old version) is generating invalid bams like that, then we'd have to work around it.

**Comment by dannon** [comment]
(if this is the path we choose, I'll submit another tweak to update 3.bam so that it's valid)

**Comment by peterjc** [comment]
I'm not a heavy bowtie user - it might be worth asking on Galaxy or samtools-dev the mailing list for a wider/historical perspective? As you say, this quirk might be as rare as we would like...

**Comment by peterjc** [comment]
According to http://bowtie-bio.sourceforge.net/news.shtml the equals signs in the `@PG` line bug was fixed in **Bowtie 0.12.0-beta1 release - 12/15/09**, traced to this commit https://github.com/BenLangmead/bowtie/commit/cff6f3db764994f5c8aa5acae22178d1ef2e9d0e

The original bug dates to https://github.com/BenLangmead/bowtie/commit/1aa1debfb10589684a2cd48b780d81c9421a19a0 when SAM output was added, i.e. **Bowtie 0.11.0 release - 10/5/09**

i.e. The Bowtie `@PG` equals bug was present in the latest release from 5 October 2009 up to 12 December 2009, which is a relatively small window.

**Comment by natefoo** [comment]
Thanks for the fantastic detective work @peterjc. I'd say in this case, then, that we can just accept this and fix 3.bam.

**Comment by dannon** [comment]
@natefoo I pushed a fix to 3.bam in ba9ad97, but there's still a failing test.  Looking into it now.

**Comment by natefoo** [comment]
Confirmed via IRC that the RHEL 6 pysam wheels work for SL 6, the problem is that the `linux_x86_64_scientific_*` platform tags should be added to `binary-compatibility.cfg` like CentOS. I also want to verify that SL 7 does not identify itself as CentOS in `/etc/os-release`.

So this can be merged.

**Comment by dannon** [comment]
@natefoo for SL7.1

```
ID="rhel"
ID_LIKE="fedora"
```

**Comment by natefoo** [comment]
I built myself some SL6 and 7 docker images and updated the [running gist](https://gist.github.com/natefoo/814c5bf936922dad97ff) I have for this.

SL 7 will work with these wheels out of the box w/o `binary-compatibilty.cfg` since it sets `ID="rhel"` in `/etc/os-release`. Interesting choice by SL and perhaps the platform lib should force it to `scientific` as in older versions, but that's a question for later.

**Pull request merged**
