### PR TITLE
Update all Python dependencies

### PR DESCRIPTION
**Pull request by nsoranzo**
using `make update-dependencies` .

Also:
- Update `lib/galaxy/dependencies/update.sh` with recommended `poetry` installation method
- Increate `poetry` verbosity
- Update version pins in `pyproject.toml` for a faster and correct dependency resolution
- Remove leftover `six` requirement from 3 packages

Help in fixing the the issues that will inevitably arise is very welcome!

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

**Comment by nsoranzo** [comment]
The integration test `test/integration/test_job_environments.py::EmbeddedPulsarDefaultJobEnvironmentIntegrationTestCase::test_default_environment_1801` fails reproducibly with pulsar-galaxy-lib==0.14.11 but pass with 0.14.10 (which we are currently using on dev). I've looked at the diff between the 2 versions but couldn't spot what could cause this.
Any idea @jmchilton ?

**Comment by jmchilton** [comment]
I can verify the issue locally:

```
--------------------------------------
| 1 - user_id (HID - NAME) 
INFO:     127.0.0.1:50726 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50732 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 2 - group_id (HID - NAME) 
INFO:     127.0.0.1:50733 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50734 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 3 - pwd (HID - NAME) 
INFO:     127.0.0.1:50735 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50736 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 4 - home (HID - NAME) 
INFO:     127.0.0.1:50737 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50738 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 5 - tmp (HID - NAME) 
INFO:     127.0.0.1:50739 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50740 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 6 - env_var (HID - NAME) 
INFO:     127.0.0.1:50741 - "GET /api/histories/adb5f5c93f827949/contents/cb227cec8ca83994 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50742 - "GET /api/histories/adb5f5c93f827949/contents/cb227cec8ca83994/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
INFO:     127.0.0.1:50743 - "GET /api/jobs?history_id=adb5f5c93f827949 HTTP/1.1" 200 OK
--------------------------------------
| Job adb5f5c93f827949
| State: 
|  error
| Update Time:
|  2021-11-08T19:09:18.712775
| Create Time:
|  2021-11-08T19:09:05.018306
|
--------------------------------------
Problem in history with id adb5f5c93f827949 - summary of history's datasets and jobs below.
INFO:     127.0.0.1:50744 - "GET /api/histories/adb5f5c93f827949/contents HTTP/1.1" 200 OK
--------------------------------------
| 1 - user_id (HID - NAME) 
INFO:     127.0.0.1:50749 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50750 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 2 - group_id (HID - NAME) 
INFO:     127.0.0.1:50751 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50752 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 3 - pwd (HID - NAME) 
INFO:     127.0.0.1:50753 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50755 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 4 - home (HID - NAME) 
INFO:     127.0.0.1:50756 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50757 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 5 - tmp (HID - NAME) 
INFO:     127.0.0.1:50758 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50762 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 6 - env_var (HID - NAME) 
INFO:     127.0.0.1:50772 - "GET /api/histories/adb5f5c93f827949/contents/cb227cec8ca83994 HTTP/1.1" 200 OK
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  *Peek unavailable.*
INFO:     127.0.0.1:50773 - "GET /api/histories/adb5f5c93f827949/contents/cb227cec8ca83994/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
INFO:     127.0.0.1:50774 - "GET /api/jobs?history_id=adb5f5c93f827949 HTTP/1.1" 200 OK
--------------------------------------
| Job adb5f5c93f827949
| State: 
|  error
| Update Time:
|  2021-11-08T19:09:18.712775
| Create Time:
|  2021-11-08T19:09:05.018306
|
--------------------------------------
```

No clue why it is happening yet though.

**Comment by jmchilton** [comment]
The files look pretty much the same before:

```
--------------------------------------
| 1 - user_id (HID - NAME) 
INFO:     127.0.0.1:53589 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949 HTTP/1.1" 200 OK
| Dataset State:
|  ok
| Dataset Blurb:
|  1 line
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  <table cellspacing="0" cellpadding="3"><tr><td>190288850</td></tr></table>
INFO:     127.0.0.1:53590 - "GET /api/histories/adb5f5c93f827949/contents/adb5f5c93f827949/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 2 - group_id (HID - NAME) 
INFO:     127.0.0.1:53591 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36 HTTP/1.1" 200 OK
| Dataset State:
|  ok
| Dataset Blurb:
|  1 line
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  <table cellspacing="0" cellpadding="3"><tr><td>357253257</td></tr></table>
INFO:     127.0.0.1:53592 - "GET /api/histories/adb5f5c93f827949/contents/529fd61ab1c6cc36/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 3 - pwd (HID - NAME) 
INFO:     127.0.0.1:53593 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e HTTP/1.1" 200 OK
| Dataset State:
|  ok
| Dataset Blurb:
|  1 line
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  <table cellspacing="0" cellpadding="3"><tr><td>/private/var/folders/1d/bs7mkcjx4t79x1rgbr2ns5br5ng4yk/T/tmp86aqrvdv/tmpryirjeyr/tmpoff1gxhr/database/pulsar_staging/1/working</td></tr></table>
INFO:     127.0.0.1:53594 - "GET /api/histories/adb5f5c93f827949/contents/d9abeb98649a6a7e/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 4 - home (HID - NAME) 
INFO:     127.0.0.1:53595 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006 HTTP/1.1" 200 OK
| Dataset State:
|  ok
| Dataset Blurb:
|  1 line
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  <table cellspacing="0" cellpadding="3"><tr><td>/private/var/folders/1d/bs7mkcjx4t79x1rgbr2ns5br5ng4yk/T/tmp86aqrvdv/tmpryirjeyr/tmpoff1gxhr/database/pulsar_staging/1/working/../home</td></tr></table>
INFO:     127.0.0.1:53596 - "GET /api/histories/adb5f5c93f827949/contents/f3f73e481f432006/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
| 5 - tmp (HID - NAME) 
INFO:     127.0.0.1:53597 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331 HTTP/1.1" 200 OK
| Dataset State:
|  ok
| Dataset Blurb:
|  0 lines
| Dataset Info:
|  Writing environment properties to output files.
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
| Peek:
|  <table cellspacing="0" cellpadding="3"></table>
INFO:     127.0.0.1:53598 - "GET /api/histories/adb5f5c93f827949/contents/2234cb1fd1df4331/provenance HTTP/1.1" 200 OK
| Dataset Job Standard Output:
|  Writing environment properties to output files.
| Dataset Job Standard Error:
|  Example tool stderr output.
|  touch: /tmp_test: Read-only file system
|
--------------------------------------
```

The problem is I think this test was written when there was a bug that prevented this job failure exit code from reaching Galaxy and we fixed that with https://github.com/galaxyproject/pulsar/pull/274/files. So two bugs cancelled each other out and now just one is happening and this indicates a real problem.

I'll keep looking into it though.

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/galaxy/commit/7ed0f5337fd5de6cd17ff9453dbceb8092ab81dc this just doesn't work with Pulsar. Why did we add this magic ``_GALAXY_JOB_TMP_DIR`` when I put some much work into ``job_info.tmp_directory``.

And like the magic is only going to work with older tools?

```
        if self.job_info.tmp_directory is not None:
            volumes.append(DockerVolume.from_str("%s:/tmp:rw" % self.job_info.tmp_directory))
        else:
            volumes.append(DockerVolume.from_str("$_GALAXY_JOB_TMP_DIR:$_GALAXY_JOB_TMP_DIR:rw"))
```

I need to dig into this for more context.

**Comment by nsoranzo** [comment]
I've rebased to fix a merge conflict, updated more dependencies and manually changed the pin for pulsar-galaxy-lib to 0.14.10 to make this mergeable.

**Pull request merged**
