### PR TITLE
Spinner in library folders

### PR DESCRIPTION
**Pull request by OlegZharkov**
Sometimes, it really takes a while to load a library folder and it's hard to tell whether page is loading or it's hanged.  So, this PR adds a spinner:

image

Spinner is already part of galaxy (font awesome).

Ultimately, would be quite nice to Vuefy this functionality one day.. However, adding spinner for now

### CODE REVIEW

**Comment by dannon** [comment]
Good idea; looks like the branch accidentally includes a commit from https://github.com/galaxyproject/galaxy/pull/9686 ?

**Comment by OlegZharkov** [comment]
@Dannon

Oh yeah, you are right. I probably merged it with wrong "dev", so `gitk` showed me only  spinner stuff. I will fix...

**Comment by dannon** [comment]
@OlegZharkov No worries, figured it was an accident :)

**Comment by dannon** [comment]
Merged manually resolving prettier issues.

**Comment by OlegZharkov** [comment]
thanks @dannon !

**Pull request merged**
