### PR TITLE
Downgraded mercurial to 6.0.2 as wheels for 6.0.3 is not available

### PR DESCRIPTION
**Pull request by kxk302**
(Please replace this header with a description of your pull request. Please include *BOTH* what you did and why you made the changes. The "why" may simply be citing a relevant Galaxy issue.)
(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Better to open a PR creating the wheel, as in https://github.com/galaxyproject/starforge-recipes/pull/93 . Also see the discussion there.

**Comment by mvdbeek** [comment]
@kxk302 As I said on slack, you can either build the wheel or downgrade on the branch we deploy from, this doesn't block upgrading test.

**Comment by kxk302** [comment]
@mvdbeek You cannot deploy the dev branch to Test.

**Comment by mvdbeek** [comment]
If you don't want to add a commit that downgrades mercurial you are totally free to build the wheel. That's a one lien change. And feel free to set up the automation.

**Comment by kxk302** [comment]
I did not upgrade mercurial. Whoever set it to 6.0.3, and realized the wheel is not there, should have downgraded it, instead of everyone be required to downgrade it in their branch for a Test deployment.

**Comment by kxk302** [comment]
I did not upgrade mercurial.

**Comment by mvdbeek** [comment]
But you're the one who wants to upgrade test and hence noticed that we don't have the wheel. And I don't understand why we even need to discuss this, it takes 1 line and 5 minutes of waiting to build a wheel, or one commit to deploy from another branch.

**Pull request closed without merging**
