### PR TITLE
Add buffer-size to galaxy.yml.sample

### PR DESCRIPTION
**Pull request by blankenberg**
Bumped into "invalid request block size" message locally. Increasing buffer-size solved it for me.

### CODE REVIEW

**Comment by martenson** [comment]
sample is modified by changing https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/config_schema.yml and then running a makefile

**Comment by jmchilton** [comment]
Ping @natefoo , should we just change the default here? Also does the uwsgi parsing code need to be updated for this in some way?

**Comment by martenson** [comment]
@jmchilton I am a bit confused how this plays together with https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/uwsgi_schema.yml#L147

Do we just override it using config_manage?

**Comment by jmchilton** [comment]
That schema is auto-generated and contains way more options than we want to include in our sample file, so we use it for validation but not for generating the sample. For the sample we just pick a few options out and give them our own description - I believe - that set of descriptions I think is what modified in this PR (the config_manage.py change).

**Comment by natefoo** [comment]
[On Main](https://github.com/galaxyproject/usegalaxy-playbook/blob/086ff26fd1ab03f9173829d4de683e410a5e1525/env/main/templates/galaxy/config/uwsgi.ini.j2#L11) we use 16384. I'd say a default of at least 8192 probably makes sense. `scripts/get_uwsgi_args.py` would need to be updated for it.

**Comment by jmchilton** [comment]
Will increase the default in a subsequent PR - thanks for the change @blankenberg !

**Pull request merged**
