### PR TITLE
[18.05] Limit select2 text label length to 100 characters

### LINKED ISSUE #6123: upload modal genome selection too wide
under 1600px of width it starts being unusable as the start hides off the screen

screenshot 2018-05-11 12 24 47

ping @guerler

### PR DESCRIPTION
**Pull request by guerler**
Fixes #6123. This PR augments the select2 fields used in the upload dialog. It limits the maximum text label length and supplements the trimmed text with the selection value to avoid entry duplication.

### CODE REVIEW

**Comment by martenson** [comment]
I had a look at Main and currently the problem is pretty big with the longest label being 148 chars (`Japanese eel 18 Mar-2014 (japanese_eel_genome_v1_25_oct_2011_japonica_c401b400k25m200_sspacepremiumk3a02n24_extra.final.scaffolds/angJap1) (angJap1)`).

What is worse is that the actual `dbkey` seems to be in the last part of the string and we should definitely preserve that.

Maybe 100 chars from the end of the string could do it? I am not sure :/

edit: I would also advocate for a more defensive approach that affects only the upload modal, in other contexts long items might make better sense

**Comment by dannon** [comment]
Opened a PR for this branch at https://github.com/guerler/galaxy/pull/26, which fixes a bug where due to reinitialization/reuse of the same data array the separator sequence would get appended potentially a bunch of times, yielding entries like:
`S. cerevisiae Oct.    2003 ................(sacCer1)`

**Comment by guerler** [comment]
Thanks @dannon.

**Comment by dannon** [comment]
@guerler No prob, looks good to me now.

**Pull request merged**
