### PR TITLE
[15.10] docs - deprecate TS direct hg api

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by hexylena** [comment]
:+1:!!!

**Comment by hexylena** [comment]
Crap, this was 15.10 wasn't it. @nsoranzo I don't suppose you'd +1 this as well?

**Comment by blankenberg** [comment]
+1

**Comment by dannon** [comment]
@erasche Prerelease, YY.MM branch contributions do not need a second +1 -- only after the official release.

**Comment by nsoranzo** [comment]
:+1: anyway!

**Pull request merged**
