### PR TITLE
[PROCEDURES] Update committers list

### PR DESCRIPTION
**Pull request by carlfeberhard**
@natefoo That work?

### CODE REVIEW

**Comment by dannon** [comment]
+1, thanks for all the contributions @carlfeberhard, and best of luck!

**Comment by martenson** [comment]
@natefoo I don't see the point in removing @carlfeberhard from the committers. If he chooses to provide his input I applaud and there is no harm in having the option if he doesn't.

Maybe I misunderstood this and @carlfeberhard wants to remove himself from the list, in which case I begrudgingly understand.

**Comment by dannon** [comment]
Hrmm, I assumed this was the latter case and that @carlfeberhard wanted to remove himself, but let me know if I am wrong.

**Comment by jmchilton** [comment]
@martenson The procedures make it clear that we shouldn't have committers that aren't actively engaged in Galaxy. The "harm" of committers that aren't engaged is that it is harder to reach consensus on procedures votes. From the procedures doc:

> Given the responsibilities and power invested in this group - it is important that individuals not actively working on Galaxy in some fashion are removed from the group. If individuals in this group intend to change jobs or reallocate volunteer activities and will no longer be active in the Galaxy community, they should withdraw from membership of this group. Periodically, active members may review this group and request inactive members are removed - this should not be interpreted as a condemnation of these inactive members but merely as a reflection of a desire to keep this group focused enough to remain effective.

If @carlfeberhard plans to continue to work on Galaxy, I think we would all love his contributions and expertise. If not though, I think he should be removed.

**Comment by jmchilton** [comment]
+1 - thanks for everything @carlfeberhard. Every time I read your code I learn something new. Your focus on software quality, documentation, and testing was (and remains) desperately needed - this is a real loss for the project. Hope whatever you are moving on to next is awesome - I'm sure you'll excel at it!

**Comment by nsoranzo** [comment]
:+1: 

@carlfeberhard Thanks a lot for all your contributions, your work on the UI made Galaxy much better and we'll try to follow your footsteps. Best of luck for your new adventure!

**Comment by carlfeberhard** [comment]
@martenson Yeah, absolutely my idea. I had already removed myself from the actual list of committers in github and this change just updates the records to reflect that fact. @natefoo just reminded me of the list.

Thanks, guys - I've learned a lot working with you all.

**Comment by mvdbeek** [comment]
:+1: Thanks for all your great work, @carlfeberhard. Best of luck with your next projects.

**Comment by martenson** [comment]
@carlfeberhard Best of luck mate.
👍

**Comment by natefoo** [comment]
Yeah, to clarify, I spoke with @carlfeberhard privately beforehand, this wasn't me attempting to kick him out of the club. I 100% support the idea that people should be able to leave a job that supports them working on Galaxy but continue to be a part of the committers group if they still intend to be an active part of the project on their own.

+1 from me, and best of luck to you Carl - it's truly been a pleasure to work with you and I can't speak highly enough about your contributions to Galaxy.

**Comment by jxtx** [comment]
I think it is an excellent precedent for committers who will be less active in Galaxy (especially those who leave jobs working on Galaxy full time) to voluntarily remove themselves from committers. They can always continue to contribute to Galaxy through pull requests just like many active members of our community.

Thanks for your work on the project @carlfeberhard, its been great to have you on the team and I hope you enjoy your next gig!

**Comment by bgruening** [comment]
It's a sad day for me! All the best Carl.
:+1:

**Pull request merged**
