### PR TITLE
[17.01] Logout recalc backport and additional logic

### PR DESCRIPTION
**Pull request by dannon**
xref #3600

### CODE REVIEW

**Comment by martenson** [comment]
@dannon these TS tests fails seem legit

**Comment by dannon** [comment]
Hrmm, that's interesting.  I thought about this when writing it, but logout() isn't an available endpoint when trans.user is None, so this should never be called.  My hunch is the tests are doing something weird, but I'll make it more defensive anyway.

**Comment by martenson** [comment]
also the whole branch is only when `if trans.webapp.name == 'galaxy':` so that is weird

**Comment by dannon** [comment]
Minor tweak to the tooltips inc, one sec.

**Comment by dannon** [comment]
@martenson Thanks!  I'll merge it forward now.

**Comment by bgruening** [comment]
@dannon can we make this async? People think than logging out takes now seconds ... and after refreshing the page they are still logged in.

**Comment by nsoranzo** [comment]
True, I don't log out often, but noticed this too. I have to clear the cookie to log out.

**Comment by dannon** [comment]
Hrmm.  Yes, probably.  I'll work on it.  It also looks like User.calculate_disk_usage() (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L259) isn't using the much faster postgres optimizations here: https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/lib/galaxy/model/util.py#L6

And that's a much easier first target.

**Comment by dannon** [comment]
Linked to the main issue, but I forgot about the backport.  See #3669

**Pull request merged**
