### PR TITLE
Allows to drag-and-drop history items into the content selector

### PR DESCRIPTION
**Pull request by guerler**
Enhancement towards #3833. This does not yet allow to pick and drag sub-datasets from within collections.

drag-and-drop

### CODE REVIEW

**Comment by nekrut** [comment]
Should also be able (reverentially) to drag and drop collections

**Comment by guerler** [comment]
Just to clarify this, so collections can be dragged and dropped but not datasets from within collections. Basically everything what currently can be selected with the content selector can also be dropped into it.

**Comment by nekrut** [comment]
Hmmm....without being ideological I must say that dragging individual dataset from collection may be exactly what I'm asking in #3870 Why not?

**Comment by nekrut** [comment]
...but the difficulty may be with workflow representations and other such things (what would happen if I would convert a history in which datasets are pulled from a collection into a workflow?). I would just make collections drag-able at this point. Need more feedback from @jmchilton and @jxtx

**Comment by guerler** [comment]
I totally agree with you, accessing individual components of collections would significantly improve the user experience. This PR simply filters the dropped items by dataset ids currently available in the data selector. The ids of collection datasets are not in this list. We have a couple ideas on how to extend this dynamically and make individual collection datasets selectable but that should probably not be part of this PR.

**Comment by jmchilton** [comment]
Great job - I really like this! I do think it is a step in the right direction and I'm excited to see follow up steps. I do think this has some advantages over #3870 as discussed on #740 but drag and drop isn't a silver bullet either - just a very common sense thing that we should definitely be doing. There are ramifications for workflow extraction say - but I think it would be happy to take a swing at solving those after dragging and dropping collection elements works.

**Comment by martenson** [comment]
Great stuff & very clear, also way shorter than I expected this to be.

**Comment by jmchilton** [comment]
This was marked WIP.

**Comment by martenson** [comment]
Sorry for missing the wip tag, the merge was reverted with the PR above. Now I think you need to open a new PR @guerler - sorry again. :(

**Comment by guerler** [comment]
No worries, it was good to go. I'll open a new PR in a few and run a couple more tests. Thanks a lot for the quick review.

**Pull request merged**
