### PR TITLE
Kubernetes runner corrects working directory not passed to container

### PR DESCRIPTION
**Pull request by pcm32**
For some reason, probably an error by myself, the workingDirectory setting for the container in Kubernetes got erased at some commit. This PR puts it back again. This was only noticeable when jobs had to rescue files generated in the working directory.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by erasche** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Pull request merged**
