### PR TITLE
Fix post job actions for Database Operation tools, implement change_datatype for collection output

### LINKED ISSUE #7473: Workflow collection operation "Build list": no hide; no delete intermediate data
Tool: Build List from one or more datasets (Galaxy Version 1.0.0)

At least two problems, might be related:

1. The tool job itself ends up in the history output -- not following the hidden/show toggle or the post job action "delete intermediate datasets".
1. The datasets the tool uses as inputs are copied back into the same history and are not hidden either. 

History: https://usegalaxy.org:/u/jen/h/test-buildlist-wf-dup-data

Workflow:  https://usegalaxy.org/u/jen/w/testbuildlist

ping @dannon @jmchilton

### PR DESCRIPTION
**Pull request by mvdbeek**
The rename action works, the hide action fails.
Building this to fix https://github.com/galaxyproject/galaxy/issues/7473.

### CODE REVIEW

**Comment by dannon** [comment]
@mvdbeek Thanks for this -- I should have added tests for these years ago, would have saved some pain!

**Comment by mvdbeek** [comment]
Looks like it's working, but I think I'll want to test all of the possible PJAs.

**Comment by mvdbeek** [comment]
This will also fix https://github.com/galaxyproject/galaxy/issues/3947.

**Comment by jmchilton** [comment]
I assume we should backport this to at least 19.01?

**Comment by mvdbeek** [comment]
Yep, I wouldn't go further back than 19.01, it is more of a new feature than a bug I'd say.

**Pull request merged**
