### PR TITLE
Include link to old and new toolshed repository, and make sure upgrade message is…

### PR DESCRIPTION
**Pull request by mvdbeek**
… not overwritten by tool_version changes.

This is in continuation of PR #818

### CODE REVIEW

**Comment by mvdbeek** [comment]
Ping @guerler @bgruening

**Comment by mvdbeek** [comment]
These are the 2 warning messages
screen shot 2015-12-10 at 14 09 37
screen shot 2015-12-10 at 14 17 57

**Comment by mvdbeek** [comment]
To satisfy the unit tests I had to put tool_id back into the message.
The message looks like this now:
screen shot 2015-12-10 at 14 44 54

**Comment by martenson** [comment]
Awesome @mvdbeek ! 
I have to say I would rather see the unit test being changed to test your more reasonable message than the other way around.

**Comment by mvdbeek** [comment]
@martenson I think it's even better to do it like it is now: The tool id is shown only when hovering over the line and the test passes.

**Comment by martenson** [comment]
looks great, thanks @mvdbeek !

**Pull request merged**
