### PR TITLE
[24.0] Update ENA url in ebi_sra tool

### PR DESCRIPTION
**Pull request by mvdbeek**
I think this fixes https://github.com/galaxyproject/galaxy/issues/18770 ? I did manage to get the redirect to Galaxy, however the user interface does not look intuitive to me, so I'm not sure this is how it is meant to be ?

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mr-c** [comment]
> I did manage to get the redirect to Galaxy,

Where? I can't see it..

**Comment by mr-c** [comment]
@mvdbeek Thanks! Yeah, I never saw that link. Please let me know if there is a public test server I can use, or when this is rolled

**Comment by B0r1sD** [comment]
@mr-c did you end up successfully testing the tool? As it does not seem to be working on .be (v24.2) nor .eu (v25.0). It's still behaving exactly as you described in your issue #18770 so If I'm not missing anything, I can open a new issue or ask a dev to reopen your old one. 
Thank you in advance!

**Comment by mvdbeek** [comment]
What the tool does is set the galaxy server URL you're working with (`Select Galaxy Server` in the screenshot above). Click on 
Screenshot 2025-09-19 at 11 57 44 
and the download will start at your server

**Comment by B0r1sD** [comment]
The problem is that I never get to the `Select Galaxy Server` option when browsing to such a Read file page. 

Reproducible example: When I click the `EBI SRA ENA SRA` data source tool in the .be instance ([link](https://usegalaxy.be/tool_runner/data_source_redirect?tool_id=ebi_sra_main)), the URL includes a reference to our server at the end: `https://www.ebi.ac.uk/ena/browser/search?GALAXY_URL=https:%2F%2Fusegalaxy.be%2Ftool_runner%3Ftool_id%3Debi_sra_main`. But from the moment I click something on that page or enter a search term (and press enter to search), that URL suffix dissapears. So then when I take a random example sample that has a Read file page, I don't see any Galaxy option ([link](https://www.ebi.ac.uk/ena/browser/view/SRR32928175)):
afbeelding

Even when I try to 'spoof' it by adding that special suffix, I still don't see the option to select my Galaxy instance ([link](https://www.ebi.ac.uk/ena/browser/view/SRR32928175?GALAXY_URL=https:%2F%2Fusegalaxy.be%2Ftool_runner%3Ftool_id%3Debi_sra_main)). 

Does this make sense? I'm also not missing a way to update the tool I believe, as it lives as the following entry in a tool_conf.xml file:  `<tool file="data_source/ebi_sra.xml" />`. I also tried another browser (Firefox, Safari). But as you guys do seem to have success with the tool, I'm curious how and where : - ). 

I have the exact same behaviour for the same tool at the .eu and .org.au instance. 

Thanks a lot for getting back to this older issue @mvdbeek!

**Comment by mvdbeek** [comment]
> that URL suffix dissapears.

probably stored in a cookie or session storage. it does work for me:

Screenshot 2025-09-22 at 14 55 10

**Comment by mvdbeek** [comment]
Well, it doesn't work in anon mode. Possibly something broken at the ENA site? All that should be needed is the `GALAXY_URL` query parameter.

**Comment by B0r1sD** [comment]
Does that mean it was some dangling cookie or cache which made it still work for you in non-anon mode? Do I fill in [their support form](https://www.ebi.ac.uk/ena/browser/support) then? 

[I also made .eu aware](https://github.com/usegalaxy-eu/infrastructure-playbook/issues/1644), as there are more data source tools that don't seem to be working on our servers. I'm waiting for their input to draw conclusions but a lot of tools on that list come default with the codebase: https://github.com/galaxyproject/galaxy/blob/10991781e47c33c3392df958f4f18a8615f0e1e8/lib/galaxy/config/sample/tool_conf.xml.sample#L11.

**Comment by mvdbeek** [comment]
Yes, if you could fill the support form that'd be great!
Can you move the issue to the main galaxy repo ?

**Comment by mvdbeek** [comment]
Screenshot 2025-10-13 at 11 11 34

The (default) server selection works on anon mode too, but you have to select `fastq_galaxy` as a field to display. Maybe this could work more like the instance selector at https://iwc.galaxyproject.org/workflow/rnaseq-pe-main/ ?
Screenshot 2025-10-13 at 11 13 16

**Comment by B0r1sD** [comment]
Thanks @mvdbeek, after checking (= displaying) one of the `*_galaxy` columns I was indeed redirected to the selected Galaxy instance!

I also found that the functionality to send data from ENA using this EBI SRA tool to a Galaxy instance is always available, whether a user was redirected from Galaxy or not. The 'Select Galaxy server' appears from the moment when either `fastq_galaxy`, `sra_galaxy` or `submitted_galaxy` are checked.

So my idea is to fill in their contact form asking if it is possible to make the 'Select Galaxy server' option visible enabled by default (so checking one of those three aforementioned columns) when users are redirected from Galaxy, as that is how it used to work if I remember that right. [This old demo video](https://vimeo.com/121187220) seems to confirm this, but also shows no additional columns could be selected. So these changes made on their side now at least requires documentation on how to use the tool on our side, which is not straightforward with such data source tool as they don't work like regular tools which have a dedicated landing page with help section. Sounds good to you?

**Comment by B0r1sD** [comment]
Also not fully convinced we can say the tool (wrapper) is not broken on the Galaxy side as well:
image

Is shows green, alongside an error code (exact same seen on .eu and .au). There is content that was downloaded but I am not able to display it and when trying to download it locally, the download of the file is called 'display' and the content (when opened in a text editor) is a combination of what seems like wrongly interpreted binary and incoherent metadata. This is an example of such a download link (1.2 GB!): `https://usegalaxy.org/datasets/f9cad7b01a472135ed4e5210b8cac6e2/display`. Here is my history with the job from the screenshot: https://usegalaxy.eu/u/b0r1sd99/h/test.

**Comment by mvdbeek** [comment]
This works both on usegalaxy.eu and usegalaxy.org, but the ENA has had intermittent issues last week. Here's one I did now: https://usegalaxy.org/u/marius/h/ena and here's one on .eu from last week: https://usegalaxy.eu/datasets/26c75dcccb616ac8a95ade2c0434f7d5/details

**Comment by mvdbeek** [comment]
> Sounds good to you?

yes, in principle. if you get in contact and they have some resources for collaboration it's also worth pointing out landing requests which should eventually replace this kind of data source tools. Some of the upsides are that they can send along arbitrary metadata and multiple datasets, so it might also be worth waiting until that's rolled out in a couple of weeks.

**Comment by B0r1sD** [comment]
Closing this open ended conversation with confirming the tool does work (also on .be) but needs extra documentation for users to figure it easily out on their first tries. Data source tools don't really have a place to document as the normal 'help' section on the tool form page is only accessible through the direct URL (as you get directed to another browser tab when selecting a data source tool). Not sure where this could or should be done. 

EBI responded to me once where they indeed acknowledged some transient FTP issues and shared some alternatives like Aspera and Globus (page they updated: https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html#). I also made a UX suggestion to have the possibility to add more Galaxy servers to the list where one could sent the data back to, like an additional field that allows custom Galaxy URLs. But did not hear back so leaving it as is.

**Pull request merged**
