### PR TITLE
Mauve XMFA datatype

### PR DESCRIPTION
**Pull request by hexylena**
CC @bgruening

The only change I want to discuss is adding the `-E` flag to grep for extended regex. 
- I need `-E` for phrases like `[[:digits:]]+` as sequence counts can go above one digit.
- however, I don't strictly need that function, I could write a custom sniffer which just reads header lines and quits when it sees a `>` line. This would remove the need for `-E`, but results in more code.

Is `-E` a problem for anyone? The grep statement is used in two places:
- stockholm sniffing
- xmfa metadata (I could use it in sniffing too, but .. eh)

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by bgruening** [comment]
`-E` is fine and the datatype as well :+1:

**Comment by natefoo** [comment]
`-E` is specified in the POSIX standard for `grep`, so there shouldn't be any cross-platform issues, if that's what you were worried about.

**Comment by hexylena** [comment]
@natefoo indeed, that's what I was worried about.

**Pull request merged**
