### PR TITLE
Fix import orders for updates to flake8_import_order.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by nsoranzo** [comment]
I don't think that's going to fix the errors (or is not the "right" fix), you should group them on a single line, and order them alphabetically. I was also working on this, fixing some Python3 errors in the same files. How would you like to proceed?

**Comment by jmchilton** [comment]
I don't know - this fixed it for me locally. I don't really believe in putting multiple imports on one line. I feel like multi-line imports with `(` and `)` are more readable and more merge friendly for downstream work.

**Comment by nsoranzo** [comment]
@jmchilton Yeah, that is fine too, the problem is with:

```
from foo import bar1
from foo import bar2
```

which should either be:

```
from foo import bar1, bar2
```

or (as you suggested):

```
from foo import (
    bar1
    bar2
)
```

**Comment by jmchilton** [comment]
This did fix the errors - I'd recommend merging this so CI is fixed and follow up with a PR merging the import lines?

**Pull request merged**
