### PR TITLE
Bring Galaxy, reports, and shed run scripts in sync.

### PR DESCRIPTION
**Pull request by jmchilton**
- They now uniformly handle server option processing.
- Reports and Tool Shed now respect many important options such as `--skip_venv`.
- Reports and Tool Shed now do extra checking around Python version that Galaxy does.

In addition to improving the reports and tool shed startup scripts and reducing cognative load with respect to option handling, this is an important precondition to us being able us to switch on uwsgi by default for all three services simultaneously without a bunch of copy and pasting.

### CODE REVIEW

**Comment by jmchilton** [comment]
Includes #2836 but that should disappear once that PR is merged I believe.

**Comment by dannon** [comment]
This seems to break (at least) reports running for me.  With reports running locally (from dev), `./run_reports.sh --stop-daemon` is returning a [1] and is not stopping reports.

After killing it manually and trying to relaunch (from this branch)  `./run_reports.sh --daemon` simply hangs instead of daemonizing and running reports.

**Comment by jmchilton** [comment]
Thanks for the review @dannon - I'll fix and reopen.

**Comment by dannon** [comment]
@jmchilton Sounds good.  (or, really, it'd be fine to fix them here on this branch to preserve the context, but totally up to you)

**Pull request closed without merging**
