### PR TITLE
[WIP] [19.09] backport: Fix bug in build_dependency_manager()

### PR DESCRIPTION
**Pull request by martenson**
backport of https://github.com/galaxyproject/galaxy/pull/8660

### CODE REVIEW

**Comment by jdavcs** [comment]
@martenson sorry - would've done it. Asked you on slack earlier today if it was what I thought it was.

**Comment by martenson** [comment]
@ic4f nurries mate, I missed that message, sorry

**Comment by nsoranzo** [comment]
Don't merge as it is, the original PR broke tool dependencies API.

**Comment by nsoranzo** [comment]
Alternative fix in https://github.com/galaxyproject/galaxy/pull/8696

**Comment by jmchilton** [comment]
Closing in favor of #8696?

**Pull request closed without merging**
