### PR TITLE
More backend speed ups for user's workflow index query.

### PR DESCRIPTION
**Pull request by jmchilton**
Ping @martenson - any chance you can deploy this on test and let me know if it speeds things up? Obviously things are not slow on my local machine so it is hard to say if it will help (I suspect yes but I don't want to hurt the situation). Let me know if you'd prefer I bug Nate about this.

Stealing Dan's or Anton's API key from the DB and hitting ``http://test.galaxyproject.org/api/workflows?key=<key>`` might be a useful stress test.

### CODE REVIEW

**Comment by martenson** [comment]
@jmchilton is this ready for deployment or WIP?

**Comment by jmchilton** [comment]
Umm... I was marking it as WIP until it has been tested but I'm not actively working on it. It appears to be functionality correct and I think generally ready for deployment testing.

**Comment by martenson** [comment]
We did some testing on Test with this and seems to improve the situation (~500ms down to ~200ms for the call). But Main will be the proper testing ground for this. Do we want to backport @jmchilton ?

**Comment by jmchilton** [comment]
@martenson Yeah - I'll open a PR to merge a few things from dev into 18.01.

**Pull request merged**
