### PR TITLE
[usegalaxy] Merge release 17.01

### PR DESCRIPTION
**Pull request by martenson**
this is waiting on https://github.com/galaxyproject/galaxy/pull/3771

### CODE REVIEW

**Comment by dannon** [comment]
@martenson I thought the update playbook automatically did this merge?

**Comment by martenson** [comment]
@dannon I am not aware of it. Where?

**Comment by dannon** [comment]
I lose the trail at https://github.com/galaxyproject/usegalaxy-playbook/blob/3f3d614c52f0fbea7c9de5600799ee33ca724b7d/galaxy.yml#L23, but I definitely remember updating main without having to update this usegalaxy branch manually, before.

**Comment by martenson** [comment]
@dannon the `usegalaxy` branch only appeared after 17.01, did you update after?

**Comment by dannon** [comment]
This is clearly another @natefoo question, I can't even find the Dockerfile for that to dig deeper.

**Comment by natefoo** [comment]
We never used the `usegalaxy` branch prior to 17.01, we were always on the release branch. So unfortunately it's now necessary to merge `release_17.01` to `usegalaxy` prior to updating. We'll switch back to the release branch with 17.05, but the option will always remain to use the `usegalaxy` branch if additional features are needed on Main mid-cycle.

I've added documentation to the [usegalaxy-playbook wiki](https://github.com/galaxyproject/usegalaxy-playbook/wiki) and also committed most of the docker stuff in galaxyproject/usegalaxy-playbook@d37d808bf7a6f3b8e5688fd0581289deb0aca4ab.

**Pull request merged**
