### PR TITLE
Implement regex validators for text workflow parameter

### PR DESCRIPTION
**Pull request by mvdbeek**
Screenshot 2024-09-05 at 17 14 24

Screenshot 2024-09-05 at 17 16 49

Can't quite get the repeat to render in the editor when loading the persisted state ... but other than that I think this is functional. Will also need https://github.com/galaxyproject/gxformat2/pull/105 for tests

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
Probably is worth aligning the user facing language here with the rule builder. I used "regular expression" instead of regex throughout the frontend pieces. I think that is the right call in terms of clarify but it isn't a hill I am going to die on. I would just switch around the rule builder if you go with regex. I guess both components should be ported to use the new help terms also so we have a unified... "check out how to learn about regular expressions" blurb.

Screenshot 2024-09-06 at 11 55 03 AM

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/training-material/pull/5288#discussion_r1748082221

(maybe we can add `regular expression` to John's new help infrastructure and link to GTN?)

**Comment by mvdbeek** [comment]
regular expression sounds good to me, but we're using the tool form builder here (for better or worse), do you see a way to embed terms here ? to the form builder this just looks like a regular text parameter.

**Comment by mvdbeek** [comment]
Maybe it's time to have a regex parameter, where we can provide more help ? That concept could be extended to awk, ecmascript, python etc

**Comment by mvdbeek** [comment]
Finished in https://github.com/galaxyproject/galaxy/pull/19092

**Pull request closed without merging**
