### PR TITLE
Merge changes to common modules shared between Galaxy, Planemo, and Pulsar.

### PR DESCRIPTION
**Pull request by natefoo**
Corresponding updates to Pulsar and Planemo in galaxyproject/pulsar#85 and galaxyproject/planemo#356

This is going to fail unit tests because `galaxy.tools.linters.xsd` attempts to `from ..lint import SkipLint`, but `galaxy.tools.lint` has no `SkipLint`. Any idea what that's supposed to be, @jmchilton?

Two things worth noting:
1. This merging was done by hand and I probably broke everything
2. Due to whitespace differences and other things between Galaxy's `galaxy.util` and Planemo's `planemo_ext.galaxy.util`, I did not merge these changes

In the short term, we should try to do a better job of only updating these things in one place and then pushing them one direction. I propose:
- `$PULSAR/pulsar/client` is the canonical source for `$GALAXY/lib/pulsar/client`
- `$GALAXY/lib/galaxy/jobs/runners/util` is the canonical source for `$PULSAR/pulsar/managers/util`
- `$GALAXY/lib/galaxy` is the canonical source for `$PULSAR/galaxy` and `$PLANEMO/planemo_ext/galaxy` (even the linting stuff that originated in Planemo)

In the long term, when Galaxy is a lib (#921), we should not maintain local copies of Galaxy things in either Planemo or Pulsar.

### CODE REVIEW

**Comment by nsoranzo** [comment]
LGTM

> This is going to fail unit tests because galaxy.tools.linters.xsd attempts to from ..lint import SkipLint, but galaxy.tools.lint has no SkipLint.

I think this is a Planemo bug introduced in https://github.com/galaxyproject/planemo/commit/912df026256150bbb3005c1b8462075d26de1062 .

**Comment by jmchilton** [comment]
https://github.com/natefoo/galaxy/pull/1 to touch up invalid linting code that got left in planemo somehow and removed today.

**Comment by jmchilton** [comment]
:+1: after natefoo#1 is merged. Sorry this got crazy @natefoo.

**Comment by natefoo** [comment]
natefoo#1 is merged. You could have just committed directly to my fork. ;P

**Comment by jmchilton** [comment]
Thought I tried to be honest. Anyway thanks for taking care of this.

**Pull request merged**
