### PR TITLE
Replace ``unittest.TestCase`` in API, framework, performance, Selenium and ToolShed tests

### PR DESCRIPTION
**Pull request by nsoranzo**
In API tests, replace no more working `uses_test_history` decorator (because the `history_id` method parameter is interpreted as a fixture) with a real class-level pytest fixture.
As a consequence, replace use of `self.history_id` in API tests because it interferes with the class-level `history_id` fixture.

Also:
- Some type annotations
- Remove now unused `require_new` and `GALAXY_TEST_HISTORY_ID`

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by jmchilton** [comment]
-0 - this seems like a step backward - requires_new was interesting, useful, and actionable metadata and I didn't use GALAXY_TEST_HISTORY_ID daily but I certainly used it a few times a year. We're degrading the tests to switch to a less standard framework. We're trading clear annotations for magic.

**Comment by jdavcs** [comment]
I think passing a "history id" to the test might be not quite transparent in the first place. Each test using `history_id` (via decorator or fixture) has a new `History` created for it - but that's not obvious, one has to search where the `history_id` comes from.

I think making that explicit (i.e., each test creating a new History instance) would make it easier to understand the test. And if we explicitly create the history inside the test, we can say what kind of history we want - in each test - and then we retain the ability to specify, per test, whether we want a new or existing history. (note: we are *not* calling the constructor here, of course!)

I don't think pytest fixtures are magic. But I do think being able to specify new vs existing History per test is a useful feature, even if it's used infrequently, in development only.

What do you think of something like this:

```py
def test_foo(history_factory):
    history_id  = history_factory()
    # body of test here

def test_bar(history_factory):
    history_id  = history_factory(require_new=False)
    # body of test here
```
And in `_framework.py`:

```py
@pytest.fixture
def history_factory():
    def f(require_new=True):
        # call populator's `test_history` here, passing `require_new`, return history_id
    return f
```

**Comment by nsoranzo** [comment]
> I didn't use `GALAXY_TEST_HISTORY_ID` daily but I certainly used it a few times a year.

@jmchilton Setting it manually? I couldn't find a place where it was defined and thought it was unused, especially given the caveats in its description about parallel testing.

> We're degrading the tests to switch to a less standard framework.

pytest seems pretty standard nowadays.

> We're trading clear annotations for magic.

I don't think fixtures are more magical than e.g. dependency injection, no?
Not that I am particularly a fan of either.

@jdavcs I agree, there's a trade-off between transparency and convenience when using fixtures.

> But I do think being able to specify new vs existing History per test is a useful feature

Note that in the previous implementation `require_new=False` would only re-use a history if it its id is manually specified via the `GALAXY_TEST_HISTORY_ID` environment variable.

Regarding your suggested implementation, there is the additional complexity that `dataset_populator.test_history()` needs to be used in a `with` statement. I've given some thoughts about possible solutions to keep the `require_new` functionality, and I've come with the following 2 options:

```python
import contextlib

import pytest


@contextlib.contextmanager
def get_test_history_id(require_new=True):
    """
    This plays the role of `dataset_populator.test_history()`.
    """
    if require_new:
        yield "new"
    else:
        yield "old"


# Solution 1: Add `require_new` parameter to the `history_id` fixture, and use
#             `@pytest.mark.parametrize()` to annotate tests
#
# Needs also a small dummy `require_new` fixture for the default value.
# `@pytest.mark.parametrize("require_new", [False])` is a bit obscure.
# Fixtures are a bit magic, but the `@uses_test_history` wasn't better.

@pytest.fixture
def require_new():
    return True


class Base:
    @pytest.fixture
    def history_id(self, require_new):
        with get_test_history_id(require_new) as history_id:
            yield history_id


class Test1(Base):
    def test_new(self, history_id):
        assert history_id == "new"

    @pytest.mark.parametrize("require_new", [False])
    def test_old(self, history_id):
        assert history_id == "old"


# Solution 2: use `with` statement in each test method.
# Clean, no decorators, no fixtures.
# Adds one level of indentation to the test method code.


class Test2:
    def test_new(self):
        with get_test_history_id() as history_id:
            assert history_id == "new"

    def test_old(self):
        with get_test_history_id(require_new=False) as history_id:
            assert history_id == "old"
```

Please let me know your opinions and if you see other options.

**Comment by jdavcs** [comment]
+1 on fixtures not more magical than DI (although I did find them somewhat too magical to my taste in complex code reuse scenarios, given that we don't import them explicitly and rely on pytest handling that precedence logic instead)

+1 on setting `GALAXY_TEST_HISTORY_ID` manually when needed, in development (I haven't used it, but I can see myself using it)

> @jdavcs I agree, there's a trade-off between transparency and convenience when using fixtures.

I didn't mean that kind of tradeoff: my example *is* a pytest fixture.

> Regarding your suggested implementation, there is the additional complexity that `dataset_populator.test_history()` needs to be used in a `with` statement.

```py
@pytest.fixture
def history_factory(self):
    def f(require_new=True):
        with self.dataset_populator.test_history(require_new) as history_id:
            return history_id
    return f
```
As a side benefit, you can have multiple History objects in one test, if you need them. I used these factories extensively when testing model mapping - I often needed multiple instances of the same class.

> I've given some thoughts about possible solutions to keep the `require_new` functionality, and I've come with the following 2 options:

If we were to choose between these, my vote would go to solution 2: it's clean and simple. I think, simple is good *especially* for test code: we usually don't have tests for our tests, so the simpler the code - the better. Besides, given that we usually don't intend to modify test code, I think even some duplication for the sake of improved comprehension is OK. That said, I think I still prefer an explicit call to a factory (whether implemented as a pytest fixture or not), giving it whatever arguments are relevant for that particular test. I absolutely don't mind if we go with any alternative solution though.

**Comment by jmchilton** [comment]
I am totally when with ``require_new=False`` tests being given a new history - that is why it is called 'required_new' and not 'use_new' or something. Some tests actually require new histories but almost all tests could be given a new history. So I'm not sure the test below makes sense to me:

```
@pytest.mark.parametrize("require_new", [False])
    def test_old(self, history_id):
        assert history_id == "old"
```

It is about the annotation and discovery. Likewise we should have tests annotated if they require new users for instance or an admin user key and the skip_without_tool decorator is useful I think even though we could just throw a skiptest when we encounter problems. The idea is to make progress toward a parameterized suite that deployers or developers can run against Galaxy instances - either production instances or against containerized applications and have a sense of what is being done and what is required and can set flags to run different kinds of tests.

As for the comment about pytest - I agree it is quite standard and we simply disagree about how much we should shield ourselves from it despite that - but I warned you I would grumble about this PR and this is me grumbling. You break stuff I have used and set my long term projects/goals back and I'm going to get sad - that is just the nature of these things I think.

**Comment by jdavcs** [comment]
> It is about the annotation and discovery. ... The idea is to make progress toward a parameterized suite that deployers or developers can run against Galaxy instances - either production instances or against containerized applications and have a sense of what is being done and what is required and can set flags to run different kinds of tests.

+1 on this. I wasn't aware of the big picture here. (I may have missed it in a previous discussion, but, I think, that's exactly the kind of stuff we need to be accessible via the Testing WG project board as a long term issue (or in any other format).)

**Comment by nsoranzo** [comment]
@jmchilton It looks to me that `require_new`/`GALAXY_TEST_HISTORY_ID` has never worked since it was introduced in commit 136255c0ad7a2aca6584f4c1fa3d10ea5e4a632e : `history_id = kwds.get("GALAXY_TEST_HISTORY_ID", None)` tries to get the history id from the keyword arguments instead of `os.environ` , or am I missing something?

**Pull request merged**
