### PR TITLE
Add custom activation email message

### LINKED ISSUE #10607: [Request] modify / personalize the verification email (send to new Galaxy users)
Would it be possible to personalize the verification email that is being send to new users
by letting admins add (optionally) a few lines of text? This can now be done by editing
the body of the the **send_verification_email** function in ..lib/galaxy/managers/users.py 
but this will result in conflicts when updating Galaxy.
Perhaps it could be added as an additional setting in the **galaxy.yml** configuration file?

### PR DESCRIPTION
**Pull request by jdavcs**
Fixes #10607.

Is this sufficient?

### CODE REVIEW

**Comment by hexylena** [comment]
@dickgroenenberg is this fine for your needs?

**Comment by dickgroenenberg** [comment]
Yes, very convenient. Thanks for adding this feature Sergey and Helena.

**Comment by hexylena** [comment]
@ic4f should there be a test for this function? If there was I'd be happy to hit merge.

**Review by jmchilton — APPROVED** [review]

**Comment by ic4f** [comment]
> @ic4f should there be a test for this function? If there was I'd be happy to hit merge.

@hexylena no, it doesn't have a test, and you're right - it should have a simple unit test (same for the enclosing method, `send_activation_email`, which needs several). I've added it to my testing todo list; if you don't mind I'll take care of this later. And you are completely right - little trivial changes like this one are good triggers for refactoring, adding tests, and cleaning up the code base.

**Comment by hexylena** [comment]
@ic4f sure, no worries, no time pressure for sure. I was just remembering marius suggesting a while back that reviewers should ask for more tests and thought it might not be a huge burden here. :)

**Comment by jmchilton** [comment]
Opps - sorry I really didn't even see that comment. I was just going through and clicking merge on stuff that had stalled out and looked fine to me. Happy to also merge a test 😆

**Comment by ic4f** [comment]
I think I also brought up the same point at that discussion - asking for more tests on such PRs. Now, this is embarrassing :) I'll add the test of course! Thanks, @hexylena , @jmchilton

**Pull request merged**
