### PR TITLE
Fix SLURM job re-submission.

### LINKED ISSUE #3289: Ensure clean job working directory if job was re-queued
Want to ensure that the job working directory is always empty when a job starts up.

In our cluster environment, jobs can be requeue by slurm because a higher priority job has bump it off or a node has failed. When the job is re-queue using slurm, it will still have the same job ID and working directory but its <job_directory>/working could have some partial datasets already because it already ran but not to completion.  As such most tools expect to have an empty working/ .

My solution would be to add _rm -rf working/_ at 
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/command_factory.py#L89
i.e
commands_builder.prepend_command("**rm -rf working/ ;** mkdir -p working; cd working")

### PR DESCRIPTION
**Pull request by jmchilton**
Approach from @Takadonet - fixes #3289.

### CODE REVIEW

**Comment by natefoo** [comment]
FWIW this does preclude future checkpointing and job recovery, but I think it's fine for now.

**Comment by jmchilton** [comment]
@natefoo I feel like that largely depends on how check pointing would be implemented. I'm not sure I agree with you.

**Comment by Takadonet** [comment]
Not all tools can be checkpointed.

**Comment by natefoo** [comment]
Is there a common checkpointing system in use by applications that doesn't involve writing out some sort of status? If not the job working directory, where would this go? Anyhow, it was just a heads up to future people.

**Pull request merged**
