### PR TITLE
Managers

### PR DESCRIPTION
**Pull request by carlfeberhard**
- More tests for existing managers
- Removing trans from function signatures (this unfortunately makes those functions that still need trans or a portion of it - like current history - a bit clunkier) in managers and de/serializers
- laying some foundation for an interface over the rbac dataset permissions
- and some foundation for a unified 'contents' interface for dataset collections, histories, and libraries (things that can contain datasets and subcontainers)
- Refactoring of existing managers

### CODE REVIEW

**Comment by martenson** [comment]
I gave it an hour of review and I like it. Test coverage is great, getting rid of trans is awesome. Looking forward to use ContainerManagerMixin.
:+1:

**Comment by carlfeberhard** [comment]
The run_tests part of the travis CI is awesome - thanks for that! (<-- not sarcasm)

**Comment by martenson** [comment]
In ideal world we will have many more tests there soon. :)

**Comment by jmchilton** [comment]
`lib/galaxy/managers` is exactly the kind of module where linting is most useful - we expect it to see a lot of growth and many people modifying the various files. The former means it will be useful to have good tooling watching this module to catch obvious bugs and code smells automatically (https://github.com/galaxyproject/galaxy/commit/03a67d52babd659bf48dc8ee388d2e8880fbdd4b).  The latter means things like git blame and history are important - and these tools are most effective when people don't need to make whitespace/PEP-8 only changes (https://github.com/galaxyproject/galaxy/commit/7291d2f440fe55a29fa414722ebede8b15ac9442, https://github.com/galaxyproject/galaxy/commit/8708cc231bfc301b57fbb3280d97e3dd252994d3).

Obviously each of us has a different set of coding standards we would like to see - and I am vocally unhappy about the current consensus - but I still think it is more useful to have a standard and enforce it than not have the standard or not enforce it.

I am not -1'ing this - but it does make me sad to see `pep8_sources` shrinking instead of growing.

**Comment by dannon** [comment]
Not to hijack the PR, but those pep8, whitespace, and otherwise style-only changes _are_ important to have in isolated commits, and I think they're additionally important to go ahead and get done for all the reasons you list.  If anyone's digging through a file trying to track down a bug I definitely do not want to discourage them from going ahead and cleaning up while they review.  It's fairly trivial to track history bypassing a particular changeset.

**Comment by carlfeberhard** [comment]
Hopefully we can resolve this and get back to writing code.

Leaving aside:
- that we introduced this new process in the middle of a cycle
- I think Galaxy has much more pressing concerns (does it have docs? does it have tests?)
- the script seems to be inflexible about the one thing pep 8 is asking you to be flexible on

Your computer script is not good at enforcing a human metric: readability. Readability is what pep8 is for.

Unit tests: awesome! Functional tests? outstanding. If you want to check unused variables, scoping errors, deprecated functions - fine and useful. Python 3 safety? Yes, please.

Automated style _warnings_/_notifications_? Ok. Demerits? Whatever. I'd rather take non-syntax suggestions and talk about nits with a human.

So let's move this to the human space: Humans: Is my code really unreadable? Are you really arguing that the vertical alignment of those functions make the code less readable? That stacking two logically-joined if statements so that the subject lines up and the operator is forward is less readable than on a single line? 

Or are you arguing that it doesn't matter because (as your script points out) it violates pep8?

Is readability (and style) subjective?
Perhaps (- I'm not sure vertical alignment is subjective). 

Should a script be the arbiter for this subjective problem?
A script that blindly adheres to pep8 (and not even our project pep8) isn't a good idea IMO. Your script will not apply [common sense](http://bugs.python.org/msg193909) and it should not be a(n unsupervised, automated) gatekeeper for pull requests.

The pep20 linter in my head is erroring on the pep8 linter in your repo: "Automating strict adherence to pep8 is a violation of pep8."

**Comment by blankenberg** [comment]
Yeah, I can't really see a good argument for removing files from pep8_sources. Seems like that is a lot like deleting a test because it fails and you want to see green everywhere. 

If there is an issue between the linting and what we have established as the coding styles for the project, the linter should be fixed, we shouldn't stop 'testing'.

**Comment by martenson** [comment]
Ignore E203 and E128 (and any other controversial ones) for now until we have a team-wide discussion?

lib/galaxy/managers/datasets.py:521:33: E203 whitespace before ':'
lib/galaxy/managers/datasets.py:532:14: E128 continuation line under-indented for visual indent

https://travis-ci.org/galaxyproject/galaxy/jobs/56934033

**Comment by carlfeberhard** [comment]
Dan: that's a false comparison. This isn't a unit test, functional test, integrative test, or any other actual test - it's linting. It's not deletion - it's a change on the code I had already started working on when someone else added it to the linting. It's not green - or - red - it's me doing my job - or - it's automated failure of a subjective rule on a non-syntactic and still readable style choice. 

Code is less effected by a change there than the 30+ tests I added in the actual pull request. If _someone  else_ wrote a 'test' that checked a subjective, non-computational aspect of some code you'd written and it was preventing you from doing your job - I would hope you would change it (or at least try).

At any rate:
If people would rather I pull the pep8_sources change into a different pull request (and out of it's context) - I'm fine with that. If they would rather I change the setup.cfg file - I'm down with that, too.

**Comment by jxtx** [comment]
> @carlfeberhard Readability is what pep8 is for

Oh that I only have +1 +1s to give.

> @martenson Ignore E203 and E128

+1, I think this is a reasonable solution and is consistent with our current best practice guidelines. 

> @jmchilton but I still think it is more useful to have a standard and enforce it than not have the standard or not enforce it

+1, as long as the tooling reflects our actual agreed on standard.

**Comment by dannon** [comment]
@carlfeberhard I'd prefer changes to linting be in a separate PR.  I'll also +1 the suggestion to just relax those two particular rules.  (Separate PR submitted, apparently 3 of us were trying to make it at the same time :)

Can you revert the changes to pep8_sources?

**Comment by carlfeberhard** [comment]
@dannon done.

**Comment by martenson** [comment]
still :+1:

**Comment by dannon** [comment]
-1 (for now, until we fix the errors revealed in the build I just reran)

**Comment by jmchilton** [comment]
Ugh - I did that thing you complained about where I changed the criteria for PRs while you were in the middle of work. I thought I was being helpful, I certainly didn't mean to be a stubborn ass - but I may just be beyond redemption. I owe you an additional beer for sure @carlfeberhard.

**Comment by dannon** [comment]
To be fair, F821 was definitely in (hopefully) everyone's criteria for reviewing a PR previously ;)

**Comment by dannon** [comment]
(did not mean to close)

**Comment by dannon** [comment]
Changing my -1 to a +1, looks good now :)

**Pull request merged**
