### PR TITLE
Fix deferred dom removal

### PR DESCRIPTION
**Pull request by guerler**
This fix improves the front-end performance. Thx for the issue description during the meeting @blankenberg.

### CODE REVIEW

**Comment by martenson** [comment]
I like where this is going. Have you measured any difference locally?

**Comment by guerler** [comment]
Yes, you can test this by triggering artificial clicks while observing memory profiles. Here is an example patch: https://gist.github.com/guerler/9f45a3fdc6ef4c7b6e26 and here a profile using this fix:
form_performance.

**Comment by dannon** [comment]
Nice!  Works for me.

**Comment by martenson** [comment]
@guerler I tested and it looks like it does not grow number of DOM nodes forever anymore, which is great. Feels a bit faster too. Good job!

**Comment by guerler** [comment]
@martenson Thx, that makes sense. The full benefit of this will come into play once we improved the client side logging. Then the entire memory should clear properly just as in the example above.

**Pull request merged**
