### PR TITLE
Wrap conditional test parameters

### LINKED ISSUE #1712: Conditional on boolean: bool-expression is returned instead of param's (true/false)value
When I run the following tool:

```
<tool id="conditional_bug" name="test_bug" version="g0">
    <description>Shows bug in conditional</description>
    <command><![CDATA[
        echo "1. check" > $output ; 
        echo "2. ${conditional.param1a}" >> $output ; 
        echo "3. ${conditional.param1b}" >> $output ; 
        echo "4. ${param2a}" >> $output ; 
    ]]></command>
    <inputs>
            <conditional name="conditional">
                <param name="param1a" type="boolean" truevalue=" --arg1" falsevalue="" label="arg1 (as conditional)" checked="True" />

                <when value=" --arg1">
                    <param name="param1b" type="hidden" value="pass" />
                </when>
                <when value="">
                    <param name="param1b" type="hidden" value="no pass" />
                </when>
            </conditional>

            <param name="param2a" type="boolean" truevalue=" --arg2" falsevalue="" label="arg2 (as plain param)" checked="True" />
    </inputs>
    <outputs>
        <data format="tabular" name="output" label="test" />
    </outputs>
</tool>
```

I get the following output:

```
1. check
2. True
3. pass
4. --arg2
```

The output I expected:

```
1. check
2. --arg1
3. pass
4. --arg2
```

A `<param type="boolean" />` returns the boolean expression if it is within a conditional while it returns the truevalue or falsevalue when it is not within a conditional. I am not sure if this is a feature or a bug, but it complicates using a boolean as conditional because you need to specify the truevalue and falsevalue both in the param as well as the command tag:

```
    <command><![CDATA[
        echo "1. check" > $output ; 

        #if $conditional.param1a
            echo "2. --arg1" >> $output ; 
        #else
            echo "2. " >> $output ; 
        #end if

        echo "3. ${conditional.param1b}" >> $output ; 
        echo "4. ${param2a}" >> $output ; 
    ]]></command>
```

The `when` case seems to use the truevalue and falsevalue correctly because param1b gets printed correctly.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #1712.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Hey @guerler ,

That was quick. It solved my problem :+1: , let's hope it doesn't break anything else and the PR get's in.

Thanks!

**Comment by blankenberg** [comment]
While this seems like the correct thing to do, it is going to break a whole bunch of tools.

**Comment by jmchilton** [comment]
@blankenberg - @guerler and I were exploring overriding `__eq__` to maintain backward compatibility on exressions like `$cond.param == "moo"` for select params, reviewing #1712 however it looks like we need override truthy-ness also.

https://github.com/galaxyproject/galaxy/pull/1688 introduces a new tool attribute `profile="16.04"` - when it is set tools assume a bunch of new and more reasonable defaults. If we can't get this fix to work in a satisfactorily backward compatible way we apply conditionally to just new profiled tools.

**Comment by guerler** [comment]
Thx everyone. I have incorporated @jmchilton's idea (https://github.com/guerler/galaxy/pull/9) and added similar checks to the InputValueWrapper. ping @blankenberg.

**Comment by jmchilton** [comment]
@guerler How about tools with `#if $cond.param` and boolean parameters? Does this change their behavior? I feel like we could fix that pretty easily also.

**Comment by guerler** [comment]
I assumed that https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/wrappers.py#L30 handles this.

**Comment by jmchilton** [comment]
Sounds good to me - I haven't tested it, I don't know if that would work or not.

I'm :+1: on this I guess, I can imagine some things that could go wrong but I don't suspect any tools would be setup in these ways.

**Comment by guerler** [comment]
Ok, I can test it later and then merge it, unless there are remaining concerns.

**Comment by blankenberg** [comment]
Previously working comparisons could now fail, since these param values are now being mutated (sanitized) when `str`ed, whereas before they would not have been.  I do not have an example tool off the top of my head, however.

**Comment by yhoogstrate** [comment]
> @guerler How about tools with #if $cond.param and boolean parameters? Does this change their behavior? I feel like we could fix that pretty easily also.

The old way of using boolean conditionals seems to still work the same way:

```
<tool id="conditional_bug" name="test_bug" version="g0">
    <description>Shows bug in conditional</description>
   <command><![CDATA[
        echo "1. check" > $output ; 

        #if $conditional.param1a
            echo "2. --arg1" >> $output ; 
        #else
            echo "2. " >> $output ; 
        #end if
    ]]></command>
    <inputs>
        <conditional name="conditional">
            <param name="param1a" type="boolean" truevalue=" --arg1" falsevalue="" label="arg1 (as conditional)" checked="True" />

            <when value=" --arg1">
                <param name="param1b" type="hidden" value="pass" />
            </when>
            <when value="">
                <param name="param1b" type="hidden" value="no pass" />
            </when>
        </conditional>
    </inputs>
    <outputs>
        <data format="tabular" name="output" label="test" />
    </outputs>
</tool>
```

if boolean is set to `True`, it gives:

```
1. check
2. --arg1
3. pass
```

if boolean is set to `False`, it gives:

```
1. check
2.
3. no pass
```

**Comment by jmchilton** [comment]
Great, thanks for the testing @yhoogstrate. I clarified @blankenberg's comments with him offline and he made it clear he thinks this should be merged he is just warning of potential problems - I had read the comments initially as more of an attempt to stop the PR.

**Comment by guerler** [comment]
Yes, and his warnings are definitely reasonable. Thanks for all the comments.

**Pull request merged**
