### PR TITLE
Remove PlantTribes datatypes that are no longer needed

### PR DESCRIPTION
**Pull request by gregvonkuster**
I just released version 1.0.3 of the PlantTribes tools to the MTS.  I worked with the author of the underlying packages for this release to simplify them so that most of the custom PlantTribes datatypes are no longer needed.  I'm not quite sure of the process for deprecating custom datatypes in the Galaxy code, so please let me know if more is needed here.

### CODE REVIEW

**Comment by mvdbeek** [comment]
This breaks reproducibility for users that have been using tools that requires these datatypes. I'm not sure we ever removed a core datatype. Are these conflicting with the new datatypes (if there are any) ? Would it be enough to clearly mark them deprecated?

**Comment by martenson** [comment]
ping @gregvonkuster

**Comment by gregvonkuster** [comment]
I'm fine with whatever process the core team has defined for deprecated datatypes.  These datatypes in particular have so far been used by a very small community, so the likelihood that there will be problems if they are completely removed is small.  Its fine to keep them in the code base if this is the process defined for deprecated datatypes like this.  Please just let me know if there is something I should do.

**Comment by martenson** [comment]
@mvdbeek what do you think? I am fine leaving them in.

**Comment by bgruening** [comment]
@martenson we could comment them out for the next release and remove them in the next?

**Comment by mvdbeek** [comment]
Either way is fine for me (In principle I'd like all datatypes to be around forever, but if no-one uses them it's OK to remove them), but this is setting a precedent we should think about.

**Comment by gregvonkuster** [comment]
Any decision is fine with me as well.  Maybe it would help to define or clarify an approach for supporting tools that use these custom datatypes.  In this case, these datatypes are required only for versions ```1.0.0, 1.0.1, 1.0.2``` of the various PlantTribes tools.  Is it acceptable to require a Galaxy instance that is running a version of Galaxy that no longer includes support for these datatypes to upgrade the tools to version 1.0.3 or later?

**Comment by bgruening** [comment]
Let's comment them out and add a explanation to it for a few releases until we remove them.
@gregvonkuster can you do that and resolve the merge conflict? Thanks!

**Comment by gregvonkuster** [comment]
Closing this due to new PR here: https://github.com/galaxyproject/galaxy/pull/5254

**Pull request closed without merging**
