### PR TITLE
Fixing button width on Composite upload dialog #2591

### PR DESCRIPTION
**Pull request by sszakony**
Fixed by adding a width parameter for id source in upload.less. From my testing this has not caused any changes elsewhere.

### CODE REVIEW

**Comment by martenson** [comment]
I believe we need a more specific selector. Given how we construct base.css this will affect everything with `id="source"` in the whole Galaxy webapp.

**Comment by guerler** [comment]
Thanks for the fix @sszakony, I think it is overall the right thing to do. I was planning to refactor the uploader by next week and will integrate the fix modifying it with @martenson suggestion to use local class specifiers.

**Comment by dannon** [comment]
Yep, I agree we should refine the selectors in this dialog a bit on this as a followup project -- was saying the same on IRC when we were working through this, this afternoon.  As it is, this seems to work well and I haven't found this to actually collide anywhere, so I'll go ahead and merge it; thanks for following up on the extra improvements @guerler!

**Comment by guerler** [comment]
Sounds good.

**Comment by martenson** [comment]
The problem is not that it collides now, problem is that if anybody puts id of `source` on any element within Galaxy in future it will inherit this property. The rest of the .less file seems well designed with `.upload` prefix to every selector.

**Comment by guerler** [comment]
Right, but its fine. If it does not collide now and I integrate it in the upcoming revision of the upload dialog next week, it will never cause issues.

**Comment by martenson** [comment]
Got it, just wanted to make sure we are on the same page, thanks folks.

**Comment by dannon** [comment]
@martenson Right, I get that, I'm the one that brought it up as an issue earlier on IRC.  I'm confident @guerler will take care of this before it's an issue down the road (and it is not one now).

**Comment by sszakony** [comment]
Thanks guys. Appreciate your support and input. :)

**Pull request merged**
