### PR TITLE
[STABLE] Import safe_dumps from galaxy_utils to properly set metadata for interva...

### PR DESCRIPTION
**Pull request by dannon**
...l files.

Cherry-pick of the json fix from @mvdbeek.

This bug showed up in the backported 50d65f45, so I will merge the change forward as necessary once this is approved.

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
:+1:

**Comment by dannon** [comment]
Thanks guys.  I'll merge this forward now.

**Comment by dannon** [comment]
Merged all the way forward to dev.

**Pull request merged**
