### PR TITLE
Do not select first value as default if select value is optional

### LINKED ISSUE #3421: Tool form defaults are changing in repeats elements
Hi Aysam,

we have a strange case. We have some select params and all of them are `optional="True"`. These params are in a repeat. The first repeat element everything is fine. The second repeat we get filled select boxes. So the `nothing is selected` option is not choosen. This yields to wired unexpected results.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #3421. This PR fixes a minor redundancy and a related bug. There is a second copy of `get_initial_value` inlined into the `to_dict` caller of some basic parameters. For the `SelectToolParameter` this copy is inconsistent. It picks the first option by default even if the paramater is optional while its `get_initial_value` caller initializes optional values with `None`.

### CODE REVIEW

**Comment by bgruening** [comment]
@guerler shouldn't this go to 17.01 as a bugfix?
Thanks for fixing it!

**Comment by bgruening** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by bgruening** [comment]
@guerler this should also go to 17.01, isn't it?

**Comment by guerler** [comment]
Possibly but since this is an old minor issue, I would prefer to push it to dev first.

**Review by nsoranzo — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @guerler!

**Comment by guerler** [comment]
Thanks for reporting and reviewing it.

**Pull request merged**
