### PR TITLE
add HTML description meta tag

### LINKED ISSUE #15286: Add meta description tag to HTML
It would be nice to have an informative `description` meta tag in Galaxy's HTML head. In Google search Galaxy is currently looking like this:

image
 
Maybe something like this?
```html
<meta name="description" content="Galaxy is a web analysis platform for life science research. Thousands of tools and community workflows are available to analyse your data.">
```

### PR DESCRIPTION
**Pull request by neoformit**
Resolve https://github.com/galaxyproject/galaxy/issues/15286.

This PR adds hard-coded meta `description` tags for pages that Google seems to like showing in search results.

e.g.
```html
<!-- default -->
<meta name="description" content="Galaxy is a community-driven web-based analysis platform for life science research.">
```
```html
<!-- /login/start/ -->
<meta name="description" content="Log in to Galaxy to get access to more tools and resources.">
```
```html
<!-- /workflows/ -->
<meta name="description" content="Galaxy Workflows facilitate rigorous, reproducible analysis pipelines that can be shared with the community.">
```

- The content is just a suggestion - feel free to request changes (suggested limit is ~150 chars)
- We might want to inherit these descriptions from `galaxy.config` so admins can set their own descriptions

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by hexylena** [comment]
> We might want to inherit these descriptions from galaxy.config so admins can set their own descriptions

definitely want to do that, especially for e.g. french deployments.

**Comment by dannon** [comment]
This is a great idea, but there's a bit of a hitch in routing.  We don't re-serve the html from the server and the mako doesn't rerun when you navigate from home -> workflows, for example, so the description would be out of date quickly.

What we should probably do longer term is use something like [vue-meta](https://vue-meta.nuxtjs.org/) to set this at a component and/or route level.

For now, maybe we pare this back to the single static tag line you have as the default and get it in?  Adding proper meta handling (for title, too!) would be a great project for next cycle.

**Comment by ElectronicBlueberry** [comment]
The html does not need to be re-served in this case, as crawlers and embed previews do not navigate in such a manner. This approach works fine, but I agree that it should be configurable.

For `vue-meta` to handle this task, we would need to switch from mako to a node-based front-end server with ssr and client-side hydration, since for this use-case client-side javascript can't be used. (Using this approach has a whole slew of other benefits, but that is beyond the scope of this PR.)

**Comment by dannon** [comment]
@ElectronicBlueberry Argh, I thought modern crawlers actually ran js to the first contentful, but I guess if we're seeing the javascript warning in the search results that's not the case.

In any event, I'd err on the side of setting the single, standard, untranslated route for now, with the default description.  Or, we can bump this to next cycle to iterate on it more.

**Comment by ElectronicBlueberry** [comment]
> (edit: https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics#titles-and-snippets -- looks like it actually should be running the JS here, might be something else going on preventing it that we can just fix, then use vue-meta or similar)

Interesting, haven't heard of this before. Searching for the noscript content being displayed leads to https://stackoverflow.com/questions/37278462/noscript-text-is-appearing-in-google
which claims google often doesn't render a page.
Either way I would not rely on it, as meta descriptions are used in more scenarios than just google search results. E.g. Link previews

**Comment by hexylena** [comment]
> which claims google often doesn't render a page

I somewhat suspect they have timeouts on loading/rendering JS, and if it doesn't happen in that time limit, they'll just render the HTML page. And especially for a website as heavyweight as galaxy, if there's a timeout, we assuredly hit it with our multi MB bundle.

**Comment by dannon** [comment]
It may be a timeout, that's a good call.  I think as we continue to modernize the client and trim down the initial page load we can likely get to a point where it should be an option that'll work, but we should dig into this more, separately. 

I'm going to go ahead and merge this change in for now and we can iterate on it more (with translations and/or a different mechanism) next cycle.

**Comment by neoformit** [comment]
Haha you all teased out the same thought process I went through when I wrote this. Thanks for the merge @dannon. I guess we can add to galaxy config in another PR.

**Comment by hexylena** [comment]
> Haha you all teased out the same thought process I went through when I wrote this. 

good reason to write it in the PR next time ;)

**Pull request merged**
