### PR TITLE
[20.09] Pathbar race bugfix

### PR DESCRIPTION
**Pull request by OlegZharkov**
So, even after mounted callback, props not always seem to be available, thus we miss pathbar in data library.
This PR will fix it. I would also appreciate if someone experienced like @dannon or @guerler would take a look on [pathbar](https://github.com/galaxyproject/galaxy/compare/release_20.09...OlegZharkov:pathbar-fix?expand=1#diff-421675cbac7b46f4d74385828695ff4695b8bd2fa27ccb82fa5d435123e9e46fR230)

### CODE REVIEW

**Comment by bgruening** [comment]
@Nerdinacan maybe you can look at this one? :-)
Oleg is eager to learn I'm sure!

**Comment by dannon** [comment]
I took a quick look a few minutes ago and I wasn't sure why we aren't just using a regular vue component with props that'll be reactive?  Is this pathbar used anywhere else?

**Comment by OlegZharkov** [comment]
> I took a quick look a few minutes ago and I wasn't sure why we aren't just using a regular vue component with props that'll be reactive? Is this pathbar used anywhere else?

that pathbar is legacy backbone code. Do you want to wrap it in a separate Vue component?

**Comment by Nerdinacan** [comment]
@OlegZharkov @bgruening 
I'm happy to take a peek, when you've got something together.

Throw me a message on gitter if you get impatient.

**Comment by mvdbeek** [comment]
The linter is complaining about this:
```
/home/circleci/repo/client/src/components/LibraryFolder/TopToolbar/FolderTopBar.vue
    8:17  error    Custom elements in iteration require 'v-bind:key' directives  vue/valid-v-for
```

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@OlegZharkov Thanks for indulging my nudges here, this looks great now.  I'll test it again locally and will merge it on in.

**Comment by OlegZharkov** [comment]
> @OlegZharkov Thanks for indulging my nudges here, this looks great now. I'll test it again locally and will merge it on in.

I asked for the review, so thanks a lot for looking into this so quick!!

**Review by dannon — APPROVED** [review]

**Pull request merged**
