### PR TITLE
Add parenthesis to argument name search

### PR DESCRIPTION
**Pull request by guerler**
Addition to https://github.com/galaxyproject/galaxy/pull/346.

### CODE REVIEW

**Comment by hexylena** [comment]
+1

**Comment by bgruening** [comment]
@guerler any reason for this change? There are a lot of tools that uses a schema without parenthesis: https://github.com/galaxyproject/tools-devteam/blob/master/tools/tophat2/tophat2_wrapper.xml#L188

**Comment by hexylena** [comment]
@bgruening I requested it https://github.com/guerler/galaxy/commit/d2da9d9a17ef7f0d1839c21233b078b76cb6afd7#commitcomment-11686506

**Comment by hexylena** [comment]
Maybe we should PR the devteam repo to standardise against http://galaxy-iuc-standards.readthedocs.org/en/latest/best_practices/tool_xml.html#parameter-help

**Comment by bgruening** [comment]
This means that with the next release many of the devteam tools will have two arguments displayed, isn't it? PR all tools will not help much if you have old tools around.

**Comment by hexylena** [comment]
Do we keep making it more complex? Do we check for the devteam special case? If they're upgrading their galaxy to get this feature, why aren't they upgrading their devteam tools?

``` javascript
if ( options.argument && ( options.help.indexOf('(' + options.argument + ')') == -1 || options.help != options.argument) ) {
  ...
}
```

**Comment by hexylena** [comment]
(You raise a good point though, having a doubly displayed value isn't very nice, but I think it's the lesser of two evils)

**Comment by bgruening** [comment]
This has nothing to do with upgrading tools. You have all tools with all revisions. It's just a cosmetic change, if you think this is correct, this is fine with me :)

**Comment by hexylena** [comment]
Ah, true. I don't think my users know or care to look for historical versions of tools. I'll open a PR shortly addressing devteam tools :)

(Gee I'd love statistics on that...what % of jobs are run with latest tool vs old version. Xref https://github.com/erasche/galactic-radio-telescope/issues/1)

**Pull request merged**
