### PR TITLE
Collection Operator tools

### PR DESCRIPTION
**Pull request by Takadonet**
Initial implementation of "Merge Collection" Tool takes two list collection and combined them together into a single unified list. Tool provides options on how to deal when element_identifier aka name are found in both list.

Tests can be ran with planemo from the working directory of galaxy/lib/galaxy/tools . One side note that galaxy/test-data has to be soft-linked in the tools directory to work.

Planning to do a few more different collection operators but want more feedback before writing them.

ping @jmchilton

### CODE REVIEW

**Comment by martenson** [comment]
Looks great! Do I understand it correctly that it has two 'modes' when it encounters duplicates - either suffix it or ignore the second occurrence?

**Comment by Takadonet** [comment]
Three Modes:

Default is the suffix route i.e '__1 ' , '__2', etc...
Next mode would be to take the first instance found.  i.e keep item from first list
Last would be to take the second instance found. i.e keep item from second list

I can see that the if , elif statement  is little confusing.

**Comment by martenson** [comment]
Which means that  `if dupl_actions  not in ['suffix', 'first'] == True` it will only keep the second item? Would you consider refactoring this to be more explicit?

**Comment by Takadonet** [comment]
Sure, one second please.

**Comment by Takadonet** [comment]
@martenson changes made

**Comment by martenson** [comment]
👍

**Comment by nsoranzo** [comment]
@Takadonet Can you fix the flake8 errors in https://travis-ci.org/galaxyproject/galaxy/jobs/151333451 , please?

**Comment by Takadonet** [comment]
@nsoranzo Changes made to conform to flake8 standard. Waiting for CI build now.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by nsoranzo** [comment]
Would it make sense to extend the tool to merge more than 2 collections (using `multiple="true"`)? Not sure how that would affect the de-duplication modes.

**Comment by Takadonet** [comment]
I am starting with baby step before extending the tool capability. I am currently working on that it can accept two List:paired and create an unified list:paired collection.  Ability to merge more then 2 collection is next on my list.

**Comment by nsoranzo** [comment]
@Takadonet That's a good approach! I'm just worried that the `first` and `second` modes you have implemented to deal with the duplicated datasets will not be applicable in the >2 scenario.

**Comment by jmchilton** [comment]
The `type="data_collection"` parameter doesn't yet respect `multiple="true"` yet anyway I don't think.

I'd probably add a `collection_type="list,list:paired"` to this parameter - merging say two `list:list` is fun but requires greater complexity in the handling duplicate ids section.

If we are adding a suffix - can we add a text parameter that templatizes the suffix - e.g. default might be "__#"? With a little help describing that "#" will be replaced with the list number of the inputs (e.g. 1 for the first list and 2 for the second).

**Comment by Takadonet** [comment]
@jmchilton By templatizes  text parameter, do you mean like your flatten Collection tool where you can pick your identifier character? So someone could use '--#' instead of default '__#' ?

**Comment by jmchilton** [comment]
@Takadonet - yup!

**Comment by Takadonet** [comment]
@jmchilton Added ability to change suffix parameter to the same as Flatten Collection tool.

**Comment by Takadonet** [comment]
@galaxybot test this

**Comment by Takadonet** [comment]
Looks like I am not special enough for galaxybot . All well

**Comment by martenson** [comment]
@galaxybot test this

**Comment by Takadonet** [comment]
It passed! YAHOO!

**Comment by Takadonet** [comment]
Since no one merged this yet into dev. Decided to change this merge into a WIP and add more tools/changes.
1. Added new operator : appendCollectionTool . Allows users to append one or more data-sets into an existing list collection. Comes with same name conflict tools as Merge Collection.
2. filter_failed_collection.xml now has the ability to filter out failed paired elements from a list:paired collection. If one or both dataset failed, both will be thrown out. Before it allowed only list.

**Comment by jmchilton** [comment]
@Takadonet - Sorry for not moving on this - I've sat down a few times to look at it but I want some small modifications. I'll try to find some time this week to spell them out or open a PR against your PR.

I did want to say that I don't like the addition of an appendCollectionTool - I'd prefer collections to be immutable (write once). This eliminates concurrency problems, keeps the model for workflow extraction simpler, and matches what the GUI expects I believe. Is appending the collection something you really feel you need?

**Comment by Takadonet** [comment]
After thinking about it with my end user,  AppendCollectionTool could be eliminates as long as mergeCollection stays in.

If you are planning a PR against my PR, my next modification would be to allow for list:paired in mergeCollection.

**Comment by Takadonet** [comment]
Removed AppendCollectionTool and added ability for MergeCollection to work on list:paired

**Comment by jmchilton** [comment]
I've opened a PR to enhance the merge collections tool - https://github.com/Takadonet/galaxy/pull/1. I'll merge this if you merge mine :smile:.

**Comment by Takadonet** [comment]
Sounds like a fair deal.

**Comment by jmchilton** [comment]
The travis test failures affect dev also - must have been a linter update over the weekend.

**Comment by martenson** [comment]
thanks @Takadonet !

**Comment by jmchilton** [comment]
Agreed - thanks a ton @Takadonet. This is awesome work and sorry for the delay in getting it merged.

**Pull request merged**
