### PR TITLE
[23.0] test and fix for is_of_type problem

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref https://github.com/galaxyproject/tools-iuc/issues/5163

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by nsoranzo** [comment]
Fix part one is enough, removing the `.tool` would be wrong. I was about to push some extra type annotations here and ~ the same fix.

**Comment by bernt-matthias** [comment]
> hope that's OK!

100%

> removing the .tool would be wrong

out of curiosity. Why? :)  Haven't found it used...

**Comment by bernt-matthias** [comment]
@mvdbeek can you run this against IUC?

**Comment by mvdbeek** [comment]
It looks like there's a bunch of things in there not needed for the fix, can we isolate this?

**Comment by nsoranzo** [comment]
Sure, I can open a PR against dev for the tool annotations.

> I am in particular not convinced we should place those asserts.

These are part of the type annotations, in each case where one was added the code would fail with an AttributeError some lines below if the tested object was None.

**Comment by nsoranzo** [comment]
Superseded by #15871 , thanks @bernt-matthias !

**Pull request closed without merging**
