### PR TITLE
Load steps in background, show progress bar upon workflow execution, avoid nested tables

### PR DESCRIPTION
**Pull request by guerler**
This PR started off as lazy loading procedure for the new run workflow form, although this significantly improved the load times (see also jsfiddle demo below), we decided to follow up on a different strategy which might allow us to keep appending every step form to the browser. This would have the benefit that the scrolling behavior is more natural. As a step towards that goal, this modified PR places the step loading procedure into the background and if necessary completes it upon workflow execution. This way the form is instantly responsive. Showing the progress bar upon start up is uneccessary. This PR also enhances the tool form building process. Previously tool form parameters were listed in nested table views. Now the tool parameters are appended directly to a regular div, removing the overhead of using an uneccessary and separate backbone view for each subsection.

### CODE REVIEW

**Comment by dannon** [comment]
I'm impressed (and surprised) that it's that much faster, nice!  I didn't realize rendering the forms was that expensive, and I'd have expected the overwhelming majority of the time would be the requests.

Two problems I see here, though:

As it is, if the user grabs the scrollbar and scrolls that way, or uses keyboard pgup/pgdn/etc, the refresh is never called so the later steps never get displayed.  I don't think we should be using (at least not exclusively) mousewheel/dommousescroll events like this.  Have you checked out the scroll detection I wrote for the tabular dataset display way back?  It works well, maybe we can generalize that and use it in multiple contexts.

When you run a workflow without scrolling down and forcing the entire thing to load, if it has validation errors or needed values missing it no longer focuses those errors if they're below the fold.  To the user, it appears like you hit execute, and nothing happens.  When I scroll down and force the form to display all the workflow steps, I do see them eventually, but it's not intuitive that there's an error at first without the auto-focus-on-errors motion.

**Comment by dannon** [comment]
So, during the 'preparing' phase, can we load all steps and only render elements that need to be visible, and then relinquish the lock on execution?  And after that, just keep on rendering incrementally from the already loaded modules instead of waiting on the user to scroll?

**Comment by guerler** [comment]
Good point. We should definitely add support for pgup/pgdn and others. I will checkout the tabular display view and get back to you on this. I am surprised that the validation errors are not focused properly if the user has not manually scrolled to the corresponding form tho. I added support for it (https://github.com/galaxyproject/galaxy/pull/2720/files#diff-9ff1e180bce47724e6980063b159add2R364) and it worked for me in a couple test cases. I will retest it and fix it if something is not right. Other than that I agree with your last comment and have a similar line of thought but I would want to leave it for a followup PR. Btw the 1/3 is in relation to the time after the api has responded. So yeah, your intution is not necessarily wrong. Quite a bit of time is spend for the request itself before the rendering starts in the first place, particularly if several hundred datasets are in the history. I have updated the above PR details to clarify this. Thanks a lot @dannon.

**Comment by dannon** [comment]
Is the last change working as intended?  It appears to be instantaneous, which sorta supports what I was trying to figure out in those profiles earlier, that the dom addition part is not what the problem was.

**Comment by guerler** [comment]
Here is the jsfiddle which demonstrates the behavior we worked on for completeness: https://jsfiddle.net/guerler/0qccf7uw/. The time difference is a consequence of continuously flushing the browsers rendering queue after each append, triggered before the timeout call.

Copy of the jsfiddle in case it disappears from the remote server:
`var useappend = true; var $d = $( '#target' ); var i = 0; var s = new Date(); var f = function() { useappend && $d.append( '<b>.</b>' ) }; var r = function() { if ( i++ < 1000 ) { setTimeout( function() { f(); r(); }, 0 ); } else { alert( ( new Date() ) - s ); } } r();`

**Comment by dannon** [comment]
+1, looks great to me.

**Comment by guerler** [comment]
Thanks a lot for working on this @dannon. It was extremely helpful.

**Pull request merged**
