### PR TITLE
Fix py34-lint tox test

### PR DESCRIPTION
**Pull request by nsoranzo**
Broken with the merge of #2269.

### CODE REVIEW

**Comment by martenson** [comment]
it seems TS test were also broken by the same merge :/

**Comment by martenson** [comment]
thanks @nsoranzo !

**Comment by nsoranzo** [comment]
@martenson @davebx Yes, `get_updated_changeset_revisions_from_tool_shed` method was removed from `lib/tool_shed/util/shed_util_common.py` but not added to `lib/tool_shed/util/metadata_util.py` . I'm going to fix that in other PR if that's ok for you.

**Comment by martenson** [comment]
@nsoranzo that is very fine :)

**Pull request merged**
