### PR TITLE
[24.0] Fix vanishing connections on workflow upgrade

### LINKED ISSUE #17986: Connections vanish when upgrading a subworkflow
**Describe the bug**
When I upgrade a subworkflow, all the connections in the workflow disappear. They are still there but invisible. I have to reload the page to make them reappear.
The bug  doesn't happen the very first time it upgrades after the creation of the workflow, but every subsequent time.

**Galaxy Version and/or server at which you observed the bug**
Observed on main and on eu

**Browser and Operating System**
Operating System: macOS
Browser: Chrome and Safari

**To Reproduce**
1. Edit https://usegalaxy.org/u/delphinel/w/vanishing-connections
2. Click on 'Test Subworkflow'
3. Upgrade the subworkflow

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/11195061/6bf174cf-a9e7-4f41-8f7e-e679b8004439

**Additional context**

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
fixes  #17986

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Any clue why this only happens for the refactoring response ?

**Comment by ElectronicBlueberry** [comment]
> Any clue why this only happens for the refactoring response ?

The other method (`_loadCurrent`) has the store reset before the data fetching, which adds a delay in between the reset and `fromSimple` calls. Would the API response be instant, they would also disappear there.

**Comment by mvdbeek** [comment]
Should we move the nextTick call into the resetStores function then ?

**Comment by mvdbeek** [comment]
And can you target 24.0 ?

**Review by mvdbeek — APPROVED** [review]

**Pull request merged**
