### PR TITLE
Open tool executions in a different tab from admin/tool_lineage, inst…

### PR DESCRIPTION
**Pull request by dannon**
…ead of loading galaxy(whole) within the tab

### CODE REVIEW

**Comment by dannon** [comment]
This resolves #2854.

I still don't like, though, how we display _many_ versions in the display, yet if those aren't installed, we link to whatever is available without any notification it isn't the right version.  (new ticket, probably, but maybe it's just me)

**Comment by nsoranzo** [comment]
> I still don't like, though, how we display many versions in the display, yet if those aren't installed, we link to whatever is available without any notification it isn't the right version.

@dannon Maybe those versions could be represented as normal text (no link).

**Comment by dannon** [comment]
@nsoranzo Yeah, that's actually the intended behavior at https://github.com/galaxyproject/galaxy/pull/2862/commits/633f958e1b6f2179264cdad06d9cda8cc13d0e93#diff-8d95f5bce7db0244fa94512d5dfb9fcdR457, but now that I look at it more the logic for `toolbox.has_tool` w/ `exact=True` is broken.  I might as well fix that while I'm digging around here.

**Comment by dannon** [comment]
@nsoranzo The latest commits fix what's actually a much larger bug than just this galaxy-in-frame issue, and should make it work correctly.

**Comment by dannon** [comment]
Looks like the failure is unrelated, was just a timeout for collections?

**Comment by jmchilton** [comment]
Two nice fixes, thanks @dannon. The failing test passes for me locally - I don't know if it is a timeout problem or a random job failure.

**Pull request merged**
