### PR TITLE
[16.10] Fixes for deleting histories

### PR DESCRIPTION
**Pull request by blankenberg**
broken in 1cc57b1eb2c295dbd68837c864740b6ff079b83d

JS repack also did a few other targets...

### CODE REVIEW

**Comment by martenson** [comment]
ping @erasche 

probably bad merge of https://github.com/galaxyproject/galaxy/commit/2b4a8557f1f0057447c729717f22452d14ac11ef ?

**Comment by martenson** [comment]
@blankenberg you might want to remove your `client/node_modules/` and do new npm install to get rid of the other targets building

**Comment by blankenberg** [comment]
@martenson thanks. That did in fact change things :)

**Comment by hexylena** [comment]
@martenson ??

**Comment by martenson** [comment]
@erasche 
```
16:20:00 martenson | we should be able to track it down though                                                                                                         │
16:20:11 martenson | seems GitHub interface is hiding something                                                                                                        │
16:22:13 martenson | the commit 2b4a8557f1f0057447c729717f22452d14ac11ef seems to never make it to dev                                                                 │
16:22:29 martenson | despite being clearly shown in GH                                                                                                                 │
16:23:25 martenson | if I go to pre-fix revision and `blame` the file I see                                                                                            │
16:23:27 martenson | Carl Eberhard   2014-11-14                                                                                                                        │
16:23:33 martenson | Eric Rasche     2015-10-25                                                                                                                        │
16:23:40 martenson | on the two delete_current lines                                                                                                                   │
16:24:06 martenson | but it should have been Carl on 25th of July                                                                                                      │

```

**Comment by martenson** [comment]
This bug was in fact caused by a bad merge in https://github.com/galaxyproject/galaxy/pull/3040

**Comment by hexylena** [comment]
@martenson Ah. I have no memory of editing this file so... glad y'all figured it out.

**Comment by blankenberg** [comment]
@erasche sorry for the misdirected git blame :)

**Pull request merged**
