### PR TITLE
Remove bam to bai converter

### PR DESCRIPTION
**Pull request by mvdbeek**
This converter served no real purpose (you can download bam index files
by clicking on the floppy icon of a bam dataset, and we never had a bai datatype).

I would still like to get this into 17.09, since otherwise there will be some very abundant warnings in the logs (lot's of `galaxy.datatypes.registry WARNING 2017-09-04 15:51:32,659 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam’`) whenever galaxy checks if a history item is compatible with a tool input.

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by jmchilton** [comment]
xref 4fa0ac86822e59742413d80cca770f754cd94da8 412f24d5674b1241ca1601a938586d9c5636acdd

**Comment by nsoranzo** [comment]
Thanks @mvdbeek for following up on this!

**Comment by nsoranzo** [comment]
412f24d5674b1241ca1601a938586d9c5636acdd was reverted in commit 189abc32d51834dbfac7edce990b40c64931f1de

**Comment by dannon** [comment]
xref #5167, I believe this is what caused that issue, and will need to follow up to see what the right fix is here.  Can we just update the data providers to use pysam/bams, without involving .bai?

**Comment by nsoranzo** [comment]
See `"bai": genome.BamDataProvider,` in `lib/galaxy/visualization/data_providers/registry.py`

**Pull request merged**
