### PR TITLE
Enable new run workflow form

### PR DESCRIPTION
**Pull request by guerler**
This PR activates the new run workflow form by default in dev:

workflowform

### CODE REVIEW

**Comment by martenson** [comment]
This PR should probably also flip https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L959

I am unsure why this config option is not being loaded in `config.py`.

edit: given this switch is annotated as 'temporary' we can probably directly remove the config option and make it the new default

**Comment by guerler** [comment]
Thanks.

edit: I think we should leave the switch in for now and remove it later when we strip the entire former mako and related code.

**Comment by martenson** [comment]
👍 
please let me know when you want to merge this, as it is labeled WIP

**Comment by bgruening** [comment]
@guerler plus one from me as well. My initial testing looked really good.

**Comment by guerler** [comment]
Thanks for the review @martenson, and thanks for the initial testing and comments @bjoern. That was incredibly helpful. Thanks @dannon for your weeks long help, and discussions regarding the performance issues and @jmchilton for helping with the revision of the parameter handling, processing and validation. Thanks also @carlfeberhard for the backbone discussions and @blankenberg for your UI revision suggestions.

**Comment by jmchilton** [comment]
I'm a standing -0.5 as long as it is targeting the new API endpoint we don't encourage the use of. We should eat our own dog food.

**Comment by guerler** [comment]
This is the same discussion as here https://github.com/galaxyproject/galaxy/pull/2077. This discussion which centers around 50 lines of code has blocked the implementation and development of the new run workflow form for many month and has left users struggling with the old run workflow form, prevented us from closing multiple issues and refining the new form. In #2077, the consenus was that missing features will be added to the invocations endpoint before 16.10, so that existing workflows can actually be processed right? Although it remains a mystery as why the invocations endpoint is not able to incorporate the most basic behavior exhibited by the current workflow execution controller endpoint, this has only little to do with this PR which targets dev.

**Comment by jmchilton** [comment]
> Although it remains a mystery as why the invocations endpoint is not able to incorporate the most basic behavior exhibited by the current workflow execution controller endpoint

If you added an endpoint that enabled everything you want - you could have put the work into adapting the existing backend to the GUI. I get that it isn't of interest to you - but then you should back off and let me do it - forking the paths through the code for workflow execution is not the right answer.

I wouldn't just ignore the GUI code you wrote, I'd adapt it and make it work with workflows (and I'd write tests and add future-facing features available in the backend).

> this has only little to do with this PR which targets dev

My objection is to the endpoint - it shouldn't exist and it certainly shouldn't be enshrined to the point of being the default GUI way to run workflows - so I do think it has a lot to do with this PR.

**Comment by dannon** [comment]
@jmchilton I think swapping to this workflow form reduces more code paths than it creates, and I really don't get the feeling that we're doing any sort of "enshrining" here of the non-public, non-recommended-for-external-use, internal API we created to bootstrap this along.

When the other endpoint has functional parity, we swap it over, delete the temporary internal one, and everyone's happy, right?  No harm done in the interim I don't think.

**Comment by guerler** [comment]
This discussion started in late December 2015 when we noticed that single step workflows cannot be executed through the invocations API unless explicit data inputs are attached. After similar arguments, I stepped back and used the time to rework the parameter handling process by removing legacies and redundancies, significantly simplifying the process up to the point were workflows are executed. Why would I take on such an endevaor if my interest is limited to only one part of this project. In March I noticed that the invocations API was untouched and I wanted to know what the actual problem is. I identified missing components and added them in a reusable way e.g. the batchmode options. I did not modify the invocations API after I encountered some issues, most of them probably fixed by today. It would have not been possible for me to distinguish old from new issues or regular from invocation submission issues because switching between old and new workflow form would not have helped. So I added 50 lines of code to demonstrate that they consistently cover the functionality of the existing controller endpoint and to remove the stall on this project. It is not about my personal interest or about what I want but what has been supported throughout Galaxy for years and that this project moves forward. If I would have kept silent to avoid this discussion the entire project would have been stalled much longer. In fact, I do not understand why there is still an argument after we agreed to extend the invocations API till the end of the month and to redirect the form submission.

**Pull request merged**
