### PR TITLE
Replace custom tour ids in forms with regular DOM identifiers

### PR DESCRIPTION
**Pull request by guerler**
Requires #13246. This PR removes the custom `tour_id` dom attribute and uses the regular `id` attribute instead to query form input elements. It also removes the input id replacement of `|`. Although a special character newer conventions do allow its use as part of a dom id. A benefit of this PR is that input element identifiers for dom elements are now equivalent to actual parameter identifiers used by the api and elsewhere.

## How to test the changes?
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
element-id seems redundant and generic as a prefix for a DOM ID. My preference would be ``gxform-input-``. But this is a small thing - I am okay with the way you have currently.

**Comment by guerler** [comment]
@jmchilton I agree with you, it is redundant. I replaced it with `form-element` since it is the used as part of the `FormElement` component.

**Comment by dannon** [comment]
We're going to try to get this one into 22.01 to minimize conflicts with any bugfixes that may need to propagate forward.

**Comment by guerler** [comment]
Thank you for the review!

**Pull request merged**
