### PR TITLE
A command line script for collecting stats on job runtimes

### PR DESCRIPTION
**Pull request by natefoo**
To help admins make decisions about how/where to run jobs

### CODE REVIEW

**Comment by martenson** [comment]
argparse is not in Python 2.6, there are some scripts that break the Galaxy proclaimed compatibility with 2.6 but I do not think we should add more

Or we can declare that Galaxy is 2.6 but scripts/ are not.

I have recently seen at least 2 emails to -dev with people having trouble with this (having 2.6 and no argparse).

**Comment by natefoo** [comment]
Doesn't bother me for a 1-off utility script, and it makes it Python 3 compatible, but I'm willing to switch to optparse if the consensus is against me.

**Comment by martenson** [comment]
reference: http://dev.list.galaxyproject.org/Galaxy-ToolShed-Update-Problem-tp4666915p4666925.html

**Comment by afgane** [comment]
I feel more documentation would be nice (e.g., is `tool_id` the tool name?) A few sample commands even would help.

And it doesn't seem to like something about the DB connection string on the cloud (`database_connection = postgres://galaxy@localhost:5930/galaxy`):

```
(.venv)galaxy@ip-10-69-183-90:/mnt/galaxy/galaxy-app/scripts$ python runtime_stats.py -c ../config/galaxy.ini -d -u cloud bowtie2
Got options:
tool_id: bowtie2
like: False
connect_args: {'username': 'galaxy', 'host': 'localhost', 'dbname': 'galaxy', 'port': 5930}
min: -1
max: -1
user: cloud
debug: True
config: ../config/galaxy.ini
Traceback (most recent call last):
  File "runtime_stats.py", line 201, in <module>
    main()
  File "runtime_stats.py", line 197, in main
    query(**vars(args))
  File "runtime_stats.py", line 76, in query
    pc = psycopg2.connect(connect_arg_str)
  File "/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: invalid connection option "username"
```

**Comment by jmchilton** [comment]
@natefoo :+1:... but IMO job metrics collect a more accurate job runtime. The job history state change table will have times that are way off if a handler dies or Galaxy goes down for maintenance etc... - but the default job metrics collect runtime on the cluster and are enabled by default. Also the metrics result in a cleaner queries and will have more legacy data for existing Galaxy instances.

**Comment by hexylena** [comment]
@natefoo :+1: I've been wanting this for a while, :+1: to @jmchilton's suggestion of job metrics. 

Personal comments: argparse is great, IMO Galaxy should set an EOL for supporting 2.6, since SO many tools in the shed use argparse.

**Comment by bgruening** [comment]
Tool Shed package can depend on python2.7 if they want. But yes I agree with Eric we should EOL python2.6. +1 for sticking to argparse for scripts.

**Comment by natefoo** [comment]
@jmchilton If you have metrics enabled. =D

Okay, hold off on the merge, I'll add the ability to collect data from metrics.

**Comment by natefoo** [comment]
@afgane give it a try now. I also added examples to the doc string.
@jmchilton suggestion incorporated.

**Comment by afgane** [comment]
+1

**Comment by afgane** [comment]
(didn't mean to close it, clicked the wrong button)

**Pull request merged**
