### PR TITLE
add TS API to check current user

### PR DESCRIPTION
**Pull request by martenson**
ping @jmchilton

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks so much @martenson - I'm :+1: after the tool shed tests pass.

**Comment by davebx** [comment]
What @jmchilton said, +1 pending green.

**Comment by martenson** [comment]
test is red but fails on mercurial :)

**Comment by davebx** [comment]
[redacted] mercurial tests. My +1 stands regardless, the test failure is quite obviously not related.

**Pull request merged**
