### PR TITLE
[21.09] Fix private history publishing

### PR DESCRIPTION
**Pull request by davelopez**
Fixes https://github.com/galaxyproject/galaxy/issues/13001

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  - Share a history containing private datasets (that you own) by making it accessible via link or publishing it
  - Other users can access the private datasets

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thank you @davelopez!

**Comment by hexylena** [comment]
Thank you so much @davelopez!! This is very helpful. @gmauro @bgruening could you update EU to include this?

**Comment by gmauro** [comment]
will be deployed tonight on .eu

**Comment by hexylena** [comment]
amazing, thank you @gmauro!

**Pull request merged**
