### PR TITLE
CSRF protection for login, logout, and user registration.

### PR DESCRIPTION
**Pull request by jmchilton**
The approach is to use per-session CSRF tokens - this avoids many complications related to per-form tokens. We generate a sequence of hashes based on session IDs that doesn't follow the same pattern as normal database API IDs by supplying a "kind" parameter to encode_id (we use the same pattern for securing the job files API for Pulsar).

More information on CSRF for login and logout - https://security.stackexchange.com/a/62797 and CSRF in general including per-session tokens (https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#General_Recommendation%3a_Synchronizer_Token_Pattern).

Ping @erasche, @manabuishii.

### CODE REVIEW

**Comment by manabuishii** [comment]
I think this looks good .

**Comment by manabuishii** [comment]
This sections describes, potential problem of using `GET(URL)` .

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Disclosure_of_Token_in_URL

`/loglout` just  logout confirmation page and
 it has hidden field for csrf token and using POST method is more safer.

**Comment by jmchilton** [comment]
Thanks for the link - this is a subtle point about GETs.

> CSRF tokens in GET requests are potentially leaked at several locations: browser history, HTTP log files, network appliances that make a point to log the first line of an HTTP request, and Referer headers if the protected site links to an external site.

In this case however, that token is only useful until that that logout link is clicked - at that point it is no longer sensitive - or at least we are assuming it is no longer sensitive. I guess I understand the paranoia of not wanting these token to leak in general for GETs but for logouts specifically I think it is okay?

That said - the logout operation really should be a POST REST-fully speaking anyway. Here is a good line:

> For these cases, attempting to retrofit this pattern in existing applications requires significant development time and cost, and as a temporary measure it may be better to pass CSRF tokens in the URL. Once the application has been fixed to respond to HTTP GET and POST verbs correctly, CSRF tokens for GET requests should be turned off.

If we spend more time on CSRF I would like to apply it to say tool shed installation - because that is an entry point that provides shell access to the system - and then next maybe to password modification forms, user and role creation, etc... before reworking logout. How about a create an issue and we track this for longer term development.

**Comment by hexylena** [comment]
I'm used to CSRF tokens changing after every single request. If I'm reading the code correctly, this will only generate one per session? This will give us some protection, but probably isn't perfect long term. :+1: on this though, you have a task list for going forward and we can look into per-form / per-request csrf tokens going forward maybe. (Then again, as we move more and more to api-only, this becomes less of an issue.)

**Comment by jmchilton** [comment]
@erasche https://security.stackexchange.com/questions/22903/why-refresh-csrf-token-per-form-request

> For the reasons already discussed, it is not necessary to generate a new token per request. It brings almost zero security advantage, and it costs you in terms of usability: with only one token valid at once, the user will not be able to navigate the webapp normally. For example if they hit the 'back' button and submit the form with new values, the submission will fail, and likely greet them with some hostile error message. If they try to open a resource in a second tab, they'll find the session randomly breaks in one or both tabs. It is usually not worth maiming your application's usability to satisfy this pointless requirement 

I learned about CSRF in the context of per-request tokens also - but in practice it just wouldn't be workable in Galaxy or any single page app I don't think. I think long term per-session tokens are the way to go.

**Comment by jmchilton** [comment]
> Then again, as we move more and more to api-only, this becomes less of an issue.

I don't know that this mitigates anything - as long as we are using the session cookie to authenticate and GET or POST to a page that changes Galaxy state - we should be using per-session CSRF tokens - regardless of if these are API endpoints or more traditional endpoints. I think continuing to use the session cookie (with or without CSRF protection) is a lot more secure than sticking the user's API key in the web app and exposing that extra places also.

So far this CSRF protection is used as needed in a couple endpoints - I think longer term it would be good for the same logic that determines if an API key is present or checks the session cookie if not should be extended to just always ensure there is a CSRF token if there is no API key - but it would require retrofitting dozens of forms probably.

**Comment by hexylena** [comment]
yeah, ok, even OWASP is fine with per-session csrf tokens. I'm a bit out of date apparnetly. 

> I don't know that this mitigates anything - as long as we are using the session cookie to authenticate and GET or POST to a page that changes Galaxy state - we should be using per-session CSRF tokens - regardless of if these are API endpoints or more traditional endpoints. I think continuing to use the session cookie (with or without CSRF protection) is a lot more secure than sticking the user's API key in the web app and exposing that extra places also.

Yes, you're right here. Just my hope that we move to per-session authentication tokens in headers. This would expose us more to XSS issues, but remove the CSRF risks.

> So far this CSRF protection is used as needed in a couple endpoints - I think longer term it would be good for the same logic that determines if an API key is present or checks the session cookie if not should be extended to just always ensure there is a CSRF token if there is no API key - but it would require retrofitting dozens of forms probably.

sounds good to me.

**Comment by martenson** [comment]
Failing tests look related.

**Comment by jmchilton** [comment]
@martenson Yeah thanks for spotting that - I've pushed in a fix for that. I'll rebase and re-pack if the tests pass now.

**Comment by hexylena** [comment]
@jmchilton if you can fix the conflicts I'll merge this today.

**Comment by jmchilton** [comment]
@erasche Rebased and un-conflicted.

**Comment by hexylena** [comment]
Rant py27lint locally and looks good.

**Comment by mvdbeek** [comment]
This seems to have broken the workflow editor:
```
URL: http://127.0.0.1:8080/workflow/editor?id=417e33144b294c21
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 135 in __call__
  return self.handle_request( environ, start_response )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 214 in handle_request
  body = method( trans, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py', line 74 in decorator
  return func( self, trans, *args, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 627 in editor
  return trans.fill_template( "workflow/editor.mako", workflows=workflows, stored=stored, annotation=self.get_item_annotation_str( trans.sa_session, trans.user, stored ) )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 891 in fill_template
  
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 905 in fill_template_mako
  def fill_template(self, filename, **kwargs):
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/template.py', line 445 in render
  return runtime._render(self, self.callable_, args, data)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 829 in _render
  **_kwargs_for_callable(callable_, data))
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 864 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 890 in _exec_template
  callable_(context, *args, **kwargs)
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 80 in render_body
  __M_writer(unicode(self.javascript_app()))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 234 in render_javascript_app
  __M_writer(unicode( galaxy_client.load() ))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/galaxy_client_app.mako.py', line 56 in render_load
  __M_writer(unicode( trans.session_csrf_token ))
AttributeError: 'GalaxyWebTransaction' object has no attribute 'session_csrf_token'


CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
  HTTP_ACCEPT_LANGUAGE: 'en-US,fr-FR;q=0.8,fr;q=0.6,de-DE;q=0.4,de;q=0.2,el-GR;q=0.2,el;q=0.2,en;q=0.2'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'
  HTTP_HOST: '127.0.0.1:8080'
  HTTP_REFERER: 'http://127.0.0.1:8080/workflow'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
  PATH_INFO: '/workflow/editor'
  QUERY_STRING: 'id=417e33144b294c21'
  REMOTE_ADDR: '127.0.0.1'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x10a992790>
  controller_action_key: u'web.workflow.editor'
  is_api_request: False
  paste.cookies: (<SimpleCookie: galaxysession='c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'>, 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x10b839310>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x114ff40d0>
  paste.parsed_querystring: ([('id', '417e33144b294c21')], 'id=417e33144b294c21')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '61e6a7d979c811e7a236c4b301d1ef93'
  webob._parsed_query_vars: (GET([(u'id', u'417e33144b294c21')]), 'id=417e33144b294c21')
  wsgi process: 'Multithreaded'
------------------------------------------------------------
127.0.0.1 - - [05/Aug/2017:12:25:20 +0200] "GET /api/histories/964b37715ec9bd22/contents?keys=type_id%2Celement_count&order=hid&v=dev&q=history_content_type&q=deleted&q=purged&q=visible&qv=dataset_collection&qv=False&qv=False&qv=True HTTP/1.1" 200 - "http://127.0.0.1:8080/workflow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
127.0.0.1 - - [05/Aug/2017:12:25:51 +0200] "GET /workflow/editor?id=417e33144b294c21 HTTP/1.1" 500 - "http://127.0.0.1:8080/workflow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
Error - <type 'exceptions.AttributeError'>: 'GalaxyWebTransaction' object has no attribute 'session_csrf_token'
URL: http://127.0.0.1:8080/workflow/editor?id=417e33144b294c21
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 135 in __call__
  return self.handle_request( environ, start_response )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 214 in handle_request
  body = method( trans, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py', line 74 in decorator
  return func( self, trans, *args, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 627 in editor
  return trans.fill_template( "workflow/editor.mako", workflows=workflows, stored=stored, annotation=self.get_item_annotation_str( trans.sa_session, trans.user, stored ) )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 891 in fill_template
  
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 905 in fill_template_mako
  def fill_template(self, filename, **kwargs):
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/template.py', line 445 in render
  return runtime._render(self, self.callable_, args, data)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 829 in _render
  **_kwargs_for_callable(callable_, data))
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 864 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 890 in _exec_template
  callable_(context, *args, **kwargs)
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 80 in render_body
  __M_writer(unicode(self.javascript_app()))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 234 in render_javascript_app
  __M_writer(unicode( galaxy_client.load() ))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/galaxy_client_app.mako.py', line 56 in render_load
  __M_writer(unicode( trans.session_csrf_token ))
AttributeError: 'GalaxyWebTransaction' object has no attribute 'session_csrf_token'


CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
  HTTP_ACCEPT_LANGUAGE: 'en-US,fr-FR;q=0.8,fr;q=0.6,de-DE;q=0.4,de;q=0.2,el-GR;q=0.2,el;q=0.2,en;q=0.2'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'
  HTTP_HOST: '127.0.0.1:8080'
  HTTP_REFERER: 'http://127.0.0.1:8080/workflow'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
  PATH_INFO: '/workflow/editor'
  QUERY_STRING: 'id=417e33144b294c21'
  REMOTE_ADDR: '127.0.0.1'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x10a992790>
  controller_action_key: u'web.workflow.editor'
  is_api_request: False
  paste.cookies: (<SimpleCookie: galaxysession='c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'>, 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x10b839310>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x114ff40d0>
  paste.parsed_querystring: ([('id', '417e33144b294c21')], 'id=417e33144b294c21')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '74823c4279c811e7a9a0c4b301d1ef93'
  webob._parsed_query_vars: (GET([(u'id', u'417e33144b294c21')]), 'id=417e33144b294c21')
  wsgi process: 'Multithreaded'
------------------------------------------------------------
127.0.0.1 - - [05/Aug/2017:12:25:53 +0200] "GET /workflow/editor?id=417e33144b294c21 HTTP/1.1" 500 - "http://127.0.0.1:8080/workflow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
Error - <type 'exceptions.AttributeError'>: 'GalaxyWebTransaction' object has no attribute 'session_csrf_token'
URL: http://127.0.0.1:8080/workflow/editor?id=417e33144b294c21
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 135 in __call__
  return self.handle_request( environ, start_response )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 214 in handle_request
  body = method( trans, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py', line 74 in decorator
  return func( self, trans, *args, **kwargs )
File '/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 627 in editor
  return trans.fill_template( "workflow/editor.mako", workflows=workflows, stored=stored, annotation=self.get_item_annotation_str( trans.sa_session, trans.user, stored ) )
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 891 in fill_template
  
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/webapp.py', line 905 in fill_template_mako
  def fill_template(self, filename, **kwargs):
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/template.py', line 445 in render
  return runtime._render(self, self.callable_, args, data)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 829 in _render
  **_kwargs_for_callable(callable_, data))
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 864 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 890 in _exec_template
  callable_(context, *args, **kwargs)
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 80 in render_body
  __M_writer(unicode(self.javascript_app()))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/base/base_panels.mako.py', line 234 in render_javascript_app
  __M_writer(unicode( galaxy_client.load() ))
File '/Users/mvandenb/src/galaxy/database/compiled_templates/galaxy_client_app.mako.py', line 56 in render_load
  __M_writer(unicode( trans.session_csrf_token ))
AttributeError: 'GalaxyWebTransaction' object has no attribute 'session_csrf_token'


CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
  HTTP_ACCEPT_LANGUAGE: 'en-US,fr-FR;q=0.8,fr;q=0.6,de-DE;q=0.4,de;q=0.2,el-GR;q=0.2,el;q=0.2,en;q=0.2'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'
  HTTP_HOST: '127.0.0.1:8080'
  HTTP_REFERER: 'http://127.0.0.1:8080/workflow'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
  PATH_INFO: '/workflow/editor'
  QUERY_STRING: 'id=417e33144b294c21'
  REMOTE_ADDR: '127.0.0.1'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x10a992790>
  controller_action_key: u'web.workflow.editor'
  is_api_request: False
  paste.cookies: (<SimpleCookie: galaxysession='c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5'>, 'galaxysession=c6ca0ddb55be603aaf547a1bfe04b5f26e0a9c5a217ffcf61300cd7df238723aca7b7f5796e56df5')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x10b839310>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x114ff40d0>
  paste.parsed_querystring: ([('id', '417e33144b294c21')], 'id=417e33144b294c21')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '75a1278279c811e789dac4b301d1ef93'
  webob._parsed_query_vars: (GET([(u'id', u'417e33144b294c21')]), 'id=417e33144b294c21')
  wsgi process: 'Multithreaded'
```

**Comment by hexylena** [comment]
@mvdbeek I received an email, did you remove your comment because it wasn't a bug?

**Comment by mvdbeek** [comment]
Yes, sorry for the noise.

**Comment by hexylena** [comment]
No worries! I was quite concerned we'd missed something. Glad to hear false positive :)

**Pull request merged**
