### PR TITLE
Fix panel header margins in history and tool panel

### PR DESCRIPTION
**Pull request by guerler**
Follow-up PR to fix header margins in panels and reduce white spaces.

untitled

### CODE REVIEW

**Comment by jxtx** [comment]
Much better but looks like title (Unnamed History) is still slightly
off, a few pixels too far to the right?

Aysam Guerler <notifications@github.com> writes:

> Follow-up PR to fix header margins in panels and reduce white spaces.
>
> historypanel
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/galaxyproject/galaxy/pull/6854
>
> -- Commit Summary --
>
>   * Align history and tool panel margins
>   * Align search bars in both panels
>
> -- File Changes --
>
>     M client/galaxy/style/scss/base.scss (9)
>     M client/galaxy/style/scss/history.scss (28)
>     M client/galaxy/style/scss/list-item.scss (24)
>     M static/style/blue/base.css (98)
>
> -- Patch Links --
>
> https://github.com/galaxyproject/galaxy/pull/6854.patch
> https://github.com/galaxyproject/galaxy/pull/6854.diff
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/galaxyproject/galaxy/pull/6854

-- 
James Taylor
Ralph S. O'Connor Professor of Biology and Computer Science
Johns Hopkins University

**Comment by martenson** [comment]
fullscreen_10_11_18__12_02_pm

**Comment by guerler** [comment]
Thanks for pointing it out. It's a margin shift induced by the editable plugin. I fixed it by adding 1px margin to the element and updated the screenshot above. I think that this is a reasonable fix but it would be better to prevent the plugin from moving the element in the first place.

**Comment by martenson** [comment]
Thanks @guerler !

**Pull request merged**
