### PR TITLE
[16.01] Deprecation notice - Python 2.6.

### PR DESCRIPTION
**Pull request by jmchilton**
xref #1596

### CODE REVIEW

**Comment by dannon** [comment]
+1

**Comment by mvdbeek** [comment]
:+1:

**Comment by natefoo** [comment]
:+1: 

@jmchilton Funny, I swear you had argued the case to me that 2.6 support should remain.

**Comment by dannon** [comment]
https://github.com/galaxyproject/galaxy/pull/1785 for the followup (to -dev) dropping 2.6 testing.

**Pull request merged**
