### PR TITLE
Add grunt watcher on the .less files

### PR DESCRIPTION
**Pull request by remimarenco**
Hi!

I wanted to work on cleaning a bit the less files, but did not want to recompile manually the .less files. So, with the kickstart of @dannon, I added it!

In terminal, Go to `client/` and type `grunt watch-style`.
Change a .less file in `client/galaxy/style/less`, are **watch** it recompile :)

TODO:
- [x] Add documentation of it
- [ ] Less bruteforce recompilation

### CODE REVIEW

**Comment by dannon** [comment]
In your description here you say `grunt style-watch`, but it's actually `grunt watch-style` in the code, for anyone testing :)

**Comment by martenson** [comment]
@remimarenco nice!

please document it here: https://github.com/galaxyproject/galaxy/blob/dev/client/README.md

and please label things :)

**Comment by remimarenco** [comment]
Thanks @martenson, modified too :)

**Comment by remimarenco** [comment]
@martenson I would love to label, but I can't do that too :). Seems I need special rights

**Pull request merged**
