### PR TITLE
Fix repeat prefix

### PR DESCRIPTION
**Pull request by guerler**
This is a fix for #1764. The repeat prefixes were not aligned with: https://github.com/galaxyproject/galaxy/pull/1764/files#diff-ca2e00a05d3404fc5410df390ed69ac1L119. The test case demonstrates the varying behavior between parent prefixes of repeats and conditionals.

### CODE REVIEW

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by dannon** [comment]
+1

**Pull request merged**
