### PR TITLE
Fix search overlay JS errors

### PR DESCRIPTION
**Pull request by anuprulez**
This PR fixes the bug #5522 
ping @martenson

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is the bug present on 18.01 too?

**Comment by anuprulez** [comment]
I think yes because the [lines](https://github.com/galaxyproject/galaxy/blob/release_18.01/config/plugins/webhooks/demo/search/script.js#L511) which I updated to fix the bug are present in [18.01](https://github.com/galaxyproject/galaxy/tree/release_18.01).

**Comment by anuprulez** [comment]
I think the build failed for the same reasons as were for #5507

**Comment by martenson** [comment]
Thank you @anuprulez !

**Comment by martenson** [comment]
backported to 18.01 in https://github.com/galaxyproject/galaxy/commit/a269a95cf0aef62b1f1dbca8de698d7b2f61f52b

**Pull request merged**
