### PR TITLE
Extend wait for datasets to be ready in transiently failing API tests

### LINKED ISSUE #4218: Transiently Failing List Downloader Test
Added by @mvdbeek with https://github.com/galaxyproject/galaxy/pull/4098. I took a stab at debugging it with https://github.com/galaxyproject/galaxy/pull/4156 but it didn't help me come to any conclusions. I guess we should just strip it out until we have an idea? It is really odd that very similar tests don't seem to fail the same way.

### PR DESCRIPTION
**Pull request by mvdbeek**
Just testing out if that would fix #4218 ...

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
OK, the last 5 runs of the docker-api test didn't fail anymore, I guess this is working. The only failing API test in those five runs was an unrelated one (api.test_jobs.JobsApiTestCase.test_deleting_output_keep_running_until_all_deleted).

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
Hmm, 1 second is not enough (https://jenkins.galaxyproject.org/blue/organizations/jenkins/docker-api/detail/docker-api/7599/pipeline#log-1057) ... maybe this is a database synchronization issue ?

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
@galaxybot test this

**Comment by mvdbeek** [comment]
Something's funny here:
```
galaxy.webapps.galaxy.api.history_contents INFO 2017-06-24 19:30:41,378 Skipping download of 'Dataset Collection from pairs/test0/reverse', because its state is 'running'
```
So somehow `wait_for_dataset` is not actually waiting properly ...

**Comment by jmchilton** [comment]
I think you are grabbing the datasetcollectionelement id and then waiting on it as if it were an HDA id. These overlap if you run these tests one off - but not if other tests have already executed? I'll open a PR with what I think the correct ID to grab is.

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/pull/4281

**Comment by jmchilton** [comment]
Thanks for testing this so thoroughly @mvdbeek - sorry I didn't have a look sooner. I'm going to close this PR in favor of #4281 - hope that is okay.

**Pull request closed without merging**
