### PR TITLE
UI, datasets: Move support for rerunnable to dataset-li expansion; re…

### PR DESCRIPTION
**Pull request by carlfeberhard**
…move redundant listener set up

There are two test cases here. Begin both by starting a simple tool on a dataset. When the queued dataset appears in the history:
- case 1:
  -  expand the dataset
  -  check to see that it has the re-run button even in the queued state
  -  make sure it properly has all elements when in a final 'ok' state
- case 2:
  -  do not expand the dataset
  -  when it moves into the 'ok' state, expand it and make sure it has all the elements needed

This is getting close to a straight-up hack but solves the existing problems. Longer term, I'll be tackling some of the complexity that's grown up around history updating next.

Thanks to @dannon for the help on this.

@dannon @guerler please review.

### CODE REVIEW

**Comment by dannon** [comment]
The contents update correctly, but it doesn't look like the state does anymore.  I used rerun several times on the same dataset and tried expanding (details fetch) a few of them while they were running at various stages.

image

Additionally, rerun doesn't work immediately anymore, presenting a modal with `Could not find tool with id 'undefined'`.

**Comment by carlfeberhard** [comment]
Alright. I can reproduce the second error - I'll work on that. Thanks
Still trying to reproduce the first.

**Comment by dannon** [comment]
Cool, thanks!  Let me know if you still can't get the first error to reproduce -- I just clicked rerun, execute a bunch of times back to back and randomly expanded stuff, but I can try to dig into it a little more if ya want.

**Comment by carlfeberhard** [comment]
I think what was happening in the second case was the data from a slower summary request was overwriting the data from a quicker detailed 'ok' request. Let me know if you see anything else.

**Comment by dannon** [comment]
@carlfeberhard Explanation seems reasonable.  This all works for me now, thanks!

**Pull request merged**
