### PR TITLE
Add the pullapprove yaml to have a more powerful PR review process

### PR DESCRIPTION
**Pull request by remimarenco**
Hi!

I just saw the http://pullapprove.com website pushed by GitHub, and thought it could be nice for our review process :).

Let me know what you think about it! (The pullapprove thing and my yaml ;) )

### CODE REVIEW

**Comment by martenson** [comment]
I think we have a very decent setup right now that would not benefit from another dependency. If we want to automate things even more we have @erasche's P4 (https://github.com/erasche/p4/) and Jenkins to keep a continuous eye.

Furthermore the pullapprove software seems to not be open source.

**Comment by martenson** [comment]
see https://jenkins.galaxyproject.org/view/Meta/job/pull-request-watcher/

**Comment by remimarenco** [comment]
Oh cool! I did not know this P4. So Travis is running this on all Prs? I like it!

Yes, the none open-source thing was bugging me too. But it is quite young, I guess we could have asked or something.

**Comment by martenson** [comment]
@remimarenco yeah it runs it every hour on all PRs; the logic is defined in the yaml file here: https://github.com/erasche/p4/blob/master/conf.yaml

**Pull request closed without merging**
