### PR TITLE
Use standard Galaxy message box styles on tool help texts that use rST admonitions

### PR DESCRIPTION
**Pull request by natefoo**
[rST admonitions](http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions) allow you to create a block that is intended to stand out. Three of these admonition types, `warning`, `error`, and `note` align nicely with Galaxy's `warningmessage`, `errormessage`, and `infomessage` classes.

This change makes it possible to use those admonition types in tool help text and have them render as the corresponding Galaxy message types.

### CODE REVIEW

**Comment by natefoo** [comment]
FWIW I want this on Main for a tool we'll be adding that needs a big 'ole "beta" disclaimer but it's not a bug fix so it breaks the rules to accept it into 15.07. Perhaps now is the time to create a "usegalaxy.org" branch.

**Comment by martenson** [comment]
I like this. I also wouldn't bother with usegalaxy branch, it will add overhead I do not deem justified. Let's just PR against 15.07

That said you know better than me if the overhead is worth it.

**Comment by natefoo** [comment]
@martenson The problem is that it violates the rules for admission into 15.07, because it's not a bug fix. It's about as harmless a new feature as they come, but it's still against the rules.

**Comment by martenson** [comment]
I understand, I just do not like that rule. I am fine with having it in 15.07.

**Comment by nsoranzo** [comment]
@natefoo Cherry-picking the commit on Main could also be an option for you, should not be a problem when upgrading to the next release.

**Comment by natefoo** [comment]
@nsoranzo Great point, I hadn't considered that.

**Comment by bgruening** [comment]
@natefoo should this work:

```
.. error:: This is a note admonition.
   This is the second line of the first paragraph.

   - The note contains all indented body elements
     following.
   - It includes this bullet list.
```

It doesn't for me on 16.01.

**Pull request merged**
