### PR TITLE
Copy to clipboard, instead of pop-up

### PR DESCRIPTION
**Pull request by OlegZharkov**
It replaces "copy pop-up" on tools page and copies link automatically

image

### CODE REVIEW

**Comment by dannon** [comment]
@OlegZharkov Thanks!  When this was added, browser support for writing to the clipboard wasn't what it is now.  These days we may be able to just drop the extra dependency and use clipboard-write?

**Comment by OlegZharkov** [comment]
@dannon

Oh, that's actually a very good idea. But that won't work on IE. Do we drop it?

**Comment by dannon** [comment]
Looks like IE is .5% of the traffic on usegalaxy.org, and in testing it doesn't even load for me on IE anyway.  I think we can just drop the compatibility shim here.  I do need to add a warning saying "Hey, if you're using IE, please swap to firefox/chrome/edge/any-modern-thing to use Galaxy".

**Comment by OlegZharkov** [comment]
> Looks like IE is .5% of the traffic on usegalaxy.org, and in testing it doesn't even load for me on IE anyway. I think we can just drop the compatibility shim here and use the clipboard API directly. I do need to add a warning saying "Hey, if you're using IE, please swap to firefox/chrome/edge/any-modern-thing to use Galaxy", though, because right now it's just a blank page.

.5% such a number :)

I kinda thought that we still support it. I changed it to clipboard-write. Thanks a lot for advise! :+1:

**Comment by dannon** [comment]
@OlegZharkov I thought a little more about it and I added a fallback to the old functionality in the event the standard API isn't working, just in case.  I think this is great though, thank you for working on it!

**Comment by OlegZharkov** [comment]
> @OlegZharkov I thought a little more about it and I added a fallback to the old functionality in the event the standard API isn't working, just in case. I think this is great though, thank you for working on it!

thanks!

**Pull request merged**
