### PR TITLE
implement workflow bookmark selenium test

### PR DESCRIPTION
**Pull request by OlegZharkov**
1) Create a new workflow
2) Create a bookmark in "workflow-table"
3) Search for bookmark in "search tools" field 
4) Assert the bookmark exits

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
Thanks a bunch - this is a really awesome test and excellent contribution. I implemented my PR review as a commit (https://github.com/galaxyproject/galaxy/pull/9231/commits/e2a6bac0327aa96aec74c28454cc81e3f9e37d56) - just because I know this stuff isn't well documented. I think the tests aren't passing on my laptop right now so I opened a new PR to have Jenkins test this.

**Comment by jmchilton** [comment]
Pushed the fix to this branch! Thanks for the test - this is awesome.

**Comment by OlegZharkov** [comment]
Cool, thanks a lot for the review!

**Pull request merged**
