### PR TITLE
Implement ``single_user = <email>`` config option.

### PR DESCRIPTION
**Pull request by jmchilton**
Let Planemo and other such applications serve a full-fledged, personalized Galaxy instance without having to worry about logins, etc....

### CODE REVIEW

**Comment by hexylena** [comment]
> will hijack remote user mechanics

makes it sound like it will set `use_remote_user = True`, but that must be set manually. Shouldn't it completely hijack remote_user mechanics?

**Comment by jmchilton** [comment]
@erasche Yeah - it makes a little more sense from a deployer perspective but would muddle the implementation a little. I'll make this change I guess.

**Comment by hexylena** [comment]
:+1: on this. Waiting for tests to pass.

**Comment by jmchilton** [comment]
Awesome - thanks for the great feedback and for the merge @erasche.

**Pull request merged**
