### PR TITLE
Modernise build of packages

### PR DESCRIPTION
**Pull request by nsoranzo**
- Move package metadata from `setup.py` and `project_galaxy_util.py` to `setup.cfg` .
- Use `build` package to build sdist and wheel packages.
- Scripts and Makefile updated accordingly.
- Update some package requirements and MANIFEST.in files.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by jmchilton** [comment]
Looks great to me!

**Comment by nsoranzo** [comment]
Trying to sneak this into 22.05, since it'd be good to build the new packages with this clean-ups. If it's deemed too invasive, happy to have it targeted at 22.09.

**Comment by mvdbeek** [comment]
This looks good to me, but I would appreciate @jmchilton taking another look.

**Comment by mvdbeek** [comment]
Well, let's get it in, can always fix bugs if they should show up.

**Pull request merged**
