### PR TITLE
[16.04] Redirect to root instead of displaying error for datasource tools that do not provide URL or runtool_btn, and where tool.display_interface is False

### PR DESCRIPTION
**Pull request by blankenberg**
xref https://github.com/galaxyproject/galaxy/issues/2200

### CODE REVIEW

**Comment by guerler** [comment]
Can you explain this a little bit more i.e. how is hiding the error message in one of two cases a bug fix?

**Comment by martenson** [comment]
@guerler would it also redirect you to root before?

**Comment by guerler** [comment]
Yes, it silently redirected but I think its better to validate (if we can) and tell the user what went wrong. Particularly in this case where the redirect relies on staging the existence of a ui element id within the tool xml. Overall its difficult to detect issues related to silent redirects and I am in favor of avoiding them unless its clear what actually happened. Edit: Then again, I do not want stay in the way of a fix.

**Comment by jmchilton** [comment]
Ping @blankenberg - I know things have been very busy but can you respond to this now? I'll mark it as WIP if not until there is more discussion.

**Comment by martenson** [comment]
I am removing the milestone since this seems to get stuck.

**Comment by guerler** [comment]
Closing this for now. I think showing the error message instead of a silent redirect does not hurt.

**Pull request closed without merging**
