### PR TITLE
Move workflow run and history options to top, add loading indicator

### PR DESCRIPTION
**Pull request by guerler**
This PR moves the workflow execution button of the new run workflow form to the top of the screen and adds a load indicator i.e. spinner similar to the job execution spinner of regular tool forms. The history options form is also moved to the top of the screen. This is the first step, a progress bar (within the button) indicating the workflow loading progress with more detail will follow soon. Having the button at the top of the form will allow us to lazy load step forms below. It also avoids that users have to scroll through all steps which can be tedious if the workflow contains several hundred steps. In addition the PR aligns the button class patterns and adds new test cases.

workflowform

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks for implementing this. One of the common questions from our users.

**Comment by guerler** [comment]
Anytime, thanks for having pointed it out.

**Comment by guerler** [comment]
@galaxybot test this

**Comment by guerler** [comment]
@galaxybot test this

**Comment by blankenberg** [comment]
Could we have the progress bar, the run button, etc float, so that when you scroll down the form you can always just click Run after you've configured the tools that you want?

**Comment by guerler** [comment]
Awesome. Definitely. I am adding/experimenting with the progress bar right now in a separate PR and will add that feature too within that follow up i.e. keep the header with title and run button fixed at its screen location.

**Comment by dannon** [comment]
Works for me.

**Comment by dannon** [comment]
(and +1 to making it float at the header once you scroll)

I'd also change the display of the 'send results to a new history' and group that somehow, maybe.  In another PR, of course :)

**Pull request merged**
