### PR TITLE
[18.05] Update name of Workflow when updating StoredWorkflow name

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes https://github.com/galaxyproject/galaxy/issues/6773.

### CODE REVIEW

**Comment by dannon** [comment]
Interesting.  Do you know the reason for why we have `name` for both `Workflow` and `StoredWorkflow`?  (same with `user`, I guess -- is this always redundant, and should we fix the glitch in the model?)

**Comment by mvdbeek** [comment]
I think this is actually nice, this way keep track of metadata changes, so a user can go back and see what a previous version looked like.

**Comment by dannon** [comment]
@mvdbeek Storing those with the workflow revisions is totally fine, but then we should dump it in `StoredWorkflow`, right?

(well, `name` at least -- I'm not sure `user` can ever change without a new `StoredWorkflow`, can it?)

**Comment by mvdbeek** [comment]
Yeah, I suppose StoredWorkflow.name could be a property pointing to latest_workflow.name ? But let's do that in dev

**Comment by dannon** [comment]
@mvdbeek Yep, exactly.  And, I'm fine with fixing it in dev, sure.

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
