### PR TITLE
[WIP] Enhance cut tool

### PR DESCRIPTION
**Pull request by blankenberg**
... to allow use of step size within ranges, specifying the fill char, and allow handling headers in 3 different ways.

### CODE REVIEW

**Comment by blankenberg** [comment]
ping @nekrut

**Comment by blankenberg** [comment]
should add tests for the new options

**Comment by bgruening** [comment]
@blankenberg marked it as WIP until we have the tests.

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by dannon** [comment]
@blankenberg Is this still something you want to get in?

**Comment by blankenberg** [comment]
These are still useful abilities. Needs tests and conflicts resolved. I'll move the title into WIP.

**Comment by natefoo** [comment]
I would like to clarify that @mvdbeek’s finger closed this PR

**Pull request closed without merging**
