### PR TITLE
introduce the ability to favorite tools

### PR DESCRIPTION
**Pull request by martenson**
# favorite tools you like
galaxy

# display only tools you have favorited
galaxy

### CODE REVIEW

**Comment by bgruening** [comment]
@martenson what about having a "star" or a link next to the search bar indicating favorites instead of searching for them? Similar to the `deleted` datasets link on the history maybe?

**Comment by martenson** [comment]
@bgruening I am open to that but I do not think a button is necessary. I want to make tool search more powerful without overloading the interface as it happened with histories - Imo we should devise a way how to hint these extra/reserved searches. Something like a `?` popover with hints and link to docs.

**Comment by nsoranzo** [comment]
@martenson If the goal is to make access to favourite tools faster, than a button makes more sense also for me than having to type something in the search box (IIUC).

**Comment by martenson** [comment]
@bgruening @mvdbeek @nsoranzo @erasche you got it

**Comment by martenson** [comment]
@guerler The upload button behaves very non-standard in the standard panel button menu, any ideas?

galaxy

**Comment by martenson** [comment]
thanks a lot for helping @guerler !

**Comment by martenson** [comment]
ready for review I think

**Comment by jmchilton** [comment]
I'm going to approve this because it has languished and I'm not sure we need to spend more time on it. I would just say that despite my +1 I think we should not use user preferences for this - we should store the data in the database in a more structured way. For instance a ToolFavorite class with a tool ID that is linked to the User for instance. User preferences are completely untyped and unstructured and are a hack to provide an extension point for installers - we don't need to avoid creating a table because this is not optional functionality and not an extension, we can do a better job with the modeling as a result.

**Review by jmchilton — APPROVED** [review]

**Comment by bgruening** [comment]
@jmchilton you are correct. Worth to open an issue about this I guess.

**Comment by hexylena** [comment]
in case anyone was curious :)

```
(venv) galaxy@sn04:~$ psql -qAt -c "select value::json->'tools' from user_preference where name = 'favorites'" | jq -s add | jq '. | @tsv' -r | sed 's/\t/\n/g' | sort | uniq -c | sort -nr | head -n 20
     20 toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1
     12 toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.7
     11 toolshed.g2.bx.psu.edu/repos/iuc/hisat2/hisat2/2.1.0+galaxy4
     11 toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.11.40.6
      8 toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.13
      8 Filter1
      7 toolshed.g2.bx.psu.edu/repos/iuc/featurecounts/featurecounts/1.6.4
      6 toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmomatic/trimmomatic/0.36.5
      6 toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1
      6 toolshed.g2.bx.psu.edu/repos/iuc/volcanoplot/volcanoplot/0.0.3
      5 toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.6.0b-2
      5 toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.1
      4 toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmomatic/trimmomatic/0.32.3
      4 toolshed.g2.bx.psu.edu/repos/iuc/trinity/trinity/2.8.4
      4 toolshed.g2.bx.psu.edu/repos/iuc/stringtie/stringtie/1.3.6
      4 toolshed.g2.bx.psu.edu/repos/iuc/edger/edger/3.24.1
      4 toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.1
      4 Cut1
      4 cat1
      3 toolshed.g2.bx.psu.edu/repos/lparsons/htseq_count/htseq_count/0.9.1
```

**Comment by martenson** [comment]
@erasche awesome, people are starting to use it!

**Pull request merged**
