### PR TITLE
Fix batch mode input in new tool form ui

### PR DESCRIPTION
**Pull request by ericenns**
When using the new tool form ui and history has dataset that could map to multiple inputs, map_over_type: 'paired' is not set as the history object was global and not specific to the individual form-select-content view.

What ended up happening is we have a pair collection input which was being passed a list collection instead so errors were being thrown while trying to access the forward and reverse keys. This tool works correctly with the old tool form ui.

@Takadonet shows the stacktrace in this gist along with the tool xml https://gist.github.com/Takadonet/9fc52626d5402d566be0

### CODE REVIEW

**Comment by guerler** [comment]
:+1:

**Comment by jmchilton** [comment]
:+1:

**Comment by martenson** [comment]
Thank you for working on this! @ericenns

**Comment by ericenns** [comment]
I mean't to merge this into release_15.05 should I open a new pull request

**Comment by guerler** [comment]
Not sure if you have to create a new pr or if someone transfers it.

**Comment by martenson** [comment]
@ericenns new PR please (e.g. cherrypicked)

**Pull request merged**
