### PR TITLE
[15.07] Encode unicode string before passing to hashlib.sha1().

### LINKED ISSUE #673: Not possible to add a dataset to a library from an import dir if there is a file with an UTF-8 name.
To reproduce:
- configure `library_import_dir` or `user_library_import_dir` in config/galaxy.ini and restart Galaxy
- in the configured directory, create a with an UTF-8 name, e.g. `”test”` 
- from the "Share Data" menu select "Data Libraries Beta"
- click on a library to which you can add datasets
- click on the icon "Add Datasets to Current Folder" and select "from User Directory"
- a red pop-up error appear saying: "Could not create tree representation of the given folder: /path/of/the/library/import/dir". No files or folders are showed on the "Please select folders or files" pop-up.

No errors if the UTF-8 file is removed or renamed.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fixes #673.

### CODE REVIEW

**Comment by martenson** [comment]
:+1: 
also don't expect the jenkins tests to pass, 15.07 is before we dockerized things properly

**Comment by martenson** [comment]
this needs to go forward to 15.10 and dev

**Comment by nsoranzo** [comment]
@martenson: Done.

**Comment by martenson** [comment]
@nsoranzo thanks a lot!

**Pull request merged**
