### PR TITLE
Document GIEs

### PR DESCRIPTION
**Pull request by hexylena**
tl;dr [Check out the new docs!](https://github.com/erasche/galaxy/blob/gie-docs/doc/source/admin/interactive_environments.rst)

I've added docs to the codebase itself as GIE changes are very closely tied to Galaxy releases. This PR includes:
- How GIEs work (@bgruening I used images from our Paper, this is OK yes?)
- How to deploy them and the admin side of GIEs (including things like upstream proxy configuration, symlinking nodejs->node)
- A full GIE "Hello World" development tutorial covering many of the aspects of building IEs.

cc @bgruening @remimarenco @jmchilton @scholtalbers

### CODE REVIEW

**Comment by remimarenco** [comment]
Love the work you put on this! Thank you guys!

**Comment by martenson** [comment]
:+2:

**Comment by jmchilton** [comment]
@erasche This is utterly fantastic and you put a great amount of effort into it, thanks! I have two small comments and feel terrible about that because this is such an improvement - feel free to say buzz off and I'll merge and open a new PR with these changes :smile_cat:.
1. Should we really call it admin documentation at this point when there is only one section? You mention the wiki but there is no link and you don't mention that a vast, vast majority of admin documentation exists there. So I would recommend making it even more explicit on that page that admin documentation is for the most part no in this code or better yet just rename the section and call it special topics. In this case, the docs include developer and not exclusively deployer information anyway so this is another reason to do this.
2. I think the example `.ini` has un-commented defaults - is that needed for that case or should it be moved into the code?

**Comment by hexylena** [comment]
@jmchilton no worries! Solid feedback.
1. I was calling it "admin" because I had a vision of what the Galaxy docs could be, and I'd like to contribute/explore that if possible. I would really love to see more documentation on how to deploy and maintain a Galaxy instance in some form included in the codebase.
   - That information is somewhat Galaxy version specific (e.g. universe_wsgi.ini)
   - It is basically required for deployment (and still tied to Galaxy versions. E.g. what dependencies are required, what versions of python are supported in this release, and all the other arguments for shipping a manual with your product)
   - Apache's default config serves docs to localhost, Galaxy could too! It would be really admin-friendly. Heck, we could even serve them to end users as well, for those who wanted to study the API. _We would get version specific API docs served that are appropriate to the Galaxy server the user wants to talk to._
2. Oh, good catch.
   - https://github.com/erasche/galaxy/blob/gie-docs/doc/source/admin/interactive_environments.rst#docker-on-another-host those are required non-defaults
   - https://github.com/erasche/galaxy/blob/gie-docs/doc/source/admin/interactive_environments.rst#first-steps-configuration good catch, there's definitely a default value that should be commented out there.

I'll update with some wiki links and a fix for the ini file.

**Comment by jmchilton** [comment]
@erasche Don't get me wrong I'm on board in the abstract - I'd much rather a huge portion of the deployment documentation in here for exactly the reasons you mentioned. But I don't want to have a multi-year period where things are in flux across three places (old wiki, new wiki, RTD - in addition to biostar, -dev, etc...). We already have a big project ongoing to move to a new wiki/CMS platform for the web stuff - I'd prefer to wait for that to be done and have a huge bulk of the core proxy documentation ready to go before declaring this section "Admin Documentation".

Thanks for the changes though, :+1:.

**Comment by hexylena** [comment]
@jmchilton agreed, the flux is bad.

So ... can we just not announce that this exists for a while? Or would you like a larger disclaimer/notice in the header of admin/index.rst?

**Comment by hexylena** [comment]
ping @jmchilton good to go?

**Comment by jmchilton** [comment]
Definitely, sorry this fell off the radar.

**Comment by hexylena** [comment]
thanks!

**Comment by hexylena** [comment]
http://galaxy.readthedocs.org/en/dev/index.html is not showing the "Admin Docs" menu.

**Comment by martenson** [comment]
@erasche that is because we trigger the build of docs manually, sadly (just triggered it)

**Comment by hexylena** [comment]
@martenson ah, okay. Thanks!

**Comment by martenson** [comment]
we tried with @nsoranzo to fix it but did not succeed; our account at @readthedocs might be bugged I am afraid

**Pull request merged**
