### PR TITLE
Prevent transient job state test failures from failing the build.

### PR DESCRIPTION
**Pull request by jmchilton**
A precondition to the real meat of the test is failing to be met sometimes in production - this failure is indicating a problem with the test and not with Galaxy. I previously tried to address this with https://github.com/galaxyproject/galaxy/pull/3988 but that didn't work. Now if the trainsient ok occurs the test will be skipped. Most of the time it won't skip and the rest of the test will execute and ensure there aren't regressions in behaviors related to cleaning up datasets after job completion. I'm placing the skips a couple different places so hopefully we can get a stack trace at some point - knowing where the code is when the job state is changing from running to ok will help puzzle out what is handing for the two minutes the job is running in the test framework.

### CODE REVIEW

**Comment by martenson** [comment]
`./lib/galaxy/datatypes/data.py:372:21: F841 local variable 'tmp_file_name' is assigned to but never used`

I think this is the fallout of the security patch fallout fix

**Comment by jmchilton** [comment]
#4515 should fix the build problems? Can we merge this in meantime?

**Comment by dannon** [comment]
So the test requires a job in the running state?  Should we instead have a dummy tool that always takes, for example, 5 seconds of sleep() time or something?

**Comment by jmchilton** [comment]
The tool it is using sleeps for 120 seconds - looking at the timing I think it is actually sleeping for 120 seconds also. I think that part is working as far as I can tell. Just something in the test is occasionally taking more than that - possibly something is blocking on the state of the job to change somehow?

**Comment by martenson** [comment]
Thanks @jmchilton for taking time to polish the test.

**Pull request merged**
